PlayRho: playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 > Class Template Reference
playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 > Class Template Reference
Shape Classes
A class template for compositing shaped part types eligible for use with classes like the playrho::d2::Shape class.
#include <playrho/d2/part/Compositor.hpp>
Related Functions
(Note that these are not member functions.)
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto GetChild (const Compositor< P1, P2, P3, P4, P5, P6 > &arg, ChildCounter index) noexcept(noexcept(arg.GetChild(index))) -> decltype(arg.GetChild(index))
Gets the "child" shape for the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
constexpr auto GetChildCount (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept -> decltype(arg.GetChildCount())
Gets the "child" count for the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
constexpr auto GetDensity (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept -> decltype(arg.density)
Gets the density of the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
constexpr auto GetDimensions (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept -> decltype(arg.GetDimensions())
Gets the rectangle's width and height dimensions.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
constexpr auto GetFilter (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept -> decltype(arg.filter)
Gets the filter of the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
constexpr auto GetFriction (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept -> decltype(arg.friction)
Gets the friction of the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto GetMassData (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept -> decltype(arg.GetMassData(GetDensity(arg)))
Gets the mass data for the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
constexpr auto GetOffset (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept -> decltype(arg.GetOffset())
Gets the rectangle's x and y offset.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
constexpr auto GetRestitution (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept -> decltype(arg.restitution)
Gets the restitution of the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
constexpr auto GetVertexRadius (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept(noexcept(arg.GetVertexRadius())) -> decltype(arg.GetVertexRadius())
Gets the vertex radius of the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto GetVertexRadius (const Compositor< P1, P2, P3, P4, P5, P6 > &arg, ChildCounter index) noexcept(noexcept(GetChild(arg, index))) -> decltype(GetVertexRadius(GetChild(arg, index)))
Gets the vertex radius of the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
constexpr auto IsSensor (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept -> decltype(arg.sensor)
Gets the is-sensor state of the given shape configuration.
template<class P11 , class P12 , class P13 , class P14 , class P15 , class P16 , class P21 , class P22 , class P23 , class P24 , class P25 , class P26 >
bool operator!= (const Compositor< P11, P12, P13, P14, P15, P16 > &lhs, const Compositor< P21, P22, P23, P24, P25, P26 > &rhs) noexcept
Inequality operator.
template<class P11 , class P12 , class P13 , class P14 , class P15 , class P16 , class P21 , class P22 , class P23 , class P24 , class P25 , class P26 >
bool operator== (const Compositor< P11, P12, P13, P14, P15, P16 > &lhs, const Compositor< P21, P22, P23, P24, P25, P26 > &rhs) noexcept
Equality operator.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto Rotate (Compositor< P1, P2, P3, P4, P5, P6 > &arg,::playrho::d2::UnitVec value) -> decltype(arg.Rotate(value))
Rotates the given compositor's vertices by the given value.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , std::size_t N>
auto Scale (Compositor< P1, P2, P3, P4, P5, P6 > &arg, const Vector< Real, N > &value) -> decltype(arg.Scale(value))
Scales the given compositor's vertices by the given value.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto SetDensity (Compositor< P1, P2, P3, P4, P5, P6 > &arg, NonNegative< AreaDensity > value) -> std::enable_if_t<!std::is_const_v< decltype(arg.density)>, void >
Density setter.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto SetDimensions (Compositor< P1, P2, P3, P4, P5, P6 > &arg, decltype(arg.GetDimensions()) value) -> decltype(arg.SetDimensions(value))
Sets the rectangle's width and height dimensions.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto SetFilter (Compositor< P1, P2, P3, P4, P5, P6 > &arg, Filter value) -> std::enable_if_t<!std::is_const_v< decltype(arg.filter)>, void >
Filter setter.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto SetFriction (Compositor< P1, P2, P3, P4, P5, P6 > &arg, NonNegative< Real > value) -> std::enable_if_t<!std::is_const_v< decltype(arg.friction)>, void >
Sets friction.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto SetOffset (Compositor< P1, P2, P3, P4, P5, P6 > &arg, decltype(arg.GetOffset()) value) -> decltype(arg.SetOffset(value))
Sets the rectangle's x and y offset.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto SetRestitution (Compositor< P1, P2, P3, P4, P5, P6 > &arg, Real value) -> std::enable_if_t<!std::is_const_v< decltype(arg.restitution)>, void >
Sets restitution.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto SetSensor (Compositor< P1, P2, P3, P4, P5, P6 > &arg, bool value) -> std::enable_if_t<!std::is_const_v< decltype(arg.sensor)>, void >
Sensor setter.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto SetVertexRadius (Compositor< P1, P2, P3, P4, P5, P6 > &arg, ChildCounter index, decltype(arg.GetVertexRadius()) value) -> decltype(arg.SetVertexRadius(index, value))
Gets the vertex radius of the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , std::size_t N>
auto Translate (Compositor< P1, P2, P3, P4, P5, P6 > &arg, const Vector< Length, N > &value) -> decltype(arg.Translate(value))
Translates the given compositor's vertices by the given value.
Detailed Description
template<class P1 = DefaultPolicyArgs, class P2 = DefaultPolicyArgs, class P3 = DefaultPolicyArgs, class P4 = DefaultPolicyArgs, class P5 = DefaultPolicyArgs, class P6 = DefaultPolicyArgs>
class playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >
A class template for compositing shaped part types eligible for use with classes like the playrho::d2::Shape class.
Note
This is a host class template that defines geometry, density, friction, restitution, filter, and sensor policies and that is setup to use default implementations of these per the DefaultPolicies class. Use any number of the six policy setter classes - GeometryIs, DensityIs, RestitutionIs, FrictionIs, SensorIs, FilterIs (as a named template class argument) - to override these defaults that you'd like to change.
// Here's an example use of this class for a defaulted, enitrely static, rectangular part...
auto comp0 = Compositor<>{};
// Here's an example use of this class for a fully runtime settable rectangular part...
auto comp1 = Compositor<GeometryIs<DynamicRectangle<>>, //
                        DensityIs<DynamicAreaDensity<>>, //
                        RestitutionIs<DynamicRestitution<>>, //
                        FrictionIs<DynamicFriction<>>, //
                        SensorIs<DynamicSensor<>>, //
                        FilterIs<DynamicFilter<>>>{};
See also
playrho::d2::Shape, DefaultPolicies, GeometryIs, DensityIs, FrictionIs, RestitutionIs, FilterIs, SensorIs.
https://en.wikipedia.org/wiki/Modern_C%2B%2B_Design#Policy-based_design
https://flylib.com/books/en/3.401.1.126/1/
Examples
WorldShape.cpp.
Friends And Related Function Documentation
GetChild()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto GetChild (const Compositor< P1, P2, P3, P4, P5, P6 > & arg, ChildCounter index) -> decltype(arg.GetChild(index)) related
Gets the "child" shape for the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::GetChild().
GetChildCount()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > constexpr auto GetChildCount (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.GetChildCount()) related
Gets the "child" count for the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::GetChildCount().
GetDensity()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > constexpr auto GetDensity (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.density) related
Gets the density of the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name.
GetDimensions()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > constexpr auto GetDimensions (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.GetDimensions()) related
Gets the rectangle's width and height dimensions.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name.
GetFilter()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > constexpr auto GetFilter (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.filter) related
Gets the filter of the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name.
GetFriction()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > constexpr auto GetFriction (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.friction) related
Gets the friction of the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name.
GetMassData()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto GetMassData (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.GetMassData(GetDensity(arg))) related
Gets the mass data for the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::GetMassData().
GetOffset()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > constexpr auto GetOffset (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.GetOffset()) related
Gets the rectangle's x and y offset.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::GetOffset().
GetRestitution()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > constexpr auto GetRestitution (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.restitution) related
Gets the restitution of the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name.
GetVertexRadius() [1/2]
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > constexpr auto GetVertexRadius (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.GetVertexRadius()) related
Gets the vertex radius of the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::GetVertexRadius().
GetVertexRadius() [2/2]
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto GetVertexRadius (const Compositor< P1, P2, P3, P4, P5, P6 > & arg, ChildCounter index) -> decltype(GetVertexRadius(GetChild(arg, index))) related
Gets the vertex radius of the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name.
IsSensor()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > constexpr auto IsSensor (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.sensor) related
Gets the is-sensor state of the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name.
Rotate()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto Rotate (Compositor< P1, P2, P3, P4, P5, P6 > & arg, ::playrho::d2::UnitVec value) -> decltype(arg.Rotate(value)) related
Rotates the given compositor's vertices by the given value.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name and accepting the given value.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::Rotate().
Scale()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , std::size_t N> auto Scale (Compositor< P1, P2, P3, P4, P5, P6 > & arg, const Vector< Real, N > & value) -> decltype(arg.Scale(value)) related
Scales the given compositor's vertices by the given value.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name and accepting the given value.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::Scale().
SetDensity()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto SetDensity (Compositor< P1, P2, P3, P4, P5, P6 > & arg, NonNegative< AreaDensity > value) -> std::enable_if_t<!std::is_const_v<decltype(arg.density)>, void> related
Density setter.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name and accepting the given value.
SetDimensions()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto SetDimensions (Compositor< P1, P2, P3, P4, P5, P6 > & arg, decltype(arg.GetDimensions()) value) -> decltype(arg.SetDimensions(value)) related
Sets the rectangle's width and height dimensions.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name and accepting the given value.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::SetDimensions().
SetFilter()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto SetFilter (Compositor< P1, P2, P3, P4, P5, P6 > & arg, Filter value) -> std::enable_if_t<!std::is_const_v<decltype(arg.filter)>, void> related
Filter setter.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name and accepting the given value.
SetFriction()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto SetFriction (Compositor< P1, P2, P3, P4, P5, P6 > & arg, NonNegative< Real > value) -> std::enable_if_t<!std::is_const_v<decltype(arg.friction)>, void> related
Sets friction.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name and accepting the given value.
SetOffset()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto SetOffset (Compositor< P1, P2, P3, P4, P5, P6 > & arg, decltype(arg.GetOffset()) value) -> decltype(arg.SetOffset(value)) related
Sets the rectangle's x and y offset.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name and accepting the given value.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::SetOffset().
SetRestitution()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto SetRestitution (Compositor< P1, P2, P3, P4, P5, P6 > & arg, Real value) -> std::enable_if_t<!std::is_const_v<decltype(arg.restitution)>, void> related
Sets restitution.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name and accepting the given value.
SetSensor()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto SetSensor (Compositor< P1, P2, P3, P4, P5, P6 > & arg, bool value) -> std::enable_if_t<!std::is_const_v<decltype(arg.sensor)>, void> related
Sensor setter.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name and accepting the given value.
SetVertexRadius()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto SetVertexRadius (Compositor< P1, P2, P3, P4, P5, P6 > & arg, ChildCounter index, decltype(arg.GetVertexRadius()) value) -> decltype(arg.SetVertexRadius(index, value)) related
Gets the vertex radius of the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name and accepting the given index and value.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::SetVertexRadius().
Translate()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , std::size_t N> auto Translate (Compositor< P1, P2, P3, P4, P5, P6 > & arg, const Vector< Length, N > & value) -> decltype(arg.Translate(value)) related
Translates the given compositor's vertices by the given value.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name and accepting the given value.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::Translate().
The documentation for this class was generated from the following file:
Library/include/playrho/d2/part/Compositor.hpp