PlayRho: playrho::GearJoint Class Reference
playrho::GearJoint Class Reference
Joint Classes
Gear joint.
#include <GearJoint.hpp>
Public Member Functions
GearJoint (const GearJointDef &data)
Initializing constructor.
void Accept (JointVisitor &visitor) const override
Accepts a visitor.
Length2D GetAnchorA () const override
Get the anchor point on bodyA in world coordinates.
Length2D GetAnchorB () const override
Get the anchor point on bodyB in world coordinates.
Momentum2D GetLinearReaction () const override
Get the linear reaction on bodyB at the joint anchor.
AngularMomentum GetAngularReaction () const override
Get the angular reaction on bodyB.
Length2D GetLocalAnchorA () const noexcept
Gets the local anchor point relative to bodyA's origin.
Length2D GetLocalAnchorB () const noexcept
Gets the local anchor point relative to bodyB's origin.
NonNull< Joint * > GetJoint1 () const noexcept
Gets the first joint.
NonNull< Joint * > GetJoint2 () const noexcept
Gets the second joint.
void SetRatio (Real ratio)
Sets the gear ratio.
Real GetRatio () const noexcept
Gets the ratio.
Public Member Functions inherited from playrho::Joint
Body * GetBodyA () const noexcept
Gets the first body attached to this joint.
Body * GetBodyB () const noexcept
Gets the second body attached to this joint.
void * GetUserData () const noexcept
Get the user data pointer.
void SetUserData (void *data) noexcept
Set the user data pointer.
bool GetCollideConnected () const noexcept
Gets collide connected.
virtual void ShiftOrigin (const Length2D newOrigin)
Shifts the origin for any points stored in world coordinates.
Private Member Functions
void InitVelocityConstraints (BodyConstraintsMap &bodies, const StepConf &step, const ConstraintSolverConf &conf) override
Initializes velocity constraint data based on the given solver data.
bool SolveVelocityConstraints (BodyConstraintsMap &bodies, const StepConf &step) override
Solves velocity constraint.
bool SolvePositionConstraints (BodyConstraintsMap &bodies, const ConstraintSolverConf &conf) const override
Solves the position constraint.
Private Attributes
NonNull< Joint * > m_joint1
Joint 1.
NonNull< Joint * > m_joint2
Joint 2.
JointType m_typeA
Type of joint 1.
JointType m_typeB
Type of joint 2.
Body * m_bodyC
Body C.
Body * m_bodyD
Body D.
Length2D m_localAnchorA
Local anchor A.
Length2D m_localAnchorB
Local anchor B.
Length2D m_localAnchorC
Local anchor C.
Length2D m_localAnchorD
Local anchor D.
UnitVec2 m_localAxisC
Local axis C.
UnitVec2 m_localAxisD
Local axis D.
Angle m_referenceAngleA
Reference angle A.
Angle m_referenceAngleB
Reference angle B.
Real m_constant
Constant.
Real m_ratio
Ratio.
Momentum m_impulse = Momentum{0}
Impulse.
Vec2 m_JvAC = Vec2_zero
AC Jv data.
Vec2 m_JvBD
BD Jv data.
Length m_JwA = Length{0}
A Jw data.
Length m_JwB
B Jw data.
Length m_JwC
C Jw data.
Length m_JwD
D Jw data.
Real m_mass
Either linear mass or angular mass.
Related Functions
(Note that these are not member functions.)
GearJointDef GetGearJointDef (const GearJoint &joint) noexcept
Gets the definition data for the given joint.
Related Functions inherited from playrho::Joint
bool IsEnabled (const Joint &j) noexcept
Short-cut function to determine if both bodies are enabled.
void SetAwake (Joint &j) noexcept
Wakes up the joined bodies.
JointCounter GetWorldIndex (const Joint *joint)
Gets the world index of the given joint.
JointType GetType (const Joint &joint) noexcept
Gets the type of the given joint.
Additional Inherited Members
Public Types inherited from playrho::Joint
enum LimitState { e_inactiveLimit, e_atLowerLimit, e_atUpperLimit, e_equalLimits }
Limit state.
Static Public Member Functions inherited from playrho::Joint
static bool IsOkay (const JointDef &def) noexcept
Is the given definition okay.
Protected Member Functions inherited from playrho::Joint
Joint (const JointDef &def)
Initializing constructor.
Detailed Description
Gear joint.
A gear joint is used to connect two joints together. Either joint can be a revolute or prismatic joint. You specify a gear ratio to bind the motions together: coordinate1 + ratio * coordinate2 = constant The ratio can be negative or positive. If one joint is a revolute joint and the other joint is a prismatic joint, then the ratio will have units of length or units of 1/length.
Warning
You have to manually destroy the gear joint if joint1 or joint2 is destroyed.
Member Function Documentation
void playrho::GearJoint::InitVelocityConstraints (BodyConstraintsMap & bodies, const StepConf & step, const ConstraintSolverConf & conf) override private virtual
Initializes velocity constraint data based on the given solver data.
Note
This MUST be called prior to calling SolveVelocityConstraints.
See also
SolveVelocityConstraints.
Implements playrho::Joint.
Referenced by GetJoint2().
bool playrho::GearJoint::SolvePositionConstraints (BodyConstraintsMap & bodies, const ConstraintSolverConf & conf) const override private virtual
Solves the position constraint.
Returns
true if the position errors are within tolerance.
Implements playrho::Joint.
Referenced by GetJoint2().
bool playrho::GearJoint::SolveVelocityConstraints (BodyConstraintsMap & bodies, const StepConf & step) override private virtual
Solves velocity constraint.
Precondition
InitVelocityConstraints has been called.
See also
InitVelocityConstraints.
Returns
true if velocity is "solved", false otherwise.
Implements playrho::Joint.
Referenced by GetJoint2().
Friends And Related Function Documentation
GearJointDef GetGearJointDef (const GearJoint & joint) related
Gets the definition data for the given joint.
The documentation for this class was generated from the following files:
GearJoint.hpp
GearJoint.cpp
GearJointDef.hpp