PlayRho: playrho::Body2D Class Reference
playrho::Body2D Class Reference
Physical Entity Classes
Physical entity that exists within a World.
#include <Body.hpp>
Public Types
enum Flag : FlagsType {
e_islandFlag = FlagsType(0x0001), e_awakeFlag = FlagsType(0x0002), e_autoSleepFlag = FlagsType(0x0004), e_impenetrableFlag = FlagsType(0x0008),
e_fixedRotationFlag = FlagsType(0x0010), e_enabledFlag = FlagsType(0x0020), e_velocityFlag = FlagsType(0x0080), e_accelerationFlag = FlagsType(0x0100),
e_massDataDirtyFlag = FlagsType(0x0200)
}
Flag enumeration.
using Fixtures = std::vector< Fixture2D * >
Container type for fixtures.
using KeyedJointPtr = std::pair< Body2D *, Joint2D * >
Keyed joint pointer.
using Joints = std::vector< KeyedJointPtr >
Container type for joints.
using Contacts = std::vector< KeyedContactPtr >
Container type for contacts.
using FlagsType = std::uint16_t
Flags type.
Public Member Functions
Body2D (World2D *world, const BodyDef &bd)
Initializing constructor for unit testing purposes.
Fixture2D * CreateFixture (const Shape2D &shape, const FixtureDef &def=GetDefaultFixtureDef(), bool resetMassData=true)
Creates a fixture and attaches it to this body.
bool DestroyFixture (Fixture2D *fixture, bool resetMassData=true)
Destroys a fixture.
void DestroyFixtures ()
Destroy fixtures.
void SetTransform (Length2 location, Angle angle)
Sets the position of the body's origin and rotation.
Transformation2D GetTransformation () const noexcept
Gets the body transform for the body's origin.
Length2 GetLocation () const noexcept
Gets the world body origin location.
const Sweep2D & GetSweep () const noexcept
Gets the body's sweep.
Angle GetAngle () const noexcept
Get the angle.
Length2 GetWorldCenter () const noexcept
Get the world position of the center of mass.
Length2 GetLocalCenter () const noexcept
Gets the local position of the center of mass.
Velocity2D GetVelocity () const noexcept
Gets the velocity.
void SetVelocity (const Velocity2D &velocity) noexcept
Sets the body's velocity (linear and angular velocity).
void SetAcceleration (LinearAcceleration2 linear, AngularAcceleration angular) noexcept
Sets the linear and rotational accelerations on this body.
LinearAcceleration2 GetLinearAcceleration () const noexcept
Gets this body's linear acceleration.
AngularAcceleration GetAngularAcceleration () const noexcept
Gets this body's angular acceleration.
InvMass GetInvMass () const noexcept
Gets the inverse total mass of the body.
InvRotInertia GetInvRotInertia () const noexcept
Gets the inverse rotational inertia of the body.
void SetMassData (const MassData2D &massData)
Set the mass properties to override the mass properties of the fixtures.
void ResetMassData ()
Resets the mass data properties.
Frequency GetLinearDamping () const noexcept
Gets the linear damping of the body.
void SetLinearDamping (NonNegative< Frequency > linearDamping) noexcept
Sets the linear damping of the body.
Frequency GetAngularDamping () const noexcept
Gets the angular damping of the body.
void SetAngularDamping (NonNegative< Frequency > angularDamping) noexcept
Sets the angular damping of the body.
void SetType (BodyType type)
Sets the type of this body.
BodyType GetType () const noexcept
Gets the type of this body.
bool IsSpeedable () const noexcept
Is "speedable".
bool IsAccelerable () const noexcept
Is "accelerable".
void SetBullet (bool flag) noexcept
Sets the bullet status of this body.
bool IsImpenetrable () const noexcept
Is this body treated like a bullet for continuous collision detection?
void SetSleepingAllowed (bool flag) noexcept
You can disable sleeping on this body. If you disable sleeping, the body will be woken.
bool IsSleepingAllowed () const noexcept
Gets whether or not this body allowed to sleep.
void SetAwake () noexcept
Awakens this body.
void UnsetAwake () noexcept
Sets this body to asleep if sleeping is allowed.
bool IsAwake () const noexcept
Gets the awake/asleep state of this body.
Time GetUnderActiveTime () const noexcept
Gets this body's under-active time value.
void SetUnderActiveTime (Time value) noexcept
Sets the "under-active" time to the given value.
void ResetUnderActiveTime () noexcept
Resets the under-active time for this body.
void SetEnabled (bool flag)
Sets the enabled state of the body.
bool IsEnabled () const noexcept
Gets the enabled/disabled state of the body.
void SetFixedRotation (bool flag)
Sets this body to have fixed rotation.
bool IsFixedRotation () const noexcept
Does this body have fixed rotation?
SizedRange< Fixtures::const_iterator > GetFixtures () const noexcept
Gets the range of all constant fixtures attached to this body.
SizedRange< Fixtures::iterator > GetFixtures () noexcept
Gets the range of all fixtures attached to this body.
SizedRange< Joints::const_iterator > GetJoints () const noexcept
Gets the range of all joints attached to this body.
SizedRange< Joints::iterator > GetJoints () noexcept
Gets the range of all joints attached to this body.
SizedRange< Contacts::const_iterator > GetContacts () const noexcept
Gets the container of all contacts attached to this body.
void * GetUserData () const noexcept
Gets the user data pointer that was provided in the body definition.
void SetUserData (void *data) noexcept
Sets the user data. Use this to store your application specific data.
World2D * GetWorld () const noexcept
Gets the parent world of this body.
bool IsMassDataDirty () const noexcept
Gets whether the mass data for this body is "dirty".
Static Public Member Functions
static FlagsType GetFlags (BodyType type) noexcept
Gets the flags for the given value.
static FlagsType GetFlags (const BodyDef &bd) noexcept
Gets the flags for the given value.
Static Public Attributes
static PLAYRHO_CONSTEXPR const auto InvalidIslandIndex = static_cast<BodyCounter>(-1)
Invalid island index.
Private Member Functions
bool IsIslanded () const noexcept
Whether this body is in is-islanded state.
void SetIslandedFlag () noexcept
Sets this body to the is-islanded state.
void UnsetIslandedFlag () noexcept
Unsets this body to the is-islanded state.
void SetAwakeFlag () noexcept
Sets the body's awake flag.
void UnsetAwakeFlag () noexcept
Unsets the body's awake flag.
void Advance (Real alpha) noexcept
Advances the body by a given time ratio.
void SetMassDataDirty () noexcept
Sets this body to have the mass data dirty state.
void UnsetMassDataDirty () noexcept
Unsets the body from being in the mass data dirty state.
void SetEnabledFlag () noexcept
Sets the enabled flag.
void UnsetEnabledFlag () noexcept
Unsets the enabled flag.
bool Insert (ContactKey key, Contact2D *contact)
Inserts the given key and contact.
bool Insert (Joint2D *joint)
Inserts the given joint into this body's joints list.
bool Erase (const Contact2D *contact)
Erases the given contact from this body's contacts list.
bool Erase (const Joint2D *joint)
Erases the given joint from this body's joints list.
void ClearContacts ()
Clears this body's contacts list.
void ClearJoints ()
Clears this body's joints list.
void SetTransformation (Transformation2D value) noexcept
Sets the transformation for this body.
Private Attributes
Transformation2D m_xf
Transformation for body origin.
Sweep2D m_sweep
Sweep motion for CCD. 36-bytes.
Velocity2D m_velocity
Velocity (linear and angular). 12-bytes.
FlagsType m_flags = 0
Flags. 2-bytes.
LinearAcceleration2 m_linearAcceleration = LinearAcceleration2{}
Linear acceleration.
World2D *const m_world
World to which this body belongs. 8-bytes.
void * m_userData
User data. 8-bytes.
Fixtures m_fixtures
Container of fixtures.
Contacts m_contacts
Container of contacts (owned by world).
Joints m_joints
Container of joints (owned by world).
AngularAcceleration m_angularAcceleration = AngularAcceleration{0}
Angular acceleration.
InvMass m_invMass = 0
Inverse mass of the body.
InvRotInertia m_invRotI = 0
Inverse rotational inertia about the center of mass.
NonNegative< Frequency > m_linearDamping
Linear damping. 4-bytes.
NonNegative< Frequency > m_angularDamping
Angular damping. 4-bytes.
Time m_underActiveTime = 0
Under-active time.
Friends
class BodyAtty
Related Functions
(Note that these are not member functions.)
AABB2D ComputeAABB (const Body2D &body)
Computes the AABB for the given body.
MassData2D ComputeMassData (const Body2D &body) noexcept
Computes the body's mass data.
MassData2D GetMassData (const Body2D &body) noexcept
Gets the mass data of the body.
Acceleration2D GetAcceleration (const Body2D &body) noexcept
Gets the given body's acceleration.
void SetAcceleration (Body2D &body, Acceleration2D value) noexcept
Sets the accelerations on the given body.
Acceleration2D CalcGravitationalAcceleration (const Body2D &body) noexcept
Calculates the gravitationally associated acceleration for the given body within its world.
bool Awaken (Body2D &body) noexcept
Awakens the body if it's asleep.
bool Unawaken (Body2D &body) noexcept
Puts the body to sleep if it's awake.
Position2D GetPosition1 (const Body2D &body) noexcept
Gets the "position 1" Position information for the given body.
Mass GetMass (const Body2D &body) noexcept
Gets the total mass of the body.
void SetLinearAcceleration (Body2D &body, LinearAcceleration2 value) noexcept
Sets the given linear acceleration of the given body.
void SetAngularAcceleration (Body2D &body, AngularAcceleration value) noexcept
Sets the given angular acceleration of the given body.
void ApplyLinearAcceleration (Body2D &body, LinearAcceleration2 amount)
Applies the given linear acceleration to the given body.
void SetForce (Body2D &body, Force2 force, Length2 point) noexcept
Sets the given amount of force at the given point to the given body.
void ApplyForce (Body2D &body, Force2 force, Length2 point) noexcept
Apply a force at a world point.
void ApplyForceToCenter (Body2D &body, Force2 force) noexcept
Apply a force to the center of mass.
void SetTorque (Body2D &body, Torque torque) noexcept
Sets the given amount of torque to the given body.
void ApplyTorque (Body2D &body, Torque torque) noexcept
Applies a torque.
void ApplyLinearImpulse (Body2D &body, Momentum2 impulse, Length2 point) noexcept
Applies an impulse at a point.
void ApplyAngularImpulse (Body2D &body, AngularMomentum impulse) noexcept
Applies an angular impulse.
Force2 GetCentripetalForce (const Body2D &body, Length2 axis)
Gets the centripetal force necessary to put the body into an orbit having the given radius.
RotInertia GetRotInertia (const Body2D &body) noexcept
Gets the rotational inertia of the body.
RotInertia GetLocalRotInertia (const Body2D &body) noexcept
Gets the rotational inertia of the body about the local origin.
LinearVelocity2 GetLinearVelocity (const Body2D &body) noexcept
Gets the linear velocity of the center of mass.
AngularVelocity GetAngularVelocity (const Body2D &body) noexcept
Gets the angular velocity.
void SetLinearVelocity (Body2D &body, const LinearVelocity2 v) noexcept
Sets the linear velocity of the center of mass.
void SetAngularVelocity (Body2D &body, AngularVelocity omega) noexcept
Sets the angular velocity.
Length2 GetWorldPoint (const Body2D &body, const Length2 localPoint) noexcept
Gets the world coordinates of a point given in coordinates relative to the body's origin.
Length2 GetWorldVector (const Body2D &body, const Length2 localVector) noexcept
Gets the world coordinates of a vector given the local coordinates.
UnitVec2 GetWorldVector (const Body2D &body, const UnitVec2 localVector) noexcept
Gets the world vector for the given local vector from the given body's transformation.
Length2 GetLocalPoint (const Body2D &body, const Length2 worldPoint) noexcept
Gets a local point relative to the body's origin given a world point.
UnitVec2 GetLocalVector (const Body2D &body, const UnitVec2 uv) noexcept
Gets a locally oriented unit vector given a world oriented unit vector.
LinearVelocity2 GetLinearVelocityFromWorldPoint (const Body2D &body, const Length2 worldPoint) noexcept
Gets the linear velocity from a world point attached to this body.
LinearVelocity2 GetLinearVelocityFromLocalPoint (const Body2D &body, const Length2 localPoint) noexcept
Gets the linear velocity from a local point.
Force2 GetForce (const Body2D &body) noexcept
Gets the net force that the given body is currently experiencing.
Torque GetTorque (const Body2D &body) noexcept
Gets the net torque that the given body is currently experiencing.
Velocity2D GetVelocity (const Body2D &body, Time h, MovementConf conf) noexcept
Gets the velocity of the body after the given time accounting for the body's acceleration and capped by the given configuration.
BodyCounter GetWorldIndex (const Body2D *body) noexcept
Gets the world index for the given body.
std::size_t GetFixtureCount (const Body2D &body) noexcept
Gets the fixture count of the given body.
void RotateAboutWorldPoint (Body2D &body, Angle amount, Length2 worldPoint)
Rotates a body a given amount around a point in world coordinates.
void RotateAboutLocalPoint (Body2D &body, Angle amount, Length2 localPoint)
Rotates a body a given amount around a point in body local coordinates.
Length2 GetLocation (const Body2D &body) noexcept
Gets the body's origin location.
Angle GetAngle (const Body2D &body) noexcept
Gets the body's angle.
void SetLocation (Body2D &body, Length2 value) noexcept
Sets the body's location.
void SetAngle (Body2D &body, Angle value) noexcept
Sets the body's angular orientation.
BodyDef GetBodyDef (const Body2D &body) noexcept
Gets the body definition for the given body.
Detailed Description
Physical entity that exists within a World.
A rigid body entity created or destroyed through a World instance. These have physical properties like: position, velocity, acceleration, and mass.
Invariant
Only bodies that allow sleeping, can be put to sleep.
Only "speedable" bodies can be awake.
Only "speedable" bodies can have non-zero velocities.
Only "accelerable" bodies can have non-zero accelerations.
Only "accelerable" bodies can have non-zero "under-active" times.
Note
Create these using the World2D::Create method.
From a memory management perspective, bodies own Fixture instances.
On a 64-bit architecture with 4-byte Real, this data structure is at least 192-bytes large.
See also
World2D, Fixture2D
Member Typedef Documentation
FlagsType
using playrho::Body2D::FlagsType = std::uint16_t
Flags type.
Note
For internal use. Made public to facilitate unit testing.
Member Enumeration Documentation
Flag
enum playrho::Body2D::Flag : FlagsType
Flag enumeration.
Note
For internal use. Made public to facilitate unit testing.
Enumerator
e_islandFlag
Island flag.
e_awakeFlag
Awake flag.
e_autoSleepFlag
Auto sleep flag.
e_impenetrableFlag
Impenetrable flag.
Indicates whether CCD should be done for this body. All static and kinematic bodies have this flag enabled.
e_fixedRotationFlag
Fixed rotation flag.
e_enabledFlag
Enabled flag.
e_velocityFlag
Velocity flag.
Set this to enable changes in position due to velocity. Bodies with this set are "speedable" - either kinematic or dynamic bodies.
e_accelerationFlag
Acceleration flag.
Set this to enable changes in velocity due to physical properties (like forces). Bodies with this set are "accelerable" - dynamic bodies.
e_massDataDirtyFlag
Mass Data Dirty Flag.
Constructor & Destructor Documentation
Body2D()
playrho::Body2D::Body2D (World2D * world, const BodyDef & bd)
Initializing constructor for unit testing purposes.
Note
This is not meant to be called directly by users of the library API. Call a world instance's CreateBody method instead.
Member Function Documentation
Advance()
void playrho::Body2D::Advance (Real alpha) inline private noexcept
Advances the body by a given time ratio.
This method:
advances the body's sweep to the given time ratio;
updates the body's sweep positions (linear and angular) to the advanced ones; and
updates the body's transform to the new sweep one settings.
Parameters
alpha Valid new time factor in [0,1) to advance the sweep to.
Referenced by playrho::BodyAtty::Advance().
CreateFixture()
Fixture2D * playrho::Body2D::CreateFixture (const Shape2D & shape, const FixtureDef & def = GetDefaultFixtureDef(), bool resetMassData = true)
Creates a fixture and attaches it to this body.
Parameters
shape Sharable shape definition. Its vertex radius must be less than the minimum or more than the maximum allowed by the body's world.
def Initial fixture settings. Friction and density must be >= 0. Restitution must be > -infinity and < infinity.
resetMassData Whether or not to reset the mass data of the body.
Note
This function should not be called if the world is locked.
Warning
This function is locked during callbacks.
Returns
Pointer to the created fixture.
Exceptions
WrongState if called while the world is "locked".
InvalidArgument if called without a shape.
InvalidArgument if called for a shape with a vertex radius less than the minimum vertex radius.
InvalidArgument if called for a shape with a vertex radius greater than the maximum vertex radius.
See also
Physical Entity Classes
DestroyFixture()
bool playrho::Body2D::DestroyFixture (Fixture2D * fixture, bool resetMassData = true)
Destroys a fixture.
This removes the fixture from the broad-phase and destroys all contacts associated with this fixture. All fixtures attached to a body are implicitly destroyed when the body is destroyed.
Warning
This function is locked during callbacks.
Note
Make sure to explicitly call ResetMassData after fixtures have been destroyed.
See also
ResetMassData.
Parameters
fixture the fixture to be removed.
resetMassData Whether or not to reset the mass data.
See also
Physical Entity Classes
Referenced by DestroyFixtures().
DestroyFixtures()
void playrho::Body2D::DestroyFixtures ()
Destroy fixtures.
See also
Physical Entity Classes
GetAngle()
Angle playrho::Body2D::GetAngle () const inline noexcept
Get the angle.
Returns
the current world rotation angle.
Referenced by playrho::Dump(), playrho::GearJoint::GearJoint(), playrho::GetJointAngle(), ResetMassData(), and SetMassData().
GetContacts()
SizedRange< Body2D::Contacts::const_iterator > playrho::Body2D::GetContacts () const inline noexcept
Gets the container of all contacts attached to this body.
Warning
This collection changes during the time step and you may miss some collisions if you don't use ContactListener2D.
Referenced by playrho::World2D::AddContactsToIsland(), playrho::World2D::ProcessContactsForTOI(), and playrho::World2D::ResetContactsForSolveTOI().
GetInvMass()
InvMass playrho::Body2D::GetInvMass () const inline noexcept
Gets the inverse total mass of the body.
This is the cached result of dividing 1 by the body's mass. Often floating division is much slower than multiplication. As such, it's likely faster to multiply values by this inverse value than to redivide them all the time by the mass.
Returns
Value of zero or more representing the body's inverse mass (in 1/kg).
See also
SetMassData.
GetInvRotInertia()
InvRotInertia playrho::Body2D::GetInvRotInertia () const inline noexcept
Gets the inverse rotational inertia of the body.
This is the cached result of dividing 1 by the body's rotational inertia. Often floating division is much slower than multiplication. As such, it's likely faster to multiply values by this inverse value than to redivide them all the time by the rotational inertia.
Returns
Inverse rotational inertia (in 1/kg-m^2).
GetLocation()
Length2 playrho::Body2D::GetLocation () const inline noexcept
Gets the world body origin location.
This is the location of the body's origin relative to its world. The location of the body after stepping the world's physics simulations is dependent on a number of factors:
Location at the last time step.
Forces acting on the body (gravity, applied force, applied impulse).
The mass data of the body.
Damping of the body.
Restitution and friction values of the body's fixtures when they experience collisions.
Returns
World location of the body's origin.
See also
GetTransformation.
Referenced by playrho::Dump(), playrho::MotorJoint::GetAnchorA(), playrho::MotorJoint::GetAnchorB(), playrho::GetCentripetalForce(), and ResetMassData().
GetTransformation()
Transformation2D playrho::Body2D::GetTransformation () const inline noexcept
Gets the body transform for the body's origin.
Returns
the world transform of the body's origin.
See also
GetLocation.
Referenced by playrho::ComputeAABB(), playrho::GearJoint::GearJoint(), GetLocation(), ResetMassData(), playrho::RotateAboutWorldPoint(), SetMassData(), playrho::World2D::SetType(), and playrho::World2D::SynchronizeProxies().
GetUnderActiveTime()
Time playrho::Body2D::GetUnderActiveTime () const inline noexcept
Gets this body's under-active time value.
Returns
Zero or more time in seconds (of step time) that this body has been "under-active" for.
IsAccelerable()
bool playrho::Body2D::IsAccelerable () const inline noexcept
Is "accelerable".
Indicates whether this body is accelerable, ie. whether it is effected by forces. Only Dynamic bodies are accelerable.
Returns
true if the body is accelerable, false otherwise.
Referenced by playrho::World2D::ProcessContactsForTOI(), ResetMassData(), SetMassData(), and playrho::World2D::SetType().
IsAwake()
bool playrho::Body2D::IsAwake () const inline noexcept
Gets the awake/asleep state of this body.
Warning
Being awake may or may not imply being speedable.
Returns
true if the body is awake.
Referenced by playrho::World2D::AddToIsland(), and playrho::Dump().
IsSpeedable()
bool playrho::Body2D::IsSpeedable () const inline noexcept
Is "speedable".
Is this body able to have a non-zero speed associated with it. Kinematic and Dynamic bodies are speedable. Static bodies are not.
Referenced by playrho::World2D::AddToIsland(), playrho::BodyAtty::Advance0(), playrho::World2D::RemoveUnspeedablesFromIslanded(), SetAwake(), SetAwakeFlag(), playrho::BodyAtty::SetPosition0(), playrho::BodyAtty::SetPosition1(), playrho::BodyAtty::SetSweep(), UnsetAwake(), and UnsetAwakeFlag().
ResetMassData()
void playrho::Body2D::ResetMassData ()
Resets the mass data properties.
This resets the mass data to the sum of the mass properties of the fixtures.
Note
This method must be called after calling CreateFixture to update the body mass data properties unless SetMassData is used.
See also
SetMassData.
Referenced by playrho::World2D::CreateFixture(), DestroyFixtures(), SetFixedRotation(), and playrho::World2D::SetType().
ResetUnderActiveTime()
void playrho::Body2D::ResetUnderActiveTime () inline noexcept
Resets the under-active time for this body.
Note
This has performance degrading potential and is best not called unless the caller is certain that it should be.
Referenced by SetAwake().
SetAcceleration()
void playrho::Body2D::SetAcceleration (LinearAcceleration2 linear, AngularAcceleration angular) noexcept
Sets the linear and rotational accelerations on this body.
Note
This has no effect on non-accelerable bodies.
A non-zero acceleration will also awaken the body.
Parameters
linear Linear acceleration.
angular Angular acceleration.
Referenced by playrho::World2D::SetType().
SetAwake()
void playrho::Body2D::SetAwake () inline noexcept
Awakens this body.
Sets this body to awake and resets its under-active time if it's a "speedable" body. This method has no effect otherwise.
Postcondition
If this body is a "speedable" body, then this body's IsAwake method returns true.
If this body is a "speedable" body, then this body's GetUnderActiveTime method returns zero.
Referenced by playrho::RevoluteJoint::EnableLimit(), playrho::PrismaticJoint::EnableLimit(), playrho::WheelJoint::EnableMotor(), playrho::RevoluteJoint::EnableMotor(), playrho::PrismaticJoint::EnableMotor(), playrho::World2D::InternalDestroy(), playrho::MotorJoint::SetAngularOffset(), playrho::RevoluteJoint::SetLimits(), playrho::PrismaticJoint::SetLimits(), playrho::MotorJoint::SetLinearOffset(), playrho::PrismaticJoint::SetMaxMotorForce(), playrho::WheelJoint::SetMaxMotorTorque(), playrho::RevoluteJoint::SetMaxMotorTorque(), playrho::WheelJoint::SetMotorSpeed(), playrho::RevoluteJoint::SetMotorSpeed(), playrho::PrismaticJoint::SetMotorSpeed(), playrho::MouseJoint::SetTarget(), and playrho::World2D::SetType().
SetAwakeFlag()
void playrho::Body2D::SetAwakeFlag () inline private noexcept
Sets the body's awake flag.
This is done unconditionally.
Note
This should not be called unless the body is "speedable".
Warning
Behavior is undefined if called for a body that is not "speedable".
Referenced by SetAwake(), and playrho::BodyAtty::SetAwakeFlag().
SetBullet()
void playrho::Body2D::SetBullet (bool flag) inline noexcept
Sets the bullet status of this body.
Sets whether or not this body should be treated like a bullet for continuous collision detection.
SetEnabled()
void playrho::Body2D::SetEnabled (bool flag)
Sets the enabled state of the body.
A disabled body is not simulated and cannot be collided with or woken up. If you pass a flag of true, all fixtures will be added to the broad-phase. If you pass a flag of false, all fixtures will be removed from the broad-phase and all contacts will be destroyed. Fixtures and joints are otherwise unaffected.
Note
A disabled body is still owned by a World object and remains in the world's body container.
You may continue to create/destroy fixtures and joints on disabled bodies.
Fixtures on a disabled body are implicitly disabled and will not participate in collisions, ray-casts, or queries.
Joints connected to a disabled body are implicitly disabled.
SetFixedRotation()
void playrho::Body2D::SetFixedRotation (bool flag)
Sets this body to have fixed rotation.
Note
This causes the mass to be reset.
SetMassData()
void playrho::Body2D::SetMassData (const MassData2D & massData)
Set the mass properties to override the mass properties of the fixtures.
Note
This changes the center of mass position.
Creating or destroying fixtures can also alter the mass.
This function has no effect if the body isn't dynamic.
Parameters
massData the mass properties.
SetTransform()
void playrho::Body2D::SetTransform (Length2 location, Angle angle)
Sets the position of the body's origin and rotation.
This instantly adjusts the body to be at the new position and new orientation.
Warning
Manipulating a body's transform can cause non-physical behavior!
Note
Contacts are updated on the next call to World2D::Step.
Parameters
location Valid world location of the body's local origin. Behavior is undefined if value is invalid.
angle Valid world rotation. Behavior is undefined if value is invalid.
Referenced by playrho::RotateAboutWorldPoint().
SetTransformation()
void playrho::Body2D::SetTransformation (Transformation2D value) private noexcept
Sets the transformation for this body.
If value is different than the current transformation, then this method updates the current transformation and flags each associated contact for updating.
Warning
Behavior is undefined if value is invalid.
Referenced by SetTransform(), and playrho::BodyAtty::SetTransformation().
SetType()
void playrho::Body2D::SetType (BodyType type)
Sets the type of this body.
Note
This may alter the mass and velocity.
SetUnderActiveTime()
void playrho::Body2D::SetUnderActiveTime (Time value) inline noexcept
Sets the "under-active" time to the given value.
Sets the "under-active" time to a value of zero or a non-zero value if the body is "accelerable". Otherwise it does nothing.
Warning
Behavior is undefined for negative values.
Note
A non-zero time is only valid for an "accelerable" body.
SetVelocity()
void playrho::Body2D::SetVelocity (const Velocity2D & velocity) noexcept
Sets the body's velocity (linear and angular velocity).
Note
This method does nothing if this body is not speedable.
A non-zero velocity will awaken this body.
See also
SetAwake, SetUnderActiveTime.
UnsetAwake()
void playrho::Body2D::UnsetAwake () inline noexcept
Sets this body to asleep if sleeping is allowed.
If this body is allowed to sleep, this: sets the sleep state of the body to asleep, resets this body's under active time, and resets this body's velocity (linear and angular).
Postcondition
This body's IsAwake method returns false.
This body's GetUnderActiveTime method returns zero.
This body's GetVelocity method returns zero linear and zero angular speed.
Friends And Related Function Documentation
ApplyAngularImpulse()
void ApplyAngularImpulse (Body2D & body, AngularMomentum impulse) related
Applies an angular impulse.
Parameters
body Body to apply the angular impulse to.
impulse Angular impulse to be applied.
ApplyForce()
void ApplyForce (Body2D & body, Force2 force, Length2 point) related
Apply a force at a world point.
Note
If the force is not applied at the center of mass, it will generate a torque and affect the angular velocity.
Non-zero forces wakes up the body.
Parameters
body Body to apply the force to.
force World force vector.
point World position of the point of application.
ApplyForceToCenter()
void ApplyForceToCenter (Body2D & body, Force2 force) related
Apply a force to the center of mass.
Note
Non-zero forces wakes up the body.
Parameters
body Body to apply the force to.
force World force vector.
ApplyLinearAcceleration()
void ApplyLinearAcceleration (Body2D & body, LinearAcceleration2 amount) related
Applies the given linear acceleration to the given body.
ApplyLinearImpulse()
void ApplyLinearImpulse (Body2D & body, Momentum2 impulse, Length2 point) related
Applies an impulse at a point.
Note
This immediately modifies the velocity.
This also modifies the angular velocity if the point of application is not at the center of mass.
Non-zero impulses wakes up the body.
Parameters
body Body to apply the impulse to.
impulse the world impulse vector.
point the world position of the point of application.
ApplyTorque()
void ApplyTorque (Body2D & body, Torque torque) related
Applies a torque.
Note
This affects the angular velocity without affecting the linear velocity of the center of mass.
Non-zero forces wakes up the body.
Parameters
body Body to apply the torque to.
torque about the z-axis (out of the screen).
Awaken()
bool Awaken (Body2D & body) related
Awakens the body if it's asleep.
CalcGravitationalAcceleration()
Acceleration2D CalcGravitationalAcceleration (const Body2D & body) related
Calculates the gravitationally associated acceleration for the given body within its world.
Returns
Zero acceleration if given body is has no mass, else the acceleration of the body due to the gravitational attraction to the other bodies.
ComputeAABB()
AABB2D ComputeAABB (const Body2D & body) related
Computes the AABB for the given body.
ComputeMassData()
MassData2D ComputeMassData (const Body2D & body) related
Computes the body's mass data.
This basically accumulates the mass data over all fixtures.
Note
The center is the mass weighted sum of all fixture centers. Divide it by the mass to get the averaged center.
Returns
accumulated mass data for all fixtures associated with the given body.
Referenced by ResetMassData().
GetAcceleration()
Acceleration2D GetAcceleration (const Body2D & body) related
Gets the given body's acceleration.
Parameters
body Body whose acceleration should be returned.
GetAngle()
Angle GetAngle (const Body2D & body) related
Gets the body's angle.
Returns
Body's angle relative to its World.
GetAngularVelocity()
AngularVelocity GetAngularVelocity (const Body2D & body) related
Gets the angular velocity.
Parameters
body Body to get the angular velocity for.
Returns
the angular velocity.
GetBodyDef()
BodyDef GetBodyDef (const Body2D & body) related
Gets the body definition for the given body.
Parameters
body Body to get the BodyDef for.
GetCentripetalForce()
Force2 GetCentripetalForce (const Body2D & body, Length2 axis) related
Gets the centripetal force necessary to put the body into an orbit having the given radius.
GetFixtureCount()
std::size_t GetFixtureCount (const Body2D & body) related
Gets the fixture count of the given body.
GetForce()
Force2 GetForce (const Body2D & body) related
Gets the net force that the given body is currently experiencing.
GetLinearVelocity()
LinearVelocity2 GetLinearVelocity (const Body2D & body) related
Gets the linear velocity of the center of mass.
Parameters
body Body to get the linear velocity for.
Returns
the linear velocity of the center of mass.
GetLinearVelocityFromLocalPoint()
LinearVelocity2 GetLinearVelocityFromLocalPoint (const Body2D & body, const Length2 localPoint) related
Gets the linear velocity from a local point.
Parameters
body Body to get the linear velocity for.
localPoint point in local coordinates.
Returns
the world velocity of a point.
GetLinearVelocityFromWorldPoint()
LinearVelocity2 GetLinearVelocityFromWorldPoint (const Body2D & body, const Length2 worldPoint) related
Gets the linear velocity from a world point attached to this body.
Parameters
body Body to get the linear velocity for.
worldPoint point in world coordinates.
Returns
the world velocity of a point.
GetLocalPoint()
Length2 GetLocalPoint (const Body2D & body, const Length2 worldPoint) related
Gets a local point relative to the body's origin given a world point.
Parameters
body Body that the returned point should be relative to.
worldPoint point in world coordinates.
Returns
the corresponding local point relative to the body's origin.
GetLocalRotInertia()
RotInertia GetLocalRotInertia (const Body2D & body) related
Gets the rotational inertia of the body about the local origin.
Returns
the rotational inertia.
GetLocalVector()
UnitVec2 GetLocalVector (const Body2D & body, const UnitVec2 uv) related
Gets a locally oriented unit vector given a world oriented unit vector.
Parameters
body Body that the returned vector should be relative to.
uv Unit vector in world orientation.
Returns
the corresponding local vector.
GetLocation()
Length2 GetLocation (const Body2D & body) related
Gets the body's origin location.
This is the location of the body's origin relative to its world. The location of the body after stepping the world's physics simulations is dependent on a number of factors:
Location at the last time step.
Forces acting on the body (gravity, applied force, applied impulse).
The mass data of the body.
Damping of the body.
Restitution and friction values of the body's fixtures when they experience collisions.
Returns
World location of the body's origin.
See also
GetAngle.
GetMass()
Mass GetMass (const Body2D & body) related
Gets the total mass of the body.
Returns
Value of zero or more representing the body's mass (in kg).
See also
GetInvMass, SetMassData
GetMassData()
MassData2D GetMassData (const Body2D & body) related
Gets the mass data of the body.
Returns
Data structure containing the mass, inertia, and center of the body.
GetPosition1()
Position2D GetPosition1 (const Body2D & body) related
Gets the "position 1" Position information for the given body.
GetRotInertia()
RotInertia GetRotInertia (const Body2D & body) related
Gets the rotational inertia of the body.
Parameters
body Body to get the rotational inertia for.
Returns
the rotational inertia.
GetTorque()
Torque GetTorque (const Body2D & body) related
Gets the net torque that the given body is currently experiencing.
GetVelocity()
Velocity2D GetVelocity (const Body2D & body, Time h, MovementConf conf) related
Gets the velocity of the body after the given time accounting for the body's acceleration and capped by the given configuration.
Warning
Behavior is undefined if the given elapsed time is an invalid value (like NaN).
Parameters
body Body to get the velocity for.
h Time elapsed to get velocity for. Behavior is undefined if this value is invalid.
conf Movement configuration. This defines caps on linear and angular speeds.
GetWorldIndex()
BodyCounter GetWorldIndex (const Body2D * body) related
Gets the world index for the given body.
GetWorldPoint()
Length2 GetWorldPoint (const Body2D & body, const Length2 localPoint) related
Gets the world coordinates of a point given in coordinates relative to the body's origin.
Parameters
body Body that the given point is relative to.
localPoint a point measured relative the the body's origin.
Returns
the same point expressed in world coordinates.
GetWorldVector() [1/2]
Length2 GetWorldVector (const Body2D & body, const Length2 localVector) related
Gets the world coordinates of a vector given the local coordinates.
Parameters
body Body that the given vector is relative to.
localVector a vector fixed in the body.
Returns
the same vector expressed in world coordinates.
GetWorldVector() [2/2]
UnitVec2 GetWorldVector (const Body2D & body, const UnitVec2 localVector) related
Gets the world vector for the given local vector from the given body's transformation.
RotateAboutLocalPoint()
void RotateAboutLocalPoint (Body2D & body, Angle amount, Length2 localPoint) related
Rotates a body a given amount around a point in body local coordinates.
This changes both the linear and angular positions of the body.
Note
Manipulating a body's position this way may cause non-physical behavior.
This is a convenience function that translates the local point into world coordinates and then calls the RotateAboutWorldPoint function.
Parameters
body Body to rotate.
amount Amount to rotate body by (in counter-clockwise direction).
localPoint Point in local coordinates.
RotateAboutWorldPoint()
void RotateAboutWorldPoint (Body2D & body, Angle amount, Length2 worldPoint) related
Rotates a body a given amount around a point in world coordinates.
This changes both the linear and angular positions of the body.
Note
Manipulating a body's position this way may cause non-physical behavior.
Parameters
body Body to rotate.
amount Amount to rotate body by (in counter-clockwise direction).
worldPoint Point in world coordinates.
SetAcceleration()
void SetAcceleration (Body2D & body, Acceleration2D value) related
Sets the accelerations on the given body.
Note
This has no effect on non-accelerable bodies.
A non-zero acceleration will also awaken the body.
Parameters
body Body whose acceleration should be set.
value Acceleration2D value to set.
SetAngle()
void SetAngle (Body2D & body, Angle value) related
Sets the body's angular orientation.
This instantly adjusts the body to be at the new angular orientation.
Warning
Manipulating a body's angle this way can cause non-physical behavior!
Parameters
body Body to move.
value Valid world angle of the body's local origin. Behavior is undefined if value is invalid.
See also
Body2D::SetTransform
SetAngularAcceleration()
void SetAngularAcceleration (Body2D & body, AngularAcceleration value) related
Sets the given angular acceleration of the given body.
SetAngularVelocity()
void SetAngularVelocity (Body2D & body, AngularVelocity omega) related
Sets the angular velocity.
Parameters
body Body to set the angular velocity of.
omega the new angular velocity.
SetForce()
void SetForce (Body2D & body, Force2 force, Length2 point) related
Sets the given amount of force at the given point to the given body.
SetLinearAcceleration()
void SetLinearAcceleration (Body2D & body, LinearAcceleration2 value) related
Sets the given linear acceleration of the given body.
SetLinearVelocity()
void SetLinearVelocity (Body2D & body, const LinearVelocity2 v) related
Sets the linear velocity of the center of mass.
Parameters
body Body to set the linear velocity of.
v the new linear velocity of the center of mass.
SetLocation()
void SetLocation (Body2D & body, Length2 value) related
Sets the body's location.
This instantly adjusts the body to be at the new location.
Warning
Manipulating a body's location this way can cause non-physical behavior!
Parameters
body Body to move.
value Valid world location of the body's local origin. Behavior is undefined if value is invalid.
See also
Body2D::SetTransform
SetTorque()
void SetTorque (Body2D & body, Torque torque) related
Sets the given amount of torque to the given body.
Unawaken()
bool Unawaken (Body2D & body) related
Puts the body to sleep if it's awake.
Member Data Documentation
m_angularAcceleration
AngularAcceleration playrho::Body2D::m_angularAcceleration = AngularAcceleration{0} private
Angular acceleration.
Note
4-bytes.
Referenced by GetAngularAcceleration().
m_invMass
InvMass playrho::Body2D::m_invMass = 0 private
Inverse mass of the body.
A non-negative value. Can only be zero for non-accelerable bodies.
Note
4-bytes.
Referenced by GetInvMass(), ResetMassData(), and SetMassData().
m_invRotI
InvRotInertia playrho::Body2D::m_invRotI = 0 private
Inverse rotational inertia about the center of mass.
A non-negative value.
Note
4-bytes.
Referenced by GetInvRotInertia(), ResetMassData(), and SetMassData().
m_linearAcceleration
LinearAcceleration2 playrho::Body2D::m_linearAcceleration = LinearAcceleration2{} private
Linear acceleration.
Note
8-bytes.
Referenced by GetLinearAcceleration().
m_underActiveTime
Time playrho::Body2D::m_underActiveTime = 0 private
Under-active time.
A body under-active for enough time should have their awake flag unset. I.e. if a body is under-active for long enough, it should go to sleep.
Note
4-bytes.
Referenced by GetUnderActiveTime(), ResetUnderActiveTime(), playrho::BodyAtty::SetTypeFlags(), and UnsetAwake().
m_xf
Transformation2D playrho::Body2D::m_xf private
Transformation for body origin.
This is essentially the cached result of GetTransform1(m_sweep). 16-bytes.
Referenced by GetTransformation().
The documentation for this class was generated from the following files:
Body.hpp
AABB.hpp
MassData.hpp
Body.cpp
BodyDef.hpp