PlayRho: playrho::PrismaticJoint Class Reference
playrho::PrismaticJoint Class Reference
Joint Classes
Prismatic Joint.
#include <PrismaticJoint.hpp>
Public Member Functions
PrismaticJoint (const PrismaticJointDef &def)
Copy constructor.
void Accept (JointVisitor &visitor) const override
Accepts a visitor.
Length2D GetAnchorA () const override
Get the anchor point on bodyA in world coordinates.
Length2D GetAnchorB () const override
Get the anchor point on bodyB in world coordinates.
Momentum2D GetLinearReaction () const override
Get the linear reaction on bodyB at the joint anchor.
AngularMomentum GetAngularReaction () const override
Get the angular reaction on bodyB.
Length2D GetLocalAnchorA () const
Gets the local anchor point relative to bodyA's origin.
Length2D GetLocalAnchorB () const
Gets the local anchor point relative to bodyB's origin.
UnitVec2 GetLocalAxisA () const
Gets local joint axis relative to bodyA.
Angle GetReferenceAngle () const
Gets the reference angle.
bool IsLimitEnabled () const noexcept
Is the joint limit enabled?
void EnableLimit (bool flag) noexcept
Enable/disable the joint limit.
Length GetLowerLimit () const noexcept
Gets the lower joint limit.
Length GetUpperLimit () const noexcept
Gets the upper joint limit.
void SetLimits (Length lower, Length upper) noexcept
Sets the joint limits.
bool IsMotorEnabled () const noexcept
Is the joint motor enabled?
void EnableMotor (bool flag) noexcept
Enable/disable the joint motor.
void SetMotorSpeed (AngularVelocity speed) noexcept
Sets the motor speed.
AngularVelocity GetMotorSpeed () const noexcept
Gets the motor speed.
void SetMaxMotorForce (Force force) noexcept
Sets the maximum motor force.
Force GetMaxMotorForce () const noexcept
Gets the maximum motor force.
Force GetMotorForce (Frequency inv_dt) const noexcept
Gets the current motor force given the inverse time step.
LimitState GetLimitState () const noexcept
Gets the current limit state.
Public Member Functions inherited from playrho::Joint
Body * GetBodyA () const noexcept
Gets the first body attached to this joint.
Body * GetBodyB () const noexcept
Gets the second body attached to this joint.
void * GetUserData () const noexcept
Get the user data pointer.
void SetUserData (void *data) noexcept
Set the user data pointer.
bool GetCollideConnected () const noexcept
Gets collide connected.
virtual void ShiftOrigin (const Length2D newOrigin)
Shifts the origin for any points stored in world coordinates.
Private Member Functions
void InitVelocityConstraints (BodyConstraintsMap &bodies, const StepConf &step, const ConstraintSolverConf &conf) override
Initializes velocity constraint data based on the given solver data.
bool SolveVelocityConstraints (BodyConstraintsMap &bodies, const StepConf &step) override
Solves velocity constraint.
bool SolvePositionConstraints (BodyConstraintsMap &bodies, const ConstraintSolverConf &conf) const override
Solves the position constraint.
Private Attributes
Length2D m_localAnchorA
Local anchor A.
Length2D m_localAnchorB
Local anchor B.
UnitVec2 m_localXAxisA
Local X axis A.
UnitVec2 m_localYAxisA
Local Y axis A.
Angle m_referenceAngle
Reference angle.
Vec3 m_impulse = Vec3_zero
Impulse.
Momentum m_motorImpulse = 0
Motor impulse.
Length m_lowerTranslation
Lower translation.
Length m_upperTranslation
Upper translation.
Force m_maxMotorForce
Max motor force.
AngularVelocity m_motorSpeed
Motor speed.
bool m_enableLimit
Enable limit. true if limit is enabled.
bool m_enableMotor
Enable motor. true if motor is enabled.
LimitState m_limitState = e_inactiveLimit
Limit state.
UnitVec2 m_axis = UnitVec2::GetZero()
Axis.
UnitVec2 m_perp = UnitVec2::GetZero()
Perpendicular.
Length m_s1
Location S1.
Length m_s2
Location S2.
Length m_a1
Location A1.
Length m_a2
Location A2.
Mat33 m_K
K matrix.
Mass m_motorMass = Mass{0}
Motor mass.
Related Functions
(Note that these are not member functions.)
Length GetJointTranslation (const PrismaticJoint &joint) noexcept
Get the current joint translation.
LinearVelocity GetLinearVelocity (const PrismaticJoint &joint) noexcept
Get the current joint translation speed.
PrismaticJointDef GetPrismaticJointDef (const PrismaticJoint &joint) noexcept
Gets the definition data for the given joint.
Related Functions inherited from playrho::Joint
bool IsEnabled (const Joint &j) noexcept
Short-cut function to determine if both bodies are enabled.
void SetAwake (Joint &j) noexcept
Wakes up the joined bodies.
JointCounter GetWorldIndex (const Joint *joint)
Gets the world index of the given joint.
JointType GetType (const Joint &joint) noexcept
Gets the type of the given joint.
Additional Inherited Members
Public Types inherited from playrho::Joint
enum LimitState { e_inactiveLimit, e_atLowerLimit, e_atUpperLimit, e_equalLimits }
Limit state.
Static Public Member Functions inherited from playrho::Joint
static bool IsOkay (const JointDef &def) noexcept
Is the given definition okay.
Protected Member Functions inherited from playrho::Joint
Joint (const JointDef &def)
Initializing constructor.
Detailed Description
Prismatic Joint.
This joint provides one degree of freedom: translation along an axis fixed in bodyA. Relative rotation is prevented.
Note
You can use a joint limit to restrict the range of motion and a joint motor to drive the motion or to model joint friction.
Member Function Documentation
Joint::LimitState playrho::PrismaticJoint::GetLimitState () const inline noexcept
Gets the current limit state.
Note
This will be e_inactiveLimit unless the joint limit has been enabled.
Referenced by GetMaxMotorForce().
void playrho::PrismaticJoint::InitVelocityConstraints (BodyConstraintsMap & bodies, const StepConf & step, const ConstraintSolverConf & conf) override private virtual
Initializes velocity constraint data based on the given solver data.
Note
This MUST be called prior to calling SolveVelocityConstraints.
See also
SolveVelocityConstraints.
Implements playrho::Joint.
Referenced by GetMaxMotorForce().
bool playrho::PrismaticJoint::SolvePositionConstraints (BodyConstraintsMap & bodies, const ConstraintSolverConf & conf) const override private virtual
Solves the position constraint.
Returns
true if the position errors are within tolerance.
Implements playrho::Joint.
Referenced by GetMaxMotorForce().
bool playrho::PrismaticJoint::SolveVelocityConstraints (BodyConstraintsMap & bodies, const StepConf & step) override private virtual
Solves velocity constraint.
Precondition
InitVelocityConstraints has been called.
See also
InitVelocityConstraints.
Returns
true if velocity is "solved", false otherwise.
Implements playrho::Joint.
Referenced by GetMaxMotorForce().
Friends And Related Function Documentation
Length GetJointTranslation (const PrismaticJoint & joint) related
Get the current joint translation.
Referenced by GetLimitState().
LinearVelocity GetLinearVelocity (const PrismaticJoint & joint) related
Get the current joint translation speed.
Referenced by GetLimitState().
PrismaticJointDef GetPrismaticJointDef (const PrismaticJoint & joint) related
Gets the definition data for the given joint.
The documentation for this class was generated from the following files:
PrismaticJoint.hpp
PrismaticJoint.cpp
PrismaticJointDef.hpp