PlayRho: playrho::DistanceProxy2D Class Reference
playrho::DistanceProxy2D Class Reference
Distance Proxy.
#include <DistanceProxy.hpp>
Public Types
using ConstVertexPointer = const Length2 *
Constant vertex pointer.
using ConstVertexIterator = ConstVertexPointer
Constant vertex iterator.
using ConstNormalPointer = const UnitVec2 *
Constant normal pointer.
using ConstNormalIterator = ConstNormalPointer
Constant normal iterator.
Public Member Functions
DistanceProxy2D (const DistanceProxy2D &copy) noexcept
Copy constructor.
DistanceProxy2D (const NonNegative< Length > vertexRadius, const VertexCounter count, const Length2 *vertices, const UnitVec2 *normals) noexcept
Initializing constructor.
auto GetVertexRadius () const noexcept
Gets the vertex radius of the vertices of the associated shape.
Range< ConstVertexIterator > GetVertices () const noexcept
Gets the range of vertices.
Range< ConstNormalIterator > GetNormals () const noexcept
Gets the range of normal.
auto GetVertexCount () const noexcept
Gets the vertex count.
auto GetVertex (VertexCounter index) const noexcept
Gets a vertex by index.
auto GetNormal (VertexCounter index) const noexcept
Gets the normal for the given index.
Private Attributes
const Length2 * m_vertices = nullptr
Vertices.
const UnitVec2 * m_normals = nullptr
Normals.
VertexCounter m_count = 0
Count of valid elements of m_vertices.
NonNegative< Length > m_vertexRadius = 0_m
Radius of the vertices of the associated shape.
Related Functions
(Note that these are not member functions.)
AABB2D ComputeAABB (const DistanceProxy2D &proxy, const Transformation2D &xf) noexcept
Computes the AABB.
AABB2D ComputeAABB (const DistanceProxy2D &proxy, const Transformation2D &xfm0, const Transformation2D &xfm1) noexcept
Computes the AABB.
bool operator== (const DistanceProxy2D &lhs, const DistanceProxy2D &rhs) noexcept
Determines with the two given distance proxies are equal.
bool operator!= (const DistanceProxy2D &lhs, const DistanceProxy2D &rhs) noexcept
Determines with the two given distance proxies are not equal.
template<class T >
VertexCounter GetSupportIndex (const DistanceProxy2D &proxy, T dir) noexcept
Gets the supporting vertex index in the given direction for the given distance proxy.
bool TestPoint (const DistanceProxy2D &proxy, Length2 point) noexcept
Tests a point for containment in the given distance proxy.
RayCastOutput2D RayCast (const DistanceProxy2D &proxy, const RayCastInput2D &input, const Transformation2D &transform) noexcept
Cast a ray against the distance proxy.
Detailed Description
Distance Proxy.
A distance proxy aggregates a convex set of vertices and a vertex radius of those vertices. This can be visualized as a convex N-sided polygon with rounded corners. It's meant to represent any single portion of a shape identified by its child-index. These are used by the G.J.K. algorithm: "a method for determining the minimum distance between two convex sets".
Note
This data structure is 24-bytes.
See also
https://en.wikipedia.org/wiki/Gilbert%2DJohnson%2DKeerthi_distance_algorithm
Constructor & Destructor Documentation
DistanceProxy2D()
playrho::DistanceProxy2D::DistanceProxy2D (const NonNegative< Length > vertexRadius, const VertexCounter count, const Length2 * vertices, const UnitVec2 * normals) inline noexcept
Initializing constructor.
Constructs a distance proxy for n-point shape (like a polygon).
Parameters
vertexRadius Radius of the given vertices.
count Count of elements of the vertices and normals arrays.
vertices Collection of vertices of the shape (relative to the shape's origin).
normals Collection of normals of the shape.
Note
The vertices collection must have more than zero elements and no more than MaxShapeVertices elements.
Warning
Behavior is undefined if the vertices collection has less than one element or more than MaxShapeVertices elements.
Behavior is undefined if the vertices are not in counter-clockwise order.
Behavior is undefined if the shape defined by the vertices is not convex.
Behavior is undefined if the normals aren't normals for adjacent vertices.
Behavior is undefined if any normal is not unique.
Member Function Documentation
GetVertex()
auto playrho::DistanceProxy2D::GetVertex (VertexCounter index) const inline noexcept
Gets a vertex by index.
Parameters
index Index value less than the count of vertices represented by this proxy.
Warning
Behavior is undefined if the index given is not less than the count of vertices represented by this proxy.
Behavior is undefined if InvalidVertex is given as the index value.
Returns
Vertex linear position (relative to the shape's origin) at the given index.
See also
Distance.
Referenced by playrho::CollideShapes(), playrho::SeparationFinder2D::EvaluateForFaceA(), playrho::SeparationFinder2D::EvaluateForFaceB(), playrho::SeparationFinder2D::EvaluateForPoints(), playrho::SeparationFinder2D::FindMinSeparationForFaceA(), playrho::SeparationFinder2D::FindMinSeparationForFaceB(), playrho::SeparationFinder2D::FindMinSeparationForPoints(), playrho::SeparationFinder2D::Get(), playrho::GetMaxSeparation(), and playrho::GetMaxSeparation4x4().
GetVertexCount()
auto playrho::DistanceProxy2D::GetVertexCount () const inline noexcept
Gets the vertex count.
This is the count of valid vertex elements that this object provides.
Returns
Value between 0 and MaxShapeVertices.
Note
This only returns 0 if this proxy was default constructed.
Referenced by playrho::CollideShapes(), playrho::Distance(), playrho::SeparationFinder2D::Get(), and playrho::GetMaxSeparation().
GetVertexRadius()
auto playrho::DistanceProxy2D::GetVertexRadius () const inline noexcept
Gets the vertex radius of the vertices of the associated shape.
Returns
Non-negative distance.
Referenced by playrho::CollideShapes(), playrho::GetToiViaSat(), and playrho::TestOverlap().
Friends And Related Function Documentation
ComputeAABB() [1/2]
AABB2D ComputeAABB (const DistanceProxy2D & proxy, const Transformation2D & xf) related
Computes the AABB.
Computes the Axis Aligned Bounding Box (AABB) for the given child shape at a given a transform.
Warning
Behavior is undefined if the given transformation is invalid.
Parameters
proxy Distance proxy for the child shape.
xf World transform of the shape.
Returns
AABB for the proxy shape or the default AABB if the proxy has a zero vertex count.
ComputeAABB() [2/2]
AABB2D ComputeAABB (const DistanceProxy2D & proxy, const Transformation2D & xfm0, const Transformation2D & xfm1) related
Computes the AABB.
Computes the Axis Aligned Bounding Box (AABB) for the given child shape at the given transforms.
Warning
Behavior is undefined if a given transformation is invalid.
Parameters
proxy Distance proxy for the child shape.
xfm0 World transform 0 of the shape.
xfm1 World transform 1 of the shape.
Returns
AABB for the proxy shape or the default AABB if the proxy has a zero vertex count.
GetSupportIndex()
template<class T > VertexCounter GetSupportIndex (const DistanceProxy2D & proxy, T dir) related
Gets the supporting vertex index in the given direction for the given distance proxy.
This finds the vertex that's most significantly in the direction of the given vector and returns its index.
Note
0 is returned for a given zero length direction vector.
Parameters
proxy Distance proxy object to find index in if a valid index exists for it.
dir Direction vector to find index for.
Returns
InvalidVertex if d is invalid or the count of vertices is zero, otherwise a value from 0 to one less than count.
See also
GetVertexCount().
operator!=()
bool operator!= (const DistanceProxy2D & lhs, const DistanceProxy2D & rhs) related
Determines with the two given distance proxies are not equal.
operator==()
bool operator== (const DistanceProxy2D & lhs, const DistanceProxy2D & rhs) related
Determines with the two given distance proxies are equal.
The documentation for this class was generated from the following files:
DistanceProxy.hpp
AABB.hpp
RayCastOutput.hpp