PlayRho: playrho::BodyAtty Class Reference
playrho::BodyAtty Class Reference
Body attorney.
#include <BodyAtty.hpp>
Static Private Member Functions
static Fixture2D * CreateFixture (Body2D &b, Shape2D shape, const FixtureDef &def)
Creates a fixture.
static bool DestroyFixture (Body2D &b, Fixture2D *value)
Destroys the given fixture.
static void ClearFixtures (Body2D &b, std::function< void(Fixture2D &)> callback)
Clears the fixtures of the given body.
static void SetTypeFlags (Body2D &b, BodyType type) noexcept
Sets the type flags for the given body.
static void SetAwakeFlag (Body2D &b) noexcept
Sets the awake flag for the given body.
static void SetMassDataDirty (Body2D &b) noexcept
Sets the mass data dirty flag for the given body.
static bool Erase (Body2D &b, const Contact2D *value)
Erases the given contact from the given body.
static bool Erase (Body2D &b, const Joint2D *value)
Erases the given joint from the given body.
static void ClearContacts (Body2D &b)
Clears the contacts from the given body.
static void ClearJoints (Body2D &b)
Clears the joints from the given body.
static bool Insert (Body2D &b, Joint2D *value)
Inserts the given joint into the given body's joint list.
static bool Insert (Body2D *b, Joint2D *value)
Inserts the given joint into the given body's joint list.
static bool Insert (Body2D &b, ContactKey key, Contact2D *value)
Inserts the given contact key and contact into the given body's contacts list.
static void SetPosition0 (Body2D &b, const Position2D value) noexcept
Sets the position0 value of the given body to the given position.
static void SetPosition1 (Body2D &b, const Position2D value) noexcept
Sets the body sweep's position 1 value.
static void ResetAlpha0 (Body2D &b)
Resets the given body's alpha0 value.
static void SetSweep (Body2D &b, const Sweep2D value) noexcept
Sets the sweep value of the given body.
static void SetTransformation (Body2D &b, const Transformation2D value) noexcept
Sets the body's transformation.
static void SetVelocity (Body2D &b, Velocity2D value) noexcept
Sets the body's velocity.
static void Advance0 (Body2D &b, Real value) noexcept
Calls the given body sweep's Advance0 method to advance to the given value.
static void Advance (Body2D &b, Real toi) noexcept
Calls the given body's Advance method to advance to the given TOI.
static void Restore (Body2D &b, const Sweep2D value) noexcept
Restores the given body's sweep to the given sweep value.
static void ClearJoints (Body2D &b, std::function< void(Joint2D &)> callback)
Clears the given body's joints list.
static void EraseContacts (Body2D &b, const std::function< bool(Contact2D &)> &callback)
Erases the given body's contacts.
static bool IsIslanded (const Body2D &b) noexcept
Whether the given body is in the is islanded state.
static void SetIslanded (Body2D &b) noexcept
Sets the given body to the is islanded state.
static void UnsetIslanded (Body2D &b) noexcept
Unsets the given body's is islanded state.
Friends
class World2D
Detailed Description
Body attorney.
This class uses the "attorney-client" idiom to control the granularity of friend-based access to the Body class. This is meant to help preserve and enforce the invariants of the Body class.
See also
https://en.wikibooks.org/wiki/More_C++_Idioms/Friendship_and_the_Attorney-Client
Member Function Documentation
SetPosition1()
static void playrho::BodyAtty::SetPosition1 (Body2D & b, const Position2D value) inline static private noexcept
Sets the body sweep's position 1 value.
Note
This sets what Body2D::GetWorldCenter returns.
Referenced by playrho::World2D::UpdateBody().
SetTransformation()
static void playrho::BodyAtty::SetTransformation (Body2D & b, const Transformation2D value) inline static private noexcept
Sets the body's transformation.
Note
This sets what Body2D::GetLocation returns.
Referenced by Restore(), playrho::World2D::ShiftOrigin(), and playrho::World2D::UpdateBody().
SetVelocity()
static void playrho::BodyAtty::SetVelocity (Body2D & b, Velocity2D value) inline static private noexcept
Sets the body's velocity.
Note
This sets what Body2D::GetVelocity returns.
Referenced by playrho::World2D::UpdateBody().
The documentation for this class was generated from the following file:
BodyAtty.hpp