PlayRho: playrho::d2::BodyAtty Class Reference
playrho::d2::BodyAtty Class Reference
Body attorney.
#include <BodyAtty.hpp>
Static Private Member Functions
static Body * CreateBody (World *world, const BodyConf &bd)
Creates a body.
static void Delete (Body *b)
Deletes a body.
static void AddFixture (Body &b, Fixture *fixture)
Adds the given fixture to the given body.
static bool RemoveFixture (Body &b, Fixture *fixture)
Removes the given fixture from the given body.
static void ClearFixtures (Body &b, std::function< void(Fixture &)> callback)
Clears the fixtures of the given body.
static void SetTypeFlags (Body &b, BodyType type) noexcept
Sets the type flags for the given body.
static void SetAwakeFlag (Body &b) noexcept
Sets the awake flag for the given body.
static void SetMassDataDirty (Body &b) noexcept
Sets the mass data dirty flag for the given body.
static bool Erase (Body &b, const Contact *value)
Erases the given contact from the given body.
static bool Erase (Body &b, const Joint *value)
Erases the given joint from the given body.
static void ClearContacts (Body &b)
Clears the contacts from the given body.
static void ClearJoints (Body &b)
Clears the joints from the given body.
static bool Insert (Body &b, Joint *value)
Inserts the given joint into the given body's joint list.
static bool Insert (Body *b, Joint *value)
Inserts the given joint into the given body's joint list.
static bool Insert (Body &b, ContactKey key, Contact *value)
Inserts the given contact key and contact into the given body's contacts list.
static void SetPosition0 (Body &b, const Position value) noexcept
Sets the "position 0" value of the given body to the given position.
static void SetPosition1 (Body &b, const Position value) noexcept
Sets the body sweep's "position 1" value.
static void ResetAlpha0 (Body &b) noexcept
Resets the given body's "alpha-0" value.
static void SetSweep (Body &b, const Sweep value) noexcept
Sets the sweep value of the given body.
static void SetTransformation (Body &b, const Transformation value) noexcept
Sets the body's transformation.
static void SetVelocity (Body &b, Velocity value) noexcept
Sets the body's velocity.
static void Advance0 (Body &b, Real value) noexcept
Calls the given body sweep's Advance0 method to advance to the given value.
static void Advance (Body &b, Real toi) noexcept
Calls the given body's Advance method to advance to the given TOI.
static void Restore (Body &b, const Sweep value) noexcept
Restores the given body's sweep to the given sweep value.
static void ClearJoints (Body &b, std::function< void(Joint &)> callback)
Clears the given body's joints list.
static void EraseContacts (Body &b, const std::function< bool(Contact &)> &callback)
Erases the given body's contacts.
static bool IsIslanded (const Body &b) noexcept
Whether the given body is in the is-in-island state.
static void SetIslanded (Body &b) noexcept
Sets the given body to the is-in-island state.
static void UnsetIslanded (Body &b) noexcept
Unsets the given body's is-in-island state.
Friends
class World
Detailed Description
Body attorney.
This is the "body attorney" which provides limited privileged access to the Body class for the World class.
Note
This class uses the "attorney-client" idiom to control the granularity of friend-based access to the Body class. This is meant to help preserve and enforce the invariants of the Body class.
See also
https://en.wikibooks.org/wiki/More_C++_Idioms/Friendship_and_the_Attorney-Client
Member Function Documentation
SetPosition1()
static void playrho::d2::BodyAtty::SetPosition1 (Body & b, const Position value) inline static private noexcept
Sets the body sweep's "position 1" value.
Note
This sets what Body::GetWorldCenter returns.
See also
Body::GetWorldCenter
Referenced by playrho::d2::World::UpdateBody().
SetTransformation()
static void playrho::d2::BodyAtty::SetTransformation (Body & b, const Transformation value) inline static private noexcept
Sets the body's transformation.
Note
This sets what Body::GetLocation returns.
See also
Body::GetLocation
Referenced by Restore(), playrho::d2::World::ShiftOrigin(), and playrho::d2::World::UpdateBody().
SetVelocity()
static void playrho::d2::BodyAtty::SetVelocity (Body & b, Velocity value) inline static private noexcept
Sets the body's velocity.
Note
This sets what Body::GetVelocity returns.
See also
Body::GetVelocity
Referenced by playrho::d2::World::UpdateBody().
The documentation for this class was generated from the following file:
BodyAtty.hpp