PlayRho: playrho::d2::WorldImpl Class Reference
playrho::d2::WorldImpl Class Reference
Definition of a "world" implementation.
#include <WorldImpl.hpp>
Classes
struct ContactToiData
Contact TOI data.
struct ContactUpdateConf
Contact updating configuration.
struct DestroyContactsStats
Destroy contacts statistics.
struct ProcessContactsOutput
Process contacts output.
struct UpdateContactsData
Update contacts data.
struct UpdateContactsStats
Update contacts statistics.
Public Types
using Bodies = std::vector< BodyID >
Bodies container type.
using Contacts = std::vector< KeyedContactPtr >
Contacts container type.
using Joints = std::vector< JointID >
Joints container type.
using BodyJoints = std::vector< std::pair< BodyID, JointID > >
Body joints container type.
using Fixtures = std::vector< FixtureID >
Fixtures container type.
using FixtureProxies = std::vector< FixtureProxy >
using FixtureListener = std::function< void(FixtureID)>
using JointListener = std::function< void(JointID)>
using ContactListener = std::function< void(ContactID)>
using ManifoldContactListener = std::function< void(ContactID, const Manifold &)>
using ImpulsesContactListener = std::function< void(ContactID, const ContactImpulsesList &, unsigned)>
Public Member Functions
WorldImpl (const WorldConf &def=GetDefaultWorldConf())
Constructs a world implementation for a world.
WorldImpl (const WorldImpl &other)=default
Copy constructor.
WorldImpl & operator= (const WorldImpl &other)=default
~WorldImpl () noexcept
Destructor.
void Clear () noexcept
Clears this world.
void SetFixtureDestructionListener (FixtureListener listener) noexcept
Register a destruction listener for fixtures.
void SetJointDestructionListener (JointListener listener) noexcept
Register a destruction listener for joints.
void SetBeginContactListener (ContactListener listener) noexcept
Register a begin contact event listener.
void SetEndContactListener (ContactListener listener) noexcept
Register an end contact event listener.
void SetPreSolveContactListener (ManifoldContactListener listener) noexcept
Register a pre-solve contact event listener.
void SetPostSolveContactListener (ImpulsesContactListener listener) noexcept
Register a post-solve contact event listener.
BodyID CreateBody (const BodyConf &def=GetDefaultBodyConf())
Creates a rigid body with the given configuration.
void Destroy (BodyID id)
Destroys the given body.
JointID CreateJoint (const Joint &def)
Creates a joint to constrain one or more bodies.
void Destroy (JointID joint)
Destroys a joint.
StepStats Step (const StepConf &conf)
Steps the world simulation according to the given configuration.
SizedRange< Bodies::const_iterator > GetBodies () const noexcept
Gets the world body range for this constant world.
BodyCounter GetBodyRange () const noexcept
Gets the extent of the currently valid body range.
SizedRange< Bodies::const_iterator > GetBodiesForProxies () const noexcept
Gets the bodies-for-proxies range for this world.
SizedRange< Fixtures::const_iterator > GetFixturesForProxies () const noexcept
Gets the fixtures-for-proxies range for this world.
SizedRange< Joints::const_iterator > GetJoints () const noexcept
Gets the world joint range.
SizedRange< Contacts::const_iterator > GetContacts () const noexcept
Gets the world contact range.
bool IsStepComplete () const noexcept
Whether or not "step" is complete.
bool GetSubStepping () const noexcept
Gets whether or not sub-stepping is enabled.
void SetSubStepping (bool flag) noexcept
Enables/disables single stepped continuous physics.
const DynamicTree & GetTree () const noexcept
Gets access to the broad-phase dynamic tree information.
bool IsLocked () const noexcept
Is the world locked (in the middle of a time step).
void ShiftOrigin (Length2 newOrigin)
Shifts the world origin.
Length GetMinVertexRadius () const noexcept
Gets the minimum vertex radius that shapes in this world can be.
Length GetMaxVertexRadius () const noexcept
Gets the maximum vertex radius that shapes in this world can be.
Frequency GetInvDeltaTime () const noexcept
Gets the inverse delta time.
void Refilter (FixtureID id)
Re-filter the fixture.
void SetFilterData (FixtureID id, Filter filter)
Sets the contact filtering data.
void SetType (BodyID id, playrho::BodyType type)
Sets the type of the given body.
FixtureID CreateFixture (BodyID body, const Shape &shape, const FixtureConf &def=GetDefaultFixtureConf(), bool resetMassData=true)
Creates a fixture with the given parameters.
bool Destroy (FixtureID fixture, bool resetMassData=true)
Destroys a fixture.
void DestroyFixtures (BodyID id)
Destroys fixtures of the given body.
void SetEnabled (BodyID id, bool flag)
Sets the enabled state of the body.
MassData ComputeMassData (BodyID id) const
Computes the mass data of the identified body.
void SetMassData (BodyID id, const MassData &massData)
Set the mass properties to override the mass properties of the fixtures.
void SetTransformation (BodyID id, Transformation xfm)
Sets the transformation of the body.
FixtureCounter GetShapeCount () const noexcept
const Fixture & GetFixture (FixtureID id) const
Fixture & GetFixture (FixtureID id)
const Body & GetBody (BodyID id) const
Body & GetBody (BodyID id)
const Contact & GetContact (ContactID id) const
Contact & GetContact (ContactID id)
const Manifold & GetManifold (ContactID id) const
Manifold & GetManifold (ContactID id)
const Joint & GetJoint (JointID id) const
Joint & GetJoint (JointID id)
void SetJoint (JointID id, const Joint &def)
void SetSensor (FixtureID id, bool value)
Sets whether the fixture is a sensor or not.
Private Types
enum Flag : FlagsType { e_newFixture = 0x0001, e_locked = 0x0002, e_substepping = 0x0020, e_stepComplete = 0x0040 }
Flag enumeration.
using FlagsType = std::uint32_t
Flags type data type.
using ProxyId = DynamicTree::Size
Proxy ID type alias.
using ContactKeyQueue = std::vector< ContactKey >
Contact key queue type alias.
using ProxyQueue = std::vector< ProxyId >
Proxy queue type alias.
using BodyStack = std::stack< BodyID, std::vector< BodyID > >
Body stack.
Private Member Functions
RegStepStats SolveReg (const StepConf &conf)
Solves the step.
IslandStats SolveRegIslandViaGS (const StepConf &conf, const Island &island)
Solves the given island (regularly).
void AddToIsland (Island &island, BodyID seed, BodyCounter &remNumBodies, ContactCounter &remNumContacts, JointCounter &remNumJoints)
Adds to the island based off of a given "seed" body.
void AddToIsland (Island &island, BodyStack &stack, BodyCounter &remNumBodies, ContactCounter &remNumContacts, JointCounter &remNumJoints)
Adds to the island.
void AddContactsToIsland (Island &island, BodyStack &stack, SizedRange< Contacts::const_iterator > contacts, BodyID bodyID)
Adds contacts to the island.
void AddJointsToIsland (Island &island, BodyStack &stack, SizedRange< BodyJoints::const_iterator > joints)
Adds joints to the island.
ToiStepStats SolveToi (const StepConf &conf)
Solves the step using successive time of impact (TOI) events.
IslandStats SolveToi (ContactID contactID, const StepConf &conf)
Solves collisions for the given time of impact.
IslandStats SolveToiViaGS (const Island &island, const StepConf &conf)
Solves the time of impact for bodies 0 and 1 of the given island.
ProcessContactsOutput ProcessContactsForTOI (BodyID id, Island &island, Real toi, const StepConf &conf)
Processes the contacts of a given body for TOI handling.
void Remove (BodyID id) noexcept
Removes the given body from this world.
void Add (JointID j, bool flagForFiltering=false)
Updates associated bodies and contacts for specified joint's addition.
void Remove (JointID id) noexcept
Updates associated bodies and contacts for specified joint's removal.
void SetStepComplete (bool value) noexcept
Sets the step complete state.
void SetAllowSleeping () noexcept
Sets the allow sleeping state.
void UnsetAllowSleeping () noexcept
Unsets the allow sleeping state.
bool HasNewFixtures () const noexcept
Determines whether this world has new fixtures.
void UnsetNewFixtures () noexcept
Unsets the new fixtures state.
ContactCounter FindNewContacts ()
Finds new contacts.
DestroyContactsStats DestroyContacts (Contacts &contacts)
Processes the narrow phase collision for the contacts collection.
UpdateContactsStats UpdateContacts (const StepConf &conf)
Update contacts.
void Destroy (ContactID contact, Body *from)
Destroys the given contact and removes it from its container.
bool Add (ContactKey key)
Adds a contact for the proxies identified by the key if appropriate.
ContactCounter Synchronize (const Body &body, const Transformation &xfm1, const Transformation &xfm2, Real multiplier, Length extension)
Synchronizes the given body.
ContactCounter Synchronize (const Fixture &fixture, const Transformation &xfm1, const Transformation &xfm2, Length2 displacement, Length extension)
Synchronizes the given fixture.
void CreateAndDestroyProxies (Length extension)
Creates and destroys proxies.
PreStepStats::counter_type SynchronizeProxies (const StepConf &conf)
Synchronizes proxies of the bodies for proxies.
void Update (ContactID id, const ContactUpdateConf &conf)
Updates the touching related state and notifies listener (if one given).
Static Private Member Functions
static Bodies::size_type RemoveUnspeedablesFromIslanded (const std::vector< BodyID > &bodies, const ArrayAllocator< Body > &buffer, std::vector< bool > &islanded)
Removes unspeedables from the is is-in-island state.
static bool UpdateBody (Body &body, const Position &pos)
Updates the given body.
static UpdateContactsData UpdateContactTOIs (ArrayAllocator< Contact > &contactBuffer, ArrayAllocator< Body > &bodyBuffer, const ArrayAllocator< Fixture > &fixtureBuffer, const Contacts &contacts, const StepConf &conf)
Updates the contact times of impact.
static ContactToiData GetSoonestContact (const Contacts &contacts, const ArrayAllocator< Contact > &buffer) noexcept
Gets the soonest contact.
static void InternalDestroy (ContactID contact, ArrayAllocator< Body > &bodyBuffer, ArrayAllocator< Contact > &contactBuffer, ArrayAllocator< Manifold > &manifoldBuffer, ContactListener listener, Body *from=nullptr)
Destroys the given contact.
static void CreateProxies (FixtureID id, Fixture &fixture, const Transformation &xfm, ProxyQueue &proxies, DynamicTree &tree, Length aabbExtension)
Creates proxies for every child of the given fixture's shape.
static void InternalTouchProxies (ProxyQueue &proxies, const Fixture &fixture) noexcept
Touches each proxy of the given fixture.
Private Attributes
ArrayAllocator< Body > m_bodyBuffer
ArrayAllocator< Fixture > m_fixtureBuffer
ArrayAllocator< Joint > m_jointBuffer
ArrayAllocator< Contact > m_contactBuffer
ArrayAllocator< Manifold > m_manifoldBuffer
DynamicTree m_tree
Dynamic tree.
ContactKeyQueue m_proxyKeys
Proxy keys.
ProxyQueue m_proxies
Proxies queue.
Fixtures m_fixturesForProxies
Fixtures for proxies queue.
Bodies m_bodiesForProxies
Bodies for proxies queue.
Bodies m_bodies
Body collection.
Joints m_joints
Joint collection.
Contacts m_contacts
Container of contacts.
Island m_island
Island buffer.
std::vector< bool > m_islandedBodies
std::vector< bool > m_islandedContacts
std::vector< bool > m_islandedJoints
FixtureListener m_fixtureDestructionListener
JointListener m_jointDestructionListener
ContactListener m_beginContactListener
ContactListener m_endContactListener
ManifoldContactListener m_preSolveContactListener
ImpulsesContactListener m_postSolveContactListener
FlagsType m_flags = e_stepComplete
Flags.
Frequency m_inv_dt0 = 0
Inverse delta-t from previous step.
Positive< Length > m_minVertexRadius
Minimum vertex radius.
Positive< Length > m_maxVertexRadius
Maximum vertex radius.
Related Functions
(Note that these are not member functions.)
void Destroy (WorldImpl &world, BodyID id)
Destroys the identified body.
BodyConf GetBodyConf (const WorldImpl &world, BodyID id)
Gets the body configuration for the identified body.
BodyType GetType (const WorldImpl &world, BodyID id)
Gets the type of the body.
void SetType (WorldImpl &world, BodyID id, BodyType value)
bool IsImpenetrable (const WorldImpl &world, BodyID id)
Is the body treated like a bullet for continuous collision detection?
void SetImpenetrable (WorldImpl &world, BodyID id)
void UnsetImpenetrable (WorldImpl &world, BodyID id)
bool IsSleepingAllowed (const WorldImpl &world, BodyID id)
Gets whether or not the identified body is allowed to sleep.
void SetSleepingAllowed (WorldImpl &world, BodyID id, bool value)
Angle GetAngle (const WorldImpl &world, BodyID id)
Transformation GetTransformation (const WorldImpl &world, BodyID id)
void SetTransformation (WorldImpl &world, BodyID id, Transformation xfm)
Velocity GetVelocity (const WorldImpl &world, BodyID id)
void SetVelocity (WorldImpl &world, BodyID id, const Velocity &value)
Sets the body's velocity (linear and angular velocity).
void UnsetAwake (WorldImpl &world, BodyID id)
Sleeps the body.
void SetAwake (WorldImpl &world, BodyID id)
Wakes up the body.
bool IsAwake (const WorldImpl &world, BodyID id)
Frequency GetLinearDamping (const WorldImpl &world, BodyID id)
Gets the linear damping of the body.
void SetLinearDamping (WorldImpl &world, BodyID id, NonNegative< Frequency > value)
Sets the linear damping of the body.
Frequency GetAngularDamping (const WorldImpl &world, BodyID id)
Gets the angular damping of the body.
void SetAngularDamping (WorldImpl &world, BodyID id, NonNegative< Frequency > value)
Sets the angular damping of the body.
Length2 GetLocalCenter (const WorldImpl &world, BodyID id)
Gets the local position of the center of mass of the specified body.
Length2 GetWorldCenter (const WorldImpl &world, BodyID id)
Get the world position of the center of mass of the specified body.
LinearAcceleration2 GetLinearAcceleration (const WorldImpl &world, BodyID id)
Gets this body's linear acceleration.
AngularAcceleration GetAngularAcceleration (const WorldImpl &world, BodyID id)
Gets this body's angular acceleration.
void SetAcceleration (WorldImpl &world, BodyID id, LinearAcceleration2 linear, AngularAcceleration angular)
void SetAcceleration (WorldImpl &world, BodyID id, Acceleration value)
void SetAcceleration (WorldImpl &world, BodyID id, LinearAcceleration2 value)
void SetAcceleration (WorldImpl &world, BodyID id, AngularAcceleration value)
void SetMassData (WorldImpl &world, BodyID id, const MassData &massData)
Sets the mass properties to override the mass properties of the fixtures.
MassData ComputeMassData (const WorldImpl &world, BodyID id)
Computes the body's mass data.
void ResetMassData (WorldImpl &world, BodyID id)
Resets the mass data properties.
InvMass GetInvMass (const WorldImpl &world, BodyID id)
Gets the inverse total mass of the body.
Mass GetMass (const WorldImpl &world, BodyID id)
Gets the mass of the body.
InvRotInertia GetInvRotInertia (const WorldImpl &world, BodyID id)
Gets the inverse rotational inertia of the body.
RotInertia GetRotInertia (const WorldImpl &world, BodyID id)
Gets the rotational inertia of the body.
RotInertia GetLocalRotInertia (const WorldImpl &world, BodyID id)
Gets the rotational inertia of the body about the local origin.
SizedRange< std::vector< std::pair< BodyID, JointID > >::const_iterator > GetJoints (const WorldImpl &world, BodyID id)
Gets the range of all joints attached to this body.
SizedRange< std::vector< FixtureID >::const_iterator > GetFixtures (const WorldImpl &world, BodyID id)
Gets the range of all constant fixtures attached to the given body.
void DestroyFixtures (WorldImpl &world, BodyID id)
bool IsEnabled (const WorldImpl &world, BodyID id)
Gets the enabled/disabled state of the body.
void SetEnabled (WorldImpl &world, BodyID body, bool flag)
Sets the enabled state of the body.
bool IsSpeedable (const WorldImpl &world, BodyID id)
Is identified body "speedable".
bool IsAccelerable (const WorldImpl &world, BodyID id)
Is identified body "accelerable"?
SizedRange< std::vector< KeyedContactPtr >::const_iterator > GetContacts (const WorldImpl &world, BodyID id)
Gets the container of all contacts attached to this body.
bool IsMassDataDirty (const WorldImpl &world, BodyID id)
Gets whether the body's mass-data is dirty.
bool IsFixedRotation (const WorldImpl &world, BodyID id)
Gets whether the body has fixed rotation.
void SetFixedRotation (WorldImpl &world, BodyID id, bool value)
Sets this body to have fixed rotation.
bool IsAwake (const WorldImpl &world, ContactID id)
Gets the awake status of the specified contact.
void SetAwake (WorldImpl &world, ContactID id)
Sets awake the bodies of the fixtures of the given contact.
bool IsTouching (const WorldImpl &world, ContactID id)
Is this contact touching?
bool NeedsFiltering (const WorldImpl &world, ContactID id)
Whether or not the contact needs filtering.
bool NeedsUpdating (const WorldImpl &world, ContactID id)
Whether or not the contact needs updating.
bool HasValidToi (const WorldImpl &world, ContactID id)
Whether or not the contact has a valid TOI.
Real GetToi (const WorldImpl &world, ContactID id)
Gets the time of impact (TOI) as a fraction.
BodyID GetBodyA (const WorldImpl &world, ContactID id)
BodyID GetBodyB (const WorldImpl &world, ContactID id)
FixtureID GetFixtureA (const WorldImpl &world, ContactID id)
Gets fixture A of the given contact.
FixtureID GetFixtureB (const WorldImpl &world, ContactID id)
Gets fixture B of the given contact.
ChildCounter GetChildIndexA (const WorldImpl &world, ContactID id)
Get the child primitive index for fixture A.
ChildCounter GetChildIndexB (const WorldImpl &world, ContactID id)
Get the child primitive index for fixture B.
TimestepIters GetToiCount (const WorldImpl &world, ContactID id)
Real GetDefaultFriction (const WorldImpl &world, ContactID id)
Real GetDefaultRestitution (const WorldImpl &world, ContactID id)
LinearVelocity GetTangentSpeed (const WorldImpl &world, ContactID id)
void SetTangentSpeed (WorldImpl &world, ContactID id, LinearVelocity value)
bool IsEnabled (const WorldImpl &world, ContactID id)
void SetEnabled (WorldImpl &world, ContactID id)
void UnsetEnabled (WorldImpl &world, ContactID id)
FixtureID CreateFixture (WorldImpl &world, BodyID id, const Shape &shape, const FixtureConf &def, bool resetMassData=true)
bool Destroy (WorldImpl &world, FixtureID id, bool resetMassData)
BodyID GetBody (const WorldImpl &world, FixtureID id)
Shape GetShape (const WorldImpl &world, FixtureID id)
bool IsSensor (const WorldImpl &world, FixtureID id)
Is the specified fixture a sensor (non-solid)?
AreaDensity GetDensity (const WorldImpl &world, FixtureID id)
Gets the density of this fixture.
const std::vector< FixtureProxy > & GetProxies (const WorldImpl &world, FixtureID id)
void SetSensor (WorldImpl &world, FixtureID id, bool value)
Sets whether the specified fixture is a sensor or not.
Filter GetFilterData (const WorldImpl &world, FixtureID id)
void Refilter (WorldImpl &world, FixtureID id)
void SetFilterData (WorldImpl &world, FixtureID id, const Filter &value)
JointID CreateJoint (WorldImpl &world, const Joint &def)
Creates a new joint.
void Destroy (WorldImpl &world, JointID id)
Destroys the identified joint.
JointType GetType (const WorldImpl &world, JointID id)
Gets the type of the joint.
const Joint & GetJoint (const WorldImpl &world, JointID id)
Gets the identified joint's value.
void SetJoint (WorldImpl &world, JointID id, const Joint &def)
Sets the identified joint's new value.
Momentum2 GetLinearReaction (const WorldImpl &world, JointID id)
Gets the linear reaction on body-B at the joint anchor.
AngularMomentum GetAngularReaction (const WorldImpl &world, JointID id)
Get the angular reaction on body-B for the identified joint.
void SetAwake (WorldImpl &world, JointID id)
Wakes up the joined bodies.
BodyID GetBodyA (const WorldImpl &world, JointID id)
BodyID GetBodyB (const WorldImpl &world, JointID id)
Length2 GetLocalAnchorA (const WorldImpl &world, JointID id)
Length2 GetLocalAnchorB (const WorldImpl &world, JointID id)
Angle GetReferenceAngle (const WorldImpl &world, JointID id)
Detailed Description
Definition of a "world" implementation.
See also
World.
Member Typedef Documentation
Joints
using playrho::d2::WorldImpl::Joints = std::vector<JointID>
Joints container type.
Note
Cannot be container of Joint instances since joints are polymorphic types.
Member Enumeration Documentation
Flag
enum playrho::d2::WorldImpl::Flag : FlagsType private
Flag enumeration.
Enumerator
e_newFixture
New fixture.
e_locked
Locked.
e_substepping
Sub-stepping.
e_stepComplete
Step complete.
Used for sub-stepping.
See also
e_substepping.
Constructor & Destructor Documentation
WorldImpl()
playrho::d2::WorldImpl::WorldImpl (const WorldConf & def = GetDefaultWorldConf()) explicit
Constructs a world implementation for a world.
Parameters
def A customized world configuration or its default value.
Note
A lot more configurability can be had via the StepConf data that's given to the world's Step method.
Exceptions
InvalidArgument if the given max vertex radius is less than the min.
See also
Step.
~WorldImpl()
playrho::d2::WorldImpl::~WorldImpl () noexcept
Destructor.
All physics entities are destroyed and all dynamically allocated memory is released.
Member Function Documentation
Add()
bool playrho::d2::WorldImpl::Add (ContactKey key) private
Adds a contact for the proxies identified by the key if appropriate.
Adds a new contact object to represent a contact between proxy A and proxy B if all of the following are true:
The bodies of the fixtures of the proxies are not the one and the same.
No contact already exists for these two proxies.
The bodies of the proxies should collide (according to ShouldCollide).
The contact filter says the fixtures of the proxies should collide.
There exists a contact-create function for the pair of shapes of the proxies.
Postcondition
The size of the contacts collection is one greater-than it was before this method is called if it returns true.
Parameters
key ID's of dynamic tree entries identifying the fixture proxies involved.
Returns
true if a new contact was indeed added (and created), else false.
See also
bool ShouldCollide(const Body& lhs, const Body& rhs) noexcept.
AddToIsland()
void playrho::d2::WorldImpl::AddToIsland (Island & island, BodyID seed, BodyCounter & remNumBodies, ContactCounter & remNumContacts, JointCounter & remNumJoints) private
Adds to the island based off of a given "seed" body.
Postcondition
Contacts are listed in the island in the order that bodies provide those contacts.
Joints are listed the island in the order that bodies provide those joints.
Referenced by SolveReg().
Clear()
void playrho::d2::WorldImpl::Clear () noexcept
Clears this world.
Postcondition
The contents of this world have all been destroyed and this world's internal state reset as though it had just been constructed.
Referenced by ~WorldImpl().
CreateBody()
BodyID playrho::d2::WorldImpl::CreateBody (const BodyConf & def = GetDefaultBodyConf())
Creates a rigid body with the given configuration.
Warning
This function should not be used while the world is locked — as it is during callbacks. If it is, it will throw an exception or abort your program.
Note
No references to the configuration are retained. Its value is copied.
Postcondition
The created body will be present in the range returned from the GetBodies() method.
Parameters
def A customized body configuration or its default value.
Returns
Identifier of the newly created body which can later be destroyed by calling the Destroy(BodyID) method.
Exceptions
WrongState if this method is called while the world is locked.
LengthError if this operation would create more than MaxBodies.
See also
Destroy(BodyID), GetBodies.
Physical Entities.
CreateFixture()
FixtureID playrho::d2::WorldImpl::CreateFixture (BodyID body, const Shape & shape, const FixtureConf & def = GetDefaultFixtureConf(), bool resetMassData = true)
Creates a fixture with the given parameters.
Creates a fixture for attaching a shape and other characteristics to the given body. Fixtures automatically go away when the body is destroyed. Fixtures can also be manually removed and destroyed using the Destroy(Fixture*, bool), or DestroyFixtures() methods.
Note
This function should not be called if the world is locked.
Warning
This function is locked during callbacks.
Postcondition
After creating a new fixture, it will show up in the fixture enumeration returned by the GetFixtures() methods.
Parameters
body Body to associated new fixture with.
shape Shareable shape definition. Its vertex radius must be less than the minimum or more than the maximum allowed by the body's world.
def Initial fixture settings. Friction and density must be >= 0. Restitution must be > -infinity and < infinity.
resetMassData Whether or not to reset the mass data of the body.
Returns
Identifier for the created fixture.
Exceptions
WrongState if called while the world is "locked".
InvalidArgument if called for a shape with a vertex radius less than the minimum vertex radius.
InvalidArgument if called for a shape with a vertex radius greater than the maximum vertex radius.
See also
Destroy, GetFixtures
Physical Entities
CreateJoint()
JointID playrho::d2::WorldImpl::CreateJoint (const Joint & def)
Creates a joint to constrain one or more bodies.
Warning
This function is locked during callbacks.
Note
No references to the configuration are retained. Its value is copied.
Postcondition
The created joint will be present in the range returned from the GetJoints() method.
Returns
Identifier for the newly created joint which can later be destroyed by calling the Destroy(JointID) method.
Exceptions
WrongState if this method is called while the world is locked.
LengthError if this operation would create more than MaxJoints.
InvalidArgument if the given definition is not allowed.
See also
Physical Entities.
Destroy(JointID), GetJoints.
Referenced by playrho::d2::CreateJoint().
CreateProxies()
void playrho::d2::WorldImpl::CreateProxies (FixtureID id, Fixture & fixture, const Transformation & xfm, ProxyQueue & proxies, DynamicTree & tree, Length aabbExtension) static private
Creates proxies for every child of the given fixture's shape.
Note
This sets the proxy count to the child count of the shape.
Destroy() [1/4]
void playrho::d2::WorldImpl::Destroy (BodyID id)
Destroys the given body.
Destroys a given body that had previously been created by a call to this world's CreateBody(const BodyConf&) method.
Warning
This automatically deletes all associated shapes and joints.
This function is locked during callbacks.
Behavior is undefined if given a null body.
Behavior is undefined if the passed body was not created by this world.
Note
This function is locked during callbacks.
Postcondition
The destroyed body will no longer be present in the range returned from the GetBodies() method.
None of the body's fixtures will be present in the fixtures-for-proxies collection.
Parameters
id Body to destroy that had been created by this world.
Exceptions
WrongState if this method is called while the world is locked.
See also
CreateBody(const BodyConf&), GetBodies, GetFixturesForProxies.
Physical Entities.
Referenced by playrho::d2::Destroy().
Destroy() [2/4]
void playrho::d2::WorldImpl::Destroy (ContactID contact, Body * from) private
Destroys the given contact and removes it from its container.
This updates the contacts container, returns the memory to the allocator, and decrements the contact manager's contact count.
Parameters
contact Contact to destroy.
from From body.
Destroy() [3/4]
bool playrho::d2::WorldImpl::Destroy (FixtureID fixture, bool resetMassData = true)
Destroys a fixture.
This removes the fixture from the broad-phase and destroys all contacts associated with this fixture. All fixtures attached to a body are implicitly destroyed when the body is destroyed.
Warning
This function is locked during callbacks.
Note
Make sure to explicitly call Body::ResetMassData after fixtures have been destroyed.
Parameters
fixture the fixture to be removed.
resetMassData Whether or not to reset the mass data of the associated body.
See also
Body::ResetMassData.
Exceptions
WrongState if this method is called while the world is locked.
Destroy() [4/4]
void playrho::d2::WorldImpl::Destroy (JointID joint)
Destroys a joint.
Destroys a given joint that had previously been created by a call to this world's CreateJoint(const JointConf&) method.
Warning
This function is locked during callbacks.
Behavior is undefined if the passed joint was not created by this world.
Note
This may cause the connected bodies to begin colliding.
Postcondition
The destroyed joint will no longer be present in the range returned from the GetJoints() method.
Parameters
joint Joint to destroy that had been created by this world.
Exceptions
WrongState if this method is called while the world is locked.
See also
CreateJoint(const JointConf&), GetJoints.
Physical Entities.
DestroyContacts()
WorldImpl::DestroyContactsStats playrho::d2::WorldImpl::DestroyContacts (Contacts & contacts) private
Processes the narrow phase collision for the contacts collection.
This finds and destroys the contacts that need filtering and no longer should collide or that no longer have AABB-based overlapping fixtures. Those contacts that persist and have active bodies (either or both) get their Update methods called with the current contact listener as its argument. Essentially this really just purges contacts that are no longer relevant.
DestroyFixtures()
void playrho::d2::WorldImpl::DestroyFixtures (BodyID id)
Destroys fixtures of the given body.
Destroys all of the fixtures previously created for this body by the CreateFixture(const Shape&, const FixtureConf&, bool) method.
Note
This unconditionally calls the ResetMassData() method.
Postcondition
After this call, no fixtures will show up in the fixture enumeration returned by the GetFixtures() methods.
See also
CreateFixture, GetFixtures, ResetMassData.
Physical Entities
FindNewContacts()
ContactCounter playrho::d2::WorldImpl::FindNewContacts () private
Finds new contacts.
Finds and adds new valid contacts to the contacts container.
Note
The new contacts will all have overlapping AABBs.
Referenced by SolveReg().
GetBodies()
SizedRange< WorldImpl::Bodies::const_iterator > playrho::d2::WorldImpl::GetBodies () const inline noexcept
Gets the world body range for this constant world.
Gets a range enumerating the bodies currently existing within this world. These are the bodies that had been created from previous calls to the CreateBody(const BodyConf&) method that haven't yet been destroyed.
Returns
Body range that can be iterated over using its begin and end methods or using ranged-based for-loops.
See also
CreateBody(const BodyConf&).
GetBodiesForProxies()
SizedRange< WorldImpl::Bodies::const_iterator > playrho::d2::WorldImpl::GetBodiesForProxies () const inline noexcept
Gets the bodies-for-proxies range for this world.
Provides insight on what bodies have been queued for proxy processing during the next call to the world step method.
See also
Step.
GetBody() [1/2]
Body & playrho::d2::WorldImpl::GetBody (BodyID id)
Exceptions
std::out_of_range if given an invalid id.
GetBody() [2/2]
const Body & playrho::d2::WorldImpl::GetBody (BodyID id) const
Exceptions
std::out_of_range if given an invalid id.
Referenced by Destroy(), playrho::d2::GetAngularAcceleration(), playrho::d2::GetAngularDamping(), playrho::d2::GetBodyConf(), playrho::d2::GetContacts(), playrho::d2::GetFixtures(), playrho::d2::GetInvMass(), playrho::d2::GetInvRotInertia(), playrho::d2::GetJoints(), playrho::d2::GetLinearAcceleration(), playrho::d2::GetLinearDamping(), playrho::d2::GetLocalCenter(), playrho::d2::GetType(), playrho::d2::GetWorldCenter(), playrho::d2::IsAccelerable(), playrho::d2::IsEnabled(), playrho::d2::IsFixedRotation(), playrho::d2::IsImpenetrable(), playrho::d2::IsMassDataDirty(), playrho::d2::IsSleepingAllowed(), playrho::d2::IsSpeedable(), playrho::d2::SetAngularDamping(), playrho::d2::SetAwake(), playrho::d2::SetFixedRotation(), playrho::d2::SetLinearDamping(), playrho::d2::SetVelocity(), and playrho::d2::UnsetAwake().
GetBodyRange()
BodyCounter playrho::d2::WorldImpl::GetBodyRange () const noexcept
Gets the extent of the currently valid body range.
Note
This is one higher than the maxium BodyID that is in range for body related functions.
GetContacts()
SizedRange< WorldImpl::Contacts::const_iterator > playrho::d2::WorldImpl::GetContacts () const inline noexcept
Gets the world contact range.
Warning
contacts are created and destroyed in the middle of a time step. Use ContactListener to avoid missing contacts.
Returns
World contacts sized-range.
Referenced by Add().
GetFixturesForProxies()
SizedRange< WorldImpl::Fixtures::const_iterator > playrho::d2::WorldImpl::GetFixturesForProxies () const inline noexcept
Gets the fixtures-for-proxies range for this world.
Provides insight on what fixtures have been queued for proxy processing during the next call to the world step method.
See also
Step.
GetInvDeltaTime()
Frequency playrho::d2::WorldImpl::GetInvDeltaTime () const inline noexcept
Gets the inverse delta time.
Gets the inverse delta time that was set on construction or assignment, and updated on every call to the Step() method having a non-zero delta-time.
See also
Step.
GetJoints()
SizedRange< WorldImpl::Joints::const_iterator > playrho::d2::WorldImpl::GetJoints () const inline noexcept
Gets the world joint range.
Gets a range enumerating the joints currently existing within this world. These are the joints that had been created from previous calls to the CreateJoint(const JointConf&) method that haven't yet been destroyed.
Returns
World joints sized-range.
See also
CreateJoint(const JointConf&).
GetSoonestContact()
WorldImpl::ContactToiData playrho::d2::WorldImpl::GetSoonestContact (const Contacts & contacts, const ArrayAllocator< Contact > & buffer) static private noexcept
Gets the soonest contact.
This finds the contact with the lowest (soonest) time of impact.
Returns
Contact with the least time of impact and its time of impact, or null contact. A non-null contact will be enabled, not have sensors, be active, and impenetrable.
GetSubStepping()
bool playrho::d2::WorldImpl::GetSubStepping () const inline noexcept
Gets whether or not sub-stepping is enabled.
See also
SetSubStepping, IsStepComplete.
InternalTouchProxies()
void playrho::d2::WorldImpl::InternalTouchProxies (ProxyQueue & proxies, const Fixture & fixture) static private noexcept
Touches each proxy of the given fixture.
Note
This sets things up so that pairs may be created for potentially new contacts.
IsStepComplete()
bool playrho::d2::WorldImpl::IsStepComplete () const inline noexcept
Whether or not "step" is complete.
The "step" is completed when there are no more TOI events for the current time step.
Returns
true unless sub-stepping is enabled and the step method returned without finishing all of its sub-steps.
See also
GetSubStepping, SetSubStepping.
ProcessContactsForTOI()
WorldImpl::ProcessContactsOutput playrho::d2::WorldImpl::ProcessContactsForTOI (BodyID id, Island & island, Real toi, const StepConf & conf) private
Processes the contacts of a given body for TOI handling.
This does the following:
Advances the appropriate associated other bodies to the given TOI (advancing their sweeps and synchronizing their transforms to their new sweeps).
Updates the contact manifolds and touching statuses and notifies listener (if one given) of the appropriate contacts of the body.
Adds those contacts that are still enabled and still touching to the given island (or resets the other bodies advancement).
Adds to the island, those other bodies that haven't already been added of the contacts that got added.
Note
Precondition: there should be no lower TOI for which contacts have not already been processed.
Parameters
[in,out] id Identifier of the dynamic/accelerable body to process contacts for.
[in,out] island Island. On return this may contain additional contacts or bodies.
[in] toi Time of impact (TOI). Value between 0 and 1.
[in] conf Step configuration data.
Refilter()
void playrho::d2::WorldImpl::Refilter (FixtureID id)
Re-filter the fixture.
Note
Call this if you want to establish collision that was previously disabled by ShouldCollide(const Fixture&, const Fixture&).
See also
bool ShouldCollide(const Fixture& fixtureA, const Fixture& fixtureB)
SetEnabled()
void playrho::d2::WorldImpl::SetEnabled (BodyID id, bool flag)
Sets the enabled state of the body.
A disabled body is not simulated and cannot be collided with or woken up. If you pass a flag of true, all fixtures will be added to the broad-phase. If you pass a flag of false, all fixtures will be removed from the broad-phase and all contacts will be destroyed. Fixtures and joints are otherwise unaffected.
Note
A disabled body is still owned by a World object and remains in the world's body container.
You may continue to create/destroy fixtures and joints on disabled bodies.
Fixtures on a disabled body are implicitly disabled and will not participate in collisions, ray-casts, or queries.
Joints connected to a disabled body are implicitly disabled.
Exceptions
WrongState If call would change body's state when world is locked.
Postcondition
IsEnabled() returns the state given to this function.
See also
IsEnabled.
Referenced by playrho::d2::SetEnabled().
SetFilterData()
void playrho::d2::WorldImpl::SetFilterData (FixtureID id, Filter filter)
Sets the contact filtering data.
Note
This won't update contacts until the next time step when either parent body is speedable and awake.
This automatically calls Refilter.
SetMassData()
void playrho::d2::WorldImpl::SetMassData (BodyID id, const MassData & massData)
Set the mass properties to override the mass properties of the fixtures.
Note
This changes the center of mass position.
Creating or destroying fixtures can also alter the mass.
This function has no effect if the body isn't dynamic.
Parameters
id Body to set mass data for.
massData the mass properties.
Referenced by playrho::d2::SetMassData().
SetSensor()
void playrho::d2::WorldImpl::SetSensor (FixtureID id, bool value)
Sets whether the fixture is a sensor or not.
See also
IsSensor(FixtureID id).
Referenced by playrho::d2::SetSensor().
SetStepComplete()
void playrho::d2::WorldImpl::SetStepComplete (bool value) inline private noexcept
Sets the step complete state.
Postcondition
IsStepComplete() will return the value set.
See also
IsStepComplete.
SetSubStepping()
void playrho::d2::WorldImpl::SetSubStepping (bool flag) inline noexcept
Enables/disables single stepped continuous physics.
Note
This is not normally used. Enabling sub-stepping is meant for testing.
Postcondition
The GetSubStepping() method will return the value this method was called with.
See also
IsStepComplete, GetSubStepping.
SetTransformation()
void playrho::d2::WorldImpl::SetTransformation (BodyID id, Transformation xfm)
Sets the transformation of the body.
This instantly adjusts the body to have the new transformation.
Warning
Manipulating a body's transform can cause non-physical behavior!
Behavior is undefined if the value is invalid.
Note
Associated contacts may be flagged for updating on the next call to WorldImpl::Step.
Exceptions
WrongState If call would change body's state when world is locked.
SetType()
void playrho::d2::WorldImpl::SetType (BodyID id, playrho::BodyType type)
Sets the type of the given body.
Note
This may alter the body's mass and velocity.
Exceptions
WrongState if this method is called while the world is locked.
ShiftOrigin()
void playrho::d2::WorldImpl::ShiftOrigin (Length2 newOrigin)
Shifts the world origin.
Note
Useful for large worlds.
The body shift formula is: position -= newOrigin.
Postcondition
The "origin" of this world's bodies, joints, and the board-phase dynamic tree have been translated per the shift amount and direction.
Parameters
newOrigin the new origin with respect to the old origin
Exceptions
WrongState if this method is called while the world is locked.
SolveReg()
RegStepStats playrho::d2::WorldImpl::SolveReg (const StepConf & conf) private
Solves the step.
Finds islands, integrates and solves constraints, solves position constraints.
Note
This may miss collisions involving fast moving bodies and allow them to tunnel through each other.
SolveRegIslandViaGS()
IslandStats playrho::d2::WorldImpl::SolveRegIslandViaGS (const StepConf & conf, const Island & island) private
Solves the given island (regularly).
This:
Updates every island-body's sweep.pos0 to its sweep.pos1.
Updates every island-body's sweep.pos1 to the new normalized "solved" position for it.
Updates every island-body's velocity to the new accelerated, dampened, and "solved" velocity for it.
Synchronizes every island-body's transform (by updating it to transform one of the body's sweep).
Reports to the listener (if non-null).
Parameters
conf Time step configuration information.
island Island of bodies, contacts, and joints to solve for. Must contain at least one body, contact, or joint.
Warning
Behavior is undefined if the given island doesn't have at least one body, contact, or joint.
Returns
Island solver results.
< Time step.
Referenced by SolveReg().
SolveToi() [1/2]
ToiStepStats playrho::d2::WorldImpl::SolveToi (const StepConf & conf) private
Solves the step using successive time of impact (TOI) events.
Used for continuous physics.
Note
This is intended to detect and prevent the tunneling that the faster Solve method may miss.
Parameters
conf Time step configuration to use.
SolveToi() [2/2]
IslandStats playrho::d2::WorldImpl::SolveToi (ContactID contactID, const StepConf & conf) private
Solves collisions for the given time of impact.
Parameters
contactID Identifier of contact to solve for.
conf Time step configuration to solve for.
Note
Precondition 1: there is no contact having a lower TOI in this time step that has not already been solved for.
Precondition 2: there is not a lower TOI in the time step for which collisions have not already been processed.
SolveToiViaGS()
IslandStats playrho::d2::WorldImpl::SolveToiViaGS (const Island & island, const StepConf & conf) private
Solves the time of impact for bodies 0 and 1 of the given island.
This:
Updates position 0 of the sweeps of bodies 0 and 1.
Updates position 1 of the sweeps, the transforms, and the velocities of the other bodies in this island.
Precondition
island.bodies contains at least two bodies, the first two of which are bodies 0 and 1.
island.bodies contains appropriate other bodies of the contacts of the two bodies.
island.contacts contains the contact that specified the two identified bodies.
island.contacts contains appropriate other contacts of the two bodies.
Parameters
conf Time step configuration information.
island Island to do time of impact solving for.
Returns
Island solver results.
Step()
StepStats playrho::d2::WorldImpl::Step (const StepConf & conf)
Steps the world simulation according to the given configuration.
Performs position and velocity updating, sleeping of non-moving bodies, updating of the contacts, and notifying the contact listener of begin-contact, end-contact, pre-solve, and post-solve events.
Warning
Behavior is undefined if given a negative step time delta.
Varying the step time delta may lead to non-physical behaviors.
Note
Calling this with a zero step time delta results only in fixtures and bodies registered for proxy handling being processed. No physics is performed.
If the given velocity and position iterations are zero, this method doesn't do velocity or position resolutions respectively of the contacting bodies.
While body velocities are updated accordingly (per the sum of forces acting on them), body positions (barring any collisions) are updated as if they had moved the entire time step at those resulting velocities. In other words, a body initially at position 0 (p0) going velocity 0 (v0) fast with a sum acceleration of a, after time t and barring any collisions, will have a new velocity (v1) of v0 + (a * t) and a new position (p1) of p0 + v1 * t.
Postcondition
Static bodies are unmoved.
Kinetic bodies are moved based on their previous velocities.
Dynamic bodies are moved based on their previous velocities, gravity, applied forces, applied impulses, masses, damping, and the restitution and friction values of their fixtures when they experience collisions.
The bodies for proxies queue will be empty.
The fixtures for proxies queue will be empty.
Parameters
conf Configuration for the simulation step.
Returns
Statistics for the step.
Exceptions
WrongState if this method is called while the world is locked.
See also
GetBodiesForProxies, GetFixturesForProxies.
Synchronize() [1/2]
ContactCounter playrho::d2::WorldImpl::Synchronize (const Body & body, const Transformation & xfm1, const Transformation & xfm2, Real multiplier, Length extension) private
Synchronizes the given body.
This updates the broad phase dynamic tree data for all of the given body's fixtures.
Referenced by SolveReg().
Synchronize() [2/2]
ContactCounter playrho::d2::WorldImpl::Synchronize (const Fixture & fixture, const Transformation & xfm1, const Transformation & xfm2, Length2 displacement, Length extension) private
Synchronizes the given fixture.
This updates the broad phase dynamic tree data for all of the given fixture shape's children.
Update()
void playrho::d2::WorldImpl::Update (ContactID id, const ContactUpdateConf & conf) private
Updates the touching related state and notifies listener (if one given).
Note
Ideally this method is only called when a dependent change has occurred.
Touching related state depends on the following data:
The fixtures' sensor states.
The fixtures bodies' transformations.
The maxCirclesRatio per-step configuration state OR the maxDistanceIters per-step configuration state.
Parameters
id Identifies the contact to update.
conf Per-step configuration information.
See also
GetManifold, IsTouching
UpdateBody()
bool playrho::d2::WorldImpl::UpdateBody (Body & body, const Position & pos) static private
Updates the given body.
Updates the given body's sweep position 1, and its transformation.
Parameters
body Body to update.
pos New position to set the given body to.
Returns
true if body's contacts should be flagged for updating, otherwise false.
Friends And Related Function Documentation
ComputeMassData()
MassData ComputeMassData (const WorldImpl & world, BodyID id) related
Computes the body's mass data.
This basically accumulates the mass data over all fixtures.
Note
The center is the mass weighted sum of all fixture centers. Divide it by the mass to get the averaged center.
Returns
accumulated mass data for all fixtures associated with the given body.
GetBodyConf()
BodyConf GetBodyConf (const WorldImpl & world, BodyID id) related
Gets the body configuration for the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetContacts()
SizedRange< std::vector< KeyedContactPtr >::const_iterator > GetContacts (const WorldImpl & world, BodyID id) related
Gets the container of all contacts attached to this body.
Warning
This collection changes during the time step and you may miss some collisions if you don't use ContactListener.
GetDensity()
AreaDensity GetDensity (const WorldImpl & world, FixtureID id) related
Gets the density of this fixture.
Returns
Non-negative density (in mass per area).
Examples
World.cpp.
GetInvMass()
InvMass GetInvMass (const WorldImpl & world, BodyID id) related
Gets the inverse total mass of the body.
Returns
Value of zero or more representing the body's inverse mass (in 1/kg).
See also
SetMassData.
GetInvRotInertia()
InvRotInertia GetInvRotInertia (const WorldImpl & world, BodyID id) related
Gets the inverse rotational inertia of the body.
Returns
Inverse rotational inertia (in 1/kg-m^2).
GetLocalRotInertia()
RotInertia GetLocalRotInertia (const WorldImpl & world, BodyID id) related
Gets the rotational inertia of the body about the local origin.
Returns
the rotational inertia.
GetMass()
Mass GetMass (const WorldImpl & world, BodyID id) related
Gets the mass of the body.
Note
This may be the total calculated mass or it may be the set mass of the body.
Returns
Value of zero or more representing the body's mass.
See also
GetInvMass, SetMassData
GetRotInertia()
RotInertia GetRotInertia (const WorldImpl & world, BodyID id) related
Gets the rotational inertia of the body.
Parameters
world The world of the identified body.
id Body to get the rotational inertia for.
Returns
the rotational inertia.
GetToi()
Real GetToi (const WorldImpl & world, ContactID id) related
Gets the time of impact (TOI) as a fraction.
Note
This is only valid if a TOI has been set.
Returns
Time of impact fraction in the range of 0 to 1 if set (where 1 means no actual impact in current time slot), otherwise undefined.
IsAccelerable()
bool IsAccelerable (const WorldImpl & world, BodyID id) related
Is identified body "accelerable"?
Indicates whether the body is accelerable, i.e. whether it is effected by forces. Only Dynamic bodies are accelerable.
Returns
true if the body is accelerable, false otherwise.
IsAwake()
bool IsAwake (const WorldImpl & world, ContactID id) related
Gets the awake status of the specified contact.
See also
SetAwake(WorldImpl& world, ContactID id)
IsEnabled()
bool IsEnabled (const WorldImpl & world, BodyID id) related
Gets the enabled/disabled state of the body.
See also
SetEnabled.
Referenced by AddContactsToIsland().
IsFixedRotation()
bool IsFixedRotation (const WorldImpl & world, BodyID id) related
Gets whether the body has fixed rotation.
See also
SetFixedRotation(WorldImpl& world, BodyID id, bool value).
IsSensor()
bool IsSensor (const WorldImpl & world, FixtureID id) related
Is the specified fixture a sensor (non-solid)?
Returns
the true if the fixture is a sensor.
Referenced by AddContactsToIsland().
IsSpeedable()
bool IsSpeedable (const WorldImpl & world, BodyID id) related
Is identified body "speedable".
Is the body able to have a non-zero speed associated with it. Kinematic and Dynamic bodies are speedable. Static bodies are not.
Referenced by RemoveUnspeedablesFromIslanded().
IsTouching()
bool IsTouching (const WorldImpl & world, ContactID id) related
Is this contact touching?
Touching is defined as either:
This contact's manifold has more than 0 contact points, or
This contact has sensors and the two shapes of this contact are found to be overlapping.
Returns
true if this contact is said to be touching, false otherwise.
Referenced by AddContactsToIsland().
ResetMassData()
void ResetMassData (WorldImpl & world, BodyID id) related
Resets the mass data properties.
This resets the mass data to the sum of the mass properties of the fixtures.
Note
This method must be called after calling CreateFixture to update the body mass data properties unless SetMassData is used.
See also
SetMassData.
SetAwake()
void SetAwake (WorldImpl & world, ContactID id) related
Sets awake the bodies of the fixtures of the given contact.
See also
IsAwake(const WorldImpl& world, ContactID id)
SetEnabled()
void SetEnabled (WorldImpl & world, BodyID body, bool flag) related
Sets the enabled state of the body.
A disabled body is not simulated and cannot be collided with or woken up. If you pass a flag of true, all fixtures will be added to the broad-phase. If you pass a flag of false, all fixtures will be removed from the broad-phase and all contacts will be destroyed. Fixtures and joints are otherwise unaffected.
Note
A disabled body is still owned by a World object and remains in the world's body container.
You may continue to create/destroy fixtures and joints on disabled bodies.
Fixtures on a disabled body are implicitly disabled and will not participate in collisions, ray-casts, or queries.
Joints connected to a disabled body are implicitly disabled.
Exceptions
WrongState If call would change body's state when world is locked.
Postcondition
IsEnabled() returns the state given to this function.
See also
IsEnabled.
SetFixedRotation()
void SetFixedRotation (WorldImpl & world, BodyID id, bool value) related
Sets this body to have fixed rotation.
Note
This causes the mass to be reset.
See also
IsFixedRotation(const WorldImpl& world, BodyID id).
SetMassData()
void SetMassData (WorldImpl & world, BodyID id, const MassData & massData) related
Sets the mass properties to override the mass properties of the fixtures.
Note
This changes the center of mass position.
Creating or destroying fixtures can also alter the mass.
This function has no effect if the body isn't dynamic.
Parameters
world The world of the identified body.
id Identification of body.
massData the mass properties.
SetVelocity()
void SetVelocity (WorldImpl & world, BodyID id, const Velocity & value) related
Sets the body's velocity (linear and angular velocity).
Note
This method does nothing if this body is not speedable.
A non-zero velocity will awaken this body.
See also
SetAwake, SetUnderActiveTime.
Member Data Documentation
m_contacts
Contacts playrho::d2::WorldImpl::m_contacts private
Container of contacts.
Note
In the add pair stress-test, 401 bodies can have some 31000 contacts during a given time step.
Referenced by Clear(), GetContacts(), and SolveReg().
m_inv_dt0
Frequency playrho::d2::WorldImpl::m_inv_dt0 = 0 private
Inverse delta-t from previous step.
Used to compute time step ratio to support a variable time step.
Note
4-bytes large.
See also
Step.
Referenced by GetInvDeltaTime().
m_maxVertexRadius
Positive<Length> playrho::d2::WorldImpl::m_maxVertexRadius private
Maximum vertex radius.
This is the maximum shape vertex radius that any bodies' of this world should create fixtures for. Requests to create fixtures for shapes with vertex radiuses bigger than this must be rejected. As an upper bound, this value prevents shapes from getting associated with this world that would otherwise not be able to be simulated due to numerical issues. It can also be set below this upper bound to constrain the differences between shape vertex radiuses to possibly more limited visual ranges.
Referenced by GetMaxVertexRadius().
The documentation for this class was generated from the following files:
WorldImpl.hpp
WorldImpl.cpp
WorldImplBody.hpp
WorldImplContact.hpp
WorldImplFixture.hpp
WorldImplJoint.hpp