PlayRho: playrho::d2::Manifold Class Reference
playrho::d2::Manifold Class Reference
A collision description for the collision two convex shapes.
#include <Manifold.hpp>
Classes
struct Conf
Configuration data for manifold calculation.
struct Point
Data for a point of collision in a Manifold.
struct PointArray
Point array structure.
Public Types
enum Type : std::uint8_t { e_unset, e_circles, e_faceA, e_faceB }
Manifold type.
using size_type = std::remove_const< decltype(MaxManifoldPoints)>::type
Size type.
using CfIndex = ContactFeature::Index
Contact feature index.
using CfType = ContactFeature::Type
Contact feature type.
Public Member Functions
Manifold ()=default
Default constructor.
Manifold (const Manifold &copy)=default
Copy constructor.
PLAYRHO_CONSTEXPR Type GetType () const noexcept
Gets the type of this manifold.
PLAYRHO_CONSTEXPR size_type GetPointCount () const noexcept
Gets the manifold point count.
PLAYRHO_CONSTEXPR ContactFeature GetContactFeature (size_type index) const noexcept
Gets the contact feature for the given index.
PLAYRHO_CONSTEXPR Momentum2 GetContactImpulses (size_type index) const noexcept
Gets the contact impulses for the given index.
void SetContactImpulses (size_type index, Momentum2 value) noexcept
Sets the contact impulses for the given index.
const Point & GetPoint (size_type index) const noexcept
Gets the point identified by the given index.
void SetPointImpulses (size_type index, Momentum n, Momentum t)
Sets the point impulses for the given index.
void AddPoint (const Point &mp) noexcept
Adds a new point.
void AddPoint (CfType type, CfIndex index, Length2 point) noexcept
Adds a new point with the given data.
PLAYRHO_CONSTEXPR UnitVec GetLocalNormal () const noexcept
Gets the local normal for a face-type manifold.
PLAYRHO_CONSTEXPR Length2 GetLocalPoint () const noexcept
Gets the local point.
PLAYRHO_CONSTEXPR Length2 GetOpposingPoint (size_type index) const noexcept
Gets the opposing point.
Static Public Member Functions
static Manifold GetForCircles (Length2 vA, CfIndex iA, Length2 vB, CfIndex iB) noexcept
Gets a circles-typed manifold with one point.
static Manifold GetForFaceA (UnitVec normalA, Length2 faceA) noexcept
Gets a face A typed manifold.
static Manifold GetForFaceA (UnitVec ln, Length2 lp, const Point &mp1) noexcept
Gets a face A typed manifold.
static Manifold GetForFaceA (UnitVec ln, Length2 lp, const Point &mp1, const Point &mp2) noexcept
Gets a face A typed manifold.
static Manifold GetForFaceB (UnitVec ln, Length2 lp) noexcept
Gets a face B typed manifold.
static Manifold GetForFaceB (UnitVec ln, Length2 lp, const Point &mp1) noexcept
Gets a face B typed manifold.
static Manifold GetForFaceB (UnitVec ln, Length2 lp, const Point &mp1, const Point &mp2) noexcept
Gets a face B typed manifold.
static Manifold GetForFaceA (UnitVec na, CfIndex ia, Length2 pa) noexcept
Gets the face A manifold for the given data.
static Manifold GetForFaceB (UnitVec nb, CfIndex ib, Length2 pb) noexcept
Gets the face B manifold for the given data.
static Manifold GetForFaceA (UnitVec na, CfIndex ia, Length2 pa, CfType tb0, CfIndex ib0, Length2 pb0) noexcept
Gets the face A manifold for the given data.
static Manifold GetForFaceB (UnitVec nb, CfIndex ib, Length2 pb, CfType ta0, CfIndex ia0, Length2 pa0) noexcept
Gets the face B manifold for the given data.
static Manifold GetForFaceA (UnitVec na, CfIndex ia, Length2 pa, CfType tb0, CfIndex ib0, Length2 pb0, CfType tb1, CfIndex ib1, Length2 pb1) noexcept
Gets the face A manifold for the given data.
static Manifold GetForFaceB (UnitVec nb, CfIndex ib, Length2 pb, CfType ta0, CfIndex ia0, Length2 pa0, CfType ta1, CfIndex ia1, Length2 pa1) noexcept
Gets the face B manifold for the given data.
Private Member Functions
PLAYRHO_CONSTEXPR Manifold (Type t, UnitVec ln, Length2 lp, size_type n, const PointArray &mpa) noexcept
Constructs manifold with array of points using the given values.
Private Attributes
Type m_type = e_unset
Type of collision this manifold is associated with (1-byte).
size_type m_pointCount = 0
Number of defined manifold points (1-byte).
UnitVec m_localNormal = GetInvalid<decltype(m_localNormal)>()
Local normal.
Length2 m_localPoint = GetInvalid<Length2>()
Local point.
PointArray m_points
Points of contact (at least 40-bytes).
Related Functions
(Note that these are not member functions.)
bool operator== (const Manifold &lhs, const Manifold &rhs) noexcept
Manifold equality operator.
bool operator!= (const Manifold &lhs, const Manifold &rhs) noexcept
Manifold inequality operator.
Manifold CollideShapes (const DistanceProxy &shapeA, const Transformation &xfA, const DistanceProxy &shapeB, const Transformation &xfB, Manifold::Conf conf=GetDefaultManifoldConf())
Calculates the relevant collision manifold.
template<>
PLAYRHO_CONSTEXPR bool IsValid (const d2::Manifold &value) noexcept
Gets whether the given manifold is valid.
WorldManifold GetWorldManifold (const Manifold &manifold, Transformation xfA, Length radiusA, Transformation xfB, Length radiusB)
Gets the world manifold for the given data.
Detailed Description
A collision description for the collision two convex shapes.
This describes zero, one, or two points of contact for which impulses should be applied to most naturally resolve those contacts. Ideally the manifold is calculated at the earliest point in time of contact occurring. The further past that time, the less natural contact resolution of solid bodies will be - eventually resulting in oddities like tunneling.
Multiple types of contact are supported: clip point versus plane with radius, point versus point with radius (circles). Contacts are stored in this way so that position correction can account for movement, which is critical for continuous physics. All contact scenarios must be expressed in one of these types.
Conceptually, a manifold represents the intersection of two convex sets (which is itself a convex set) and a solution for moving the sets away from each other to eliminate the intersection.
Note
The local point and local normal usage depends on the manifold type. For details, see the documentation associated with the different manifold types.
Every point adds computational overhead to the collision response calculation - so express collision manifolds with one point if possible instead of two.
While this data structure is at least 58-bytes large (60-bytes on one 64-bit platform), it is intentionally 64-byte aligned making it 64-byte large (on 64-bit platforms with 4-byte Real).
See also
Contact, PositionConstraint, VelocityConstraint
https://en.wikipedia.org/wiki/Convex_set
http://box2d.org/files/GDC2007/GDC2007_Catto_Erin_Physics2.ppt
Member Enumeration Documentation
Type
enum playrho::d2::Manifold::Type : std::uint8_t
Manifold type.
Note
This is by design a 1-byte sized type.
Enumerator
e_unset
Unset type.
Manifold is unset. For manifolds of this type: the point count is zero, point data is undefined, and all other properties are invalid.
e_circles
Circles type.
Manifold is for circle-to-circle like collisions.
Note
For manifolds of this type: the local point is local center of "circle-A" (where shape A wasn't necessarily a circle but treating it as such is useful), the local normal is invalid (and unused) and, the point count will be zero or one where the contact feature will be ContactFeature{e_vertex, i, e_vertex, j} where i and j are indexes of the vertexes of shapes A and B respectively.
e_faceA
Face-A type.
Indicates: local point is center of face A, local normal is normal on shape A, and the local points of Point instances are the local center of circle B or a clip point of polygon B where the contact feature will be ContactFeature{e_face, i, e_vertex, j} or ContactFeature{e_face, i, e_face, j} where i and j are indexes for the vertex or edge of shapes A and B respectively..
e_faceB
Face-B type.
Indicates: local point is center of face B, local normal is normal on shape B, and the local points of Point instances are the local center of circle A or a clip point of polygon A where the contact feature will be ContactFeature{e_face, i, e_vertex, j} or ContactFeature{e_face, i, e_face, j} where i and j are indexes for the vertex or edge of shapes A and B respectively..
Constructor & Destructor Documentation
Manifold() [1/2]
playrho::d2::Manifold::Manifold () default
Default constructor.
Constructs an unset-type manifold. For an unset-type manifold: point count is zero, point data is undefined, and all other properties are invalid.
Manifold() [2/2]
PLAYRHO_CONSTEXPR playrho::d2::Manifold::Manifold (Type t, UnitVec ln, Length2 lp, size_type n, const PointArray & mpa) inline private noexcept
Constructs manifold with array of points using the given values.
Parameters
t Manifold type.
ln Local normal.
lp Local point.
n number of points defined in array.
mpa Manifold point array.
Member Function Documentation
AddPoint()
void playrho::d2::Manifold::AddPoint (const Point & mp) inline noexcept
Adds a new point.
This can be called once for circle type manifolds, and up to twice for face-A or face-B type manifolds. GetPointCount() can be called to find out how many points have already been added.
Warning
Behavior is undefined if this object's type is e_unset.
Behavior is undefined if this is called more than twice.
GetContactImpulses()
PLAYRHO_CONSTEXPR Momentum2 playrho::d2::Manifold::GetContactImpulses (size_type index) const inline noexcept
Gets the contact impulses for the given index.
Returns
Pair of impulses where the first impulse is the "normal impulse" and the second impulse is the "tangent impulse".
GetForCircles()
static Manifold playrho::d2::Manifold::GetForCircles (Length2 vA, CfIndex iA, Length2 vB, CfIndex iB) inline static noexcept
Gets a circles-typed manifold with one point.
Parameters
vA Local center of "circle" A.
iA Index of vertex from shape A representing the local center of "circle" A.
vB Local center of "circle" B.
iB Index of vertex from shape B representing the local center of "circle" B.
GetForFaceA() [1/3]
static Manifold playrho::d2::Manifold::GetForFaceA (UnitVec normalA, Length2 faceA) inline static noexcept
Gets a face A typed manifold.
Parameters
normalA Local normal of the face from polygon A.
faceA Any point in local coordinates on the face whose normal was provided.
GetForFaceA() [2/3]
static Manifold playrho::d2::Manifold::GetForFaceA (UnitVec ln, Length2 lp, const Point & mp1) inline static noexcept
Gets a face A typed manifold.
Parameters
ln Normal on polygon A.
lp Center of face A.
mp1 Manifold point 1 (of 1).
GetForFaceA() [3/3]
static Manifold playrho::d2::Manifold::GetForFaceA (UnitVec ln, Length2 lp, const Point & mp1, const Point & mp2) inline static noexcept
Gets a face A typed manifold.
Parameters
ln Normal on polygon A.
lp Center of face A.
mp1 Manifold point 1 (of 2).
mp2 Manifold point 2 (of 2).
GetForFaceB() [1/3]
static Manifold playrho::d2::Manifold::GetForFaceB (UnitVec ln, Length2 lp) inline static noexcept
Gets a face B typed manifold.
Parameters
ln Normal on polygon B.
lp Center of face B.
GetForFaceB() [2/3]
static Manifold playrho::d2::Manifold::GetForFaceB (UnitVec ln, Length2 lp, const Point & mp1) inline static noexcept
Gets a face B typed manifold.
Parameters
ln Normal on polygon B.
lp Center of face B.
mp1 Manifold point 1.
GetForFaceB() [3/3]
static Manifold playrho::d2::Manifold::GetForFaceB (UnitVec ln, Length2 lp, const Point & mp1, const Point & mp2) inline static noexcept
Gets a face B typed manifold.
Parameters
ln Normal on polygon B.
lp Center of face B.
mp1 Manifold point 1 (of 2).
mp2 Manifold point 2 (of 2).
GetLocalNormal()
PLAYRHO_CONSTEXPR UnitVec playrho::d2::Manifold::GetLocalNormal () const inline noexcept
Gets the local normal for a face-type manifold.
Note
Only valid for face-A or face-B type manifolds.
Warning
Behavior is undefined for unset (e_unset) type manifolds.
Behavior is undefined for circles (e_circles) type manifolds.
Returns
Local normal if the manifold type is face A or face B, else invalid value.
Referenced by playrho::d2::GetPSM().
GetLocalPoint()
PLAYRHO_CONSTEXPR Length2 playrho::d2::Manifold::GetLocalPoint () const inline noexcept
Gets the local point.
This is the: local center of "circle" A for circles-type manifolds; the center of face A for face-A-type manifolds; or the center of face B for face-B-type manifolds.
Note
Only valid for circle, face-A, or face-B type manifolds.
Warning
Behavior is undefined for unset (e_unset) type manifolds.
Returns
Local point.
Referenced by playrho::d2::GetPSM().
GetPointCount()
PLAYRHO_CONSTEXPR size_type playrho::d2::Manifold::GetPointCount () const inline noexcept
Gets the manifold point count.
This is the count of contact points for this manifold. Only up to this many points can be validly accessed using the GetPoint() method.
Note
Non-zero values indicate that the two shapes are touching.
Returns
Value between 0 and MaxManifoldPoints.
See also
MaxManifoldPoints.
AddPoint().
GetPoint().
Referenced by playrho::d2::World::InternalDestroy().
GetType()
PLAYRHO_CONSTEXPR Type playrho::d2::Manifold::GetType () const inline noexcept
Gets the type of this manifold.
Note
This must be a constant expression in order to use it in the context of the IsValid specialized template function for it.
Referenced by playrho::d2::GetPSM(), and playrho::d2::GetWorldManifold().
SetContactImpulses()
void playrho::d2::Manifold::SetContactImpulses (size_type index, Momentum2 value) inline noexcept
Sets the contact impulses for the given index.
Sets the contact impulses for the given index where the first impulse is the "normal impulse" and the second impulse is the "tangent impulse".
Friends And Related Function Documentation
CollideShapes()
Manifold CollideShapes (const DistanceProxy & shapeA, const Transformation & xfA, const DistanceProxy & shapeB, const Transformation & xfB, Manifold::Conf conf = GetDefaultManifoldConf()) related
Calculates the relevant collision manifold.
Note
The returned touching state information typically agrees with that returned from the distance-proxy-based TestOverlap function. This is not always the case however especially when the separation or overlap distance is closer to zero.
GetWorldManifold()
WorldManifold GetWorldManifold (const Manifold & manifold, Transformation xfA, Length radiusA, Transformation xfB, Length radiusB) related
Gets the world manifold for the given data.
Precondition
The given manifold input has between 0 and 2 points.
Parameters
manifold Manifold to use. Uses the manifold's type, local point, local normal, point-count, and the indexed-points' local point data.
xfA Transformation A.
radiusA Radius of shape A.
xfB Transformation B.
radiusB Radius of shape B.
Returns
World manifold value for the given inputs which will have the same number of points as the given manifold has. The returned world manifold points will be the mid-points of the manifold intersection.
IsValid()
PLAYRHO_CONSTEXPR bool IsValid (const d2::Manifold & value) related
Gets whether the given manifold is valid.
operator!=()
bool operator!= (const Manifold & lhs, const Manifold & rhs) related
Manifold inequality operator.
Determines whether the two given manifolds are not equal.
operator==()
bool operator== (const Manifold & lhs, const Manifold & rhs) related
Manifold equality operator.
Note
In-so-far as manifold points are concerned, order doesn't matter; only whether the two manifolds have the same point set.
Member Data Documentation
m_localNormal
UnitVec playrho::d2::Manifold::m_localNormal = GetInvalid<decltype(m_localNormal)>() private
Local normal.
Exact usage depends on manifold type (8-bytes).
Note
Invalid for the unset and circle manifold types.
Referenced by GetLocalNormal().
m_localPoint
Length2 playrho::d2::Manifold::m_localPoint = GetInvalid<Length2>() private
Local point.
Exact usage depends on manifold type (8-bytes).
Note
Invalid for the unset manifold type.
Referenced by GetLocalPoint().
m_points
PointArray playrho::d2::Manifold::m_points private
Points of contact (at least 40-bytes).
See also
pointCount.
Referenced by GetContactFeature(), GetContactImpulses(), GetOpposingPoint(), GetPoint(), SetContactImpulses(), and SetPointImpulses().
The documentation for this class was generated from the following files:
Manifold.hpp
WorldManifold.hpp