PlayRho: playrho::DistanceJoint Class Reference
playrho::DistanceJoint Class Reference
Joint Classes
Distance Joint.
#include <DistanceJoint.hpp>
Public Member Functions
DistanceJoint (const DistanceJointDef &data)
Initializing constructor.
void Accept (JointVisitor &visitor) const override
Accepts a visitor.
Length2D GetAnchorA () const override
Get the anchor point on bodyA in world coordinates.
Length2D GetAnchorB () const override
Get the anchor point on bodyB in world coordinates.
Momentum2D GetLinearReaction () const override
Get the linear reaction.
AngularMomentum GetAngularReaction () const override
Gets the angular reaction.
Length2D GetLocalAnchorA () const noexcept
Gets the local anchor point relative to bodyA's origin.
Length2D GetLocalAnchorB () const noexcept
Gets the local anchor point relative to bodyB's origin.
void SetLength (Length length) noexcept
Sets the natural length.
Length GetLength () const noexcept
Gets the length.
void SetFrequency (NonNegative< Frequency > frequency) noexcept
Sets frequency.
NonNegative< Frequency > GetFrequency () const noexcept
Gets the frequency.
void SetDampingRatio (Real ratio) noexcept
Sets the damping ratio.
Real GetDampingRatio () const noexcept
Gets damping ratio.
Public Member Functions inherited from playrho::Joint
Body * GetBodyA () const noexcept
Gets the first body attached to this joint.
Body * GetBodyB () const noexcept
Gets the second body attached to this joint.
void * GetUserData () const noexcept
Get the user data pointer.
void SetUserData (void *data) noexcept
Set the user data pointer.
bool GetCollideConnected () const noexcept
Gets collide connected.
virtual void ShiftOrigin (const Length2D newOrigin)
Shifts the origin for any points stored in world coordinates.
Static Public Member Functions
static bool IsOkay (const DistanceJointDef &data) noexcept
Is the given definition okay.
Static Public Member Functions inherited from playrho::Joint
static bool IsOkay (const JointDef &def) noexcept
Is the given definition okay.
Private Member Functions
void InitVelocityConstraints (BodyConstraintsMap &bodies, const StepConf &step, const ConstraintSolverConf &) override
Initializes velocity constraint data based on the given solver data.
bool SolveVelocityConstraints (BodyConstraintsMap &bodies, const StepConf &step) override
Solves velocity constraint.
bool SolvePositionConstraints (BodyConstraintsMap &bodies, const ConstraintSolverConf &conf) const override
Solves the position constraint.
Private Attributes
Length2D m_localAnchorA
Local anchor A.
Length2D m_localAnchorB
Local anchor B.
Length m_length
Length.
NonNegative< Frequency > m_frequency = NonNegative<Frequency>{0}
Frequency.
Real m_dampingRatio
Damping ratio.
Momentum m_impulse = Momentum{0}
Impulse.
InvMass m_invGamma
Inverse gamma.
LinearVelocity m_bias
Bias.
Mass m_mass
Mass.
UnitVec2 m_u
"u" directional.
Length2D m_rA
Relative A position.
Length2D m_rB
Relative B position.
Related Functions
(Note that these are not member functions.)
DistanceJointDef GetDistanceJointDef (const DistanceJoint &joint) noexcept
Gets the definition data for the given joint.
Related Functions inherited from playrho::Joint
bool IsEnabled (const Joint &j) noexcept
Short-cut function to determine if both bodies are enabled.
void SetAwake (Joint &j) noexcept
Wakes up the joined bodies.
JointCounter GetWorldIndex (const Joint *joint)
Gets the world index of the given joint.
JointType GetType (const Joint &joint) noexcept
Gets the type of the given joint.
Additional Inherited Members
Public Types inherited from playrho::Joint
enum LimitState { e_inactiveLimit, e_atLowerLimit, e_atUpperLimit, e_equalLimits }
Limit state.
Protected Member Functions inherited from playrho::Joint
Joint (const JointDef &def)
Initializing constructor.
Detailed Description
Distance Joint.
A distance joint constrains two points on two bodies to remain at a fixed distance from each other. You can view this as a massless, rigid rod.
Member Function Documentation
AngularMomentum playrho::DistanceJoint::GetAngularReaction () const override virtual
Gets the angular reaction.
Note
This is always zero for a distance joint.
Implements playrho::Joint.
void playrho::DistanceJoint::InitVelocityConstraints (BodyConstraintsMap & bodies, const StepConf & step, const ConstraintSolverConf & conf) override private virtual
Initializes velocity constraint data based on the given solver data.
Note
This MUST be called prior to calling SolveVelocityConstraints.
See also
SolveVelocityConstraints.
Implements playrho::Joint.
Referenced by GetLocalAnchorB().
void playrho::DistanceJoint::SetLength (Length length) inline noexcept
Sets the natural length.
Note
Manipulating the length can lead to non-physical behavior when the frequency is zero.
Referenced by GetLocalAnchorB().
bool playrho::DistanceJoint::SolvePositionConstraints (BodyConstraintsMap & bodies, const ConstraintSolverConf & conf) const override private virtual
Solves the position constraint.
Returns
true if the position errors are within tolerance.
Implements playrho::Joint.
Referenced by GetLocalAnchorB().
bool playrho::DistanceJoint::SolveVelocityConstraints (BodyConstraintsMap & bodies, const StepConf & step) override private virtual
Solves velocity constraint.
Precondition
InitVelocityConstraints has been called.
See also
InitVelocityConstraints.
Returns
true if velocity is "solved", false otherwise.
Implements playrho::Joint.
Referenced by GetLocalAnchorB().
Friends And Related Function Documentation
DistanceJointDef GetDistanceJointDef (const DistanceJoint & joint) related
Gets the definition data for the given joint.
The documentation for this class was generated from the following files:
DistanceJoint.hpp
DistanceJoint.cpp
DistanceJointDef.hpp