PlayRho: playrho::EdgeShape Class Reference
playrho::EdgeShape Class Reference
Shape Classes
Edge shape.
#include <EdgeShape.hpp>
Classes
struct Conf
Configuration data for edge shapes.
Public Member Functions
EdgeShape (const Conf &conf=GetDefaultConf()) noexcept
Initializing constructor.
EdgeShape (Length2D v1, Length2D v2, const Conf &conf=GetDefaultConf()) noexcept
Initializing constructor.
EdgeShape (const EdgeShape &other)=default
Copy constructor.
EdgeShape (EdgeShape &&other)=default
Move constructor.
EdgeShape & operator= (const EdgeShape &other)=default
Copy assignment operator.
EdgeShape & operator= (EdgeShape &&other)=default
Move assignment operator.
ChildCounter GetChildCount () const noexcept override
Gets the number of child primitives of the shape.
DistanceProxy GetChild (ChildCounter index) const override
Gets the child for the given index.
MassData GetMassData () const noexcept override
Gets the mass properties of this shape using its dimensions and density.
void Accept (ShapeVisitor &visitor) const override
Accepts a visitor.
void Set (Length2D v1, Length2D v2)
Sets this as an isolated edge.
Length2D GetVertex1 () const noexcept
Gets vertex number 1 (of 2).
Length2D GetVertex2 () const noexcept
Gets vertex number 2 (of 2).
UnitVec2 GetNormal1 () const noexcept
Gets normal number 1 (of 2).
UnitVec2 GetNormal2 () const noexcept
Gets normal number 2 (of 2).
Public Member Functions inherited from playrho::Shape
NonNegative< Length > GetVertexRadius () const noexcept
Gets the vertex radius.
void SetVertexRadius (NonNegative< Length > vertexRadius) noexcept
Sets the vertex radius.
NonNegative< Density > GetDensity () const noexcept
Gets the density of this fixture.
void SetDensity (NonNegative< Density > density) noexcept
Sets the density of this fixture.
Real GetFriction () const noexcept
Gets the coefficient of friction.
void SetFriction (NonNegative< Real > friction) noexcept
Sets the coefficient of friction.
Real GetRestitution () const noexcept
Gets the coefficient of restitution.
void SetRestitution (Finite< Real > restitution) noexcept
Sets the coefficient of restitution.
Static Public Member Functions
static constexpr Length GetDefaultVertexRadius () noexcept
Gets the default vertex radius.
static constexpr Conf GetDefaultConf () noexcept
Gets the default configuration for an EdgeShape.
Private Attributes
Length2D m_vertices [2]
Vertices.
UnitVec2 m_normals [2]
Normals.
Additional Inherited Members
Protected Member Functions inherited from playrho::Shape
Shape ()=default
Default constructor.
Shape (const ShapeDef &conf) noexcept
Initializing constructor.
Shape (const Shape &other)=default
Copy constructor.
Shape (Shape &&other)=default
Move constructor.
Shape & operator= (const Shape &other)=default
Copy assignment operator.
Shape & operator= (Shape &&other)=default
Move assignment operator.
Related Functions inherited from playrho::Shape
AABB ComputeAABB (const Shape &shape, const Transformation &xf) noexcept
Computes the AABB for the given shape with the given transformation.
RayCastOutput RayCast (const Shape &shape, ChildCounter childIndex, const RayCastInput &input, const Transformation &transform) noexcept
Cast a ray against the child of the given shape.
NonNegative< Length > GetVertexRadius (const Shape &shape) noexcept
Gets the vertex radius of the given shape.
bool TestPoint (const Shape &shape, Length2D point) noexcept
Test a point for containment in the given shape.
Detailed Description
Edge shape.
A line segment (edge) shape. These can be connected in chains or loops to other edge shapes. The connectivity information is used to ensure correct contact normals.
Note
This data structure is 56-bytes.
Member Function Documentation
DistanceProxy playrho::EdgeShape::GetChild (ChildCounter index) const inline override virtual
Gets the child for the given index.
Parameters
index Index to a child element of the shape. Value must be less than the number of child primitives of the shape.
Note
The shape must remain in scope while the proxy is in use.
Exceptions
InvalidArgument if the given index is out of range.
See also
GetChildCount
Implements playrho::Shape.
Referenced by EdgeShape().
ChildCounter playrho::EdgeShape::GetChildCount () const inline override virtual noexcept
Gets the number of child primitives of the shape.
Returns
Non-negative count.
Implements playrho::Shape.
Referenced by EdgeShape().
MassData playrho::EdgeShape::GetMassData () const override virtual noexcept
Gets the mass properties of this shape using its dimensions and density.
Returns
Mass data for this shape.
Implements playrho::Shape.
Referenced by EdgeShape().
The documentation for this class was generated from the following files:
EdgeShape.hpp
EdgeShape.cpp