PlayRho: playrho::FrictionJoint Class Reference
playrho::FrictionJoint Class Reference
Joint Classes
Friction joint.
#include <FrictionJoint.hpp>
Public Member Functions
FrictionJoint (const FrictionJointDef &def)
Initializing constructor.
void Accept (JointVisitor &visitor) const override
Accepts a visitor.
Length2D GetAnchorA () const override
Get the anchor point on bodyA in world coordinates.
Length2D GetAnchorB () const override
Get the anchor point on bodyB in world coordinates.
Momentum2D GetLinearReaction () const override
Get the linear reaction on bodyB at the joint anchor.
AngularMomentum GetAngularReaction () const override
Get the angular reaction on bodyB.
Length2D GetLocalAnchorA () const
The local anchor point relative to bodyA's origin.
Length2D GetLocalAnchorB () const
The local anchor point relative to bodyB's origin.
void SetMaxForce (NonNegative< Force > force)
Set the maximum friction force in N.
NonNegative< Force > GetMaxForce () const
Get the maximum friction force in N.
void SetMaxTorque (NonNegative< Torque > torque)
Set the maximum friction torque in N*m.
NonNegative< Torque > GetMaxTorque () const
Get the maximum friction torque in N*m.
Public Member Functions inherited from playrho::Joint
Body * GetBodyA () const noexcept
Gets the first body attached to this joint.
Body * GetBodyB () const noexcept
Gets the second body attached to this joint.
void * GetUserData () const noexcept
Get the user data pointer.
void SetUserData (void *data) noexcept
Set the user data pointer.
bool GetCollideConnected () const noexcept
Gets collide connected.
virtual void ShiftOrigin (const Length2D newOrigin)
Shifts the origin for any points stored in world coordinates.
Private Member Functions
void InitVelocityConstraints (BodyConstraintsMap &bodies, const StepConf &step, const ConstraintSolverConf &conf) override
Initializes velocity constraint data based on the given solver data.
bool SolveVelocityConstraints (BodyConstraintsMap &bodies, const StepConf &step) override
Solves velocity constraint.
bool SolvePositionConstraints (BodyConstraintsMap &bodies, const ConstraintSolverConf &conf) const override
Solves the position constraint.
Private Attributes
Length2D m_localAnchorA
Local anchor A.
Length2D m_localAnchorB
Local anchor B.
NonNegative< Force > m_maxForce = NonNegative<Force>{0}
Max force.
NonNegative< Torque > m_maxTorque = NonNegative<Torque>{0}
Max torque.
Momentum2D m_linearImpulse = Momentum2D{}
Linear impulse.
AngularMomentum m_angularImpulse = AngularMomentum{0}
Angular impulse.
Length2D m_rA
Relative A.
Length2D m_rB
Relative B.
Mass22 m_linearMass
2x2 linear mass matrix in kilograms.
RotInertia m_angularMass
Angular mass.
Related Functions
(Note that these are not member functions.)
FrictionJointDef GetFrictionJointDef (const FrictionJoint &joint) noexcept
Gets the definition data for the given joint.
Related Functions inherited from playrho::Joint
bool IsEnabled (const Joint &j) noexcept
Short-cut function to determine if both bodies are enabled.
void SetAwake (Joint &j) noexcept
Wakes up the joined bodies.
JointCounter GetWorldIndex (const Joint *joint)
Gets the world index of the given joint.
JointType GetType (const Joint &joint) noexcept
Gets the type of the given joint.
Additional Inherited Members
Public Types inherited from playrho::Joint
enum LimitState { e_inactiveLimit, e_atLowerLimit, e_atUpperLimit, e_equalLimits }
Limit state.
Static Public Member Functions inherited from playrho::Joint
static bool IsOkay (const JointDef &def) noexcept
Is the given definition okay.
Protected Member Functions inherited from playrho::Joint
Joint (const JointDef &def)
Initializing constructor.
Detailed Description
Friction joint.
This is used for top-down friction. It provides 2D translational friction and angular friction.
Member Function Documentation
void playrho::FrictionJoint::InitVelocityConstraints (BodyConstraintsMap & bodies, const StepConf & step, const ConstraintSolverConf & conf) override private virtual
Initializes velocity constraint data based on the given solver data.
Note
This MUST be called prior to calling SolveVelocityConstraints.
See also
SolveVelocityConstraints.
Implements playrho::Joint.
Referenced by GetLocalAnchorB().
bool playrho::FrictionJoint::SolvePositionConstraints (BodyConstraintsMap & bodies, const ConstraintSolverConf & conf) const override private virtual
Solves the position constraint.
Returns
true if the position errors are within tolerance.
Implements playrho::Joint.
Referenced by GetLocalAnchorB().
bool playrho::FrictionJoint::SolveVelocityConstraints (BodyConstraintsMap & bodies, const StepConf & step) override private virtual
Solves velocity constraint.
Precondition
InitVelocityConstraints has been called.
See also
InitVelocityConstraints.
Returns
true if velocity is "solved", false otherwise.
Implements playrho::Joint.
Referenced by GetLocalAnchorB().
Friends And Related Function Documentation
FrictionJointDef GetFrictionJointDef (const FrictionJoint & joint) related
Gets the definition data for the given joint.
The documentation for this class was generated from the following files:
FrictionJoint.hpp
FrictionJoint.cpp
FrictionJointDef.hpp