PlayRho: playrho::d2::Contact Class Reference
playrho::d2::Contact Class Reference
Physical Entity Classes
A potential contact between the children of two Fixture objects.
#include <Contact.hpp>
Classes
struct UpdateConf
Update configuration.
Public Types
using substep_type = TimestepIters
Substep type.
Public Member Functions
Contact (Fixture *fA, ChildCounter iA, Fixture *fB, ChildCounter iB)
Initializing constructor.
Contact ()=delete
Default construction not allowed.
Contact (const Contact &copy)=default
Copy constructor.
const Manifold & GetManifold () const noexcept
Gets the contact manifold.
bool IsTouching () const noexcept
Is this contact touching?
void SetEnabled (bool flag) noexcept
Enables or disables this contact.
void SetEnabled () noexcept
Enables this contact.
void UnsetEnabled () noexcept
Disables this contact.
bool IsEnabled () const noexcept
Has this contact been disabled?
Fixture * GetFixtureA () const noexcept
Gets fixture A in this contact.
ChildCounter GetChildIndexA () const noexcept
Get the child primitive index for fixture A.
Fixture * GetFixtureB () const noexcept
Gets fixture B in this contact.
ChildCounter GetChildIndexB () const noexcept
Get the child primitive index for fixture B.
void SetFriction (Real friction) noexcept
Sets the friction value for this contact.
Real GetFriction () const noexcept
Gets the coefficient of friction.
void SetRestitution (Real restitution) noexcept
Sets the restitution.
Real GetRestitution () const noexcept
Gets the restitution.
void SetTangentSpeed (LinearVelocity speed) noexcept
Sets the desired tangent speed for a conveyor belt behavior.
LinearVelocity GetTangentSpeed () const noexcept
Gets the desired tangent speed.
substep_type GetToiCount () const noexcept
Gets the time of impact count.
bool HasValidToi () const noexcept
Gets whether a TOI is set.
Real GetToi () const
Gets the time of impact (TOI) as a fraction.
void FlagForFiltering () noexcept
Flags the contact for filtering.
bool NeedsFiltering () const noexcept
Whether or not the contact needs filtering.
void FlagForUpdating () noexcept
Flags the contact for updating.
bool NeedsUpdating () const noexcept
Whether or not the contact needs updating.
Static Public Member Functions
static UpdateConf GetUpdateConf (const StepConf &conf) noexcept
Gets the update configuration from the given step configuration data.
Private Types
enum : FlagsType {
e_islandFlag = 0x01, e_touchingFlag = 0x02, e_enabledFlag = 0x04, e_filterFlag = 0x08,
e_toiFlag = 0x10, e_dirtyFlag = 0x20
}
Flags stored in m_flags.
using FlagsType = std::uint8_t
Flags type data type.
Private Member Functions
void UnflagForFiltering () noexcept
Flags this contact for filtering.
void UnflagForUpdating () noexcept
Unflags this contact for updating.
void Update (const UpdateConf &conf, ContactListener *listener=nullptr)
Updates the touching related state and notifies listener (if one given).
void SetToi (Real toi) noexcept
Sets the time of impact (TOI).
void UnsetToi () noexcept
Unsets the TOI.
void SetToiCount (substep_type value) noexcept
Sets the TOI count to the given value.
void SetTouching () noexcept
Sets the touching flag state.
void UnsetTouching () noexcept
Unsets the touching flag state.
Manifold & GetMutableManifold () noexcept
Gets the writable manifold.
bool IsIslanded () const noexcept
Whether this contact is in the is islanded state.
void SetIslanded () noexcept
Sets this contact to the is islanded state.
void UnsetIslanded () noexcept
Unsets the is islanded state.
Private Attributes
Manifold m_manifold
Manifold of the contact. 64-bytes.
Fixture *const m_fixtureA
Fixture A.
Fixture *const m_fixtureB
Fixture B.
ChildCounter const m_indexA
Index A.
ChildCounter const m_indexB
Index B.
Real m_friction
Mix of frictions of the associated fixtures.
Real m_restitution
Mix of restitutions of the associated fixtures.
LinearVelocity m_tangentSpeed = 0
Tangent speed.
Real m_toi
Time of impact.
substep_type m_toiCount = 0
Count of TOI calculations contact has gone through since last reset.
FlagsType m_flags = e_enabledFlag|e_dirtyFlag
Flags.
Friends
class ContactAtty
Related Functions
(Note that these are not member functions.)
WorldManifold GetWorldManifold (const Contact &contact)
Gets the world manifold for the given data.
Body * GetBodyA (const Contact &contact) noexcept
Gets the body A associated with the given contact.
Body * GetBodyB (const Contact &contact) noexcept
Gets the body B associated with the given contact.
Fixture * GetFixtureA (const Contact &contact) noexcept
Gets the fixture A associated with the given contact.
Fixture * GetFixtureB (const Contact &contact) noexcept
Gets the fixture B associated with the given contact.
bool HasSensor (const Contact &contact) noexcept
Whether the given contact has a sensor.
bool IsImpenetrable (const Contact &contact) noexcept
Whether the given contact is "impenetrable".
bool IsActive (const Contact &contact) noexcept
Determines whether the given contact is "active".
void SetAwake (const Contact &c) noexcept
Sets awake the fixtures of the given contact.
void ResetFriction (Contact &contact)
Resets the friction mixture to the default value.
void ResetRestitution (Contact &contact) noexcept
Reset the restitution to the default value.
TOIOutput CalcToi (const Contact &contact, ToiConf conf)
Calculates the Time Of Impact for the given contact with the given configuration.
Detailed Description
A potential contact between the children of two Fixture objects.
The class manages contact between two shapes. A contact exists for each overlapping AABB in the broad-phase (except if filtered). Therefore a contact object may exist that has no actual contact points.
Note
These are created by World instances. Users have no need to instantiate these themselves.
This data structure is 104-bytes large (on at least one 64-bit platform).
Constructor & Destructor Documentation
Contact()
playrho::d2::Contact::Contact (Fixture * fA, ChildCounter iA, Fixture * fB, ChildCounter iB)
Initializing constructor.
Parameters
fA Non-null pointer to fixture A that must have a shape and may not be the same or have the same body as the other fixture.
iA Child index A.
fB Non-null pointer to fixture B that must have a shape and may not be the same or have the same body as the other fixture.
iB Child index B.
Note
This need never be called directly by a user.
Warning
Behavior is undefined if fA is null.
Behavior is undefined if fB is null.
Behavior is undefined if fA == fB.
Behavior is undefined if fA has no associated shape.
Behavior is undefined if fB has no associated shape.
Behavior is undefined if both fixture's have the same body.
Member Function Documentation
GetFriction()
Real playrho::d2::Contact::GetFriction () const inline noexcept
Gets the coefficient of friction.
Gets the combined friction of the two fixtures associated with this contact.
Returns
Value of 0 or higher.
See also
MixFriction.
GetMutableManifold()
Manifold & playrho::d2::Contact::GetMutableManifold () inline private noexcept
Gets the writable manifold.
Note
This is intentionally not a public method.
Warning
Do not modify the manifold unless you understand the internals of the engine.
GetToi()
Real playrho::d2::Contact::GetToi () const inline
Gets the time of impact (TOI) as a fraction.
Note
This is only valid if a TOI has been set.
See also
void SetToi(Real toi).
Returns
Time of impact fraction in the range of 0 to 1 if set (where 1 means no actual impact in current time slot), otherwise undefined.
Referenced by playrho::d2::World::SolveToi().
HasValidToi()
bool playrho::d2::Contact::HasValidToi () const inline noexcept
Gets whether a TOI is set.
Returns
true if this object has a TOI set for it, false otherwise.
Referenced by GetToi().
IsTouching()
bool playrho::d2::Contact::IsTouching () const inline noexcept
Is this contact touching?
Touching is defined as either:
This contact's manifold has more than 0 contact points, or
This contact has sensors and the two shapes of this contact are found to be overlapping.
Returns
true if this contact is said to be touching, false otherwise.
Referenced by playrho::d2::World::InternalDestroy(), playrho::d2::World::ProcessContactsForTOI(), and playrho::d2::World::SolveToi().
SetEnabled()
void playrho::d2::Contact::SetEnabled (bool flag) inline noexcept
Enables or disables this contact.
Note
This can be used inside the pre-solve contact listener. The contact is only disabled for the current time step (or sub-step in continuous collisions).
Referenced by playrho::d2::World::ProcessContactsForTOI(), and playrho::d2::World::SolveToi().
SetFriction()
void playrho::d2::Contact::SetFriction (Real friction) inline noexcept
Sets the friction value for this contact.
Override the default friction mixture.
Note
You can call this in ContactListener::PreSolve.
This value persists until set or reset.
Warning
Behavior is undefined if given a negative friction value.
Parameters
friction Co-efficient of friction value of zero or greater.
Referenced by playrho::d2::ResetFriction().
SetRestitution()
void playrho::d2::Contact::SetRestitution (Real restitution) inline noexcept
Sets the restitution.
This override the default restitution mixture.
Note
You can call this in ContactListener::PreSolve.
The value persists until you set or reset.
SetToi()
void playrho::d2::Contact::SetToi (Real toi) inline private noexcept
Sets the time of impact (TOI).
After returning, this object will have a TOI that is set as indicated by HasValidToi().
Note
Behavior is undefined if the value assigned is less than 0 or greater than 1.
See also
Real GetToi() const.
HasValidToi.
Parameters
toi Time of impact as a fraction between 0 and 1 where 1 indicates no actual impact in the current time slot.
SetTouching()
void playrho::d2::Contact::SetTouching () inline private noexcept
Sets the touching flag state.
Note
This should only be called if either:
The contact's manifold has more than 0 contact points, or
The contact has sensors and the two shapes of this contact are found to be overlapping.
See also
IsTouching().
Referenced by Update().
UnflagForFiltering()
void playrho::d2::Contact::UnflagForFiltering () inline private noexcept
Flags this contact for filtering.
Note
Filtering will occur the next time step.
Update()
void playrho::d2::Contact::Update (const UpdateConf & conf, ContactListener * listener = nullptr) private
Updates the touching related state and notifies listener (if one given).
Note
Ideally this method is only called when a dependent change has occurred.
Touching related state depends on the following data:
The fixtures' sensor states.
The fixtures bodies' transformations.
The "maxCirclesRatio" per-step configuration state OR the "maxDistanceIters" per-step configuration state.
Parameters
conf Per-step configuration information.
listener Listener that if non-null is called with status information.
See also
GetManifold, IsTouching
Referenced by playrho::d2::ContactAtty::Update().
Friends And Related Function Documentation
CalcToi()
TOIOutput CalcToi (const Contact & contact, ToiConf conf) related
Calculates the Time Of Impact for the given contact with the given configuration.
GetBodyA()
Body * GetBodyA (const Contact & contact) related
Gets the body A associated with the given contact.
GetBodyB()
Body * GetBodyB (const Contact & contact) related
Gets the body B associated with the given contact.
GetFixtureA()
Fixture * GetFixtureA (const Contact & contact) related
Gets the fixture A associated with the given contact.
GetFixtureB()
Fixture * GetFixtureB (const Contact & contact) related
Gets the fixture B associated with the given contact.
GetWorldManifold()
WorldManifold GetWorldManifold (const Contact & contact) related
Gets the world manifold for the given data.
Note
This is a convenience function that in turn calls the GetWorldManifold(const Manifold&, const Transformation&, const Real, const Transformation& xfB, const Real) function.
Parameters
contact Contact to return a world manifold for.
Returns
World manifold value for the given inputs which will have the same number of points as the given manifold has. The returned world manifold points will be the mid-points of the contact's intersection.
HasSensor()
bool HasSensor (const Contact & contact) related
Whether the given contact has a sensor.
IsActive()
bool IsActive (const Contact & contact) related
Determines whether the given contact is "active".
IsImpenetrable()
bool IsImpenetrable (const Contact & contact) related
Whether the given contact is "impenetrable".
ResetFriction()
void ResetFriction (Contact & contact) related
Resets the friction mixture to the default value.
ResetRestitution()
void ResetRestitution (Contact & contact) related
Reset the restitution to the default value.
SetAwake()
void SetAwake (const Contact & c) related
Sets awake the fixtures of the given contact.
Member Data Documentation
m_fixtureA
Fixture* const playrho::d2::Contact::m_fixtureA private
Fixture A.
Non-null pointer to fixture A.
Referenced by GetFixtureA().
m_fixtureB
Fixture* const playrho::d2::Contact::m_fixtureB private
Fixture B.
Non-null pointer to fixture B.
Referenced by GetFixtureB().
m_friction
Real playrho::d2::Contact::m_friction private
Mix of frictions of the associated fixtures.
See also
MixFriction.
Referenced by GetFriction(), and SetFriction().
m_manifold
Manifold playrho::d2::Contact::m_manifold mutable private
Manifold of the contact. 64-bytes.
See also
Update.
Referenced by GetManifold(), GetMutableManifold(), and Update().
m_restitution
Real playrho::d2::Contact::m_restitution private
Mix of restitutions of the associated fixtures.
See also
MixRestitution.
Referenced by GetRestitution(), and SetRestitution().
m_toi
Real playrho::d2::Contact::m_toi private
Time of impact.
Note
This is a unit interval of time (a value between 0 and 1).
Only valid if m_flags & e_toiFlag
Referenced by GetToi(), and SetToi().
The documentation for this class was generated from the following files:
Contact.hpp
WorldManifold.hpp
Contact.cpp