PlayRho: playrho::Shape Class Reference
playrho::Shape Class Reference abstract
Shape Classes
A base abstract class for describing a type of shape.
#include <Shape.hpp>
Public Member Functions
virtual ChildCounter GetChildCount () const noexcept=0
Gets the number of child primitives of the shape.
virtual DistanceProxy GetChild (ChildCounter index) const =0
Gets the child for the given index.
virtual MassData GetMassData () const noexcept=0
Gets the mass properties of this shape using its dimensions and density.
virtual void Accept (ShapeVisitor &visitor) const =0
Accepts a visitor.
NonNegative< Length > GetVertexRadius () const noexcept
Gets the vertex radius.
void SetVertexRadius (NonNegative< Length > vertexRadius) noexcept
Sets the vertex radius.
NonNegative< AreaDensity > GetDensity () const noexcept
Gets the density of this fixture.
void SetDensity (NonNegative< AreaDensity > density) noexcept
Sets the density of this fixture.
Real GetFriction () const noexcept
Gets the coefficient of friction.
void SetFriction (NonNegative< Real > friction) noexcept
Sets the coefficient of friction.
Real GetRestitution () const noexcept
Gets the coefficient of restitution.
void SetRestitution (Finite< Real > restitution) noexcept
Sets the coefficient of restitution.
Protected Member Functions
Shape ()=default
Default constructor.
Shape (const ShapeDef &conf) noexcept
Initializing constructor.
Shape (const Shape &other)=default
Copy constructor.
Shape (Shape &&other)=default
Move constructor.
Shape & operator= (const Shape &other)=default
Copy assignment operator.
Shape & operator= (Shape &&other)=default
Move assignment operator.
Private Attributes
NonNegative< Length > m_vertexRadius = NonNegative<Length>{0_m}
Vertex radius.
NonNegative< AreaDensity > m_density = NonNegative<AreaDensity>{0_kgpm2}
AreaDensity.
NonNegative< Real > m_friction = NonNegative<Real>{Real{2} / Real{10}}
Friction as a coefficient.
Finite< Real > m_restitution = Finite<Real>{0}
Restitution as a coefficient.
Related Functions
(Note that these are not member functions.)
AABB2D ComputeAABB (const Shape &shape, const Transformation &xf) noexcept
Computes the AABB for the given shape with the given transformation.
RayCastOutput RayCast (const Shape &shape, ChildCounter childIndex, const RayCastInput &input, const Transformation &transform) noexcept
Cast a ray against the child of the given shape.
NonNegative< Length > GetVertexRadius (const Shape &shape) noexcept
Gets the vertex radius of the given shape.
bool TestPoint (const Shape &shape, Length2 point) noexcept
Test a point for containment in the given shape.
Detailed Description
A base abstract class for describing a type of shape.
This is a polymorphic abstract base class for shapes. A shape is used for collision detection. You can create a shape however you like. Shapes used for simulation in World are created automatically when a Fixture is created. Shapes may encapsulate zero or more child shapes.
Note
This data structure is 32-bytes large (on at least one 64-bit platform).
See also
Fixture
Constructor & Destructor Documentation
Shape()
playrho::Shape::Shape () protected default
Default constructor.
This is a base class that shouldn't ever be directly instantiated.
Member Function Documentation
Accept()
virtual void playrho::Shape::Accept (ShapeVisitor & visitor) const pure virtual
Accepts a visitor.
This is the Accept method definition of a "visitor design pattern" for for doing shape subclass specific types of processing for a constant shape.
See also
ShapeVisitor
https://en.wikipedia.org/wiki/Visitor_pattern
Implemented in playrho::EdgeShape, playrho::PolygonShape, playrho::DiskShape, playrho::ChainShape, and playrho::MultiShape.
GetChild()
virtual DistanceProxy playrho::Shape::GetChild (ChildCounter index) const pure virtual
Gets the child for the given index.
Parameters
index Index to a child element of the shape. Value must be less than the number of child primitives of the shape.
Note
The shape must remain in scope while the proxy is in use.
Exceptions
InvalidArgument if the given index is out of range.
See also
GetChildCount
Implemented in playrho::EdgeShape, playrho::PolygonShape, playrho::DiskShape, playrho::ChainShape, and playrho::MultiShape.
GetChildCount()
virtual ChildCounter playrho::Shape::GetChildCount () const pure virtual noexcept
Gets the number of child primitives of the shape.
Returns
Non-negative count.
Implemented in playrho::EdgeShape, playrho::PolygonShape, playrho::DiskShape, playrho::ChainShape, and playrho::MultiShape.
GetDensity()
NonNegative< AreaDensity > playrho::Shape::GetDensity () const inline noexcept
Gets the density of this fixture.
Returns
Non-negative density (in mass per area).
Referenced by playrho::MultiShape::GetMassData(), playrho::ChainShape::GetMassData(), playrho::DiskShape::GetMassData(), playrho::PolygonShape::GetMassData(), and playrho::EdgeShape::GetMassData().
GetFriction()
Real playrho::Shape::GetFriction () const inline noexcept
Gets the coefficient of friction.
Returns
Value of 0 or higher.
GetMassData()
virtual MassData playrho::Shape::GetMassData () const pure virtual noexcept
Gets the mass properties of this shape using its dimensions and density.
Returns
Mass data for this shape.
Implemented in playrho::EdgeShape, playrho::PolygonShape, playrho::DiskShape, playrho::ChainShape, and playrho::MultiShape.
GetVertexRadius()
NonNegative< Length > playrho::Shape::GetVertexRadius () const inline noexcept
Gets the vertex radius.
This gets the radius from the vertex that the shape's "skin" should extend outward by. While any edges - line segments between multiple vertices - are straight, corners between them (the vertices) are rounded and treated as rounded. Shapes with larger vertex radiuses compared to edge lengths therefore will be more prone to rolling or having other shapes more prone to roll off of them. Here's an image of a PolygonShape with it's skin drawn:
Note
This must be a non-negative value.
See also
SetVertexRadius
Referenced by playrho::MultiShape::GetChild(), playrho::ChainShape::GetChild(), playrho::DiskShape::GetChild(), playrho::PolygonShape::GetChild(), playrho::EdgeShape::GetChild(), playrho::MultiShape::GetMassData(), playrho::ChainShape::GetMassData(), playrho::DiskShape::GetMassData(), playrho::PolygonShape::GetMassData(), playrho::EdgeShape::GetMassData(), and playrho::DiskShape::GetRadius().
SetDensity()
void playrho::Shape::SetDensity (NonNegative< AreaDensity > density) inline noexcept
Sets the density of this fixture.
Note
This will not automatically adjust the mass of the body. You must call Body::ResetMassData to update the body's mass.
Parameters
density Non-negative density (in mass per area).
SetFriction()
void playrho::Shape::SetFriction (NonNegative< Real > friction) inline noexcept
Sets the coefficient of friction.
Note
This will not change the friction of existing contacts.
Parameters
friction Zero or higher (non-negative) co-efficient of friction.
SetRestitution()
void playrho::Shape::SetRestitution (Finite< Real > restitution) inline noexcept
Sets the coefficient of restitution.
Note
This will not change the restitution of existing contacts.
SetVertexRadius()
void playrho::Shape::SetVertexRadius (NonNegative< Length > vertexRadius) inline noexcept
Sets the vertex radius.
This sets the radius from the vertex that the shape's "skin" should extend outward by. While any edges - line segments between multiple vertices - are straight, corners between them (the vertices) are rounded and treated as rounded. Shapes with larger vertex radiuses compared to edge lengths therefore will be more prone to rolling or having other shapes more prone to roll off of them.
Note
This should be a non-negative value.
See also
GetVertexRadius
Referenced by playrho::DiskShape::SetRadius().
Friends And Related Function Documentation
ComputeAABB()
AABB2D ComputeAABB (const Shape & shape, const Transformation & xf) related
Computes the AABB for the given shape with the given transformation.
GetVertexRadius()
NonNegative< Length > GetVertexRadius (const Shape & shape) related
Gets the vertex radius of the given shape.
Gets the radius of every vertex of this shape. This is used for collision handling.
Note
This value should never be less than zero.
See also
Shape::GetVertexRadius
The documentation for this class was generated from the following files:
Shape.hpp
AABB.hpp
RayCastOutput.hpp
Shape.cpp