PlayRho: playrho::Shape2D Class Reference
playrho::Shape2D Class Reference
Shape2D Classes
Shape2D.
#include <Shape.hpp>
Classes
struct Concept
Internal shape configuration concept.
struct Model
Internal model configuration concept.
Public Types
using Visitor = std::function< void(const std::type_info &ti, const void *data)>
Visitor type alias for underlying shape configuration.
Public Member Functions
Shape2D ()=delete
Default constructor.
template<typename T >
Shape2D (T v)
Initializing constructor.
Shape2D (const Shape2D &other)=default
Copy constructor.
Shape2D (Shape2D &&other)=default
Move constructor.
Shape2D & operator= (const Shape2D &other)=default
Copy assignment operator.
Shape2D & operator= (Shape2D &&other)=default
Move assignment operator.
Private Attributes
std::shared_ptr< const Concept > m_self
Self shared pointer.
Friends
ChildCounter GetChildCount (const Shape2D &shape) noexcept
Gets the number of child primitives of the shape.
DistanceProxy2D GetChild (const Shape2D &shape, ChildCounter index)
Gets the "child" for the given index.
MassData2D GetMassData (const Shape2D &shape) noexcept
Gets the mass properties of this shape using its dimensions and density.
NonNegative< Length > GetVertexRadius (const Shape2D &shape) noexcept
Gets the vertex radius.
Real GetFriction (const Shape2D &shape) noexcept
Gets the coefficient of friction.
Real GetRestitution (const Shape2D &shape) noexcept
Gets the coefficient of restitution.
NonNegative< AreaDensity > GetDensity (const Shape2D &shape) noexcept
Gets the density of this fixture.
const void * GetData (const Shape2D &shape) noexcept
Gets a pointer to the underlying data.
void Accept (const Shape2D &shape, const Visitor &visitor)
Accepts a visitor.
bool operator== (const Shape2D &lhs, const Shape2D &rhs) noexcept
Equality operator for shape to shape comparisons.
bool operator!= (const Shape2D &lhs, const Shape2D &rhs) noexcept
Inequality operator for shape to shape comparisons.
Related Functions
(Note that these are not member functions.)
AABB2D ComputeAABB (const Shape2D &shape, const Transformation2D &xf) noexcept
Computes the AABB for the given shape with the given transformation.
RayCastOutput2D RayCast (const Shape2D &shape, ChildCounter childIndex, const RayCastInput2D &input, const Transformation2D &transform) noexcept
Cast a ray against the child of the given shape.
bool TestPoint (const Shape2D &shape, Length2 point) noexcept
Test a point for containment in the given shape.
Detailed Description
Shape2D.
A shape is used for collision detection. You can create a shape however you like. Shapes used for simulation in World2D are created automatically when a Fixture2D is created. Shapes may encapsulate zero or more child shapes.
Note
This data structure is 32-bytes large (on at least one 64-bit platform).
See also
Fixture2D
Constructor & Destructor Documentation
Shape2D()
playrho::Shape2D::Shape2D () delete
Default constructor.
This is a base class that shouldn't ever be directly instantiated.
Friends And Related Function Documentation
Accept
void Accept (const Shape2D & shape, const Visitor & visitor) friend
Accepts a visitor.
This is the "accept" method definition of a "visitor design pattern" for doing shape configuration specific types of processing for a constant shape.
See also
https://en.wikipedia.org/wiki/Visitor_pattern
ComputeAABB()
AABB2D ComputeAABB (const Shape2D & shape, const Transformation2D & xf) related
Computes the AABB for the given shape with the given transformation.
GetChild
DistanceProxy2D GetChild (const Shape2D & shape, ChildCounter index) friend
Gets the "child" for the given index.
Parameters
shape Shape to get "child" shape of.
index Index to a child element of the shape. Value must be less than the number of child primitives of the shape.
Note
The shape must remain in scope while the proxy is in use.
Exceptions
InvalidArgument if the given index is out of range.
See also
GetChildCount
Referenced by playrho::Shape2D::Model< T >::GetChild_().
GetChildCount
ChildCounter GetChildCount (const Shape2D & shape) friend
Gets the number of child primitives of the shape.
Returns
Non-negative count.
Referenced by playrho::Shape2D::Model< T >::GetChildCount_().
GetData
const void* GetData (const Shape2D & shape) friend
Gets a pointer to the underlying data.
Note
Provided for introspective purposes like visitation.
Generally speaking, try to avoid using this method unless there's no other way to access the underlying data.
GetDensity
NonNegative<AreaDensity> GetDensity (const Shape2D & shape) friend
Gets the density of this fixture.
Returns
Non-negative density (in mass per area).
Referenced by playrho::Shape2D::Model< T >::GetDensity_().
GetFriction
Real GetFriction (const Shape2D & shape) friend
Gets the coefficient of friction.
Returns
Value of 0 or higher.
Referenced by playrho::Shape2D::Model< T >::GetFriction_().
GetMassData
MassData2D GetMassData (const Shape2D & shape) friend
Gets the mass properties of this shape using its dimensions and density.
Returns
Mass data for this shape.
Referenced by playrho::Shape2D::Model< T >::GetMassData_().
GetVertexRadius
NonNegative<Length> GetVertexRadius (const Shape2D & shape) friend
Gets the vertex radius.
This gets the radius from the vertex that the shape's "skin" should extend outward by. While any edges - line segments between multiple vertices - are straight, corners between them (the vertices) are rounded and treated as rounded. Shapes with larger vertex radiuses compared to edge lengths therefore will be more prone to rolling or having other shapes more prone to roll off of them. Here's an image of a shape configured via a PolygonShapeConf with it's skin drawn:
Note
This must be a non-negative value.
See also
UseVertexRadius
Referenced by playrho::Shape2D::Model< T >::GetVertexRadius_().
The documentation for this class was generated from the following files:
Shape.hpp
AABB.hpp
RayCastOutput.hpp