PlayRho: playrho::d2::PolygonShapeConf Class Reference
playrho::d2::PolygonShapeConf Class Reference
Shape Classes
Polygon shape configuration.
#include <PolygonShapeConf.hpp>
Public Member Functions
PolygonShapeConf (Length hx, Length hy, const PolygonShapeConf &conf=GetDefaultConf()) noexcept
Initializing constructor for a 4-sided box polygon.
PolygonShapeConf (Span< const Length2 > points, const PolygonShapeConf &conf=GetDefaultConf()) noexcept
Creates a convex hull from the given array of local points.
PolygonShapeConf & UseVertexRadius (NonNegative< Length > value) noexcept
Uses the given vertex radius.
PolygonShapeConf & UseVertices (const std::vector< Length2 > &verts) noexcept
Uses the given vertices.
PolygonShapeConf & SetAsBox (Length hx, Length hy) noexcept
Sets the vertices to represent an axis-aligned box centered on the local origin.
PolygonShapeConf & SetAsBox (Length hx, Length hy, Length2 center, Angle angle) noexcept
Sets the vertices for the described box.
PolygonShapeConf & Set (Span< const Length2 > verts) noexcept
Sets the vertices to a convex hull of the given ones.
PolygonShapeConf & Set (const VertexSet &points) noexcept
Sets the vertices to a convex hull of the given ones.
PolygonShapeConf & Transform (Transformation xfm) noexcept
Transforms the vertices by the given transformation.
PolygonShapeConf & Transform (const Mat22 &m) noexcept
Transforms the vertices by the given transformation matrix.
VertexCounter GetVertexCount () const noexcept
Gets the vertex count.
Length2 GetVertex (VertexCounter index) const
Gets a vertex by index.
UnitVec GetNormal (VertexCounter index) const
Gets a normal by index.
Span< const Length2 > GetVertices () const noexcept
Gets the span of vertices.
Span< const UnitVec > GetNormals () const noexcept
Gets the span of normals.
Length2 GetCentroid () const noexcept
Gets the centroid.
Public Member Functions inherited from playrho::d2::ShapeBuilder< PolygonShapeConf >
constexpr ShapeBuilder ()=default
Default constructor.
constexpr ShapeBuilder (const BaseShapeConf &value) noexcept
Initializing constructor.
constexpr PolygonShapeConf & UseFriction (NonNegative< Real > value) noexcept
Uses the given friction.
constexpr PolygonShapeConf & UseRestitution (Finite< Real > value) noexcept
Uses the given restitution.
constexpr PolygonShapeConf & UseDensity (NonNegative< AreaDensity > value) noexcept
Uses the given density.
Static Public Member Functions
static constexpr NonNegative< Length > GetDefaultVertexRadius () noexcept
Gets the default vertex radius for the PolygonShapeConf.
static PolygonShapeConf GetDefaultConf () noexcept
Gets the default configuration for a PolygonShapeConf.
Public Attributes
NonNegative< Length > vertexRadius = GetDefaultVertexRadius()
Vertex radius.
Public Attributes inherited from playrho::d2::BaseShapeConf
NonNegative< Real > friction = NonNegative<Real>{Real{2} / Real{10}}
Friction coefficient.
Finite< Real > restitution = Finite<Real>{0}
Restitution (elasticity) of the associated shape.
NonNegative< AreaDensity > density = NonNegative<AreaDensity>{0_kgpm2}
Area density of the associated shape.
Private Attributes
std::vector< Length2 > m_vertices
Array of vertices.
std::vector< UnitVec > m_normals
Normals of edges.
Length2 m_centroid = GetInvalid<Length2>()
Centroid of this shape.
Friends
bool operator== (const PolygonShapeConf &lhs, const PolygonShapeConf &rhs) noexcept
Equality operator.
bool operator!= (const PolygonShapeConf &lhs, const PolygonShapeConf &rhs) noexcept
Inequality operator.
Related Functions
(Note that these are not member functions.)
Length2 GetEdge (const PolygonShapeConf &shape, VertexCounter index)
Gets the identified edge of the given polygon shape.
Detailed Description
Polygon shape configuration.
A convex polygon. The interior of the polygon is to the left of each edge. Polygons maximum number of vertices is defined by MaxShapeVertices. In most cases you should not need many vertices for a convex polygon.
Note
This data structure is 64-bytes large (with 4-byte Real).
Examples
HelloWorld.cpp, World.cpp, and WorldBody.cpp.
Constructor & Destructor Documentation
PolygonShapeConf() [1/2]
playrho::d2::PolygonShapeConf::PolygonShapeConf (Length hx, Length hy, const PolygonShapeConf & conf = GetDefaultConf()) noexcept
Initializing constructor for a 4-sided box polygon.
Parameters
hx Half of the width.
hy Half of the height.
conf Additional configuration information.
See also
SetAsBox.
PolygonShapeConf() [2/2]
playrho::d2::PolygonShapeConf::PolygonShapeConf (Span< const Length2 > points, const PolygonShapeConf & conf = GetDefaultConf()) explicit noexcept
Creates a convex hull from the given array of local points.
Note
The size of the span must be in the range [1, MaxShapeVertices].
Warning
the points may be re-ordered, even if they form a convex polygon
collinear points are handled but not removed. Collinear points may lead to poor stacking behavior.
Member Function Documentation
GetNormal()
UnitVec playrho::d2::PolygonShapeConf::GetNormal (VertexCounter index) const inline
Gets a normal by index.
These are 90-degree clockwise-rotated (outward-facing) unit-vectors of the edges defined by consecutive pairs of vertices starting with vertex 0.
Parameters
index Index of the normal to get.
Returns
Normal for the given index.
GetVertex()
Length2 playrho::d2::PolygonShapeConf::GetVertex (VertexCounter index) const inline
Gets a vertex by index.
Vertices go counter-clockwise.
Referenced by playrho::d2::GetEdge().
GetVertexCount()
VertexCounter playrho::d2::PolygonShapeConf::GetVertexCount () const inline noexcept
Gets the vertex count.
Returns
value between 0 and MaxShapeVertices inclusive.
See also
MaxShapeVertices
Referenced by playrho::d2::GetChild(), playrho::d2::GetEdge(), GetNormal(), and GetVertex().
GetVertices()
Span<const Length2> playrho::d2::PolygonShapeConf::GetVertices () const inline noexcept
Gets the span of vertices.
Vertices go counter-clockwise.
Referenced by playrho::d2::GetChild().
Set() [1/2]
PolygonShapeConf & playrho::d2::PolygonShapeConf::Set (const VertexSet & points) noexcept
Sets the vertices to a convex hull of the given ones.
Note
The size of the span must be in the range [1, MaxShapeVertices].
Warning
Points may be re-ordered, even if they form a convex polygon
Collinear points are handled but not removed. Collinear points may lead to poor stacking behavior.
Set() [2/2]
PolygonShapeConf & playrho::d2::PolygonShapeConf::Set (Span< const Length2 > verts) noexcept
Sets the vertices to a convex hull of the given ones.
Note
The size of the span must be in the range [1, MaxShapeVertices].
Warning
Points may be re-ordered, even if they form a convex polygon
Collinear points are handled but not removed. Collinear points may lead to poor stacking behavior.
SetAsBox()
PolygonShapeConf & playrho::d2::PolygonShapeConf::SetAsBox (Length hx, Length hy) noexcept
Sets the vertices to represent an axis-aligned box centered on the local origin.
Parameters
hx the half-width.
hy the half-height.
Examples
HelloWorld.cpp, and World.cpp.
Transform()
PolygonShapeConf & playrho::d2::PolygonShapeConf::Transform (const Mat22 & m) noexcept
Transforms the vertices by the given transformation matrix.
See also
https://en.wikipedia.org/wiki/Transformation_matrix
Friends And Related Function Documentation
GetEdge()
Length2 GetEdge (const PolygonShapeConf & shape, VertexCounter index) related
Gets the identified edge of the given polygon shape.
Note
This must not be called for shapes with less than 2 vertices.
Warning
Behavior is undefined if called for a shape with less than 2 vertices.
Member Data Documentation
m_normals
std::vector<UnitVec> playrho::d2::PolygonShapeConf::m_normals private
Normals of edges.
These are 90-degree clockwise-rotated unit-vectors of the vectors defined by consecutive pairs of elements of vertices.
Referenced by GetNormal(), and GetNormals().
m_vertices
std::vector<Length2> playrho::d2::PolygonShapeConf::m_vertices private
Array of vertices.
Consecutive vertices constitute "edges" of the polygon.
Referenced by GetNormals(), GetVertex(), GetVertexCount(), and GetVertices().
vertexRadius
NonNegative<Length> playrho::d2::PolygonShapeConf::vertexRadius = GetDefaultVertexRadius()
Vertex radius.
This is the radius from the vertex that the shape's "skin" should extend outward by. While any edges — line segments between multiple vertices — are straight, corners between them (the vertices) are rounded and treated as rounded. Shapes with larger vertex radiuses compared to edge lengths therefore will be more prone to rolling or having other shapes more prone to roll off of them.
Note
This should be a non-negative value.
Referenced by playrho::d2::GetChild().
The documentation for this class was generated from the following files:
PolygonShapeConf.hpp
PolygonShapeConf.cpp