PlayRho: playrho::d2::UnitVec2 Class Reference
playrho::d2::UnitVec2 Class Reference
2-D unit vector.
#include <UnitVec2.hpp>
Public Types
using value_type = Real
Value type used for the coordinate values of this vector.
using size_type = std::size_t
Size type.
using const_reference = const value_type &
Constant reference type.
using const_pointer = const value_type *
Constant pointer type.
using const_iterator = const value_type *
Constant iterator type.
using const_reverse_iterator = std::reverse_iterator< const_iterator >
Constant reverse iterator type.
using PolarCoord = std::pair< UnitVec2, Real >
Polar coordinate.
Public Member Functions
PLAYRHO_CONSTEXPR size_type max_size () const noexcept
Gets the max size.
PLAYRHO_CONSTEXPR size_type size () const noexcept
Gets the size.
PLAYRHO_CONSTEXPR bool empty () const noexcept
Whether empty.
const_iterator begin () const noexcept
Gets a "begin" iterator.
const_iterator end () const noexcept
Gets an "end" iterator.
const_iterator cbegin () const noexcept
Gets a "begin" iterator.
const_iterator cend () const noexcept
Gets an "end" iterator.
const_reverse_iterator crbegin () const noexcept
Gets a reverse "begin" iterator.
const_reverse_iterator crend () const noexcept
Gets a reverse "end" iterator.
const_reverse_iterator rbegin () const noexcept
Gets a reverse "begin" iterator.
const_reverse_iterator rend () const noexcept
Gets a reverse "end" iterator.
PLAYRHO_CONSTEXPR const_reference operator[] (size_type pos) const noexcept
Gets a constant reference to the requested element.
PLAYRHO_CONSTEXPR const_reference at (size_type pos) const
Gets a constant reference to the requested element.
PLAYRHO_CONSTEXPR const_pointer data () const noexcept
Direct access to data.
PLAYRHO_CONSTEXPR auto GetX () const noexcept
Gets the "X" value.
PLAYRHO_CONSTEXPR auto GetY () const noexcept
Gets the "Y" value.
PLAYRHO_CONSTEXPR UnitVec2 FlipXY () const noexcept
Flips the X and Y values.
PLAYRHO_CONSTEXPR UnitVec2 FlipX () const noexcept
Flips the X value.
PLAYRHO_CONSTEXPR UnitVec2 FlipY () const noexcept
Flips the Y value.
PLAYRHO_CONSTEXPR UnitVec2 Rotate (UnitVec2 amount) const noexcept
Rotates the unit vector by the given amount.
PLAYRHO_CONSTEXPR UnitVec2 GetRevPerpendicular () const noexcept
Gets a vector counter-clockwise (reverse-clockwise) perpendicular to this vector.
PLAYRHO_CONSTEXPR UnitVec2 GetFwdPerpendicular () const noexcept
Gets a vector clockwise (forward-clockwise) perpendicular to this vector.
PLAYRHO_CONSTEXPR UnitVec2 operator- () const noexcept
Negation operator.
PLAYRHO_CONSTEXPR UnitVec2 operator+ () const noexcept
Positive operator.
PLAYRHO_CONSTEXPR UnitVec2 Absolute () const noexcept
Gets the absolute value.
Static Public Member Functions
static PLAYRHO_CONSTEXPR UnitVec2 GetRight () noexcept
Gets the right-ward oriented unit vector.
static PLAYRHO_CONSTEXPR UnitVec2 GetTop () noexcept
Gets the top-ward oriented unit vector.
static PLAYRHO_CONSTEXPR UnitVec2 GetLeft () noexcept
Gets the left-ward oriented unit vector.
static PLAYRHO_CONSTEXPR UnitVec2 GetBottom () noexcept
Gets the bottom-ward oriented unit vector.
static PLAYRHO_CONSTEXPR UnitVec2 GetZero () noexcept
Gets the non-oriented unit vector.
static PLAYRHO_CONSTEXPR UnitVec2 GetTopRight () noexcept
Gets the 45 degree unit vector.
static PLAYRHO_CONSTEXPR UnitVec2 GetBottomRight () noexcept
Gets the -45 degree unit vector.
static PLAYRHO_CONSTEXPR UnitVec2 GetDefaultFallback () noexcept
Gets the default fallback.
static PolarCoord Get (const Real x, const Real y, const UnitVec2 fallback=GetDefaultFallback()) noexcept
Gets the unit vector & magnitude from the given parameters.
static UnitVec2 Get (const Angle angle) noexcept
Gets the given angled unit vector.
Private Member Functions
PLAYRHO_CONSTEXPR UnitVec2 (value_type x, value_type y) noexcept
Initializing constructor.
Private Attributes
value_type m_elems [2] = { value_type{0}, value_type{0} }
Element values.
Detailed Description
2-D unit vector.
This is a 2-dimensional directional vector.
Member Typedef Documentation
PolarCoord
using playrho::d2::UnitVec2::PolarCoord = std::pair<UnitVec2, Real>
Polar coordinate.
This is a direction and magnitude pair defined by the unit vector class.
Note
A magnitude of 0 indicates that no conclusive direction could be determined. The magnitude will otherwise be a normal value.
Member Function Documentation
at()
PLAYRHO_CONSTEXPR const_reference playrho::d2::UnitVec2::at (size_type pos) const inline
Gets a constant reference to the requested element.
Exceptions
InvalidArgument if given a position that's >= size().
empty()
PLAYRHO_CONSTEXPR bool playrho::d2::UnitVec2::empty () const inline noexcept
Whether empty.
Note
Always false for N > 0.
Get()
UnitVec2 playrho::d2::UnitVec2::Get (const Angle angle) static noexcept
Gets the given angled unit vector.
Note
For angles that are meant to be at exact multiples of the quarter turn, better accuracy will be had by using one of the four oriented unit vector returning methods - for the right, top, left, bottom orientations.
GetBottom()
static PLAYRHO_CONSTEXPR UnitVec2 playrho::d2::UnitVec2::GetBottom () inline static noexcept
Gets the bottom-ward oriented unit vector.
Note
This is the actual value for the 3/4 turned (270 degree angled) unit vector.
This is the reverse perpendicular unit vector of the left oriented vector.
This is the forward perpendicular unit vector of the right oriented vector.
Referenced by playrho::d2::RayCast().
GetBottomRight()
static PLAYRHO_CONSTEXPR UnitVec2 playrho::d2::UnitVec2::GetBottomRight () inline static noexcept
Gets the -45 degree unit vector.
This is the unit vector in the positive X and negative Y quadrant where |X| == |Y|.
GetFwdPerpendicular()
PLAYRHO_CONSTEXPR UnitVec2 playrho::d2::UnitVec2::GetFwdPerpendicular () const inline noexcept
Gets a vector clockwise (forward-clockwise) perpendicular to this vector.
This returns the unit vector (y, -x).
Returns
A clockwise 90-degree rotation of this vector.
See also
GetRevPerpendicular.
GetLeft()
static PLAYRHO_CONSTEXPR UnitVec2 playrho::d2::UnitVec2::GetLeft () inline static noexcept
Gets the left-ward oriented unit vector.
Note
This is the actual value for the 2/4 turned (180 degree angled) unit vector.
This is the reverse perpendicular unit vector of the top oriented vector.
This is the forward perpendicular unit vector of the bottom oriented vector.
Referenced by playrho::d2::RayCast().
GetRevPerpendicular()
PLAYRHO_CONSTEXPR UnitVec2 playrho::d2::UnitVec2::GetRevPerpendicular () const inline noexcept
Gets a vector counter-clockwise (reverse-clockwise) perpendicular to this vector.
This returns the unit vector (-y, x).
Returns
A counter-clockwise 90-degree rotation of this vector.
See also
GetFwdPerpendicular.
GetRight()
static PLAYRHO_CONSTEXPR UnitVec2 playrho::d2::UnitVec2::GetRight () inline static noexcept
Gets the right-ward oriented unit vector.
Note
This is the value for the 0/4 turned (0 angled) unit vector.
This is the reverse perpendicular unit vector of the bottom oriented vector.
This is the forward perpendicular unit vector of the top oriented vector.
Referenced by playrho::d2::RayCast().
GetTop()
static PLAYRHO_CONSTEXPR UnitVec2 playrho::d2::UnitVec2::GetTop () inline static noexcept
Gets the top-ward oriented unit vector.
Note
This is the actual value for the 1/4 turned (90 degree angled) unit vector.
This is the reverse perpendicular unit vector of the right oriented vector.
This is the forward perpendicular unit vector of the left oriented vector.
Referenced by playrho::d2::RayCast().
GetTopRight()
static PLAYRHO_CONSTEXPR UnitVec2 playrho::d2::UnitVec2::GetTopRight () inline static noexcept
Gets the 45 degree unit vector.
This is the unit vector in the positive X and Y quadrant where X == Y.
operator[]()
PLAYRHO_CONSTEXPR const_reference playrho::d2::UnitVec2::operator[] (size_type pos) const inline noexcept
Gets a constant reference to the requested element.
Note
No bounds checking is performed.
Warning
Behavior is undefined if given a position equal to or greater than size().
Rotate()
PLAYRHO_CONSTEXPR UnitVec2 playrho::d2::UnitVec2::Rotate (UnitVec2 amount) const inline noexcept
Rotates the unit vector by the given amount.
Parameters
amount Expresses the angular difference from the right-ward oriented unit vector to rotate this unit vector by.
Returns
Result of rotating this unit vector by the given amount.
The documentation for this class was generated from the following files:
UnitVec2.hpp
UnitVec2.cpp