PlayRho: playrho::RopeJoint Class Reference
playrho::RopeJoint Class Reference
Joint Classes
Rope joint.
#include <RopeJoint.hpp>
Public Member Functions
RopeJoint (const RopeJointDef &data)
Initializing constructor.
void Accept (JointVisitor &visitor) const override
Accepts a visitor.
Length2D GetAnchorA () const override
Get the anchor point on bodyA in world coordinates.
Length2D GetAnchorB () const override
Get the anchor point on bodyB in world coordinates.
Momentum2D GetLinearReaction () const override
Get the linear reaction on bodyB at the joint anchor.
AngularMomentum GetAngularReaction () const override
Get the angular reaction on bodyB.
Length2D GetLocalAnchorA () const
The local anchor point relative to bodyA's origin.
Length2D GetLocalAnchorB () const
The local anchor point relative to bodyB's origin.
void SetMaxLength (Length length)
Sets the maximum length of the rope.
Length GetMaxLength () const
Gets the maximum length of the rope.
LimitState GetLimitState () const
Gets the limit state.
Public Member Functions inherited from playrho::Joint
Body * GetBodyA () const noexcept
Gets the first body attached to this joint.
Body * GetBodyB () const noexcept
Gets the second body attached to this joint.
void * GetUserData () const noexcept
Get the user data pointer.
void SetUserData (void *data) noexcept
Set the user data pointer.
bool GetCollideConnected () const noexcept
Gets collide connected.
virtual void ShiftOrigin (const Length2D newOrigin)
Shifts the origin for any points stored in world coordinates.
Private Member Functions
void InitVelocityConstraints (BodyConstraintsMap &bodies, const StepConf &step, const ConstraintSolverConf &conf) override
Initializes velocity constraint data based on the given solver data.
bool SolveVelocityConstraints (BodyConstraintsMap &bodies, const StepConf &step) override
Solves velocity constraint.
bool SolvePositionConstraints (BodyConstraintsMap &bodies, const ConstraintSolverConf &conf) const override
Solves the position constraint.
Private Attributes
Length2D m_localAnchorA
Local anchor A.
Length2D m_localAnchorB
Local anchor B.
Length m_maxLength
Max length.
Length m_length = 0
Length.
Momentum m_impulse = Momentum{0}
Impulse.
UnitVec2 m_u
U direction.
Length2D m_rA
Relative A.
Length2D m_rB
Relative B.
Mass m_mass = Mass{0}
Mass.
LimitState m_state = e_inactiveLimit
Limit state.
Related Functions
(Note that these are not member functions.)
RopeJointDef GetRopeJointDef (const RopeJoint &joint) noexcept
Gets the definition data for the given joint.
Related Functions inherited from playrho::Joint
bool IsEnabled (const Joint &j) noexcept
Short-cut function to determine if both bodies are enabled.
void SetAwake (Joint &j) noexcept
Wakes up the joined bodies.
JointCounter GetWorldIndex (const Joint *joint)
Gets the world index of the given joint.
JointType GetType (const Joint &joint) noexcept
Gets the type of the given joint.
Additional Inherited Members
Public Types inherited from playrho::Joint
enum LimitState { e_inactiveLimit, e_atLowerLimit, e_atUpperLimit, e_equalLimits }
Limit state.
Static Public Member Functions inherited from playrho::Joint
static bool IsOkay (const JointDef &def) noexcept
Is the given definition okay.
Protected Member Functions inherited from playrho::Joint
Joint (const JointDef &def)
Initializing constructor.
Detailed Description
Rope joint.
A rope joint enforces a maximum distance between two points on two bodies. It has no other effect.
Warning
If you attempt to change the maximum length during the simulation you will get some non-physical behavior. A model that would allow you to dynamically modify the length would have some sponginess, so it was decided not to implement it that way. See DistanceJoint if you want to dynamically control length.
Member Function Documentation
void playrho::RopeJoint::InitVelocityConstraints (BodyConstraintsMap & bodies, const StepConf & step, const ConstraintSolverConf & conf) override private virtual
Initializes velocity constraint data based on the given solver data.
Note
This MUST be called prior to calling SolveVelocityConstraints.
See also
SolveVelocityConstraints.
Implements playrho::Joint.
Referenced by SetMaxLength().
bool playrho::RopeJoint::SolvePositionConstraints (BodyConstraintsMap & bodies, const ConstraintSolverConf & conf) const override private virtual
Solves the position constraint.
Returns
true if the position errors are within tolerance.
Implements playrho::Joint.
Referenced by SetMaxLength().
bool playrho::RopeJoint::SolveVelocityConstraints (BodyConstraintsMap & bodies, const StepConf & step) override private virtual
Solves velocity constraint.
Precondition
InitVelocityConstraints has been called.
See also
InitVelocityConstraints.
Returns
true if velocity is "solved", false otherwise.
Implements playrho::Joint.
Referenced by SetMaxLength().
Friends And Related Function Documentation
RopeJointDef GetRopeJointDef (const RopeJoint & joint) related
Gets the definition data for the given joint.
The documentation for this class was generated from the following files:
RopeJoint.hpp
RopeJoint.cpp
RopeJointDef.hpp