PlayRho: playrho::d2::DynamicTree Class Reference
playrho::d2::DynamicTree Class Reference
A dynamic AABB tree broad-phase.
#include <DynamicTree.hpp>
Classes
struct BranchData
Branch data of a tree node.
struct LeafData
Leaf data of a tree node.
class TreeNode
A node in the dynamic tree.
struct UnusedData
Unused data of a tree node.
union VariantData
Variant data.
Public Types
using Size = ContactCounter
Size type.
using Height = ContactCounter
Strong type for heights.
Public Member Functions
DynamicTree (Size nodeCapacity=GetDefaultInitialNodeCapacity())
Constructing the tree initializes the node pool.
~DynamicTree () noexcept
Destroys the tree, freeing the node pool.
DynamicTree (const DynamicTree &other)
Copy constructor.
DynamicTree (DynamicTree &&other) noexcept
Move constructor.
DynamicTree & operator= (const DynamicTree &other)
Copy assignment operator.
DynamicTree & operator= (DynamicTree &&other) noexcept
Move assignment operator.
Size CreateLeaf (const AABB &aabb, const LeafData &leafData)
Creates a new leaf node.
void DestroyLeaf (Size index)
Destroys a leaf node.
void UpdateLeaf (Size index, const AABB &aabb)
Updates a leaf node with a new AABB value.
LeafData GetLeafData (Size index) const noexcept
Gets the user data for the node identified by the given identifier.
void SetLeafData (Size index, LeafData value) noexcept
Sets the leaf data for the element at the given index to the given value.
AABB GetAABB (Size index) const noexcept
Gets the AABB for a leaf or branch (a non-unused node).
Height GetHeight (Size index) const noexcept
Gets the height value for the identified node.
BranchData GetBranchData (Size index) const noexcept
Gets the branch data for the identified node.
bool Validate () const
Validates this tree.
bool ValidateStructure (Size index) const noexcept
Validates the structure of this tree from the given index.
bool ValidateMetrics (Size index) const noexcept
Validates the metrics of this tree from the given index.
Size GetRootIndex () const noexcept
Gets the root index.
Height GetMaxBalance () const noexcept
Gets the maximum balance.
Length ComputeTotalPerimeter () const noexcept
Gets the ratio of the sum of the perimeters of nodes to the root perimeter.
void RebuildBottomUp ()
Builds an optimal tree.
void ShiftOrigin (Length2 newOrigin)
Shifts the world origin.
Height ComputeHeight (Size index) const noexcept
Computes the height of the tree from a given node.
Size GetNodeCapacity () const noexcept
Gets the current node capacity of this tree.
Size GetNodeCount () const noexcept
Gets the current node count.
Size GetLeafCount () const noexcept
Gets the current leaf node count.
Size FindLowestCostNode (AABB leafAABB) const noexcept
Finds the lowest cost node.
Size FindReference (Size index) const noexcept
Finds first node which references the given index.
Static Public Member Functions
static PLAYRHO_CONSTEXPR Size GetInvalidSize () noexcept
Gets the invalid size value.
static PLAYRHO_CONSTEXPR Height GetInvalidHeight () noexcept
Gets the invalid height value.
static PLAYRHO_CONSTEXPR bool IsUnused (Height value) noexcept
Gets whether the given height is the height for an "unused" node.
static PLAYRHO_CONSTEXPR bool IsLeaf (Height value) noexcept
Gets whether the given height is the height for a "leaf" node.
static PLAYRHO_CONSTEXPR bool IsBranch (Height value) noexcept
Gets whether the given height is a height for a "branch" node.
static PLAYRHO_CONSTEXPR Size GetDefaultInitialNodeCapacity () noexcept
Gets the default initial node capacity.
Static Public Attributes
static PLAYRHO_CONSTEXPR const auto InvalidHeight = static_cast<Height>(-1)
Invalid height constant value.
Private Member Functions
void SetNodeCapacity (Size value) noexcept
Sets the node capacity to the given value.
Size AllocateNode () noexcept
Allocates a node.
Size AllocateNode (const LeafData &node, AABB aabb) noexcept
Allocates a leaf node.
Size AllocateNode (const BranchData &node, AABB aabb, Height height, Size parent=GetInvalidSize()) noexcept
Allocates a branch node.
void FreeNode (Size index) noexcept
Frees the specified node.
void InsertLeaf (Size index)
Inserts the specified node.
void RemoveLeaf (Size leaf)
Removes the specified node.
void Rebalance (Size index)
Rebalances the tree from the given index.
Size GetParent (Size index) const noexcept
Gets the parent node index of the node identified by the given index.
void SetParent (Size index, Size newParent) noexcept
Sets the parent node index of the node identified by the given index.
void SetHeight (Size index, Height value) noexcept
Sets the height of the node identified by the given index to the given value.
Size GetChild1 (Size index) const noexcept
Gets the child-1 index value of the node identified by the given index.
void SetChild1 (Size index, Size value) noexcept
Sets the child-1 index value of the node identified by the given index.
Size GetChild2 (Size index) const noexcept
Gets the child-2 index value of the node identified by the given index.
void SetChild2 (Size index, Size value) noexcept
Sets the child-2 index value of the node identified by the given index.
void SetAABB (Size index, AABB value) noexcept
Sets the AABB of the node identified by the given index to the given value.
void SwapChild (Size index, Size oldChild, Size newChild) noexcept
Swaps the child index of the node identified by the given index.
void SetChildren (Size index, Size child1, Size child2) noexcept
Sets the child indexes for the node identified by the given index.
Private Attributes
TreeNode * m_nodes
Nodes.
Size m_root = GetInvalidSize()
Index of root element in m_nodes or GetInvalidSize().
Size m_nodeCount = Size{0}
Node count.
Size m_nodeCapacity
Node capacity.
Size m_leafCount = 0
Leaf count.
Size m_freeListIndex = Size{0}
Free list.
Related Functions
(Note that these are not member functions.)
DynamicTree::Height GetHeight (const DynamicTree &tree) noexcept
Gets the height of the binary tree.
AABB GetAABB (const DynamicTree &tree) noexcept
Gets the AABB for the given dynamic tree.
bool TestOverlap (const DynamicTree &tree, DynamicTree::Size leafIdA, DynamicTree::Size leafIdB) noexcept
Tests for overlap of the elements identified in the given dynamic tree.
Detailed Description
A dynamic AABB tree broad-phase.
A dynamic tree arranges data in a binary tree to accelerate queries such as volume queries and ray casts. Leafs are proxies with an AABB.
Note
This code was inspired by Nathanael Presson's btDbvt.
Nodes are pooled and relocatable, so we use node indices rather than pointers.
This data structure is 32-bytes large (on at least one 64-bit platform).
See also
http://www.randygaul.net/2013/08/06/dynamic-aabb-tree/
http://www.cs.utah.edu/~thiago/papers/rotations.pdf ("Fast, Effective BVH Updates for Animated Scenes")
Member Function Documentation
AllocateNode() [1/3]
DynamicTree::Size playrho::d2::DynamicTree::AllocateNode () private noexcept
Allocates a node.
This allocates a node from the free list that can be used as either a leaf node or a branch node.
Referenced by CreateLeaf(), InsertLeaf(), and RebuildBottomUp().
AllocateNode() [2/3]
DynamicTree::Size playrho::d2::DynamicTree::AllocateNode (const LeafData & node, AABB aabb) private noexcept
Allocates a leaf node.
This allocates a node from the free list as a leaf node.
AllocateNode() [3/3]
DynamicTree::Size playrho::d2::DynamicTree::AllocateNode (const BranchData & node, AABB aabb, Height height, Size parent = GetInvalidSize()) private noexcept
Allocates a branch node.
This allocates a node from the free list as a branch node.
Postcondition
The free list no longer references the returned index.
ComputeHeight()
DynamicTree::Height playrho::d2::DynamicTree::ComputeHeight (Size index) const noexcept
Computes the height of the tree from a given node.
Warning
Behavior is undefined if the given index is not valid.
Parameters
index ID of node to compute height from.
Returns
0 unless the given index is to a branch node.
ComputeTotalPerimeter()
Length playrho::d2::DynamicTree::ComputeTotalPerimeter () const noexcept
Gets the ratio of the sum of the perimeters of nodes to the root perimeter.
Note
Zero is returned if no proxies exist at the time of the call.
Returns
Value of zero or more.
CreateLeaf()
DynamicTree::Size playrho::d2::DynamicTree::CreateLeaf (const AABB & aabb, const LeafData & leafData)
Creates a new leaf node.
Creates a leaf node for a tight fitting AABB and the given data.
Note
The indices of leaf nodes that have been destroyed get reused for new nodes.
Postcondition
If the root index had been the GetInvalidSize(), then it will be set to the index returned from this method.
Returns
Index of the created leaf node.
Referenced by playrho::d2::World::CreateProxies().
DestroyLeaf()
void playrho::d2::DynamicTree::DestroyLeaf (Size index)
Destroys a leaf node.
Warning
Behavior is undefined if the given index is not valid.
Referenced by playrho::d2::World::DestroyProxies().
FindLowestCostNode()
DynamicTree::Size playrho::d2::DynamicTree::FindLowestCostNode (AABB leafAABB) const noexcept
Finds the lowest cost node.
Warning
Behavior is undefined if the tree doesn't have a valid root.
Referenced by InsertLeaf().
FindReference()
DynamicTree::Size playrho::d2::DynamicTree::FindReference (Size index) const noexcept
Finds first node which references the given index.
Note
Primarily intended for unit testing and/or debugging.
Returns
Index of node referencing the given index, or the value of GetInvalidSize().
Referenced by DestroyLeaf(), and RemoveLeaf().
FreeNode()
void playrho::d2::DynamicTree::FreeNode (Size index) private noexcept
Frees the specified node.
Warning
Behavior is undefined if the given index is not valid.
Specified node must be a "leaf" or "branch" node.
Precondition
Specified node's other index is the invalid size index.
Specified node isn't referenced by any other nodes.
Postcondition
The free list links to the given index.
Referenced by DestroyLeaf(), RebuildBottomUp(), and RemoveLeaf().
GetAABB()
AABB playrho::d2::DynamicTree::GetAABB (Size index) const inline noexcept
Gets the AABB for a leaf or branch (a non-unused node).
Warning
Behavior is undefined if the given index is not valid.
Parameters
index Leaf or branch node's ID. Must be a valid ID.
Referenced by ComputeTotalPerimeter(), playrho::d2::World::FindNewContacts(), InsertLeaf(), playrho::d2::Query(), playrho::d2::RayCast(), Rebalance(), RebuildBottomUp(), ShiftOrigin(), and playrho::d2::World::Synchronize().
GetBranchData()
DynamicTree::BranchData playrho::d2::DynamicTree::GetBranchData (Size index) const inline noexcept
Gets the branch data for the identified node.
Warning
Behavior is undefined if the given index in not a valid branch node.
Referenced by playrho::d2::Query(), and playrho::d2::RayCast().
GetHeight()
DynamicTree::Height playrho::d2::DynamicTree::GetHeight (Size index) const inline noexcept
Gets the height value for the identified node.
Warning
Behavior is undefined if the given index is not valid.
Referenced by ComputeTotalPerimeter(), DestroyLeaf(), GetMaxBalance(), InsertLeaf(), playrho::d2::Query(), playrho::d2::RayCast(), Rebalance(), RebuildBottomUp(), and UpdateLeaf().
GetLeafCount()
DynamicTree::Size playrho::d2::DynamicTree::GetLeafCount () const inline noexcept
Gets the current leaf node count.
Gets the current leaf node count.
GetLeafData()
DynamicTree::LeafData playrho::d2::DynamicTree::GetLeafData (Size index) const inline noexcept
Gets the user data for the node identified by the given identifier.
Warning
Behavior is undefined if the given index is not valid.
Parameters
index Identifier of node to get the user data for.
Returns
User data for the specified node.
Referenced by playrho::d2::World::Add(), playrho::d2::World::FindNewContacts(), playrho::d2::Query(), and playrho::d2::RayCast().
GetMaxBalance()
DynamicTree::Height playrho::d2::DynamicTree::GetMaxBalance () const noexcept
Gets the maximum balance.
This gets the maximum balance of nodes in the tree.
Note
The balance is the difference in height of the two children of a node.
GetNodeCount()
DynamicTree::Size playrho::d2::DynamicTree::GetNodeCount () const inline noexcept
Gets the current node count.
Returns
Count of existing proxies (count of nodes currently allocated).
Referenced by Validate().
InsertLeaf()
void playrho::d2::DynamicTree::InsertLeaf (Size index) private
Inserts the specified node.
Does a leaf insertion of the node with the given index into the dynamic tree.
Warning
Behavior is undefined if the given index is not valid.
Postcondition
The root index is set to the given index if the root index had been GetInvalidSize().
Referenced by CreateLeaf(), and UpdateLeaf().
Rebalance()
void playrho::d2::DynamicTree::Rebalance (Size index) private
Rebalances the tree from the given index.
Warning
Behavior is undefined if the given index is not valid.
Referenced by InsertLeaf(), and RemoveLeaf().
RebuildBottomUp()
void playrho::d2::DynamicTree::RebuildBottomUp ()
Builds an optimal tree.
Note
This operation is very expensive.
Meant for testing.
RemoveLeaf()
void playrho::d2::DynamicTree::RemoveLeaf (Size leaf) private
Removes the specified node.
Does a leaf removal of the node with the given index.
Warning
Behavior is undefined if the given index is not valid.
Postcondition
The specified leaf index is not referenced by any other nodes.
The identified node has its other value set to the invalid size.
Referenced by DestroyLeaf(), and UpdateLeaf().
ShiftOrigin()
void playrho::d2::DynamicTree::ShiftOrigin (Length2 newOrigin)
Shifts the world origin.
Note
Useful for large worlds.
The shift formula is: position -= newOrigin.
Parameters
newOrigin the new origin with respect to the old origin.
Referenced by playrho::d2::World::ShiftOrigin().
UpdateLeaf()
void playrho::d2::DynamicTree::UpdateLeaf (Size index, const AABB & aabb)
Updates a leaf node with a new AABB value.
Warning
Behavior is undefined if the given index is not valid.
Parameters
index Leaf node's ID. Behavior is undefined if this is not a valid ID.
aabb New axis aligned bounding box for the leaf node.
Referenced by playrho::d2::World::Synchronize().
Validate()
bool playrho::d2::DynamicTree::Validate () const
Validates this tree.
Note
Meant for testing.
Returns
true if valid, false otherwise.
Referenced by RebuildBottomUp().
ValidateMetrics()
bool playrho::d2::DynamicTree::ValidateMetrics (Size index) const noexcept
Validates the metrics of this tree from the given index.
Note
Meant for testing.
Returns
true if valid, false otherwise.
Referenced by Validate().
ValidateStructure()
bool playrho::d2::DynamicTree::ValidateStructure (Size index) const noexcept
Validates the structure of this tree from the given index.
Note
Meant for testing.
Returns
true if valid, false otherwise.
Referenced by Validate().
Friends And Related Function Documentation
GetAABB()
AABB GetAABB (const DynamicTree & tree) related
Gets the AABB for the given dynamic tree.
Gets the AABB that encloses all other AABB instances that are within the given dynamic tree.
Returns
Enclosing AABB or the "unset" AABB.
GetHeight()
DynamicTree::Height GetHeight (const DynamicTree & tree) related
Gets the height of the binary tree.
Returns
Height of the tree (as stored in the root node) or 0 if the root node is not valid.
TestOverlap()
bool TestOverlap (const DynamicTree & tree, DynamicTree::Size leafIdA, DynamicTree::Size leafIdB) related
Tests for overlap of the elements identified in the given dynamic tree.
Member Data Documentation
m_freeListIndex
Size playrho::d2::DynamicTree::m_freeListIndex = Size{0} private
Free list.
Index to free nodes.
Referenced by AllocateNode(), operator=(), and Validate().
m_leafCount
Size playrho::d2::DynamicTree::m_leafCount = 0 private
Leaf count.
Count of currently allocated leaf nodes.
Referenced by CreateLeaf(), DestroyLeaf(), GetLeafCount(), and operator=().
m_nodeCapacity
Size playrho::d2::DynamicTree::m_nodeCapacity private
Node capacity.
Size of buffer allocated for nodes.
Referenced by AllocateNode(), ComputeTotalPerimeter(), DestroyLeaf(), DynamicTree(), GetMaxBalance(), GetNodeCapacity(), InsertLeaf(), operator=(), Rebalance(), RebuildBottomUp(), RemoveLeaf(), ShiftOrigin(), and UpdateLeaf().
m_nodeCount
Size playrho::d2::DynamicTree::m_nodeCount = Size{0} private
Node count.
Count of currently allocated nodes.
Referenced by AllocateNode(), GetNodeCount(), operator=(), and RebuildBottomUp().
m_nodes
TreeNode* playrho::d2::DynamicTree::m_nodes private
Nodes.
Initialized on construction.
Referenced by AllocateNode(), ComputeTotalPerimeter(), DestroyLeaf(), GetMaxBalance(), InsertLeaf(), operator=(), Rebalance(), RebuildBottomUp(), ShiftOrigin(), UpdateLeaf(), Validate(), and ~DynamicTree().
The documentation for this class was generated from the following files:
DynamicTree.hpp
DynamicTree.cpp