PlayRho: playrho::RevoluteJoint Class Reference
playrho::RevoluteJoint Class Reference
Joint Classes
Revolute Joint.
#include <RevoluteJoint.hpp>
Public Member Functions
RevoluteJoint (const RevoluteJointDef &def)
Initializing constructor.
void Accept (JointVisitor &visitor) const override
Accepts a visitor.
Length2D GetAnchorA () const override
Get the anchor point on bodyA in world coordinates.
Length2D GetAnchorB () const override
Get the anchor point on bodyB in world coordinates.
Length2D GetLocalAnchorA () const noexcept
The local anchor point relative to bodyA's origin.
Length2D GetLocalAnchorB () const noexcept
The local anchor point relative to bodyB's origin.
Angle GetReferenceAngle () const noexcept
Get the reference angle.
bool IsLimitEnabled () const noexcept
Is the joint limit enabled?
void EnableLimit (bool flag)
Enable/disable the joint limit.
Angle GetLowerLimit () const noexcept
Get the lower joint limit.
Angle GetUpperLimit () const noexcept
Get the upper joint limit.
void SetLimits (Angle lower, Angle upper)
Set the joint limits.
bool IsMotorEnabled () const noexcept
Is the joint motor enabled?
void EnableMotor (bool flag)
Enable/disable the joint motor.
void SetMotorSpeed (AngularVelocity speed)
Set the angular motor speed.
AngularVelocity GetMotorSpeed () const noexcept
Gets the angular motor speed.
void SetMaxMotorTorque (Torque torque)
Set the maximum motor torque.
Torque GetMaxMotorTorque () const noexcept
Gets the max motor torque.
Momentum2D GetLinearReaction () const override
Get the linear reaction.
AngularMomentum GetAngularReaction () const override
Get the angular reaction due to the joint limit.
Torque GetMotorTorque (Frequency inv_dt) const
Get the current motor torque given the inverse time step.
LimitState GetLimitState () const noexcept
Gets the current limit state.
Public Member Functions inherited from playrho::Joint
Body * GetBodyA () const noexcept
Gets the first body attached to this joint.
Body * GetBodyB () const noexcept
Gets the second body attached to this joint.
void * GetUserData () const noexcept
Get the user data pointer.
void SetUserData (void *data) noexcept
Set the user data pointer.
bool GetCollideConnected () const noexcept
Gets collide connected.
virtual void ShiftOrigin (const Length2D newOrigin)
Shifts the origin for any points stored in world coordinates.
Private Member Functions
void InitVelocityConstraints (BodyConstraintsMap &bodies, const StepConf &step, const ConstraintSolverConf &conf) override
Initializes velocity constraint data based on the given solver data.
bool SolveVelocityConstraints (BodyConstraintsMap &bodies, const StepConf &step) override
Solves velocity constraint.
bool SolvePositionConstraints (BodyConstraintsMap &bodies, const ConstraintSolverConf &conf) const override
Solves the position constraint.
Private Attributes
Length2D m_localAnchorA
Local anchor A.
Length2D m_localAnchorB
Local anchor B.
Vec3 m_impulse = Vec3_zero
Impulse. Mofified by: InitVelocityConstraints, SolveVelocityConstraints.
AngularMomentum m_motorImpulse = 0
Motor impulse. Modified by: InitVelocityConstraints, SolveVelocityConstraints.
bool m_enableMotor
Enable motor. true if motor is enabled.
Torque m_maxMotorTorque
Max motor torque.
AngularVelocity m_motorSpeed
Motor speed.
bool m_enableLimit
Enable limit. true if limit is enabled.
Angle m_referenceAngle
Reference angle.
Angle m_lowerAngle
Lower angle.
Angle m_upperAngle
Upper angle.
Length2D m_rA
Rotated delta of body A's local center from local anchor A.
Length2D m_rB
Rotated delta of body B's local center from local anchor B.
Mat33 m_mass
Effective mass for point-to-point constraint.
RotInertia m_motorMass
Effective mass for motor/limit angular constraint.
LimitState m_limitState = e_inactiveLimit
Limit state.
Related Functions
(Note that these are not member functions.)
Angle GetJointAngle (const RevoluteJoint &joint)
Gets the current joint angle.
AngularVelocity GetAngularVelocity (const RevoluteJoint &joint)
Gets the current joint angle speed.
RevoluteJointDef GetRevoluteJointDef (const RevoluteJoint &joint) noexcept
Gets the definition data for the given joint.
Related Functions inherited from playrho::Joint
bool IsEnabled (const Joint &j) noexcept
Short-cut function to determine if both bodies are enabled.
void SetAwake (Joint &j) noexcept
Wakes up the joined bodies.
JointCounter GetWorldIndex (const Joint *joint)
Gets the world index of the given joint.
JointType GetType (const Joint &joint) noexcept
Gets the type of the given joint.
Additional Inherited Members
Public Types inherited from playrho::Joint
enum LimitState { e_inactiveLimit, e_atLowerLimit, e_atUpperLimit, e_equalLimits }
Limit state.
Static Public Member Functions inherited from playrho::Joint
static bool IsOkay (const JointDef &def) noexcept
Is the given definition okay.
Protected Member Functions inherited from playrho::Joint
Joint (const JointDef &def)
Initializing constructor.
Detailed Description
Revolute Joint.
A revolute joint constrains two bodies to share a common point while they are free to rotate about the point. The relative rotation about the shared point is the joint angle.
Note
You can limit the relative rotation with a joint limit that specifies a lower and upper angle. You can use a motor to drive the relative rotation about the shared point. A maximum motor torque is provided so that infinite forces are not generated.
Member Function Documentation
Joint::LimitState playrho::RevoluteJoint::GetLimitState () const inline noexcept
Gets the current limit state.
Note
This will be e_inactiveLimit unless the joint limit has been enabled.
Referenced by GetMaxMotorTorque().
void playrho::RevoluteJoint::InitVelocityConstraints (BodyConstraintsMap & bodies, const StepConf & step, const ConstraintSolverConf & conf) override private virtual
Initializes velocity constraint data based on the given solver data.
Note
This MUST be called prior to calling SolveVelocityConstraints.
See also
SolveVelocityConstraints.
Implements playrho::Joint.
Referenced by GetMaxMotorTorque().
bool playrho::RevoluteJoint::SolvePositionConstraints (BodyConstraintsMap & bodies, const ConstraintSolverConf & conf) const override private virtual
Solves the position constraint.
Returns
true if the position errors are within tolerance.
Implements playrho::Joint.
Referenced by GetMaxMotorTorque().
bool playrho::RevoluteJoint::SolveVelocityConstraints (BodyConstraintsMap & bodies, const StepConf & step) override private virtual
Solves velocity constraint.
Precondition
InitVelocityConstraints has been called.
See also
InitVelocityConstraints.
Returns
true if velocity is "solved", false otherwise.
Implements playrho::Joint.
Referenced by GetMaxMotorTorque().
Friends And Related Function Documentation
AngularVelocity GetAngularVelocity (const RevoluteJoint & joint) related
Gets the current joint angle speed.
Referenced by GetLimitState().
Angle GetJointAngle (const RevoluteJoint & joint) related
Gets the current joint angle.
Referenced by GetLimitState().
RevoluteJointDef GetRevoluteJointDef (const RevoluteJoint & joint) related
Gets the definition data for the given joint.
The documentation for this class was generated from the following files:
RevoluteJoint.hpp
RevoluteJoint.cpp
RevoluteJointDef.hpp