PlayRho: playrho::WheelJoint Class Reference
playrho::WheelJoint Class Reference
Joint Classes
Wheel joint.
#include <WheelJoint.hpp>
Public Member Functions
WheelJoint (const WheelJointDef &def)
Initializing constructor.
void Accept (JointVisitor &visitor) const override
Accepts a visitor.
Length2D GetAnchorA () const override
Get the anchor point on bodyA in world coordinates.
Length2D GetAnchorB () const override
Get the anchor point on bodyB in world coordinates.
Momentum2D GetLinearReaction () const override
Get the linear reaction on bodyB at the joint anchor.
AngularMomentum GetAngularReaction () const override
Get the angular reaction on bodyB.
Length2D GetLocalAnchorA () const
The local anchor point relative to bodyA's origin.
Length2D GetLocalAnchorB () const
The local anchor point relative to bodyB's origin.
UnitVec2 GetLocalAxisA () const
The local joint axis relative to bodyA.
bool IsMotorEnabled () const noexcept
Is the joint motor enabled?
void EnableMotor (bool flag)
Enable/disable the joint motor.
void SetMotorSpeed (AngularVelocity speed)
Set the angular motor speed.
AngularVelocity GetMotorSpeed () const
Get the angular motor speed.
void SetMaxMotorTorque (Torque torque)
Sets the maximum motor torque.
Torque GetMaxMotorTorque () const
Gets the maximum motor torque.
Torque GetMotorTorque (Frequency inv_dt) const
Get the current motor torque given the inverse time step.
void SetSpringFrequency (Frequency frequency)
Sets the spring frequency.
Frequency GetSpringFrequency () const
Gets the spring frequency.
void SetSpringDampingRatio (Real ratio)
Sets the spring damping ratio.
Real GetSpringDampingRatio () const
Gets the spring damping ratio.
Public Member Functions inherited from playrho::Joint
Body * GetBodyA () const noexcept
Gets the first body attached to this joint.
Body * GetBodyB () const noexcept
Gets the second body attached to this joint.
void * GetUserData () const noexcept
Get the user data pointer.
void SetUserData (void *data) noexcept
Set the user data pointer.
bool GetCollideConnected () const noexcept
Gets collide connected.
virtual void ShiftOrigin (const Length2D newOrigin)
Shifts the origin for any points stored in world coordinates.
Private Member Functions
void InitVelocityConstraints (BodyConstraintsMap &bodies, const StepConf &step, const ConstraintSolverConf &conf) override
Initializes velocity constraint data based on the given solver data.
bool SolveVelocityConstraints (BodyConstraintsMap &bodies, const StepConf &step) override
Solves velocity constraint.
bool SolvePositionConstraints (BodyConstraintsMap &bodies, const ConstraintSolverConf &conf) const override
Solves the position constraint.
Private Attributes
Frequency m_frequency
Frequency.
Real m_dampingRatio
Damping ratio.
Length2D m_localAnchorA
Local anchor A.
Length2D m_localAnchorB
Local anchor B.
UnitVec2 m_localXAxisA
Local X axis A.
UnitVec2 m_localYAxisA
Local Y axis A.
Momentum m_impulse = 0
Impulse.
AngularMomentum m_motorImpulse = 0
Motor impulse.
Momentum m_springImpulse = 0
Spring impulse.
Torque m_maxMotorTorque
Max motor torque.
AngularVelocity m_motorSpeed
Motor speed.
bool m_enableMotor
Enable motor. true if motor is enabled.
UnitVec2 m_ax
AX directional.
UnitVec2 m_ay
AY directional.
Length m_sAx
sAx location.
Length m_sBx
sBx location.
Length m_sAy
sAy location.
Length m_sBy
sBy location.
Mass m_mass = Mass{0}
Mass.
RotInertia m_motorMass = RotInertia{0}
Motor mass.
Mass m_springMass = Mass{0}
Spring mass.
LinearVelocity m_bias = LinearVelocity{0}
Bias.
InvMass m_gamma = InvMass{0}
Gamma.
Related Functions
(Note that these are not member functions.)
Length GetJointTranslation (const WheelJoint &joint) noexcept
Get the current joint translation.
AngularVelocity GetAngularVelocity (const WheelJoint &joint) noexcept
Get the current joint translation speed.
WheelJointDef GetWheelJointDef (const WheelJoint &joint) noexcept
Gets the definition data for the given joint.
Related Functions inherited from playrho::Joint
bool IsEnabled (const Joint &j) noexcept
Short-cut function to determine if both bodies are enabled.
void SetAwake (Joint &j) noexcept
Wakes up the joined bodies.
JointCounter GetWorldIndex (const Joint *joint)
Gets the world index of the given joint.
JointType GetType (const Joint &joint) noexcept
Gets the type of the given joint.
Additional Inherited Members
Public Types inherited from playrho::Joint
enum LimitState { e_inactiveLimit, e_atLowerLimit, e_atUpperLimit, e_equalLimits }
Limit state.
Static Public Member Functions inherited from playrho::Joint
static bool IsOkay (const JointDef &def) noexcept
Is the given definition okay.
Protected Member Functions inherited from playrho::Joint
Joint (const JointDef &def)
Initializing constructor.
Detailed Description
Wheel joint.
This joint provides two degrees of freedom: translation along an axis fixed in bodyA and rotation in the plane. In other words, it is a point to line constraint with a rotational motor and a linear spring/damper.
Note
This joint is designed for vehicle suspensions.
Member Function Documentation
void playrho::WheelJoint::InitVelocityConstraints (BodyConstraintsMap & bodies, const StepConf & step, const ConstraintSolverConf & conf) override private virtual
Initializes velocity constraint data based on the given solver data.
Note
This MUST be called prior to calling SolveVelocityConstraints.
See also
SolveVelocityConstraints.
Implements playrho::Joint.
Referenced by IsMotorEnabled().
void playrho::WheelJoint::SetSpringFrequency (Frequency frequency) inline
Sets the spring frequency.
Note
Setting the frequency to zero disables the spring.
Referenced by IsMotorEnabled().
bool playrho::WheelJoint::SolvePositionConstraints (BodyConstraintsMap & bodies, const ConstraintSolverConf & conf) const override private virtual
Solves the position constraint.
Returns
true if the position errors are within tolerance.
Implements playrho::Joint.
Referenced by IsMotorEnabled().
bool playrho::WheelJoint::SolveVelocityConstraints (BodyConstraintsMap & bodies, const StepConf & step) override private virtual
Solves velocity constraint.
Precondition
InitVelocityConstraints has been called.
See also
InitVelocityConstraints.
Returns
true if velocity is "solved", false otherwise.
Implements playrho::Joint.
Referenced by IsMotorEnabled().
Friends And Related Function Documentation
AngularVelocity GetAngularVelocity (const WheelJoint & joint) related
Get the current joint translation speed.
Referenced by GetSpringDampingRatio().
Length GetJointTranslation (const WheelJoint & joint) related
Get the current joint translation.
Referenced by GetSpringDampingRatio().
WheelJointDef GetWheelJointDef (const WheelJoint & joint) related
Gets the definition data for the given joint.
The documentation for this class was generated from the following files:
WheelJoint.hpp
WheelJoint.cpp
WheelJointDef.hpp