PlayRho: playrho::MultiShape Class Reference
playrho::MultiShape Class Reference
Shape Classes
The "multi-shape" shape.
#include <MultiShape.hpp>
Classes
struct Conf
Configuration data for multi-shape shapes.
struct ConvexHull
Convex hull.
Public Types
using VertexCounter = std::remove_const< decltype(MaxShapeVertices)>::type
Vertex count type.
Public Member Functions
MultiShape (const Conf &conf=GetDefaultConf()) noexcept
Default constructor.
MultiShape (const MultiShape &)=default
Copy constructor.
ChildCounter GetChildCount () const noexcept override
Gets the number of child primitives of the shape.
DistanceProxy GetChild (ChildCounter index) const override
Gets the child for the given index.
MassData GetMassData () const noexcept override
Computes the mass properties of this shape using its dimensions and density. The inertia tensor is computed about the local origin.
void Accept (ShapeVisitor &visitor) const override
Accepts a visitor.
void AddConvexHull (const VertexSet &pointSet) noexcept
Creates a convex hull from the given set of local points. The size of the set must be in the range [1, MaxShapeVertices].
Public Member Functions inherited from playrho::Shape
NonNegative< Length > GetVertexRadius () const noexcept
Gets the vertex radius.
void SetVertexRadius (NonNegative< Length > vertexRadius) noexcept
Sets the vertex radius.
NonNegative< Density > GetDensity () const noexcept
Gets the density of this fixture.
void SetDensity (NonNegative< Density > density) noexcept
Sets the density of this fixture.
Real GetFriction () const noexcept
Gets the coefficient of friction.
void SetFriction (NonNegative< Real > friction) noexcept
Sets the coefficient of friction.
Real GetRestitution () const noexcept
Gets the coefficient of restitution.
void SetRestitution (Finite< Real > restitution) noexcept
Sets the coefficient of restitution.
Static Public Member Functions
static constexpr Length GetDefaultVertexRadius () noexcept
Gets the default vertex radius for the MultiShape.
static constexpr Conf GetDefaultConf () noexcept
Gets the default configuration for a MultiShape.
Static Public Attributes
static constexpr auto InvalidVertex = static_cast<VertexCounter>(-1)
Invalid vertex.
Private Attributes
std::vector< ConvexHull > m_children
Children.
Additional Inherited Members
Protected Member Functions inherited from playrho::Shape
Shape ()=default
Default constructor.
Shape (const ShapeDef &conf) noexcept
Initializing constructor.
Shape (const Shape &other)=default
Copy constructor.
Shape (Shape &&other)=default
Move constructor.
Shape & operator= (const Shape &other)=default
Copy assignment operator.
Shape & operator= (Shape &&other)=default
Move assignment operator.
Related Functions inherited from playrho::Shape
AABB ComputeAABB (const Shape &shape, const Transformation &xf) noexcept
Computes the AABB for the given shape with the given transformation.
RayCastOutput RayCast (const Shape &shape, ChildCounter childIndex, const RayCastInput &input, const Transformation &transform) noexcept
Cast a ray against the child of the given shape.
NonNegative< Length > GetVertexRadius (const Shape &shape) noexcept
Gets the vertex radius of the given shape.
bool TestPoint (const Shape &shape, Length2D point) noexcept
Test a point for containment in the given shape.
Detailed Description
The "multi-shape" shape.
Composes zero or more convex shapes into what can be a concave shape.
Member Typedef Documentation
using playrho::MultiShape::VertexCounter = std::remove_const<decltype(MaxShapeVertices)>::type
Vertex count type.
Note
This type must not support more than 255 vertices as that would conflict with the ContactFeature::Index type.
Constructor & Destructor Documentation
playrho::MultiShape::MultiShape (const Conf & conf = GetDefaultConf()) inline explicit noexcept
Default constructor.
Constructs a polygon shape with a 0,0 centroid and vertex count of 0.
Note
Polygons with a vertex count less than 1 are "degenerate" and should be treated as invalid.
Member Function Documentation
void playrho::MultiShape::AddConvexHull (const VertexSet & pointSet) noexcept
Creates a convex hull from the given set of local points. The size of the set must be in the range [1, MaxShapeVertices].
Warning
the points may be re-ordered, even if they form a convex polygon
collinear points are handled but not removed. Collinear points may lead to poor stacking behavior.
Referenced by MultiShape().
DistanceProxy playrho::MultiShape::GetChild (ChildCounter index) const inline override virtual
Gets the child for the given index.
Parameters
index Index to a child element of the shape. Value must be less than the number of child primitives of the shape.
Note
The shape must remain in scope while the proxy is in use.
Exceptions
InvalidArgument if the given index is out of range.
See also
GetChildCount
Implements playrho::Shape.
Referenced by MultiShape().
ChildCounter playrho::MultiShape::GetChildCount () const inline override virtual noexcept
Gets the number of child primitives of the shape.
Returns
Non-negative count.
Implements playrho::Shape.
Referenced by GetChild(), and MultiShape().
MassData playrho::MultiShape::GetMassData () const override virtual noexcept
Computes the mass properties of this shape using its dimensions and density. The inertia tensor is computed about the local origin.
Returns
Mass data for this shape.
Implements playrho::Shape.
Referenced by MultiShape().
The documentation for this class was generated from the following files:
MultiShape.hpp
MultiShape.cpp