PlayRho: playrho::DynamicTree2D::TreeNode Class Reference
playrho::DynamicTree2D::TreeNode Class Reference
A node in the dynamic tree.
#include <DynamicTree.hpp>
Public Member Functions
PLAYRHO_CONSTEXPR TreeNode (const TreeNode &other)=default
Copy constructor.
PLAYRHO_CONSTEXPR TreeNode (TreeNode &&other)=default
Move constructor.
PLAYRHO_CONSTEXPR TreeNode (Size other=DynamicTree2D::GetInvalidSize()) noexcept
Initializing constructor.
PLAYRHO_CONSTEXPR TreeNode (const LeafData &value, AABB2D aabb, Size other=DynamicTree2D::GetInvalidSize()) noexcept
Initializing constructor.
PLAYRHO_CONSTEXPR TreeNode (const BranchData &value, AABB2D aabb, Height height, Size other=DynamicTree2D::GetInvalidSize()) noexcept
Initializing constructor.
TreeNode & operator= (const TreeNode &other)
Copy assignment operator.
TreeNode & operator= (TreeNode &&other)=default
Move assignment operator.
PLAYRHO_CONSTEXPR Height GetHeight () const noexcept
Gets the node "height".
PLAYRHO_CONSTEXPR TreeNode & SetHeight (Height value) noexcept
Sets the node "height" to the given value.
PLAYRHO_CONSTEXPR Size GetOther () const noexcept
Gets the node's "other" index.
PLAYRHO_CONSTEXPR TreeNode & SetOther (Size other) noexcept
Sets the node's "other" index to the given value.
PLAYRHO_CONSTEXPR AABB2D GetAABB () const noexcept
Gets the node's AABB.
PLAYRHO_CONSTEXPR TreeNode & SetAABB (AABB2D value) noexcept
Sets the node's AABB.
PLAYRHO_CONSTEXPR UnusedData AsUnused () const noexcept
Gets the node as an "unused" value.
PLAYRHO_CONSTEXPR LeafData AsLeaf () const noexcept
Gets the node as a "leaf" value.
PLAYRHO_CONSTEXPR BranchData AsBranch () const noexcept
Gets the node as a "branch" value.
PLAYRHO_CONSTEXPR UnusedData & AsUnused () noexcept
Gets the node as an "unused" value.
PLAYRHO_CONSTEXPR LeafData & AsLeaf () noexcept
Gets the node as a "leaf" value.
PLAYRHO_CONSTEXPR BranchData & AsBranch () noexcept
Gets the node as a "branch" value.
PLAYRHO_CONSTEXPR TreeNode & Assign (Size height, const UnusedData &value) noexcept
Assign's the node's value.
PLAYRHO_CONSTEXPR TreeNode & Assign (Size height, const LeafData &value) noexcept
Assign's the node's value.
PLAYRHO_CONSTEXPR TreeNode & Assign (Size height, const BranchData &value) noexcept
Assign's the node's value.
Private Attributes
Height m_height = GetInvalidHeight()
Height.
Size m_other = DynamicTree2D::GetInvalidSize()
Other node.
AABB2D m_aabb
AABB.
VariantData m_variant
Variant data for the node.
Related Functions
(Note that these are not member functions.)
PLAYRHO_CONSTEXPR bool IsUnused (const DynamicTree2D::TreeNode &node) noexcept
Is unused.
PLAYRHO_CONSTEXPR bool IsLeaf (const DynamicTree2D::TreeNode &node) noexcept
Is leaf.
PLAYRHO_CONSTEXPR bool IsBranch (const DynamicTree2D::TreeNode &node) noexcept
Is branch.
PLAYRHO_CONSTEXPR bool IsUnused (const DynamicTree2D::TreeNode &node) noexcept
Whether this node is free (or allocated).
PLAYRHO_CONSTEXPR bool IsLeaf (const DynamicTree2D::TreeNode &node) noexcept
Whether or not this node is a leaf node.
PLAYRHO_CONSTEXPR bool IsBranch (const DynamicTree2D::TreeNode &node) noexcept
Is branch.
PLAYRHO_CONSTEXPR AABB2D GetAABB (const DynamicTree2D::TreeNode &node) noexcept
Gets the AABB of the given dynamic tree node.
PLAYRHO_CONSTEXPR DynamicTree2D::Size GetNext (const DynamicTree2D::TreeNode &node) noexcept
Gets the next index of the given node.
DynamicTree2D::TreeNode & SetParent (DynamicTree2D::TreeNode &node, DynamicTree2D::Size other) noexcept
Sets the parent index of the given node.
Detailed Description
A node in the dynamic tree.
Note
Users do not interact with this directly.
By using indexes to other tree nodes, these don't need to be updated if the memory for other nodes is relocated.
On some 64-bit architectures, pointers are 8-bytes, while indices need only be 4-bytes. So using indices can also save 4-bytes.
This data structure is 48-bytes large on at least one 64-bit platform.
Friends And Related Function Documentation
GetAABB()
PLAYRHO_CONSTEXPR AABB2D GetAABB (const DynamicTree2D::TreeNode & node) related
Gets the AABB of the given dynamic tree node.
GetNext()
PLAYRHO_CONSTEXPR DynamicTree2D::Size GetNext (const DynamicTree2D::TreeNode & node) related
Gets the next index of the given node.
Warning
Behavior is undefined if the given node is not an "unused" node.
IsBranch() [1/2]
PLAYRHO_CONSTEXPR bool IsBranch (const DynamicTree2D::TreeNode & node) related
Is branch.
Determines whether the given dynamic tree node is a branch node. Branch nodes have 2 indices to child nodes.
Referenced by AsBranch().
IsBranch() [2/2]
PLAYRHO_CONSTEXPR bool IsBranch (const DynamicTree2D::TreeNode & node) related
Is branch.
Determines whether the given node is a "branch" node.
IsLeaf() [1/2]
PLAYRHO_CONSTEXPR bool IsLeaf (const DynamicTree2D::TreeNode & node) related
Is leaf.
Determines whether the given dynamic tree node is a leaf node. Leaf nodes have a pointer to user data.
Referenced by AsLeaf().
IsLeaf() [2/2]
PLAYRHO_CONSTEXPR bool IsLeaf (const DynamicTree2D::TreeNode & node) related
Whether or not this node is a leaf node.
Note
This has constant complexity.
Returns
true if this is a leaf node, false otherwise.
IsUnused() [1/2]
PLAYRHO_CONSTEXPR bool IsUnused (const DynamicTree2D::TreeNode & node) related
Is unused.
Determines whether the given dynamic tree node is an unused node.
Referenced by AsUnused().
IsUnused() [2/2]
PLAYRHO_CONSTEXPR bool IsUnused (const DynamicTree2D::TreeNode & node) related
Whether this node is free (or allocated).
SetParent()
DynamicTree2D::TreeNode & SetParent (DynamicTree2D::TreeNode & node, DynamicTree2D::Size other) related
Sets the parent index of the given node.
Warning
Behavior is undefined if the given node is not a "branch" node.
Member Data Documentation
m_height
Height playrho::DynamicTree2D::TreeNode::m_height = GetInvalidHeight() private
Height.
"Height" for tree balancing.
Note
0 if leaf node.
Value of DynamicTree::GetInvalidHeight() if free (unallocated) node.
Referenced by AsBranch(), AsLeaf(), Assign(), AsUnused(), GetHeight(), operator=(), and SetHeight().
m_other
Size playrho::DynamicTree2D::TreeNode::m_other = DynamicTree2D::GetInvalidSize() private
Other node.
Index of another node.
Referenced by GetOther(), operator=(), and SetOther().
The documentation for this class was generated from the following file:
DynamicTree.hpp