PlayRho: playrho::World2D Class Reference
playrho::World2D Class Reference
Definition of an independent and simulatable "world".
#include <World.hpp>
Classes
struct ContactToiData
Contact TOI data.
struct DestroyContactsStats
Destroy contacts statistics.
struct IslandSolverResults
Island solver results.
struct ProcessContactsOutput
Process contacts output.
struct UpdateContactsData
Update contacts data.
struct UpdateContactsStats
Update contacts statistics.
Public Types
enum RayCastOpcode { RayCastOpcode::Terminate, RayCastOpcode::IgnoreFixture, RayCastOpcode::ClipRay, RayCastOpcode::ResetRay }
World ray cast opcode enumeration.
using proxy_size_type = std::remove_const< decltype(MaxContacts)>::type
Proxy size type.
using Bodies = std::vector< Body2D * >
Bodies container type.
using Contacts = std::vector< KeyedContactPtr >
Contacts container type.
using Joints = std::vector< Joint2D * >
Joints container type.
using QueryFixtureCallback = std::function< bool(Fixture2D *fixture, ChildCounter child)>
Query AABB for fixtures callback function type.
using RayCastCallback = std::function< RayCastOpcode(Fixture2D *fixture, ChildCounter child, Length2 point, UnitVec2 normal)>
Ray cast callback function signature.
Public Member Functions
World2D (const WorldDef &def=GetDefaultWorldDef())
Constructs a world object.
World2D (const World2D &other)
Copy constructor.
World2D & operator= (const World2D &other)
Assignment operator.
~World2D ()
Destructor.
void Clear () noexcept
Clears this world.
void SetDestructionListener (DestructionListener *listener) noexcept
Register a destruction listener. The listener is owned by you and must remain in scope.
void SetContactFilter (ContactFilter2D *filter) noexcept
Register a contact filter to provide specific control over collision. Otherwise the default filter is used. The listener is owned by you and must remain in scope.
void SetContactListener (ContactListener2D *listener) noexcept
Register a contact event listener. The listener is owned by you and must remain in scope.
Body2D * CreateBody (const BodyDef &def=GetDefaultBodyDef())
Creates a rigid body given a definition.
void Destroy (Body2D *body)
Destroys the given body.
Joint2D * CreateJoint (const JointDef &def)
Creates a joint to constrain bodies together.
void Destroy (Joint2D *joint)
Destroys a joint.
StepStats Step (const StepConf &conf)
Steps the world simulation according to the given configuration.
void QueryAABB (const AABB2D &aabb, QueryFixtureCallback callback) const
Queries the world for all fixtures that potentially overlap the provided AABB.
void RayCast (Length2 point1, Length2 point2, RayCastCallback callback) const
Ray-cast the world for all fixtures in the path of the ray.
SizedRange< Bodies::iterator > GetBodies () noexcept
Gets the world body range for this world.
SizedRange< Bodies::const_iterator > GetBodies () const noexcept
Gets the world body range for this constant world.
SizedRange< Joints::const_iterator > GetJoints () const noexcept
Gets the world joint range.
SizedRange< Joints::iterator > GetJoints () noexcept
Gets the world joint range.
SizedRange< Contacts::const_iterator > GetContacts () const noexcept
Gets the world contact range.
bool GetSubStepping () const noexcept
Gets whether or not sub-stepping is enabled.
void SetSubStepping (bool flag) noexcept
Enables/disables single stepped continuous physics.
const DynamicTree2D & GetTree () const noexcept
Gets access to the broad-phase dynamic tree information.
void SetGravity (LinearAcceleration2 gravity) noexcept
Changes the global gravity vector.
LinearAcceleration2 GetGravity () const noexcept
Gets the global gravity vector.
bool IsLocked () const noexcept
Is the world locked (in the middle of a time step).
void ShiftOrigin (Length2 newOrigin)
Shifts the world origin.
Length GetMinVertexRadius () const noexcept
Gets the minimum vertex radius that shapes in this world can be.
Length GetMaxVertexRadius () const noexcept
Gets the maximum vertex radius that shapes in this world can be.
Frequency GetInvDeltaTime () const noexcept
Gets the inverse delta time.
void SetType (Body2D &body, BodyType type)
Sets the type of the given body.
bool RegisterForProxies (Fixture2D *fixture)
Register for proxies for the given fixture.
bool RegisterForProxies (Body2D *body)
Register for proxies for the given body.
Fixture2D * CreateFixture (Body2D &body, const Shape2D &shape, const FixtureDef &def=GetDefaultFixtureDef(), bool resetMassData=true)
Creates a fixture with the given parameters.
bool DestroyFixture (Fixture2D *fixture, bool resetMassData=true)
Destroys a fixture.
bool TouchProxies (Fixture2D &fixture) noexcept
Touches each proxy of the given fixture.
void SetNewFixtures () noexcept
Sets new fixtures flag.
Private Types
enum Flag : FlagsType { e_newFixture = 0x0001, e_locked = 0x0002, e_substepping = 0x0020, e_stepComplete = 0x0040 }
Flag enumeration.
using FlagsType = std::uint32_t
Flags type data type.
using ProxyId = DynamicTree2D::Size
Proxy ID type alias.
using ContactKeyQueue = std::vector< ContactKey >
Contact key queue type alias.
using ProxyQueue = std::vector< ProxyId >
Proxy queue type alias.
using FixtureQueue = std::vector< Fixture2D * >
Fixture queue type alias.
using BodyQueue = std::vector< Body2D * >
Body queue type alias.
using BodyStack = std::vector< Body2D * >
Body stack.
Private Member Functions
void CopyBodies (std::map< const Body2D *, Body2D *> &bodyMap, std::map< const Fixture2D *, Fixture2D *> &fixtureMap, SizedRange< World2D::Bodies::const_iterator > range)
Copies bodies.
void CopyJoints (const std::map< const Body2D *, Body2D *> &bodyMap, SizedRange< World2D::Joints::const_iterator > range)
Copies joints.
void CopyContacts (const std::map< const Body2D *, Body2D *> &bodyMap, const std::map< const Fixture2D *, Fixture2D *> &fixtureMap, SizedRange< World2D::Contacts::const_iterator > range)
Copies contacts.
void InternalDestroy (Joint2D *joint)
Internal destroy.
RegStepStats SolveReg (const StepConf &conf)
Solves the step.
IslandSolverResults SolveRegIslandViaGS (const StepConf &conf, Island2D island)
Solves the given island (regularly).
void AddToIsland (Island2D &island, Body2D &seed, Bodies::size_type &remNumBodies, Contacts::size_type &remNumContacts, Joints::size_type &remNumJoints)
Adds to the island based off of a given "seed" body.
void AddToIsland (Island2D &island, BodyStack &stack, Bodies::size_type &remNumBodies, Contacts::size_type &remNumContacts, Joints::size_type &remNumJoints)
Adds to the island.
void AddContactsToIsland (Island2D &island, BodyStack &stack, const Body2D *b)
Adds contacts to the island.
void AddJointsToIsland (Island2D &island, BodyStack &stack, const Body2D *b)
Adds joints to the island.
Bodies::size_type RemoveUnspeedablesFromIslanded (const std::vector< Body2D *> &bodies)
Removes unspeedables from the is islanded state.
ToiStepStats SolveToi (const StepConf &conf)
Solves the step using successive time of impact (TOI) events.
IslandSolverResults SolveToi (const StepConf &conf, Contact2D &contact)
Solves collisions for the given time of impact.
IslandSolverResults SolveToiViaGS (const StepConf &conf, Island2D &island)
Solves the time of impact for bodies 0 and 1 of the given island.
void ResetBodiesForSolveTOI ()
Reset bodies for solve TOI.
void ResetContactsForSolveTOI ()
Reset contacts for solve TOI.
void ResetContactsForSolveTOI (Body2D &body)
Reset contacts for solve TOI.
ProcessContactsOutput ProcessContactsForTOI (Island2D &island, Body2D &body, Real toi, const StepConf &conf)
Processes the contacts of a given body for TOI handling.
bool Add (Joint2D *j)
Adds the given joint to this world.
bool Remove (const Body2D &b)
Removes the given body from this world.
bool Remove (Joint2D &j)
Removes the given joint from this world.
bool IsStepComplete () const noexcept
Whether or not "step" is complete.
void SetStepComplete (bool value) noexcept
Sets the step complete state.
void SetAllowSleeping () noexcept
Sets the allow sleeping state.
void UnsetAllowSleeping () noexcept
Unsets the allow sleeping state.
UpdateContactsData UpdateContactTOIs (const StepConf &conf)
Updates the contact times of impact.
ContactToiData GetSoonestContact () const noexcept
Gets the soonest contact.
bool HasNewFixtures () const noexcept
Determines whether this world has new fixtures.
void UnsetNewFixtures () noexcept
Unsets the new fixtures state.
ContactCounter FindNewContacts ()
Finds new contacts.
DestroyContactsStats DestroyContacts (Contacts &contacts)
Processes the narrow phase collision for the contacts collection.
UpdateContactsStats UpdateContacts (Contacts &contacts, const StepConf &conf)
Update contacts.
bool ShouldCollide (const Fixture2D *fixtureA, const Fixture2D *fixtureB)
Determines whether the two fixtures should collide.
void Destroy (Contact2D *contact, Body2D *from)
Destroys the given contact and removes it from its container.
bool Add (ContactKey key)
Adds a contact for the proxies identified by the key if appropriate.
void RegisterForProcessing (ProxyId pid) noexcept
Registers the given dynamic tree ID for processing.
void UnregisterForProcessing (ProxyId pid) noexcept
Unregisters the given dynamic tree ID from processing.
void InternalDestroy (Contact2D *contact, Body2D *from=nullptr)
Destroys the given contact.
void CreateProxies (Fixture2D &fixture, Length aabbExtension)
Creates proxies for every child of the given fixture's shape.
void DestroyProxies (Fixture2D &fixture)
Destroys the given fixture's proxies.
void InternalTouchProxies (Fixture2D &fixture) noexcept
Touches each proxy of the given fixture.
ContactCounter Synchronize (Body2D &body, Transformation2D xfm1, Transformation2D xfm2, Real multiplier, Length extension)
Synchronizes the given body.
ContactCounter Synchronize (Fixture2D &fixture, Transformation2D xfm1, Transformation2D xfm2, Length2 displacement, Length extension)
Synchronizes the given fixture.
void CreateAndDestroyProxies (const StepConf &conf)
Creates and destroys proxies.
void CreateAndDestroyProxies (Fixture2D &fixture, const StepConf &conf)
Creates and destroys proxies for the given fixture.
PreStepStats::counter_type SynchronizeProxies (const StepConf &conf)
Synchronizes proxies of the bodies for proxies.
bool IsIslanded (const Body2D *body) const noexcept
Whether the given body is in an island.
bool IsIslanded (const Contact2D *contact) const noexcept
Whether the given contact is in an island.
bool IsIslanded (const Joint2D *joint) const noexcept
Whether the given joint is in an island.
void SetIslanded (Body2D *body) noexcept
Sets the given body to the in an island state.
void SetIslanded (Contact2D *contact) noexcept
Sets the given contact to the in an island state.
void SetIslanded (Joint2D *joint) noexcept
Sets the given joint to the in an island state.
void UnsetIslanded (Body2D *body) noexcept
Unsets the given body's in island state.
void UnsetIslanded (Contact2D *contact) noexcept
Unsets the given contact's in island state.
void UnsetIslanded (Joint2D *joint) noexcept
Unsets the given joint's in island state.
Static Private Member Functions
static RegStepStats & Update (RegStepStats &lhs, const IslandSolverResults &rhs) noexcept
Updates the given regular step statistics.
static void UpdateBody (Body2D &body, const Position2D &pos, const Velocity2D &vel)
Updates the given body.
Private Attributes
DynamicTree2D m_tree
Dynamic tree.
ContactKeyQueue m_proxyKeys
Proxy keys.
ProxyQueue m_proxies
Proxies queue.
FixtureQueue m_fixturesForProxies
Fixtures for proxies queue.
BodyQueue m_bodiesForProxies
Bodies for proxies queue.
ContactFilter2D m_defaultFilter
Default contact filter. 8-bytes.
Bodies m_bodies
Body collection.
Joints m_joints
Joint collection.
Contacts m_contacts
Container of contacts.
LinearAcceleration2 m_gravity
Gravity setting. 8-bytes.
DestructionListener * m_destructionListener = nullptr
Destruction listener. 8-bytes.
ContactListener2D * m_contactListener = nullptr
Contact listener. 8-bytes.
ContactFilter2D * m_contactFilter = &m_defaultFilter
Contact filter. 8-bytes.
FlagsType m_flags = e_stepComplete
Flags.
Frequency m_inv_dt0 = 0
Inverse delta-t from previous step.
Positive< Length > m_minVertexRadius
Minimum vertex radius.
Positive< Length > m_maxVertexRadius
Maximum vertex radius.
Related Functions
(Note that these are not member functions.)
BodyCounter GetBodyCount (const World2D &world) noexcept
Gets the body count in the given world.
JointCounter GetJointCount (const World2D &world) noexcept
Gets the count of joints in the given world.
ContactCounter GetContactCount (const World2D &world) noexcept
Gets the count of contacts in the given world.
ContactCounter GetTouchingCount (const World2D &world) noexcept
Gets the touching count for the given world.
StepStats Step (World2D &world, Time delta, TimestepIters velocityIterations=8, TimestepIters positionIterations=3)
Steps the world ahead by a given time amount.
std::size_t GetFixtureCount (const World2D &world) noexcept
Gets the count of fixtures in the given world.
std::size_t GetShapeCount (const World2D &world) noexcept
Gets the count of unique shapes in the given world.
BodyCounter GetAwakeCount (const World2D &world) noexcept
Gets the count of awake bodies in the given world.
BodyCounter Awaken (World2D &world) noexcept
Awakens all of the bodies in the given world.
void SetAccelerations (World2D &world, std::function< Acceleration2D(const Body2D &b)> fn) noexcept
Sets the accelerations of all the world's bodies.
void SetAccelerations (World2D &world, Acceleration2D acceleration) noexcept
Sets the accelerations of all the world's bodies to the given value.
void ClearForces (World2D &world) noexcept
Clears forces.
Body2D * CreateRectangularEnclosingBody (World2D &world, Length2 dimensions, const ShapeDef &baseConf)
Creates a rectangular enclosure.
Body2D * CreateSquareEnclosingBody (World2D &world, Length size, const ShapeDef &baseConf)
Creates a square enclosure.
Body2D * FindClosestBody (const World2D &world, Length2 location) noexcept
Finds body in given world that's closest to the given location.
Detailed Description
Definition of an independent and simulatable "world".
The world class manages physics entities, dynamic simulation, and queries. In a physical sense, perhaps this is more like a universe in that entities in a world have no interaction with entities in other worlds. In any case, there's precedence, from a physics-engine standpoint, for this being called a world.
Note
World instances are composed of — i.e. contain and own — Body2D, Joint2D, and Contact2D instances.
This data structure is 352-bytes large (with 4-byte Real on at least one 64-bit platform).
See also
Body2D, Joint2D, Contact2D
Examples:
HelloWorld.cpp.
Member Typedef Documentation
BodyStack
using playrho::World2D::BodyStack = std::vector<Body2D*> private
Body stack.
Note
Using a std::stack<Body2D*, std::vector<Body2D*>> would be nice except it doesn't support the reserve method.
Joints
using playrho::World2D::Joints = std::vector<Joint2D*>
Joints container type.
Note
Cannot be container of Joint instances since joints are polymorphic types.
QueryFixtureCallback
using playrho::World2D::QueryFixtureCallback = std::function<bool(Fixture2D* fixture, ChildCounter child)>
Query AABB for fixtures callback function type.
Note
Returning true will continue the query. Returning false will terminate the query.
Member Enumeration Documentation
Flag
enum playrho::World2D::Flag : FlagsType private
Flag enumeration.
Enumerator
e_newFixture
New fixture.
e_locked
Locked.
e_substepping
Sub-stepping.
e_stepComplete
Step complete.
Used for sub-stepping.
See also
e_substepping.
RayCastOpcode
enum playrho::World2D::RayCastOpcode strong
World ray cast opcode enumeration.
Enumerator
Terminate
End the ray-cast search for fixtures.
Use this to stop searching for fixtures.
IgnoreFixture
Ignore the current fixture.
Use this to continue searching for fixtures along the ray.
ClipRay
Clip the ray end to the current point.
Use this shorten the ray to the current point and to continue searching for fixtures now along the newly shortened ray.
ResetRay
Reset the ray end back to the second point.
Use this to restore the ray to its full length and to continue searching for fixtures now along the restored full length ray.
Constructor & Destructor Documentation
World2D()
playrho::World2D::World2D (const WorldDef & def = GetDefaultWorldDef()) explicit
Constructs a world object.
Exceptions
InvalidArgument if the given max vertex radius is less than the min.
~World2D()
playrho::World2D::~World2D ()
Destructor.
All physics entities are destroyed and all dynamically allocated memory is released.
Member Function Documentation
Add() [1/2]
bool playrho::World2D::Add (Joint2D * j) private
Adds the given joint to this world.
Note
This also adds the joint to the bodies of the joint.
Referenced by CopyJoints(), and CreateJoint().
Add() [2/2]
bool playrho::World2D::Add (ContactKey key) private
Adds a contact for the proxies identified by the key if appropriate.
Adds a new contact object to represent a contact between proxy A and proxy B if all of the following are true:
The bodies of the fixtures of the proxies are not the one and the same.
No contact already exists for these two proxies.
The bodies of the proxies should collide (according to Body2D::ShouldCollide).
The contact filter says the fixtures of the proxies should collide.
There exists a contact-create function for the pair of shapes of the proxies.
Postcondition
The size of the m_contacts collection is one greater-than it was before this method is called if it returns true.
Parameters
key ID's of dynamic tree entries identifying the fixture proxies involved.
Returns
true if a new contact was indeed added (and created), else false.
See also
bool Body2D::ShouldCollide(const Body2D* other) const
AddToIsland()
void playrho::World2D::AddToIsland (Island2D & island, Body2D & seed, Bodies::size_type & remNumBodies, Contacts::size_type & remNumContacts, Joints::size_type & remNumJoints) private
Adds to the island based off of a given "seed" body.
Postcondition
Contacts are listed in the island in the order that bodies provide those contacts.
Joints are listed the island in the order that bodies provide those joints.
Referenced by SolveReg().
CreateBody()
Body2D * playrho::World2D::CreateBody (const BodyDef & def = GetDefaultBodyDef())
Creates a rigid body given a definition.
Note
No reference to the definition is retained.
Warning
This function is locked during callbacks.
Returns
Pointer to newly created body.
Exceptions
WrongState if this method is called while the world is locked.
LengthError if this operation would create more than MaxBodies.
See also
Physical Entity Classes
Examples:
HelloWorld.cpp.
Referenced by CopyBodies(), and playrho::CreateRectangularEnclosingBody().
CreateFixture()
Fixture2D * playrho::World2D::CreateFixture (Body2D & body, const Shape2D & shape, const FixtureDef & def = GetDefaultFixtureDef(), bool resetMassData = true)
Creates a fixture with the given parameters.
Exceptions
InvalidArgument if called for a body that doesn't belong to this world.
InvalidArgument if called without a shape.
InvalidArgument if called for a shape with a vertex radius less than the minimum vertex radius.
InvalidArgument if called for a shape with a vertex radius greater than the maximum vertex radius.
WrongState if this method is called while the world is locked.
Referenced by playrho::Body2D::CreateFixture().
CreateJoint()
Joint2D * playrho::World2D::CreateJoint (const JointDef & def)
Creates a joint to constrain bodies together.
No reference to the definition is retained. This may cause the connected bodies to cease colliding.
Warning
This function is locked during callbacks.
Returns
Pointer to newly created joint.
Exceptions
WrongState if this method is called while the world is locked.
LengthError if this operation would create more than MaxJoints.
InvalidArgument if the given definition is not allowed.
See also
Physical Entity Classes
CreateProxies()
void playrho::World2D::CreateProxies (Fixture2D & fixture, Length aabbExtension) private
Creates proxies for every child of the given fixture's shape.
Note
This sets the proxy count to the child count of the shape.
Referenced by CreateAndDestroyProxies().
Destroy() [1/3]
void playrho::World2D::Destroy (Body2D * body)
Destroys the given body.
Note
This function is locked during callbacks.
Warning
This automatically deletes all associated shapes and joints.
This function is locked during callbacks.
Behavior is undefined if given a null body.
Behavior is undefined if the passed body was not created by this world.
Exceptions
WrongState if this method is called while the world is locked.
See also
Physical Entity Classes
Referenced by CreateAndDestroyProxies(), DestroyFixture(), and SetType().
Destroy() [2/3]
void playrho::World2D::Destroy (Joint2D * joint)
Destroys a joint.
This may cause the connected bodies to begin colliding.
Warning
This function is locked during callbacks.
Behavior is undefined if the passed joint was not created by this world.
Parameters
joint Joint, created by this world, to destroy.
Exceptions
WrongState if this method is called while the world is locked.
See also
Physical Entity Classes
Destroy() [3/3]
void playrho::World2D::Destroy (Contact2D * contact, Body2D * from) private
Destroys the given contact and removes it from its container.
This updates the contacts container, returns the memory to the allocator, and decrements the contact manager's contact count.
Parameters
contact Contact to destroy.
from From body.
DestroyContacts()
World2D::DestroyContactsStats playrho::World2D::DestroyContacts (Contacts & contacts) private
Processes the narrow phase collision for the contacts collection.
This finds and destroys the contacts that need filtering and no longer should collide or that no longer have AABB-based overlapping fixtures. Those contacts that persist and have active bodies (either or both) get their Update methods called with the current contact listener as its argument. Essentially this really just purges contacts that are no longer relevant.
Referenced by Step().
DestroyFixture()
bool playrho::World2D::DestroyFixture (Fixture2D * fixture, bool resetMassData = true)
Destroys a fixture.
This removes the fixture from the broad-phase and destroys all contacts associated with this fixture. All fixtures attached to a body are implicitly destroyed when the body is destroyed.
Warning
This function is locked during callbacks.
Note
Make sure to explicitly call ResetMassData after fixtures have been destroyed.
Parameters
fixture the fixture to be removed.
resetMassData Whether or not to reset the mass data of the associated body.
See also
ResetMassData.
Exceptions
WrongState if this method is called while the world is locked.
Referenced by playrho::Body2D::DestroyFixture().
DestroyProxies()
void playrho::World2D::DestroyProxies (Fixture2D & fixture) private
Destroys the given fixture's proxies.
Note
This resets the proxy count to 0.
Referenced by Clear(), CreateAndDestroyProxies(), Destroy(), and DestroyFixture().
FindNewContacts()
ContactCounter playrho::World2D::FindNewContacts () private
Finds new contacts.
Finds and adds new valid contacts to the contacts container.
Note
The new contacts will all have overlapping AABBs.
Referenced by SolveReg(), SolveToi(), and Step().
GetBodies() [1/2]
SizedRange< World2D::Bodies::iterator > playrho::World2D::GetBodies () inline noexcept
Gets the world body range for this world.
Returns
Body range that can be iterated over using its begin and end methods or using ranged-based for-loops.
Referenced by playrho::Dump(), playrho::FindClosestBody(), operator=(), playrho::SetAccelerations(), and ShiftOrigin().
GetBodies() [2/2]
SizedRange< World2D::Bodies::const_iterator > playrho::World2D::GetBodies () const inline noexcept
Gets the world body range for this constant world.
Returns
Body range that can be iterated over using its begin and end methods or using ranged-based for-loops.
GetContacts()
SizedRange< World2D::Contacts::const_iterator > playrho::World2D::GetContacts () const inline noexcept
Gets the world contact range.
Warning
contacts are created and destroyed in the middle of a time step. Use ContactListener2D to avoid missing contacts.
Returns
World contacts sized-range.
Referenced by operator=().
GetJoints() [1/2]
SizedRange< World2D::Joints::const_iterator > playrho::World2D::GetJoints () const inline noexcept
Gets the world joint range.
Returns
World joints sized-range.
Referenced by playrho::Dump(), playrho::GetWorldIndex(), and operator=().
GetJoints() [2/2]
SizedRange< World2D::Joints::iterator > playrho::World2D::GetJoints () inline noexcept
Gets the world joint range.
Returns
World joints sized-range.
GetSoonestContact()
World2D::ContactToiData playrho::World2D::GetSoonestContact () const private noexcept
Gets the soonest contact.
This finds the contact with the lowest (soonest) time of impact.
Returns
Contact with the least time of impact and its time of impact, or null contact. A non-null contact will be enabled, not have sensors, be active, and impenetrable.
Referenced by SolveToi().
InternalDestroy()
void playrho::World2D::InternalDestroy (Joint2D * joint) private
Internal destroy.
Warning
Behavior is undefined if passed a null pointer for the joint.
Referenced by Destroy(), and DestroyContacts().
InternalTouchProxies()
void playrho::World2D::InternalTouchProxies (Fixture2D & fixture) private noexcept
Touches each proxy of the given fixture.
Note
This sets things up so that pairs may be created for potentially new contacts.
Referenced by SetType().
IsStepComplete()
bool playrho::World2D::IsStepComplete () const inline private noexcept
Whether or not "step" is complete.
The "step" is completed when there are no more TOI events for the current time step.
See also
SetStepComplete.
Referenced by SolveToi(), and Step().
ProcessContactsForTOI()
World2D::ProcessContactsOutput playrho::World2D::ProcessContactsForTOI (Island2D & island, Body2D & body, Real toi, const StepConf & conf) private
Processes the contacts of a given body for TOI handling.
This does the following:
Advances the appropriate associated other bodies to the given TOI (advancing their sweeps and synchronizing their transforms to their new sweeps).
Updates the contact manifolds and touching statuses and notifies listener (if one given) of the appropriate contacts of the body.
Adds those contacts that are still enabled and still touching to the given island (or resets the other bodies advancement).
Adds to the island, those other bodies that haven't already been added of the contacts that got added.
Note
Precondition: there should be no lower TOI for which contacts have not already been processed.
Parameters
[in,out] island Island. On return this may contain additional contacts or bodies.
[in,out] body A dynamic/accelerable body.
[in] toi Time of impact (TOI). Value between 0 and 1.
[in] conf Step configuration data.
Referenced by SolveToi().
QueryAABB()
void playrho::World2D::QueryAABB (const AABB2D & aabb, QueryFixtureCallback callback) const
Queries the world for all fixtures that potentially overlap the provided AABB.
Parameters
aabb the query box.
callback User implemented callback function.
RayCast()
void playrho::World2D::RayCast (Length2 point1, Length2 point2, RayCastCallback callback) const
Ray-cast the world for all fixtures in the path of the ray.
Note
The callback controls whether you get the closest point, any point, or n-points.
The ray-cast ignores shapes that contain the starting point.
Parameters
point1 Ray starting point.
point2 Ray ending point.
callback A user implemented callback function.
SetSubStepping()
void playrho::World2D::SetSubStepping (bool flag) inline noexcept
Enables/disables single stepped continuous physics.
Note
This is for testing.
SetType()
void playrho::World2D::SetType (Body2D & body, BodyType type)
Sets the type of the given body.
Note
This may alter the body's mass and velocity.
Exceptions
WrongState if this method is called while the world is locked.
Referenced by playrho::Body2D::SetType().
ShiftOrigin()
void playrho::World2D::ShiftOrigin (Length2 newOrigin)
Shifts the world origin.
Note
Useful for large worlds.
The body shift formula is: position -= newOrigin.
Parameters
newOrigin the new origin with respect to the old origin
Exceptions
WrongState if this method is called while the world is locked.
SolveReg()
RegStepStats playrho::World2D::SolveReg (const StepConf & conf) private
Solves the step.
Finds islands, integrates and solves constraints, solves position constraints.
Note
This may miss collisions involving fast moving bodies and allow them to tunnel through each other.
< Remaining number of bodies.
< Remaining number of contacts.
< Remaining number of joints.
Referenced by Step().
SolveRegIslandViaGS()
World2D::IslandSolverResults playrho::World2D::SolveRegIslandViaGS (const StepConf & conf, Island2D island) private
Solves the given island (regularly).
This:
Updates every island-body's sweep.pos0 to its sweep.pos1.
Updates every island-body's sweep.pos1 to the new normalized "solved" position for it.
Updates every island-body's velocity to the new accelerated, dampened, and "solved" velocity for it.
Synchronizes every island-body's transform (by updating it to transform one of the body's sweep).
Reports to the listener (if non-null).
Parameters
conf Time step configuration information.
island Island of bodies, contacts, and joints to solve for. Must contain at least one body, contact, or joint.
Warning
Behavior is undefined if the given island doesn't have at least one body, contact, or joint.
Returns
Island solver results.
< Time step.
Referenced by SolveReg().
SolveToi() [1/2]
ToiStepStats playrho::World2D::SolveToi (const StepConf & conf) private
Solves the step using successive time of impact (TOI) events.
Used for continuous physics.
Note
This is intended to detect and prevent the tunneling that the faster Solve method may miss.
Parameters
conf Time step configuration to use.
Referenced by Step().
SolveToi() [2/2]
World2D::IslandSolverResults playrho::World2D::SolveToi (const StepConf & conf, Contact2D & contact) private
Solves collisions for the given time of impact.
Parameters
conf Time step configuration to solve for.
contact Contact.
Note
Precondition 1: there is no contact having a lower TOI in this time step that has not already been solved for.
Precondition 2: there is not a lower TOI in the time step for which collisions have not already been processed.
SolveToiViaGS()
World2D::IslandSolverResults playrho::World2D::SolveToiViaGS (const StepConf & conf, Island2D & island) private
Solves the time of impact for bodies 0 and 1 of the given island.
This:
Updates position 0 of the sweeps of bodies 0 and 1.
Updates position 1 of the sweeps, the transforms, and the velocities of the other bodies in this island.
Precondition
island.m_bodies contains at least two bodies, the first two of which are bodies 0 and 1.
island.m_bodies contains appropriate other bodies of the contacts of the two bodies.
island.m_contacts contains the contact that specified the two identified bodies.
island.m_contacts contains appropriate other contacts of the two bodies.
Parameters
conf Time step configuration information.
island Island to do time of impact solving for.
Returns
Island solver results.
Referenced by SolveToi().
Step()
StepStats playrho::World2D::Step (const StepConf & conf)
Steps the world simulation according to the given configuration.
Performs position and velocity updating, sleeping of non-moving bodies, updating of the contacts, and notifying the contact listener of begin-contact, end-contact, pre-solve, and post-solve events.
Warning
Behavior is undefined if given a negative step time delta.
Varying the step time delta may lead to non-physical behaviors.
Note
Calling this with a zero step time delta results only in fixtures and bodies registered for proxy handling being processed. No physics is performed.
If the given velocity and position iterations are zero, this method doesn't do velocity or position resolutions respectively of the contacting bodies.
While body velocities are updated accordingly (per the sum of forces acting on them), body positions (barring any collisions) are updated as if they had moved the entire time step at those resulting velocities. In other words, a body initially at position 0 (p0) going velocity 0 (v0) fast with a sum acceleration of a, after time t and barring any collisions, will have a new velocity (v1) of v0 + (a * t) and a new position (p1) of p0 + v1 * t.
Postcondition
Static bodies are unmoved.
Kinetic bodies are moved based on their previous velocities.
Dynamic bodies are moved based on their previous velocities, gravity, applied forces, applied impulses, masses, damping, and the restitution and friction values of their fixtures when they experience collisions.
Parameters
conf Configuration for the simulation step.
Returns
Statistics for the step.
Exceptions
WrongState if this method is called while the world is locked.
Referenced by playrho::Step().
Synchronize() [1/2]
ContactCounter playrho::World2D::Synchronize (Body2D & body, Transformation2D xfm1, Transformation2D xfm2, Real multiplier, Length extension) private
Synchronizes the given body.
This updates the broad phase dynamic tree data for all of the given body's fixtures.
Referenced by SolveReg(), SolveToi(), and SynchronizeProxies().
Synchronize() [2/2]
ContactCounter playrho::World2D::Synchronize (Fixture2D & fixture, Transformation2D xfm1, Transformation2D xfm2, Length2 displacement, Length extension) private
Synchronizes the given fixture.
This updates the broad phase dynamic tree data for all of the given fixture shape's children.
TouchProxies()
bool playrho::World2D::TouchProxies (Fixture2D & fixture) noexcept
Touches each proxy of the given fixture.
Note
Fixture must belong to a body that belongs to this world or this method will return false.
This sets things up so that pairs may be created for potentially new contacts.
UpdateBody()
void playrho::World2D::UpdateBody (Body2D & body, const Position2D & pos, const Velocity2D & vel) static private
Updates the given body.
Updates the given body's velocity, sweep position 1, and its transformation.
Parameters
body Body to update.
pos New position to set the given body to.
vel New velocity to set the given body to.
Referenced by SolveRegIslandViaGS(), and SolveToiViaGS().
Friends And Related Function Documentation
Awaken()
BodyCounter Awaken (World2D & world) related
Awakens all of the bodies in the given world.
Calls all of the world's bodies' SetAwake method.
Returns
Sum total of calls to bodies' SetAwake method that returned true.
See also
Body2D::SetAwake.
ClearForces()
void ClearForces (World2D & world) related
Clears forces.
Manually clear the force buffer on all bodies.
CreateRectangularEnclosingBody()
Body2D * CreateRectangularEnclosingBody (World2D & world, Length2 dimensions, const ShapeDef & baseConf) related
Creates a rectangular enclosure.
Referenced by playrho::CreateSquareEnclosingBody().
CreateSquareEnclosingBody()
Body2D * CreateSquareEnclosingBody (World2D & world, Length size, const ShapeDef & baseConf) related
Creates a square enclosure.
FindClosestBody()
Body2D * FindClosestBody (const World2D & world, Length2 location) related
Finds body in given world that's closest to the given location.
GetAwakeCount()
BodyCounter GetAwakeCount (const World2D & world) related
Gets the count of awake bodies in the given world.
GetBodyCount()
BodyCounter GetBodyCount (const World2D & world) related
Gets the body count in the given world.
Returns
0 or higher.
GetContactCount()
ContactCounter GetContactCount (const World2D & world) related
Gets the count of contacts in the given world.
Note
Not all contacts are for shapes that are actually touching. Some contacts are for shapes which merely have overlapping AABBs.
Returns
0 or higher.
GetFixtureCount()
std::size_t GetFixtureCount (const World2D & world) related
Gets the count of fixtures in the given world.
GetJointCount()
JointCounter GetJointCount (const World2D & world) related
Gets the count of joints in the given world.
Returns
0 or higher.
GetShapeCount()
std::size_t GetShapeCount (const World2D & world) related
Gets the count of unique shapes in the given world.
GetTouchingCount()
ContactCounter GetTouchingCount (const World2D & world) related
Gets the touching count for the given world.
SetAccelerations() [1/2]
void SetAccelerations (World2D & world, std::function< Acceleration2D(const Body2D &b)> fn) related
Sets the accelerations of all the world's bodies.
Referenced by playrho::ClearForces().
SetAccelerations() [2/2]
void SetAccelerations (World2D & world, Acceleration2D acceleration) related
Sets the accelerations of all the world's bodies to the given value.
Step()
StepStats Step (World2D & world, Time delta, TimestepIters velocityIterations = 8, TimestepIters positionIterations = 3) related
Steps the world ahead by a given time amount.
Performs position and velocity updating, sleeping of non-moving bodies, updating of the contacts, and notifying the contact listener of begin-contact, end-contact, pre-solve, and post-solve events. If the given velocity and position iterations are more than zero, this method also respectively performs velocity and position resolution of the contacting bodies.
Note
While body velocities are updated accordingly (per the sum of forces acting on them), body positions (barring any collisions) are updated as if they had moved the entire time step at those resulting velocities. In other words, a body initially at p0 going v0 fast with a sum acceleration of a, after time t and barring any collisions, will have a new velocity (v1) of v0 + (a * t) and a new position (p1) of p0 + v1 * t.
Warning
Varying the time step may lead to non-physical behaviors.
Postcondition
Static bodies are unmoved.
Kinetic bodies are moved based on their previous velocities.
Dynamic bodies are moved based on their previous velocities, gravity, applied forces, applied impulses, masses, damping, and the restitution and friction values of their fixtures when they experience collisions.
Parameters
world World to step.
delta Time to simulate as a delta from the current state. This should not vary.
velocityIterations Number of iterations for the velocity constraint solver.
positionIterations Number of iterations for the position constraint solver. The position constraint solver resolves the positions of bodies that overlap.
Member Data Documentation
m_contacts
Contacts playrho::World2D::m_contacts private
Container of contacts.
Note
In the add pair stress-test, 401 bodies can have some 31000 contacts during a given time step.
Referenced by Add(), Clear(), CopyContacts(), Destroy(), GetContacts(), GetSoonestContact(), ResetContactsForSolveTOI(), SolveReg(), SolveToi(), Step(), and UpdateContactTOIs().
m_inv_dt0
Frequency playrho::World2D::m_inv_dt0 = 0 private
Inverse delta-t from previous step.
Used to compute time step ratio to support a variable time step.
Note
4-bytes large.
See also
Step.
Referenced by GetInvDeltaTime(), operator=(), and Step().
m_maxVertexRadius
Positive<Length> playrho::World2D::m_maxVertexRadius private
Maximum vertex radius.
This is the maximum shape vertex radius that any bodies' of this world should create fixtures for. Requests to create fixtures for shapes with vertex radiuses bigger than this must be rejected. As an upper bound, this value prevents shapes from getting associated with this world that would otherwise not be able to be simulated due to numerical issues. It can also be set below this upper bound to constrain the differences between shape vertex radiuses to possibly more limited visual ranges.
Referenced by GetMaxVertexRadius(), operator=(), and Step().
The documentation for this class was generated from the following files:
World.hpp
World.cpp