PlayRho: playrho::ContactListener Class Reference
playrho::ContactListener Class Reference abstract
A pure-virtual interface for "listeners" for contacts.
#include <WorldCallbacks.hpp>
Public Types
using iteration_type = unsigned
Iteration type.
Public Member Functions
virtual void BeginContact (Contact2D &contact)=0
Called when two fixtures begin to touch.
virtual void EndContact (Contact2D &contact)=0
End contact callback.
virtual void PreSolve (Contact2D &contact, const Manifold2D &oldManifold)=0
Pre-solve callback.
virtual void PostSolve (Contact2D &contact, const ContactImpulsesList &impulses, iteration_type solved)=0
Post-solve callback.
Detailed Description
A pure-virtual interface for "listeners" for contacts.
Implement this class to get contact information. You can use these results for things like sounds and game logic. You can also get contact results by traversing the contact lists after the time step. However, you might miss some contacts because continuous physics leads to sub-stepping. Additionally you may receive multiple callbacks for the same contact in a single time step. You should strive to make your callbacks efficient because there may be many callbacks per time step.
Warning
You cannot create/destroy PlayRho entities inside these callbacks.
Member Function Documentation
EndContact()
virtual void playrho::ContactListener::EndContact (Contact2D & contact) pure virtual
End contact callback.
Called when the contact's "touching" property becomes false, or just before the contact is destroyed.
Note
This contact persists until the broad phase determines there's no overlap anymore between the two fixtures.
If the contact's "touching" property becomes true again, BeginContact will be called again for this contact.
Parameters
contact Contact that's about to be destroyed or whose "touching" property has become false.
See also
Contact2D::IsTouching().
Referenced by playrho::World2D::InternalDestroy(), and playrho::Contact2D::Update().
PostSolve()
virtual void playrho::ContactListener::PostSolve (Contact2D & contact, const ContactImpulsesList & impulses, iteration_type solved) pure virtual
Post-solve callback.
This lets you inspect a contact after the solver is finished. This is useful for inspecting impulses.
Note
The contact manifold does not include time of impact impulses, which can be arbitrarily large if the sub-step is small. Hence the impulse is provided explicitly in a separate data structure.
This is only called for contacts that are touching, solid, and awake.
PreSolve()
virtual void playrho::ContactListener::PreSolve (Contact2D & contact, const Manifold2D & oldManifold) pure virtual
Pre-solve callback.
This is called after a contact is updated. This allows you to inspect a contact before it goes to the solver. If you are careful, you can modify the contact manifold (e.g. disable contact). A copy of the old manifold is provided so that you can detect changes.
Note
This is called only for awake bodies.
This is called even when the number of contact points is zero.
This is not called for sensors.
If you set the number of contact points to zero, you will not get an EndContact callback. However, you may get a BeginContact callback the next step.
Referenced by playrho::Contact2D::Update().
The documentation for this class was generated from the following file:
WorldCallbacks.hpp