PlayRho: playrho::d2::Shape Class Reference
playrho::d2::Shape Class Reference
Shape Classes
Shape.
#include <Shape.hpp>
Classes
struct Concept
Internal configuration concept.
struct Model
Internal model configuration concept.
Public Member Functions
Shape () noexcept=default
Default constructor.
template<typename T >
Shape (T arg)
Initializing constructor.
Shape (const Shape &other)=default
Copy constructor.
Shape (Shape &&other)=default
Move constructor.
Shape & operator= (const Shape &other)=default
Copy assignment operator.
Shape & operator= (Shape &&other)=default
Move assignment operator.
template<typename T , typename Tp = std::decay_t<T>, typename = std::enable_if_t< !std::is_same<Tp, Shape>::value && std::is_copy_constructible<Tp>::value >>
Shape & operator= (T &&other)
Move assignment operator.
void swap (Shape &other) noexcept
Swap support.
Private Attributes
std::shared_ptr< const Concept > m_self
Self shared pointer.
Friends
ChildCounter GetChildCount (const Shape &shape) noexcept
Gets the number of child primitives of the shape.
DistanceProxy GetChild (const Shape &shape, ChildCounter index)
Gets the "child" for the given index.
MassData GetMassData (const Shape &shape) noexcept
Gets the mass properties of this shape using its dimensions and density.
NonNegative< Length > GetVertexRadius (const Shape &shape, ChildCounter idx)
Gets the vertex radius of the indexed child of the given shape.
Real GetFriction (const Shape &shape) noexcept
Gets the coefficient of friction.
Real GetRestitution (const Shape &shape) noexcept
Gets the coefficient of restitution value of the given shape.
NonNegative< AreaDensity > GetDensity (const Shape &shape) noexcept
Gets the density of the given shape.
void Transform (Shape &shape, const Mat22 &m)
Transforms all of the given shape's vertices by the given transformation matrix.
const void * GetData (const Shape &shape) noexcept
Gets a pointer to the underlying data.
TypeID GetType (const Shape &shape) noexcept
Gets the type info of the use of the given shape.
template<typename T >
std::add_pointer_t< std::add_const_t< T > > TypeCast (const Shape *value) noexcept
Converts the given shape into its current configuration value.
bool operator== (const Shape &lhs, const Shape &rhs) noexcept
Equality operator for shape to shape comparisons.
bool operator!= (const Shape &lhs, const Shape &rhs) noexcept
Inequality operator for shape to shape comparisons.
Related Functions
(Note that these are not member functions.)
AABB ComputeAABB (const Shape &shape, const Transformation &xf) noexcept
Computes the AABB for the given shape with the given transformation.
RayCastOutput RayCast (const Shape &shape, ChildCounter childIndex, const RayCastInput &input, const Transformation &transform) noexcept
Cast a ray against the child of the given shape.
bool TestPoint (const Shape &shape, Length2 point) noexcept
Test a point for containment in the given shape.
template<typename T >
T TypeCast (const Shape &value)
Casts the specified instance into the template specified type.
Detailed Description
Shape.
A shape is used for collision detection. You can create a shape from any supporting type. Shapes are conceptually made up of zero or more convex child shapes where each child shape is made up of zero or more vertices and an associated radius called its "vertex radius".
Note
This class's design provides a "polymorphic value type" offering polymorphism without public inheritance. This is based on a technique that's described by Sean Parent in his January 2017 Norwegian Developers Conference London talk "Better Code: Runtime Polymorphism". With this implementation, different shapes types can be had by constructing instances of this class with the different types that provide the required support. Different shapes of a given type meanwhile are had by providing different values for the type.
This data structure is 32-bytes large (on at least one 64-bit platform).
See also
FixtureConf
https://youtu.be/QGcVXgEVMJg
https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Polymorphic_Value_Types
Examples
HelloWorld.cpp, World.cpp, WorldBody.cpp, WorldContact.cpp, and WorldFixture.cpp.
Constructor & Destructor Documentation
Shape()
template<typename T > playrho::d2::Shape::Shape (T arg) inline
Initializing constructor.
Parameters
arg Configuration value to construct a shape instance for.
Note
Only usable with types of values that have all of the support functions required by this class. The compiler emits errors if the given type doesn't.
See also
GetChildCount
GetChild
GetMassData
GetVertexRadius
GetDensity
GetFriction
GetRestitution
Exceptions
std::bad_alloc if there's a failure allocating storage.
Friends And Related Function Documentation
GetChild
DistanceProxy GetChild (const Shape & shape, ChildCounter index) friend
Gets the "child" for the given index.
Parameters
shape Shape to get "child" shape of.
index Index to a child element of the shape. Value must be less than the number of child primitives of the shape.
Note
The shape must remain in scope while the proxy is in use.
Exceptions
InvalidArgument if the given index is out of range.
See also
GetChildCount
Referenced by playrho::d2::Shape::Model< T >::GetChild_().
GetChildCount
ChildCounter GetChildCount (const Shape & shape) friend
Gets the number of child primitives of the shape.
Returns
Non-negative count.
Referenced by playrho::d2::Shape::Model< T >::GetChildCount_().
GetData
const void* GetData (const Shape & shape) friend
Gets a pointer to the underlying data.
Note
Provided for introspective purposes like visitation.
GetDensity
NonNegative<AreaDensity> GetDensity (const Shape & shape) friend
Gets the density of the given shape.
Returns
Non-negative density (in mass per area).
Referenced by playrho::d2::Shape::Model< T >::GetDensity_().
GetFriction
Real GetFriction (const Shape & shape) friend
Gets the coefficient of friction.
Returns
Value of 0 or higher.
Referenced by playrho::d2::Shape::Model< T >::GetFriction_().
GetMassData
MassData GetMassData (const Shape & shape) friend
Gets the mass properties of this shape using its dimensions and density.
Returns
Mass data for this shape.
Referenced by playrho::d2::Shape::Model< T >::GetMassData_().
GetType
TypeID GetType (const Shape & shape) friend
Gets the type info of the use of the given shape.
Note
This is not the same as calling GetTypeID<Shape>().
Returns
Type info of the underlying value's type.
GetVertexRadius
NonNegative<Length> GetVertexRadius (const Shape & shape, ChildCounter idx) friend
Gets the vertex radius of the indexed child of the given shape.
This gets the radius from the vertex that the shape's "skin" should extend outward by. While any edges - line segments between multiple vertices - are straight, corners between them (the vertices) are rounded and treated as rounded. Shapes with larger vertex radiuses compared to edge lengths therefore will be more prone to rolling or having other shapes more prone to roll off of them. Here's an image of a shape configured via a PolygonShapeConf with it's skin drawn:
Parameters
shape Shape to get child's vertex radius for.
idx Child index to get vertex radius for.
Note
This must be a non-negative value.
See also
UseVertexRadius
Exceptions
InvalidArgument if the child index is not less than the child count.
Referenced by playrho::d2::Shape::Model< T >::GetVertexRadius_().
Transform
void Transform (Shape & shape, const Mat22 & m) friend
Transforms all of the given shape's vertices by the given transformation matrix.
See also
https://en.wikipedia.org/wiki/Transformation_matrix
Note
This may throw std::bad_alloc or any exception that's thrown by the constructor for the model's underlying data type.
Exceptions
std::bad_alloc if there's a failure allocating storage.
Referenced by playrho::d2::Shape::Model< T >::Transform_().
TypeCast() [1/2]
template<typename T > T TypeCast (const Shape & value) related
Casts the specified instance into the template specified type.
Exceptions
std::bad_cast If the template specified type is not the type of data underlying the given instance.
See also
GetType(const Shape&)
TypeCast [2/2]
template<typename T > std::add_pointer_t<std::add_const_t<T> > TypeCast (const Shape * value) friend
Converts the given shape into its current configuration value.
Note
The design for this was based off the design of the C++17 std::any class and its associated std::any_cast function. The code for this is based off of the std::any code from the LLVM Project.
See also
https://llvm.org/
GetType(const Shape&)
The documentation for this class was generated from the following files:
Shape.hpp
AABB.hpp
RayCastOutput.hpp