PlayRho: playrho::d2::Joint Class Reference
playrho::d2::Joint Class Reference
Library Defined Constraints » Joint Classes | Physical Entities
Joint class.
#include <Joint.hpp>
Classes
struct Concept
Internal configuration concept.
struct Model
Internal model configuration concept.
Public Types
using BodyConstraintsMap = std::vector< BodyConstraint >
Body constraints map type alias.
Public Member Functions
Joint () noexcept=default
Default constructor.
template<typename T >
Joint (T arg)
Initializing constructor.
Joint (const Joint &other)
Copy constructor.
Joint (Joint &&other) noexcept
Move constructor.
Joint & operator= (const Joint &other)
Copy assignment.
Joint & operator= (Joint &&other) noexcept
Move assignment.
template<typename T , typename Tp = std::decay_t<T>, typename = std::enable_if_t< !std::is_same<Tp, Joint>::value && std::is_copy_constructible<Tp>::value >>
Joint & operator= (T &&other) noexcept
Move assignment support for any valid underlying configuration.
void swap (Joint &other) noexcept
Swap function.
Private Attributes
std::unique_ptr< Concept > m_self
Self pointer.
Friends
JointType GetType (const Joint &object) noexcept
Gets the identifier of the type of data this can be casted to.
template<typename T >
std::add_pointer_t< std::add_const_t< T > > TypeCast (const Joint *value) noexcept
Converts the given joint into its current configuration value.
template<typename T >
std::add_pointer_t< T > TypeCast (Joint *value) noexcept
Converts the given joint into its current configuration value.
BodyID GetBodyA (const Joint &object) noexcept
Gets the first body attached to this joint.
BodyID GetBodyB (const Joint &object) noexcept
Gets the second body attached to this joint.
bool GetCollideConnected (const Joint &object) noexcept
Gets collide connected.
bool ShiftOrigin (Joint &object, Length2 value) noexcept
Shifts the origin for any points stored in world coordinates.
void InitVelocity (Joint &object, std::vector< BodyConstraint > &bodies, const playrho::StepConf &step, const ConstraintSolverConf &conf)
Initializes velocity constraint data based on the given solver data.
bool SolveVelocity (Joint &object, std::vector< BodyConstraint > &bodies, const playrho::StepConf &step)
Solves velocity constraint.
bool SolvePosition (const Joint &object, std::vector< BodyConstraint > &bodies, const ConstraintSolverConf &conf)
Solves the position constraint.
Related Functions
(Note that these are not member functions.)
DistanceJointConf GetDistanceJointConf (const Joint &joint) noexcept
Gets the definition data for the given joint.
FrictionJointConf GetFrictionJointConf (const Joint &joint) noexcept
Gets the definition data for the given joint.
GearJointConf GetGearJointConf (const Joint &joint) noexcept
Gets the definition data for the given joint.
template<typename T >
T TypeCast (const Joint &value)
Converts the given joint into its current configuration value.
Length2 GetLocalAnchorA (const Joint &object)
Get the anchor point on body-A in local coordinates.
Length2 GetLocalAnchorB (const Joint &object)
Get the anchor point on body-B in local coordinates.
Momentum2 GetLinearReaction (const Joint &object)
Get the linear reaction on body-B at the joint anchor.
AngularMomentum GetAngularReaction (const Joint &object)
Get the angular reaction on body-B.
Angle GetReferenceAngle (const Joint &object)
Gets the reference angle of the joint if it has one.
UnitVec GetLocalXAxisA (const Joint &object)
Gets the given joint's local X axis A if its type supports that.
UnitVec GetLocalYAxisA (const Joint &object)
Gets the given joint's local Y axis A if its type supports that.
AngularVelocity GetMotorSpeed (const Joint &object)
Gets the given joint's motor speed if its type supports that.
void SetMotorSpeed (Joint &object, AngularVelocity value)
Sets the given joint's motor speed if its type supports that.
Force GetMaxForce (const Joint &object)
Gets the given joint's max force if its type supports that.
Torque GetMaxTorque (const Joint &object)
Gets the given joint's max torque if its type supports that.
Force GetMaxMotorForce (const Joint &object)
Gets the given joint's max motor force if its type supports that.
void SetMaxMotorForce (Joint &object, Force value)
Sets the given joint's max motor force if its type supports that.
Torque GetMaxMotorTorque (const Joint &object)
Gets the given joint's max motor torque if its type supports that.
void SetMaxMotorTorque (Joint &object, Torque value)
Sets the given joint's max motor torque if its type supports that.
RotInertia GetAngularMass (const Joint &object)
Gets the given joint's angular mass.
Real GetRatio (const Joint &object)
Gets the given joint's ratio property if it has one.
Real GetDampingRatio (const Joint &object)
Gets the given joint's damping ratio property if it has one.
Frequency GetFrequency (const Joint &object)
Gets the frequency of the joint if it has this property.
void SetFrequency (Joint &object, Frequency value)
Sets the frequency of the joint if it has this property.
AngularMomentum GetAngularMotorImpulse (const Joint &object)
Gets the angular motor impulse of the joint if it has this property.
Length2 GetTarget (const Joint &object)
Gets the given joint's target property if it has one.
void SetTarget (Joint &object, Length2 value)
Sets the given joint's target property if it has one.
Length GetLinearLowerLimit (const Joint &object)
Gets the lower linear joint limit.
Length GetLinearUpperLimit (const Joint &object)
Gets the upper linear joint limit.
void SetLinearLimits (Joint &object, Length lower, Length upper)
Sets the joint limits.
Angle GetAngularLowerLimit (const Joint &object)
Gets the lower joint limit.
Angle GetAngularUpperLimit (const Joint &object)
Gets the upper joint limit.
void SetAngularLimits (Joint &object, Angle lower, Angle upper)
Sets the joint limits.
bool IsLimitEnabled (const Joint &object)
Gets the specified joint's limit property if it supports one.
void EnableLimit (Joint &object, bool value)
Enables the specified joint's limit property if it supports one.
bool IsMotorEnabled (const Joint &object)
Gets the specified joint's motor property value if it supports one.
void EnableMotor (Joint &object, bool value)
Enables the specified joint's motor property if it supports one.
Length2 GetLinearOffset (const Joint &object)
Gets the linear offset property of the specified joint if its type has one.
void SetLinearOffset (Joint &object, Length2 value)
Sets the linear offset property of the specified joint if its type has one.
Angle GetAngularOffset (const Joint &object)
Gets the angular offset property of the specified joint if its type has one.
void SetAngularOffset (Joint &object, Angle value)
Sets the angular offset property of the specified joint if its type has one.
LimitState GetLimitState (const Joint &object)
Length2 GetGroundAnchorA (const Joint &object)
Length2 GetGroundAnchorB (const Joint &object)
Momentum GetLinearMotorImpulse (const Joint &object)
Length GetLength (const Joint &object)
Gets the length property of the specified joint if its type has one.
Torque GetMotorTorque (const Joint &joint, Frequency inv_dt)
Gets the current motor torque for the given joint given the inverse time step.
MotorJointConf GetMotorJointConf (const Joint &joint) noexcept
Gets the definition data for the given joint.
PrismaticJointConf GetPrismaticJointConf (const Joint &joint)
Gets the definition data for the given joint.
PulleyJointConf GetPulleyJointConf (const Joint &joint)
Gets the definition data for the given joint.
RevoluteJointConf GetRevoluteJointConf (const Joint &joint)
Gets the definition data for the given joint.
RopeJointConf GetRopeJointConf (const Joint &joint) noexcept
Gets the definition data for the given joint.
TargetJointConf GetTargetJointConf (const Joint &joint)
Gets the definition data for the given joint.
WeldJointConf GetWeldJointConf (const Joint &joint)
Gets the definition data for the given joint.
WheelJointConf GetWheelJointConf (const Joint &joint)
Gets the definition data for the given joint.
Detailed Description
Joint class.
This is a concrete manifestation of the joint concept. Joints are constraints that are used to constrain one or more bodies in various fashions. Some joints also feature limits and motors.
Note
This class's design provides a "polymorphic value type" offering polymorphism without public inheritance. This is based on a technique that's described by Sean Parent in his January 2017 Norwegian Developers Conference London talk "Better Code: Runtime Polymorphism".
See also
https://youtu.be/QGcVXgEVMJg
https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Polymorphic_Value_Types
Examples
World.cpp.
Friends And Related Function Documentation
EnableLimit()
void EnableLimit (Joint & object, bool value) related
Enables the specified joint's limit property if it supports one.
Exceptions
std::invalid_argument If not supported for the given joint's type.
EnableMotor()
void EnableMotor (Joint & object, bool value) related
Enables the specified joint's motor property if it supports one.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetAngularLowerLimit()
Angle GetAngularLowerLimit (const Joint & object) related
Gets the lower joint limit.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetAngularMass()
RotInertia GetAngularMass (const Joint & object) related
Gets the given joint's angular mass.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetAngularMotorImpulse()
AngularMomentum GetAngularMotorImpulse (const Joint & object) related
Gets the angular motor impulse of the joint if it has this property.
Exceptions
std::invalid_argument If not supported for the given joint's type.
Referenced by playrho::d2::GetMotorTorque().
GetAngularOffset()
Angle GetAngularOffset (const Joint & object) related
Gets the angular offset property of the specified joint if its type has one.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetAngularUpperLimit()
Angle GetAngularUpperLimit (const Joint & object) related
Gets the upper joint limit.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetCollideConnected
bool GetCollideConnected (const Joint & object) friend
Gets collide connected.
Note
Modifying the collide connect flag won't work correctly because the flag is only checked when fixture AABBs begin to overlap.
Referenced by playrho::d2::Joint::Model< T >::GetCollideConnected_().
GetDampingRatio()
Real GetDampingRatio (const Joint & object) related
Gets the given joint's damping ratio property if it has one.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetFrequency()
Frequency GetFrequency (const Joint & object) related
Gets the frequency of the joint if it has this property.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetGroundAnchorA()
Length2 GetGroundAnchorA (const Joint & object) related
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetGroundAnchorB()
Length2 GetGroundAnchorB (const Joint & object) related
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetLength()
Length GetLength (const Joint & object) related
Gets the length property of the specified joint if its type has one.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetLimitState()
LimitState GetLimitState (const Joint & object) related
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetLinearLowerLimit()
Length GetLinearLowerLimit (const Joint & object) related
Gets the lower linear joint limit.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetLinearMotorImpulse()
Momentum GetLinearMotorImpulse (const Joint & object) related
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetLinearOffset()
Length2 GetLinearOffset (const Joint & object) related
Gets the linear offset property of the specified joint if its type has one.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetLinearUpperLimit()
Length GetLinearUpperLimit (const Joint & object) related
Gets the upper linear joint limit.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetLocalXAxisA()
UnitVec GetLocalXAxisA (const Joint & object) related
Gets the given joint's local X axis A if its type supports that.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetLocalYAxisA()
UnitVec GetLocalYAxisA (const Joint & object) related
Gets the given joint's local Y axis A if its type supports that.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetMaxForce()
Force GetMaxForce (const Joint & object) related
Gets the given joint's max force if its type supports that.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetMaxMotorForce()
Force GetMaxMotorForce (const Joint & object) related
Gets the given joint's max motor force if its type supports that.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetMaxMotorTorque()
Torque GetMaxMotorTorque (const Joint & object) related
Gets the given joint's max motor torque if its type supports that.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetMaxTorque()
Torque GetMaxTorque (const Joint & object) related
Gets the given joint's max torque if its type supports that.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetMotorSpeed()
AngularVelocity GetMotorSpeed (const Joint & object) related
Gets the given joint's motor speed if its type supports that.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetMotorTorque()
Torque GetMotorTorque (const Joint & joint, Frequency inv_dt) related
Gets the current motor torque for the given joint given the inverse time step.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetRatio()
Real GetRatio (const Joint & object) related
Gets the given joint's ratio property if it has one.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetReferenceAngle()
Angle GetReferenceAngle (const Joint & object) related
Gets the reference angle of the joint if it has one.
Exceptions
std::invalid_argument If not supported for the given joint's type.
GetTarget()
Length2 GetTarget (const Joint & object) related
Gets the given joint's target property if it has one.
Exceptions
std::invalid_argument If not supported for the given joint's type.
Examples
World.cpp.
InitVelocity
void InitVelocity (Joint & object, std::vector< BodyConstraint > & bodies, const playrho::StepConf & step, const ConstraintSolverConf & conf) friend
Initializes velocity constraint data based on the given solver data.
Note
This MUST be called prior to calling SolveVelocity.
See also
SolveVelocity.
Referenced by playrho::d2::Joint::Model< T >::InitVelocity_().
IsLimitEnabled()
bool IsLimitEnabled (const Joint & object) related
Gets the specified joint's limit property if it supports one.
Exceptions
std::invalid_argument If not supported for the given joint's type.
IsMotorEnabled()
bool IsMotorEnabled (const Joint & object) related
Gets the specified joint's motor property value if it supports one.
Exceptions
std::invalid_argument If not supported for the given joint's type.
SetAngularLimits()
void SetAngularLimits (Joint & object, Angle lower, Angle upper) related
Sets the joint limits.
Exceptions
std::invalid_argument If not supported for the given joint's type.
SetAngularOffset()
void SetAngularOffset (Joint & object, Angle value) related
Sets the angular offset property of the specified joint if its type has one.
Exceptions
std::invalid_argument If not supported for the given joint's type.
SetFrequency()
void SetFrequency (Joint & object, Frequency value) related
Sets the frequency of the joint if it has this property.
Exceptions
std::invalid_argument If not supported for the given joint's type.
SetLinearLimits()
void SetLinearLimits (Joint & object, Length lower, Length upper) related
Sets the joint limits.
Exceptions
std::invalid_argument If not supported for the given joint's type.
SetLinearOffset()
void SetLinearOffset (Joint & object, Length2 value) related
Sets the linear offset property of the specified joint if its type has one.
Exceptions
std::invalid_argument If not supported for the given joint's type.
SetMaxMotorForce()
void SetMaxMotorForce (Joint & object, Force value) related
Sets the given joint's max motor force if its type supports that.
Exceptions
std::invalid_argument If not supported for the given joint's type.
SetMaxMotorTorque()
void SetMaxMotorTorque (Joint & object, Torque value) related
Sets the given joint's max motor torque if its type supports that.
Exceptions
std::invalid_argument If not supported for the given joint's type.
SetMotorSpeed()
void SetMotorSpeed (Joint & object, AngularVelocity value) related
Sets the given joint's motor speed if its type supports that.
Exceptions
std::invalid_argument If not supported for the given joint's type.
SetTarget()
void SetTarget (Joint & object, Length2 value) related
Sets the given joint's target property if it has one.
Exceptions
std::invalid_argument If not supported for the given joint's type.
Examples
World.cpp.
ShiftOrigin
bool ShiftOrigin (Joint & object, Length2 value) friend
Shifts the origin for any points stored in world coordinates.
Returns
true if shift done, false otherwise.
Referenced by playrho::d2::Joint::Model< T >::ShiftOrigin_().
SolvePosition
bool SolvePosition (const Joint & object, std::vector< BodyConstraint > & bodies, const ConstraintSolverConf & conf) friend
Solves the position constraint.
Returns
true if the position errors are within tolerance.
Referenced by playrho::d2::Joint::Model< T >::SolvePosition_().
SolveVelocity
bool SolveVelocity (Joint & object, std::vector< BodyConstraint > & bodies, const playrho::StepConf & step) friend
Solves velocity constraint.
Precondition
InitVelocity has been called.
See also
InitVelocity.
Returns
true if velocity is "solved", false otherwise.
Referenced by playrho::d2::Joint::Model< T >::SolveVelocity_().
TypeCast() [1/3]
template<typename T > T TypeCast (const Joint & value) related
Converts the given joint into its current configuration value.
Note
The design for this was based off the design of the C++17 std::any class and its associated std::any_cast function. The code for this is based off of the std::any implementation from the LLVM Project.
Exceptions
std::bad_cast If the given template parameter type isn't the type of this joint's configuration value.
TypeCast [2/3]
template<typename T > std::add_pointer_t<std::add_const_t<T> > TypeCast (const Joint * value) friend
Converts the given joint into its current configuration value.
Note
The design for this was based off the design of the C++17 std::any class and its associated std::any_cast function. The code for this is based off of the std::any code from the LLVM Project.
The design for this was based off the design of the C++17 std::any class and its associated std::any_cast function. The code for this is based off of the std::any implementation from the LLVM Project.
TypeCast [3/3]
template<typename T > std::add_pointer_t<T> TypeCast (Joint * value) friend
Converts the given joint into its current configuration value.
Note
The design for this was based off the design of the C++17 std::any class and its associated std::any_cast function. The code for this is based off of the std::any implementation from the LLVM Project.
The documentation for this class was generated from the following files:
Joint.hpp
DistanceJointConf.hpp
FrictionJointConf.hpp
GearJointConf.hpp
MotorJointConf.hpp
PrismaticJointConf.hpp
PulleyJointConf.hpp
RevoluteJointConf.hpp
RopeJointConf.hpp
TargetJointConf.hpp
WeldJointConf.hpp
WheelJointConf.hpp