PlayRho: playrho::PolygonShape Class Reference
playrho::PolygonShape Class Reference
Shape Classes
Polygon shape.
#include <PolygonShape.hpp>
Classes
struct Conf
Configuration data for polygon shapes.
Public Types
using VertexCounter = std::remove_const< decltype(MaxShapeVertices)>::type
Vertex count type.
Public Member Functions
PolygonShape (const Conf &conf=GetDefaultConf()) noexcept
Default constructor.
PolygonShape (const PolygonShape &other)=default
Copy constructor.
PolygonShape (PolygonShape &&other)=default
Move constructor.
PolygonShape (Length hx, Length hy, const Conf &conf=GetDefaultConf()) noexcept
Initializing constructor for rectangles.
PolygonShape (Span< const Length2D > points, const Conf &conf=GetDefaultConf()) noexcept
Creates a convex hull from the given array of local points. The size of the span must be in the range [1, MaxShapeVertices].
PolygonShape & operator= (const PolygonShape &other)=default
Copy assignment operator.
PolygonShape & operator= (PolygonShape &&other)=default
Move assignment operator.
ChildCounter GetChildCount () const noexcept override
Gets the number of child primitives of the shape.
DistanceProxy GetChild (ChildCounter index) const override
Gets the child for the given index.
MassData GetMassData () const noexcept override
Gets the mass properties of this shape using its dimensions and density.
void Accept (ShapeVisitor &visitor) const override
Accepts a visitor.
void Set (Span< const Length2D > points) noexcept
Creates a convex hull from the given array of local points. The size of the span must be in the range [1, MaxShapeVertices].
void Set (const VertexSet &points) noexcept
Creates a convex hull from the given set of local points. The size of the set must be in the range [1, MaxShapeVertices].
void SetAsBox (Length hx, Length hy) noexcept
Build vertices to represent an axis-aligned box centered on the local origin.
PolygonShape & Transform (Transformation xfm) noexcept
Transforms this polygon by the given transformation.
VertexCounter GetVertexCount () const noexcept
Gets the vertex count.
Length2D GetVertex (VertexCounter index) const
Gets a vertex by index.
UnitVec2 GetNormal (VertexCounter index) const
Gets a normal by index.
Span< const Length2D > GetVertices () const noexcept
Gets the span of vertices.
Span< const UnitVec2 > GetNormals () const noexcept
Gets the span of normals.
Length2D GetCentroid () const noexcept
Gets the centroid.
Public Member Functions inherited from playrho::Shape
NonNegative< Length > GetVertexRadius () const noexcept
Gets the vertex radius.
void SetVertexRadius (NonNegative< Length > vertexRadius) noexcept
Sets the vertex radius.
NonNegative< Density > GetDensity () const noexcept
Gets the density of this fixture.
void SetDensity (NonNegative< Density > density) noexcept
Sets the density of this fixture.
Real GetFriction () const noexcept
Gets the coefficient of friction.
void SetFriction (NonNegative< Real > friction) noexcept
Sets the coefficient of friction.
Real GetRestitution () const noexcept
Gets the coefficient of restitution.
void SetRestitution (Finite< Real > restitution) noexcept
Sets the coefficient of restitution.
Static Public Member Functions
static constexpr Length GetDefaultVertexRadius () noexcept
Gets the default vertex radius for the PolygonShape.
static constexpr Conf GetDefaultConf () noexcept
Gets the default configuration for a PolygonShape.
Static Public Attributes
static constexpr auto InvalidVertex = static_cast<VertexCounter>(-1)
Invalid vertex.
Private Attributes
std::vector< Length2D > m_vertices
Array of vertices.
std::vector< UnitVec2 > m_normals
Normals of edges.
Length2D m_centroid = Length2D{}
Centroid of this shape.
Related Functions
(Note that these are not member functions.)
Length2D GetEdge (const PolygonShape &shape, PolygonShape::VertexCounter index)
Gets the identified edge of the given polygon shape.
bool Validate (const PolygonShape &shape)
Validate convexity of the given shape.
void SetAsBox (PolygonShape &shape, Length hx, Length hy, Length2D center, Angle angle) noexcept
Build vertices to represent an oriented box.
PolygonShape Transform (PolygonShape value, Transformation xfm) noexcept
Transforms the given shape by the given transformation.
Related Functions inherited from playrho::Shape
AABB ComputeAABB (const Shape &shape, const Transformation &xf) noexcept
Computes the AABB for the given shape with the given transformation.
RayCastOutput RayCast (const Shape &shape, ChildCounter childIndex, const RayCastInput &input, const Transformation &transform) noexcept
Cast a ray against the child of the given shape.
NonNegative< Length > GetVertexRadius (const Shape &shape) noexcept
Gets the vertex radius of the given shape.
bool TestPoint (const Shape &shape, Length2D point) noexcept
Test a point for containment in the given shape.
Additional Inherited Members
Protected Member Functions inherited from playrho::Shape
Shape ()=default
Default constructor.
Shape (const ShapeDef &conf) noexcept
Initializing constructor.
Shape (const Shape &other)=default
Copy constructor.
Shape (Shape &&other)=default
Move constructor.
Shape & operator= (const Shape &other)=default
Copy assignment operator.
Shape & operator= (Shape &&other)=default
Move assignment operator.
Detailed Description
Polygon shape.
A convex polygon. The interior of the polygon is to the left of each edge. Polygons have a maximum number of vertices equal to MaxShapeVertices. In most cases you should not need many vertices for a convex polygon.
Note
This data structure is 64-bytes large (with 4-byte Real).
Member Typedef Documentation
using playrho::PolygonShape::VertexCounter = std::remove_const<decltype(MaxShapeVertices)>::type
Vertex count type.
Note
This type must not support more than 255 vertices as that would conflict with the ContactFeature::Index type.
Constructor & Destructor Documentation
playrho::PolygonShape::PolygonShape (const Conf & conf = GetDefaultConf()) inline explicit noexcept
Default constructor.
Constructs a polygon shape with a 0,0 centroid and vertex count of 0.
Note
Polygons with a vertex count less than 1 are "degenerate" and should be treated as invalid.
playrho::PolygonShape::PolygonShape (Length hx, Length hy, const Conf & conf = GetDefaultConf()) explicit noexcept
Initializing constructor for rectangles.
Parameters
hx the half-width.
hy the half-height.
conf Configuration data for the shape.
playrho::PolygonShape::PolygonShape (Span< const Length2D > points, const Conf & conf = GetDefaultConf()) explicit noexcept
Creates a convex hull from the given array of local points. The size of the span must be in the range [1, MaxShapeVertices].
Warning
the points may be re-ordered, even if they form a convex polygon
collinear points are handled but not removed. Collinear points may lead to poor stacking behavior.
Member Function Documentation
DistanceProxy playrho::PolygonShape::GetChild (ChildCounter index) const inline override virtual
Gets the child for the given index.
Parameters
index Index to a child element of the shape. Value must be less than the number of child primitives of the shape.
Note
The shape must remain in scope while the proxy is in use.
Exceptions
InvalidArgument if the given index is out of range.
See also
GetChildCount
Implements playrho::Shape.
Referenced by PolygonShape().
ChildCounter playrho::PolygonShape::GetChildCount () const inline override virtual noexcept
Gets the number of child primitives of the shape.
Returns
Non-negative count.
Implements playrho::Shape.
Referenced by PolygonShape().
MassData playrho::PolygonShape::GetMassData () const override virtual noexcept
Gets the mass properties of this shape using its dimensions and density.
Returns
Mass data for this shape.
Implements playrho::Shape.
Referenced by PolygonShape().
UnitVec2 playrho::PolygonShape::GetNormal (VertexCounter index) const inline
Gets a normal by index.
These are 90-degree clockwise-rotated (outward-facing) unit-vectors of the edges defined by consecutive pairs of vertices starting with vertex 0.
Parameters
index Index of the normal to get.
Returns
Normal for the given index.
Referenced by PolygonShape().
Length2D playrho::PolygonShape::GetVertex (VertexCounter index) const inline
Gets a vertex by index.
Vertices go counter-clockwise.
Referenced by playrho::GetEdge(), PolygonShape(), and playrho::Validate().
PolygonShape::VertexCounter playrho::PolygonShape::GetVertexCount () const inline noexcept
Gets the vertex count.
Returns
value between 0 and MaxShapeVertices inclusive.
See also
MaxShapeVertices.
Referenced by playrho::GetEdge(), GetNormal(), GetNormals(), GetVertex(), GetVertices(), PolygonShape(), Transform(), and playrho::Validate().
Span<const Length2D> playrho::PolygonShape::GetVertices () const inline noexcept
Gets the span of vertices.
Vertices go counter-clockwise.
Referenced by Set().
void playrho::PolygonShape::Set (Span< const Length2D > points) noexcept
Creates a convex hull from the given array of local points. The size of the span must be in the range [1, MaxShapeVertices].
Warning
the points may be re-ordered, even if they form a convex polygon
collinear points are handled but not removed. Collinear points may lead to poor stacking behavior.
Referenced by PolygonShape().
void playrho::PolygonShape::Set (const VertexSet & points) noexcept
Creates a convex hull from the given set of local points. The size of the set must be in the range [1, MaxShapeVertices].
Warning
the points may be re-ordered, even if they form a convex polygon
collinear points are handled but not removed. Collinear points may lead to poor stacking behavior.
void playrho::PolygonShape::SetAsBox (Length hx, Length hy) noexcept
Build vertices to represent an axis-aligned box centered on the local origin.
Parameters
hx the half-width.
hy the half-height.
Referenced by GetNormal(), and PolygonShape().
Friends And Related Function Documentation
Length2D GetEdge (const PolygonShape & shape, PolygonShape::VertexCounter index) related
Gets the identified edge of the given polygon shape.
Note
This must not be called for shapes with less than 2 vertices.
Warning
Behavior is undefined if called for a shape with less than 2 vertices.
Referenced by GetNormal(), and Set().
void SetAsBox (PolygonShape & shape, Length hx, Length hy, Length2D center, Angle angle) related
Build vertices to represent an oriented box.
Parameters
shape Shape to set as a box.
hx the half-width.
hy the half-height.
center the center of the box in local coordinates.
angle the rotation of the box in local coordinates.
PolygonShape Transform (PolygonShape value, Transformation xfm) related
Transforms the given shape by the given transformation.
bool Validate (const PolygonShape & shape) related
Validate convexity of the given shape.
Note
This is a time consuming operation.
Returns
true if valid
Referenced by GetNormal().
Member Data Documentation
std::vector<UnitVec2> playrho::PolygonShape::m_normals private
Normals of edges.
These are 90-degree clockwise-rotated unit-vectors of the vectors defined by consecutive pairs of elements of vertices.
Referenced by GetChild(), GetNormal(), GetNormals(), Set(), SetAsBox(), and Transform().
std::vector<Length2D> playrho::PolygonShape::m_vertices private
Array of vertices.
Consecutive vertices constitute "edges" of the polygon.
Referenced by GetChild(), GetMassData(), GetVertex(), GetVertexCount(), GetVertices(), Set(), SetAsBox(), and Transform().
The documentation for this class was generated from the following files:
PolygonShape.hpp
PolygonShape.cpp