PlayRho: playrho::d2::WorldAtty Class Reference
playrho::d2::WorldAtty Class Reference
World attorney.
#include <WorldAtty.hpp>
Static Private Member Functions
static void TouchProxies (World &world, Fixture &fixture) noexcept
Touches each proxy of the given fixture.
static void SetType (World &world, Body &body, playrho::BodyType type)
Sets the type of the given body.
static Fixture * CreateFixture (World &world, Body &body, const Shape &shape, const FixtureConf &def, bool resetMassData)
Creates a fixture with the given parameters.
static bool Destroy (World &world, Fixture &fixture, bool resetMassData)
Destroys a fixture.
static void RegisterForProxies (World &world, Body &body)
Register for proxies for the given body.
static void RegisterForProxies (World &world, Fixture &fixture)
Register for proxies for the given fixture.
Friends
class Body
class Fixture
Detailed Description
World attorney.
This is the "world attorney" which provides limited privileged access to the World class for the Body and Fixture classes.
Note
This class uses the "attorney-client" idiom to control the granularity of friend-based access to the World class. This is meant to help preserve and enforce the invariants of the World class.
See also
https://en.wikibooks.org/wiki/More_C++_Idioms/Friendship_and_the_Attorney-Client
Member Function Documentation
CreateFixture()
static Fixture* playrho::d2::WorldAtty::CreateFixture (World & world, Body & body, const Shape & shape, const FixtureConf & def, bool resetMassData) inline static private
Creates a fixture with the given parameters.
Exceptions
InvalidArgument if called for a body that doesn't belong to this world.
InvalidArgument if called without a shape.
InvalidArgument if called for a shape with a vertex radius less than the minimum vertex radius.
InvalidArgument if called for a shape with a vertex radius greater than the maximum vertex radius.
WrongState if this method is called while the world is locked.
Referenced by playrho::d2::Body::CreateFixture().
Destroy()
static bool playrho::d2::WorldAtty::Destroy (World & world, Fixture & fixture, bool resetMassData) inline static private
Destroys a fixture.
This removes the fixture from the broad-phase and destroys all contacts associated with this fixture. All fixtures attached to a body are implicitly destroyed when the body is destroyed.
Warning
This function is locked during callbacks.
Note
Make sure to explicitly call ResetMassData after fixtures have been destroyed.
Parameters
world World instance to have destroy the fixture.
fixture the fixture to be removed.
resetMassData Whether or not to reset the mass data of the associated body.
See also
ResetMassData.
Exceptions
WrongState if this method is called while the world is locked.
Referenced by playrho::d2::Body::Destroy().
SetType()
static void playrho::d2::WorldAtty::SetType (World & world, Body & body, playrho::BodyType type) inline static private
Sets the type of the given body.
Note
This may alter the body's mass and velocity.
Exceptions
WrongState if this method is called while the world is locked.
Referenced by playrho::d2::Body::SetType().
TouchProxies()
static void playrho::d2::WorldAtty::TouchProxies (World & world, Fixture & fixture) inline static private noexcept
Touches each proxy of the given fixture.
Note
Fixture must belong to a body that belongs to this world or this method will return false.
This sets things up so that pairs may be created for potentially new contacts.
Referenced by playrho::d2::Fixture::Refilter().
The documentation for this class was generated from the following file:
WorldAtty.hpp