PlayRho: playrho::BodyConstraint Class Reference
playrho::BodyConstraint Class Reference
Body Constraint.
#include <BodyConstraint.hpp>
Public Types
using index_type = std::remove_const< decltype(MaxBodies)>::type
Index type.
Public Member Functions
constexpr BodyConstraint (InvMass invMass, InvRotInertia invRotI, Length2D localCenter, Position position, Velocity velocity) noexcept
Initializing constructor.
InvMass GetInvMass () const noexcept
Gets the inverse mass of this body representation.
InvRotInertia GetInvRotInertia () const noexcept
Gets the inverse rotational inertia of this body representation.
Length2D GetLocalCenter () const noexcept
Gets the location of the body's center of mass in local coordinates.
Position GetPosition () const noexcept
Gets the position of the body.
Velocity GetVelocity () const noexcept
Gets the velocity of the body.
BodyConstraint & SetPosition (Position value) noexcept
Sets the position of the body.
BodyConstraint & SetVelocity (Velocity value) noexcept
Sets the velocity of the body.
Private Attributes
Position m_position
Body position data.
Velocity m_velocity
Body velocity data.
Length2D m_localCenter
Local center of the associated body's sweep.
InvMass m_invMass
Inverse mass of associated body (a non-negative value).
InvRotInertia m_invRotI
Inverse rotational inertia about the center of mass of the associated body (a non-negative value).
Detailed Description
Body Constraint.
Body data related to constraint processing.
Note
Only position and velocity is independently changable after construction.
This data structure is 40-bytes large (with 4-byte Real on at least one 64-bit platform).
Member Function Documentation
InvMass playrho::BodyConstraint::GetInvMass () const inline noexcept
Gets the inverse mass of this body representation.
Returns
Value >= 0.
Referenced by BodyConstraint(), and playrho::GetBodyConstraint().
InvRotInertia playrho::BodyConstraint::GetInvRotInertia () const inline noexcept
Gets the inverse rotational inertia of this body representation.
Returns
Value >= 0.
Referenced by BodyConstraint().
BodyConstraint & playrho::BodyConstraint::SetPosition (Position value) inline noexcept
Sets the position of the body.
Parameters
value A valid position value to set for the represented body.
Warning
Behavior is undefined if the given value is not valid.
Referenced by BodyConstraint().
BodyConstraint & playrho::BodyConstraint::SetVelocity (Velocity value) inline noexcept
Sets the velocity of the body.
Parameters
value A valid velocity value to set for the represented body.
Warning
Behavior is undefined if the given value is not valid.
Referenced by BodyConstraint().
The documentation for this class was generated from the following file:
BodyConstraint.hpp