PlayRho: playrho::Joint2D Class Reference
playrho::Joint2D Class Reference abstract
Joint Classes | Physical Entity Classes
Base joint class.
#include <Joint.hpp>
Public Types
enum LimitState { e_inactiveLimit, e_atLowerLimit, e_atUpperLimit, e_equalLimits }
Limit state.
Public Member Functions
Body2D * GetBodyA () const noexcept
Gets the first body attached to this joint.
Body2D * GetBodyB () const noexcept
Gets the second body attached to this joint.
virtual Length2 GetAnchorA () const =0
Get the anchor point on bodyA in world coordinates.
virtual Length2 GetAnchorB () const =0
Get the anchor point on bodyB in world coordinates.
virtual Momentum2 GetLinearReaction () const =0
Get the linear reaction on bodyB at the joint anchor.
virtual AngularMomentum GetAngularReaction () const =0
Get the angular reaction on bodyB.
virtual void Accept (JointVisitor &visitor) const =0
Accepts a visitor.
virtual void Accept (JointVisitor &visitor)=0
Accepts a visitor.
void * GetUserData () const noexcept
Get the user data pointer.
void SetUserData (void *data) noexcept
Set the user data pointer.
bool GetCollideConnected () const noexcept
Gets collide connected.
virtual bool ShiftOrigin (const Length2)
Shifts the origin for any points stored in world coordinates.
Static Public Member Functions
static bool IsOkay (const JointDef &def) noexcept
Is the given definition okay.
Protected Member Functions
Joint2D (const JointDef &def)
Initializing constructor.
Private Types
enum Flag : FlagsType { e_islandFlag = 0x01u, e_collideConnectedFlag = 0x02u }
Flags stored in m_flags.
using FlagsType = std::uint8_t
Flags type data type.
Private Member Functions
virtual void InitVelocityConstraints (BodyConstraintsMap &bodies, const StepConf &step, const ConstraintSolverConf &conf)=0
Initializes velocity constraint data based on the given solver data.
virtual bool SolveVelocityConstraints (BodyConstraintsMap &bodies, const StepConf &step)=0
Solves velocity constraint.
virtual bool SolvePositionConstraints (BodyConstraintsMap &bodies, const ConstraintSolverConf &conf) const =0
Solves the position constraint.
bool IsIslanded () const noexcept
Whether this joint is in the is-islanded state.
void SetIslanded () noexcept
Sets this joint to be in the is-islanded state.
void UnsetIslanded () noexcept
Unsets this joint from being in the is-islanded state.
Static Private Member Functions
static FlagsType GetFlags (const JointDef &def) noexcept
Gets the flags value for the given joint definition.
template<class OUT_TYPE , class IN_TYPE >
static OUT_TYPE * Create (IN_TYPE def)
Dynamically allocates and instantiates the out-type from the given data.
static Joint2D * Create (const JointDef &def)
Creates a new joint based on the given definition.
static void Destroy (const Joint2D *joint)
Destroys the given joint.
Private Attributes
Body2D *const m_bodyA
Body A.
Body2D *const m_bodyB
Body B.
void * m_userData
User data.
FlagsType m_flags = 0u
Flags. 1-byte.
Friends
class JointAtty
Related Functions
(Note that these are not member functions.)
bool IsEnabled (const Joint2D &j) noexcept
Short-cut function to determine if both bodies are enabled.
void SetAwake (Joint2D &j) noexcept
Wakes up the joined bodies.
JointCounter GetWorldIndex (const Joint2D *joint)
Gets the world index of the given joint.
JointType GetType (const Joint2D &joint) noexcept
Gets the type of the given joint.
Detailed Description
Base joint class.
Joints are used to constraint two bodies together in various fashions. Some joints also feature limits and motors.
See also
World2D
Member Function Documentation
Accept() [1/2]
virtual void playrho::Joint2D::Accept (JointVisitor & visitor) const pure virtual
Accepts a visitor.
This is the Accept method definition of a "visitor design pattern" for for doing joint subclass specific types of processing for a constant joint.
See also
JointVisitor
https://en.wikipedia.org/wiki/Visitor_pattern
Implemented in playrho::GearJoint, playrho::MouseJoint, playrho::RevoluteJoint, playrho::PulleyJoint, playrho::PrismaticJoint, playrho::RopeJoint, playrho::DistanceJoint, playrho::WheelJoint, playrho::FrictionJoint, playrho::MotorJoint, and playrho::WeldJoint.
Accept() [2/2]
virtual void playrho::Joint2D::Accept (JointVisitor & visitor) pure virtual
Accepts a visitor.
This is the Accept method definition of a "visitor design pattern" for for doing joint subclass specific types of processing.
See also
JointVisitor
https://en.wikipedia.org/wiki/Visitor_pattern
Implemented in playrho::GearJoint, playrho::MouseJoint, playrho::RevoluteJoint, playrho::PulleyJoint, playrho::PrismaticJoint, playrho::RopeJoint, playrho::DistanceJoint, playrho::WheelJoint, playrho::FrictionJoint, playrho::MotorJoint, and playrho::WeldJoint.
Create()
Joint2D * playrho::Joint2D::Create (const JointDef & def) static private
Creates a new joint based on the given definition.
Exceptions
InvalidArgument if given a joint definition with a type that's not recognized.
Destroy()
void playrho::Joint2D::Destroy (const Joint2D * joint) static private
Destroys the given joint.
Note
This calls the joint's destructor.
Referenced by playrho::JointAtty::Destroy().
GetCollideConnected()
bool playrho::Joint2D::GetCollideConnected () const inline noexcept
Gets collide connected.
Note
Modifying the collide connect flag won't work correctly because the flag is only checked when fixture AABBs begin to overlap.
Referenced by playrho::Dump(), and playrho::World2D::InternalDestroy().
InitVelocityConstraints()
virtual void playrho::Joint2D::InitVelocityConstraints (BodyConstraintsMap & bodies, const StepConf & step, const ConstraintSolverConf & conf) private pure virtual
Initializes velocity constraint data based on the given solver data.
Note
This MUST be called prior to calling SolveVelocityConstraints.
See also
SolveVelocityConstraints.
Implemented in playrho::RevoluteJoint, playrho::PrismaticJoint, playrho::WheelJoint, playrho::MouseJoint, playrho::MotorJoint, playrho::GearJoint, playrho::PulleyJoint, playrho::DistanceJoint, playrho::RopeJoint, playrho::WeldJoint, and playrho::FrictionJoint.
Referenced by playrho::JointAtty::InitVelocityConstraints().
ShiftOrigin()
virtual bool playrho::Joint2D::ShiftOrigin (const Length2) inline virtual
Shifts the origin for any points stored in world coordinates.
Returns
true if shift done, false otherwise.
Reimplemented in playrho::MouseJoint, and playrho::PulleyJoint.
SolvePositionConstraints()
virtual bool playrho::Joint2D::SolvePositionConstraints (BodyConstraintsMap & bodies, const ConstraintSolverConf & conf) const private pure virtual
Solves the position constraint.
Returns
true if the position errors are within tolerance.
Implemented in playrho::RevoluteJoint, playrho::PrismaticJoint, playrho::WheelJoint, playrho::MouseJoint, playrho::MotorJoint, playrho::GearJoint, playrho::PulleyJoint, playrho::DistanceJoint, playrho::RopeJoint, playrho::WeldJoint, and playrho::FrictionJoint.
Referenced by playrho::JointAtty::SolvePositionConstraints().
SolveVelocityConstraints()
virtual bool playrho::Joint2D::SolveVelocityConstraints (BodyConstraintsMap & bodies, const StepConf & step) private pure virtual
Solves velocity constraint.
Precondition
InitVelocityConstraints has been called.
See also
InitVelocityConstraints.
Returns
true if velocity is "solved", false otherwise.
Implemented in playrho::RevoluteJoint, playrho::PrismaticJoint, playrho::WheelJoint, playrho::MouseJoint, playrho::MotorJoint, playrho::GearJoint, playrho::PulleyJoint, playrho::DistanceJoint, playrho::RopeJoint, playrho::WeldJoint, and playrho::FrictionJoint.
Referenced by playrho::JointAtty::SolveVelocityConstraints().
Friends And Related Function Documentation
GetType()
JointType GetType (const Joint2D & joint) related
Gets the type of the given joint.
GetWorldIndex()
JointCounter GetWorldIndex (const Joint2D * joint) related
Gets the world index of the given joint.
IsEnabled()
bool IsEnabled (const Joint2D & j) related
Short-cut function to determine if both bodies are enabled.
SetAwake()
void SetAwake (Joint2D & j) related
Wakes up the joined bodies.
The documentation for this class was generated from the following files:
Joint.hpp
Joint.cpp
JointType.hpp