PlayRho: playrho::ValueRange< T > Class Template Reference
playrho::ValueRange< T > Class Template Reference
Value range template type.
#include <ValueRange.hpp>
Public Types
using value_type = T
Value type.
Public Member Functions
constexpr ValueRange ()=default
Default constructor.
constexpr ValueRange (const ValueRange &other)=default
Copy constructor.
constexpr ValueRange (ValueRange &&other)=default
Move constructor.
constexpr ValueRange (const value_type &v) noexcept
Initializing constructor.
constexpr ValueRange (const value_type &a, const value_type &b) noexcept
Initializing constructor.
constexpr ValueRange (const std::initializer_list< T > ilist) noexcept
Initializing constructor.
ValueRange & operator= (const ValueRange &other)=default
Copy assignment operator.
ValueRange & operator= (ValueRange &&other)=default
Move assignment operator.
constexpr ValueRange & Move (const value_type &v) noexcept
Moves the value range by the given amount.
constexpr value_type GetMin () const noexcept
Gets the minimum value of this range.
constexpr value_type GetMax () const noexcept
Gets the maximum value of this range.
constexpr ValueRange & Include (const value_type &v) noexcept
Includes the given value into this value range.
constexpr ValueRange & Include (const ValueRange &v) noexcept
Includes the given value range into this value range.
constexpr ValueRange & Intersect (const ValueRange &v) noexcept
Intersects this value range with the given value range.
constexpr ValueRange & Expand (const value_type &v) noexcept
Expands this value range.
constexpr ValueRange & ExpandEqually (const NonNegative< value_type > &v) noexcept
Expands equally both ends of this value range.
Related Functions
(Note that these are not member functions.)
template<typename T >
constexpr T GetCenter (const ValueRange< T > &v) noexcept
Gets the center of the given value range.
Detailed Description
template<typename T>
class playrho::ValueRange< T >
Value range template type.
This type encapsulates a min-max value range relationship.
Invariant
The min and max values can only be the result of std::minmax(a, b) or the special values of positive and negative infinity respectively indicating the "unset" value.
Member Typedef Documentation
value_type
template<typename T> using playrho::ValueRange< T >::value_type = T
Value type.
Alias for the type of the value that this class was template instantiated for.
Constructor & Destructor Documentation
ValueRange() [1/4]
template<typename T> constexpr playrho::ValueRange< T >::ValueRange () default
Default constructor.
Constructs an "unset" value range.
Postcondition
GetMin() returns positive infinity.
GetMax() returns negative infinity.
ValueRange() [2/4]
template<typename T> constexpr playrho::ValueRange< T >::ValueRange (const ValueRange< T > & other) default
Copy constructor.
Postcondition
GetMin() returns the value of other.GetMin().
GetMax() returns the value of other.GetMax().
ValueRange() [3/4]
template<typename T> constexpr playrho::ValueRange< T >::ValueRange (ValueRange< T > && other) default
Move constructor.
Postcondition
GetMin() returns the value of other.GetMin().
GetMax() returns the value of other.GetMax().
ValueRange() [4/4]
template<typename T> constexpr playrho::ValueRange< T >::ValueRange (const value_type & v) inline explicit noexcept
Initializing constructor.
Postcondition
GetMin() returns the value of v.
GetMax() returns the value of v.
Member Function Documentation
Expand()
template<typename T> constexpr ValueRange& playrho::ValueRange< T >::Expand (const value_type & v) inline noexcept
Expands this value range.
Expands this value range by decreasing the min value if the given value is negative, or by increasing the max value if the given value is positive.
Parameters
v Amount to expand this value range by.
Referenced by playrho::AABB::Displace().
ExpandEqually()
template<typename T> constexpr ValueRange& playrho::ValueRange< T >::ExpandEqually (const NonNegative< value_type > & v) inline noexcept
Expands equally both ends of this value range.
Expands equally this value range by decreasing the min value and by increasing the max value by the given amount.
Note
This operation has no effect if this value range is "unset".
Parameters
v Amount to expand both ends of this value range by.
Referenced by playrho::AABB::Fatten(), and playrho::Fatten().
operator=() [1/2]
template<typename T> ValueRange& playrho::ValueRange< T >::operator= (const ValueRange< T > & other) default
Copy assignment operator.
Postcondition
GetMin() returns the value of other.GetMin().
GetMax() returns the value of other.GetMax().
operator=() [2/2]
template<typename T> ValueRange& playrho::ValueRange< T >::operator= (ValueRange< T > && other) default
Move assignment operator.
Postcondition
GetMin() returns the value of other.GetMin().
GetMax() returns the value of other.GetMax().
Friends And Related Function Documentation
GetCenter()
template<typename T > constexpr T GetCenter (const ValueRange< T > & v) related
Gets the center of the given value range.
The documentation for this class was generated from the following file:
ValueRange.hpp