PlayRho: playrho::Sweep Class Reference
playrho::Sweep Class Reference
Description of a "sweep" of motion.
#include <Sweep.hpp>
Public Member Functions
Sweep ()=default
Default constructor.
constexpr Sweep (const Sweep &copy)=default
Copy constructor.
constexpr Sweep (const Position p0, const Position p1, const Length2D lc=Length2D{Real(0)*Meter, Real(0)*Meter}, Real a0=0) noexcept
Initializing constructor.
constexpr Sweep (const Position p, const Length2D lc=Length2D{Real(0)*Meter, Real(0)*Meter})
Initializing constructor.
Length2D GetLocalCenter () const noexcept
Gets the local center of mass position.
Real GetAlpha0 () const noexcept
Gets the alpha0 for this sweep.
void Advance0 (Real alpha) noexcept
Advances the sweep by a factor of the difference between the given time alpha and the sweep's alpha0.
void ResetAlpha0 () noexcept
Resets the alpha 0 value back to zero.
Public Attributes
Position pos0
Center world position and world angle at time "0".
Position pos1
Center world position and world angle at time "1".
Private Attributes
Length2D localCenter = Length2D{Real(0) * Meter, Real(0) * Meter}
Local center of mass position.
Real alpha0 = 0
Fraction of the current time step in the range [0,1].
Detailed Description
Description of a "sweep" of motion.
This describes the motion of a body/shape for TOI computation. Shapes are defined with respect to the body origin, which may not coincide with the center of mass. However, to support dynamics we must interpolate the center of mass position.
Note
This data structure is likely 36-bytes (at least on 64-bit platforms).
Member Function Documentation
void playrho::Sweep::Advance0 (Real alpha) inline noexcept
Advances the sweep by a factor of the difference between the given time alpha and the sweep's alpha0.
This advances position 0 (pos0) of the sweep towards position 1 (pos1) by a factor of the difference between the given alpha and the alpha0.
Parameters
alpha Valid new time factor in [0,1) to update the sweep to. Behavior is undefined if value is invalid.
Referenced by playrho::Body::Advance(), playrho::BodyAtty::Advance0(), and GetAlpha0().
Real playrho::Sweep::GetAlpha0 () const inline noexcept
Gets the alpha0 for this sweep.
Returns
Value between 0 and less than 1.
Referenced by playrho::GetToiViaSat().
Length2D playrho::Sweep::GetLocalCenter () const inline noexcept
Gets the local center of mass position.
Note
This value can only be set via a sweep constructed using an initializing constructor.
Referenced by playrho::Body::GetLocalCenter().
void playrho::Sweep::ResetAlpha0 () inline noexcept
Resets the alpha 0 value back to zero.
Postcondition
Getting the alpha 0 value after calling this method will return zero.
Referenced by GetAlpha0(), and playrho::BodyAtty::ResetAlpha0().
Member Data Documentation
Real playrho::Sweep::alpha0 = 0 private
Fraction of the current time step in the range [0,1].
Note
pos0.linear and pos0.angular are the positions at alpha0.
4-bytes.
Referenced by Advance0(), GetAlpha0(), ResetAlpha0(), and Sweep().
Length2D playrho::Sweep::localCenter = Length2D{Real(0) * Meter, Real(0) * Meter} private
Local center of mass position.
Note
8-bytes.
Referenced by GetLocalCenter(), and Sweep().
The documentation for this class was generated from the following file:
Sweep.hpp