PlayRho: playrho::d2::Fixture Class Reference
playrho::d2::Fixture Class Reference
Physical Entity Classes
An association between a body and a shape.
#include <Fixture.hpp>
Classes
union FixtureProxies
Fixture proxies union.
Public Member Functions
Fixture (NonNull< Body *> body, const FixtureConf &def, const Shape &shape)
Initializing constructor.
Fixture (const Fixture &other)
Copy constructor.
~Fixture ()
Destructor.
NonNull< Body * > GetBody () const noexcept
Gets the parent body of this fixture.
Shape GetShape () const noexcept
Gets the child shape.
void SetSensor (bool sensor) noexcept
Set if this fixture is a sensor.
bool IsSensor () const noexcept
Is this fixture a sensor (non-solid)?
void SetFilterData (Filter filter)
Sets the contact filtering data.
Filter GetFilterData () const noexcept
Gets the contact filtering data.
void Refilter ()
Re-filter the fixture.
void * GetUserData () const noexcept
Get the user data that was assigned in the fixture definition. Use this to store your application specific data.
void SetUserData (void *data) noexcept
Sets the user data.
AreaDensity GetDensity () const noexcept
Gets the density of this fixture.
Real GetFriction () const noexcept
Gets the coefficient of friction.
Real GetRestitution () const noexcept
Gets the coefficient of restitution.
ChildCounter GetProxyCount () const noexcept
Gets the proxy count.
FixtureProxy GetProxy (ChildCounter index) const noexcept
Gets the proxy for the given index.
Span< const FixtureProxy > GetProxies () const noexcept
Gets the proxies.
Private Member Functions
void SetProxies (std::unique_ptr< FixtureProxy[]> value, std::size_t count) noexcept
Sets the proxies.
void ResetProxies () noexcept
Resets the proxies.
Private Attributes
NonNull< Body * > const m_body
Parent body. Set on construction. 8-bytes.
void * m_userData = nullptr
User data. 8-bytes.
Shape m_shape
Shape (of fixture).
FixtureProxies m_proxies
Collection of fixture proxies for the assigned shape. 8-bytes.
ChildCounter m_proxyCount = 0
Proxy count.
Filter m_filter
Filter object. 6-bytes.
bool m_isSensor = false
Is/is-not sensor. 1-bytes.
Friends
class FixtureAtty
Related Functions
(Note that these are not member functions.)
AABB ComputeAABB (const Fixture &fixture) noexcept
Computes the AABB for the given fixture.
MassData GetMassData (const Fixture &f)
Computes the mass data for the given fixture.
bool TestPoint (const Fixture &f, Length2 p) noexcept
Tests a point for containment in a fixture.
void SetAwake (const Fixture &f) noexcept
Sets the associated body's sleep status to awake.
Transformation GetTransformation (const Fixture &f) noexcept
Gets the transformation associated with the given fixture.
bool ShouldCollide (const Fixture &fixtureA, const Fixture &fixtureB) noexcept
Whether contact calculations should be performed between the two fixtures.
FixtureConf GetFixtureConf (const Fixture &fixture) noexcept
Gets the fixture definition for the given fixture.
Detailed Description
An association between a body and a shape.
A fixture is used to attach a shape to a body for collision detection. A fixture inherits its transform from its parent. Fixtures hold additional non-geometric data such as collision filters, etc.
Warning
you cannot reuse fixtures.
Note
Fixtures should be created using the Body::CreateFixture method.
This structure is 56-bytes large (using a 4-byte Real on at least one 64-bit architecture/build).
See also
Body, Shape
Constructor & Destructor Documentation
Fixture()
playrho::d2::Fixture::Fixture (NonNull< Body *> body, const FixtureConf & def, const Shape & shape) inline
Initializing constructor.
Warning
Behavior is undefined if shape is nullptr.
Note
This is not meant to be called by normal user code. Use the Body::CreateFixture method instead.
Parameters
body Body the new fixture is to be associated with.
def Initial fixture settings. Friction must be greater-than-or-equal-to zero. AreaDensity must be greater-than-or-equal-to zero.
shape Shareable shape to associate fixture with. Must be non-null.
~Fixture()
playrho::d2::Fixture::~Fixture () inline
Destructor.
Precondition
Proxy count is zero.
Warning
Behavior is undefined if proxy count is greater than zero.
Member Function Documentation
GetBody()
NonNull< Body * > playrho::d2::Fixture::GetBody () const inline noexcept
Gets the parent body of this fixture.
Returns
Non-null pointer to the parent body.
Referenced by playrho::d2::CalcToi(), playrho::d2::World::CreateAndDestroyProxies(), playrho::d2::World::CreateProxies(), playrho::d2::Body::DestroyFixture(), playrho::d2::World::DestroyFixture(), playrho::d2::World::InternalDestroy(), playrho::d2::World::ProcessContactsForTOI(), playrho::d2::RayCast(), Refilter(), playrho::d2::World::RegisterForProxies(), and playrho::d2::World::SolveToi().
GetDensity()
AreaDensity playrho::d2::Fixture::GetDensity () const inline noexcept
Gets the density of this fixture.
Returns
Non-negative density (in mass per area).
Referenced by playrho::d2::Dump().
GetFriction()
Real playrho::d2::Fixture::GetFriction () const inline noexcept
Gets the coefficient of friction.
Returns
Value of 0 or higher.
Referenced by playrho::d2::Dump(), and playrho::d2::ResetFriction().
GetProxy()
FixtureProxy playrho::d2::Fixture::GetProxy (ChildCounter index) const noexcept
Gets the proxy for the given index.
Warning
Behavior is undefined if given an invalid index.
Returns
Fixture proxy value.
GetProxyCount()
ChildCounter playrho::d2::Fixture::GetProxyCount () const inline noexcept
Gets the proxy count.
Note
This will be zero until a world step has been run since this fixture's creation.
Referenced by playrho::d2::World::CreateAndDestroyProxies(), and playrho::d2::World::CreateProxies().
GetShape()
Shape playrho::d2::Fixture::GetShape () const inline noexcept
Gets the child shape.
The shape is not modifiable. Use a new fixture instead.
Referenced by playrho::d2::World::CreateProxies(), playrho::d2::Dump(), playrho::d2::GetMassData(), playrho::d2::RayCast(), and playrho::d2::World::Synchronize().
IsSensor()
bool playrho::d2::Fixture::IsSensor () const inline noexcept
Is this fixture a sensor (non-solid)?
Returns
the true if the shape is a sensor.
Referenced by playrho::d2::Dump().
Refilter()
void playrho::d2::Fixture::Refilter ()
Re-filter the fixture.
Note
Call this if you want to establish collision that was previously disabled by ShouldCollide(const Fixture&, const Fixture&).
See also
bool ShouldCollide(const Fixture& fixtureA, const Fixture& fixtureB) noexcept
Referenced by SetFilterData().
SetFilterData()
void playrho::d2::Fixture::SetFilterData (Filter filter) inline
Sets the contact filtering data.
Note
This won't update contacts until the next time step when either parent body is speedable and awake.
This automatically calls Refilter.
SetUserData()
void playrho::d2::Fixture::SetUserData (void * data) inline noexcept
Sets the user data.
Note
Use this to store your application specific data.
Friends And Related Function Documentation
ComputeAABB()
AABB ComputeAABB (const Fixture & fixture) related
Computes the AABB for the given fixture.
This is the AABB of the entire shape of the given fixture at the body's location for the given fixture.
GetFixtureConf()
FixtureConf GetFixtureConf (const Fixture & fixture) related
Gets the fixture definition for the given fixture.
Parameters
fixture Fixture to get the definition for.
GetMassData()
MassData GetMassData (const Fixture & f) related
Computes the mass data for the given fixture.
The mass data is based on the density and the shape of the fixture. The rotational inertia is about the shape's origin.
Note
This operation may be expensive.
Parameters
f Fixture to compute the mass data for.
GetTransformation()
Transformation GetTransformation (const Fixture & f) related
Gets the transformation associated with the given fixture.
Warning
Behavior is undefined if the fixture doesn't have an associated body - i.e. behavior is undefined if the fixture has nullptr as its associated body.
SetAwake()
void SetAwake (const Fixture & f) related
Sets the associated body's sleep status to awake.
Note
This is a convenience function that simply looks up the fixture's body and calls that body' SetAwake method.
Parameters
f Fixture whose body should be awoken.
ShouldCollide()
bool ShouldCollide (const Fixture & fixtureA, const Fixture & fixtureB) related
Whether contact calculations should be performed between the two fixtures.
Returns
true if contact calculations should be performed between these two fixtures; false otherwise.
Referenced by playrho::d2::ShouldCollide().
Member Data Documentation
m_proxyCount
ChildCounter playrho::d2::Fixture::m_proxyCount = 0 private
Proxy count.
This is the fixture shape's child count after proxy creation. 4-bytes.
Referenced by GetProxies(), GetProxyCount(), ResetProxies(), and SetProxies().
m_shape
Shape playrho::d2::Fixture::m_shape private
Shape (of fixture).
Note
Set on construction.
Either null or pointer to a heap-memory private copy of the assigned shape.
16-bytes.
Referenced by GetDensity(), GetFriction(), GetRestitution(), and GetShape().
The documentation for this class was generated from the following files:
Fixture.hpp
AABB.hpp
MassData.hpp
Fixture.cpp
FixtureConf.hpp