PlayRho: playrho::ChainShape Class Reference
playrho::ChainShape Class Reference
Shape Classes
Chain shape.
#include <ChainShape.hpp>
Classes
struct Conf
Configuration data for chain shapes.
Public Member Functions
ChainShape (const Conf &conf=GetDefaultConf())
Initializing constructor.
ChainShape (const ChainShape &other)=default
Copy constructor.
ChainShape (ChainShape &&other)=default
Move constructor.
ChainShape & operator= (const ChainShape &other)=default
Copy assignment operator.
ChainShape & operator= (ChainShape &&other)=default
Move assignment operator.
ChildCounter GetChildCount () const noexcept override
Gets the number of child primitives of the shape.
DistanceProxy GetChild (ChildCounter index) const override
Gets the child for the given index.
MassData GetMassData () const noexcept override
Gets the mass properties of this shape using its dimensions and density.
void Accept (ShapeVisitor &visitor) const override
Accepts a visitor.
ChildCounter GetVertexCount () const noexcept
Gets the vertex count.
Length2D GetVertex (ChildCounter index) const
Gets a vertex by index.
UnitVec2 GetNormal (ChildCounter index) const
Gets the normal at the given index.
Public Member Functions inherited from playrho::Shape
NonNegative< Length > GetVertexRadius () const noexcept
Gets the vertex radius.
void SetVertexRadius (NonNegative< Length > vertexRadius) noexcept
Sets the vertex radius.
NonNegative< Density > GetDensity () const noexcept
Gets the density of this fixture.
void SetDensity (NonNegative< Density > density) noexcept
Sets the density of this fixture.
Real GetFriction () const noexcept
Gets the coefficient of friction.
void SetFriction (NonNegative< Real > friction) noexcept
Sets the coefficient of friction.
Real GetRestitution () const noexcept
Gets the coefficient of restitution.
void SetRestitution (Finite< Real > restitution) noexcept
Sets the coefficient of restitution.
Static Public Member Functions
static constexpr NonNegative< Length > GetDefaultVertexRadius () noexcept
Gets the default vertex radius.
static Conf GetDefaultConf () noexcept
Gets the default configuration.
Private Attributes
std::vector< Length2D > m_vertices
Vertices.
std::vector< UnitVec2 > m_normals
Normals.
Additional Inherited Members
Protected Member Functions inherited from playrho::Shape
Shape ()=default
Default constructor.
Shape (const ShapeDef &conf) noexcept
Initializing constructor.
Shape (const Shape &other)=default
Copy constructor.
Shape (Shape &&other)=default
Move constructor.
Shape & operator= (const Shape &other)=default
Copy assignment operator.
Shape & operator= (Shape &&other)=default
Move assignment operator.
Related Functions inherited from playrho::Shape
AABB ComputeAABB (const Shape &shape, const Transformation &xf) noexcept
Computes the AABB for the given shape with the given transformation.
RayCastOutput RayCast (const Shape &shape, ChildCounter childIndex, const RayCastInput &input, const Transformation &transform) noexcept
Cast a ray against the child of the given shape.
NonNegative< Length > GetVertexRadius (const Shape &shape) noexcept
Gets the vertex radius of the given shape.
bool TestPoint (const Shape &shape, Length2D point) noexcept
Test a point for containment in the given shape.
Detailed Description
Chain shape.
A chain shape is a free form sequence of line segments. The chain has two-sided collision, so you can use inside and outside collision. Therefore, you may use any winding order. Since there may be many vertices, they are allocated on the memory heap.
Warning
The chain will not collide properly if there are self-intersections.
Member Function Documentation
DistanceProxy playrho::ChainShape::GetChild (ChildCounter index) const override virtual
Gets the child for the given index.
Parameters
index Index to a child element of the shape. Value must be less than the number of child primitives of the shape.
Note
The shape must remain in scope while the proxy is in use.
Exceptions
InvalidArgument if the given index is out of range.
See also
GetChildCount
Implements playrho::Shape.
Referenced by GetDefaultConf().
ChildCounter playrho::ChainShape::GetChildCount () const override virtual noexcept
Gets the number of child primitives of the shape.
Returns
Non-negative count.
Implements playrho::Shape.
Referenced by GetChild(), and GetDefaultConf().
MassData playrho::ChainShape::GetMassData () const override virtual noexcept
Gets the mass properties of this shape using its dimensions and density.
Returns
Mass data for this shape.
Implements playrho::Shape.
Referenced by GetDefaultConf().
The documentation for this class was generated from the following files:
ChainShape.hpp
ChainShape.cpp