PlayRho: playrho::DiskShape Class Reference
playrho::DiskShape Class Reference
Shape Classes
Disk shape.
#include <DiskShape.hpp>
Classes
struct Conf
Configuration data for disk shapes.
Public Member Functions
DiskShape (const Conf &conf=GetDefaultConf()) noexcept
Initializing constructor.
DiskShape (const Length radius, const Conf &conf=GetDefaultConf()) noexcept
Initializing constructor.
DiskShape (const DiskShape &other)=default
Copy constructor.
DiskShape (DiskShape &&other)=default
Move constructor.
DiskShape & operator= (const DiskShape &other)=default
Copy assignment operator.
DiskShape & operator= (DiskShape &&other)=default
Move assignment operator.
ChildCounter GetChildCount () const noexcept override
Gets the number of child primitives of the shape.
DistanceProxy GetChild (ChildCounter index) const override
Gets the child for the given index.
MassData GetMassData () const noexcept override
Gets the mass properties of this shape using its dimensions and density.
void Accept (ShapeVisitor &visitor) const override
Accepts a visitor.
NonNegative< Length > GetRadius () const noexcept
Gets the "radius" of the shape.
void SetRadius (Length radius) noexcept
Sets the radius to the given value.
Length2D GetLocation () const noexcept
Gets the location of the center of this circle shape.
void SetLocation (const Length2D value) noexcept
Sets the location to the given value.
Public Member Functions inherited from playrho::Shape
NonNegative< Length > GetVertexRadius () const noexcept
Gets the vertex radius.
void SetVertexRadius (NonNegative< Length > vertexRadius) noexcept
Sets the vertex radius.
NonNegative< Density > GetDensity () const noexcept
Gets the density of this fixture.
void SetDensity (NonNegative< Density > density) noexcept
Sets the density of this fixture.
Real GetFriction () const noexcept
Gets the coefficient of friction.
void SetFriction (NonNegative< Real > friction) noexcept
Sets the coefficient of friction.
Real GetRestitution () const noexcept
Gets the coefficient of restitution.
void SetRestitution (Finite< Real > restitution) noexcept
Sets the coefficient of restitution.
Static Public Member Functions
static constexpr Length GetDefaultRadius () noexcept
Gets the default radius.
static constexpr Conf GetDefaultConf () noexcept
Gets the default configuration.
Private Attributes
Length2D m_location = Length2D{}
Location of the shape as initialized on construction or as assigned using the SetPosition method.
Additional Inherited Members
Protected Member Functions inherited from playrho::Shape
Shape ()=default
Default constructor.
Shape (const ShapeDef &conf) noexcept
Initializing constructor.
Shape (const Shape &other)=default
Copy constructor.
Shape (Shape &&other)=default
Move constructor.
Shape & operator= (const Shape &other)=default
Copy assignment operator.
Shape & operator= (Shape &&other)=default
Move assignment operator.
Related Functions inherited from playrho::Shape
AABB ComputeAABB (const Shape &shape, const Transformation &xf) noexcept
Computes the AABB for the given shape with the given transformation.
RayCastOutput RayCast (const Shape &shape, ChildCounter childIndex, const RayCastInput &input, const Transformation &transform) noexcept
Cast a ray against the child of the given shape.
NonNegative< Length > GetVertexRadius (const Shape &shape) noexcept
Gets the vertex radius of the given shape.
bool TestPoint (const Shape &shape, Length2D point) noexcept
Test a point for containment in the given shape.
Detailed Description
Disk shape.
A disk shape "is the region in a plane bounded by a circle". This is a two-dimensional solid round shape. This used to be called the circle shape but that's now used for hollow round shapes.
See also
https://en.wikipedia.org/wiki/Disk_(mathematics)
CircleShape.
Member Function Documentation
DistanceProxy playrho::DiskShape::GetChild (ChildCounter index) const inline override virtual
Gets the child for the given index.
Parameters
index Index to a child element of the shape. Value must be less than the number of child primitives of the shape.
Note
The shape must remain in scope while the proxy is in use.
Exceptions
InvalidArgument if the given index is out of range.
See also
GetChildCount
Implements playrho::Shape.
Referenced by DiskShape().
ChildCounter playrho::DiskShape::GetChildCount () const inline override virtual noexcept
Gets the number of child primitives of the shape.
Returns
Non-negative count.
Implements playrho::Shape.
Referenced by DiskShape().
Length2D playrho::DiskShape::GetLocation () const inline noexcept
Gets the location of the center of this circle shape.
Returns
The origin (0, 0) unless explicitly set otherwise on construction or via the set location method.
See also
SetPosition.
Referenced by GetMassData().
MassData playrho::DiskShape::GetMassData () const override virtual noexcept
Gets the mass properties of this shape using its dimensions and density.
Returns
Mass data for this shape.
Implements playrho::Shape.
Referenced by DiskShape().
NonNegative<Length> playrho::DiskShape::GetRadius () const inline noexcept
Gets the "radius" of the shape.
Returns
Non-negative radius.
The documentation for this class was generated from the following files:
DiskShape.hpp
DiskShape.cpp