PlayRho: playrho::WeldJoint Class Reference
playrho::WeldJoint Class Reference
Joint Classes
Weld joint.
#include <WeldJoint.hpp>
Public Member Functions
WeldJoint (const WeldJointDef &def)
Initializing constructor.
void Accept (JointVisitor &visitor) const override
Accepts a visitor.
Length2D GetAnchorA () const override
Get the anchor point on bodyA in world coordinates.
Length2D GetAnchorB () const override
Get the anchor point on bodyB in world coordinates.
Momentum2D GetLinearReaction () const override
Get the linear reaction on bodyB at the joint anchor.
AngularMomentum GetAngularReaction () const override
Get the angular reaction on bodyB.
Length2D GetLocalAnchorA () const
The local anchor point relative to bodyA's origin.
Length2D GetLocalAnchorB () const
The local anchor point relative to bodyB's origin.
Angle GetReferenceAngle () const
Get the reference angle.
void SetFrequency (Frequency frequency)
Sets frequency.
Frequency GetFrequency () const
Gets the frequency.
void SetDampingRatio (Real ratio)
Sets damping ratio.
Real GetDampingRatio () const
Gets damping ratio.
Public Member Functions inherited from playrho::Joint
Body * GetBodyA () const noexcept
Gets the first body attached to this joint.
Body * GetBodyB () const noexcept
Gets the second body attached to this joint.
void * GetUserData () const noexcept
Get the user data pointer.
void SetUserData (void *data) noexcept
Set the user data pointer.
bool GetCollideConnected () const noexcept
Gets collide connected.
virtual void ShiftOrigin (const Length2D newOrigin)
Shifts the origin for any points stored in world coordinates.
Private Member Functions
void InitVelocityConstraints (BodyConstraintsMap &bodies, const StepConf &step, const ConstraintSolverConf &) override
Initializes velocity constraint data based on the given solver data.
bool SolveVelocityConstraints (BodyConstraintsMap &bodies, const StepConf &step) override
Solves velocity constraint.
bool SolvePositionConstraints (BodyConstraintsMap &bodies, const ConstraintSolverConf &conf) const override
Solves the position constraint.
Private Attributes
Length2D m_localAnchorA
Local anchor A.
Length2D m_localAnchorB
Local anchor B.
Angle m_referenceAngle
Reference angle.
Frequency m_frequency
Frequency.
Real m_dampingRatio
Damping ratio.
Vec3 m_impulse = Vec3_zero
Impulse.
InvRotInertia m_gamma
Gamma.
AngularVelocity m_bias
Bias.
Length2D m_rA
Relative A.
Length2D m_rB
Relative B.
Mat33 m_mass
Mass.
Related Functions
(Note that these are not member functions.)
WeldJointDef GetWeldJointDef (const WeldJoint &joint) noexcept
Gets the definition data for the given joint.
Related Functions inherited from playrho::Joint
bool IsEnabled (const Joint &j) noexcept
Short-cut function to determine if both bodies are enabled.
void SetAwake (Joint &j) noexcept
Wakes up the joined bodies.
JointCounter GetWorldIndex (const Joint *joint)
Gets the world index of the given joint.
JointType GetType (const Joint &joint) noexcept
Gets the type of the given joint.
Additional Inherited Members
Public Types inherited from playrho::Joint
enum LimitState { e_inactiveLimit, e_atLowerLimit, e_atUpperLimit, e_equalLimits }
Limit state.
Static Public Member Functions inherited from playrho::Joint
static bool IsOkay (const JointDef &def) noexcept
Is the given definition okay.
Protected Member Functions inherited from playrho::Joint
Joint (const JointDef &def)
Initializing constructor.
Detailed Description
Weld joint.
A weld joint essentially glues two bodies together. A weld joint may distort somewhat because the island constraint solver is approximate.
Member Function Documentation
void playrho::WeldJoint::InitVelocityConstraints (BodyConstraintsMap & bodies, const StepConf & step, const ConstraintSolverConf & conf) override private virtual
Initializes velocity constraint data based on the given solver data.
Note
This MUST be called prior to calling SolveVelocityConstraints.
See also
SolveVelocityConstraints.
Implements playrho::Joint.
Referenced by GetDampingRatio().
bool playrho::WeldJoint::SolvePositionConstraints (BodyConstraintsMap & bodies, const ConstraintSolverConf & conf) const override private virtual
Solves the position constraint.
Returns
true if the position errors are within tolerance.
Implements playrho::Joint.
Referenced by GetDampingRatio().
bool playrho::WeldJoint::SolveVelocityConstraints (BodyConstraintsMap & bodies, const StepConf & step) override private virtual
Solves velocity constraint.
Precondition
InitVelocityConstraints has been called.
See also
InitVelocityConstraints.
Returns
true if velocity is "solved", false otherwise.
Implements playrho::Joint.
Referenced by GetDampingRatio().
Friends And Related Function Documentation
WeldJointDef GetWeldJointDef (const WeldJoint & joint) related
Gets the definition data for the given joint.
The documentation for this class was generated from the following files:
WeldJoint.hpp
WeldJoint.cpp
WeldJointDef.hpp