PlayRho: World Contacts Related Free Functions
World Contacts Related Free Functions
Collection of "free" functions related to contacts within a World.
Functions
SizedRange< std::vector< KeyedContactPtr >::const_iterator > playrho::d2::GetContacts (const World &world) noexcept
Gets the contacts recognized within the given world.
const Contact & playrho::d2::GetContact (const World &world, ContactID id)
Gets the identified contact.
void playrho::d2::SetContact (World &world, ContactID id, const Contact &value)
Sets the identified contact's state.
bool playrho::d2::IsTouching (const World &world, ContactID id)
Is this contact touching?
bool playrho::d2::IsAwake (const World &world, ContactID id)
Gets the awake status of the specified contact.
void playrho::d2::SetAwake (World &world, ContactID id)
Sets awake the bodies of the fixtures of the given contact.
BodyID playrho::d2::GetBodyA (const World &world, ContactID id)
Gets the body-A of the identified contact if it has one.
BodyID playrho::d2::GetBodyB (const World &world, ContactID id)
Gets the body-B of the identified contact if it has one.
FixtureID playrho::d2::GetFixtureA (const World &world, ContactID id)
Gets fixture A of the identified contact.
FixtureID playrho::d2::GetFixtureB (const World &world, ContactID id)
Gets fixture B of the identified contact.
ChildCounter playrho::d2::GetChildIndexA (const World &world, ContactID id)
Get the child primitive index for fixture A.
ChildCounter playrho::d2::GetChildIndexB (const World &world, ContactID id)
Get the child primitive index for fixture B.
TimestepIters playrho::d2::GetToiCount (const World &world, ContactID id)
Gets the Time Of Impact (TOI) count.
bool playrho::d2::NeedsFiltering (const World &world, ContactID id)
Whether or not the contact needs filtering.
bool playrho::d2::NeedsUpdating (const World &world, ContactID id)
Whether or not the contact needs updating.
bool playrho::d2::HasValidToi (const World &world, ContactID id)
Whether or not the contact has a valid TOI.
Real playrho::d2::GetToi (const World &world, ContactID id)
Gets the time of impact (TOI) as a fraction.
Real playrho::d2::GetDefaultFriction (const World &world, ContactID id)
Gets the default friction amount for the identified contact.
Real playrho::d2::GetDefaultRestitution (const World &world, ContactID id)
Gets the default restitution amount for the identified contact.
Real playrho::d2::GetFriction (const World &world, ContactID id)
Gets the friction used with the identified contact.
Real playrho::d2::GetRestitution (const World &world, ContactID id)
Gets the restitution used with the identified contact.
void playrho::d2::SetFriction (World &world, ContactID id, Real friction)
Sets the friction value for the identified contact.
void playrho::d2::SetRestitution (World &world, ContactID id, Real restitution)
Sets the restitution value for the specified contact.
const Manifold & playrho::d2::GetManifold (const World &world, ContactID id)
Gets the manifold for the identified contact.
WorldManifold playrho::d2::GetWorldManifold (const World &world, ContactID id)
Gets the world manifold for the identified contact.
void playrho::d2::ResetFriction (World &world, ContactID id)
Resets the friction mixture to the default value.
void playrho::d2::ResetRestitution (World &world, ContactID id)
Resets the restitution to the default value.
LinearVelocity playrho::d2::GetTangentSpeed (const World &world, ContactID id)
Gets the tangent speed of the identified contact.
void playrho::d2::SetTangentSpeed (World &world, ContactID id, LinearVelocity value)
Sets the desired tangent speed for a conveyor belt behavior.
bool playrho::d2::IsEnabled (const World &world, ContactID id)
Gets the enabled status of the identified contact.
void playrho::d2::SetEnabled (World &world, ContactID id)
Sets the enabled status of the identified contact.
void playrho::d2::UnsetEnabled (World &world, ContactID id)
Unsets the enabled status of the identified contact.
ContactCounter playrho::d2::GetTouchingCount (const World &world) noexcept
Gets the touching count for the given world.
void playrho::d2::SetEnabled (World &world, ContactID id, bool value)
Convenience function for setting/unsetting the enabled status of the identified contact based on the value parameter.
ContactCounter playrho::d2::GetContactCount (const World &world) noexcept
Gets the count of contacts in the given world.
SizedRange< std::vector< KeyedContactPtr >::const_iterator > GetContacts (const World &world) noexcept
Gets the contacts recognized within the given world.
const Contact & GetContact (const World &world, ContactID id)
Gets the identified contact.
void SetContact (World &world, ContactID id, const Contact &value)
Sets the identified contact's state.
bool IsTouching (const World &world, ContactID id)
Is this contact touching?
bool IsAwake (const World &world, ContactID id)
Gets the awake status of the specified contact.
void SetAwake (World &world, ContactID id)
Sets awake the bodies of the fixtures of the given contact.
BodyID GetBodyA (const World &world, ContactID id)
Gets the body-A of the identified contact if it has one.
BodyID GetBodyB (const World &world, ContactID id)
Gets the body-B of the identified contact if it has one.
FixtureID GetFixtureA (const World &world, ContactID id)
Gets fixture A of the identified contact.
FixtureID GetFixtureB (const World &world, ContactID id)
Gets fixture B of the identified contact.
ChildCounter GetChildIndexA (const World &world, ContactID id)
Get the child primitive index for fixture A.
ChildCounter GetChildIndexB (const World &world, ContactID id)
Get the child primitive index for fixture B.
TimestepIters GetToiCount (const World &world, ContactID id)
Gets the Time Of Impact (TOI) count.
bool NeedsFiltering (const World &world, ContactID id)
Whether or not the contact needs filtering.
bool NeedsUpdating (const World &world, ContactID id)
Whether or not the contact needs updating.
bool HasValidToi (const World &world, ContactID id)
Whether or not the contact has a valid TOI.
Real GetToi (const World &world, ContactID id)
Gets the time of impact (TOI) as a fraction.
Real GetDefaultFriction (const World &world, ContactID id)
Gets the default friction amount for the identified contact.
Real GetDefaultRestitution (const World &world, ContactID id)
Gets the default restitution amount for the identified contact.
Real GetFriction (const World &world, ContactID id)
Gets the friction used with the identified contact.
Real GetRestitution (const World &world, ContactID id)
Gets the restitution used with the identified contact.
void SetFriction (World &world, ContactID id, Real friction)
Sets the friction value for the identified contact.
void SetRestitution (World &world, ContactID id, Real restitution)
Sets the restitution value for the specified contact.
const Manifold & GetManifold (const World &world, ContactID id)
Gets the manifold for the identified contact.
WorldManifold GetWorldManifold (const World &world, ContactID id)
Gets the world manifold for the identified contact.
void ResetFriction (World &world, ContactID id)
Resets the friction mixture to the default value.
void ResetRestitution (World &world, ContactID id)
Resets the restitution to the default value.
LinearVelocity GetTangentSpeed (const World &world, ContactID id)
Gets the tangent speed of the identified contact.
void SetTangentSpeed (World &world, ContactID id, LinearVelocity value)
Sets the desired tangent speed for a conveyor belt behavior.
bool IsEnabled (const World &world, ContactID id)
Gets the enabled status of the identified contact.
void SetEnabled (World &world, ContactID id)
Sets the enabled status of the identified contact.
void UnsetEnabled (World &world, ContactID id)
Unsets the enabled status of the identified contact.
ContactCounter GetTouchingCount (const World &world) noexcept
Gets the touching count for the given world.
void SetEnabled (World &world, ContactID id, bool value)
Convenience function for setting/unsetting the enabled status of the identified contact based on the value parameter.
ContactCounter GetContactCount (const World &world) noexcept
Gets the count of contacts in the given world.
Detailed Description
Collection of "free" functions related to contacts within a World.
This is a collection of non-member non-friend functions - also called "free" functions - that are related to contacts within an instance of a World. Many are just "wrappers" to similarly named member functions but some are additional functionality built on those member functions. A benefit to using free functions that are now just wrappers, is that of helping to isolate your code from future changes that might occur to the underlying World member functions. Free functions in this sense are "cheap" abstractions. While using these incurs extra run-time overhead when compiled without any compiler optimizations enabled, enabling optimizations should entirely eliminate that overhead.
Note
The four basic categories of these functions are "CRUD": create, read, update, and delete.
See also
World, ContactID.
https://en.wikipedia.org/wiki/Create,_read,_update_and_delete.
Function Documentation
GetBodyA() [1/2]
BodyID GetBodyA (const World & world, ContactID id)
Gets the body-A of the identified contact if it has one.
Returns
Identification of the body-A or InvalidBodyID.
Exceptions
std::out_of_range If given an invalid contact identifier.
Examples
World.cpp.
GetBodyA() [2/2]
BodyID GetBodyA (const World & world, ContactID id) related
Gets the body-A of the identified contact if it has one.
Returns
Identification of the body-A or InvalidBodyID.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetBodyB() [1/2]
BodyID GetBodyB (const World & world, ContactID id)
Gets the body-B of the identified contact if it has one.
Returns
Identification of the body-B or InvalidBodyID.
Exceptions
std::out_of_range If given an invalid contact identifier.
Examples
World.cpp.
GetBodyB() [2/2]
BodyID GetBodyB (const World & world, ContactID id) related
Gets the body-B of the identified contact if it has one.
Returns
Identification of the body-B or InvalidBodyID.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetChildIndexA() [1/2]
ChildCounter GetChildIndexA (const World & world, ContactID id)
Get the child primitive index for fixture A.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetChildIndexA() [2/2]
ChildCounter GetChildIndexA (const World & world, ContactID id) related
Get the child primitive index for fixture A.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetChildIndexB() [1/2]
ChildCounter GetChildIndexB (const World & world, ContactID id)
Get the child primitive index for fixture B.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetChildIndexB() [2/2]
ChildCounter GetChildIndexB (const World & world, ContactID id) related
Get the child primitive index for fixture B.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetContact() [1/2]
const Contact & GetContact (const World & world, ContactID id)
Gets the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
Referenced by playrho::d2::GetBodyA(), playrho::d2::GetBodyB(), playrho::d2::GetChildIndexA(), playrho::d2::GetChildIndexB(), playrho::d2::World::GetContact(), playrho::d2::GetFixtureA(), playrho::d2::GetFixtureB(), playrho::d2::GetFriction(), playrho::d2::GetRestitution(), playrho::d2::GetTangentSpeed(), playrho::d2::GetToi(), playrho::d2::GetToiCount(), playrho::d2::HasValidToi(), playrho::d2::IsAwake(), playrho::d2::IsEnabled(), playrho::d2::IsTouching(), playrho::d2::NeedsFiltering(), playrho::d2::NeedsUpdating(), playrho::d2::SetEnabled(), playrho::d2::SetFriction(), playrho::d2::SetRestitution(), playrho::d2::SetTangentSpeed(), and playrho::d2::UnsetEnabled().
GetContact() [2/2]
const Contact & GetContact (const World & world, ContactID id) related
Gets the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetContactCount() [1/2]
ContactCounter GetContactCount (const World & world) related
Gets the count of contacts in the given world.
Note
Not all contacts are for shapes that are actually touching. Some contacts are for shapes which merely have overlapping AABBs.
Returns
0 or higher.
GetContactCount() [2/2]
ContactCounter GetContactCount (const World & world) inline noexcept
Gets the count of contacts in the given world.
Note
Not all contacts are for shapes that are actually touching. Some contacts are for shapes which merely have overlapping AABBs.
Returns
0 or higher.
Examples
World.cpp.
GetDefaultFriction() [1/2]
Real GetDefaultFriction (const World & world, ContactID id)
Gets the default friction amount for the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
SetFriction.
Referenced by playrho::d2::WorldImpl::Add().
GetDefaultFriction() [2/2]
Real GetDefaultFriction (const World & world, ContactID id) related
Gets the default friction amount for the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
SetFriction.
GetDefaultRestitution() [1/2]
Real GetDefaultRestitution (const World & world, ContactID id)
Gets the default restitution amount for the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
SetRestitution.
Referenced by playrho::d2::WorldImpl::Add().
GetDefaultRestitution() [2/2]
Real GetDefaultRestitution (const World & world, ContactID id) related
Gets the default restitution amount for the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
SetRestitution.
GetFixtureA() [1/2]
FixtureID GetFixtureA (const World & world, ContactID id)
Gets fixture A of the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
Examples
World.cpp.
GetFixtureA() [2/2]
FixtureID GetFixtureA (const World & world, ContactID id) related
Gets fixture A of the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetFixtureB() [1/2]
FixtureID GetFixtureB (const World & world, ContactID id)
Gets fixture B of the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
Examples
World.cpp.
GetFixtureB() [2/2]
FixtureID GetFixtureB (const World & world, ContactID id) related
Gets fixture B of the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetFriction() [1/2]
Real GetFriction (const World & world, ContactID id)
Gets the friction used with the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
SetFriction.
GetFriction() [2/2]
Real GetFriction (const World & world, ContactID id) related
Gets the friction used with the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
SetFriction.
GetManifold() [1/2]
const Manifold & GetManifold (const World & world, ContactID id)
Gets the manifold for the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
Referenced by playrho::d2::World::GetManifold().
GetManifold() [2/2]
const Manifold & GetManifold (const World & world, ContactID id) related
Gets the manifold for the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
Examples
World.cpp.
GetRestitution() [1/2]
Real GetRestitution (const World & world, ContactID id)
Gets the restitution used with the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
SetRestitution(World& world, ContactID id, Real restitution)
GetRestitution() [2/2]
Real GetRestitution (const World & world, ContactID id) related
Gets the restitution used with the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
SetRestitution(World& world, ContactID id, Real restitution)
GetTangentSpeed() [1/2]
LinearVelocity GetTangentSpeed (const World & world, ContactID id)
Gets the tangent speed of the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetTangentSpeed() [2/2]
LinearVelocity GetTangentSpeed (const World & world, ContactID id) related
Gets the tangent speed of the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetToi() [1/2]
Real GetToi (const World & world, ContactID id)
Gets the time of impact (TOI) as a fraction.
Note
This is only valid if a TOI has been set.
Returns
Time of impact fraction in the range of 0 to 1 if set (where 1 means no actual impact in current time slot), otherwise undefined.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
HasValidToi.
GetToi() [2/2]
Real GetToi (const World & world, ContactID id) related
Gets the time of impact (TOI) as a fraction.
Note
This is only valid if a TOI has been set.
Returns
Time of impact fraction in the range of 0 to 1 if set (where 1 means no actual impact in current time slot), otherwise undefined.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
HasValidToi.
GetToiCount() [1/2]
TimestepIters GetToiCount (const World & world, ContactID id)
Gets the Time Of Impact (TOI) count.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetToiCount() [2/2]
TimestepIters GetToiCount (const World & world, ContactID id) related
Gets the Time Of Impact (TOI) count.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetWorldManifold() [1/2]
WorldManifold GetWorldManifold (const World & world, ContactID id)
Gets the world manifold for the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetWorldManifold() [2/2]
WorldManifold GetWorldManifold (const World & world, ContactID id) related
Gets the world manifold for the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
HasValidToi() [1/2]
bool HasValidToi (const World & world, ContactID id)
Whether or not the contact has a valid TOI.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
GetToi.
HasValidToi() [2/2]
bool HasValidToi (const World & world, ContactID id) related
Whether or not the contact has a valid TOI.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
GetToi.
IsAwake() [1/2]
bool IsAwake (const World & world, ContactID id)
Gets the awake status of the specified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
SetAwake.
IsAwake() [2/2]
bool IsAwake (const World & world, ContactID id) related
Gets the awake status of the specified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
SetAwake.
IsEnabled() [1/2]
bool IsEnabled (const World & world, ContactID id)
Gets the enabled status of the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
IsEnabled() [2/2]
bool IsEnabled (const World & world, ContactID id) related
Gets the enabled status of the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
IsTouching() [1/2]
bool IsTouching (const World & world, ContactID id)
Is this contact touching?
Touching is defined as either:
This contact's manifold has more than 0 contact points, or
This contact has sensors and the two shapes of this contact are found to be overlapping.
Returns
true if this contact is said to be touching, false otherwise.
Exceptions
std::out_of_range If given an invalid contact identifier.
Examples
World.cpp.
IsTouching() [2/2]
bool IsTouching (const World & world, ContactID id) related
Is this contact touching?
Touching is defined as either:
This contact's manifold has more than 0 contact points, or
This contact has sensors and the two shapes of this contact are found to be overlapping.
Returns
true if this contact is said to be touching, false otherwise.
Exceptions
std::out_of_range If given an invalid contact identifier.
NeedsFiltering() [1/2]
bool NeedsFiltering (const World & world, ContactID id)
Whether or not the contact needs filtering.
Exceptions
std::out_of_range If given an invalid contact identifier.
NeedsFiltering() [2/2]
bool NeedsFiltering (const World & world, ContactID id) related
Whether or not the contact needs filtering.
Exceptions
std::out_of_range If given an invalid contact identifier.
NeedsUpdating() [1/2]
bool NeedsUpdating (const World & world, ContactID id)
Whether or not the contact needs updating.
Exceptions
std::out_of_range If given an invalid contact identifier.
NeedsUpdating() [2/2]
bool NeedsUpdating (const World & world, ContactID id) related
Whether or not the contact needs updating.
Exceptions
std::out_of_range If given an invalid contact identifier.
ResetFriction() [1/2]
void ResetFriction (World & world, ContactID id) related
Resets the friction mixture to the default value.
Exceptions
std::out_of_range If given an invalid contact identifier.
ResetFriction() [2/2]
void ResetFriction (World & world, ContactID id) inline
Resets the friction mixture to the default value.
Exceptions
std::out_of_range If given an invalid contact identifier.
Examples
WorldContact.cpp.
ResetRestitution() [1/2]
void ResetRestitution (World & world, ContactID id) related
Resets the restitution to the default value.
Exceptions
std::out_of_range If given an invalid contact identifier.
ResetRestitution() [2/2]
void ResetRestitution (World & world, ContactID id) inline
Resets the restitution to the default value.
Exceptions
std::out_of_range If given an invalid contact identifier.
Examples
WorldContact.cpp.
SetAwake() [1/2]
void SetAwake (World & world, ContactID id)
Sets awake the bodies of the fixtures of the given contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
SetAwake() [2/2]
void SetAwake (World & world, ContactID id) related
Sets awake the bodies of the fixtures of the given contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
SetContact() [1/2]
void SetContact (World & world, ContactID id, const Contact & value)
Sets the identified contact's state.
Exceptions
std::out_of_range If given an invalid contact identifier.
Referenced by playrho::d2::World::SetContact(), playrho::d2::SetEnabled(), playrho::d2::SetFriction(), playrho::d2::SetRestitution(), playrho::d2::SetTangentSpeed(), and playrho::d2::UnsetEnabled().
SetContact() [2/2]
void SetContact (World & world, ContactID id, const Contact & value) related
Sets the identified contact's state.
Exceptions
std::out_of_range If given an invalid contact identifier.
SetEnabled() [1/4]
void SetEnabled (World & world, ContactID id)
Sets the enabled status of the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
SetEnabled() [2/4]
void SetEnabled (World & world, ContactID id) related
Sets the enabled status of the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
SetEnabled() [3/4]
void SetEnabled (World & world, ContactID id, bool value) inline
Convenience function for setting/unsetting the enabled status of the identified contact based on the value parameter.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
IsEnabled(const World&, ContactID).
SetEnabled() [4/4]
void SetEnabled (World & world, ContactID id, bool value) related
Convenience function for setting/unsetting the enabled status of the identified contact based on the value parameter.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
IsEnabled(const World&, ContactID).
SetFriction() [1/2]
void SetFriction (World & world, ContactID id, Real friction)
Sets the friction value for the identified contact.
Overrides the default friction mixture.
Note
You can call this in "pre-solve" listeners.
This value persists until set or reset.
Warning
Behavior is undefined if given a negative friction value.
Parameters
world The world in which the contact is identified in.
id Identifier of the contact whose friction value should be set.
friction Co-efficient of friction value of zero or greater.
Exceptions
std::out_of_range If given an invalid contact identifier.
SetFriction() [2/2]
void SetFriction (World & world, ContactID id, Real friction) related
Sets the friction value for the identified contact.
Overrides the default friction mixture.
Note
You can call this in "pre-solve" listeners.
This value persists until set or reset.
Warning
Behavior is undefined if given a negative friction value.
Parameters
world The world in which the contact is identified in.
id Identifier of the contact whose friction value should be set.
friction Co-efficient of friction value of zero or greater.
Exceptions
std::out_of_range If given an invalid contact identifier.
SetRestitution() [1/2]
void SetRestitution (World & world, ContactID id, Real restitution)
Sets the restitution value for the specified contact.
This override the default restitution mixture.
Note
You can call this in "pre-solve" listeners.
The value persists until you set or reset.
SetRestitution() [2/2]
void SetRestitution (World & world, ContactID id, Real restitution) related
Sets the restitution value for the specified contact.
This override the default restitution mixture.
Note
You can call this in "pre-solve" listeners.
The value persists until you set or reset.
SetTangentSpeed() [1/2]
void SetTangentSpeed (World & world, ContactID id, LinearVelocity value)
Sets the desired tangent speed for a conveyor belt behavior.
Exceptions
std::out_of_range If given an invalid contact identifier.
SetTangentSpeed() [2/2]
void SetTangentSpeed (World & world, ContactID id, LinearVelocity value) related
Sets the desired tangent speed for a conveyor belt behavior.
Exceptions
std::out_of_range If given an invalid contact identifier.
UnsetEnabled() [1/2]
void UnsetEnabled (World & world, ContactID id)
Unsets the enabled status of the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
UnsetEnabled() [2/2]
void UnsetEnabled (World & world, ContactID id) related
Unsets the enabled status of the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.