PlayRho: Unit definitions for expressing quantities.
Unit definitions for expressing quantities.
Variables
constexpr auto playrho::Second = PLAYRHO_UNIT(Time, boost::units::si::second)
Second unit of Time.
constexpr auto playrho::Hertz = PLAYRHO_UNIT(Frequency, boost::units::si::hertz)
Hertz unit of Frequency.
constexpr auto playrho::Meter = PLAYRHO_UNIT(Length, boost::units::si::meter)
Meter unit of Length.
constexpr auto playrho::MeterPerSecond
Meter per second unit of LinearVelocity.
constexpr auto playrho::MeterPerSquareSecond
Meter per square second unit of LinearAcceleration.
constexpr auto playrho::Kilogram = PLAYRHO_UNIT(Mass, boost::units::si::kilogram)
Kilogram unit of Mass.
constexpr auto playrho::SquareMeter = PLAYRHO_UNIT(Area, boost::units::si::square_meter)
Square meter unit of Area.
constexpr auto playrho::KilogramPerSquareMeter
Kilogram per square meter unit of Density.
constexpr auto playrho::Radian = PLAYRHO_UNIT(Angle, boost::units::si::radian)
Radian unit of Angle.
constexpr auto playrho::Degree = Angle{Radian * Pi / Real{180}}
Degree unit of Angle quantity.
constexpr auto playrho::SquareRadian = Radian * Radian
Square radian unit type.
constexpr auto playrho::RadianPerSecond
Radian per second unit of AngularVelocity.
constexpr auto playrho::DegreePerSecond = AngularVelocity{RadianPerSecond * Degree / Radian}
Degree per second unit of AngularVelocity.
constexpr auto playrho::RadianPerSquareSecond = Radian / (Second * Second)
Radian per square second unit of AngularAcceleration.
constexpr auto playrho::Newton = PLAYRHO_UNIT(Force, boost::units::si::newton)
Newton unit of Force.
constexpr auto playrho::NewtonMeter = PLAYRHO_UNIT(Torque, boost::units::si::newton_meter)
Newton meter unit of Torque.
constexpr auto playrho::NewtonSecond = Newton * Second
Newton second unit of Momentum.
Detailed Description
These are the unit definitions for physical quantities like time and length. Conceptually a given unit is only usable with the quantities that are made up of the dimensions which the unit is associated with.
See also
Physical quantity type aliases..
Variable Documentation
constexpr auto playrho::Degree = Angle{Radian * Pi / Real{180}}
Degree unit of Angle quantity.
See also
Angle.
Radian.
Referenced by playrho::GetRevRotationalAngle().
constexpr auto playrho::DegreePerSecond = AngularVelocity{RadianPerSecond * Degree / Radian}
Degree per second unit of AngularVelocity.
See also
AngularVelocity.
constexpr auto playrho::Hertz = PLAYRHO_UNIT(Frequency, boost::units::si::hertz)
Hertz unit of Frequency.
Represents the hertz unit of Frequency (Hz).
See also
Frequency.
https://en.wikipedia.org/wiki/Hertz
Referenced by playrho::Dump(), and playrho::StepConf::SetTime().
constexpr auto playrho::Kilogram = PLAYRHO_UNIT(Mass, boost::units::si::kilogram)
Kilogram unit of Mass.
See also
Mass.
Referenced by playrho::Body::Body(), playrho::ComputeMassData(), playrho::Dump(), playrho::WeldJoint::GetAngularReaction(), playrho::PrismaticJoint::GetAngularReaction(), playrho::RevoluteJoint::GetAngularReaction(), playrho::WeldJoint::GetLinearReaction(), playrho::PrismaticJoint::GetLinearReaction(), playrho::RevoluteJoint::GetLinearReaction(), playrho::MultiShape::GetMassData(), playrho::ChainShape::GetMassData(), playrho::WeldJoint::InitVelocityConstraints(), playrho::MouseJoint::InitVelocityConstraints(), playrho::PrismaticJoint::InitVelocityConstraints(), playrho::RevoluteJoint::InitVelocityConstraints(), playrho::operator/(), playrho::Body::ResetMassData(), playrho::Body::SetMassData(), playrho::WeldJoint::SolvePositionConstraints(), playrho::GearJoint::SolvePositionConstraints(), playrho::WheelJoint::SolvePositionConstraints(), playrho::PrismaticJoint::SolvePositionConstraints(), playrho::RevoluteJoint::SolvePositionConstraints(), playrho::WeldJoint::SolveVelocityConstraints(), playrho::GearJoint::SolveVelocityConstraints(), playrho::PrismaticJoint::SolveVelocityConstraints(), and playrho::RevoluteJoint::SolveVelocityConstraints().
constexpr auto playrho::KilogramPerSquareMeter
Initial value:
= PLAYRHO_UNIT(Density,
        boost::units::si::kilogram_per_square_meter)
Kilogram per square meter unit of Density.
See also
Density.
constexpr auto playrho::Meter = PLAYRHO_UNIT(Length, boost::units::si::meter)
Meter unit of Length.
A unit of the Length quantity.
See also
Length.
Examples:
HelloWorld.cpp.
Referenced by playrho::Simplex::CalcSearchDirection(), playrho::Dump(), playrho::GearJoint::GearJoint(), playrho::GetClosestPoint(), playrho::details::Defaults< T >::GetLinearSlop(), playrho::details::Defaults< Fixed< std::int32_t, FRACTION_BITS > >::GetLinearSlop(), playrho::GetMaxSeparation(), playrho::details::Defaults< T >::GetMaxVertexRadius(), playrho::details::Defaults< Fixed< std::int32_t, FRACTION_BITS > >::GetMaxVertexRadius(), playrho::GetSupportIndex(), playrho::GetToiViaSat(), playrho::GetUnitVector(), playrho::WeldJoint::InitVelocityConstraints(), playrho::GearJoint::InitVelocityConstraints(), playrho::PrismaticJoint::InitVelocityConstraints(), playrho::RevoluteJoint::InitVelocityConstraints(), playrho::operator/(), playrho::RayCast(), playrho::WeldJoint::SolvePositionConstraints(), playrho::GearJoint::SolvePositionConstraints(), playrho::WheelJoint::SolvePositionConstraints(), playrho::PrismaticJoint::SolvePositionConstraints(), playrho::PrismaticJoint::SolveVelocityConstraints(), playrho::Sqrt(), playrho::Sweep::Sweep(), and playrho::TestPoint().
constexpr auto playrho::MeterPerSecond
Initial value:
= PLAYRHO_UNIT(LinearVelocity,
        boost::units::si::meter_per_second)
Meter per second unit of LinearVelocity.
See also
LinearVelocity.
Referenced by playrho::Dump(), playrho::GetCentripetalForce(), playrho::GetContactRelVelocity(), playrho::WeldJoint::GetLinearReaction(), playrho::PrismaticJoint::GetLinearReaction(), playrho::RevoluteJoint::GetLinearReaction(), playrho::GetUnitVector(), playrho::WeldJoint::InitVelocityConstraints(), playrho::PrismaticJoint::InitVelocityConstraints(), playrho::RevoluteJoint::InitVelocityConstraints(), playrho::operator/(), playrho::WeldJoint::SolveVelocityConstraints(), playrho::PrismaticJoint::SolveVelocityConstraints(), and playrho::RevoluteJoint::SolveVelocityConstraints().
constexpr auto playrho::MeterPerSquareSecond
Initial value:
= PLAYRHO_UNIT(LinearAcceleration,
        boost::units::si::meter_per_second_squared)
Meter per square second unit of LinearAcceleration.
See also
LinearAcceleration.
Referenced by playrho::Dump().
constexpr auto playrho::Newton = PLAYRHO_UNIT(Force, boost::units::si::newton)
Newton unit of Force.
See also
Force.
Referenced by playrho::Dump(), and playrho::operator/().
constexpr auto playrho::NewtonMeter = PLAYRHO_UNIT(Torque, boost::units::si::newton_meter)
Newton meter unit of Torque.
See also
Torque.
Referenced by playrho::Dump().
constexpr auto playrho::NewtonSecond = Newton * Second
Newton second unit of Momentum.
See also
Momentum.
constexpr auto playrho::Radian = PLAYRHO_UNIT(Angle, boost::units::si::radian)
Radian unit of Angle.
See also
Angle.
Degree.
Referenced by playrho::ApplyForce(), playrho::ApplyLinearImpulse(), playrho::Atan2(), playrho::Dump(), playrho::GearJoint::GearJoint(), playrho::UnitVec2::Get(), playrho::WeldJoint::GetAngularReaction(), playrho::PrismaticJoint::GetAngularReaction(), playrho::GearJoint::GetAngularReaction(), playrho::RevoluteJoint::GetAngularReaction(), playrho::GetCircleVertices(), playrho::GetContactRelVelocity(), playrho::GetLinearVelocity(), playrho::GetLinearVelocityFromWorldPoint(), playrho::GetNormalized(), playrho::FrictionJoint::InitVelocityConstraints(), playrho::RopeJoint::InitVelocityConstraints(), playrho::WeldJoint::InitVelocityConstraints(), playrho::GearJoint::InitVelocityConstraints(), playrho::MotorJoint::InitVelocityConstraints(), playrho::PulleyJoint::InitVelocityConstraints(), playrho::DistanceJoint::InitVelocityConstraints(), playrho::MouseJoint::InitVelocityConstraints(), playrho::WheelJoint::InitVelocityConstraints(), playrho::PrismaticJoint::InitVelocityConstraints(), playrho::RevoluteJoint::InitVelocityConstraints(), playrho::Body::ResetMassData(), playrho::RotateAboutWorldPoint(), playrho::SetForce(), playrho::Body::SetMassData(), playrho::RopeJoint::SolvePositionConstraints(), playrho::WeldJoint::SolvePositionConstraints(), playrho::GearJoint::SolvePositionConstraints(), playrho::PulleyJoint::SolvePositionConstraints(), playrho::DistanceJoint::SolvePositionConstraints(), playrho::WheelJoint::SolvePositionConstraints(), playrho::PrismaticJoint::SolvePositionConstraints(), playrho::RevoluteJoint::SolvePositionConstraints(), playrho::FrictionJoint::SolveVelocityConstraints(), playrho::WeldJoint::SolveVelocityConstraints(), playrho::RopeJoint::SolveVelocityConstraints(), playrho::GearJoint::SolveVelocityConstraints(), playrho::MotorJoint::SolveVelocityConstraints(), playrho::PulleyJoint::SolveVelocityConstraints(), playrho::DistanceJoint::SolveVelocityConstraints(), playrho::MouseJoint::SolveVelocityConstraints(), playrho::WheelJoint::SolveVelocityConstraints(), playrho::PrismaticJoint::SolveVelocityConstraints(), and playrho::RevoluteJoint::SolveVelocityConstraints().
constexpr auto playrho::RadianPerSecond
Initial value:
= PLAYRHO_UNIT(AngularVelocity,
        boost::units::si::radian_per_second)
Radian per second unit of AngularVelocity.
See also
AngularVelocity.
Referenced by playrho::Dump(), playrho::WeldJoint::SolveVelocityConstraints(), and playrho::RevoluteJoint::SolveVelocityConstraints().
constexpr auto playrho::RadianPerSquareSecond = Radian / (Second * Second)
Radian per square second unit of AngularAcceleration.
See also
AngularAcceleration.
constexpr auto playrho::Second = PLAYRHO_UNIT(Time, boost::units::si::second)
Second unit of Time.
See also
Time.
Referenced by playrho::WeldJoint::GetAngularReaction(), playrho::PrismaticJoint::GetAngularReaction(), playrho::RevoluteJoint::GetAngularReaction(), playrho::WeldJoint::InitVelocityConstraints(), playrho::MouseJoint::InitVelocityConstraints(), playrho::PrismaticJoint::InitVelocityConstraints(), playrho::RevoluteJoint::InitVelocityConstraints(), playrho::Body::ResetUnderActiveTime(), playrho::Body::SetUnderActiveTime(), playrho::WeldJoint::SolveVelocityConstraints(), playrho::RevoluteJoint::SolveVelocityConstraints(), and playrho::World::Step().
constexpr auto playrho::SquareMeter = PLAYRHO_UNIT(Area, boost::units::si::square_meter)
Square meter unit of Area.
See also
Area.
Referenced by playrho::Simplex::CalcSearchDirection(), playrho::ComputeCentroid(), playrho::Dump(), playrho::WeldJoint::GetAngularReaction(), playrho::PrismaticJoint::GetAngularReaction(), playrho::RevoluteJoint::GetAngularReaction(), playrho::GetAreaOfPolygon(), playrho::VertexSet::GetDefaultMinSeparationSquared(), playrho::GetPolarMoment(), playrho::WeldJoint::InitVelocityConstraints(), playrho::PrismaticJoint::InitVelocityConstraints(), playrho::RevoluteJoint::InitVelocityConstraints(), playrho::RayCast(), playrho::WeldJoint::SolvePositionConstraints(), playrho::PrismaticJoint::SolvePositionConstraints(), playrho::RevoluteJoint::SolvePositionConstraints(), playrho::WeldJoint::SolveVelocityConstraints(), and playrho::RevoluteJoint::SolveVelocityConstraints().
constexpr auto playrho::SquareRadian = Radian * Radian
Square radian unit type.
See also
Angle.
Radian.
Referenced by playrho::MouseJoint::GetEffectiveMassMatrix(), playrho::GetLocalInertia(), playrho::GetMassData(), playrho::VelocityConstraint::GetPoint(), playrho::FrictionJoint::InitVelocityConstraints(), playrho::WeldJoint::InitVelocityConstraints(), playrho::RopeJoint::InitVelocityConstraints(), playrho::GearJoint::InitVelocityConstraints(), playrho::MotorJoint::InitVelocityConstraints(), playrho::PulleyJoint::InitVelocityConstraints(), playrho::WheelJoint::InitVelocityConstraints(), playrho::PrismaticJoint::InitVelocityConstraints(), playrho::RevoluteJoint::InitVelocityConstraints(), playrho::Body::ResetMassData(), playrho::Body::SetMassData(), playrho::WeldJoint::SolvePositionConstraints(), playrho::PulleyJoint::SolvePositionConstraints(), playrho::WheelJoint::SolvePositionConstraints(), playrho::PrismaticJoint::SolvePositionConstraints(), and playrho::RevoluteJoint::SolvePositionConstraints().