PlayRho: World Joint Related Free Functions
World Joint Related Free Functions
Collection of "free" functions related to joints within a World.
Functions
SizedRange< std::vector< JointID >::const_iterator > playrho::d2::GetJoints (const World &world) noexcept
Gets the joints of the specified world.
JointID playrho::d2::CreateJoint (World &world, const Joint &def)
Create a new joint.
void playrho::d2::Destroy (World &world, JointID id)
Destroys the identified joint.
JointType playrho::d2::GetType (const World &world, JointID id)
Gets the type of the joint.
const Joint & playrho::d2::GetJoint (const World &world, JointID id)
Gets the value of the identified joint.
void playrho::d2::SetJoint (World &world, JointID id, const Joint &def)
Sets the value of the identified joint.
bool playrho::d2::GetCollideConnected (const World &world, JointID id)
Gets collide connected for the specified joint.
bool playrho::d2::IsMotorEnabled (const World &world, JointID id)
Is the joint motor enabled?
void playrho::d2::EnableMotor (World &world, JointID id, bool value)
Enable/disable the joint motor.
bool playrho::d2::IsLimitEnabled (const World &world, JointID id)
Gets whether the identified joint's limit is enabled.
void playrho::d2::EnableLimit (World &world, JointID id, bool value)
Sets whether the identified joint's limit is enabled or not.
BodyID playrho::d2::GetBodyA (const World &world, JointID id)
Gets the identifier of body-A of the identified joint.
BodyID playrho::d2::GetBodyB (const World &world, JointID id)
Gets the identifier of body-B of the identified joint.
Length2 playrho::d2::GetLocalAnchorA (const World &world, JointID id)
Get the anchor point on body-A in local coordinates.
Length2 playrho::d2::GetLocalAnchorB (const World &world, JointID id)
Get the anchor point on body-B in local coordinates.
Momentum2 playrho::d2::GetLinearReaction (const World &world, JointID id)
Gets the linear reaction on body-B at the joint anchor.
AngularMomentum playrho::d2::GetAngularReaction (const World &world, JointID id)
Get the angular reaction on body-B for the identified joint.
Angle playrho::d2::GetReferenceAngle (const World &world, JointID id)
Gets the reference-angle property of the identified joint if it has it.
UnitVec playrho::d2::GetLocalXAxisA (const World &world, JointID id)
Gets the local-X-axis-A property of the identified joint if it has it.
UnitVec playrho::d2::GetLocalYAxisA (const World &world, JointID id)
Gets the local-Y-axis-A property of the identified joint if it has it.
AngularVelocity playrho::d2::GetMotorSpeed (const World &world, JointID id)
Gets the motor-speed property of the identied joint if it supports it.
void playrho::d2::SetMotorSpeed (World &world, JointID id, AngularVelocity value)
Sets the motor-speed property of the identied joint if it supports it.
Torque playrho::d2::GetMaxMotorTorque (const World &world, JointID id)
Gets the max motor torque.
void playrho::d2::SetMaxMotorTorque (World &world, JointID id, Torque value)
Sets the maximum motor torque.
Momentum playrho::d2::GetLinearMotorImpulse (const World &world, JointID id)
Gets the linear motor impulse of the identified joint if it supports that.
AngularMomentum playrho::d2::GetAngularMotorImpulse (const World &world, JointID id)
Gets the angular motor impulse of the identified joint if it has this property.
RotInertia playrho::d2::GetAngularMass (const World &world, JointID id)
Gets the computed angular rotational inertia used by the joint.
Frequency playrho::d2::GetFrequency (const World &world, JointID id)
Gets the frequency of the identified joint if it has this property.
void playrho::d2::SetFrequency (World &world, JointID id, Frequency value)
Sets the frequency of the identified joint if it has this property.
AngularVelocity playrho::d2::GetAngularVelocity (const World &world, JointID id)
Gets the angular velocity of the identified joint if it has this property.
bool playrho::d2::IsEnabled (const World &world, JointID id)
Gets the enabled/disabled state of the joint.
JointCounter playrho::d2::GetWorldIndex (const World &world, JointID id) noexcept
Gets the world index of the given joint.
Length2 playrho::d2::GetAnchorA (const World &world, JointID id)
Get the anchor point on body-A in world coordinates.
Length2 playrho::d2::GetAnchorB (const World &world, JointID id)
Get the anchor point on body-B in world coordinates.
Real playrho::d2::GetRatio (const World &world, JointID id)
Gets the ratio property of the identified joint if it has it.
Length playrho::d2::GetJointTranslation (const World &world, JointID id)
Gets the current joint translation.
Angle playrho::d2::GetAngle (const World &world, JointID id)
Gets the angle property of the identified joint if it has it.
Force playrho::d2::GetMotorForce (const World &world, JointID id, Frequency inv_dt)
Gets the current motor force for the given joint, given the inverse time step.
Torque playrho::d2::GetMotorTorque (const World &world, JointID id, Frequency inv_dt)
Gets the current motor torque for the given joint given the inverse time step.
Length2 playrho::d2::GetLinearOffset (const World &world, JointID id)
Gets the target linear offset, in frame A.
void playrho::d2::SetLinearOffset (World &world, JointID id, Length2 value)
Sets the target linear offset, in frame A.
Angle playrho::d2::GetAngularOffset (const World &world, JointID id)
Gets the target angular offset.
void playrho::d2::SetAngularOffset (World &world, JointID id, Angle value)
Sets the target angular offset.
Length2 playrho::d2::GetGroundAnchorA (const World &world, JointID id)
Get the first ground anchor.
Length2 playrho::d2::GetGroundAnchorB (const World &world, JointID id)
Get the second ground anchor.
Length playrho::d2::GetCurrentLengthA (const World &world, JointID id)
Get the current length of the segment attached to body-A.
Length playrho::d2::GetCurrentLengthB (const World &world, JointID id)
Get the current length of the segment attached to body-B.
Length2 playrho::d2::GetTarget (const World &world, JointID id)
Gets the target point.
void playrho::d2::SetTarget (World &world, JointID id, Length2 value)
Sets the target point.
Angle playrho::d2::GetAngularLowerLimit (const World &world, JointID id)
Get the lower joint limit.
Angle playrho::d2::GetAngularUpperLimit (const World &world, JointID id)
Get the upper joint limit.
void playrho::d2::SetAngularLimits (World &world, JointID id, Angle lower, Angle upper)
Set the joint limits.
bool playrho::d2::ShiftOrigin (World &world, JointID id, Length2 value)
Shifts the origin of the identified joint.
Real playrho::d2::GetDampingRatio (const World &world, JointID id)
Gets the damping ratio associated with the identified joint if it has one.
Length playrho::d2::GetLength (const World &world, JointID id)
Gets the length associated with the identified joint if it has one.
LimitState playrho::d2::GetLimitState (const World &world, JointID id)
Gets the joint's limit state if it has one.
void playrho::d2::SetAwake (World &world, JointID id)
Wakes up the joined bodies.
JointCounter playrho::d2::GetJointCount (const World &world) noexcept
Gets the count of joints in the given world.
SizedRange< std::vector< JointID >::const_iterator > GetJoints (const World &world) noexcept
Gets the joints of the specified world.
JointID CreateJoint (World &world, const Joint &def)
Create a new joint.
void Destroy (World &world, JointID id)
Destroys the identified joint.
JointType GetType (const World &world, JointID id)
Gets the type of the joint.
const Joint & GetJoint (const World &world, JointID id)
Gets the value of the identified joint.
void SetJoint (World &world, JointID id, const Joint &def)
Sets the value of the identified joint.
bool GetCollideConnected (const World &world, JointID id)
Gets collide connected for the specified joint.
bool IsMotorEnabled (const World &world, JointID id)
Is the joint motor enabled?
void EnableMotor (World &world, JointID id, bool value)
Enable/disable the joint motor.
bool IsLimitEnabled (const World &world, JointID id)
Gets whether the identified joint's limit is enabled.
void EnableLimit (World &world, JointID id, bool value)
Sets whether the identified joint's limit is enabled or not.
BodyID GetBodyA (const World &world, JointID id)
Gets the identifier of body-A of the identified joint.
BodyID GetBodyB (const World &world, JointID id)
Gets the identifier of body-B of the identified joint.
Length2 GetLocalAnchorA (const World &world, JointID id)
Get the anchor point on body-A in local coordinates.
Length2 GetLocalAnchorB (const World &world, JointID id)
Get the anchor point on body-B in local coordinates.
Momentum2 GetLinearReaction (const World &world, JointID id)
Gets the linear reaction on body-B at the joint anchor.
AngularMomentum GetAngularReaction (const World &world, JointID id)
Get the angular reaction on body-B for the identified joint.
Angle GetReferenceAngle (const World &world, JointID id)
Gets the reference-angle property of the identified joint if it has it.
UnitVec GetLocalXAxisA (const World &world, JointID id)
Gets the local-X-axis-A property of the identified joint if it has it.
UnitVec GetLocalYAxisA (const World &world, JointID id)
Gets the local-Y-axis-A property of the identified joint if it has it.
AngularVelocity GetMotorSpeed (const World &world, JointID id)
Gets the motor-speed property of the identied joint if it supports it.
void SetMotorSpeed (World &world, JointID id, AngularVelocity value)
Sets the motor-speed property of the identied joint if it supports it.
Torque GetMaxMotorTorque (const World &world, JointID id)
Gets the max motor torque.
void SetMaxMotorTorque (World &world, JointID id, Torque value)
Sets the maximum motor torque.
Momentum GetLinearMotorImpulse (const World &world, JointID id)
Gets the linear motor impulse of the identified joint if it supports that.
AngularMomentum GetAngularMotorImpulse (const World &world, JointID id)
Gets the angular motor impulse of the identified joint if it has this property.
RotInertia GetAngularMass (const World &world, JointID id)
Gets the computed angular rotational inertia used by the joint.
Frequency GetFrequency (const World &world, JointID id)
Gets the frequency of the identified joint if it has this property.
void SetFrequency (World &world, JointID id, Frequency value)
Sets the frequency of the identified joint if it has this property.
AngularVelocity GetAngularVelocity (const World &world, JointID id)
Gets the angular velocity of the identified joint if it has this property.
bool IsEnabled (const World &world, JointID id)
Gets the enabled/disabled state of the joint.
JointCounter GetWorldIndex (const World &world, JointID id) noexcept
Gets the world index of the given joint.
Length2 GetAnchorA (const World &world, JointID id)
Get the anchor point on body-A in world coordinates.
Length2 GetAnchorB (const World &world, JointID id)
Get the anchor point on body-B in world coordinates.
Real GetRatio (const World &world, JointID id)
Gets the ratio property of the identified joint if it has it.
Length GetJointTranslation (const World &world, JointID id)
Gets the current joint translation.
Angle GetAngle (const World &world, JointID id)
Gets the angle property of the identified joint if it has it.
Force GetMotorForce (const World &world, JointID id, Frequency inv_dt)
Gets the current motor force for the given joint, given the inverse time step.
Torque GetMotorTorque (const World &world, JointID id, Frequency inv_dt)
Gets the current motor torque for the given joint given the inverse time step.
Length2 GetLinearOffset (const World &world, JointID id)
Gets the target linear offset, in frame A.
void SetLinearOffset (World &world, JointID id, Length2 value)
Sets the target linear offset, in frame A.
Angle GetAngularOffset (const World &world, JointID id)
Gets the target angular offset.
void SetAngularOffset (World &world, JointID id, Angle value)
Sets the target angular offset.
Length2 GetGroundAnchorA (const World &world, JointID id)
Get the first ground anchor.
Length2 GetGroundAnchorB (const World &world, JointID id)
Get the second ground anchor.
Length GetCurrentLengthA (const World &world, JointID id)
Get the current length of the segment attached to body-A.
Length GetCurrentLengthB (const World &world, JointID id)
Get the current length of the segment attached to body-B.
Length2 GetTarget (const World &world, JointID id)
Gets the target point.
void SetTarget (World &world, JointID id, Length2 value)
Sets the target point.
Angle GetAngularLowerLimit (const World &world, JointID id)
Get the lower joint limit.
Angle GetAngularUpperLimit (const World &world, JointID id)
Get the upper joint limit.
void SetAngularLimits (World &world, JointID id, Angle lower, Angle upper)
Set the joint limits.
bool ShiftOrigin (World &world, JointID id, Length2 value)
Shifts the origin of the identified joint.
Real GetDampingRatio (const World &world, JointID id)
Gets the damping ratio associated with the identified joint if it has one.
Length GetLength (const World &world, JointID id)
Gets the length associated with the identified joint if it has one.
LimitState GetLimitState (const World &world, JointID id)
Gets the joint's limit state if it has one.
void SetAwake (World &world, JointID id)
Wakes up the joined bodies.
JointCounter GetJointCount (const World &world) noexcept
Gets the count of joints in the given world.
Detailed Description
Collection of "free" functions related to joints within a World.
This is a collection of non-member non-friend functions - also called "free" functions - that are related to joints within an instance of a World. Many are just "wrappers" to similarly named member functions but some are additional functionality built on those member functions. A benefit to using free functions that are now just wrappers, is that of helping to isolate your code from future changes that might occur to the underlying World member functions. Free functions in this sense are "cheap" abstractions. While using these incurs extra run-time overhead when compiled without any compiler optimizations enabled, enabling optimizations should entirely eliminate that overhead.
Note
The four basic categories of these functions are "CRUD": create, read, update, and delete.
See also
World, JointID.
https://en.wikipedia.org/wiki/Create,_read,_update_and_delete.
Function Documentation
Destroy() [1/2]
void Destroy (World & world, JointID id)
Destroys the identified joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
Destroy() [2/2]
void Destroy (World & world, JointID id) related
Destroys the identified joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
EnableLimit() [1/2]
void EnableLimit (World & world, JointID id, bool value)
Sets whether the identified joint's limit is enabled or not.
Exceptions
std::out_of_range If given an invalid joint identifier.
EnableLimit() [2/2]
void EnableLimit (World & world, JointID id, bool value) related
Sets whether the identified joint's limit is enabled or not.
Exceptions
std::out_of_range If given an invalid joint identifier.
EnableMotor() [1/2]
void EnableMotor (World & world, JointID id, bool value)
Enable/disable the joint motor.
Exceptions
std::out_of_range If given an invalid joint identifier.
EnableMotor() [2/2]
void EnableMotor (World & world, JointID id, bool value) related
Enable/disable the joint motor.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAnchorA() [1/2]
Length2 GetAnchorA (const World & world, JointID id)
Get the anchor point on body-A in world coordinates.
Exceptions
std::out_of_range If given an invalid joint identifier.
Referenced by playrho::d2::GetCurrentLengthA(), and playrho::d2::GetJointTranslation().
GetAnchorA() [2/2]
Length2 GetAnchorA (const World & world, JointID id) related
Get the anchor point on body-A in world coordinates.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAnchorB() [1/2]
Length2 GetAnchorB (const World & world, JointID id)
Get the anchor point on body-B in world coordinates.
Exceptions
std::out_of_range If given an invalid joint identifier.
Referenced by playrho::d2::GetCurrentLengthB(), and playrho::d2::GetJointTranslation().
GetAnchorB() [2/2]
Length2 GetAnchorB (const World & world, JointID id) related
Get the anchor point on body-B in world coordinates.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngle() [1/2]
Angle GetAngle (const World & world, JointID id)
Gets the angle property of the identified joint if it has it.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngle() [2/2]
Angle GetAngle (const World & world, JointID id) related
Gets the angle property of the identified joint if it has it.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularLowerLimit() [1/2]
Angle GetAngularLowerLimit (const World & world, JointID id)
Get the lower joint limit.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularLowerLimit() [2/2]
Angle GetAngularLowerLimit (const World & world, JointID id) related
Get the lower joint limit.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularMass() [1/2]
RotInertia GetAngularMass (const World & world, JointID id)
Gets the computed angular rotational inertia used by the joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularMass() [2/2]
RotInertia GetAngularMass (const World & world, JointID id) related
Gets the computed angular rotational inertia used by the joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularMotorImpulse() [1/2]
AngularMomentum GetAngularMotorImpulse (const World & world, JointID id)
Gets the angular motor impulse of the identified joint if it has this property.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularMotorImpulse() [2/2]
AngularMomentum GetAngularMotorImpulse (const World & world, JointID id) related
Gets the angular motor impulse of the identified joint if it has this property.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularOffset() [1/2]
Angle GetAngularOffset (const World & world, JointID id)
Gets the target angular offset.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularOffset() [2/2]
Angle GetAngularOffset (const World & world, JointID id) related
Gets the target angular offset.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularReaction() [1/2]
AngularMomentum GetAngularReaction (const World & world, JointID id)
Get the angular reaction on body-B for the identified joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
Referenced by playrho::d2::World::GetAngularReaction().
GetAngularReaction() [2/2]
AngularMomentum GetAngularReaction (const World & world, JointID id) related
Get the angular reaction on body-B for the identified joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularUpperLimit() [1/2]
Angle GetAngularUpperLimit (const World & world, JointID id)
Get the upper joint limit.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularUpperLimit() [2/2]
Angle GetAngularUpperLimit (const World & world, JointID id) related
Get the upper joint limit.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularVelocity() [1/2]
AngularVelocity GetAngularVelocity (const World & world, JointID id)
Gets the angular velocity of the identified joint if it has this property.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularVelocity() [2/2]
AngularVelocity GetAngularVelocity (const World & world, JointID id) related
Gets the angular velocity of the identified joint if it has this property.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetBodyA() [1/2]
BodyID GetBodyA (const World & world, JointID id)
Gets the identifier of body-A of the identified joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetBodyA() [2/2]
BodyID GetBodyA (const World & world, JointID id) related
Gets the identifier of body-A of the identified joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetBodyB() [1/2]
BodyID GetBodyB (const World & world, JointID id)
Gets the identifier of body-B of the identified joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetBodyB() [2/2]
BodyID GetBodyB (const World & world, JointID id) related
Gets the identifier of body-B of the identified joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetCollideConnected() [1/2]
bool GetCollideConnected (const World & world, JointID id)
Gets collide connected for the specified joint.
Note
Modifying the collide connect flag won't work correctly because the flag is only checked when fixture AABBs begin to overlap.
Exceptions
std::out_of_range If given an invalid joint identifier.
Referenced by playrho::d2::World::GetCollideConnected().
GetCollideConnected() [2/2]
bool GetCollideConnected (const World & world, JointID id) related
Gets collide connected for the specified joint.
Note
Modifying the collide connect flag won't work correctly because the flag is only checked when fixture AABBs begin to overlap.
Exceptions
std::out_of_range If given an invalid joint identifier.
Examples
World.cpp.
GetCurrentLengthA() [1/2]
Length GetCurrentLengthA (const World & world, JointID id)
Get the current length of the segment attached to body-A.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetCurrentLengthA() [2/2]
Length GetCurrentLengthA (const World & world, JointID id) related
Get the current length of the segment attached to body-A.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetCurrentLengthB() [1/2]
Length GetCurrentLengthB (const World & world, JointID id)
Get the current length of the segment attached to body-B.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetCurrentLengthB() [2/2]
Length GetCurrentLengthB (const World & world, JointID id) related
Get the current length of the segment attached to body-B.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetDampingRatio() [1/2]
Real GetDampingRatio (const World & world, JointID id)
Gets the damping ratio associated with the identified joint if it has one.
Exceptions
std::out_of_range If given an invalid joint identifier.
std::invalid_argument If the identified joint's type doesn't support this.
GetDampingRatio() [2/2]
Real GetDampingRatio (const World & world, JointID id) related
Gets the damping ratio associated with the identified joint if it has one.
Exceptions
std::out_of_range If given an invalid joint identifier.
std::invalid_argument If the identified joint's type doesn't support this.
GetFrequency() [1/2]
Frequency GetFrequency (const World & world, JointID id)
Gets the frequency of the identified joint if it has this property.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetFrequency() [2/2]
Frequency GetFrequency (const World & world, JointID id) related
Gets the frequency of the identified joint if it has this property.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetGroundAnchorA() [1/2]
Length2 GetGroundAnchorA (const World & world, JointID id)
Get the first ground anchor.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetGroundAnchorA() [2/2]
Length2 GetGroundAnchorA (const World & world, JointID id) related
Get the first ground anchor.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetGroundAnchorB() [1/2]
Length2 GetGroundAnchorB (const World & world, JointID id)
Get the second ground anchor.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetGroundAnchorB() [2/2]
Length2 GetGroundAnchorB (const World & world, JointID id) related
Get the second ground anchor.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetJoint() [1/2]
const Joint & GetJoint (const World & world, JointID id)
Gets the value of the identified joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
Referenced by playrho::d2::World::GetJoint().
GetJoint() [2/2]
const Joint & GetJoint (const World & world, JointID id) related
Gets the value of the identified joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetJointCount() [1/2]
JointCounter GetJointCount (const World & world) inline noexcept
Gets the count of joints in the given world.
Returns
0 or higher.
Examples
World.cpp.
GetJointCount() [2/2]
JointCounter GetJointCount (const World & world) related
Gets the count of joints in the given world.
Returns
0 or higher.
Examples
World.cpp.
GetJointTranslation() [1/2]
Length GetJointTranslation (const World & world, JointID id)
Gets the current joint translation.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetJointTranslation() [2/2]
Length GetJointTranslation (const World & world, JointID id) related
Gets the current joint translation.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLength() [1/2]
Length GetLength (const World & world, JointID id)
Gets the length associated with the identified joint if it has one.
Exceptions
std::out_of_range If given an invalid joint identifier.
std::invalid_argument If the identified joint's type doesn't support this.
GetLength() [2/2]
Length GetLength (const World & world, JointID id) related
Gets the length associated with the identified joint if it has one.
Exceptions
std::out_of_range If given an invalid joint identifier.
std::invalid_argument If the identified joint's type doesn't support this.
GetLimitState() [1/2]
LimitState GetLimitState (const World & world, JointID id)
Gets the joint's limit state if it has one.
Exceptions
std::out_of_range If given an invalid joint identifier.
std::invalid_argument If the identified joint's type doesn't support this.
GetLimitState() [2/2]
LimitState GetLimitState (const World & world, JointID id) related
Gets the joint's limit state if it has one.
Exceptions
std::out_of_range If given an invalid joint identifier.
std::invalid_argument If the identified joint's type doesn't support this.
GetLinearMotorImpulse() [1/2]
Momentum GetLinearMotorImpulse (const World & world, JointID id)
Gets the linear motor impulse of the identified joint if it supports that.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLinearMotorImpulse() [2/2]
Momentum GetLinearMotorImpulse (const World & world, JointID id) related
Gets the linear motor impulse of the identified joint if it supports that.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLinearOffset() [1/2]
Length2 GetLinearOffset (const World & world, JointID id)
Gets the target linear offset, in frame A.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLinearOffset() [2/2]
Length2 GetLinearOffset (const World & world, JointID id) related
Gets the target linear offset, in frame A.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLinearReaction() [1/2]
Momentum2 GetLinearReaction (const World & world, JointID id)
Gets the linear reaction on body-B at the joint anchor.
Exceptions
std::out_of_range If given an invalid joint identifier.
Referenced by playrho::d2::World::GetLinearReaction().
GetLinearReaction() [2/2]
Momentum2 GetLinearReaction (const World & world, JointID id) related
Gets the linear reaction on body-B at the joint anchor.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLocalAnchorA() [1/2]
Length2 GetLocalAnchorA (const World & world, JointID id)
Get the anchor point on body-A in local coordinates.
Exceptions
std::out_of_range If given an invalid joint identifier.
Referenced by playrho::d2::World::GetLocalAnchorA().
GetLocalAnchorA() [2/2]
Length2 GetLocalAnchorA (const World & world, JointID id) related
Get the anchor point on body-A in local coordinates.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLocalAnchorB() [1/2]
Length2 GetLocalAnchorB (const World & world, JointID id)
Get the anchor point on body-B in local coordinates.
Exceptions
std::out_of_range If given an invalid joint identifier.
Referenced by playrho::d2::World::GetLocalAnchorB().
GetLocalAnchorB() [2/2]
Length2 GetLocalAnchorB (const World & world, JointID id) related
Get the anchor point on body-B in local coordinates.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLocalXAxisA() [1/2]
UnitVec GetLocalXAxisA (const World & world, JointID id)
Gets the local-X-axis-A property of the identified joint if it has it.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLocalXAxisA() [2/2]
UnitVec GetLocalXAxisA (const World & world, JointID id) related
Gets the local-X-axis-A property of the identified joint if it has it.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLocalYAxisA() [1/2]
UnitVec GetLocalYAxisA (const World & world, JointID id)
Gets the local-Y-axis-A property of the identified joint if it has it.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLocalYAxisA() [2/2]
UnitVec GetLocalYAxisA (const World & world, JointID id) related
Gets the local-Y-axis-A property of the identified joint if it has it.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetMaxMotorTorque() [1/2]
Torque GetMaxMotorTorque (const World & world, JointID id)
Gets the max motor torque.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetMaxMotorTorque() [2/2]
Torque GetMaxMotorTorque (const World & world, JointID id) related
Gets the max motor torque.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetMotorForce() [1/2]
Force GetMotorForce (const World & world, JointID id, Frequency inv_dt) inline
Gets the current motor force for the given joint, given the inverse time step.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetMotorForce() [2/2]
Force GetMotorForce (const World & world, JointID id, Frequency inv_dt) related
Gets the current motor force for the given joint, given the inverse time step.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetMotorSpeed() [1/2]
AngularVelocity GetMotorSpeed (const World & world, JointID id)
Gets the motor-speed property of the identied joint if it supports it.
Exceptions
std::out_of_range If given an invalid joint identifier.
See also
SetMotorSpeed(World& world, JointID id, AngularVelocity value)
GetMotorSpeed() [2/2]
AngularVelocity GetMotorSpeed (const World & world, JointID id) related
Gets the motor-speed property of the identied joint if it supports it.
Exceptions
std::out_of_range If given an invalid joint identifier.
See also
SetMotorSpeed(World& world, JointID id, AngularVelocity value)
GetMotorTorque() [1/2]
Torque GetMotorTorque (const World & world, JointID id, Frequency inv_dt) related
Gets the current motor torque for the given joint given the inverse time step.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetMotorTorque() [2/2]
Torque GetMotorTorque (const World & world, JointID id, Frequency inv_dt) inline
Gets the current motor torque for the given joint given the inverse time step.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetRatio() [1/2]
Real GetRatio (const World & world, JointID id)
Gets the ratio property of the identified joint if it has it.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetRatio() [2/2]
Real GetRatio (const World & world, JointID id) related
Gets the ratio property of the identified joint if it has it.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetReferenceAngle() [1/2]
Angle GetReferenceAngle (const World & world, JointID id)
Gets the reference-angle property of the identified joint if it has it.
Exceptions
std::out_of_range If given an invalid joint identifier.
Referenced by playrho::d2::World::GetReferenceAngle().
GetReferenceAngle() [2/2]
Angle GetReferenceAngle (const World & world, JointID id) related
Gets the reference-angle property of the identified joint if it has it.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetTarget() [1/2]
Length2 GetTarget (const World & world, JointID id)
Gets the target point.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetTarget() [2/2]
Length2 GetTarget (const World & world, JointID id) related
Gets the target point.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetType() [1/2]
JointType GetType (const World & world, JointID id)
Gets the type of the joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetType() [2/2]
JointType GetType (const World & world, JointID id) related
Gets the type of the joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetWorldIndex() [1/2]
JointCounter GetWorldIndex (const World & world, JointID id) noexcept
Gets the world index of the given joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetWorldIndex() [2/2]
JointCounter GetWorldIndex (const World & world, JointID id) related
Gets the world index of the given joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
IsEnabled() [1/2]
bool IsEnabled (const World & world, JointID id)
Gets the enabled/disabled state of the joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
IsEnabled() [2/2]
bool IsEnabled (const World & world, JointID id) related
Gets the enabled/disabled state of the joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
IsLimitEnabled() [1/2]
bool IsLimitEnabled (const World & world, JointID id)
Gets whether the identified joint's limit is enabled.
Exceptions
std::out_of_range If given an invalid joint identifier.
IsLimitEnabled() [2/2]
bool IsLimitEnabled (const World & world, JointID id) related
Gets whether the identified joint's limit is enabled.
Exceptions
std::out_of_range If given an invalid joint identifier.
IsMotorEnabled() [1/2]
bool IsMotorEnabled (const World & world, JointID id)
Is the joint motor enabled?
Exceptions
std::out_of_range If given an invalid joint identifier.
See also
EnableMotor(World& world, JointID joint, bool value)
IsMotorEnabled() [2/2]
bool IsMotorEnabled (const World & world, JointID id) related
Is the joint motor enabled?
Exceptions
std::out_of_range If given an invalid joint identifier.
See also
EnableMotor(World& world, JointID joint, bool value)
SetAngularLimits() [1/2]
void SetAngularLimits (World & world, JointID id, Angle lower, Angle upper)
Set the joint limits.
Exceptions
std::out_of_range If given an invalid joint identifier.
SetAngularLimits() [2/2]
void SetAngularLimits (World & world, JointID id, Angle lower, Angle upper) related
Set the joint limits.
Exceptions
std::out_of_range If given an invalid joint identifier.
SetAngularOffset() [1/2]
void SetAngularOffset (World & world, JointID id, Angle value)
Sets the target angular offset.
Exceptions
std::out_of_range If given an invalid joint identifier.
SetAngularOffset() [2/2]
void SetAngularOffset (World & world, JointID id, Angle value) related
Sets the target angular offset.
Exceptions
std::out_of_range If given an invalid joint identifier.
SetAwake() [1/2]
void SetAwake (World & world, JointID id)
Wakes up the joined bodies.
Exceptions
std::out_of_range If given an invalid joint identifier.
SetAwake() [2/2]
void SetAwake (World & world, JointID id) related
Wakes up the joined bodies.
Exceptions
std::out_of_range If given an invalid joint identifier.
SetFrequency() [1/2]
void SetFrequency (World & world, JointID id, Frequency value)
Sets the frequency of the identified joint if it has this property.
Exceptions
std::out_of_range If given an invalid joint identifier.
SetFrequency() [2/2]
void SetFrequency (World & world, JointID id, Frequency value) related
Sets the frequency of the identified joint if it has this property.
Exceptions
std::out_of_range If given an invalid joint identifier.
SetJoint() [1/2]
void SetJoint (World & world, JointID id, const Joint & def)
Sets the value of the identified joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
Referenced by playrho::d2::World::SetJoint().
SetJoint() [2/2]
void SetJoint (World & world, JointID id, const Joint & def) related
Sets the value of the identified joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
SetLinearOffset() [1/2]
void SetLinearOffset (World & world, JointID id, Length2 value)
Sets the target linear offset, in frame A.
Exceptions
std::out_of_range If given an invalid joint identifier.
SetLinearOffset() [2/2]
void SetLinearOffset (World & world, JointID id, Length2 value) related
Sets the target linear offset, in frame A.
Exceptions
std::out_of_range If given an invalid joint identifier.
SetMaxMotorTorque() [1/2]
void SetMaxMotorTorque (World & world, JointID id, Torque value)
Sets the maximum motor torque.
Exceptions
std::out_of_range If given an invalid joint identifier.
SetMaxMotorTorque() [2/2]
void SetMaxMotorTorque (World & world, JointID id, Torque value) related
Sets the maximum motor torque.
Exceptions
std::out_of_range If given an invalid joint identifier.
SetMotorSpeed() [1/2]
void SetMotorSpeed (World & world, JointID id, AngularVelocity value)
Sets the motor-speed property of the identied joint if it supports it.
Exceptions
std::out_of_range If given an invalid joint identifier.
See also
GetMotorSpeed(const World& world, JointID id)
SetMotorSpeed() [2/2]
void SetMotorSpeed (World & world, JointID id, AngularVelocity value) related
Sets the motor-speed property of the identied joint if it supports it.
Exceptions
std::out_of_range If given an invalid joint identifier.
See also
GetMotorSpeed(const World& world, JointID id)
SetTarget() [1/2]
void SetTarget (World & world, JointID id, Length2 value)
Sets the target point.
Exceptions
std::out_of_range If given an invalid joint identifier.
SetTarget() [2/2]
void SetTarget (World & world, JointID id, Length2 value) related
Sets the target point.
Exceptions
std::out_of_range If given an invalid joint identifier.
ShiftOrigin() [1/2]
bool ShiftOrigin (World & world, JointID id, Length2 value)
Shifts the origin of the identified joint.
Note
This only effects joints having points in world coordinates.
Exceptions
std::out_of_range If given an invalid joint identifier.
Referenced by playrho::d2::World::ShiftOrigin(), and playrho::d2::WorldImpl::ShiftOrigin().
ShiftOrigin() [2/2]
bool ShiftOrigin (World & world, JointID id, Length2 value) related
Shifts the origin of the identified joint.
Note
This only effects joints having points in world coordinates.
Exceptions
std::out_of_range If given an invalid joint identifier.