PlayRho: Decimal Unit Prefices
Decimal Unit Prefices
Decimal unit prefices in the metric system for denoting a multiple, or a fraction of, a unit.
Variables
constexpr auto playrho::Centi = Real(1e-2)
Centi- (1 x 10^-2).
constexpr auto playrho::Deci = Real(1e-1)
Deci- (1 x 10^-1).
constexpr auto playrho::Kilo = Real(1e3)
Kilo- (1 x 10^3).
constexpr auto playrho::Mega = Real(1e6)
Mega- (1 x 10^6).
constexpr auto playrho::Giga = Real(1e9)
Giga- (1 x 10^9).
constexpr auto playrho::Tera = Real(1e12)
Tera- (1 x 10^12).
constexpr auto playrho::Peta = Real(1e15)
Peta- (1 x 10^15).
constexpr auto playrho::Yotta = Real(1e24)
Yotta- (1 x 10^24).
Detailed Description
Decimal unit prefices in the metric system for denoting a multiple, or a fraction of, a unit.
Note
std::ratio doesn't necessarily support larger sizes like Yotta or bigger so floating-point literal notation is used instead.
See also
https://en.wikipedia.org/wiki/Metric_prefix
Variable Documentation
Centi
constexpr auto playrho::Centi = Real(1e-2) constexpr
Centi- (1 x 10^-2).
See also
https://en.wikipedia.org/wiki/Centi-
Referenced by playrho::operator""_cm().
Deci
constexpr auto playrho::Deci = Real(1e-1) constexpr
Deci- (1 x 10^-1).
See also
https://en.wikipedia.org/wiki/Deci-
Referenced by playrho::operator""_dm().
Giga
constexpr auto playrho::Giga = Real(1e9) constexpr
Giga- (1 x 10^9).
See also
https://en.wikipedia.org/wiki/Giga-
Referenced by playrho::operator""_Gm().
Kilo
constexpr auto playrho::Kilo = Real(1e3) constexpr
Kilo- (1 x 10^3).
See also
https://en.wikipedia.org/wiki/Kilo-
Referenced by playrho::operator""_g(), playrho::operator""_km(), playrho::operator""_kps(), playrho::operator""_Pg(), and playrho::operator""_Yg().
Mega
constexpr auto playrho::Mega = Real(1e6) constexpr
Mega- (1 x 10^6).
See also
https://en.wikipedia.org/wiki/Mega-
Referenced by playrho::operator""_Mm().
Peta
constexpr auto playrho::Peta = Real(1e15) constexpr
Peta- (1 x 10^15).
See also
https://en.wikipedia.org/wiki/Peta-
Referenced by playrho::operator""_Pg().
Tera
constexpr auto playrho::Tera = Real(1e12) constexpr
Tera- (1 x 10^12).
See also
https://en.wikipedia.org/wiki/Tera-
Yotta
constexpr auto playrho::Yotta = Real(1e24) constexpr
Yotta- (1 x 10^24).
See also
https://en.wikipedia.org/wiki/Yotta-
Referenced by playrho::operator""_Yg().