PlayRho: World Fixture Related Free Functions
World Fixture Related Free Functions
Collection of "free" functions related to fixtures within a World.
Functions
SizedRange< std::vector< FixtureID >::const_iterator > playrho::d2::GetFixturesForProxies (const World &world) noexcept
Gets the fixtures-for-proxies range for this world.
FixtureCounter playrho::d2::GetFixtureCount (const World &world) noexcept
Gets the count of fixtures in the given world.
FixtureID playrho::d2::CreateFixture (World &world, BodyID id, const Shape &shape, const FixtureConf &def=GetDefaultFixtureConf(), bool resetMassData=true)
Creates a fixture within the specified world.
bool playrho::d2::Destroy (World &world, FixtureID id, bool resetMassData=true)
Destroys the identified fixture.
Filter playrho::d2::GetFilterData (const World &world, FixtureID id)
Gets the filter data for the identified fixture.
void playrho::d2::SetFilterData (World &world, FixtureID id, const Filter &filter)
Sets the contact filtering data.
void playrho::d2::Refilter (World &world, FixtureID id)
Re-filter the fixture.
BodyID playrho::d2::GetBody (const World &world, FixtureID id)
Gets the identifier of the body associated with the identified fixture.
Transformation playrho::d2::GetTransformation (const World &world, FixtureID id)
Gets the transformation associated with the given fixture.
Shape playrho::d2::GetShape (const World &world, FixtureID id)
Gets the shape associated with the identified fixture.
Real playrho::d2::GetFriction (const World &world, FixtureID id)
Gets the coefficient of friction of the specified fixture.
Real playrho::d2::GetRestitution (const World &world, FixtureID id)
Gets the coefficient of restitution of the specified fixture.
void playrho::d2::SetSensor (World &world, FixtureID id, bool value)
Sets whether the fixture is a sensor or not.
bool playrho::d2::IsSensor (const World &world, FixtureID id)
Is the specified fixture a sensor (non-solid)?
AreaDensity playrho::d2::GetDensity (const World &world, FixtureID id)
Gets the density of this fixture.
const std::vector< FixtureProxy > & playrho::d2::GetProxies (const World &world, FixtureID id)
Gets the proxies of the identified fixture.
ChildCounter playrho::d2::GetProxyCount (const World &world, FixtureID id)
Gets the count of proxies of the identified fixture.
const FixtureProxy & playrho::d2::GetProxy (const World &world, FixtureID id, ChildCounter child)
Gets the specified proxy of the identified fixture.
MassData playrho::d2::GetMassData (const World &world, FixtureID id)
Gets the mass data for the identified fixture in the given world.
SizedRange< std::vector< FixtureID >::const_iterator > GetFixturesForProxies (const World &world) noexcept
Gets the fixtures-for-proxies range for this world.
FixtureCounter GetFixtureCount (const World &world) noexcept
Gets the count of fixtures in the given world.
FixtureID CreateFixture (World &world, BodyID id, const Shape &shape, const FixtureConf &def=GetDefaultFixtureConf(), bool resetMassData=true)
Creates a fixture within the specified world.
bool Destroy (World &world, FixtureID id, bool resetMassData=true)
Destroys the identified fixture.
Filter GetFilterData (const World &world, FixtureID id)
Gets the filter data for the identified fixture.
void SetFilterData (World &world, FixtureID id, const Filter &filter)
Sets the contact filtering data.
void Refilter (World &world, FixtureID id)
Re-filter the fixture.
BodyID GetBody (const World &world, FixtureID id)
Gets the identifier of the body associated with the identified fixture.
Transformation GetTransformation (const World &world, FixtureID id)
Gets the transformation associated with the given fixture.
Shape GetShape (const World &world, FixtureID id)
Gets the shape associated with the identified fixture.
Real GetFriction (const World &world, FixtureID id)
Gets the coefficient of friction of the specified fixture.
Real GetRestitution (const World &world, FixtureID id)
Gets the coefficient of restitution of the specified fixture.
void SetSensor (World &world, FixtureID id, bool value)
Sets whether the fixture is a sensor or not.
bool IsSensor (const World &world, FixtureID id)
Is the specified fixture a sensor (non-solid)?
const std::vector< FixtureProxy > & GetProxies (const World &world, FixtureID id)
Gets the proxies of the identified fixture.
ChildCounter GetProxyCount (const World &world, FixtureID id)
Gets the count of proxies of the identified fixture.
const FixtureProxy & GetProxy (const World &world, FixtureID id, ChildCounter child)
Gets the specified proxy of the identified fixture.
MassData GetMassData (const World &world, FixtureID id)
Gets the mass data for the identified fixture in the given world.
Detailed Description
Collection of "free" functions related to fixtures within a World.
This is a collection of non-member non-friend functions - also called "free" functions - that are related to fixtures within an instance of a World. Many are just "wrappers" to similarly named member functions but some are additional functionality built on those member functions. A benefit to using free functions that are now just wrappers, is that of helping to isolate your code from future changes that might occur to the underlying World member functions. Free functions in this sense are "cheap" abstractions. While using these incurs extra run-time overhead when compiled without any compiler optimizations enabled, enabling optimizations should entirely eliminate that overhead.
Note
The four basic categories of these functions are "CRUD": create, read, update, and delete.
See also
World, FixtureID.
https://en.wikipedia.org/wiki/Create,_read,_update_and_delete.
Function Documentation
CreateFixture() [1/2]
FixtureID CreateFixture (World & world, BodyID id, const Shape & shape, const FixtureConf & def = GetDefaultFixtureConf(), bool resetMassData = true)
Creates a fixture within the specified world.
Exceptions
WrongState if called while the world is "locked".
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp, WorldContact.cpp, and WorldFixture.cpp.
Referenced by playrho::d2::World::CreateFixture().
CreateFixture() [2/2]
FixtureID CreateFixture (World & world, BodyID id, const Shape & shape, const FixtureConf & def = GetDefaultFixtureConf(), bool resetMassData = true) related
Creates a fixture within the specified world.
Exceptions
WrongState if called while the world is "locked".
std::out_of_range If given an invalid body identifier.
Destroy() [1/2]
bool Destroy (World & world, FixtureID id, bool resetMassData = true)
Destroys the identified fixture.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid fixture identifier.
Destroy() [2/2]
bool Destroy (World & world, FixtureID id, bool resetMassData = true) related
Destroys the identified fixture.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid fixture identifier.
GetBody() [1/2]
BodyID GetBody (const World & world, FixtureID id)
Gets the identifier of the body associated with the identified fixture.
Exceptions
std::out_of_range If given an invalid fixture identifier.
Examples
World.cpp, WorldBody.cpp, and WorldFixture.cpp.
Referenced by playrho::d2::ComputeAABB(), playrho::d2::ComputeIntersectingAABB(), playrho::d2::WorldImpl::ComputeMassData(), playrho::d2::WorldImpl::CreateFixture(), playrho::d2::WorldImpl::DestroyFixtures(), playrho::d2::World::GetBody(), playrho::d2::GetTransformation(), playrho::d2::WorldImpl::SetEnabled(), playrho::d2::WorldImpl::SetMassData(), playrho::d2::WorldImpl::SetTransformation(), and playrho::d2::WorldImpl::SetType().
GetBody() [2/2]
BodyID GetBody (const World & world, FixtureID id) related
Gets the identifier of the body associated with the identified fixture.
Exceptions
std::out_of_range If given an invalid fixture identifier.
Examples
World.cpp.
GetDensity()
AreaDensity playrho::d2::GetDensity (const World & world, FixtureID id)
Gets the density of this fixture.
Returns
Non-negative density (in mass per area).
Exceptions
std::out_of_range If given an invalid fixture identifier.
Referenced by playrho::d2::World::GetDensity().
GetFilterData() [1/2]
Filter GetFilterData (const World & world, FixtureID id)
Gets the filter data for the identified fixture.
Exceptions
std::out_of_range If given an invalid fixture identifier.
Examples
WorldFixture.cpp.
Referenced by playrho::d2::World::GetFilterData().
GetFilterData() [2/2]
Filter GetFilterData (const World & world, FixtureID id) related
Gets the filter data for the identified fixture.
Exceptions
std::out_of_range If given an invalid fixture identifier.
GetFixtureCount() [1/2]
FixtureCounter GetFixtureCount (const World & world) noexcept
Gets the count of fixtures in the given world.
Exceptions
WrongState if called while the world is "locked".
GetFixtureCount() [2/2]
FixtureCounter GetFixtureCount (const World & world) related
Gets the count of fixtures in the given world.
Exceptions
WrongState if called while the world is "locked".
GetFixturesForProxies() [1/2]
SizedRange< std::vector< FixtureID >::const_iterator > GetFixturesForProxies (const World & world) noexcept
Gets the fixtures-for-proxies range for this world.
Provides insight on what fixtures have been queued for proxy processing during the next call to the world step method.
See also
Step.
Examples
WorldBody.cpp.
Referenced by playrho::d2::World::GetFixturesForProxies().
GetFixturesForProxies() [2/2]
SizedRange< std::vector< FixtureID >::const_iterator > GetFixturesForProxies (const World & world) related
Gets the fixtures-for-proxies range for this world.
Provides insight on what fixtures have been queued for proxy processing during the next call to the world step method.
See also
Step.
Examples
World.cpp.
GetFriction() [1/2]
Real GetFriction (const World & world, FixtureID id) inline
Gets the coefficient of friction of the specified fixture.
Returns
Value of 0 or higher.
Exceptions
std::out_of_range If given an invalid fixture identifier.
GetFriction() [2/2]
Real GetFriction (const World & world, FixtureID id) related
Gets the coefficient of friction of the specified fixture.
Returns
Value of 0 or higher.
Exceptions
std::out_of_range If given an invalid fixture identifier.
GetMassData() [1/2]
MassData GetMassData (const World & world, FixtureID id) inline
Gets the mass data for the identified fixture in the given world.
Exceptions
std::out_of_range If given an invalid fixture identifier.
GetMassData() [2/2]
MassData GetMassData (const World & world, FixtureID id) related
Gets the mass data for the identified fixture in the given world.
Exceptions
std::out_of_range If given an invalid fixture identifier.
GetProxies() [1/2]
const std::vector< FixtureProxy > & GetProxies (const World & world, FixtureID id)
Gets the proxies of the identified fixture.
Exceptions
std::out_of_range If given an invalid fixture identifier.
Referenced by playrho::d2::World::GetProxies(), playrho::d2::GetProxy(), and playrho::d2::GetProxyCount().
GetProxies() [2/2]
const std::vector< FixtureProxy > & GetProxies (const World & world, FixtureID id) related
Gets the proxies of the identified fixture.
Exceptions
std::out_of_range If given an invalid fixture identifier.
GetProxy() [1/2]
const FixtureProxy & GetProxy (const World & world, FixtureID id, ChildCounter child)
Gets the specified proxy of the identified fixture.
Exceptions
std::out_of_range If given an invalid fixture identifier.
Examples
WorldFixture.cpp.
GetProxy() [2/2]
const FixtureProxy & GetProxy (const World & world, FixtureID id, ChildCounter child) related
Gets the specified proxy of the identified fixture.
Exceptions
std::out_of_range If given an invalid fixture identifier.
GetProxyCount() [1/2]
ChildCounter GetProxyCount (const World & world, FixtureID id) related
Gets the count of proxies of the identified fixture.
Exceptions
std::out_of_range If given an invalid fixture identifier.
GetProxyCount() [2/2]
ChildCounter GetProxyCount (const World & world, FixtureID id) inline
Gets the count of proxies of the identified fixture.
Exceptions
std::out_of_range If given an invalid fixture identifier.
Examples
WorldBody.cpp, and WorldFixture.cpp.
GetRestitution() [1/2]
Real GetRestitution (const World & world, FixtureID id) related
Gets the coefficient of restitution of the specified fixture.
Exceptions
std::out_of_range If given an invalid fixture identifier.
GetRestitution() [2/2]
Real GetRestitution (const World & world, FixtureID id) inline
Gets the coefficient of restitution of the specified fixture.
Exceptions
std::out_of_range If given an invalid fixture identifier.
GetShape() [1/2]
Shape GetShape (const World & world, FixtureID id)
Gets the shape associated with the identified fixture.
Exceptions
std::out_of_range If given an invalid fixture identifier.
Examples
WorldBody.cpp, and WorldFixture.cpp.
Referenced by playrho::d2::ComputeAABB(), playrho::d2::ComputeIntersectingAABB(), playrho::d2::GetFriction(), playrho::d2::GetMassData(), playrho::d2::GetRestitution(), playrho::d2::World::GetShape(), playrho::d2::GetWorldManifold(), playrho::d2::RayCast(), and playrho::d2::TestPoint().
GetShape() [2/2]
Shape GetShape (const World & world, FixtureID id) related
Gets the shape associated with the identified fixture.
Exceptions
std::out_of_range If given an invalid fixture identifier.
GetTransformation() [1/2]
Transformation GetTransformation (const World & world, FixtureID id)
Gets the transformation associated with the given fixture.
Warning
Behavior is undefined if the fixture doesn't have an associated body - i.e. behavior is undefined if the fixture has nullptr as its associated body.
Exceptions
std::out_of_range If given an invalid fixture identifier.
GetTransformation() [2/2]
Transformation GetTransformation (const World & world, FixtureID id) related
Gets the transformation associated with the given fixture.
Warning
Behavior is undefined if the fixture doesn't have an associated body - i.e. behavior is undefined if the fixture has nullptr as its associated body.
Exceptions
std::out_of_range If given an invalid fixture identifier.
IsSensor() [1/2]
bool IsSensor (const World & world, FixtureID id)
Is the specified fixture a sensor (non-solid)?
Returns
the true if the fixture is a sensor.
Exceptions
std::out_of_range If given an invalid fixture identifier.
See also
SetSensor.
Referenced by playrho::d2::World::IsSensor(), and playrho::d2::WorldImpl::UpdateContactTOIs().
IsSensor() [2/2]
bool IsSensor (const World & world, FixtureID id) related
Is the specified fixture a sensor (non-solid)?
Returns
the true if the fixture is a sensor.
Exceptions
std::out_of_range If given an invalid fixture identifier.
See also
SetSensor.
Refilter() [1/2]
void Refilter (World & world, FixtureID id)
Re-filter the fixture.
Note
Call this if you want to establish collision that was previously disabled by ShouldCollide(const Fixture&, const Fixture&).
Exceptions
std::out_of_range If given an invalid fixture identifier.
See also
bool ShouldCollide(const Fixture& fixtureA, const Fixture& fixtureB) noexcept
Referenced by playrho::d2::World::Refilter(), and playrho::d2::WorldImpl::SetFilterData().
Refilter() [2/2]
void Refilter (World & world, FixtureID id) related
Re-filter the fixture.
Note
Call this if you want to establish collision that was previously disabled by ShouldCollide(const Fixture&, const Fixture&).
Exceptions
std::out_of_range If given an invalid fixture identifier.
See also
bool ShouldCollide(const Fixture& fixtureA, const Fixture& fixtureB) noexcept
SetFilterData() [1/2]
void SetFilterData (World & world, FixtureID id, const Filter & filter)
Sets the contact filtering data.
Note
This won't update contacts until the next time step when either parent body is speedable and awake.
This automatically calls Refilter.
Exceptions
std::out_of_range If given an invalid fixture identifier.
Examples
WorldFixture.cpp.
Referenced by playrho::d2::World::SetFilterData().
SetFilterData() [2/2]
void SetFilterData (World & world, FixtureID id, const Filter & filter) related
Sets the contact filtering data.
Note
This won't update contacts until the next time step when either parent body is speedable and awake.
This automatically calls Refilter.
Exceptions
std::out_of_range If given an invalid fixture identifier.
SetSensor() [1/2]
void SetSensor (World & world, FixtureID id, bool value)
Sets whether the fixture is a sensor or not.
Exceptions
std::out_of_range If given an invalid fixture identifier.
See also
IsSensor.
Examples
WorldFixture.cpp.
Referenced by playrho::d2::World::SetSensor().
SetSensor() [2/2]
void SetSensor (World & world, FixtureID id, bool value) related
Sets whether the fixture is a sensor or not.
Exceptions
std::out_of_range If given an invalid fixture identifier.
See also
IsSensor.
Examples
World.cpp.