PlayRho: Mathematical Functions
Mathematical Functions
Functions for common mathematical operations.
Functions
template<typename T , typename U >
constexpr U playrho::Secant (T target, U a1, T s1, U a2, T s2) noexcept
Secant method.
template<typename T >
constexpr T playrho::Bisect (T a1, T a2) noexcept
Bisection method.
template<typename T >
constexpr bool playrho::IsOdd (T val) noexcept
Is-odd.
template<class TYPE >
constexpr auto playrho::Square (TYPE t) noexcept
Squares the given value.
template<typename T >
std::enable_if< std::is_arithmetic< T >::value, T >::type playrho::Sqrt (T t)
Square root's the given value.
template<typename T >
std::enable_if< std::is_arithmetic< T >::value, T >::type playrho::Hypot (T x, T y)
Computes the square root of the sum of the squares.
template<typename T >
std::enable_if< std::is_arithmetic< T >::value, bool >::type playrho::IsNormal (T arg)
Determines if the given argument is normal.
template<typename T >
std::enable_if< std::is_arithmetic< T >::value, bool >::type playrho::IsNan (T arg)
Gets whether the given value is not-a-number.
template<typename T >
std::enable_if< std::is_arithmetic< T >::value, bool >::type playrho::IsFinite (T arg)
Gets whether the given value is finite.
template<typename T >
std::enable_if< std::is_arithmetic< T >::value, T >::type playrho::Round (T arg)
Rounds the given value.
template<typename T >
std::enable_if< std::is_arithmetic< T >::value, T >::type playrho::Trunc (T arg)
Truncates the given value.
template<typename T >
std::enable_if< std::is_arithmetic< T >::value, bool >::type playrho::SignBit (T value) noexcept
Determines whether the given value is negative.
template<typename T >
T playrho::NextAfter (T from, T to)
Gets the next representable value after the given from value and going towards the to value.
template<typename T >
std::enable_if< std::is_arithmetic< T >::value, T >::type playrho::Cos (T arg)
Computes the cosine of the argument.
template<typename T >
std::enable_if< std::is_arithmetic< T >::value, T >::type playrho::Sin (T arg)
Computes the sine of the argument.
template<typename T >
auto playrho::Atan2 (T y, T x)
Computes the arc-tangent of the given y and x values.
template<typename T >
auto playrho::Average (Span< const T > span)
Computes the average of the given values.
template<typename T >
std::enable_if< std::is_arithmetic< T >::value, T >::type playrho::RoundOff (T value, unsigned precision=100000)
Computes the rounded value of the given value.
Vec2 playrho::RoundOff (Vec2 value, std::uint32_t precision=100000)
Computes the rounded value of the given value.
constexpr Vec2 playrho::GetVec2 (const UnitVec2 value)
Gets a Vec2 representation of the given value.
template<typename T >
constexpr std::enable_if< std::is_arithmetic< T >::value, bool >::type playrho::AlmostZero (T value)
Gets whether a given value is almost zero.
template<typename T >
constexpr std::enable_if< std::is_floating_point< T >::value, bool >::type playrho::AlmostEqual (T x, T y, int ulp=2)
Determines whether the given two values are "almost equal".
template<typename T >
std::enable_if< std::is_floating_point< T >::value, T >::type playrho::ModuloViaFmod (T dividend, T divisor) noexcept
Modulo operation using std::fmod.
template<typename T >
auto playrho::ModuloViaTrunc (T dividend, T divisor) noexcept
Modulo operation using std::trunc.
Angle playrho::GetNormalized (Angle value) noexcept
Gets the "normalized" value of the given angle.
Position playrho::GetNormalized (const Position &val) noexcept
Gets the "normalized" position.
Sweep playrho::GetNormalized (Sweep sweep) noexcept
Gets a sweep with the given sweeps's angles normalized.
Angle playrho::GetAngle (const UnitVec2 value)
Gets the angle of the given unit vector.
template<class T >
Angle playrho::GetAngle (const Vector2< T > value)
Gets the angle.
template<typename T >
constexpr auto playrho::GetMagnitudeSquared (T value) noexcept
Gets the square of the magnitude of the given iterable value.
template<typename T >
auto playrho::GetMagnitude (T value)
Gets the magnitude of the given value.
template<typename T1 , typename T2 >
constexpr auto playrho::Dot (const T1 a, const T2 b) noexcept
Performs the dot product on two vectors (A and B).
template<class T1 , class T2 , std::enable_if_t< std::tuple_size< T1 >::value==2 &&std::tuple_size< T2 >::value==2, int > = 0>
constexpr auto playrho::Cross (T1 a, T2 b) noexcept
Performs the 2-element analog of the cross product of two vectors.
template<typename T , typename U >
constexpr auto playrho::Solve (const Matrix22< U > mat, const Vector2< T > b) noexcept
Solves A * x = b, where b is a column vector.
template<class IN_TYPE >
constexpr auto playrho::Invert (const Matrix22< IN_TYPE > value) noexcept
Inverts the given value.
constexpr Vec3 playrho::Solve33 (const Mat33 &mat, const Vec3 b) noexcept
Solves A * x = b, where b is a column vector.
template<typename T >
constexpr T playrho::Solve22 (const Mat33 &mat, const T b) noexcept
Solves A * x = b, where b is a column vector.
constexpr Mat33 playrho::GetInverse22 (const Mat33 &value) noexcept
Gets the inverse of the given matrix as a 2-by-2.
constexpr Mat33 playrho::GetSymInverse33 (const Mat33 &value) noexcept
Gets the symmetric inverse of this matrix as a 3-by-3.
template<class T >
constexpr auto playrho::GetRevPerpendicular (const T vector) noexcept
Gets a vector counter-clockwise (reverse-clockwise) perpendicular to the given vector.
template<class T >
constexpr auto playrho::GetFwdPerpendicular (const T vector) noexcept
Gets a vector clockwise (forward-clockwise) perpendicular to the given vector.
constexpr Vec2 playrho::Transform (const Vec2 v, const Mat22 &A) noexcept
Multiply a matrix times a vector. If a rotation matrix is provided, then this transforms the vector from one frame to another.
constexpr Vec2 playrho::InverseTransform (const Vec2 v, const Mat22 &A) noexcept
Multiply a matrix transpose times a vector. If a rotation matrix is provided, then this transforms the vector from one frame to another (inverse transform).
template<class T , LoValueCheck lo, HiValueCheck hi>
constexpr Vector2< T > playrho::operator* (BoundedValue< T, lo, hi > s, UnitVec2 u) noexcept
Multiplication operator.
template<class T >
constexpr Vector2< T > playrho::operator* (const T s, const UnitVec2 u) noexcept
Multiplication operator.
template<class T , LoValueCheck lo, HiValueCheck hi>
constexpr Vector2< T > playrho::operator* (UnitVec2 u, BoundedValue< T, lo, hi > s) noexcept
Multiplication operator.
template<class T >
constexpr Vector2< T > playrho::operator* (const UnitVec2 u, const T s) noexcept
Multiplication operator.
constexpr Vec2 playrho::operator/ (const UnitVec2 u, const UnitVec2::value_type s) noexcept
Division operator.
constexpr Mat22 playrho::Mul (const Mat22 &A, const Mat22 &B) noexcept
Computes A * B.
constexpr Mat22 playrho::MulT (const Mat22 &A, const Mat22 &B) noexcept
Computes A^T * B.
constexpr Vec3 playrho::Transform (const Vec3 &v, const Mat33 &A) noexcept
Multiplies a matrix by a vector.
template<class T >
constexpr auto playrho::Rotate (const Vector2< T > vector, const UnitVec2 &angle) noexcept
Rotates a vector by a given angle.
template<class T >
constexpr auto playrho::InverseRotate (const Vector2< T > vector, const UnitVec2 &angle) noexcept
Inverse rotates a vector.
constexpr Length2 playrho::Transform (const Length2 v, const Transformation xfm) noexcept
Transforms the given 2-D vector with the given transformation.
constexpr Length2 playrho::InverseTransform (const Length2 v, const Transformation T) noexcept
Inverse transforms the given 2-D vector with the given transformation.
constexpr Transformation playrho::Mul (const Transformation &A, const Transformation &B) noexcept
Multiplies a given transformation by another given transformation.
constexpr Transformation playrho::MulT (const Transformation &A, const Transformation &B) noexcept
Inverse multiplies a given transformation by another given transformation.
template<>
Vec2 playrho::Abs (Vec2 a)
Gets the absolute value of the given value.
template<>
UnitVec2 playrho::Abs (UnitVec2 a)
Gets the absolute value of the given value.
Mat22 playrho::Abs (const Mat22 &A)
Gets the absolute value of the given value.
template<typename T >
constexpr T playrho::Clamp (T value, T low, T high) noexcept
Clamps the given value within the given range (inclusive).
std::uint64_t playrho::NextPowerOfTwo (std::uint64_t x)
Gets the next largest power of 2.
constexpr Transformation playrho::GetTransformation (const Length2 ctr, const UnitVec2 rot, const Length2 localCtr) noexcept
Gets the transformation for the given values.
Transformation playrho::GetTransformation (const Position pos, const Length2 local_ctr) noexcept
Gets the transformation for the given values.
Transformation playrho::GetTransformation (const Sweep &sweep, const Real beta) noexcept
Gets the interpolated transform at a specific time.
Transformation playrho::GetTransform0 (const Sweep &sweep) noexcept
Gets the transform at "time" zero.
Transformation playrho::GetTransform1 (const Sweep &sweep) noexcept
Gets the transform at "time" one.
Real playrho::Normalize (Vec2 &vector)
Converts the given vector into a unit vector and returns its original length.
LinearVelocity2 playrho::GetContactRelVelocity (const Velocity velA, const Length2 relA, const Velocity velB, const Length2 relB) noexcept
Gets the contact relative velocity.
Length2 playrho::ComputeCentroid (const Span< const Length2 > &vertices)
Computes the centroid of a counter-clockwise array of 3 or more vertices.
template<typename T >
constexpr T playrho::GetModuloNext (T value, T count) noexcept
Gets the modulo next value.
template<typename T >
constexpr T playrho::GetModuloPrev (T value, T count) noexcept
Gets the modulo previous value.
Angle playrho::GetDelta (Angle a1, Angle a2) noexcept
Gets the shortest angular distance to go from angle 1 to angle 2.
constexpr Angle playrho::GetRevRotationalAngle (Angle a1, Angle a2) noexcept
Gets the reverse (counter) clockwise rotational angle to go from angle 1 to angle 2.
template<class T >
UnitVec2 playrho::GetUnitVector (Vector2< T > value, UnitVec2 fallback=UnitVec2::GetDefaultFallback())
Gets the unit vector for the given value.
std::vector< Length2 > playrho::GetCircleVertices (Length radius, unsigned slices, Angle start=0_deg, Real turns=Real{1})
Gets the vertices for a circle described by the given parameters.
NonNegative< Area > playrho::GetAreaOfCircle (Length radius)
Gets the area of a cirlce.
NonNegative< Area > playrho::GetAreaOfPolygon (Span< const Length2 > vertices)
Gets the area of a polygon.
SecondMomentOfArea playrho::GetPolarMoment (Span< const Length2 > vertices)
Gets the polar moment of the area enclosed by the given vertices.
Sweep GetNormalized (Sweep sweep) noexcept
Gets a sweep with the given sweeps's angles normalized.
Detailed Description
Functions for common mathematical operations.
These are non-member non-friend functions for mathematical operations especially those with mixed input and output types.
Function Documentation
AlmostZero()
template<typename T > constexpr std::enable_if<std::is_arithmetic<T>::value, bool>::type playrho::AlmostZero (T value)
Gets whether a given value is almost zero.
An almost zero value is "subnormal". Dividing by these values can lead to odd results like a divide by zero trap occurring.
Returns
true if the given value is almost zero, false otherwise.
Atan2()
template<typename T > auto playrho::Atan2 (T y, T x) inline
Computes the arc-tangent of the given y and x values.
Returns
Normalized angle - an angle between -Pi and Pi inclusively.
See also
http://en.cppreference.com/w/cpp/numeric/math/atan2
Referenced by playrho::GetAngle().
Bisect()
template<typename T > constexpr T playrho::Bisect (T a1, T a2) inline noexcept
Bisection method.
See also
https://en.wikipedia.org/wiki/Bisection_method
Referenced by playrho::GetToiViaSat().
Clamp()
template<typename T > constexpr T playrho::Clamp (T value, T low, T high) inline noexcept
Clamps the given value within the given range (inclusive).
Parameters
value Value to clamp.
low Lowest value to return or NaN to keep the low-end unbounded.
high Highest value to return or NaN to keep the high-end unbounded.
Referenced by playrho::RopeJoint::SolvePositionConstraints(), playrho::DistanceJoint::SolvePositionConstraints(), playrho::PrismaticJoint::SolvePositionConstraints(), playrho::RevoluteJoint::SolvePositionConstraints(), playrho::FrictionJoint::SolveVelocityConstraints(), playrho::MotorJoint::SolveVelocityConstraints(), playrho::WheelJoint::SolveVelocityConstraints(), playrho::PrismaticJoint::SolveVelocityConstraints(), and playrho::RevoluteJoint::SolveVelocityConstraints().
ComputeCentroid()
Length2 playrho::ComputeCentroid (const Span< const Length2 > & vertices)
Computes the centroid of a counter-clockwise array of 3 or more vertices.
Note
Behavior is undefined if there are less than 3 vertices or the vertices don't go counter-clockwise.
Referenced by playrho::PolygonShape::Set().
Cross()
template<class T1 , class T2 , std::enable_if_t< std::tuple_size< T1 >::value==2 &&std::tuple_size< T2 >::value==2, int > = 0> constexpr auto playrho::Cross (T1 a, T2 b) noexcept
Performs the 2-element analog of the cross product of two vectors.
Cross-products the given two values.
Defined as the result of: (a.x * b.y) - (a.y * b.x).
Note
This operation is dimension squashing. I.e. A cross of a 2-D length by a 2-D unit vector results in a 1-D length value.
The unit of the result is the 1-D product of the inputs.
This operation is anti-commutative. I.e. Cross(a, b) == -Cross(b, a).
The result will be 0 if any of the following are true: vector A or vector B has a length of zero; vectors A and B point in the same direction; or vectors A and B point in exactly opposite direction of each other.
The result will be positive if: neither vector A nor B has a length of zero; and vector B is at an angle from vector A of greater than 0 and less than 180 degrees (counter-clockwise from A being a positive angle).
Result will be negative if: neither vector A nor B has a length of zero; and vector B is at an angle from vector A of less than 0 and greater than -180 degrees (clockwise from A being a negative angle).
The absolute value of the result is the area of the parallelogram formed by the vectors A and B.
See also
https://en.wikipedia.org/wiki/Cross_product
Parameters
a Value A of a 2-element type.
b Value B of a 2-element type.
Returns
Cross product of the two values.
Note
This operation is anti-commutative. I.e. Cross(a, b) == -Cross(b, a).
See also
https://en.wikipedia.org/wiki/Cross_product
Parameters
a Value A of a 3-element type.
b Value B of a 3-element type.
Returns
Cross product of the two values.
Referenced by playrho::ApplyForce(), playrho::ApplyLinearImpulse(), playrho::Simplex::CalcMetric(), playrho::Simplex::CalcSearchDirection(), playrho::ComputeCentroid(), playrho::Simplex::Get(), playrho::GetConvexHullAsVector(), playrho::GetMassData(), playrho::VelocityConstraint::GetPoint(), playrho::GetPolarMoment(), playrho::GetSymInverse33(), playrho::FrictionJoint::InitVelocityConstraints(), playrho::WeldJoint::InitVelocityConstraints(), playrho::RopeJoint::InitVelocityConstraints(), playrho::PulleyJoint::InitVelocityConstraints(), playrho::MotorJoint::InitVelocityConstraints(), playrho::DistanceJoint::InitVelocityConstraints(), playrho::MouseJoint::InitVelocityConstraints(), playrho::WheelJoint::InitVelocityConstraints(), playrho::PrismaticJoint::InitVelocityConstraints(), playrho::RevoluteJoint::InitVelocityConstraints(), playrho::Invert(), playrho::RayCast(), playrho::SetForce(), playrho::Solve(), playrho::Solve33(), playrho::RopeJoint::SolvePositionConstraints(), playrho::WeldJoint::SolvePositionConstraints(), playrho::PulleyJoint::SolvePositionConstraints(), playrho::DistanceJoint::SolvePositionConstraints(), playrho::WheelJoint::SolvePositionConstraints(), playrho::PrismaticJoint::SolvePositionConstraints(), playrho::RevoluteJoint::SolvePositionConstraints(), playrho::FrictionJoint::SolveVelocityConstraints(), playrho::RopeJoint::SolveVelocityConstraints(), playrho::WeldJoint::SolveVelocityConstraints(), playrho::PulleyJoint::SolveVelocityConstraints(), playrho::MotorJoint::SolveVelocityConstraints(), playrho::DistanceJoint::SolveVelocityConstraints(), playrho::MouseJoint::SolveVelocityConstraints(), playrho::RevoluteJoint::SolveVelocityConstraints(), and playrho::Validate().
Dot()
template<typename T1 , typename T2 > constexpr auto playrho::Dot (const T1 a, const T2 b) noexcept
Performs the dot product on two vectors (A and B).
The dot product of two vectors is defined as: the magnitude of vector A, multiplied by, the magnitude of vector B, multiplied by, the cosine of the angle between the two vectors (A and B). Thus the dot product of two vectors is a value ranging between plus and minus the magnitudes of each vector times each other. The middle value of 0 indicates that two vectors are perpendicular to each other (at an angle of +/- 90 degrees from each other).
Note
This operation is commutative. I.e. Dot(a, b) == Dot(b, a).
If A and B are the same vectors, GetMagnitudeSquared(Vec2) returns the same value using effectively one less input parameter.
This is similar to the std::inner_product standard library algorithm except benchmark tests suggest this implementation is faster at least for Vec2 like instances.
See also
https://en.wikipedia.org/wiki/Dot_product
Parameters
a Vector A.
b Vector B.
Returns
Dot product of the vectors (0 means the two vectors are perpendicular).
Referenced by playrho::ClipSegmentToLine(), playrho::SeparationFinder::EvaluateForFaceA(), playrho::SeparationFinder::EvaluateForFaceB(), playrho::SeparationFinder::EvaluateForPoints(), playrho::SeparationFinder::FindMinSeparationForFaceA(), playrho::SeparationFinder::FindMinSeparationForFaceB(), playrho::SeparationFinder::FindMinSeparationForPoints(), playrho::SeparationFinder::Get(), playrho::Simplex::Get(), playrho::GetJointTranslation(), playrho::GetLinearVelocity(), playrho::GetMaxSeparation4x4(), playrho::VelocityConstraint::GetPoint(), playrho::GetSupportIndex(), playrho::GetSymInverse33(), playrho::WheelJoint::InitVelocityConstraints(), playrho::PrismaticJoint::InitVelocityConstraints(), playrho::InverseTransform(), playrho::MulT(), playrho::RayCast(), playrho::Solve33(), playrho::WheelJoint::SolvePositionConstraints(), playrho::PrismaticJoint::SolvePositionConstraints(), playrho::RopeJoint::SolveVelocityConstraints(), playrho::GearJoint::SolveVelocityConstraints(), playrho::PulleyJoint::SolveVelocityConstraints(), playrho::DistanceJoint::SolveVelocityConstraints(), playrho::WheelJoint::SolveVelocityConstraints(), playrho::PrismaticJoint::SolveVelocityConstraints(), and playrho::TestPoint().
GetAngle()
template<class T > Angle playrho::GetAngle (const Vector2< T > value) inline
Gets the angle.
Returns
Angular value in the range of -Pi to +Pi radians.
GetAreaOfPolygon()
NonNegative< Area > playrho::GetAreaOfPolygon (Span< const Length2 > vertices)
Gets the area of a polygon.
Note
This function is valid for any non-self-intersecting (simple) polygon, which can be convex or concave.
Winding order doesn't matter.
GetContactRelVelocity()
LinearVelocity2 playrho::GetContactRelVelocity (const Velocity velA, const Length2 relA, const Velocity velB, const Length2 relB) inline noexcept
Gets the contact relative velocity.
Note
If relA and relB are the zero vectors, the resulting value is simply velB.linear - velA.linear.
Referenced by playrho::VelocityConstraint::GetPoint().
GetDelta()
Angle playrho::GetDelta (Angle a1, Angle a2) noexcept
Gets the shortest angular distance to go from angle 1 to angle 2.
This gets the angle to rotate angle 1 by in order to get to angle 2 with the least amount of rotation.
Returns
Angle between -Pi and Pi radians inclusively.
See also
GetNormalized
GetFwdPerpendicular()
template<class T > constexpr auto playrho::GetFwdPerpendicular (const T vector) inline noexcept
Gets a vector clockwise (forward-clockwise) perpendicular to the given vector.
This takes a vector of form (x, y) and returns the vector (y, -x).
Parameters
vector Vector to return a clockwise perpendicular equivalent for.
Returns
A clockwise 90-degree rotation of the given vector.
See also
GetRevPerpendicular.
Referenced by playrho::MultiShape::AddConvexHull(), playrho::Simplex::CalcSearchDirection(), playrho::SeparationFinder::Get(), playrho::VelocityConstraint::GetTangent(), playrho::EdgeShape::Set(), and playrho::PolygonShape::Set().
GetInverse22()
constexpr Mat33 playrho::GetInverse22 (const Mat33 & value) inline noexcept
Gets the inverse of the given matrix as a 2-by-2.
Returns
Zero matrix if singular.
Referenced by playrho::WeldJoint::InitVelocityConstraints().
GetMagnitude()
template<typename T > auto playrho::GetMagnitude (T value) inline
Gets the magnitude of the given value.
Note
Works for any type for which GetMagnitudeSquared also works.
Referenced by playrho::GetCentripetalForce(), playrho::GetCurrentLengthA(), playrho::GetCurrentLengthB(), playrho::GetMassData(), playrho::ChainShape::GetMassData(), playrho::Normalize(), and playrho::WeldJoint::SolvePositionConstraints().
GetMagnitudeSquared()
template<typename T > constexpr auto playrho::GetMagnitudeSquared (T value) inline noexcept
Gets the square of the magnitude of the given iterable value.
Note
For performance, use this instead of GetMagnitude(T value) (if possible).
Returns
Non-negative value.
Referenced by playrho::CalcGravitationalAcceleration(), playrho::Simplex::CalcMetric(), playrho::Distance(), playrho::VertexSet::find(), playrho::FindClosestBody(), playrho::GetConvexHullAsVector(), playrho::GetLocalRotInertia(), playrho::GetMagnitude(), playrho::GetMassData(), playrho::GetToiViaSat(), playrho::GetVelocity(), playrho::IsUnderActive(), playrho::RayCast(), playrho::Body::ResetMassData(), playrho::Body::SetMassData(), playrho::RevoluteJoint::SolvePositionConstraints(), playrho::FrictionJoint::SolveVelocityConstraints(), playrho::MotorJoint::SolveVelocityConstraints(), playrho::MouseJoint::SolveVelocityConstraints(), playrho::TestOverlap(), playrho::TestPoint(), and playrho::Contact::Update().
GetNormalized() [1/4]
Angle playrho::GetNormalized (Angle value) inline noexcept
Gets the "normalized" value of the given angle.
Returns
Angle between -Pi and Pi radians inclusively where 0 represents the positive X-axis.
See also
Atan2
Referenced by playrho::CalcToi(), playrho::GetDelta(), and playrho::GetNormalized().
GetNormalized() [2/4]
Position playrho::GetNormalized (const Position & val) inline noexcept
Gets the "normalized" position.
Enforces a wrap-around of one rotation on the angular position.
Note
Use to prevent unbounded angles in positions.
GetNormalized() [3/4]
Sweep GetNormalized (Sweep sweep) related
Gets a sweep with the given sweeps's angles normalized.
Parameters
sweep Sweep to return with its angles normalized.
Returns
Sweep with its pos0 angle to be between -2 pi and 2 pi and its pos1 angle reduced by the amount pos0's angle was reduced by.
GetNormalized() [4/4]
Sweep GetNormalized (Sweep sweep) inline noexcept
Gets a sweep with the given sweeps's angles normalized.
Parameters
sweep Sweep to return with its angles normalized.
Returns
Sweep with its pos0 angle to be between -2 pi and 2 pi and its pos1 angle reduced by the amount pos0's angle was reduced by.
GetPolarMoment()
SecondMomentOfArea playrho::GetPolarMoment (Span< const Length2 > vertices)
Gets the polar moment of the area enclosed by the given vertices.
Warning
Behavior is undefined if given collection has less than 3 vertices.
Parameters
vertices Collection of three or more vertices.
Referenced by playrho::GetMassData().
GetRevPerpendicular()
template<class T > constexpr auto playrho::GetRevPerpendicular (const T vector) inline noexcept
Gets a vector counter-clockwise (reverse-clockwise) perpendicular to the given vector.
This takes a vector of form (x, y) and returns the vector (-y, x).
Parameters
vector Vector to return a counter-clockwise perpendicular equivalent for.
Returns
A counter-clockwise 90-degree rotation of the given vector.
See also
GetFwdPerpendicular.
Referenced by playrho::Simplex::CalcSearchDirection(), playrho::GetContactRelVelocity(), playrho::GetLinearVelocity(), playrho::GetLinearVelocityFromWorldPoint(), playrho::GetMassData(), playrho::RayCast(), playrho::Body::ResetMassData(), playrho::Body::SetMassData(), playrho::FrictionJoint::SolveVelocityConstraints(), playrho::RopeJoint::SolveVelocityConstraints(), playrho::WeldJoint::SolveVelocityConstraints(), playrho::PulleyJoint::SolveVelocityConstraints(), playrho::MotorJoint::SolveVelocityConstraints(), playrho::DistanceJoint::SolveVelocityConstraints(), playrho::MouseJoint::SolveVelocityConstraints(), and playrho::RevoluteJoint::SolveVelocityConstraints().
GetRevRotationalAngle()
constexpr Angle playrho::GetRevRotationalAngle (Angle a1, Angle a2) inline noexcept
Gets the reverse (counter) clockwise rotational angle to go from angle 1 to angle 2.
Returns
Angular rotation in the counter clockwise direction to go from angle 1 to angle 2.
GetSymInverse33()
constexpr Mat33 playrho::GetSymInverse33 (const Mat33 & value) inline noexcept
Gets the symmetric inverse of this matrix as a 3-by-3.
Returns
Zero matrix if singular.
Referenced by playrho::WeldJoint::InitVelocityConstraints().
GetTransform0()
Transformation playrho::GetTransform0 (const Sweep & sweep) inline noexcept
Gets the transform at "time" zero.
Note
This is like calling GetTransformation(sweep, 0), except more efficiently.
See also
GetTransformation(const Sweep& sweep, Real beta).
Parameters
sweep Sweep data to get the transform from.
Returns
Transformation of the given sweep at time zero.
Referenced by playrho::World::SetType(), playrho::World::SolveReg(), playrho::World::SolveToi(), and playrho::World::SynchronizeProxies().
GetTransform1()
Transformation playrho::GetTransform1 (const Sweep & sweep) inline noexcept
Gets the transform at "time" one.
Note
This is like calling GetTransformation(sweep, 1.0), except more efficiently.
See also
GetTransformation(const Sweep& sweep, Real beta).
Parameters
sweep Sweep data to get the transform from.
Returns
Transformation of the given sweep at time one.
Referenced by playrho::Body::Advance(), and playrho::BodyAtty::Restore().
GetTransformation()
Transformation playrho::GetTransformation (const Sweep & sweep, const Real beta) inline noexcept
Gets the interpolated transform at a specific time.
Parameters
sweep Sweep data to get the transform from.
beta Time factor in [0,1], where 0 indicates alpha0.
Returns
Transformation of the given sweep at the specified time.
GetUnitVector()
template<class T > UnitVec2 playrho::GetUnitVector (Vector2< T > value, UnitVec2 fallback = UnitVec2::GetDefaultFallback()) inline
Gets the unit vector for the given value.
Parameters
value Value to get the unit vector for.
fallback Fallback unit vector value to use in case a unit vector can't effectively be calculated from the given value.
Returns
value divided by its length if length not almost zero otherwise invalid value.
See also
AlmostEqual.
Referenced by playrho::MultiShape::AddConvexHull(), playrho::CalcGravitationalAcceleration(), playrho::SeparationFinder::Get(), playrho::GetMassData(), playrho::PulleyJoint::InitVelocityConstraints(), playrho::RayCast(), playrho::EdgeShape::Set(), playrho::PolygonShape::Set(), playrho::FrictionJoint::SolveVelocityConstraints(), playrho::MotorJoint::SolveVelocityConstraints(), and playrho::MouseJoint::SolveVelocityConstraints().
InverseRotate()
template<class T > constexpr auto playrho::InverseRotate (const Vector2< T > vector, const UnitVec2 & angle) inline noexcept
Inverse rotates a vector.
This is the inverse of rotating a vector - it undoes what rotate does. I.e. this effectively subtracts from the angle of the given vector the angle that's expressed by the angle parameter.
Parameters
vector Vector to reverse rotate.
angle Expresses the angle to reverse rotate the given vector by.
See also
Rotate.
Referenced by playrho::Distance(), playrho::SeparationFinder::FindMinSeparationForFaceA(), playrho::SeparationFinder::FindMinSeparationForFaceB(), playrho::SeparationFinder::FindMinSeparationForPoints(), playrho::GetLocalVector(), playrho::InverseTransform(), and playrho::MulT().
InverseTransform()
constexpr Length2 playrho::InverseTransform (const Length2 v, const Transformation T) inline noexcept
Inverse transforms the given 2-D vector with the given transformation.
Inverse translate and rotate the given 2-D vector according to the translation and rotation defined by the given transformation.
Note
Passing the output of this function to Transform (with the same transformation again) will result in the original vector being returned.
See also
Transform.
Parameters
v 2-D vector to inverse transform (inverse translate and inverse rotate).
T Transformation (a translation and rotation) to inversely apply to the given vector.
Returns
Inverse transformed vector.
IsOdd()
template<typename T > constexpr bool playrho::IsOdd (T val) inline noexcept
Is-odd.
Determines whether the given integral value is odd (as opposed to being even).
Referenced by playrho::GetToiViaSat().
ModuloViaFmod()
template<typename T > std::enable_if<std::is_floating_point<T>::value, T>::type playrho::ModuloViaFmod (T dividend, T divisor) inline noexcept
Modulo operation using std::fmod.
Note
Modulo via std::fmod appears slower than via std::trunc.
See also
ModuloViaTrunc
Referenced by playrho::GetNormalized().
ModuloViaTrunc()
template<typename T > auto playrho::ModuloViaTrunc (T dividend, T divisor) inline noexcept
Modulo operation using std::trunc.
Note
Modulo via std::fmod appears slower than via std::trunc.
See also
ModuloViaFmod
Referenced by playrho::GetNormalized().
Mul()
constexpr Transformation playrho::Mul (const Transformation & A, const Transformation & B) inline noexcept
Multiplies a given transformation by another given transformation.
Note
v2 = A.q.Rot(B.q.Rot(v1) + B.p) + A.p = (A.q * B.q).Rot(v1) + A.q.Rot(B.p) + A.p
MulT()
constexpr Transformation playrho::MulT (const Transformation & A, const Transformation & B) inline noexcept
Inverse multiplies a given transformation by another given transformation.
Note
v2 = A.q' * (B.q * v1 + B.p - A.p) = A.q' * B.q * v1 + A.q' * (B.p - A.p)
NextPowerOfTwo()
std::uint64_t playrho::NextPowerOfTwo (std::uint64_t x) inline
Gets the next largest power of 2.
Given a binary integer value x, the next largest power of 2 can be computed by a SWAR algorithm that recursively "folds" the upper bits into the lower bits. This process yields a bit vector with the same most significant 1 as x, but all 1's below it. Adding 1 to that value yields the next largest power of 2. For a 64-bit value:"
Rotate()
template<class T > constexpr auto playrho::Rotate (const Vector2< T > vector, const UnitVec2 & angle) inline noexcept
Rotates a vector by a given angle.
This rotates a vector by the angle expressed by the angle parameter.
Parameters
vector Vector to forward rotate.
angle Expresses the angle to forward rotate the given vector by.
See also
InverseRotate.
Referenced by playrho::SeparationFinder::EvaluateForFaceA(), playrho::SeparationFinder::EvaluateForFaceB(), playrho::SeparationFinder::FindMinSeparationForFaceA(), playrho::SeparationFinder::FindMinSeparationForFaceB(), playrho::SeparationFinder::Get(), playrho::GetLinearVelocity(), playrho::GetMaxSeparation(), playrho::GetTransformation(), playrho::GetWorldVector(), playrho::FrictionJoint::InitVelocityConstraints(), playrho::RopeJoint::InitVelocityConstraints(), playrho::WeldJoint::InitVelocityConstraints(), playrho::PulleyJoint::InitVelocityConstraints(), playrho::MotorJoint::InitVelocityConstraints(), playrho::DistanceJoint::InitVelocityConstraints(), playrho::MouseJoint::InitVelocityConstraints(), playrho::WheelJoint::InitVelocityConstraints(), playrho::PrismaticJoint::InitVelocityConstraints(), playrho::RevoluteJoint::InitVelocityConstraints(), playrho::Mul(), playrho::RayCast(), playrho::WeldJoint::SolvePositionConstraints(), playrho::RopeJoint::SolvePositionConstraints(), playrho::PulleyJoint::SolvePositionConstraints(), playrho::DistanceJoint::SolvePositionConstraints(), playrho::WheelJoint::SolvePositionConstraints(), playrho::PrismaticJoint::SolvePositionConstraints(), playrho::RevoluteJoint::SolvePositionConstraints(), playrho::PolygonShape::Transform(), and playrho::Transform().
Secant()
template<typename T , typename U > constexpr U playrho::Secant (T target, U a1, T s1, U a2, T s2) inline noexcept
Secant method.
See also
https://en.wikipedia.org/wiki/Secant_method
Referenced by playrho::GetToiViaSat().
Solve()
template<typename T , typename U > constexpr auto playrho::Solve (const Matrix22< U > mat, const Vector2< T > b) noexcept
Solves A * x = b, where b is a column vector.
Note
This is more efficient than computing the inverse in one-shot cases.
Referenced by playrho::PrismaticJoint::SolvePositionConstraints(), and playrho::RevoluteJoint::SolvePositionConstraints().
Solve22()
template<typename T > constexpr T playrho::Solve22 (const Mat33 & mat, const T b) noexcept
Solves A * x = b, where b is a column vector.
Note
This is more efficient than computing the inverse in one-shot cases.
Solves only the upper 2-by-2 matrix equation.
Referenced by playrho::WeldJoint::SolvePositionConstraints(), playrho::PrismaticJoint::SolveVelocityConstraints(), and playrho::RevoluteJoint::SolveVelocityConstraints().
Solve33()
constexpr Vec3 playrho::Solve33 (const Mat33 & mat, const Vec3 b) noexcept
Solves A * x = b, where b is a column vector.
Note
This is more efficient than computing the inverse in one-shot cases.
Referenced by playrho::WeldJoint::SolvePositionConstraints(), playrho::PrismaticJoint::SolvePositionConstraints(), playrho::PrismaticJoint::SolveVelocityConstraints(), and playrho::RevoluteJoint::SolveVelocityConstraints().
Transform() [1/2]
constexpr Vec2 playrho::Transform (const Vec2 v, const Mat22 & A) inline noexcept
Multiply a matrix times a vector. If a rotation matrix is provided, then this transforms the vector from one frame to another.
Multiplies a matrix by a vector.
Transform() [2/2]
constexpr Length2 playrho::Transform (const Length2 v, const Transformation xfm) inline noexcept
Transforms the given 2-D vector with the given transformation.
Rotate and translate the given 2-D linear position according to the rotation and translation defined by the given transformation.
Note
Passing the output of this function to InverseTransform (with the same transformation again) will result in the original vector being returned.
For a 2-D linear position of the origin (0, 0), the result is simply the translation.
See also
InverseTransform.
Parameters
v 2-D position to transform (to rotate and then translate).
xfm Transformation (a translation and rotation) to apply to the given vector.
Returns
Rotated and translated vector.