PlayRho: World Body Related Free Functions
World Body Related Free Functions
Collection of "free" functions related to bodies within a World.
Functions
BodyCounter playrho::d2::GetBodyRange (const World &world) noexcept
Gets the extent of the currently valid body range.
SizedRange< std::vector< BodyID >::const_iterator > playrho::d2::GetBodies (const World &world) noexcept
Gets the bodies of the specified world.
SizedRange< std::vector< BodyID >::const_iterator > playrho::d2::GetBodiesForProxies (const World &world) noexcept
Gets the bodies-for-proxies range for the given world.
BodyID playrho::d2::CreateBody (World &world, const BodyConf &def=GetDefaultBodyConf())
Creates a rigid body with the given configuration.
void playrho::d2::Destroy (World &world, BodyID id)
Destroys the identified body.
SizedRange< std::vector< FixtureID >::const_iterator > playrho::d2::GetFixtures (const World &world, BodyID id)
Gets the range of all constant fixtures attached to the given body.
FixtureCounter playrho::d2::GetFixtureCount (const World &world, BodyID id)
Gets the count of fixtures associated with the identified body.
LinearAcceleration2 playrho::d2::GetLinearAcceleration (const World &world, BodyID id)
Gets this body's linear acceleration.
AngularAcceleration playrho::d2::GetAngularAcceleration (const World &world, BodyID id)
Gets this body's angular acceleration.
Acceleration playrho::d2::GetAcceleration (const World &world, BodyID id)
Gets the acceleration of the identified body.
void playrho::d2::SetAcceleration (World &world, BodyID id, LinearAcceleration2 linear, AngularAcceleration angular)
Sets the linear and rotational accelerations on the body.
void playrho::d2::SetAcceleration (World &world, BodyID id, LinearAcceleration2 value)
Sets the linear accelerations on the body.
void playrho::d2::SetAcceleration (World &world, BodyID id, AngularAcceleration value)
Sets the rotational accelerations on the body.
void playrho::d2::SetAcceleration (World &world, BodyID id, Acceleration value)
Sets the accelerations on the given body.
void playrho::d2::SetTransformation (World &world, BodyID id, Transformation xfm)
Sets the body's transformation.
void playrho::d2::SetTransform (World &world, BodyID id, Length2 location, Angle angle)
Sets the position of the body's origin and rotation.
void playrho::d2::SetLocation (World &world, BodyID id, Length2 value)
Sets the body's location.
void playrho::d2::SetAngle (World &world, BodyID id, Angle value)
Sets the body's angular orientation.
void playrho::d2::RotateAboutWorldPoint (World &world, BodyID id, Angle amount, Length2 worldPoint)
Rotates a body a given amount around a point in world coordinates.
void playrho::d2::RotateAboutLocalPoint (World &world, BodyID id, Angle amount, Length2 localPoint)
Rotates a body a given amount around a point in body local coordinates.
Acceleration playrho::d2::CalcGravitationalAcceleration (const World &world, BodyID id)
Calculates the gravitationally associated acceleration for the given body within its world.
BodyCounter playrho::d2::GetWorldIndex (const World &world, const BodyID id) noexcept
Gets the world index for the given body.
BodyConf playrho::d2::GetBodyConf (const World &world, BodyID id)
Gets the body configuration for the identified body.
void playrho::d2::SetType (World &world, BodyID id, BodyType value)
Sets the type of the given body.
BodyType playrho::d2::GetType (const World &world, BodyID id)
Gets the type of this body.
Transformation playrho::d2::GetTransformation (const World &world, BodyID id)
Length2 playrho::d2::GetLocation (const World &world, BodyID id)
Convenience function for getting just the location of the identified body.
Length2 playrho::d2::GetWorldPoint (const World &world, BodyID id, const Length2 localPoint)
Gets the world coordinates of a point given in coordinates relative to the body's origin.
UnitVec playrho::d2::GetLocalVector (const World &world, BodyID body, const UnitVec uv)
Convenience function for getting the local vector of the identified body.
Length2 playrho::d2::GetLocalPoint (const World &world, BodyID body, const Length2 worldPoint)
Gets a local point relative to the body's origin given a world point.
Angle playrho::d2::GetAngle (const World &world, BodyID id)
Get the angle.
Position playrho::d2::GetPosition (const World &world, BodyID id)
Convenience function for getting the position of the identified body.
UnitVec playrho::d2::GetWorldVector (const World &world, BodyID body, UnitVec localVector)
Convenience function for getting a world vector of the identified body.
Velocity playrho::d2::GetVelocity (const World &world, BodyID id)
Gets the velocity of the identified body.
LinearVelocity2 playrho::d2::GetLinearVelocity (const World &world, BodyID id)
Gets the linear velocity of the center of mass of the identified body.
AngularVelocity playrho::d2::GetAngularVelocity (const World &world, BodyID id)
Gets the angular velocity.
void playrho::d2::SetVelocity (World &world, BodyID id, const Velocity &value)
Sets the body's velocity (linear and angular velocity).
void playrho::d2::SetVelocity (World &world, BodyID id, const LinearVelocity2 &value)
Sets the velocity of the identified body.
void playrho::d2::SetVelocity (World &world, BodyID id, AngularVelocity value)
Sets the velocity of the identified body.
void playrho::d2::DestroyFixtures (World &world, BodyID id)
Destroys fixtures of the given body.
bool playrho::d2::IsEnabled (const World &world, BodyID id)
Gets the enabled/disabled state of the body.
void playrho::d2::SetEnabled (World &world, BodyID id, bool value)
Sets the enabled state of the body.
bool playrho::d2::IsAwake (const World &world, BodyID id)
Gets the awake/asleep state of this body.
void playrho::d2::SetAwake (World &world, BodyID id)
Wakes up the identified body.
void playrho::d2::UnsetAwake (World &world, BodyID id)
Sleeps the identified body.
bool playrho::d2::Awaken (World &world, BodyID id)
Awakens the body if it's asleep.
bool playrho::d2::IsMassDataDirty (const World &world, BodyID id)
Gets whether the body's mass-data is dirty.
bool playrho::d2::IsFixedRotation (const World &world, BodyID id)
Gets whether the body has fixed rotation.
void playrho::d2::SetFixedRotation (World &world, BodyID id, bool value)
Sets this body to have fixed rotation.
Length2 playrho::d2::GetWorldCenter (const World &world, BodyID id)
Get the world position of the center of mass of the specified body.
InvMass playrho::d2::GetInvMass (const World &world, BodyID id)
Gets the inverse total mass of the body.
InvRotInertia playrho::d2::GetInvRotInertia (const World &world, BodyID id)
Gets the inverse rotational inertia of the body.
Mass playrho::d2::GetMass (const World &world, BodyID id)
Gets the mass of the body.
RotInertia playrho::d2::GetRotInertia (const World &world, BodyID id)
Gets the rotational inertia of the body.
Length2 playrho::d2::GetLocalCenter (const World &world, BodyID id)
Gets the local position of the center of mass of the specified body.
RotInertia playrho::d2::GetLocalRotInertia (const World &world, BodyID id)
Gets the rotational inertia of the body about the local origin.
MassData playrho::d2::GetMassData (const World &world, BodyID id)
Gets the mass data of the body.
MassData playrho::d2::ComputeMassData (const World &world, BodyID id)
Computes the body's mass data.
void playrho::d2::SetMassData (World &world, BodyID id, const MassData &massData)
Sets the mass properties to override the mass properties of the fixtures.
void playrho::d2::ResetMassData (World &world, BodyID id)
Resets the mass data properties.
bool playrho::d2::ShouldCollide (const World &world, BodyID lhs, BodyID rhs)
Should collide.
SizedRange< std::vector< std::pair< BodyID, JointID > >::const_iterator > playrho::d2::GetJoints (const World &world, BodyID id)
Gets the range of all joints attached to the identified body.
bool playrho::d2::IsSpeedable (const World &world, BodyID id)
Is identified body "speedable".
bool playrho::d2::IsAccelerable (const World &world, BodyID id)
Is identified body "accelerable"?
bool playrho::d2::IsImpenetrable (const World &world, BodyID id)
Is the body treated like a bullet for continuous collision detection?
void playrho::d2::SetImpenetrable (World &world, BodyID id)
Sets the impenetrable status of the identified body.
void playrho::d2::UnsetImpenetrable (World &world, BodyID id)
Unsets the impenetrable status of the identified body.
void playrho::d2::SetImpenetrable (World &world, BodyID id, bool value)
Convenience function that sets/unsets the impenetrable status of the identified body.
bool playrho::d2::IsSleepingAllowed (const World &world, BodyID id)
Gets whether the identified body is allowed to sleep.
void playrho::d2::SetSleepingAllowed (World &world, BodyID, bool value)
Sets whether the identified body is allowed to sleep.
SizedRange< std::vector< KeyedContactPtr >::const_iterator > playrho::d2::GetContacts (const World &world, BodyID id)
Gets the container of all contacts attached to the identified body.
Force2 playrho::d2::GetCentripetalForce (const World &world, BodyID id, Length2 axis)
Gets the centripetal force necessary to put the body into an orbit having the given radius.
void playrho::d2::ApplyForceToCenter (World &world, BodyID id, Force2 force)
Applies a force to the center of mass of the given body.
void playrho::d2::ApplyForce (World &world, BodyID id, Force2 force, Length2 point)
Apply a force at a world point.
void playrho::d2::ApplyTorque (World &world, BodyID id, Torque torque)
Applies a torque.
void playrho::d2::ApplyLinearImpulse (World &world, BodyID id, Momentum2 impulse, Length2 point)
Applies an impulse at a point.
void playrho::d2::ApplyAngularImpulse (World &world, BodyID id, AngularMomentum impulse)
Applies an angular impulse.
void playrho::d2::SetForce (World &world, BodyID id, Force2 force, Length2 point) noexcept
Sets the given amount of force at the given point to the given body.
void playrho::d2::SetTorque (World &world, BodyID id, Torque torque) noexcept
Sets the given amount of torque to the given body.
Frequency playrho::d2::GetLinearDamping (const World &world, BodyID id)
Gets the linear damping of the body.
void playrho::d2::SetLinearDamping (World &world, BodyID id, NonNegative< Frequency > linearDamping)
Sets the linear damping of the body.
Frequency playrho::d2::GetAngularDamping (const World &world, BodyID id)
Gets the angular damping of the body.
void playrho::d2::SetAngularDamping (World &world, BodyID id, NonNegative< Frequency > angularDamping)
Sets the angular damping of the body.
BodyCounter playrho::d2::GetAwakeCount (const World &world) noexcept
Gets the count of awake bodies in the given world.
BodyCounter playrho::d2::Awaken (World &world) noexcept
Awakens all of the bodies in the given world.
BodyID playrho::d2::FindClosestBody (const World &world, Length2 location) noexcept
Finds body in given world that's closest to the given location.
BodyCounter playrho::d2::GetBodyCount (const World &world) noexcept
Gets the body count in the given world.
void playrho::d2::SetAccelerations (World &world, Acceleration acceleration) noexcept
Sets the accelerations of all the world's bodies to the given value.
void playrho::d2::SetAccelerations (World &world, LinearAcceleration2 acceleration) noexcept
Sets the accelerations of all the world's bodies to the given value.
void playrho::d2::ClearForces (World &world) noexcept
Clears forces.
template<class F >
void playrho::d2::SetAccelerations (World &world, F fn)
Sets the accelerations of all the world's bodies.
BodyCounter GetBodyRange (const World &world) noexcept
Gets the extent of the currently valid body range.
SizedRange< std::vector< BodyID >::const_iterator > GetBodies (const World &world) noexcept
Gets the bodies of the specified world.
SizedRange< std::vector< BodyID >::const_iterator > GetBodiesForProxies (const World &world) noexcept
Gets the bodies-for-proxies range for the given world.
BodyID CreateBody (World &world, const BodyConf &def=GetDefaultBodyConf())
Creates a rigid body with the given configuration.
void Destroy (World &world, BodyID id)
Destroys the identified body.
SizedRange< std::vector< FixtureID >::const_iterator > GetFixtures (const World &world, BodyID id)
Gets the range of all constant fixtures attached to the given body.
FixtureCounter GetFixtureCount (const World &world, BodyID id)
Gets the count of fixtures associated with the identified body.
LinearAcceleration2 GetLinearAcceleration (const World &world, BodyID id)
Gets this body's linear acceleration.
AngularAcceleration GetAngularAcceleration (const World &world, BodyID id)
Gets this body's angular acceleration.
Acceleration GetAcceleration (const World &world, BodyID id)
Gets the acceleration of the identified body.
void SetAcceleration (World &world, BodyID id, LinearAcceleration2 linear, AngularAcceleration angular)
Sets the linear and rotational accelerations on the body.
void SetAcceleration (World &world, BodyID id, LinearAcceleration2 value)
Sets the linear accelerations on the body.
void SetAcceleration (World &world, BodyID id, AngularAcceleration value)
Sets the rotational accelerations on the body.
void SetAcceleration (World &world, BodyID id, Acceleration value)
Sets the accelerations on the given body.
void SetTransformation (World &world, BodyID id, Transformation xfm)
Sets the body's transformation.
void SetTransform (World &world, BodyID id, Length2 location, Angle angle)
Sets the position of the body's origin and rotation.
void SetLocation (World &world, BodyID id, Length2 value)
Sets the body's location.
void SetAngle (World &world, BodyID id, Angle value)
Sets the body's angular orientation.
void RotateAboutWorldPoint (World &world, BodyID id, Angle amount, Length2 worldPoint)
Rotates a body a given amount around a point in world coordinates.
void RotateAboutLocalPoint (World &world, BodyID id, Angle amount, Length2 localPoint)
Rotates a body a given amount around a point in body local coordinates.
Acceleration CalcGravitationalAcceleration (const World &world, BodyID id)
Calculates the gravitationally associated acceleration for the given body within its world.
BodyCounter GetWorldIndex (const World &world, const BodyID id) noexcept
Gets the world index for the given body.
BodyConf GetBodyConf (const World &world, BodyID id)
Gets the body configuration for the identified body.
void SetType (World &world, BodyID id, BodyType value)
Sets the type of the given body.
BodyType GetType (const World &world, BodyID id)
Gets the type of this body.
Transformation GetTransformation (const World &world, BodyID id)
Length2 GetLocation (const World &world, BodyID id)
Convenience function for getting just the location of the identified body.
Length2 GetWorldPoint (const World &world, BodyID id, const Length2 localPoint)
Gets the world coordinates of a point given in coordinates relative to the body's origin.
UnitVec GetLocalVector (const World &world, BodyID body, const UnitVec uv)
Convenience function for getting the local vector of the identified body.
Length2 GetLocalPoint (const World &world, BodyID body, const Length2 worldPoint)
Gets a local point relative to the body's origin given a world point.
Angle GetAngle (const World &world, BodyID id)
Get the angle.
UnitVec GetWorldVector (const World &world, BodyID body, UnitVec localVector)
Convenience function for getting a world vector of the identified body.
Velocity GetVelocity (const World &world, BodyID id)
Gets the velocity of the identified body.
LinearVelocity2 GetLinearVelocity (const World &world, BodyID id)
Gets the linear velocity of the center of mass of the identified body.
AngularVelocity GetAngularVelocity (const World &world, BodyID id)
Gets the angular velocity.
void SetVelocity (World &world, BodyID id, const Velocity &value)
Sets the body's velocity (linear and angular velocity).
void SetVelocity (World &world, BodyID id, const LinearVelocity2 &value)
Sets the velocity of the identified body.
void SetVelocity (World &world, BodyID id, AngularVelocity value)
Sets the velocity of the identified body.
void DestroyFixtures (World &world, BodyID id)
Destroys fixtures of the given body.
bool IsEnabled (const World &world, BodyID id)
Gets the enabled/disabled state of the body.
void SetEnabled (World &world, BodyID id, bool value)
Sets the enabled state of the body.
bool IsAwake (const World &world, BodyID id)
Gets the awake/asleep state of this body.
void SetAwake (World &world, BodyID id)
Wakes up the identified body.
void UnsetAwake (World &world, BodyID id)
Sleeps the identified body.
bool Awaken (World &world, BodyID id)
Awakens the body if it's asleep.
bool IsMassDataDirty (const World &world, BodyID id)
Gets whether the body's mass-data is dirty.
bool IsFixedRotation (const World &world, BodyID id)
Gets whether the body has fixed rotation.
void SetFixedRotation (World &world, BodyID id, bool value)
Sets this body to have fixed rotation.
Length2 GetWorldCenter (const World &world, BodyID id)
Get the world position of the center of mass of the specified body.
InvMass GetInvMass (const World &world, BodyID id)
Gets the inverse total mass of the body.
InvRotInertia GetInvRotInertia (const World &world, BodyID id)
Gets the inverse rotational inertia of the body.
Mass GetMass (const World &world, BodyID id)
Gets the mass of the body.
RotInertia GetRotInertia (const World &world, BodyID id)
Gets the rotational inertia of the body.
Length2 GetLocalCenter (const World &world, BodyID id)
Gets the local position of the center of mass of the specified body.
RotInertia GetLocalRotInertia (const World &world, BodyID id)
Gets the rotational inertia of the body about the local origin.
MassData GetMassData (const World &world, BodyID id)
Gets the mass data of the body.
MassData ComputeMassData (const World &world, BodyID id)
Computes the body's mass data.
void SetMassData (World &world, BodyID id, const MassData &massData)
Sets the mass properties to override the mass properties of the fixtures.
void ResetMassData (World &world, BodyID id)
Resets the mass data properties.
bool ShouldCollide (const World &world, BodyID lhs, BodyID rhs)
Should collide.
SizedRange< std::vector< std::pair< BodyID, JointID > >::const_iterator > GetJoints (const World &world, BodyID id)
Gets the range of all joints attached to the identified body.
bool IsSpeedable (const World &world, BodyID id)
Is identified body "speedable".
bool IsAccelerable (const World &world, BodyID id)
Is identified body "accelerable"?
bool IsImpenetrable (const World &world, BodyID id)
Is the body treated like a bullet for continuous collision detection?
void SetImpenetrable (World &world, BodyID id)
Sets the impenetrable status of the identified body.
void UnsetImpenetrable (World &world, BodyID id)
Unsets the impenetrable status of the identified body.
void SetImpenetrable (World &world, BodyID id, bool value)
Convenience function that sets/unsets the impenetrable status of the identified body.
bool IsSleepingAllowed (const World &world, BodyID id)
Gets whether the identified body is allowed to sleep.
void SetSleepingAllowed (World &world, BodyID, bool value)
Sets whether the identified body is allowed to sleep.
SizedRange< std::vector< KeyedContactPtr >::const_iterator > GetContacts (const World &world, BodyID id)
Gets the container of all contacts attached to the identified body.
Force2 GetCentripetalForce (const World &world, BodyID id, Length2 axis)
Gets the centripetal force necessary to put the body into an orbit having the given radius.
void ApplyForceToCenter (World &world, BodyID id, Force2 force)
Applies a force to the center of mass of the given body.
void ApplyForce (World &world, BodyID id, Force2 force, Length2 point)
Apply a force at a world point.
void ApplyTorque (World &world, BodyID id, Torque torque)
Applies a torque.
void ApplyLinearImpulse (World &world, BodyID id, Momentum2 impulse, Length2 point)
Applies an impulse at a point.
void ApplyAngularImpulse (World &world, BodyID id, AngularMomentum impulse)
Applies an angular impulse.
void SetForce (World &world, BodyID id, Force2 force, Length2 point) noexcept
Sets the given amount of force at the given point to the given body.
void SetTorque (World &world, BodyID id, Torque torque) noexcept
Sets the given amount of torque to the given body.
Frequency GetLinearDamping (const World &world, BodyID id)
Gets the linear damping of the body.
void SetLinearDamping (World &world, BodyID id, NonNegative< Frequency > linearDamping)
Sets the linear damping of the body.
Frequency GetAngularDamping (const World &world, BodyID id)
Gets the angular damping of the body.
void SetAngularDamping (World &world, BodyID id, NonNegative< Frequency > angularDamping)
Sets the angular damping of the body.
BodyCounter GetAwakeCount (const World &world) noexcept
Gets the count of awake bodies in the given world.
BodyCounter Awaken (World &world) noexcept
Awakens all of the bodies in the given world.
BodyID FindClosestBody (const World &world, Length2 location) noexcept
Finds body in given world that's closest to the given location.
BodyCounter GetBodyCount (const World &world) noexcept
Gets the body count in the given world.
void SetAccelerations (World &world, Acceleration acceleration) noexcept
Sets the accelerations of all the world's bodies to the given value.
void SetAccelerations (World &world, LinearAcceleration2 acceleration) noexcept
Sets the accelerations of all the world's bodies to the given value.
void ClearForces (World &world) noexcept
Clears forces.
template<class F >
void SetAccelerations (World &world, F fn)
Sets the accelerations of all the world's bodies.
Detailed Description
Collection of "free" functions related to bodies within a World.
This is a collection of non-member non-friend functions - also called "free" functions - that are related to bodies within an instance of a World. Many are just "wrappers" to similarly named member functions but some are additional functionality built on those member functions. A benefit to using free functions that are now just wrappers, is that of helping to isolate your code from future changes that might occur to the underlying World member functions. Free functions in this sense are "cheap" abstractions. While using these incurs extra run-time overhead when compiled without any compiler optimizations enabled, enabling optimizations should entirely eliminate that overhead.
Note
The four basic categories of these functions are "CRUD": create, read, update, and delete.
See also
World, BodyID.
https://en.wikipedia.org/wiki/Create,_read,_update_and_delete.
Function Documentation
ApplyAngularImpulse() [1/2]
void ApplyAngularImpulse (World & world, BodyID id, AngularMomentum impulse)
Applies an angular impulse.
Parameters
world The world in which the identified body exists.
id Body to apply the angular impulse to.
impulse Angular impulse to be applied.
Exceptions
std::out_of_range If given an invalid body identifier.
ApplyAngularImpulse() [2/2]
void ApplyAngularImpulse (World & world, BodyID id, AngularMomentum impulse) related
Applies an angular impulse.
Parameters
world The world in which the identified body exists.
id Body to apply the angular impulse to.
impulse Angular impulse to be applied.
Exceptions
std::out_of_range If given an invalid body identifier.
ApplyForce() [1/2]
void ApplyForce (World & world, BodyID id, Force2 force, Length2 point)
Apply a force at a world point.
Note
If the force is not applied at the center of mass, it will generate a torque and affect the angular velocity.
Non-zero forces wakes up the body.
Parameters
world World in which body exists.
id Identity of body to apply the force to.
force World force vector.
point World position of the point of application.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp.
ApplyForce() [2/2]
void ApplyForce (World & world, BodyID id, Force2 force, Length2 point) related
Apply a force at a world point.
Note
If the force is not applied at the center of mass, it will generate a torque and affect the angular velocity.
Non-zero forces wakes up the body.
Parameters
world World in which body exists.
id Identity of body to apply the force to.
force World force vector.
point World position of the point of application.
Exceptions
std::out_of_range If given an invalid body identifier.
ApplyForceToCenter() [1/2]
void ApplyForceToCenter (World & world, BodyID id, Force2 force) inline
Applies a force to the center of mass of the given body.
Note
Non-zero forces wakes up the body.
Parameters
world The world in which the identified body exists.
id Body to apply the force to.
force World force vector.
Exceptions
std::out_of_range If given an invalid body identifier.
ApplyForceToCenter() [2/2]
void ApplyForceToCenter (World & world, BodyID id, Force2 force) related
Applies a force to the center of mass of the given body.
Note
Non-zero forces wakes up the body.
Parameters
world The world in which the identified body exists.
id Body to apply the force to.
force World force vector.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
ApplyLinearImpulse() [1/2]
void ApplyLinearImpulse (World & world, BodyID id, Momentum2 impulse, Length2 point)
Applies an impulse at a point.
Note
This immediately modifies the velocity.
This also modifies the angular velocity if the point of application is not at the center of mass.
Non-zero impulses wakes up the body.
Parameters
world The world in which the identified body exists.
id Body to apply the impulse to.
impulse the world impulse vector.
point the world position of the point of application.
Exceptions
std::out_of_range If given an invalid body identifier.
ApplyLinearImpulse() [2/2]
void ApplyLinearImpulse (World & world, BodyID id, Momentum2 impulse, Length2 point) related
Applies an impulse at a point.
Note
This immediately modifies the velocity.
This also modifies the angular velocity if the point of application is not at the center of mass.
Non-zero impulses wakes up the body.
Parameters
world The world in which the identified body exists.
id Body to apply the impulse to.
impulse the world impulse vector.
point the world position of the point of application.
Exceptions
std::out_of_range If given an invalid body identifier.
ApplyTorque() [1/2]
void ApplyTorque (World & world, BodyID id, Torque torque)
Applies a torque.
Note
This affects the angular velocity without affecting the linear velocity of the center of mass.
Non-zero forces wakes up the body.
Parameters
world The world in which the identified body exists.
id Body to apply the torque to.
torque about the z-axis (out of the screen).
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp.
ApplyTorque() [2/2]
void ApplyTorque (World & world, BodyID id, Torque torque) related
Applies a torque.
Note
This affects the angular velocity without affecting the linear velocity of the center of mass.
Non-zero forces wakes up the body.
Parameters
world The world in which the identified body exists.
id Body to apply the torque to.
torque about the z-axis (out of the screen).
Exceptions
std::out_of_range If given an invalid body identifier.
Awaken() [1/4]
BodyCounter Awaken (World & world) noexcept
Awakens all of the bodies in the given world.
Calls all of the world's bodies' SetAwake method.
Returns
Sum total of calls to bodies' SetAwake method that returned true.
See also
Body::SetAwake.
Awaken() [2/4]
BodyCounter Awaken (World & world) related
Awakens all of the bodies in the given world.
Calls all of the world's bodies' SetAwake method.
Returns
Sum total of calls to bodies' SetAwake method that returned true.
See also
Body::SetAwake.
Awaken() [3/4]
bool Awaken (World & world, BodyID id) related
Awakens the body if it's asleep.
Exceptions
std::out_of_range If given an invalid body identifier.
Awaken() [4/4]
bool Awaken (World & world, BodyID id) inline
Awakens the body if it's asleep.
Exceptions
std::out_of_range If given an invalid body identifier.
CalcGravitationalAcceleration() [1/2]
Acceleration CalcGravitationalAcceleration (const World & world, BodyID id)
Calculates the gravitationally associated acceleration for the given body within its world.
Returns
Zero acceleration if given body is has no mass, else the acceleration of the body due to the gravitational attraction to the other bodies.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp.
CalcGravitationalAcceleration() [2/2]
Acceleration CalcGravitationalAcceleration (const World & world, BodyID id) related
Calculates the gravitationally associated acceleration for the given body within its world.
Returns
Zero acceleration if given body is has no mass, else the acceleration of the body due to the gravitational attraction to the other bodies.
Exceptions
std::out_of_range If given an invalid body identifier.
ClearForces() [1/2]
void ClearForces (World & world) inline noexcept
Clears forces.
Manually clear the force buffer on all bodies.
ClearForces() [2/2]
void ClearForces (World & world) related
Clears forces.
Manually clear the force buffer on all bodies.
Examples
World.cpp.
ComputeMassData() [1/2]
MassData ComputeMassData (const World & world, BodyID id)
Computes the body's mass data.
This basically accumulates the mass data over all fixtures.
Note
The center is the mass weighted sum of all fixture centers. Divide it by the mass to get the averaged center.
Returns
accumulated mass data for all fixtures associated with the given body.
Exceptions
std::out_of_range If given an invalid body identifier.
Referenced by playrho::d2::World::ComputeMassData(), playrho::d2::WorldImpl::CreateFixture(), playrho::d2::WorldImpl::Destroy(), playrho::d2::WorldImpl::DestroyFixtures(), playrho::d2::ResetMassData(), and playrho::d2::WorldImpl::SetType().
ComputeMassData() [2/2]
MassData ComputeMassData (const World & world, BodyID id) related
Computes the body's mass data.
This basically accumulates the mass data over all fixtures.
Note
The center is the mass weighted sum of all fixture centers. Divide it by the mass to get the averaged center.
Returns
accumulated mass data for all fixtures associated with the given body.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
CreateBody() [1/2]
BodyID CreateBody (World & world, const BodyConf & def = GetDefaultBodyConf())
Creates a rigid body with the given configuration.
Warning
This function should not be used while the world is locked — as it is during callbacks. If it is, it will throw an exception or abort your program.
Note
No references to the configuration are retained. Its value is copied.
Postcondition
The created body will be present in the range returned from the GetBodies(const World&) method.
Parameters
world The world within which to create the body.
def A customized body configuration or its default value.
Returns
Identifier of the newly created body which can later be destroyed by calling the Destroy(World&, BodyID) method.
Exceptions
WrongState if this method is called while the world is locked.
LengthError if this operation would create more than MaxBodies.
See also
Destroy(BodyID), GetBodies(const World&).
Physical Entities.
Examples
WorldBody.cpp, WorldContact.cpp, and WorldFixture.cpp.
Referenced by playrho::d2::World::CreateBody().
CreateBody() [2/2]
BodyID CreateBody (World & world, const BodyConf & def = GetDefaultBodyConf()) related
Creates a rigid body with the given configuration.
Warning
This function should not be used while the world is locked — as it is during callbacks. If it is, it will throw an exception or abort your program.
Note
No references to the configuration are retained. Its value is copied.
Postcondition
The created body will be present in the range returned from the GetBodies(const World&) method.
Parameters
world The world within which to create the body.
def A customized body configuration or its default value.
Returns
Identifier of the newly created body which can later be destroyed by calling the Destroy(World&, BodyID) method.
Exceptions
WrongState if this method is called while the world is locked.
LengthError if this operation would create more than MaxBodies.
See also
Destroy(BodyID), GetBodies(const World&).
Physical Entities.
Examples
World.cpp.
Destroy() [1/2]
void Destroy (World & world, BodyID id)
Destroys the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
CreateBody(World&, const BodyConf&).
Examples
WorldBody.cpp, and WorldFixture.cpp.
Referenced by playrho::d2::WorldImpl::CreateAndDestroyProxies(), playrho::d2::World::Destroy(), playrho::d2::WorldImpl::Destroy(), playrho::d2::WorldImpl::DestroyFixtures(), and playrho::d2::WorldImpl::SetType().
Destroy() [2/2]
void Destroy (World & world, BodyID id) related
Destroys the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
CreateBody(World&, const BodyConf&).
DestroyFixtures() [1/2]
void DestroyFixtures (World & world, BodyID id)
Destroys fixtures of the given body.
Destroys all of the fixtures previously created for this body by the CreateFixture(const Shape&, const FixtureConf&, bool) method.
Note
This unconditionally calls the ResetMassData() method.
Postcondition
After this call, no fixtures will show up in the fixture enumeration returned by the GetFixtures() methods.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
CreateFixture, GetFixtures, ResetMassData.
Physical Entities
Examples
WorldBody.cpp.
Referenced by playrho::d2::World::DestroyFixtures().
DestroyFixtures() [2/2]
void DestroyFixtures (World & world, BodyID id) related
Destroys fixtures of the given body.
Destroys all of the fixtures previously created for this body by the CreateFixture(const Shape&, const FixtureConf&, bool) method.
Note
This unconditionally calls the ResetMassData() method.
Postcondition
After this call, no fixtures will show up in the fixture enumeration returned by the GetFixtures() methods.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
CreateFixture, GetFixtures, ResetMassData.
Physical Entities
GetAcceleration() [1/2]
Acceleration GetAcceleration (const World & world, BodyID id)
Gets the acceleration of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetAcceleration() [2/2]
Acceleration GetAcceleration (const World & world, BodyID id) related
Gets the acceleration of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetAngle() [1/2]
Angle GetAngle (const World & world, BodyID id)
Get the angle.
Returns
the current world rotation angle.
Exceptions
std::out_of_range If given an invalid body identifier.
GetAngle() [2/2]
Angle GetAngle (const World & world, BodyID id) related
Get the angle.
Returns
the current world rotation angle.
Exceptions
std::out_of_range If given an invalid body identifier.
GetAngularAcceleration() [1/2]
AngularAcceleration GetAngularAcceleration (const World & world, BodyID id)
Gets this body's angular acceleration.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp.
Referenced by playrho::d2::ApplyForce(), playrho::d2::ApplyForceToCenter(), playrho::d2::ApplyTorque(), and playrho::d2::World::GetAngularAcceleration().
GetAngularAcceleration() [2/2]
AngularAcceleration GetAngularAcceleration (const World & world, BodyID id) related
Gets this body's angular acceleration.
Exceptions
std::out_of_range If given an invalid body identifier.
GetAngularDamping() [1/2]
Frequency GetAngularDamping (const World & world, BodyID id)
Gets the angular damping of the body.
Exceptions
std::out_of_range If given an invalid body identifier.
Referenced by playrho::d2::World::GetAngularDamping().
GetAngularDamping() [2/2]
Frequency GetAngularDamping (const World & world, BodyID id) related
Gets the angular damping of the body.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
GetAngularVelocity() [1/2]
AngularVelocity GetAngularVelocity (const World & world, BodyID id) inline
Gets the angular velocity.
Parameters
world World in which body is identified for.
id Body to get the angular velocity for.
Returns
the angular velocity.
Exceptions
std::out_of_range If given an invalid body identifier.
GetAngularVelocity() [2/2]
AngularVelocity GetAngularVelocity (const World & world, BodyID id) related
Gets the angular velocity.
Parameters
world World in which body is identified for.
id Body to get the angular velocity for.
Returns
the angular velocity.
Exceptions
std::out_of_range If given an invalid body identifier.
GetBodyConf() [1/2]
BodyConf GetBodyConf (const World & world, BodyID id)
Gets the body configuration for the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
Referenced by playrho::d2::World::GetBodyConf().
GetBodyConf() [2/2]
BodyConf GetBodyConf (const World & world, BodyID id) related
Gets the body configuration for the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetBodyCount() [1/2]
BodyCounter GetBodyCount (const World & world) inline noexcept
Gets the body count in the given world.
Returns
0 or higher.
Examples
World.cpp, and WorldBody.cpp.
GetBodyCount() [2/2]
BodyCounter GetBodyCount (const World & world) related
Gets the body count in the given world.
Returns
0 or higher.
Examples
World.cpp.
GetBodyRange() [1/2]
BodyCounter GetBodyRange (const World & world) noexcept
Gets the extent of the currently valid body range.
Note
This is one higher than the maxium BodyID that is in range for body related functions.
Referenced by playrho::d2::World::GetBodyRange().
GetBodyRange() [2/2]
BodyCounter GetBodyRange (const World & world) related
Gets the extent of the currently valid body range.
Note
This is one higher than the maxium BodyID that is in range for body related functions.
GetCentripetalForce() [1/2]
Force2 GetCentripetalForce (const World & world, BodyID id, Length2 axis)
Gets the centripetal force necessary to put the body into an orbit having the given radius.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp.
GetCentripetalForce() [2/2]
Force2 GetCentripetalForce (const World & world, BodyID id, Length2 axis) related
Gets the centripetal force necessary to put the body into an orbit having the given radius.
Exceptions
std::out_of_range If given an invalid body identifier.
GetContacts() [1/2]
SizedRange< std::vector< KeyedContactPtr >::const_iterator > GetContacts (const World & world, BodyID id)
Gets the container of all contacts attached to the identified body.
Warning
This collection changes during the time step and you may miss some collisions if you don't use ContactListener.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp, and WorldContact.cpp.
Referenced by playrho::d2::GetContactCount(), playrho::d2::World::GetContacts(), and playrho::d2::WorldImpl::Remove().
GetContacts() [2/2]
SizedRange< std::vector< KeyedContactPtr >::const_iterator > GetContacts (const World & world, BodyID id) related
Gets the container of all contacts attached to the identified body.
Warning
This collection changes during the time step and you may miss some collisions if you don't use ContactListener.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
GetFixtureCount() [1/2]
FixtureCounter GetFixtureCount (const World & world, BodyID id) related
Gets the count of fixtures associated with the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetFixtureCount() [2/2]
FixtureCounter GetFixtureCount (const World & world, BodyID id) inline
Gets the count of fixtures associated with the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetFixtures() [1/2]
SizedRange< std::vector< FixtureID >::const_iterator > GetFixtures (const World & world, BodyID id)
Gets the range of all constant fixtures attached to the given body.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp, and WorldFixture.cpp.
Referenced by playrho::d2::ComputeAABB(), playrho::d2::GetFixtureCount(), and playrho::d2::World::GetFixtures().
GetFixtures() [2/2]
SizedRange< std::vector< FixtureID >::const_iterator > GetFixtures (const World & world, BodyID id) related
Gets the range of all constant fixtures attached to the given body.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
GetInvMass() [1/2]
InvMass GetInvMass (const World & world, BodyID id)
Gets the inverse total mass of the body.
Returns
Value of zero or more representing the body's inverse mass (in 1/kg).
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetMassData.
Referenced by playrho::d2::World::GetInvMass().
GetInvMass() [2/2]
InvMass GetInvMass (const World & world, BodyID id) related
Gets the inverse total mass of the body.
Returns
Value of zero or more representing the body's inverse mass (in 1/kg).
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetMassData.
Examples
World.cpp.
GetInvRotInertia() [1/2]
InvRotInertia GetInvRotInertia (const World & world, BodyID id)
Gets the inverse rotational inertia of the body.
Returns
Inverse rotational inertia (in 1/kg-m^2).
Exceptions
std::out_of_range If given an invalid body identifier.
Referenced by playrho::d2::ApplyAngularImpulse(), playrho::d2::ApplyLinearImpulse(), playrho::d2::ApplyTorque(), playrho::d2::World::GetInvRotInertia(), playrho::d2::GetRotInertia(), playrho::d2::SetForce(), and playrho::d2::SetTorque().
GetInvRotInertia() [2/2]
InvRotInertia GetInvRotInertia (const World & world, BodyID id) related
Gets the inverse rotational inertia of the body.
Returns
Inverse rotational inertia (in 1/kg-m^2).
Exceptions
std::out_of_range If given an invalid body identifier.
GetJoints() [1/2]
SizedRange< std::vector< std::pair< BodyID, JointID > >::const_iterator > GetJoints (const World & world, BodyID id)
Gets the range of all joints attached to the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp.
Referenced by playrho::d2::GetJointCount(), playrho::d2::World::GetJoints(), and playrho::d2::ShouldCollide().
GetJoints() [2/2]
SizedRange< std::vector< std::pair< BodyID, JointID > >::const_iterator > GetJoints (const World & world, BodyID id) related
Gets the range of all joints attached to the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetLinearAcceleration() [1/2]
LinearAcceleration2 GetLinearAcceleration (const World & world, BodyID id)
Gets this body's linear acceleration.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp.
Referenced by playrho::d2::ApplyForce(), playrho::d2::ApplyForceToCenter(), playrho::d2::ApplyTorque(), playrho::d2::World::GetLinearAcceleration(), and playrho::d2::SetTorque().
GetLinearAcceleration() [2/2]
LinearAcceleration2 GetLinearAcceleration (const World & world, BodyID id) related
Gets this body's linear acceleration.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
GetLinearDamping() [1/2]
Frequency GetLinearDamping (const World & world, BodyID id)
Gets the linear damping of the body.
Exceptions
std::out_of_range If given an invalid body identifier.
Referenced by playrho::d2::World::GetLinearDamping().
GetLinearDamping() [2/2]
Frequency GetLinearDamping (const World & world, BodyID id) related
Gets the linear damping of the body.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
GetLinearVelocity() [1/2]
LinearVelocity2 GetLinearVelocity (const World & world, BodyID id) inline
Gets the linear velocity of the center of mass of the identified body.
Parameters
world World in which body is identified for.
id Body to get the linear velocity for.
Returns
the linear velocity of the center of mass.
Exceptions
std::out_of_range If given an invalid body identifier.
GetLinearVelocity() [2/2]
LinearVelocity2 GetLinearVelocity (const World & world, BodyID id) related
Gets the linear velocity of the center of mass of the identified body.
Parameters
world World in which body is identified for.
id Body to get the linear velocity for.
Returns
the linear velocity of the center of mass.
Exceptions
std::out_of_range If given an invalid body identifier.
GetLocalCenter() [1/2]
Length2 GetLocalCenter (const World & world, BodyID id)
Gets the local position of the center of mass of the specified body.
Exceptions
std::out_of_range If given an invalid body identifier.
Referenced by playrho::d2::GetLinearVelocity(), playrho::d2::World::GetLocalCenter(), playrho::d2::GetLocalRotInertia(), and playrho::d2::GetMassData().
GetLocalCenter() [2/2]
Length2 GetLocalCenter (const World & world, BodyID id) related
Gets the local position of the center of mass of the specified body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetLocalPoint() [1/2]
Length2 GetLocalPoint (const World & world, BodyID body, const Length2 worldPoint) related
Gets a local point relative to the body's origin given a world point.
Parameters
world The world in which the identified body exists.
body Body that the returned point should be relative to.
worldPoint point in world coordinates.
Returns
the corresponding local point relative to the body's origin.
Exceptions
std::out_of_range If given an invalid body identifier.
GetLocalPoint() [2/2]
Length2 GetLocalPoint (const World & world, BodyID body, const Length2 worldPoint) inline
Gets a local point relative to the body's origin given a world point.
Parameters
world The world in which the identified body exists.
body Body that the returned point should be relative to.
worldPoint point in world coordinates.
Returns
the corresponding local point relative to the body's origin.
Exceptions
std::out_of_range If given an invalid body identifier.
GetLocalRotInertia() [1/2]
RotInertia GetLocalRotInertia (const World & world, BodyID id) related
Gets the rotational inertia of the body about the local origin.
Returns
the rotational inertia.
Exceptions
std::out_of_range If given an invalid body identifier.
GetLocalRotInertia() [2/2]
RotInertia GetLocalRotInertia (const World & world, BodyID id) inline
Gets the rotational inertia of the body about the local origin.
Returns
the rotational inertia.
Exceptions
std::out_of_range If given an invalid body identifier.
GetLocalVector() [1/2]
UnitVec GetLocalVector (const World & world, BodyID body, const UnitVec uv) inline
Convenience function for getting the local vector of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetLocalVector() [2/2]
UnitVec GetLocalVector (const World & world, BodyID body, const UnitVec uv) related
Convenience function for getting the local vector of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetLocation() [1/2]
Length2 GetLocation (const World & world, BodyID id) inline
Convenience function for getting just the location of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
GetLocation() [2/2]
Length2 GetLocation (const World & world, BodyID id) related
Convenience function for getting just the location of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetMass() [1/2]
Mass GetMass (const World & world, BodyID id) related
Gets the mass of the body.
Note
This may be the total calculated mass or it may be the set mass of the body.
Returns
Value of zero or more representing the body's mass.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
GetInvMass, SetMassData
GetMass() [2/2]
Mass GetMass (const World & world, BodyID id) inline
Gets the mass of the body.
Note
This may be the total calculated mass or it may be the set mass of the body.
Returns
Value of zero or more representing the body's mass.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
GetInvMass, SetMassData
GetMassData() [1/2]
MassData GetMassData (const World & world, BodyID id) related
Gets the mass data of the body.
Returns
Data structure containing the mass, inertia, and center of the body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetMassData() [2/2]
MassData GetMassData (const World & world, BodyID id) inline
Gets the mass data of the body.
Returns
Data structure containing the mass, inertia, and center of the body.
Exceptions
std::out_of_range If given an invalid body identifier.
Referenced by playrho::d2::WorldImpl::ComputeMassData().
GetRotInertia() [1/2]
RotInertia GetRotInertia (const World & world, BodyID id) related
Gets the rotational inertia of the body.
Parameters
world The world in which the identified body exists.
id Body to get the rotational inertia for.
Returns
the rotational inertia.
Exceptions
std::out_of_range If given an invalid body identifier.
GetRotInertia() [2/2]
RotInertia GetRotInertia (const World & world, BodyID id) inline
Gets the rotational inertia of the body.
Parameters
world The world in which the identified body exists.
id Body to get the rotational inertia for.
Returns
the rotational inertia.
Exceptions
std::out_of_range If given an invalid body identifier.
GetTransformation() [1/2]
Transformation GetTransformation (const World & world, BodyID id)
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetTransformation
Referenced by playrho::d2::Body::Body(), playrho::d2::World::GetTransformation(), and playrho::d2::WorldImpl::UpdateBody().
GetTransformation() [2/2]
Transformation GetTransformation (const World & world, BodyID id) related
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetTransformation
GetType() [1/2]
BodyType GetType (const World & world, BodyID id)
Gets the type of this body.
See also
SetType(World& world, BodyID id, BodyType value)
Examples
World.cpp.
Referenced by playrho::d2::World::GetType(), and playrho::d2::GetType().
GetType() [2/2]
BodyType GetType (const World & world, BodyID id) related
Gets the type of this body.
See also
SetType(World& world, BodyID id, BodyType value)
Examples
World.cpp.
GetVelocity() [1/2]
Velocity GetVelocity (const World & world, BodyID id)
Gets the velocity of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetVelocity(BodyID id, const Velocity& value).
Referenced by playrho::d2::World::GetVelocity().
GetVelocity() [2/2]
Velocity GetVelocity (const World & world, BodyID id) related
Gets the velocity of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetVelocity(BodyID id, const Velocity& value).
GetWorldCenter() [1/2]
Length2 GetWorldCenter (const World & world, BodyID id)
Get the world position of the center of mass of the specified body.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp.
Referenced by playrho::d2::ApplyLinearImpulse(), playrho::d2::GetLinearVelocity(), playrho::d2::World::GetWorldCenter(), and playrho::d2::SetForce().
GetWorldCenter() [2/2]
Length2 GetWorldCenter (const World & world, BodyID id) related
Get the world position of the center of mass of the specified body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetWorldIndex() [1/2]
BodyCounter GetWorldIndex (const World & world, const BodyID id) noexcept
Gets the world index for the given body.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp.
Referenced by playrho::d2::Dump().
GetWorldIndex() [2/2]
BodyCounter GetWorldIndex (const World & world, const BodyID id) related
Gets the world index for the given body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetWorldPoint() [1/2]
Length2 GetWorldPoint (const World & world, BodyID id, const Length2 localPoint) inline
Gets the world coordinates of a point given in coordinates relative to the body's origin.
Parameters
world World context.
id Body that the given point is relative to.
localPoint a point measured relative the the body's origin.
Returns
the same point expressed in world coordinates.
Exceptions
std::out_of_range If given an invalid body identifier.
GetWorldPoint() [2/2]
Length2 GetWorldPoint (const World & world, BodyID id, const Length2 localPoint) related
Gets the world coordinates of a point given in coordinates relative to the body's origin.
Parameters
world World context.
id Body that the given point is relative to.
localPoint a point measured relative the the body's origin.
Returns
the same point expressed in world coordinates.
Exceptions
std::out_of_range If given an invalid body identifier.
IsAccelerable() [1/2]
bool IsAccelerable (const World & world, BodyID id)
Is identified body "accelerable"?
Indicates whether the body is accelerable, i.e. whether it is effected by forces. Only Dynamic bodies are accelerable.
Returns
true if the body is accelerable, false otherwise.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp.
Referenced by playrho::d2::World::IsAccelerable(), playrho::d2::Body::SetAcceleration(), playrho::d2::Body::SetUnderActiveTime(), and playrho::d2::ShouldCollide().
IsAccelerable() [2/2]
bool IsAccelerable (const World & world, BodyID id) related
Is identified body "accelerable"?
Indicates whether the body is accelerable, i.e. whether it is effected by forces. Only Dynamic bodies are accelerable.
Returns
true if the body is accelerable, false otherwise.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
IsAwake() [1/2]
bool IsAwake (const World & world, BodyID id)
Gets the awake/asleep state of this body.
Warning
Being awake may or may not imply being speedable.
Returns
true if the body is awake.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp, and WorldContact.cpp.
Referenced by playrho::d2::Awaken(), playrho::d2::GetAwakeCount(), and playrho::d2::World::IsAwake().
IsAwake() [2/2]
bool IsAwake (const World & world, BodyID id) related
Gets the awake/asleep state of this body.
Warning
Being awake may or may not imply being speedable.
Returns
true if the body is awake.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
IsEnabled() [1/2]
bool IsEnabled (const World & world, BodyID id)
Gets the enabled/disabled state of the body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetEnabled(BodyID).
SetEnabled(World& world, BodyID id, bool value).
Referenced by playrho::d2::World::IsEnabled(), and playrho::d2::WorldImpl::UpdateContactTOIs().
IsEnabled() [2/2]
bool IsEnabled (const World & world, BodyID id) related
Gets the enabled/disabled state of the body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetEnabled(BodyID).
SetEnabled(World& world, BodyID id, bool value).
IsFixedRotation() [1/2]
bool IsFixedRotation (const World & world, BodyID id)
Gets whether the body has fixed rotation.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetFixedRotation.
Examples
WorldBody.cpp.
Referenced by playrho::d2::World::IsFixedRotation().
IsFixedRotation() [2/2]
bool IsFixedRotation (const World & world, BodyID id) related
Gets whether the body has fixed rotation.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetFixedRotation.
IsImpenetrable() [1/2]
bool IsImpenetrable (const World & world, BodyID id)
Is the body treated like a bullet for continuous collision detection?
Exceptions
std::out_of_range If given an invalid body identifier.
Referenced by playrho::d2::World::IsImpenetrable(), playrho::d2::WorldImpl::SolveToi(), and playrho::d2::WorldImpl::UpdateContactTOIs().
IsImpenetrable() [2/2]
bool IsImpenetrable (const World & world, BodyID id) related
Is the body treated like a bullet for continuous collision detection?
Exceptions
std::out_of_range If given an invalid body identifier.
IsMassDataDirty() [1/2]
bool IsMassDataDirty (const World & world, BodyID id)
Gets whether the body's mass-data is dirty.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp.
Referenced by playrho::d2::World::IsMassDataDirty().
IsMassDataDirty() [2/2]
bool IsMassDataDirty (const World & world, BodyID id) related
Gets whether the body's mass-data is dirty.
Exceptions
std::out_of_range If given an invalid body identifier.
IsSleepingAllowed() [1/2]
bool IsSleepingAllowed (const World & world, BodyID id)
Gets whether the identified body is allowed to sleep.
Exceptions
std::out_of_range If given an invalid body identifier.
Referenced by playrho::d2::World::IsSleepingAllowed().
IsSleepingAllowed() [2/2]
bool IsSleepingAllowed (const World & world, BodyID id) related
Gets whether the identified body is allowed to sleep.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
IsSpeedable() [1/2]
bool IsSpeedable (const World & world, BodyID id)
Is identified body "speedable".
Is the body able to have a non-zero speed associated with it. Kinematic and Dynamic bodies are speedable. Static bodies are not.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp.
Referenced by playrho::d2::Awaken(), playrho::d2::World::IsSpeedable(), playrho::d2::Body::SetSleepingAllowed(), and playrho::d2::Body::SetVelocity().
IsSpeedable() [2/2]
bool IsSpeedable (const World & world, BodyID id) related
Is identified body "speedable".
Is the body able to have a non-zero speed associated with it. Kinematic and Dynamic bodies are speedable. Static bodies are not.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
ResetMassData() [1/2]
void ResetMassData (World & world, BodyID id) related
Resets the mass data properties.
This resets the mass data to the sum of the mass properties of the fixtures.
Note
This method must be called after calling CreateFixture to update the body mass data properties unless SetMassData is used.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetMassData.
ResetMassData() [2/2]
void ResetMassData (World & world, BodyID id) inline
Resets the mass data properties.
This resets the mass data to the sum of the mass properties of the fixtures.
Note
This method must be called after calling CreateFixture to update the body mass data properties unless SetMassData is used.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetMassData.
Examples
WorldBody.cpp.
Referenced by playrho::d2::SetFixedRotation().
RotateAboutLocalPoint() [1/2]
void RotateAboutLocalPoint (World & world, BodyID id, Angle amount, Length2 localPoint)
Rotates a body a given amount around a point in body local coordinates.
This changes both the linear and angular positions of the body.
Note
Manipulating a body's position this way may cause non-physical behavior.
This is a convenience function that translates the local point into world coordinates and then calls the RotateAboutWorldPoint function.
Parameters
world The world in which the identified body exists.
id Body to rotate.
amount Amount to rotate body by (in counter-clockwise direction).
localPoint Point in local coordinates.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp.
RotateAboutLocalPoint() [2/2]
void RotateAboutLocalPoint (World & world, BodyID id, Angle amount, Length2 localPoint) related
Rotates a body a given amount around a point in body local coordinates.
This changes both the linear and angular positions of the body.
Note
Manipulating a body's position this way may cause non-physical behavior.
This is a convenience function that translates the local point into world coordinates and then calls the RotateAboutWorldPoint function.
Parameters
world The world in which the identified body exists.
id Body to rotate.
amount Amount to rotate body by (in counter-clockwise direction).
localPoint Point in local coordinates.
Exceptions
std::out_of_range If given an invalid body identifier.
RotateAboutWorldPoint() [1/2]
void RotateAboutWorldPoint (World & world, BodyID id, Angle amount, Length2 worldPoint)
Rotates a body a given amount around a point in world coordinates.
This changes both the linear and angular positions of the body.
Note
Manipulating a body's position this way may cause non-physical behavior.
Parameters
world The world in which the identified body exists.
id Body to rotate.
amount Amount to rotate body by (in counter-clockwise direction).
worldPoint Point in world coordinates.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp.
Referenced by playrho::d2::RotateAboutLocalPoint().
RotateAboutWorldPoint() [2/2]
void RotateAboutWorldPoint (World & world, BodyID id, Angle amount, Length2 worldPoint) related
Rotates a body a given amount around a point in world coordinates.
This changes both the linear and angular positions of the body.
Note
Manipulating a body's position this way may cause non-physical behavior.
Parameters
world The world in which the identified body exists.
id Body to rotate.
amount Amount to rotate body by (in counter-clockwise direction).
worldPoint Point in world coordinates.
Exceptions
std::out_of_range If given an invalid body identifier.
SetAcceleration() [1/8]
void SetAcceleration (World & world, BodyID id, Acceleration value)
Sets the accelerations on the given body.
Note
This has no effect on non-accelerable bodies.
A non-zero acceleration will also awaken the body.
Parameters
world The world in which the identified body's acceleration should be set.
id Body whose acceleration should be set.
value Acceleration value to set.
Exceptions
std::out_of_range If given an invalid body identifier.
SetAcceleration() [2/8]
void SetAcceleration (World & world, BodyID id, Acceleration value) related
Sets the accelerations on the given body.
Note
This has no effect on non-accelerable bodies.
A non-zero acceleration will also awaken the body.
Parameters
world The world in which the identified body's acceleration should be set.
id Body whose acceleration should be set.
value Acceleration value to set.
Exceptions
std::out_of_range If given an invalid body identifier.
SetAcceleration() [3/8]
void SetAcceleration (World & world, BodyID id, AngularAcceleration value)
Sets the rotational accelerations on the body.
Note
This has no effect on non-accelerable bodies.
A non-zero acceleration will also awaken the body.
Exceptions
std::out_of_range If given an invalid body identifier.
SetAcceleration() [4/8]
void SetAcceleration (World & world, BodyID id, AngularAcceleration value) related
Sets the rotational accelerations on the body.
Note
This has no effect on non-accelerable bodies.
A non-zero acceleration will also awaken the body.
Exceptions
std::out_of_range If given an invalid body identifier.
SetAcceleration() [5/8]
void SetAcceleration (World & world, BodyID id, LinearAcceleration2 linear, AngularAcceleration angular)
Sets the linear and rotational accelerations on the body.
Note
This has no effect on non-accelerable bodies.
A non-zero acceleration will also awaken the body.
Exceptions
std::out_of_range If given an invalid body identifier.
Referenced by playrho::d2::World::SetAcceleration().
SetAcceleration() [6/8]
void SetAcceleration (World & world, BodyID id, LinearAcceleration2 linear, AngularAcceleration angular) related
Sets the linear and rotational accelerations on the body.
Note
This has no effect on non-accelerable bodies.
A non-zero acceleration will also awaken the body.
Exceptions
std::out_of_range If given an invalid body identifier.
SetAcceleration() [7/8]
void SetAcceleration (World & world, BodyID id, LinearAcceleration2 value)
Sets the linear accelerations on the body.
Note
This has no effect on non-accelerable bodies.
A non-zero acceleration will also awaken the body.
Exceptions
std::out_of_range If given an invalid body identifier.
SetAcceleration() [8/8]
void SetAcceleration (World & world, BodyID id, LinearAcceleration2 value) related
Sets the linear accelerations on the body.
Note
This has no effect on non-accelerable bodies.
A non-zero acceleration will also awaken the body.
Exceptions
std::out_of_range If given an invalid body identifier.
SetAccelerations() [1/4]
template<class F > void SetAccelerations (World & world, F fn) related
Sets the accelerations of all the world's bodies.
Parameters
world World instance to set the acceleration of all contained bodies for.
fn Function or functor with a signature like: Acceleration (*fn)(const Body& body).
SetAccelerations() [2/4]
template<class F > void SetAccelerations (World & world, F fn)
Sets the accelerations of all the world's bodies.
Parameters
world World instance to set the acceleration of all contained bodies for.
fn Function or functor with a signature like: Acceleration (*fn)(const Body& body).
SetAccelerations() [3/4]
void SetAccelerations (World & world, LinearAcceleration2 acceleration) noexcept
Sets the accelerations of all the world's bodies to the given value.
Note
This will leave the angular acceleration alone.
SetAccelerations() [4/4]
void SetAccelerations (World & world, LinearAcceleration2 acceleration) related
Sets the accelerations of all the world's bodies to the given value.
Note
This will leave the angular acceleration alone.
SetAngle() [1/2]
void SetAngle (World & world, BodyID id, Angle value)
Sets the body's angular orientation.
This instantly adjusts the body to be at the new angular orientation.
Warning
Manipulating a body's angle this way can cause non-physical behavior!
Parameters
world The world in which the identified body's angle should be set.
id Body to move.
value Valid world angle of the body's local origin. Behavior is undefined if value is invalid.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
Body::SetTransform
Examples
WorldBody.cpp.
SetAngle() [2/2]
void SetAngle (World & world, BodyID id, Angle value) related
Sets the body's angular orientation.
This instantly adjusts the body to be at the new angular orientation.
Warning
Manipulating a body's angle this way can cause non-physical behavior!
Parameters
world The world in which the identified body's angle should be set.
id Body to move.
value Valid world angle of the body's local origin. Behavior is undefined if value is invalid.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
Body::SetTransform
SetAngularDamping() [1/2]
void SetAngularDamping (World & world, BodyID id, NonNegative< Frequency > angularDamping)
Sets the angular damping of the body.
Exceptions
std::out_of_range If given an invalid body identifier.
Referenced by playrho::d2::World::SetAngularDamping().
SetAngularDamping() [2/2]
void SetAngularDamping (World & world, BodyID id, NonNegative< Frequency > angularDamping) related
Sets the angular damping of the body.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
SetAwake() [1/2]
void SetAwake (World & world, BodyID id)
Wakes up the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp, and WorldContact.cpp.
Referenced by playrho::d2::Awaken(), and playrho::d2::World::SetAwake().
SetAwake() [2/2]
void SetAwake (World & world, BodyID id) related
Wakes up the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
SetEnabled() [1/2]
void SetEnabled (World & world, BodyID id, bool value)
Sets the enabled state of the body.
A disabled body is not simulated and cannot be collided with or woken up. If you pass a flag of true, all fixtures will be added to the broad-phase. If you pass a flag of false, all fixtures will be removed from the broad-phase and all contacts will be destroyed. Fixtures and joints are otherwise unaffected.
Note
A disabled body is still owned by a World object and remains in the world's body container.
You may continue to create/destroy fixtures and joints on disabled bodies.
Fixtures on a disabled body are implicitly disabled and will not participate in collisions, ray-casts, or queries.
Joints connected to a disabled body are implicitly disabled.
Exceptions
WrongState If call would change body's state when world is locked.
std::out_of_range If given an invalid body identifier.
Postcondition
IsEnabled() returns the state given to this function.
See also
IsEnabled(BodyID).
IsEnabled(const World& world, BodyID id).
Examples
WorldBody.cpp, and WorldContact.cpp.
Referenced by playrho::d2::World::SetEnabled(), and playrho::d2::SetEnabled().
SetEnabled() [2/2]
void SetEnabled (World & world, BodyID id, bool value) related
Sets the enabled state of the body.
A disabled body is not simulated and cannot be collided with or woken up. If you pass a flag of true, all fixtures will be added to the broad-phase. If you pass a flag of false, all fixtures will be removed from the broad-phase and all contacts will be destroyed. Fixtures and joints are otherwise unaffected.
Note
A disabled body is still owned by a World object and remains in the world's body container.
You may continue to create/destroy fixtures and joints on disabled bodies.
Fixtures on a disabled body are implicitly disabled and will not participate in collisions, ray-casts, or queries.
Joints connected to a disabled body are implicitly disabled.
Exceptions
WrongState If call would change body's state when world is locked.
std::out_of_range If given an invalid body identifier.
Postcondition
IsEnabled() returns the state given to this function.
See also
IsEnabled(BodyID).
IsEnabled(const World& world, BodyID id).
SetFixedRotation() [1/2]
void SetFixedRotation (World & world, BodyID id, bool value)
Sets this body to have fixed rotation.
Exceptions
std::out_of_range If given an invalid body identifier.
Note
This causes the mass to be reset.
Examples
WorldBody.cpp.
Referenced by playrho::d2::World::SetFixedRotation().
SetFixedRotation() [2/2]
void SetFixedRotation (World & world, BodyID id, bool value) related
Sets this body to have fixed rotation.
Exceptions
std::out_of_range If given an invalid body identifier.
Note
This causes the mass to be reset.
SetForce() [1/2]
void SetForce (World & world, BodyID id, Force2 force, Length2 point) inline noexcept
Sets the given amount of force at the given point to the given body.
Exceptions
std::out_of_range If given an invalid body identifier.
SetForce() [2/2]
void SetForce (World & world, BodyID id, Force2 force, Length2 point) related
Sets the given amount of force at the given point to the given body.
Exceptions
std::out_of_range If given an invalid body identifier.
SetImpenetrable() [1/4]
void SetImpenetrable (World & world, BodyID id)
Sets the impenetrable status of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
Referenced by playrho::d2::World::SetImpenetrable(), and playrho::d2::SetImpenetrable().
SetImpenetrable() [2/4]
void SetImpenetrable (World & world, BodyID id) related
Sets the impenetrable status of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
SetImpenetrable() [3/4]
void SetImpenetrable (World & world, BodyID id, bool value) related
Convenience function that sets/unsets the impenetrable status of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
SetImpenetrable() [4/4]
void SetImpenetrable (World & world, BodyID id, bool value) inline
Convenience function that sets/unsets the impenetrable status of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
SetLinearDamping() [1/2]
void SetLinearDamping (World & world, BodyID id, NonNegative< Frequency > linearDamping)
Sets the linear damping of the body.
Exceptions
std::out_of_range If given an invalid body identifier.
Referenced by playrho::d2::World::SetLinearDamping().
SetLinearDamping() [2/2]
void SetLinearDamping (World & world, BodyID id, NonNegative< Frequency > linearDamping) related
Sets the linear damping of the body.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
SetLocation() [1/2]
void SetLocation (World & world, BodyID id, Length2 value)
Sets the body's location.
This instantly adjusts the body to be at the new location.
Warning
Manipulating a body's location this way can cause non-physical behavior!
Parameters
world The world in which the identified body's location should be set.
id Body to move.
value Valid world location of the body's local origin. Behavior is undefined if value is invalid.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
Body::SetTransform
Examples
WorldBody.cpp.
SetLocation() [2/2]
void SetLocation (World & world, BodyID id, Length2 value) related
Sets the body's location.
This instantly adjusts the body to be at the new location.
Warning
Manipulating a body's location this way can cause non-physical behavior!
Parameters
world The world in which the identified body's location should be set.
id Body to move.
value Valid world location of the body's local origin. Behavior is undefined if value is invalid.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
Body::SetTransform
Examples
World.cpp.
SetMassData() [1/2]
void SetMassData (World & world, BodyID id, const MassData & massData)
Sets the mass properties to override the mass properties of the fixtures.
Note
This changes the center of mass position.
Creating or destroying fixtures can also alter the mass.
This function has no effect if the body isn't dynamic.
Parameters
world The world in which the identified body exists.
id Identifier of the body.
massData the mass properties.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp.
Referenced by playrho::d2::WorldImpl::CreateFixture(), playrho::d2::WorldImpl::Destroy(), playrho::d2::WorldImpl::DestroyFixtures(), playrho::d2::ResetMassData(), playrho::d2::World::SetMassData(), and playrho::d2::WorldImpl::SetType().
SetMassData() [2/2]
void SetMassData (World & world, BodyID id, const MassData & massData) related
Sets the mass properties to override the mass properties of the fixtures.
Note
This changes the center of mass position.
Creating or destroying fixtures can also alter the mass.
This function has no effect if the body isn't dynamic.
Parameters
world The world in which the identified body exists.
id Identifier of the body.
massData the mass properties.
Exceptions
std::out_of_range If given an invalid body identifier.
SetSleepingAllowed() [1/2]
void SetSleepingAllowed (World & world, BodyID , bool value)
Sets whether the identified body is allowed to sleep.
Exceptions
std::out_of_range If given an invalid body identifier.
Referenced by playrho::d2::World::SetSleepingAllowed().
SetSleepingAllowed() [2/2]
void SetSleepingAllowed (World & world, BodyID , bool value) related
Sets whether the identified body is allowed to sleep.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
SetTorque() [1/2]
void SetTorque (World & world, BodyID id, Torque torque) inline noexcept
Sets the given amount of torque to the given body.
Exceptions
std::out_of_range If given an invalid body identifier.
SetTorque() [2/2]
void SetTorque (World & world, BodyID id, Torque torque) related
Sets the given amount of torque to the given body.
Exceptions
std::out_of_range If given an invalid body identifier.
SetTransform() [1/2]
void SetTransform (World & world, BodyID id, Length2 location, Angle angle) related
Sets the position of the body's origin and rotation.
This instantly adjusts the body to be at the new position and new orientation.
Warning
Manipulating a body's transform can cause non-physical behavior!
Note
Contacts are updated on the next call to World::Step.
Parameters
world The world in which the identified body's transform should be set.
id Body whose transform is to be set.
location Valid world location of the body's local origin. Behavior is undefined if value is invalid.
angle Valid world rotation. Behavior is undefined if value is invalid.
Exceptions
std::out_of_range If given an invalid body identifier.
SetTransform() [2/2]
void SetTransform (World & world, BodyID id, Length2 location, Angle angle) inline
Sets the position of the body's origin and rotation.
This instantly adjusts the body to be at the new position and new orientation.
Warning
Manipulating a body's transform can cause non-physical behavior!
Note
Contacts are updated on the next call to World::Step.
Parameters
world The world in which the identified body's transform should be set.
id Body whose transform is to be set.
location Valid world location of the body's local origin. Behavior is undefined if value is invalid.
angle Valid world rotation. Behavior is undefined if value is invalid.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
WorldBody.cpp.
Referenced by playrho::d2::RotateAboutWorldPoint(), playrho::d2::SetAngle(), and playrho::d2::SetLocation().
SetTransformation() [1/2]
void SetTransformation (World & world, BodyID id, Transformation xfm)
Sets the body's transformation.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
GetTransformation
Examples
WorldBody.cpp.
Referenced by playrho::d2::SetTransform(), and playrho::d2::World::SetTransformation().
SetTransformation() [2/2]
void SetTransformation (World & world, BodyID id, Transformation xfm) related
Sets the body's transformation.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
GetTransformation
SetType() [1/2]
void SetType (World & world, BodyID id, BodyType value)
Sets the type of the given body.
Note
This may alter the body's mass and velocity.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid body identifier.
See also
GetType(const World& world, BodyID id)
Examples
World.cpp, and WorldBody.cpp.
Referenced by playrho::d2::World::SetType().
SetType() [2/2]
void SetType (World & world, BodyID id, BodyType value) related
Sets the type of the given body.
Note
This may alter the body's mass and velocity.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid body identifier.
See also
GetType(const World& world, BodyID id)
Examples
World.cpp.
SetVelocity() [1/6]
void SetVelocity (World & world, BodyID id, AngularVelocity value)
Sets the velocity of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
SetVelocity() [2/6]
void SetVelocity (World & world, BodyID id, AngularVelocity value) related
Sets the velocity of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
SetVelocity() [3/6]
void SetVelocity (World & world, BodyID id, const LinearVelocity2 & value)
Sets the velocity of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
SetVelocity() [4/6]
void SetVelocity (World & world, BodyID id, const LinearVelocity2 & value) related
Sets the velocity of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
SetVelocity() [5/6]
void SetVelocity (World & world, BodyID id, const Velocity & value)
Sets the body's velocity (linear and angular velocity).
Note
This method does nothing if this body is not speedable.
A non-zero velocity will awaken this body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
GetVelocity(BodyID), SetAwake, SetUnderActiveTime.
GetVelocity(const World& world, BodyID id)
Referenced by playrho::d2::World::SetVelocity().
SetVelocity() [6/6]
void SetVelocity (World & world, BodyID id, const Velocity & value) related
Sets the body's velocity (linear and angular velocity).
Note
This method does nothing if this body is not speedable.
A non-zero velocity will awaken this body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
GetVelocity(BodyID), SetAwake, SetUnderActiveTime.
GetVelocity(const World& world, BodyID id)
ShouldCollide() [1/2]
bool ShouldCollide (const World & world, BodyID lhs, BodyID rhs)
Should collide.
Determines whether a body should possibly be able to collide with the other body.
Returns
true if either body is dynamic and no joint prevents collision, false otherwise.
Exceptions
std::out_of_range If given an invalid body identifier.
ShouldCollide() [2/2]
bool ShouldCollide (const World & world, BodyID lhs, BodyID rhs) related
Should collide.
Determines whether a body should possibly be able to collide with the other body.
Returns
true if either body is dynamic and no joint prevents collision, false otherwise.
Exceptions
std::out_of_range If given an invalid body identifier.
UnsetAwake() [1/2]
void UnsetAwake (World & world, BodyID id)
Sleeps the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
IsAwake(BodyID id), SetAwake(BodyID id).
Examples
WorldBody.cpp, and WorldContact.cpp.
Referenced by playrho::d2::World::UnsetAwake().
UnsetAwake() [2/2]
void UnsetAwake (World & world, BodyID id) related
Sleeps the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
IsAwake(BodyID id), SetAwake(BodyID id).
UnsetImpenetrable() [1/2]
void UnsetImpenetrable (World & world, BodyID id)
Unsets the impenetrable status of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
Referenced by playrho::d2::SetImpenetrable(), and playrho::d2::World::UnsetImpenetrable().
UnsetImpenetrable() [2/2]
void UnsetImpenetrable (World & world, BodyID id) related
Unsets the impenetrable status of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.