PlayRho: playrho::detail Namespace Reference
playrho::detail Namespace Reference
Mathematical Functions For Fixed Types
Name space for internal/detail related PlayRho names.
Classes
struct AABB
N-dimensional Axis Aligned Bounding Box.
struct Defaults
Defaults object for real types.
struct Defaults< Fixed< std::int32_t, FRACTION_BITS > >
Specialization of defaults object for fixed point types.
struct LengthIndices
Length and vertex counter array of indices.
struct MassData
Mass data.
struct SeparationInfo
Separation information.
Functions
template<std::size_t N>
PLAYRHO_CONSTEXPR bool operator== (const AABB< N > &lhs, const AABB< N > &rhs) noexcept
Gets whether the two AABB objects are equal.
template<std::size_t N>
PLAYRHO_CONSTEXPR bool operator!= (const AABB< N > &lhs, const AABB< N > &rhs) noexcept
Gets whether the two AABB objects are not equal.
template<std::size_t N>
bool operator< (const AABB< N > &lhs, const AABB< N > &rhs) noexcept
Less-than operator.
template<std::size_t N>
bool operator<= (const AABB< N > &lhs, const AABB< N > &rhs) noexcept
Less-than or equal-to operator.
template<std::size_t N>
bool operator> (const AABB< N > &lhs, const AABB< N > &rhs) noexcept
Greater-than operator.
template<std::size_t N>
bool operator>= (const AABB< N > &lhs, const AABB< N > &rhs) noexcept
Greater-than or equal-to operator.
template<std::size_t N>
PLAYRHO_CONSTEXPR bool TestOverlap (const AABB< N > &a, const AABB< N > &b) noexcept
Tests for overlap between two axis aligned bounding boxes.
template<std::size_t N>
PLAYRHO_CONSTEXPR AABB< N > GetIntersectingAABB (const AABB< N > &a, const AABB< N > &b) noexcept
Gets the intersecting AABB of the two given AABBs'.
template<std::size_t N>
PLAYRHO_CONSTEXPR Vector< Length, N > GetCenter (const AABB< N > &aabb) noexcept
Gets the center of the AABB.
template<std::size_t N>
PLAYRHO_CONSTEXPR Vector< Length, N > GetDimensions (const AABB< N > &aabb) noexcept
Gets dimensions of the given AABB.
template<std::size_t N>
PLAYRHO_CONSTEXPR Vector< Length, N > GetExtents (const AABB< N > &aabb) noexcept
Gets the extents of the AABB (half-widths).
template<std::size_t N>
PLAYRHO_CONSTEXPR bool Contains (const AABB< N > &a, const AABB< N > &b) noexcept
Checks whether the first AABB fully contains the second AABB.
template<std::size_t N>
PLAYRHO_CONSTEXPR AABB< N > & Include (AABB< N > &var, const Vector< Length, N > &value) noexcept
Includes the given location into the given AABB.
template<std::size_t N>
PLAYRHO_CONSTEXPR AABB< N > & Include (AABB< N > &var, const AABB< N > &val) noexcept
Includes the second AABB into the first one.
template<std::size_t N>
PLAYRHO_CONSTEXPR AABB< N > & Move (AABB< N > &var, const Vector< Length, N > value) noexcept
Moves the given AABB by the given value.
template<std::size_t N>
PLAYRHO_CONSTEXPR AABB< N > & Fatten (AABB< N > &var, const NonNegative< Length > amount) noexcept
Fattens an AABB by the given amount.
template<std::size_t N>
PLAYRHO_CONSTEXPR AABB< N > GetDisplacedAABB (AABB< N > aabb, const Vector< Length, N > displacement)
Gets the AABB that the result of displacing the given AABB by the given displacement amount.
template<std::size_t N>
PLAYRHO_CONSTEXPR AABB< N > GetFattenedAABB (AABB< N > aabb, const Length amount)
Gets the fattened AABB result.
template<std::size_t N>
PLAYRHO_CONSTEXPR AABB< N > GetMovedAABB (AABB< N > aabb, const Vector< Length, N > value) noexcept
Gets the result of moving the given AABB by the given value.
template<std::size_t N>
PLAYRHO_CONSTEXPR AABB< N > GetEnclosingAABB (AABB< N > a, const AABB< N > &b)
Gets the AABB that minimally encloses the given AABBs.
template<std::size_t N>
PLAYRHO_CONSTEXPR Vector< Length, N > GetLowerBound (const AABB< N > &aabb) noexcept
Gets the lower bound.
template<std::size_t N>
PLAYRHO_CONSTEXPR Vector< Length, N > GetUpperBound (const AABB< N > &aabb) noexcept
Gets the upper bound.
template<std::size_t N>
inline ::std::ostream & operator<< (::std::ostream &os, const AABB< N > &value)
Output stream operator.
template<std::size_t N>
PLAYRHO_CONSTEXPR bool operator== (MassData< N > lhs, MassData< N > rhs)
Equality operator for mass data.
template<std::size_t N>
PLAYRHO_CONSTEXPR bool operator!= (MassData< N > lhs, MassData< N > rhs)
Inequality operator for mass data.
constexpr auto factorial (std::int64_t n)
Computes the factorial.
template<typename BT , unsigned int FB, int N = 6>
constexpr Fixed< BT, FB > exp (Fixed< BT, FB > arg)
Computes Euler's number raised to the given power argument.
template<typename BT , unsigned int FB, int N = 6>
Fixed< BT, FB > log (Fixed< BT, FB > arg)
Computes the natural logarithm.
template<typename BT , unsigned int FB, int N = 5>
constexpr Fixed< BT, FB > sin (Fixed< BT, FB > arg)
Computes the sine of the given argument via Maclaurin series approximation.
template<typename BT , unsigned int FB, int N = 5>
constexpr Fixed< BT, FB > cos (Fixed< BT, FB > arg)
Computes the cosine of the given argument via Maclaurin series approximation.
template<typename BT , unsigned int FB, int N = 5>
constexpr Fixed< BT, FB > atan (Fixed< BT, FB > arg)
Computes the arctangent of the given argument via Maclaurin series approximation.
template<typename BT , unsigned int FB>
auto AngularNormalize (Fixed< BT, FB > angleInRadians)
Normalizes the given angular argument.
Variables
template<typename BT , unsigned int FB>
constexpr const auto FixedPi = Fixed<BT, FB>{3.14159265358979323846264338327950288}
Fixed point pi value.
Detailed Description
Name space for internal/detail related PlayRho names.
Function Documentation
atan()
template<typename BT , unsigned int FB, int N = 5> constexpr Fixed<BT, FB> playrho::detail::atan (Fixed< BT, FB > arg) inline
Computes the arctangent of the given argument via Maclaurin series approximation.
See also
http://en.cppreference.com/w/cpp/numeric/math/atan
https://en.wikipedia.org/wiki/Taylor_series
Contains()
template<std::size_t N> PLAYRHO_CONSTEXPR bool Contains (const AABB< N > & a, const AABB< N > & b) inline noexcept
Checks whether the first AABB fully contains the second AABB.
Whether the first AABB contains the entirety of the second AABB where containment is defined as being equal-to or within an AABB.
Note
The "unset" AABB is contained by all valid AABBs including the "unset" AABB itself.
Parameters
a AABB to test whether it contains the second AABB.
b AABB to test whether it's contained by the first AABB.
cos()
template<typename BT , unsigned int FB, int N = 5> constexpr Fixed<BT, FB> playrho::detail::cos (Fixed< BT, FB > arg) inline
Computes the cosine of the given argument via Maclaurin series approximation.
See also
https://en.wikipedia.org/wiki/Taylor_series
exp()
template<typename BT , unsigned int FB, int N = 6> constexpr Fixed<BT, FB> playrho::detail::exp (Fixed< BT, FB > arg) inline
Computes Euler's number raised to the given power argument.
Note
Uses Maclaurin series approximation.
See also
http://en.cppreference.com/w/cpp/numeric/math/exp
https://en.wikipedia.org/wiki/Taylor_series
https://en.wikipedia.org/wiki/Exponentiation
https://en.wikipedia.org/wiki/Exponential_function
Fatten()
template<std::size_t N> PLAYRHO_CONSTEXPR AABB< N > & Fatten (AABB< N > & var, const NonNegative< Length > amount) inline noexcept
Fattens an AABB by the given amount.
Referenced by GetFattenedAABB().
GetCenter()
template<std::size_t N> PLAYRHO_CONSTEXPR Vector< Length, N > GetCenter (const AABB< N > & aabb) inline noexcept
Gets the center of the AABB.
GetDimensions()
template<std::size_t N> PLAYRHO_CONSTEXPR Vector< Length, N > GetDimensions (const AABB< N > & aabb) inline noexcept
Gets dimensions of the given AABB.
Referenced by GetExtents().
GetDisplacedAABB()
template<std::size_t N> PLAYRHO_CONSTEXPR AABB< N > GetDisplacedAABB (AABB< N > aabb, const Vector< Length, N > displacement) inline
Gets the AABB that the result of displacing the given AABB by the given displacement amount.
GetEnclosingAABB()
template<std::size_t N> PLAYRHO_CONSTEXPR AABB< N > GetEnclosingAABB (AABB< N > a, const AABB< N > & b) inline
Gets the AABB that minimally encloses the given AABBs.
GetExtents()
template<std::size_t N> PLAYRHO_CONSTEXPR Vector< Length, N > GetExtents (const AABB< N > & aabb) inline noexcept
Gets the extents of the AABB (half-widths).
GetFattenedAABB()
template<std::size_t N> PLAYRHO_CONSTEXPR AABB< N > GetFattenedAABB (AABB< N > aabb, const Length amount) inline
Gets the fattened AABB result.
GetLowerBound()
template<std::size_t N> PLAYRHO_CONSTEXPR Vector< Length, N > GetLowerBound (const AABB< N > & aabb) inline noexcept
Gets the lower bound.
GetMovedAABB()
template<std::size_t N> PLAYRHO_CONSTEXPR AABB< N > GetMovedAABB (AABB< N > aabb, const Vector< Length, N > value) inline noexcept
Gets the result of moving the given AABB by the given value.
GetUpperBound()
template<std::size_t N> PLAYRHO_CONSTEXPR Vector< Length, N > GetUpperBound (const AABB< N > & aabb) inline noexcept
Gets the upper bound.
Include() [1/2]
template<std::size_t N> PLAYRHO_CONSTEXPR AABB< N > & Include (AABB< N > & var, const Vector< Length, N > & value) inline noexcept
Includes the given location into the given AABB.
Referenced by GetEnclosingAABB().
Include() [2/2]
template<std::size_t N> PLAYRHO_CONSTEXPR AABB< N > & Include (AABB< N > & var, const AABB< N > & val) inline noexcept
Includes the second AABB into the first one.
Note
If an unset AABB is added to the first AABB, the result will be the first AABB.
If the first AABB is unset and another AABB is added to it, the result will be the other AABB.
log()
template<typename BT , unsigned int FB, int N = 6> Fixed<BT, FB> playrho::detail::log (Fixed< BT, FB > arg)
Computes the natural logarithm.
Note
A better method may be explained in https://math.stackexchange.com/a/61236/408405
See also
http://en.cppreference.com/w/cpp/numeric/math/log
https://en.wikipedia.org/wiki/Natural_logarithm
operator!=() [1/2]
template<std::size_t N> PLAYRHO_CONSTEXPR bool operator!= (MassData< N > lhs, MassData< N > rhs) inline
Inequality operator for mass data.
operator!=() [2/2]
template<std::size_t N> PLAYRHO_CONSTEXPR bool operator!= (const AABB< N > & lhs, const AABB< N > & rhs) inline noexcept
Gets whether the two AABB objects are not equal.
Returns
true if the two values are not equal, false otherwise.
operator<()
template<std::size_t N> bool operator< (const AABB< N > & lhs, const AABB< N > & rhs) inline noexcept
Less-than operator.
operator<=()
template<std::size_t N> bool operator<= (const AABB< N > & lhs, const AABB< N > & rhs) inline noexcept
Less-than or equal-to operator.
operator==() [1/2]
template<std::size_t N> PLAYRHO_CONSTEXPR bool operator== (MassData< N > lhs, MassData< N > rhs) inline
Equality operator for mass data.
operator==() [2/2]
template<std::size_t N> PLAYRHO_CONSTEXPR bool operator== (const AABB< N > & lhs, const AABB< N > & rhs) inline noexcept
Gets whether the two AABB objects are equal.
Returns
true if the two values are equal, false otherwise.
operator>()
template<std::size_t N> bool operator> (const AABB< N > & lhs, const AABB< N > & rhs) inline noexcept
Greater-than operator.
operator>=()
template<std::size_t N> bool operator>= (const AABB< N > & lhs, const AABB< N > & rhs) inline noexcept
Greater-than or equal-to operator.
sin()
template<typename BT , unsigned int FB, int N = 5> constexpr Fixed<BT, FB> playrho::detail::sin (Fixed< BT, FB > arg) inline
Computes the sine of the given argument via Maclaurin series approximation.
See also
https://en.wikipedia.org/wiki/Taylor_series
TestOverlap()
template<std::size_t N> PLAYRHO_CONSTEXPR bool TestOverlap (const AABB< N > & a, const AABB< N > & b) inline noexcept
Tests for overlap between two axis aligned bounding boxes.
Note
This function's complexity is constant.