PlayRho: playrho Namespace Reference
playrho Namespace Reference
Classes
struct AABB
N-dimensional Axis Aligned Bounding Box.
struct Acceleration
Acceleration related data structure.
class AllocatedArray
Allocated Array.
class ArrayList
Array list.
class BlockAllocator
Block allocator.
struct BlockDeallocator
Block deallocator.
class Body
Physical entity that exists within a World.
class BodyAtty
Body attorney.
class BodyConstraint
Body Constraint.
struct BodyDef
Body Definition.
class BoundedValue
Bounded value.
class ChainShapeConf
Chain shape configuration.
struct ClipVertex
Clip vertex.
class ConstJointVisitor
Constant joint visitor interface class.
struct ConstraintSolverConf
Constraint solver configuration data.
class Contact
A potential contact between the chidren of two Fixture objects.
class ContactAtty
Contact attorney.
struct ContactFeature
Contact Feature.
class ContactFilter
Implement this class to provide collision filtering. In other words, you can implement this class if you want finer control over contact creation.
class ContactImpulsesList
Contact Impulse.
class ContactKey
Key value class for contacts.
class ContactListener
A pure-virtual interface for "listeners" for contacts.
class ConvexHull
Convex hull.
class DestructionListener
Joints and fixtures are destroyed when their associated body is destroyed. Implement this listener so that you may nullify references to these joints and shapes.
struct DiskShapeConf
Disk shape configuration.
struct DistanceConf
Distance Configuration.
class DistanceJoint
Distance Joint.
struct DistanceJointDef
Distance joint definition.
struct DistanceOutput
Distance Output.
class DistanceProxy
Distance Proxy.
class DynamicTree
A dynamic AABB tree broad-phase.
class EdgeShapeConf
Edge shape configuration.
struct Filter
A holder for contact filtering data.
class Fixed
Template class for fixed-point numbers.
class Fixture
An association between a body and a shape.
class FixtureAtty
Fixture attorney.
struct FixtureDef
Fixture definition.
struct FixtureProxy
Fixture proxy.
class FlagGuard
Flag guard type.
class FrictionJoint
Friction joint.
struct FrictionJointDef
Friction joint definition.
class FunctionalJointVisitor
Functional joint visitor class.
class GearJoint
Gear joint.
struct GearJointDef
Gear joint definition.
class GrowableStack
This is a growable LIFO stack with an initial capacity of N. If the stack size exceeds the initial capacity, the heap is used to increase the size of the stack.
struct HasType
Has-type trait template class.
struct HasType< T, std::tuple< T, Ts... > >
Has-type trait true class.
struct HasType< T, std::tuple< U, Ts... > >
Has-type trait template super class.
struct HasType< T, std::tuple<> >
Has-type trait template class specialized for std::tuple classes.
struct IndexPairDistance
Index pair distance.
class Interval
Interval template type.
class InvalidArgument
Invalid argument logic error.
struct IsArithmetic
Template for determining if the given type is an "arithmetic" type.
struct IsArithmetic< T, VoidT< decltype(T{}+T{}), decltype(T{} - T{}), decltype(T{} *T{}), decltype(T{}/T{}) > >
Template specialization for valid/acceptable "arithmetic" types.
struct Island
Definition of a self-contained constraint "island".
class Joint
Base joint class.
class JointAtty
Joint attorney.
struct JointBuilder
Joint builder definition structure.
struct JointDef
Abstract base Joint definition class.
class JointKey
Joint key.
class JointVisitor
Vistor interface for Joint instances.
class LengthError
Length based logic error.
class Manifold
A collision description for the collision two convex shapes.
struct MassData
Mass data.
class MotorJoint
Motor joint.
struct MotorJointDef
Motor joint definition.
class MouseJoint
Mouse Joint.
struct MouseJointDef
Mouse joint definition.
struct MovementConf
Movement configuration.
struct MultiShapeConf
The "multi-shape" shape configuration.
class OptionalValue
Optional value template class.
struct PointStates
Point states.
class PolygonShapeConf
Polygon shape configuration.
struct Position
Positional data structure.
class PositionConstraint
Contact Position Constraint.
struct PositionSolution
Solution for position constraint.
struct PositionSolverManifold
Position solver manifold.
struct PreStepStats
Pre-phase per-step statistics.
class PrismaticJoint
Prismatic Joint.
struct PrismaticJointDef
Prismatic joint definition.
class PulleyJoint
Pulley joint.
struct PulleyJointDef
Pulley joint definition.
class Range
Template range value class.
struct RayCastHit
Ray-cast hit data.
struct RayCastInput
Ray-cast input data.
struct RegStepStats
Regular-phase per-step statistics.
class RevoluteJoint
Revolute Joint.
struct RevoluteJointDef
Revolute joint definition.
class RopeJoint
Rope joint.
struct RopeJointDef
Rope joint definition.
class SeparationFinder
Separation finder.
class Shape
Shape.
struct ShapeConf
Shape configuration structure.
struct ShapeDef
Base configuration for initializing shapes.
struct ShapeDefBuilder
Builder configuration structure.
class Simplex
An encapsulation of a point, line segment, or triangle.
class SimplexEdge
Simplex edge.
class SizedRange
Template sized range value class.
class Span
A C++ encapsulation of an array and its size.
class StackAllocator
Stack allocator.
class StepConf
Step configuration.
struct StepStats
Per-step statistics.
class StrongTyped
Strong type template.
class Sweep
Description of a "sweep" of motion.
struct ToiConf
Time of impact configuration.
struct TOIOutput
Output data for time of impact.
struct ToiStepStats
TOI-phase per-step statistics.
struct Transformation
Describes a geometric transformation.
class TypeJointVisitor
Typing JointVisitor.
class UnitVec2
2-D unit vector.
struct ValueCheckHelper
Value check helper.
struct ValueCheckHelper< T, typename std::enable_if< std::is_arithmetic< T >::value >::type >
Specialization of the value check helper.
struct Vector
Vector.
struct Velocity
Velocity related data structure.
class VelocityConstraint
Contact velocity constraint.
struct Version
Version numbering scheme.
class VertexSet
Vertex Set.
struct Voidify
Voiding template class.
class WeldJoint
Weld joint.
struct WeldJointDef
Weld joint definition.
class WheelJoint
Wheel joint.
struct WheelJointDef
Wheel joint definition.
struct Wider
Wider data type obtainer.
struct Wider< double >
Specialization of the Wider trait for double.
struct Wider< Fixed32 >
Specialization of the Wider trait for Fixed32 type.
struct Wider< float >
Specialization of the Wider trait for float.
struct Wider< std::int16_t >
Specialization of the Wider trait for signed 16-bit integers.
struct Wider< std::int32_t >
Specialization of the Wider trait for signed 32-bit integers.
struct Wider< std::int64_t >
Specialization of the Wider trait for signed 64-bit integers.
struct Wider< std::int8_t >
Specialization of the Wider trait for signed 8-bit integers.
struct Wider< std::uint16_t >
Specialization of the Wider trait for unsigned 16-bit integers.
struct Wider< std::uint32_t >
Specialization of the Wider trait for unsigned 32-bit integers.
struct Wider< std::uint64_t >
Specialization of the Wider trait for unsigned 64-bit integers.
struct Wider< std::uint8_t >
Specialization of the Wider trait for unsigned 8-bit integers.
class World
Definition of an independent and simulatable "world".
struct WorldDef
World construction definitions.
class WorldManifold
Essentially a Manifold expressed in world coordinate terms.
class WrongState
Wrong state logic error.
Typedefs
using AABB2D = AABB< 2 >
2-Dimensional Axis Aligned Bounding Box.
using ClipList = ArrayList< ClipVertex, MaxManifoldPoints >
Clip list for ClipSegmentToLine.
using PairLength2 = std::pair< Length2, Length2 >
Pair of Length2 values.
using DynamicTreeSizeCB = std::function< DynamicTreeOpcode(DynamicTree::Size)>
Query callback type.
using IndexPair = std::pair< VertexCounter, VertexCounter >
Index pair.
using IndexPair3 = std::array< IndexPair, MaxSimplexEdges >
Index pairs.
using RayCastOutput = Optional< RayCastHit >
Ray cast output.
using SimplexEdges = ArrayList< SimplexEdge, MaxSimplexEdges, std::remove_const< decltype(MaxSimplexEdges)>::type >
Simplex edge collection.
template<typename T >
using NonNegative = typename std::enable_if<!std::is_pointer< T >::value, BoundedValue< T, LoValueCheck::ZeroOrMore, HiValueCheck::Any > >::type
Non negative bounded value type.
template<typename T >
using NonPositive = BoundedValue< T, LoValueCheck::Any, HiValueCheck::ZeroOrLess >
Non positive bounded value type.
template<typename T >
using Positive = BoundedValue< T, LoValueCheck::AboveZero, HiValueCheck::Any >
Positive bounded value type.
template<typename T >
using Negative = BoundedValue< T, LoValueCheck::Any, HiValueCheck::BelowZero >
Negative bounded value type.
template<typename T >
using Finite = BoundedValue< T, LoValueCheck::AboveNegInf, HiValueCheck::BelowPosInf >
Finite bounded value type.
template<typename T >
using NonZero = typename std::enable_if<!std::is_pointer< T >::value, BoundedValue< T, LoValueCheck::NonZero, HiValueCheck::Any > >::type
Non zero bounded value type.
template<typename T >
using NonNull = typename std::enable_if< std::is_pointer< T >::value, BoundedValue< T, LoValueCheck::NonZero, HiValueCheck::Any > >::type
Non-null pointer type.
template<typename T >
using UnitInterval = BoundedValue< T, LoValueCheck::ZeroOrMore, HiValueCheck::OneOrLess >
Unit interval bounded value type.
using Fixed32 = Fixed< std::int32_t, 9 >
32-bit fixed precision type.
using Fixed64 = Fixed< std::int64_t, 24 >
64-bit fixed precision type.
template<typename T , std::size_t N, std::size_t M>
using Matrix = Vector< Vector< T, M >, N >
Generic N by M matrix.
template<typename T >
using Matrix22 = Matrix< T, 2, 2 >
2 by 2 matrix.
template<typename T >
using Matrix33 = Matrix< T, 3, 3 >
3 by 3 matrix.
using Mat22 = Matrix22< Real >
2 by 2 matrix of Real elements.
using Mass22 = Matrix22< Mass >
2 by 2 matrix of Mass elements.
using InvMass22 = Matrix22< InvMass >
2 by 2 matrix of InvMass elements.
using Mat33 = Matrix33< Real >
3 by 3 matrix of Real elements.
template<typename T >
using Optional = OptionalValue< T >
Optional type alias.
using Real = float
Real-number type.
using ChildCounter = std::remove_const< decltype(MaxChildCount)>::type
Child counter type.
using TimestepIters = std::uint8_t
Time step iterations type.
using VertexCounter = std::remove_const< decltype(MaxShapeVertices)>::type
Vertex count type.
using BodyCounter = std::remove_const< decltype(MaxBodies)>::type
Body count type.
using ContactCounter = Wider< BodyCounter >::type
Contact count type.
using JointCounter = std::remove_const< decltype(MaxJoints)>::type
Joint count type.
template<class... Ts>
using VoidT = typename Voidify< Ts... >::type
Void type templated alias.
template<typename T , typename Tuple >
using TupleContainsType = typename HasType< T, Tuple >::type
Tuple contains type alias.
using Time = PLAYRHO_QUANTITY(boost::units::si::time)
Time quantity.
using Frequency = PLAYRHO_QUANTITY(boost::units::si::frequency)
Frequency quantity.
using Length = PLAYRHO_QUANTITY(boost::units::si::length)
Length quantity.
using LinearVelocity = PLAYRHO_QUANTITY(boost::units::si::velocity)
Linear velocity quantity.
using LinearAcceleration = PLAYRHO_QUANTITY(boost::units::si::acceleration)
Linear acceleration quantity.
using Mass = PLAYRHO_QUANTITY(boost::units::si::mass)
Mass quantity.
using InvMass = PLAYRHO_QUANTITY(boost::units::si::inverse_mass)
Inverse mass quantity.
using Area = PLAYRHO_QUANTITY(boost::units::si::area)
Area quantity.
using AreaDensity = PLAYRHO_QUANTITY(boost::units::si::surface_density)
Aereal/surface density quantity.
using Angle = PLAYRHO_QUANTITY(boost::units::si::plane_angle)
Angle quantity.
using AngularVelocity = PLAYRHO_QUANTITY(boost::units::si::angular_velocity)
Angular velocity quantity.
using AngularAcceleration = PLAYRHO_QUANTITY(boost::units::si::angular_acceleration)
Angular acceleration quantity.
using Force = PLAYRHO_QUANTITY(boost::units::si::force)
Force quantity.
using Torque = PLAYRHO_QUANTITY(boost::units::si::torque)
Torque quantity.
using SecondMomentOfArea = PLAYRHO_QUANTITY(boost::units::si::second_moment_of_area)
Second moment of area quantity.
using RotInertia = PLAYRHO_QUANTITY(boost::units::si::moment_of_inertia)
Rotational inertia quantity.
using InvRotInertia = PLAYRHO_QUANTITY(boost::units::si::inverse_moment_of_inertia)
Inverse rotational inertia quantity.
using Momentum = PLAYRHO_QUANTITY(boost::units::si::momentum)
Momentum quantity.
using AngularMomentum = PLAYRHO_QUANTITY(boost::units::si::angular_momentum)
Angular momentum quantity.
template<typename T >
using Vector2 = Vector< T, 2 >
Vector with 2-elements.
using Vec2 = Vector2< Real >
Vector with 2 Real elements.
using Length2 = Vector2< Length >
2-element vector of Length quanties.
using LinearVelocity2 = Vector2< LinearVelocity >
2-element vector of LinearVelocity quantities.
using LinearAcceleration2 = Vector2< LinearAcceleration >
2-element vector of LinearAcceleration quantities.
using Force2 = Vector2< Force >
2-element vector of Force quantities.
using Mass2 = Vector2< Mass >
2-element vector of Mass quantities.
using InvMass2 = Vector2< InvMass >
2-element vector of InvMass quantities.
using Momentum2 = Vector2< Momentum >
2-element vector of Momentum quantities.
template<typename T >
using Vector3 = Vector< T, 3 >
Vector with 3-elements.
using Vec3 = Vector3< Real >
A 3D column vector with 3 elements.
using Mass3 = Vector3< Mass >
3-element vector of Mass quantities.
using InvMass3 = Vector3< InvMass >
3-element vector of InvMass quantities.
using VelocityPair = std::pair< Velocity, Velocity >
Velocity pair.
using ContactPtr = Contact *
Contact pointer type.
using KeyedContactPtr = std::pair< ContactKey, Contact * >
Keyed contact pointer.
using BodyConstraintPtr = BodyConstraint *
A body constraint pointer alias.
using BodyConstraintPair = std::pair< const Body *, BodyConstraintPtr >
A body pointer and body constraint pointer pair alias.
using BodyConstraintsMap = std::unordered_map< const Body *, BodyConstraint * >
A body constraints map alias.
using BodyPtr = Body *
Body pointer alias.
using BodyConstraintsPair = std::pair< const Body *const, BodyConstraint * >
A body pointer and body constraint pointer pair.
using BodyConstraints = std::vector< BodyConstraint >
Collection of body constraints.
using PositionConstraints = std::vector< PositionConstraint >
Collection of position constraints.
using VelocityConstraints = std::vector< VelocityConstraint >
Collection of velocity constraints.
Enumerations
enum PointState { PointState::NullState, PointState::AddState, PointState::PersistState, PointState::RemoveState }
Point state enumeration.
enum DynamicTreeOpcode { End, Continue }
Opcodes for DynamicTree callbacks.
enum LoValueCheck {
Any, AboveZero, ZeroOrMore, AboveNegInf,
NonZero
}
Lo value check.
enum HiValueCheck {
Any, BelowZero, ZeroOrLess, OneOrLess,
BelowPosInf
}
Hi value check.
enum BodyType { BodyType::Static = 0, BodyType::Kinematic, BodyType::Dynamic }
Body Type.
enum JointType : std::uint8_t {
Unknown, Revolute, Prismatic, Distance,
Pulley, Mouse, Gear, Wheel,
Weld, Friction, Rope, Motor
}
Enumeration of joint types.
Functions
AABB2D ComputeAABB (const DistanceProxy &proxy, const Transformation &xf) noexcept
Computes the AABB.
AABB2D ComputeAABB (const DistanceProxy &proxy, const Transformation &xfm0, const Transformation &xfm1) noexcept
Computes the AABB.
AABB2D ComputeAABB (const Shape &shape, const Transformation &xf) noexcept
Computes the AABB for the given shape with the given transformation.
AABB2D ComputeAABB (const Fixture &fixture) noexcept
Computes the AABB for the given fixture.
AABB2D ComputeAABB (const Body &body)
Computes the AABB for the given body.
AABB2D ComputeIntersectingAABB (const Fixture &fA, ChildCounter iA, const Fixture &fB, ChildCounter iB) noexcept
Computes the intersecting AABB for the given pair of fixtures and indexes.
AABB2D ComputeIntersectingAABB (const Contact &contact)
Computes the intersecting AABB for the given contact.
template<std::size_t N>
PLAYRHO_CONSTEXPR bool operator== (const AABB< N > &lhs, const AABB< N > &rhs) noexcept
Gets whether the two AABB objects are equal.
template<std::size_t N>
PLAYRHO_CONSTEXPR bool operator!= (const AABB< N > &lhs, const AABB< N > &rhs) noexcept
Gets whether the two AABB objects are not equal.
template<std::size_t N>
bool operator< (const AABB< N > &lhs, const AABB< N > &rhs) noexcept
Less-than operator.
template<std::size_t N>
bool operator<= (const AABB< N > &lhs, const AABB< N > &rhs) noexcept
Less-than or equal-to operator.
template<std::size_t N>
bool operator> (const AABB< N > &lhs, const AABB< N > &rhs) noexcept
Greater-than operator.
template<std::size_t N>
bool operator>= (const AABB< N > &lhs, const AABB< N > &rhs) noexcept
Greater-than or equal-to operator.
template<std::size_t N>
PLAYRHO_CONSTEXPR bool TestOverlap (const AABB< N > &a, const AABB< N > &b) noexcept
Tests for overlap between two axis aligned bounding boxes.
template<std::size_t N>
PLAYRHO_CONSTEXPR AABB< N > GetIntersectingAABB (const AABB< N > &a, const AABB< N > &b) noexcept
Gets the intersecting AABB of the two given AABBs'.
template<std::size_t N>
PLAYRHO_CONSTEXPR Vector< Length, N > GetCenter (const AABB< N > &aabb) noexcept
Gets the center of the AABB.
template<std::size_t N>
PLAYRHO_CONSTEXPR Vector< Length, N > GetDimensions (const AABB< N > &aabb) noexcept
Gets dimensions of the given AABB.
template<std::size_t N>
PLAYRHO_CONSTEXPR Vector< Length, N > GetExtents (const AABB< N > &aabb) noexcept
Gets the extents of the AABB (half-widths).
template<std::size_t N>
PLAYRHO_CONSTEXPR bool Contains (const AABB< N > &a, const AABB< N > &b) noexcept
Checks whether the first AABB fully contains the second AABB.
template<std::size_t N>
PLAYRHO_CONSTEXPR AABB< N > & Include (AABB< N > &var, const Vector< Length, N > &value) noexcept
Includes the given location into the given AABB.
template<std::size_t N>
PLAYRHO_CONSTEXPR AABB< N > & Include (AABB< N > &var, const AABB< N > &val) noexcept
Includes the second AABB into the first one.
template<std::size_t N>
PLAYRHO_CONSTEXPR AABB< N > & Move (AABB< N > &var, const Vector< Length, N > value) noexcept
Moves the given AABB by the given value.
template<std::size_t N>
PLAYRHO_CONSTEXPR AABB< N > & Fatten (AABB< N > &var, const NonNegative< Length > amount) noexcept
Fattens an AABB by the given amount.
template<std::size_t N>
PLAYRHO_CONSTEXPR AABB< N > GetDisplacedAABB (AABB< N > aabb, const Vector< Length, N > displacement)
Gets the AABB that the result of displacing the given AABB by the given displacement amount.
template<std::size_t N>
PLAYRHO_CONSTEXPR AABB< N > GetFattenedAABB (AABB< N > aabb, const Length amount)
Gets the fattened AABB result.
template<std::size_t N>
PLAYRHO_CONSTEXPR AABB< N > GetMovedAABB (AABB< N > aabb, const Vector< Length, N > value) noexcept
Gets the result of moving the given AABB by the given value.
template<std::size_t N>
PLAYRHO_CONSTEXPR AABB< N > GetEnclosingAABB (AABB< N > a, const AABB< N > &b)
Gets the AABB that minimally encloses the given AABBs.
template<std::size_t N>
PLAYRHO_CONSTEXPR Vector< Length, N > GetLowerBound (const AABB< N > &aabb) noexcept
Gets the lower bound.
template<std::size_t N>
PLAYRHO_CONSTEXPR Vector< Length, N > GetUpperBound (const AABB< N > &aabb) noexcept
Gets the upper bound.
template<std::size_t N>
inline ::std::ostream & operator<< (::std::ostream &os, const AABB< N > &value)
Output stream operator.
template<>
PLAYRHO_CONSTEXPR AABB2D GetInvalid () noexcept
Gets an invalid AABB value.
PLAYRHO_CONSTEXPR Length GetPerimeter (const AABB2D &aabb) noexcept
Gets the perimeter length of the 2-dimensional AABB.
PointStates GetPointStates (const Manifold &manifold1, const Manifold &manifold2) noexcept
Computes the point states given two manifolds.
ClipList ClipSegmentToLine (const ClipList &vIn, const UnitVec2 &normal, Length offset, ContactFeature::Index indexA)
Clipping for contact manifolds.
PLAYRHO_CONSTEXPR ContactFeature GetVertexVertexContactFeature (ContactFeature::Index a, ContactFeature::Index b) noexcept
Gets the vertex vertex contact feature for the given indices.
PLAYRHO_CONSTEXPR ContactFeature GetVertexFaceContactFeature (ContactFeature::Index a, ContactFeature::Index b) noexcept
Gets the vertex face contact feature for the given indices.
PLAYRHO_CONSTEXPR ContactFeature GetFaceVertexContactFeature (ContactFeature::Index a, ContactFeature::Index b) noexcept
Gets the face vertex contact feature for the given indices.
PLAYRHO_CONSTEXPR ContactFeature GetFaceFaceContactFeature (ContactFeature::Index a, ContactFeature::Index b) noexcept
Gets the face face contact feature for the given indices.
PLAYRHO_CONSTEXPR ContactFeature Flip (ContactFeature val) noexcept
Flips contact features information.
PLAYRHO_CONSTEXPR bool operator== (ContactFeature lhs, ContactFeature rhs) noexcept
Determines if the given two contact features are equal.
PLAYRHO_CONSTEXPR bool operator!= (ContactFeature lhs, ContactFeature rhs) noexcept
Determines if the given two contact features are not equal.
PairLength2 GetWitnessPoints (const Simplex &simplex) noexcept
Gets the witness points of the given simplex.
DistanceOutput Distance (const DistanceProxy &proxyA, const Transformation &transformA, const DistanceProxy &proxyB, const Transformation &transformB, DistanceConf conf=DistanceConf{})
Determines the closest points between two shapes.
Area TestOverlap (const DistanceProxy &proxyA, const Transformation &xfA, const DistanceProxy &proxyB, const Transformation &xfB, DistanceConf conf=DistanceConf{})
Determine if two generic shapes overlap.
PLAYRHO_CONSTEXPR Length2 GetDelta (PairLength2 arg) noexcept
Gets the delta of the two points of the given witness points.
bool operator== (const DistanceProxy &lhs, const DistanceProxy &rhs) noexcept
Determines with the two given distance proxies are equal.
std::size_t FindLowestRightMostVertex (Span< const Length2 > vertices)
Finds the lowest right most vertex in the given collection.
std::vector< Length2 > GetConvexHullAsVector (Span< const Length2 > vertices)
Gets the convex hull for the given collection of vertices as a vector.
bool TestPoint (const DistanceProxy &proxy, Length2 point) noexcept
Tests a point for containment in the given distance proxy.
bool operator!= (const DistanceProxy &lhs, const DistanceProxy &rhs) noexcept
Determines with the two given distance proxies are not equal.
NonNegative< Length > GetVertexRadius (const DistanceProxy &arg) noexcept
Gets the vertex radius property of a given distance proxy.
template<class T >
VertexCounter GetSupportIndex (const DistanceProxy &proxy, T d) noexcept
Gets the supporting vertex index in the given direction for the given distance proxy.
void Query (const DynamicTree &tree, const AABB2D &aabb, const DynamicTreeSizeCB &callback)
Query the given dynamic tree and find nodes overlapping the given AABB.
void RayCast (const DynamicTree &tree, const RayCastInput &input, const DynamicTree::RayCastCallback &callback)
Ray-cast against the leafs in the given tree.
PLAYRHO_CONSTEXPR bool operator== (const DynamicTree::LeafData &lhs, const DynamicTree::LeafData &rhs) noexcept
Equality operator.
PLAYRHO_CONSTEXPR bool operator!= (const DynamicTree::LeafData &lhs, const DynamicTree::LeafData &rhs) noexcept
Inequality operator.
PLAYRHO_CONSTEXPR bool IsUnused (const DynamicTree::TreeNode &node) noexcept
Is unused.
PLAYRHO_CONSTEXPR bool IsLeaf (const DynamicTree::TreeNode &node) noexcept
Is leaf.
PLAYRHO_CONSTEXPR bool IsBranch (const DynamicTree::TreeNode &node) noexcept
Is branch.
PLAYRHO_CONSTEXPR AABB2D GetAABB (const DynamicTree::TreeNode &node) noexcept
Gets the AABB of the given DynamicTree node.
PLAYRHO_CONSTEXPR DynamicTree::Size GetNext (const DynamicTree::TreeNode &node) noexcept
Gets the next index of the given node.
DynamicTree::TreeNode & SetParent (DynamicTree::TreeNode &node, DynamicTree::Size other) noexcept
Sets the parent index of the given node.
DynamicTree::Height ComputeHeight (const DynamicTree &tree) noexcept
Computes the height of the given dynamic tree.
DynamicTree::Height GetHeight (const DynamicTree &tree) noexcept
Gets the height of the binary tree.
AABB2D GetAABB (const DynamicTree &tree) noexcept
Gets the AABB for the given DynamicTree.
bool TestOverlap (const DynamicTree &tree, DynamicTree::Size leafIdA, DynamicTree::Size leafIdB) noexcept
Tests for overlap of the elements identified in the given dynamic tree.
Real ComputePerimeterRatio (const DynamicTree &tree) noexcept
Gets the ratio of the sum of the perimeters of nodes to the root perimeter.
PLAYRHO_CONSTEXPR std::size_t GetNumIndices (IndexPair3 pairs) noexcept
Gets the number of valid indices in the given collection of index pairs.
Manifold CollideShapes (const DistanceProxy &shapeA, const Transformation &xfA, const DistanceProxy &shapeB, const Transformation &xfB, Manifold::Conf conf=GetDefaultManifoldConf())
Calculates the relevant collision manifold.
const char * GetName (Manifold::Type type) noexcept
Gets a unique name for the given manifold type.
bool operator== (const Manifold::Point &lhs, const Manifold::Point &rhs) noexcept
Determines whether the two given manifold points are equal.
bool operator!= (const Manifold::Point &lhs, const Manifold::Point &rhs) noexcept
Determines whether the two given manifold points are not equal.
bool operator== (const Manifold &lhs, const Manifold &rhs) noexcept
Manifold equality operator.
bool operator!= (const Manifold &lhs, const Manifold &rhs) noexcept
Manifold inequality operator.
PLAYRHO_CONSTEXPR Manifold::Conf GetDefaultManifoldConf () noexcept
Gets the default manifold configuration.
template<>
PLAYRHO_CONSTEXPR bool IsValid (const Manifold &value) noexcept
Gets whether the given manifold is valid.
MassData GetMassData (Length r, NonNegative< AreaDensity > density, Length2 location)
Computes the mass data for a circular shape.
MassData GetMassData (Length r, NonNegative< AreaDensity > density, Length2 v0, Length2 v1)
Computes the mass data for a linear shape.
MassData GetMassData (Length vertexRadius, NonNegative< AreaDensity > density, Span< const Length2 > vertices)
Gets the mass data for the given collection of vertices with the given properties.
MassData GetMassData (const Fixture &f)
Computes the mass data for the given fixture.
MassData ComputeMassData (const Body &body) noexcept
Computes the body's mass data.
MassData GetMassData (const Body &body) noexcept
Gets the mass data of the body.
PLAYRHO_CONSTEXPR bool operator== (MassData lhs, MassData rhs)
MassData equality operator.
PLAYRHO_CONSTEXPR bool operator!= (MassData lhs, MassData rhs)
MassData inequality operator.
RayCastOutput RayCast (Length radius, Length2 location, const RayCastInput &input) noexcept
Cast a ray against a circle of a given radius at the given location.
RayCastOutput RayCast (const AABB2D &aabb, const RayCastInput &input) noexcept
Cast a ray against the given AABB.
RayCastOutput RayCast (const DistanceProxy &proxy, const RayCastInput &input, const Transformation &transform) noexcept
Cast a ray against the distance proxy.
RayCastOutput RayCast (const Shape &shape, ChildCounter childIndex, const RayCastInput &input, const Transformation &transform) noexcept
Cast a ray against the child of the given shape.
ChildCounter GetChildCount (const ChainShapeConf &arg) noexcept
Gets the child count for a given chain shape configuration.
DistanceProxy GetChild (const ChainShapeConf &arg, ChildCounter index)
Gets the "child" shape for a given chain shape configuration.
MassData GetMassData (const ChainShapeConf &arg) noexcept
Gets the mass data for a given chain shape configuration.
bool IsLooped (const ChainShapeConf &shape) noexcept
Determines whether the given shape is looped.
ChildCounter GetNextIndex (const ChainShapeConf &shape, ChildCounter index) noexcept
Gets the next index after the given index for the given shape.
bool operator== (const DiskShapeConf &lhs, const DiskShapeConf &rhs) noexcept
Equality operator.
bool operator!= (const DiskShapeConf &lhs, const DiskShapeConf &rhs) noexcept
Inequality operator.
PLAYRHO_CONSTEXPR ChildCounter GetChildCount (const DiskShapeConf &) noexcept
Gets the "child" count of the given disk shape configuration.
DistanceProxy GetChild (const DiskShapeConf &arg, ChildCounter index)
Gets the "child" of the given disk shape configuration.
MassData GetMassData (const DiskShapeConf &arg) noexcept
Gets the mass data of the given disk shape configuration.
bool operator== (const EdgeShapeConf &lhs, const EdgeShapeConf &rhs) noexcept
Equality operator.
bool operator!= (const EdgeShapeConf &lhs, const EdgeShapeConf &rhs) noexcept
Inequality operator.
PLAYRHO_CONSTEXPR ChildCounter GetChildCount (const EdgeShapeConf &) noexcept
Gets the "child" count for the given shape configuration.
DistanceProxy GetChild (const EdgeShapeConf &arg, ChildCounter index)
Gets the "child" shape for the given shape configuration.
MassData GetMassData (const EdgeShapeConf &arg) noexcept
Gets the mass data for the given shape configuration.
MassData GetMassData (const MultiShapeConf &arg) noexcept
Computes the mass properties of this shape using its dimensions and density. The inertia tensor is computed about the local origin.
bool operator== (const MultiShapeConf &lhs, const MultiShapeConf &rhs) noexcept
Equality operator.
bool operator!= (const MultiShapeConf &lhs, const MultiShapeConf &rhs) noexcept
Inequality operator.
ChildCounter GetChildCount (const MultiShapeConf &arg) noexcept
Gets the "child" count for the given shape configuration.
DistanceProxy GetChild (const MultiShapeConf &arg, ChildCounter index)
Gets the "child" shape for the given shape configuration.
Length2 GetEdge (const PolygonShapeConf &shape, VertexCounter index)
Gets the identified edge of the given polygon shape.
bool Validate (const PolygonShapeConf &shape)
Validate convexity of the given shape.
PLAYRHO_CONSTEXPR ChildCounter GetChildCount (const PolygonShapeConf &) noexcept
Gets the "child" count for the given shape configuration.
DistanceProxy GetChild (const PolygonShapeConf &arg, ChildCounter index)
Gets the "child" shape for the given shape configuration.
MassData GetMassData (const PolygonShapeConf &arg) noexcept
Gets the mass data for the given shape configuration.
bool TestPoint (const Shape &shape, Length2 point) noexcept
Test a point for containment in the given shape.
Real GetFriction (const Shape &shape) noexcept
Gets the friction of the given shape.
Real GetRestitution (const Shape &shape) noexcept
Gets the restitution value of the given shape.
NonNegative< AreaDensity > GetDensity (const Shape &shape) noexcept
Gets the density of the given shape.
NonNegative< Length > GetVertexRadius (const Shape &shape) noexcept
Gets the vertex radius of the given shape.
PLAYRHO_CONSTEXPR NonNegative< Length > GetVertexRadius (const ShapeDef &arg) noexcept
Gets the vertex radius of the given shape configuration.
PLAYRHO_CONSTEXPR NonNegative< AreaDensity > GetDensity (const ShapeDef &arg) noexcept
Gets the density of the given shape configuration.
PLAYRHO_CONSTEXPR Finite< Real > GetRestitution (const ShapeDef &arg) noexcept
Gets the restitution of the given shape configuration.
PLAYRHO_CONSTEXPR NonNegative< Real > GetFriction (const ShapeDef &arg) noexcept
Gets the friction of the given shape configuration.
IndexPairDistance GetMaxSeparation4x4 (const DistanceProxy &proxy1, Transformation xf1, const DistanceProxy &proxy2, Transformation xf2)
Gets the max separation information for the first four vertices of the two given shapes.
IndexPairDistance GetMaxSeparation (const DistanceProxy &proxy1, Transformation xf1, const DistanceProxy &proxy2, Transformation xf2)
Gets the max separation information.
IndexPairDistance GetMaxSeparation (const DistanceProxy &proxy1, Transformation xf1, const DistanceProxy &proxy2, Transformation xf2, Length stop)
Gets the max separation information.
IndexPairDistance GetMaxSeparation (const DistanceProxy &proxy1, const DistanceProxy &proxy2, Length stop=MaxFloat *Meter)
Gets the max separation information.
Length2 GetScaledDelta (const Simplex &simplex, Simplex::size_type index)
Gets the scaled delta for the given indexed element of the given simplex.
PLAYRHO_CONSTEXPR Length2 GetClosestPoint (const Simplex &simplex)
Gets the "closest point".
PLAYRHO_CONSTEXPR Length2 GetPointDelta (const SimplexEdge &sv) noexcept
Gets "w".
PLAYRHO_CONSTEXPR bool operator== (const SimplexEdge &lhs, const SimplexEdge &rhs) noexcept
SimplexEdge equality operator.
PLAYRHO_CONSTEXPR bool operator!= (const SimplexEdge &lhs, const SimplexEdge &rhs) noexcept
SimplexEdge inequality operator.
TOIOutput GetToiViaSat (const DistanceProxy &proxyA, const Sweep &sweepA, const DistanceProxy &proxyB, const Sweep &sweepB, ToiConf conf=GetDefaultToiConf())
Gets the time of impact for two disjoint convex sets using the Separating Axis Theorem.
const char * GetName (TOIOutput::State state) noexcept
Gets a human readable name for the given output state.
PLAYRHO_CONSTEXPR auto GetDefaultToiConf ()
Gets the default time of impact configuration.
WorldManifold GetWorldManifold (const Manifold &manifold, Transformation xfA, Length radiusA, Transformation xfB, Length radiusB)
Gets the world manifold for the given data.
WorldManifold GetWorldManifold (const Contact &contact)
Gets the world manifold for the given data.
template<>
PLAYRHO_CONSTEXPR bool IsValid (const Acceleration &value) noexcept
Determines if the given value is valid.
PLAYRHO_CONSTEXPR bool operator== (const Acceleration &lhs, const Acceleration &rhs)
Equality operator.
PLAYRHO_CONSTEXPR bool operator!= (const Acceleration &lhs, const Acceleration &rhs)
Inequality operator.
PLAYRHO_CONSTEXPR Acceleration & operator*= (Acceleration &lhs, const Real rhs)
Multiplication assignment operator.
PLAYRHO_CONSTEXPR Acceleration & operator/= (Acceleration &lhs, const Real rhs)
Division assignment operator.
PLAYRHO_CONSTEXPR Acceleration & operator+= (Acceleration &lhs, const Acceleration &rhs)
Addition assignment operator.
PLAYRHO_CONSTEXPR Acceleration operator+ (const Acceleration &lhs, const Acceleration &rhs)
Addition operator.
PLAYRHO_CONSTEXPR Acceleration & operator-= (Acceleration &lhs, const Acceleration &rhs)
Subtraction assignment operator.
PLAYRHO_CONSTEXPR Acceleration operator- (const Acceleration &lhs, const Acceleration &rhs)
Subtraction operator.
PLAYRHO_CONSTEXPR Acceleration operator- (const Acceleration &value)
Negation operator.
PLAYRHO_CONSTEXPR Acceleration operator+ (const Acceleration &value)
Positive operator.
PLAYRHO_CONSTEXPR Acceleration operator* (const Acceleration &lhs, const Real rhs)
Multiplication operator.
PLAYRHO_CONSTEXPR Acceleration operator* (const Real lhs, const Acceleration &rhs)
Multiplication operator.
PLAYRHO_CONSTEXPR Acceleration operator/ (const Acceleration &lhs, const Real rhs)
Division operator.
template<typename T , std::size_t S>
ArrayList< T, S > & operator+= (ArrayList< T, S > &lhs, const typename ArrayList< T, S >::data_type &rhs)
ArrayList append operator.
template<typename T , std::size_t S>
ArrayList< T, S > operator+ (ArrayList< T, S > lhs, const typename ArrayList< T, S >::data_type &rhs)
ArrayList add operator.
template<typename T >
void Delete (const T *p, BlockAllocator &allocator)
Deletes the given pointer by calling the pointed-to object's destructor and returning it to the given allocator.
bool operator== (const BlockAllocator &a, const BlockAllocator &b)
BlockAllocator equality operator.
bool operator!= (const BlockAllocator &a, const BlockAllocator &b)
BlockAllocator inequality operator.
template<typename T >
PLAYRHO_CONSTEXPR void CheckIfAboveNegInf (typename std::enable_if<!std::is_pointer< T >::value, T >::type value)
Checks if the given value is above negative infinity.
template<typename T >
PLAYRHO_CONSTEXPR void CheckIfAboveNegInf (typename std::enable_if< std::is_pointer< T >::value, T >::type)
Checks if the given value is above negative infinity.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR bool operator== (const BoundedValue< T, lo, hi > lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue equality operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR bool operator!= (const BoundedValue< T, lo, hi > lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue inequality operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR bool operator<= (const BoundedValue< T, lo, hi > lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue less-than or equal-to operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR bool operator>= (const BoundedValue< T, lo, hi > lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue greater-than or equal-to operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR bool operator< (const BoundedValue< T, lo, hi > lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue less-than operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR bool operator> (const BoundedValue< T, lo, hi > lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue greater-than operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR auto operator* (const BoundedValue< T, lo, hi > lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue multiplication operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR auto operator/ (const BoundedValue< T, lo, hi > lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue division operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR auto operator+ (const BoundedValue< T, lo, hi > lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue addition operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR auto operator- (const BoundedValue< T, lo, hi > lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue subtraction operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR bool operator== (const BoundedValue< T, lo, hi > lhs, const T rhs)
BoundedValue equality operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR bool operator!= (const BoundedValue< T, lo, hi > lhs, const T rhs)
BoundedValue inequality operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR bool operator<= (const BoundedValue< T, lo, hi > lhs, const T rhs)
BoundedValue less-than or equal-to operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR bool operator>= (const BoundedValue< T, lo, hi > lhs, const T rhs)
BoundedValue greater-than or equal-to operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR bool operator< (const BoundedValue< T, lo, hi > lhs, const T rhs)
BoundedValue less-than operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR bool operator> (const BoundedValue< T, lo, hi > lhs, const T rhs)
BoundedValue greater-than operator.
template<typename T , typename U , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR auto operator* (const BoundedValue< T, lo, hi > lhs, const U rhs)
BoundedValue multiplication operator.
template<typename T , typename U , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR auto operator/ (const BoundedValue< T, lo, hi > lhs, const U rhs)
BoundedValue division operator.
template<typename T , typename U , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR auto operator+ (const BoundedValue< T, lo, hi > lhs, const U rhs)
BoundedValue addition operator.
template<typename T , typename U , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR auto operator- (const BoundedValue< T, lo, hi > lhs, const U rhs)
BoundedValue subtraction operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR bool operator== (const T lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue equality operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR bool operator!= (const T lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue inequality operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR bool operator<= (const T lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue less-than or equal-to operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR bool operator>= (const T lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue greater-than or equal-to operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR bool operator< (const T lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue less-than operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR bool operator> (const T lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue greater-than operator.
template<typename T , typename U , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR auto operator* (const U lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue multiplication operator.
template<typename T , typename U , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR auto operator/ (const U lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue division operator.
template<typename T , typename U , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR auto operator+ (const U lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue addition operator.
template<typename T , typename U , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR auto operator- (const U lhs, const BoundedValue< T, lo, hi > rhs)
BoundedValue subtraction operator.
template<typename T , LoValueCheck lo, HiValueCheck hi>
::std::ostream & operator<< (::std::ostream &os, const BoundedValue< T, lo, hi > &value)
BoundedValue stream output operator.
void Dump (const World &world)
Dump the world into the log file.
void Dump (const Body &body, std::size_t bodyIndex)
Dump body to a log file.
void Dump (const Joint &joint, std::size_t index)
Dump joint to the log file.
void Dump (const Fixture &fixture, std::size_t bodyIndex)
Dump fixture to log file.
void Dump (const DistanceJoint &joint, std::size_t index)
Dump joint to dmLog.
void Dump (const FrictionJoint &joint, std::size_t index)
Dump joint to the log file.
void Dump (const GearJoint &joint, std::size_t index)
Dumps the joint to the log file.
void Dump (const MotorJoint &joint, std::size_t index)
Dumps the joint to the log file.
void Dump (const MouseJoint &joint, std::size_t index)
Dumps the joint to the log file.
void Dump (const PrismaticJoint &joint, std::size_t index)
Dumps the joint to the log file.
void Dump (const PulleyJoint &joint, std::size_t index)
Dump joint to dmLog.
void Dump (const RevoluteJoint &joint, std::size_t index)
Dumps the joint to the log file.
void Dump (const RopeJoint &joint, std::size_t index)
Dumps the joint to the log file.
void Dump (const WeldJoint &joint, std::size_t index)
Dumps the joint to the log file.
void Dump (const WheelJoint &joint, std::size_t index)
Dumps the joint to the log file.
void * Alloc (std::size_t size)
Allocates memory.
void * Realloc (void *ptr, std::size_t new_size)
Reallocates memory.
void Free (void *mem)
Frees memory.
template<typename T >
T * Realloc (T *ptr, std::size_t size)
Reallocates memory.
template<typename BT , unsigned int FB>
PLAYRHO_CONSTEXPR bool operator== (Fixed< BT, FB > lhs, Fixed< BT, FB > rhs) noexcept
Equality operator.
template<typename BT , unsigned int FB>
PLAYRHO_CONSTEXPR bool operator!= (Fixed< BT, FB > lhs, Fixed< BT, FB > rhs) noexcept
Inequality operator.
template<typename BT , unsigned int FB>
PLAYRHO_CONSTEXPR bool operator< (Fixed< BT, FB > lhs, Fixed< BT, FB > rhs) noexcept
Less-than operator.
template<typename BT , unsigned int FB>
PLAYRHO_CONSTEXPR bool operator> (Fixed< BT, FB > lhs, Fixed< BT, FB > rhs) noexcept
Greater-than operator.
template<typename BT , unsigned int FB>
PLAYRHO_CONSTEXPR bool operator<= (Fixed< BT, FB > lhs, Fixed< BT, FB > rhs) noexcept
Less-than or equal-to operator.
template<typename BT , unsigned int FB>
PLAYRHO_CONSTEXPR bool operator>= (Fixed< BT, FB > lhs, Fixed< BT, FB > rhs) noexcept
Greater-than or equal-to operator.
template<typename BT , unsigned int FB>
PLAYRHO_CONSTEXPR Fixed< BT, FB > operator+ (Fixed< BT, FB > lhs, Fixed< BT, FB > rhs) noexcept
Addition operator.
template<typename BT , unsigned int FB>
PLAYRHO_CONSTEXPR Fixed< BT, FB > operator- (Fixed< BT, FB > lhs, Fixed< BT, FB > rhs) noexcept
Subtraction operator.
template<typename BT , unsigned int FB>
PLAYRHO_CONSTEXPR Fixed< BT, FB > operator* (Fixed< BT, FB > lhs, Fixed< BT, FB > rhs) noexcept
Multiplication operator.
template<typename BT , unsigned int FB>
PLAYRHO_CONSTEXPR Fixed< BT, FB > operator/ (Fixed< BT, FB > lhs, Fixed< BT, FB > rhs) noexcept
Division operator.
template<typename BT , unsigned int FB>
PLAYRHO_CONSTEXPR Fixed< BT, FB > operator% (Fixed< BT, FB > lhs, Fixed< BT, FB > rhs) noexcept
Modulo operator.
template<typename BT , unsigned int FB>
auto sqrt (Fixed< BT, FB > arg)
Square root's the given value.
template<typename BT , unsigned int FB>
bool isnormal (Fixed< BT, FB > arg)
Gets whether the given value is normal - i.e. not 0 nor infinite.
template<typename BT , unsigned int FB>
Fixed< BT, FB > sin (Fixed< BT, FB > arg)
Computes the sine of the argument for Fixed types.
template<typename BT , unsigned int FB>
Fixed< BT, FB > cos (Fixed< BT, FB > arg)
Computes the cosine of the argument for Fixed types.
template<typename BT , unsigned int FB>
Fixed< BT, FB > atan2 (Fixed< BT, FB > y, Fixed< BT, FB > x)
Computes the arc tangent.
template<typename BT , unsigned int FB>
Fixed< BT, FB > pow (Fixed< BT, FB > base, Fixed< BT, FB > exp)
Computes the value of the base number raised to the power of the exponent.
template<typename BT , unsigned int FB>
Fixed< BT, FB > pow (Fixed< BT, FB > base, double exp)
Computes the value of the base number raised to the power of the exponent.
template<typename BT , unsigned int FB>
Fixed< BT, FB > hypot (Fixed< BT, FB > x, Fixed< BT, FB > y)
Computes the square root of the sum of the squares.
template<typename BT , unsigned int FB>
Fixed< BT, FB > round (Fixed< BT, FB > value) noexcept
Rounds the given value.
template<typename BT , unsigned int FB>
Fixed< BT, FB > trunc (Fixed< BT, FB > arg)
Truncates the given value.
template<typename BT , unsigned int FB>
bool signbit (Fixed< BT, FB > value) noexcept
Determines whether the given value is negative.
template<typename BT , unsigned int FB>
PLAYRHO_CONSTEXPR bool isnan (Fixed< BT, FB > value) noexcept
Gets whether the given value is not-a-number.
template<typename BT , unsigned int FB>
bool isfinite (Fixed< BT, FB > value) noexcept
Gets whether the given value is finite.
template<typename BT , unsigned int FB>
Fixed< BT, FB > nextafter (Fixed< BT, FB > from, Fixed< BT, FB > to) noexcept
Next after function for Fixed types.
template<typename BT , unsigned int FB>
Fixed< BT, FB > RoundOff (Fixed< BT, FB > value, std::uint32_t precision=100000)
Computes the rounded value of the given value.
template<typename BT , unsigned int FB>
PLAYRHO_CONSTEXPR bool AlmostZero (Fixed< BT, FB > value)
Gets whether a given value is almost zero.
template<typename BT , unsigned int FB>
PLAYRHO_CONSTEXPR bool AlmostEqual (Fixed< BT, FB > x, Fixed< BT, FB > y, int ulp=2)
Determines whether the given two values are "almost equal".
template<typename BT , unsigned int FB>
inline ::std::ostream & operator<< (::std::ostream &os, const Fixed< BT, FB > &value)
Output stream operator.
template<>
PLAYRHO_CONSTEXPR Fixed32 GetInvalid () noexcept
Gets an invalid value.
PLAYRHO_CONSTEXPR Fixed32 operator+ (Fixed32 lhs, Fixed32 rhs) noexcept
Addition operator.
PLAYRHO_CONSTEXPR Fixed32 operator- (Fixed32 lhs, Fixed32 rhs) noexcept
Subtraction operator.
PLAYRHO_CONSTEXPR Fixed32 operator* (Fixed32 lhs, Fixed32 rhs) noexcept
Multiplication operator.
PLAYRHO_CONSTEXPR Fixed32 operator/ (Fixed32 lhs, Fixed32 rhs) noexcept
Division operator.
PLAYRHO_CONSTEXPR Fixed32 operator% (Fixed32 lhs, Fixed32 rhs) noexcept
Modulo operator.
PLAYRHO_CONSTEXPR bool operator== (Fixed32 lhs, Fixed32 rhs) noexcept
Equality operator.
PLAYRHO_CONSTEXPR bool operator!= (Fixed32 lhs, Fixed32 rhs) noexcept
Inequality operator.
PLAYRHO_CONSTEXPR bool operator<= (Fixed32 lhs, Fixed32 rhs) noexcept
Less-than or equal-to operator.
PLAYRHO_CONSTEXPR bool operator>= (Fixed32 lhs, Fixed32 rhs) noexcept
Greater-than or equal-to operator.
PLAYRHO_CONSTEXPR bool operator< (Fixed32 lhs, Fixed32 rhs) noexcept
Less-than operator.
PLAYRHO_CONSTEXPR bool operator> (Fixed32 lhs, Fixed32 rhs) noexcept
Greater-than operator.
template<>
const char * GetTypeName< Fixed32 > () noexcept
Gets the specialized name for the Fixed32 type.
template<>
PLAYRHO_CONSTEXPR Fixed64 GetInvalid () noexcept
Gets an invalid value.
template<>
const char * GetTypeName< Fixed64 > () noexcept
Gets the specialized name for the Fixed64 type.
template<typename T >
PLAYRHO_CONSTEXPR T GetSize (const Interval< T > &v) noexcept
Gets the size of the given interval.
template<typename T >
PLAYRHO_CONSTEXPR T GetCenter (const Interval< T > &v) noexcept
Gets the center of the given interval.
template<typename T >
PLAYRHO_CONSTEXPR bool IsIntersecting (const Interval< T > &a, const Interval< T > &b) noexcept
Checks whether two value ranges have any intersection/overlap at all.
template<typename T >
PLAYRHO_CONSTEXPR Interval< T > GetIntersection (Interval< T > a, const Interval< T > &b) noexcept
Gets the intersecting interval of two given ranges.
template<typename T >
PLAYRHO_CONSTEXPR bool IsEntirelyBefore (const Interval< T > &a, const Interval< T > &b)
Determines whether the first range is entirely before the second range.
template<typename T >
PLAYRHO_CONSTEXPR bool IsEntirelyAfter (const Interval< T > &a, const Interval< T > &b)
Determines whether the first range is entirely after the second range.
template<typename T >
PLAYRHO_CONSTEXPR bool IsEntirelyEnclosing (const Interval< T > &a, const Interval< T > &b)
Determines whether the first range entirely encloses the second.
template<typename T >
PLAYRHO_CONSTEXPR bool operator== (const Interval< T > &a, const Interval< T > &b) noexcept
Equality operator.
template<typename T >
PLAYRHO_CONSTEXPR bool operator!= (const Interval< T > &a, const Interval< T > &b) noexcept
Inequality operator.
template<typename T >
PLAYRHO_CONSTEXPR bool operator< (const Interval< T > &lhs, const Interval< T > &rhs) noexcept
Less-than operator.
template<typename T >
PLAYRHO_CONSTEXPR bool operator<= (const Interval< T > &lhs, const Interval< T > &rhs) noexcept
Less-than or equal-to operator.
template<typename T >
PLAYRHO_CONSTEXPR bool operator> (const Interval< T > &lhs, const Interval< T > &rhs) noexcept
Greater-than operator.
template<typename T >
PLAYRHO_CONSTEXPR bool operator>= (const Interval< T > &lhs, const Interval< T > &rhs) noexcept
Greater-than or equal-to operator.
template<typename T >
::std::ostream & operator<< (::std::ostream &os, const Interval< T > &value)
Output stream operator.
Angle GetDelta (Angle a1, Angle a2) noexcept
Gets the shortest angular distance to go from angle 1 to angle 2.
Length2 ComputeCentroid (const Span< const Length2 > &vertices)
Computes the centroid of a counter-clockwise array of 3 or more vertices.
std::vector< Length2 > GetCircleVertices (Length radius, unsigned slices, Angle start=0_deg, Real turns=Real{1})
Gets the vertices for a circle described by the given parameters.
NonNegative< Area > GetAreaOfCircle (Length radius)
Gets the area of a cirlce.
NonNegative< Area > GetAreaOfPolygon (Span< const Length2 > vertices)
Gets the area of a polygon.
SecondMomentOfArea GetPolarMoment (Span< const Length2 > vertices)
Gets the polar moment of the area enclosed by the given vertices.
template<typename T >
PLAYRHO_CONSTEXPR auto & GetX (T &value)
Gets the "X" element of the given value - i.e. the first element.
template<typename T >
PLAYRHO_CONSTEXPR auto & GetY (T &value)
Gets the "Y" element of the given value - i.e. the second element.
template<typename T >
PLAYRHO_CONSTEXPR auto & GetZ (T &value)
Gets the "Z" element of the given value - i.e. the third element.
template<typename T >
PLAYRHO_CONSTEXPR auto GetX (const T &value)
Gets the "X" element of the given value - i.e. the first element.
template<typename T >
PLAYRHO_CONSTEXPR auto GetY (const T &value)
Gets the "Y" element of the given value - i.e. the second element.
template<typename T >
PLAYRHO_CONSTEXPR auto GetZ (const T &value)
Gets the "Z" element of the given value - i.e. the third element.
template<typename T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR auto StripUnit (const BoundedValue< T, lo, hi > &v)
Strips the unit from the given value.
template<typename T , typename U >
PLAYRHO_CONSTEXPR U Secant (T target, U a1, T s1, U a2, T s2) noexcept
Secant method.
template<typename T >
PLAYRHO_CONSTEXPR T Bisect (T a1, T a2) noexcept
Bisection method.
template<typename T >
PLAYRHO_CONSTEXPR bool IsOdd (T val) noexcept
Is-odd.
template<class TYPE >
PLAYRHO_CONSTEXPR auto Square (TYPE t) noexcept
Squares the given value.
template<typename T >
auto Atan2 (T y, T x)
Computes the arc-tangent of the given y and x values.
template<typename T >
auto Average (Span< const T > span)
Computes the average of the given values.
template<typename T >
std::enable_if< std::is_arithmetic< T >::value, T >::type RoundOff (T value, unsigned precision=100000)
Computes the rounded value of the given value.
Vec2 RoundOff (Vec2 value, std::uint32_t precision=100000)
Computes the rounded value of the given value.
PLAYRHO_CONSTEXPR Vec2 GetVec2 (const UnitVec2 value)
Gets a Vec2 representation of the given value.
template<typename T >
PLAYRHO_CONSTEXPR std::enable_if< std::is_arithmetic< T >::value, bool >::type AlmostZero (T value)
Gets whether a given value is almost zero.
template<typename T >
PLAYRHO_CONSTEXPR std::enable_if< std::is_floating_point< T >::value, bool >::type AlmostEqual (T x, T y, int ulp=2)
Determines whether the given two values are "almost equal".
template<typename T >
auto ModuloViaFmod (T dividend, T divisor) noexcept
Modulo operation using std::fmod.
template<typename T >
auto ModuloViaTrunc (T dividend, T divisor) noexcept
Modulo operation using std::trunc.
Angle GetNormalized (Angle value) noexcept
Gets the "normalized" value of the given angle.
Position GetNormalized (const Position &val) noexcept
Gets the "normalized" position.
Sweep GetNormalized (Sweep sweep) noexcept
Gets a sweep with the given sweeps's angles normalized.
Angle GetAngle (const UnitVec2 value)
Gets the angle of the given unit vector.
template<class T >
Angle GetAngle (const Vector2< T > value)
Gets the angle.
template<typename T >
PLAYRHO_CONSTEXPR auto GetMagnitudeSquared (T value) noexcept
Gets the square of the magnitude of the given iterable value.
template<typename T >
auto GetMagnitude (T value)
Gets the magnitude of the given value.
template<typename T1 , typename T2 >
PLAYRHO_CONSTEXPR auto Dot (const T1 a, const T2 b) noexcept
Performs the dot product on two vectors (A and B).
template<class T1 , class T2 , std::enable_if_t< std::tuple_size< T1 >::value==2 &&std::tuple_size< T2 >::value==2, int > = 0>
PLAYRHO_CONSTEXPR auto Cross (T1 a, T2 b) noexcept
Performs the 2-element analog of the cross product of two vectors.
template<typename T , typename U >
PLAYRHO_CONSTEXPR auto Solve (const Matrix22< U > mat, const Vector2< T > b) noexcept
Solves A * x = b, where b is a column vector.
template<class IN_TYPE >
PLAYRHO_CONSTEXPR auto Invert (const Matrix22< IN_TYPE > value) noexcept
Inverts the given value.
PLAYRHO_CONSTEXPR Vec3 Solve33 (const Mat33 &mat, const Vec3 b) noexcept
Solves A * x = b, where b is a column vector.
template<typename T >
PLAYRHO_CONSTEXPR T Solve22 (const Mat33 &mat, const T b) noexcept
Solves A * x = b, where b is a column vector.
PLAYRHO_CONSTEXPR Mat33 GetInverse22 (const Mat33 &value) noexcept
Gets the inverse of the given matrix as a 2-by-2.
PLAYRHO_CONSTEXPR Mat33 GetSymInverse33 (const Mat33 &value) noexcept
Gets the symmetric inverse of this matrix as a 3-by-3.
template<class T >
PLAYRHO_CONSTEXPR auto GetRevPerpendicular (const T vector) noexcept
Gets a vector counter-clockwise (reverse-clockwise) perpendicular to the given vector.
template<class T >
PLAYRHO_CONSTEXPR auto GetFwdPerpendicular (const T vector) noexcept
Gets a vector clockwise (forward-clockwise) perpendicular to the given vector.
PLAYRHO_CONSTEXPR Vec2 Transform (const Vec2 v, const Mat22 &A) noexcept
Multiply a matrix times a vector. If a rotation matrix is provided, then this transforms the vector from one frame to another.
PLAYRHO_CONSTEXPR Vec2 InverseTransform (const Vec2 v, const Mat22 &A) noexcept
Multiply a matrix transpose times a vector. If a rotation matrix is provided, then this transforms the vector from one frame to another (inverse transform).
template<class T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR Vector2< T > operator* (BoundedValue< T, lo, hi > s, UnitVec2 u) noexcept
Multiplication operator.
template<class T >
PLAYRHO_CONSTEXPR Vector2< T > operator* (const T s, const UnitVec2 u) noexcept
Multiplication operator.
template<class T , LoValueCheck lo, HiValueCheck hi>
PLAYRHO_CONSTEXPR Vector2< T > operator* (UnitVec2 u, BoundedValue< T, lo, hi > s) noexcept
Multiplication operator.
template<class T >
PLAYRHO_CONSTEXPR Vector2< T > operator* (const UnitVec2 u, const T s) noexcept
Multiplication operator.
PLAYRHO_CONSTEXPR Vec2 operator/ (const UnitVec2 u, const UnitVec2::value_type s) noexcept
Division operator.
PLAYRHO_CONSTEXPR Mat22 Mul (const Mat22 &A, const Mat22 &B) noexcept
Computes A * B.
PLAYRHO_CONSTEXPR Mat22 MulT (const Mat22 &A, const Mat22 &B) noexcept
Computes A^T * B.
PLAYRHO_CONSTEXPR Vec3 Transform (const Vec3 &v, const Mat33 &A) noexcept
Multiplies a matrix by a vector.
template<class T >
PLAYRHO_CONSTEXPR auto Rotate (const Vector2< T > vector, const UnitVec2 &angle) noexcept
Rotates a vector by a given angle.
template<class T >
PLAYRHO_CONSTEXPR auto InverseRotate (const Vector2< T > vector, const UnitVec2 &angle) noexcept
Inverse rotates a vector.
PLAYRHO_CONSTEXPR Length2 Transform (const Length2 v, const Transformation xfm) noexcept
Transforms the given 2-D vector with the given transformation.
PLAYRHO_CONSTEXPR Length2 InverseTransform (const Length2 v, const Transformation T) noexcept
Inverse transforms the given 2-D vector with the given transformation.
PLAYRHO_CONSTEXPR Transformation Mul (const Transformation &A, const Transformation &B) noexcept
Multiplies a given transformation by another given transformation.
PLAYRHO_CONSTEXPR Transformation MulT (const Transformation &A, const Transformation &B) noexcept
Inverse multiplies a given transformation by another given transformation.
template<>
Vec2 Abs (Vec2 a)
Gets the absolute value of the given value.
template<>
UnitVec2 Abs (UnitVec2 a)
Gets the absolute value of the given value.
Mat22 Abs (const Mat22 &A)
Gets the absolute value of the given value.
template<typename T >
PLAYRHO_CONSTEXPR T Clamp (T value, T low, T high) noexcept
Clamps the given value within the given range (inclusive).
std::uint64_t NextPowerOfTwo (std::uint64_t x)
Gets the next largest power of 2.
PLAYRHO_CONSTEXPR Transformation GetTransformation (const Length2 ctr, const UnitVec2 rot, const Length2 localCtr) noexcept
Gets the transformation for the given values.
Transformation GetTransformation (const Position pos, const Length2 local_ctr) noexcept
Gets the transformation for the given values.
Transformation GetTransformation (const Sweep &sweep, const Real beta) noexcept
Gets the interpolated transform at a specific time.
Transformation GetTransform0 (const Sweep &sweep) noexcept
Gets the transform at "time" zero.
Transformation GetTransform1 (const Sweep &sweep) noexcept
Gets the transform at "time" one.
Real Normalize (Vec2 &vector)
Converts the given vector into a unit vector and returns its original length.
LinearVelocity2 GetContactRelVelocity (const Velocity velA, const Length2 relA, const Velocity velB, const Length2 relB) noexcept
Gets the contact relative velocity.
template<typename T >
PLAYRHO_CONSTEXPR T GetModuloNext (T value, T count) noexcept
Gets the modulo next value.
template<typename T >
PLAYRHO_CONSTEXPR T GetModuloPrev (T value, T count) noexcept
Gets the modulo previous value.
PLAYRHO_CONSTEXPR Angle GetRevRotationalAngle (Angle a1, Angle a2) noexcept
Gets the reverse (counter) clockwise rotational angle to go from angle 1 to angle 2.
template<class T >
UnitVec2 GetUnitVector (Vector2< T > value, UnitVec2 fallback=UnitVec2::GetDefaultFallback())
Gets the unit vector for the given value.
bool IsUnderActive (Velocity velocity, LinearVelocity linSleepTol, AngularVelocity angSleepTol) noexcept
Gets whether the given velocity is "under active" based on the given tolerances.
template<>
PLAYRHO_CONSTEXPR bool IsValid (const Mat22 &value) noexcept
Determines if the given value is valid.
template<>
PLAYRHO_CONSTEXPR Mat22 GetInvalid () noexcept
Gets an invalid value for a Mat22.
template<>
PLAYRHO_CONSTEXPR bool IsValid (const Position &value) noexcept
Determines if the given value is valid.
PLAYRHO_CONSTEXPR bool operator== (const Position &lhs, const Position &rhs)
Equality operator.
PLAYRHO_CONSTEXPR bool operator!= (const Position &lhs, const Position &rhs)
Inequality operator.
PLAYRHO_CONSTEXPR Position operator- (const Position &value)
Negation operator.
PLAYRHO_CONSTEXPR Position operator+ (const Position &value)
Positive operator.
PLAYRHO_CONSTEXPR Position & operator+= (Position &lhs, const Position &rhs)
Addition assignment operator.
PLAYRHO_CONSTEXPR Position operator+ (const Position &lhs, const Position &rhs)
Addition operator.
PLAYRHO_CONSTEXPR Position & operator-= (Position &lhs, const Position &rhs)
Subtraction assignment operator.
PLAYRHO_CONSTEXPR Position operator- (const Position &lhs, const Position &rhs)
Subtraction operator.
PLAYRHO_CONSTEXPR Position operator* (const Position &pos, const Real scalar)
Multiplication operator.
PLAYRHO_CONSTEXPR Position operator* (const Real scalar, const Position &pos)
Multiplication operator.
PLAYRHO_CONSTEXPR Position GetPosition (const Position pos0, const Position pos1, const Real beta) noexcept
Gets the position between two positions at a given unit interval.
template<typename AT , class For >
constexpr StrongTyped< AT, For > operator+ (StrongTyped< AT, For > lhs, const StrongTyped< AT, For > &rhs) noexcept
Addition operator.
template<typename AT , class For >
constexpr StrongTyped< AT, For > operator- (StrongTyped< AT, For > lhs, const StrongTyped< AT, For > &rhs) noexcept
Subtraction operator.
template<typename AT , class For >
constexpr bool operator== (const StrongTyped< AT, For > &lhs, const StrongTyped< AT, For > &rhs) noexcept
Equality operator.
template<typename AT , class For >
constexpr bool operator!= (const StrongTyped< AT, For > &lhs, const StrongTyped< AT, For > &rhs) noexcept
Inequality operator.
template<typename AT , class For >
constexpr bool operator< (const StrongTyped< AT, For > &lhs, const StrongTyped< AT, For > &rhs) noexcept
Less-than operator.
template<typename AT , class For >
constexpr bool operator<= (const StrongTyped< AT, For > &lhs, const StrongTyped< AT, For > &rhs) noexcept
Less-than or equal-to operator.
template<typename AT , class For >
constexpr bool operator> (const StrongTyped< AT, For > &lhs, const StrongTyped< AT, For > &rhs) noexcept
Greater-than operator.
template<typename AT , class For >
constexpr bool operator>= (const StrongTyped< AT, For > &lhs, const StrongTyped< AT, For > &rhs) noexcept
Greater-than or equal-to operator.
template<>
PLAYRHO_CONSTEXPR bool IsValid (const Sweep &value) noexcept
Determines if the given value is valid.
template<class... T>
void NOT_USED (T &&...)
"Not used" annotator.
template<typename T >
PLAYRHO_CONSTEXPR T GetInvalid () noexcept
Gets an invalid value for the type.
template<typename T >
PLAYRHO_CONSTEXPR bool IsValid (const T &value) noexcept
Determines if the given value is valid.
template<>
PLAYRHO_CONSTEXPR float GetInvalid () noexcept
Gets an invalid value for the float type.
template<>
PLAYRHO_CONSTEXPR double GetInvalid () noexcept
Gets an invalid value for the double type.
template<>
PLAYRHO_CONSTEXPR long double GetInvalid () noexcept
Gets an invalid value for the long double type.
template<>
PLAYRHO_CONSTEXPR std::size_t GetInvalid () noexcept
Gets an invalid value for the std::size_t type.
template<>
PLAYRHO_CONSTEXPR bool IsValid (const std::size_t &value) noexcept
Determines if the given value is valid.
template<class T >
PLAYRHO_CONSTEXPR const T * GetPtr (const T *value) noexcept
Gets a pointer for the given variable.
template<class T >
PLAYRHO_CONSTEXPR T * GetPtr (T *value) noexcept
Gets a pointer for the given variable.
template<class T >
PLAYRHO_CONSTEXPR const T * GetPtr (const T &value) noexcept
Gets a pointer for the given variable.
template<class T >
PLAYRHO_CONSTEXPR T * GetPtr (T &value) noexcept
Gets a pointer for the given variable.
template<class T >
PLAYRHO_CONSTEXPR const T & GetRef (const T *value) noexcept
Gets a reference for the given variable.
template<class T >
PLAYRHO_CONSTEXPR T & GetRef (T *value) noexcept
Gets a reference for the given variable.
template<class T >
PLAYRHO_CONSTEXPR const T & GetRef (const T &value) noexcept
Gets a reference for the given variable.
template<class T >
PLAYRHO_CONSTEXPR T & GetRef (T &value) noexcept
Gets a reference for the given variable.
template<typename T >
const char * GetTypeName () noexcept
Gets the library defined name for the given type.
template<>
const char * GetTypeName< float > () noexcept
Gets a human recognizable name for the float type.
template<>
const char * GetTypeName< double > () noexcept
Gets a human recognizable name for the double type.
template<>
const char * GetTypeName< long double > () noexcept
Gets a human recognizable name for the long double type.
template<typename T >
PLAYRHO_CONSTEXPR T Abs (T a)
Computes the absolute value of the given value.
template<>
PLAYRHO_CONSTEXPR bool IsValid (const Transformation &value) noexcept
Determines if the given value is valid.
PLAYRHO_CONSTEXPR bool operator== (Transformation lhs, Transformation rhs) noexcept
Equality operator.
PLAYRHO_CONSTEXPR bool operator!= (Transformation lhs, Transformation rhs) noexcept
Inequality operator.
PLAYRHO_CONSTEXPR Mass operator"" _g (unsigned long long int v) noexcept
SI unit symbol for a gram unit of Mass.
PLAYRHO_CONSTEXPR Mass operator"" _g (long double v) noexcept
SI unit symbol for a gram unit of Mass.
PLAYRHO_CONSTEXPR Mass operator"" _kg (unsigned long long int v) noexcept
SI unit symbol for a kilogram unit of Mass.
PLAYRHO_CONSTEXPR Mass operator"" _kg (long double v) noexcept
SI unit symbol for a kilogram unit of Mass.
PLAYRHO_CONSTEXPR Mass operator"" _Yg (unsigned long long int v) noexcept
SI unit symbol for a yottagram unit of Mass.
PLAYRHO_CONSTEXPR Mass operator"" _Yg (long double v) noexcept
SI unit symbol for a yottagram unit of Mass.
PLAYRHO_CONSTEXPR Length operator"" _m (unsigned long long int v) noexcept
SI unit symbol for a meter of Length.
PLAYRHO_CONSTEXPR Length operator"" _m (long double v) noexcept
SI unit symbol for a meter of Length.
PLAYRHO_CONSTEXPR Length operator"" _dm (unsigned long long int v) noexcept
SI unit symbol for a decimeter of Length.
PLAYRHO_CONSTEXPR Length operator"" _dm (long double v) noexcept
SI unit symbol for a decimeter of Length.
PLAYRHO_CONSTEXPR Length operator"" _cm (unsigned long long int v) noexcept
SI unit symbol for a centimeter of Length.
PLAYRHO_CONSTEXPR Length operator"" _cm (long double v) noexcept
SI unit symbol for a centimeter of Length.
PLAYRHO_CONSTEXPR Length operator"" _Gm (unsigned long long int v) noexcept
SI unit symbol for a gigameter unit of Length.
PLAYRHO_CONSTEXPR Length operator"" _Gm (long double v) noexcept
SI unit symbol for a gigameter unit of Length.
PLAYRHO_CONSTEXPR Length operator"" _km (unsigned long long int v) noexcept
SI symbol for a kilometer unit of Length.
PLAYRHO_CONSTEXPR Length operator"" _km (long double v) noexcept
SI symbol for a kilometer unit of Length.
PLAYRHO_CONSTEXPR Time operator"" _s (unsigned long long int v) noexcept
SI symbol for a second unit of Time.
PLAYRHO_CONSTEXPR Time operator"" _s (long double v) noexcept
SI symbol for a second unit of Time.
PLAYRHO_CONSTEXPR Time operator"" _min (unsigned long long int v) noexcept
SI symbol for a minute unit of Time.
PLAYRHO_CONSTEXPR Time operator"" _min (long double v) noexcept
SI symbol for a minute unit of Time.
PLAYRHO_CONSTEXPR Time operator"" _h (unsigned long long int v) noexcept
Symbol for an hour unit of Time.
PLAYRHO_CONSTEXPR Time operator"" _h (long double v) noexcept
Symbol for an hour unit of Time.
PLAYRHO_CONSTEXPR Time operator"" _d (unsigned long long int v) noexcept
Symbol for a day unit of Time.
PLAYRHO_CONSTEXPR Time operator"" _d (long double v) noexcept
Symbol for a day unit of Time.
PLAYRHO_CONSTEXPR Angle operator"" _rad (unsigned long long int v) noexcept
SI symbol for a radian unit of Angle.
PLAYRHO_CONSTEXPR Angle operator"" _rad (long double v) noexcept
SI symbol for a radian unit of Angle.
PLAYRHO_CONSTEXPR Angle operator"" _deg (unsigned long long int v) noexcept
Abbreviation for a degree unit of Angle.
PLAYRHO_CONSTEXPR Angle operator"" _deg (long double v) noexcept
Abbreviation for a degree unit of Angle.
PLAYRHO_CONSTEXPR Force operator"" _N (unsigned long long int v) noexcept
SI symbol for a newton unit of Force.
PLAYRHO_CONSTEXPR Force operator"" _N (long double v) noexcept
SI symbol for a newton unit of Force.
PLAYRHO_CONSTEXPR Area operator"" _m2 (unsigned long long int v) noexcept
Abbreviation for meter squared unit of Area.
PLAYRHO_CONSTEXPR Area operator"" _m2 (long double v) noexcept
Abbreviation for meter squared unit of Area.
PLAYRHO_CONSTEXPR LinearVelocity operator"" _mps (unsigned long long int v) noexcept
Abbreviation for meter per second.
PLAYRHO_CONSTEXPR LinearVelocity operator"" _mps (long double v) noexcept
Abbreviation for meter per second.
PLAYRHO_CONSTEXPR LinearVelocity operator"" _kps (unsigned long long int v) noexcept
Abbreviation for kilometer per second.
PLAYRHO_CONSTEXPR LinearVelocity operator"" _kps (long double v) noexcept
Abbreviation for kilometer per second.
PLAYRHO_CONSTEXPR LinearAcceleration operator"" _mps2 (unsigned long long int v) noexcept
Abbreviation for meter per second squared.
PLAYRHO_CONSTEXPR LinearAcceleration operator"" _mps2 (long double v) noexcept
Abbreviation for meter per second squared.
PLAYRHO_CONSTEXPR Frequency operator"" _Hz (unsigned long long int v) noexcept
SI symbol for a hertz unit of Frequency.
PLAYRHO_CONSTEXPR Frequency operator"" _Hz (long double v) noexcept
SI symbol for a hertz unit of Frequency.
PLAYRHO_CONSTEXPR Torque operator"" _Nm (unsigned long long int v) noexcept
Abbreviation for newton-meter unit of torque.
PLAYRHO_CONSTEXPR Torque operator"" _Nm (long double v) noexcept
Abbreviation for newton-meter unit of torque.
PLAYRHO_CONSTEXPR Momentum operator"" _Ns (unsigned long long int v) noexcept
SI symbol for a newton second of impulse.
PLAYRHO_CONSTEXPR Momentum operator"" _Ns (long double v) noexcept
SI symbol for a newton second of impulse.
PLAYRHO_CONSTEXPR AreaDensity operator"" _kgpm2 (unsigned long long int v) noexcept
Abbreviation for kilogram per square meter.
PLAYRHO_CONSTEXPR AreaDensity operator"" _kgpm2 (long double v) noexcept
Abbreviation for kilogram per square meter.
PLAYRHO_CONSTEXPR AngularVelocity operator"" _rpm (unsigned long long int v) noexcept
Abbreviation for revolutions per minute.
PLAYRHO_CONSTEXPR AngularVelocity operator"" _rpm (long double v) noexcept
Abbreviation for revolutions per minute.
PLAYRHO_CONSTEXPR Real StripUnit (const Real value)
Strips the units off of the given value.
PLAYRHO_CONSTEXPR UnitVec2 GetXAxis (UnitVec2 rot) noexcept
Gets the "X-axis".
PLAYRHO_CONSTEXPR UnitVec2 GetYAxis (UnitVec2 rot) noexcept
Gets the "Y-axis".
PLAYRHO_CONSTEXPR bool operator== (const UnitVec2 a, const UnitVec2 b) noexcept
Equality operator.
PLAYRHO_CONSTEXPR bool operator!= (const UnitVec2 a, const UnitVec2 b) noexcept
Inequality operator.
PLAYRHO_CONSTEXPR UnitVec2 GetRevPerpendicular (const UnitVec2 vector) noexcept
Gets a vector counter-clockwise (reverse-clockwise) perpendicular to the given vector.
PLAYRHO_CONSTEXPR UnitVec2 GetFwdPerpendicular (const UnitVec2 vector) noexcept
Gets a vector clockwise (forward-clockwise) perpendicular to the given vector.
PLAYRHO_CONSTEXPR UnitVec2 Rotate (const UnitVec2 vector, const UnitVec2 &angle) noexcept
Rotates a unit vector by the angle expressed by the second unit vector.
PLAYRHO_CONSTEXPR UnitVec2 InverseRotate (const UnitVec2 vector, const UnitVec2 &angle) noexcept
Inverse rotates a vector.
template<>
PLAYRHO_CONSTEXPR UnitVec2 GetInvalid () noexcept
Gets an invalid value for the UnitVec2 type.
template<>
PLAYRHO_CONSTEXPR bool IsValid (const UnitVec2 &value) noexcept
Determines if the given value is valid.
template<size_t I>
PLAYRHO_CONSTEXPR UnitVec2::value_type Get (UnitVec2 v) noexcept
Gets the I'th element of the given collection.
template<>
PLAYRHO_CONSTEXPR UnitVec2::value_type Get< 0 > (UnitVec2 v) noexcept
Gets the 0'th element of the given collection.
template<>
PLAYRHO_CONSTEXPR UnitVec2::value_type Get< 1 > (UnitVec2 v) noexcept
Gets the 1'st element of the given collection.
inline ::std::ostream & operator<< (::std::ostream &os, const UnitVec2 &value)
Output stream operator.
template<typename T , std::size_t N>
PLAYRHO_CONSTEXPR bool operator== (const Vector< T, N > &lhs, const Vector< T, N > &rhs) noexcept
Equality operator.
template<typename T , std::size_t N>
PLAYRHO_CONSTEXPR bool operator!= (const Vector< T, N > &lhs, const Vector< T, N > &rhs) noexcept
Inequality operator.
template<typename T , std::size_t N>
PLAYRHO_CONSTEXPR auto operator+ (Vector< T, N > v) noexcept
Unary plus operator.
template<typename T , std::size_t N>
PLAYRHO_CONSTEXPR auto operator- (Vector< T, N > v) noexcept
Unary negation operator.
template<typename T , std::size_t N>
PLAYRHO_CONSTEXPR auto & operator+= (Vector< T, N > &lhs, const Vector< T, N > rhs) noexcept
Increments the left hand side value by the right hand side value.
template<typename T , std::size_t N>
PLAYRHO_CONSTEXPR auto & operator-= (Vector< T, N > &lhs, const Vector< T, N > rhs) noexcept
Decrements the left hand side value by the right hand side value.
template<typename T , std::size_t N>
PLAYRHO_CONSTEXPR auto operator+ (Vector< T, N > lhs, const Vector< T, N > rhs) noexcept
Adds two vectors component-wise.
template<typename T , std::size_t N>
PLAYRHO_CONSTEXPR auto operator- (Vector< T, N > lhs, const Vector< T, N > rhs) noexcept
Subtracts two vectors component-wise.
template<typename T , std::size_t N>
PLAYRHO_CONSTEXPR auto & operator*= (Vector< T, N > &lhs, const Real rhs) noexcept
Multiplication assignment operator.
template<typename T , std::size_t N>
PLAYRHO_CONSTEXPR auto & operator/= (Vector< T, N > &lhs, const Real rhs) noexcept
Division assignment operator.
template<std::size_t N, typename T1 , typename T2 , typename OT = decltype(T1{} * T2{})>
PLAYRHO_CONSTEXPR auto operator* (const T1 s, const Vector< T2, N > &a) noexcept
Multiplication operator.
template<std::size_t N, typename T1 , typename T2 , typename OT = decltype(T1{} * T2{})>
PLAYRHO_CONSTEXPR auto operator* (const Vector< T1, N > &a, const T2 s) noexcept
Multiplication operator.
template<std::size_t N, typename T1 , typename T2 , typename OT = decltype(T1{} / T2{})>
PLAYRHO_CONSTEXPR auto operator/ (const Vector< T1, N > &a, const T2 s) noexcept
Division operator.
template<std::size_t N, typename T1 , typename T2 , typename OT = decltype(T1{} * T2{})>
PLAYRHO_CONSTEXPR auto operator* (const Vector< T1, N > &lhs, const Vector< T2, N > &rhs) noexcept
Multiplication operator.
template<std::size_t N, typename T1 , typename T2 , typename OT = decltype(T1{} / T2{})>
PLAYRHO_CONSTEXPR auto operator/ (const Vector< T1, N > &lhs, const Vector< T2, N > &rhs) noexcept
Division operator.
template<typename T , std::size_t N>
PLAYRHO_CONSTEXPR bool operator< (const Vector< T, N > &lhs, const Vector< T, N > &rhs) noexcept
Lexicographical less-than operator.
template<typename T , std::size_t N>
PLAYRHO_CONSTEXPR bool operator<= (const Vector< T, N > &lhs, const Vector< T, N > &rhs) noexcept
Lexicographical less-than or equal-to operator.
template<typename T , std::size_t N>
PLAYRHO_CONSTEXPR bool operator> (const Vector< T, N > &lhs, const Vector< T, N > &rhs) noexcept
Lexicographical greater-than operator.
template<typename T , std::size_t N>
PLAYRHO_CONSTEXPR bool operator>= (const Vector< T, N > &lhs, const Vector< T, N > &rhs) noexcept
Lexicographical greater-than or equal-to operator.
template<size_t I, size_t N, typename T >
PLAYRHO_CONSTEXPR auto & Get (Vector< T, N > &v) noexcept
Gets the I'th element of the given collection.
template<size_t I, size_t N, typename T >
PLAYRHO_CONSTEXPR auto Get (const Vector< T, N > &v) noexcept
Gets the I'th element of the given collection.
template<typename T , std::size_t N>
::std::ostream & operator<< (::std::ostream &os, const Vector< T, N > &value)
Output stream operator.
PLAYRHO_CONSTEXPR Vec2 GetVec2 (const Vector2< Real > value)
Gets the given value as a Vec2.
template<>
PLAYRHO_CONSTEXPR Vec2 GetInvalid () noexcept
Gets an invalid value for the Vec2 type.
template<typename TYPE >
PLAYRHO_CONSTEXPR bool IsValid (const Vector2< TYPE > &value) noexcept
Determines whether the given vector contains finite coordinates.
template<>
PLAYRHO_CONSTEXPR Vec3 GetInvalid () noexcept
Gets an invalid value for the Vec3 type.
template<>
PLAYRHO_CONSTEXPR bool IsValid (const Velocity &value) noexcept
Determines if the given value is valid.
PLAYRHO_CONSTEXPR bool operator== (const Velocity &lhs, const Velocity &rhs)
Equality operator.
PLAYRHO_CONSTEXPR bool operator!= (const Velocity &lhs, const Velocity &rhs)
Inequality operator.
PLAYRHO_CONSTEXPR Velocity & operator*= (Velocity &lhs, const Real rhs)
Multiplication assignment operator.
PLAYRHO_CONSTEXPR Velocity & operator/= (Velocity &lhs, const Real rhs)
Division assignment operator.
PLAYRHO_CONSTEXPR Velocity & operator+= (Velocity &lhs, const Velocity &rhs)
Addition assignment operator.
PLAYRHO_CONSTEXPR Velocity operator+ (const Velocity &lhs, const Velocity &rhs)
Addition operator.
PLAYRHO_CONSTEXPR Velocity & operator-= (Velocity &lhs, const Velocity &rhs)
Subtraction assignment operator.
PLAYRHO_CONSTEXPR Velocity operator- (const Velocity &lhs, const Velocity &rhs)
Subtraction operator.
PLAYRHO_CONSTEXPR Velocity operator- (const Velocity &value)
Negation operator.
PLAYRHO_CONSTEXPR Velocity operator+ (const Velocity &value)
Positive operator.
PLAYRHO_CONSTEXPR Velocity operator* (const Velocity &lhs, const Real rhs)
Multiplication operator.
PLAYRHO_CONSTEXPR Velocity operator* (const Real lhs, const Velocity &rhs)
Multiplication operator.
PLAYRHO_CONSTEXPR Velocity operator/ (const Velocity &lhs, const Real rhs)
Division operator.
Version GetVersion () noexcept
Gets the version information of the library.
std::string GetBuildDetails () noexcept
Gets the build details of the library.
PLAYRHO_CONSTEXPR bool operator== (Version lhs, Version rhs)
Equality operator.
PLAYRHO_CONSTEXPR bool operator!= (Version lhs, Version rhs)
Inequality operator.
bool ShouldCollide (const Body &lhs, const Body &rhs) noexcept
Should collide.
BodyCounter GetWorldIndex (const Body *body) noexcept
Gets the world index for the given body.
Velocity GetVelocity (const Body &body, Time h, MovementConf conf) noexcept
Gets the velocity of the body after the given time accounting for the body's acceleration and capped by the given configuration.
std::size_t GetFixtureCount (const Body &body) noexcept
Gets the fixture count of the given body.
void RotateAboutWorldPoint (Body &body, Angle amount, Length2 worldPoint)
Rotates a body a given amount around a point in world coordinates.
void RotateAboutLocalPoint (Body &body, Angle amount, Length2 localPoint)
Rotates a body a given amount around a point in body local coordinates.
Force2 GetCentripetalForce (const Body &body, Length2 axis)
Gets the centripetal force necessary to put the body into an orbit having the given radius.
Acceleration CalcGravitationalAcceleration (const Body &body) noexcept
Calculates the gravitationally associated acceleration for the given body within its world.
Acceleration GetAcceleration (const Body &body) noexcept
Gets the given body's acceleration.
void SetAcceleration (Body &body, Acceleration value) noexcept
Sets the accelerations on the given body.
bool Awaken (Body &body) noexcept
Awakens the body if it's asleep.
bool Unawaken (Body &body) noexcept
Puts the body to sleep if it's awake.
Position GetPosition1 (const Body &body) noexcept
Gets the "position 1" Position information for the given body.
Mass GetMass (const Body &body) noexcept
Gets the total mass of the body.
void SetLinearAcceleration (Body &body, LinearAcceleration2 value) noexcept
Sets the given linear acceleration of the given body.
void SetAngularAcceleration (Body &body, AngularAcceleration value) noexcept
Sets the given angular acceleration of the given body.
void ApplyLinearAcceleration (Body &body, LinearAcceleration2 amount)
Applies the given linear acceleration to the given body.
void SetForce (Body &body, Force2 force, Length2 point) noexcept
Sets the given amount of force at the given point to the given body.
void ApplyForce (Body &body, Force2 force, Length2 point) noexcept
Apply a force at a world point.
void ApplyForceToCenter (Body &body, Force2 force) noexcept
Apply a force to the center of mass.
void SetTorque (Body &body, Torque torque) noexcept
Sets the given amount of torque to the given body.
void ApplyTorque (Body &body, Torque torque) noexcept
Applies a torque.
void ApplyLinearImpulse (Body &body, Momentum2 impulse, Length2 point) noexcept
Applies an impulse at a point.
void ApplyAngularImpulse (Body &body, AngularMomentum impulse) noexcept
Applies an angular impulse.
RotInertia GetRotInertia (const Body &body) noexcept
Gets the rotational inertia of the body.
RotInertia GetLocalRotInertia (const Body &body) noexcept
Gets the rotational inertia of the body about the local origin.
LinearVelocity2 GetLinearVelocity (const Body &body) noexcept
Gets the linear velocity of the center of mass.
AngularVelocity GetAngularVelocity (const Body &body) noexcept
Gets the angular velocity.
void SetLinearVelocity (Body &body, const LinearVelocity2 v) noexcept
Sets the linear velocity of the center of mass.
void SetAngularVelocity (Body &body, AngularVelocity omega) noexcept
Sets the angular velocity.
Length2 GetWorldPoint (const Body &body, const Length2 localPoint) noexcept
Gets the world coordinates of a point given in coordinates relative to the body's origin.
Length2 GetWorldVector (const Body &body, const Length2 localVector) noexcept
Gets the world coordinates of a vector given the local coordinates.
UnitVec2 GetWorldVector (const Body &body, const UnitVec2 localVector) noexcept
Gets the world vector for the given local vector from the given body's transformation.
Length2 GetLocalPoint (const Body &body, const Length2 worldPoint) noexcept
Gets a local point relative to the body's origin given a world point.
UnitVec2 GetLocalVector (const Body &body, const UnitVec2 uv) noexcept
Gets a locally oriented unit vector given a world oriented unit vector.
LinearVelocity2 GetLinearVelocityFromWorldPoint (const Body &body, const Length2 worldPoint) noexcept
Gets the linear velocity from a world point attached to this body.
LinearVelocity2 GetLinearVelocityFromLocalPoint (const Body &body, const Length2 localPoint) noexcept
Gets the linear velocity from a local point.
Force2 GetForce (const Body &body) noexcept
Gets the net force that the given body is currently experiencing.
Torque GetTorque (const Body &body) noexcept
Gets the net torque that the given body is currently experiencing.
Length2 GetLocation (const Body &body) noexcept
Gets the body's origin location.
Angle GetAngle (const Body &body) noexcept
Gets the body's angle.
void SetLocation (Body &body, Length2 value) noexcept
Sets the body's location.
void SetAngle (Body &body, Angle value) noexcept
Sets the body's angular orientation.
BodyDef GetBodyDef (const Body &body) noexcept
Gets the body definition for the given body.
PLAYRHO_CONSTEXPR BodyDef GetDefaultBodyDef () noexcept
Gets the default body definition.
BodyConstraint GetBodyConstraint (const Body &body, Time time, MovementConf conf) noexcept
Gets the BodyConstraint based on the given parameters.
Body * GetBodyA (const Contact &contact) noexcept
Gets the body A associated with the given contact.
Body * GetBodyB (const Contact &contact) noexcept
Gets the body B associated with the given contact.
bool HasSensor (const Contact &contact) noexcept
Whether the given contact has a sensor.
bool IsImpenetrable (const Contact &contact) noexcept
Whether the given contact is "impenetrable".
bool IsActive (const Contact &contact) noexcept
Determines whether the given contact is "active".
void SetAwake (const Contact &c) noexcept
Sets awake the fixtures of the given contact.
void ResetFriction (Contact &contact)
Resets the friction mixture to the default value.
void ResetRestitution (Contact &contact) noexcept
Reset the restitution to the default value.
TOIOutput CalcToi (const Contact &contact, ToiConf conf)
Calculates the Time Of Impact for the given contact with the given configuration.
Real MixFriction (Real friction1, Real friction2)
Mixes friction.
Real MixRestitution (Real restitution1, Real restitution2) noexcept
Mixes restitution.
Fixture * GetFixtureA (const Contact &contact) noexcept
Gets the fixture A associated with the given contact.
Fixture * GetFixtureB (const Contact &contact) noexcept
Gets the fixture B associated with the given contact.
ContactKey GetContactKey (const Fixture &fixtureA, ChildCounter childIndexA, const Fixture &fixtureB, ChildCounter childIndexB) noexcept
Gets the ContactKey for the given parameters.
ContactKey GetContactKey (const Contact &contact) noexcept
Gets the ContactKey for the given contact.
PLAYRHO_CONSTEXPR bool operator== (const ContactKey lhs, const ContactKey rhs) noexcept
Equality operator.
PLAYRHO_CONSTEXPR bool operator!= (const ContactKey lhs, const ContactKey rhs) noexcept
Inequality operator.
PLAYRHO_CONSTEXPR bool operator< (const ContactKey lhs, const ContactKey rhs) noexcept
Less-than operator.
PLAYRHO_CONSTEXPR bool operator<= (const ContactKey lhs, const ContactKey rhs) noexcept
Less-than or equal-to operator.
PLAYRHO_CONSTEXPR bool operator> (const ContactKey lhs, const ContactKey rhs) noexcept
Greater-than operator.
PLAYRHO_CONSTEXPR bool operator>= (const ContactKey lhs, const ContactKey rhs) noexcept
Greater-than or equal-to operator.
Contact * GetContactPtr (KeyedContactPtr value)
Gets the contact pointer for the given value.
PositionSolution operator+ (PositionSolution lhs, PositionSolution rhs)
Addition operator.
PositionSolution operator- (PositionSolution lhs, PositionSolution rhs)
Subtraction operator.
ConstraintSolverConf GetDefaultPositionSolverConf ()
Gets the default position solver configuration.
ConstraintSolverConf GetDefaultToiPositionSolverConf ()
Gets the default TOI position solver configuration.
PositionSolverManifold GetPSM (const Manifold &manifold, Manifold::size_type index, const Transformation &xfA, const Transformation &xfB)
Gets the normal-point-separation data in world coordinates for the given inputs.
UnitVec2 GetNormal (const VelocityConstraint &vc) noexcept
Gets the normal of the velocity constraint contact in world coordinates.
UnitVec2 GetTangent (const VelocityConstraint &vc) noexcept
Gets the tangent from the given velocity constraint data.
InvMass GetInvMass (const VelocityConstraint &vc) noexcept
Gets the inverse mass from the given velocity constraint data.
Length2 GetPointRelPosA (const VelocityConstraint &vc, VelocityConstraint::size_type index)
Gets the point relative position A data.
Length2 GetPointRelPosB (const VelocityConstraint &vc, VelocityConstraint::size_type index)
Gets the point relative position B data.
LinearVelocity GetVelocityBiasAtPoint (const VelocityConstraint &vc, VelocityConstraint::size_type index)
Gets the velocity bias at the given point from the given velocity constraint.
Mass GetNormalMassAtPoint (const VelocityConstraint &vc, VelocityConstraint::size_type index)
Gets the normal mass at the given point from the given velocity constraint.
Mass GetTangentMassAtPoint (const VelocityConstraint &vc, VelocityConstraint::size_type index)
Gets the tangent mass at the given point from the given velocity constraint.
Momentum GetNormalImpulseAtPoint (const VelocityConstraint &vc, VelocityConstraint::size_type index)
Gets the normal impulse at the given point from the given velocity constraint.
Momentum GetTangentImpulseAtPoint (const VelocityConstraint &vc, VelocityConstraint::size_type index)
Gets the tangent impulse at the given point from the given velocity constraint.
Momentum2 GetNormalImpulses (const VelocityConstraint &vc)
Gets the normal impulses of the given velocity constraint.
Momentum2 GetTangentImpulses (const VelocityConstraint &vc)
Gets the tangent impulses of the given velocity constraint.
void SetNormalImpulseAtPoint (VelocityConstraint &vc, VelocityConstraint::size_type index, Momentum value)
Sets the normal impulse at the given point of the given velocity constraint.
void SetTangentImpulseAtPoint (VelocityConstraint &vc, VelocityConstraint::size_type index, Momentum value)
Sets the tangent impulse at the given point of the given velocity constraint.
void SetNormalImpulses (VelocityConstraint &vc, const Momentum2 impulses)
Sets the normal impulses of the given velocity constraint.
void SetTangentImpulses (VelocityConstraint &vc, const Momentum2 impulses)
Sets the tangent impulses of the given velocity constraint.
PLAYRHO_CONSTEXPR bool operator== (const Filter lhs, const Filter rhs) noexcept
Equality operator.
PLAYRHO_CONSTEXPR bool operator!= (const Filter lhs, const Filter rhs) noexcept
Inequality operator.
bool ShouldCollide (const Filter filterA, const Filter filterB) noexcept
Determines whether collision processing should be performed.
bool TestPoint (const Fixture &f, Length2 p) noexcept
Tests a point for containment in a fixture.
void SetAwake (const Fixture &f) noexcept
Sets the associated body's sleep status to awake.
Transformation GetTransformation (const Fixture &f) noexcept
Gets the transformation associated with the given fixture.
FixtureDef GetFixtureDef (const Fixture &fixture) noexcept
Gets the fixture definition for the given fixture.
PLAYRHO_CONSTEXPR FixtureDef GetDefaultFixtureDef () noexcept
Gets the default fixture definition.
PLAYRHO_CONSTEXPR bool operator== (const FixtureProxy &lhs, const FixtureProxy &rhs) noexcept
Equality operator.
PLAYRHO_CONSTEXPR bool operator!= (const FixtureProxy &lhs, const FixtureProxy &rhs) noexcept
Inequality operator.
std::size_t Count (const Island &island, const Body *entry)
Counts the number of occurrances of the given entry in the given island.
std::size_t Count (const Island &island, const Contact *entry)
Counts the number of occurrances of the given entry in the given island.
std::size_t Count (const Island &island, const Joint *entry)
Counts the number of occurrances of the given entry in the given island.
bool IsFullOfBodies (const Island &island)
Determines whether the given island is full of bodies.
bool IsFullOfContacts (const Island &island)
Determines whether the given island is full of contacts.
DistanceJointDef GetDistanceJointDef (const DistanceJoint &joint) noexcept
Gets the definition data for the given joint.
FrictionJointDef GetFrictionJointDef (const FrictionJoint &joint) noexcept
Gets the definition data for the given joint.
GearJointDef GetGearJointDef (const GearJoint &joint) noexcept
Gets the definition data for the given joint.
bool IsEnabled (const Joint &j) noexcept
Short-cut function to determine if both bodies are enabled.
void SetAwake (Joint &j) noexcept
Wakes up the joined bodies.
JointCounter GetWorldIndex (const Joint *joint)
Gets the world index of the given joint.
BodyConstraintPtr & At (std::unordered_map< const Body *, BodyConstraint * > &container, const Body *key)
Provides referenced access to the identified element of the given container.
const char * ToString (Joint::LimitState val) noexcept
Provides a human readable C-style string uniquely identifying the given limit state.
template<class T >
void IncMotorSpeed (T &j, AngularVelocity delta)
Increment motor speed.
void Set (JointDef &def, const Joint &joint) noexcept
Sets the joint definition data for the given joint.
JointKey GetJointKey (const Joint &joint) noexcept
Gets the JointKey for the given joint.
PLAYRHO_CONSTEXPR int Compare (const JointKey &lhs, const JointKey &rhs) noexcept
Compares the given joint keys.
PLAYRHO_CONSTEXPR bool IsFor (const JointKey key, const Body *body) noexcept
Determines whether the given key is for the given body.
Joint * GetJointPtr (std::pair< JointKey, Joint *> value)
Gets the joint pointer from the given value.
JointType GetType (const Joint &joint) noexcept
Gets the type of the given joint.
const char * ToString (JointType type) noexcept
Provides a C-style (null-terminated) string name for given joint type.
MotorJointDef GetMotorJointDef (const MotorJoint &joint) noexcept
Gets the definition data for the given joint.
MouseJointDef GetMouseJointDef (const MouseJoint &joint) noexcept
Gets the definition data for the given joint.
Length GetJointTranslation (const PrismaticJoint &joint) noexcept
Get the current joint translation.
LinearVelocity GetLinearVelocity (const PrismaticJoint &joint) noexcept
Get the current joint translation speed.
Force GetMotorForce (const PrismaticJoint &joint, Frequency inv_dt) noexcept
Gets the current motor force for the given joint, given the inverse time step.
PrismaticJointDef GetPrismaticJointDef (const PrismaticJoint &joint) noexcept
Gets the definition data for the given joint.
Length GetCurrentLengthA (const PulleyJoint &joint)
Get the current length of the segment attached to bodyA.
Length GetCurrentLengthB (const PulleyJoint &joint)
Get the current length of the segment attached to bodyB.
PulleyJointDef GetPulleyJointDef (const PulleyJoint &joint) noexcept
Gets the definition data for the given joint.
Angle GetJointAngle (const RevoluteJoint &joint)
Gets the current joint angle.
AngularVelocity GetAngularVelocity (const RevoluteJoint &joint)
Gets the current joint angle speed.
Torque GetMotorTorque (const RevoluteJoint &joint, Frequency inv_dt) noexcept
Gets the current motor torque for the given joint given the inverse time step.
RevoluteJointDef GetRevoluteJointDef (const RevoluteJoint &joint) noexcept
Gets the definition data for the given joint.
RopeJointDef GetRopeJointDef (const RopeJoint &joint) noexcept
Gets the definition data for the given joint.
WeldJointDef GetWeldJointDef (const WeldJoint &joint) noexcept
Gets the definition data for the given joint.
Length GetJointTranslation (const WheelJoint &joint) noexcept
Get the current joint translation.
AngularVelocity GetAngularVelocity (const WheelJoint &joint) noexcept
Get the current joint translation speed.
Torque GetMotorTorque (const WheelJoint &joint, Frequency inv_dt) noexcept
Gets the current motor torque for the given joint for the given the inverse time step.
WheelJointDef GetWheelJointDef (const WheelJoint &joint) noexcept
Gets the definition data for the given joint.
MovementConf GetMovementConf (const StepConf &conf) noexcept
Gets the movement configuration from the given value.
bool IsMaxTranslationWithinTolerance (const StepConf &conf) noexcept
Determines whether the maximum translation is within tolerance.
Length GetMaxRegLinearCorrection (const StepConf &conf) noexcept
Gets the maximum regular linear correction from the given value.
StepStats Step (World &world, Time delta, TimestepIters velocityIterations=8, TimestepIters positionIterations=3)
Steps the world ahead by a given time amount.
ContactCounter GetTouchingCount (const World &world) noexcept
Gets the touching count for the given world.
size_t GetFixtureCount (const World &world) noexcept
Gets the count of fixtures in the given world.
size_t GetShapeCount (const World &world) noexcept
Gets the count of unique shapes in the given world.
BodyCounter GetAwakeCount (const World &world) noexcept
Gets the count of awake bodies in the given world.
BodyCounter Awaken (World &world) noexcept
Awakens all of the bodies in the given world.
void SetAccelerations (World &world, std::function< Acceleration(const Body &b)> fn) noexcept
Sets the accelerations of all the world's bodies.
void SetAccelerations (World &world, Acceleration acceleration) noexcept
Sets the accelerations of all the world's bodies to the given value.
Body * CreateRectangularEnclosingBody (World &world, Length2 dimensions, const ShapeDef &baseConf)
Creates a rectanglular enclosure.
Body * FindClosestBody (const World &world, Length2 location) noexcept
Finds body in given world that's closest to the given location.
BodyCounter GetBodyCount (const World &world) noexcept
Gets the body count in the given world.
JointCounter GetJointCount (const World &world) noexcept
Gets the count of joints in the given world.
ContactCounter GetContactCount (const World &world) noexcept
Gets the count of contacts in the given world.
void ClearForces (World &world) noexcept
Clears forces.
Body * CreateSquareEnclosingBody (World &world, Length size, const ShapeDef &baseConf)
Creates a square enclosure.
Momentum GetMaxNormalImpulse (const ContactImpulsesList &impulses) noexcept
Gets the maximum normal impulse from the given contact impulses list.
PLAYRHO_CONSTEXPR WorldDef GetDefaultWorldDef () noexcept
Gets the default definitions value.
Variables
PLAYRHO_CONSTEXPR const auto InvalidIndexPair
Invalid index pair value.
static PLAYRHO_CONSTEXPR const std::size_t s_blockSizes [BlockAllocator::BlockSizes]
Array of block sizes.
static PLAYRHO_CONSTEXPR const std::uint8_t s_blockSizeLookup [BlockAllocator::MaxBlockSize+1]
Block size lookup array.
PLAYRHO_CONSTEXPR const auto Pi = Real(3.14159265358979323846264338327950288)
Pi.
PLAYRHO_CONSTEXPR const auto SquareRootTwo
Square root of two.
PLAYRHO_CONSTEXPR const auto Centi = Real(1e-2)
Centi (1 x 10^-2).
PLAYRHO_CONSTEXPR const auto Deci = Real(1e-1)
Deci (1 x 10^-1).
PLAYRHO_CONSTEXPR const auto Kilo = Real(1e3)
Kilo (1 x 10^3).
PLAYRHO_CONSTEXPR const auto Giga = Real(1e9)
Giga (1 x 10^9).
PLAYRHO_CONSTEXPR const auto Yotta = Real(1e24)
Yotta (1 x 10^24).
PLAYRHO_CONSTEXPR const auto MaxSimplexEdges = std::uint8_t{3}
Maximum number of supportable edges in a simplex.
PLAYRHO_CONSTEXPR const auto MaxChildCount = std::numeric_limits<std::uint32_t>::max() >> 6
Max child count.
PLAYRHO_CONSTEXPR const auto MaxFloat = std::numeric_limits<Real>::max()
Maximum float value.
PLAYRHO_CONSTEXPR const auto MaxManifoldPoints = std::uint8_t{2}
Maximum manifold points. This is the maximum number of contact points between two convex shapes. Do not change this value.
PLAYRHO_CONSTEXPR const auto MaxShapeVertices = std::uint8_t{254}
Maximum number of vertices for any shape type.
PLAYRHO_CONSTEXPR const auto InvalidVertex = static_cast<VertexCounter>(-1)
Invalid vertex index.
PLAYRHO_CONSTEXPR const auto DefaultLinearSlop = details::Defaults<Real>::GetLinearSlop()
Default linear slop.
PLAYRHO_CONSTEXPR const auto DefaultMinVertexRadius = DefaultLinearSlop * Real{2}
Default minimum vertex radius.
PLAYRHO_CONSTEXPR const auto DefaultMaxVertexRadius = details::Defaults<Real>::GetMaxVertexRadius()
Default maximum vertex radius.
PLAYRHO_CONSTEXPR const auto DefaultAabbExtension = DefaultLinearSlop * Real{20}
Default AABB extension amount.
PLAYRHO_CONSTEXPR const auto DefaultDistanceMultiplier = Real{2}
Default distance multiplier.
PLAYRHO_CONSTEXPR const auto DefaultAngularSlop = (Pi * 2_rad) / Real{180}
Default angular slop.
PLAYRHO_CONSTEXPR const auto DefaultMaxLinearCorrection = 0.2_m
Default maximum linear correction.
PLAYRHO_CONSTEXPR const auto DefaultMaxAngularCorrection = Real(8.0f / 180.0f) * Pi * 1_rad
Default maximum angular correction.
PLAYRHO_CONSTEXPR const auto DefaultMaxTranslation = 2_m
Default maximum translation amount.
PLAYRHO_CONSTEXPR const auto DefaultMaxRotation = Angle{Pi * 1_rad / Real(2)}
Default maximum rotation per world step.
PLAYRHO_CONSTEXPR const auto DefaultMaxToiIters = std::uint8_t{20}
Default maximum time of impact iterations.
PLAYRHO_CONSTEXPR const auto DefaultMaxToiRootIters = std::uint8_t{30}
Default maximum time of impact root iterator count.
PLAYRHO_CONSTEXPR const auto DefaultMaxDistanceIters = std::uint8_t{20}
Default max number of distance iterations.
PLAYRHO_CONSTEXPR const auto DefaultMaxSubSteps = std::uint8_t{8}
Default maximum number of sub steps.
PLAYRHO_CONSTEXPR const auto DefaultVelocityThreshold = 1_mps
Default velocity threshold.
PLAYRHO_CONSTEXPR const auto DefaultRegMinMomentum = Momentum{0_Ns / 100}
Default regular-phase minimum momentum.
PLAYRHO_CONSTEXPR const auto DefaultToiMinMomentum = Momentum{0_Ns / 100}
Default TOI-phase minimum momentum.
PLAYRHO_CONSTEXPR const auto MaxBodies
Maximum number of bodies in a world.
PLAYRHO_CONSTEXPR const auto InvalidContactIndex = static_cast<ContactCounter>(-1)
Invalid contact index.
PLAYRHO_CONSTEXPR const auto MaxContacts = ContactCounter{MaxBodies} * ContactCounter{MaxBodies - 1} / ContactCounter{2}
Maximum number of contacts in a world (2147319811).
PLAYRHO_CONSTEXPR const auto MaxJoints
Maximum number of joints in a world.
PLAYRHO_CONSTEXPR const auto DefaultStepTime = Time{1_s / 60}
Default step time.
PLAYRHO_CONSTEXPR const auto DefaultStepFrequency = 60_Hz
Default step frequency.
PLAYRHO_CONSTEXPR const auto DefaultMinStillTimeToSleep = Time{1_s / 2}
Default minimum still time to sleep.
PLAYRHO_CONSTEXPR const auto DefaultLinearSleepTolerance = 0.01_mps
Default linear sleep tolerance.
PLAYRHO_CONSTEXPR const auto DefaultAngularSleepTolerance = Real{(Pi * 2) / 180} * RadianPerSecond
Default angular sleep tolerance.
PLAYRHO_CONSTEXPR const auto DefaultCirclesRatio = Real{10}
Default circles ratio.
PLAYRHO_CONSTEXPR const auto Transform_identity = Transformation{Length2{0_m, 0_m}, UnitVec2::GetRight()}
Identity transformation value.
PLAYRHO_CONSTEXPR const auto Second = PLAYRHO_UNIT(Time, boost::units::si::second)
Second unit of Time.
PLAYRHO_CONSTEXPR const auto SquareSecond = Second * Second
Square second unit.
PLAYRHO_CONSTEXPR const auto Hertz = PLAYRHO_UNIT(Frequency, boost::units::si::hertz)
Hertz unit of Frequency.
PLAYRHO_CONSTEXPR const auto Meter = PLAYRHO_UNIT(Length, boost::units::si::meter)
Meter unit of Length.
PLAYRHO_CONSTEXPR const auto MeterPerSecond
Meter per second unit of LinearVelocity.
PLAYRHO_CONSTEXPR const auto MeterPerSquareSecond
Meter per square second unit of LinearAcceleration.
PLAYRHO_CONSTEXPR const auto Kilogram = PLAYRHO_UNIT(Mass, boost::units::si::kilogram)
Kilogram unit of Mass.
PLAYRHO_CONSTEXPR const auto SquareMeter = PLAYRHO_UNIT(Area, boost::units::si::square_meter)
Square meter unit of Area.
PLAYRHO_CONSTEXPR const auto CubicMeter = Meter * Meter * Meter
Cubic meter unit of Volume.
PLAYRHO_CONSTEXPR const auto KilogramPerSquareMeter
Kilogram per square meter unit of AreaDensity.
PLAYRHO_CONSTEXPR const auto Radian = PLAYRHO_UNIT(Angle, boost::units::si::radian)
Radian unit of Angle.
PLAYRHO_CONSTEXPR const auto Degree = Angle{Radian * Pi / Real{180}}
Degree unit of Angle quantity.
PLAYRHO_CONSTEXPR const auto SquareRadian = Radian * Radian
Square radian unit type.
PLAYRHO_CONSTEXPR const auto RadianPerSecond
Radian per second unit of AngularVelocity.
PLAYRHO_CONSTEXPR const auto DegreePerSecond = AngularVelocity{RadianPerSecond * Degree / Radian}
Degree per second unit of AngularVelocity.
PLAYRHO_CONSTEXPR const auto RadianPerSquareSecond = Radian / (Second * Second)
Radian per square second unit of AngularAcceleration.
PLAYRHO_CONSTEXPR const auto DegreePerSquareSecond = Degree / (Second * Second)
Degree per square second unit of AngularAcceleration.
PLAYRHO_CONSTEXPR const auto Newton = PLAYRHO_UNIT(Force, boost::units::si::newton)
Newton unit of Force.
PLAYRHO_CONSTEXPR const auto NewtonMeter = PLAYRHO_UNIT(Torque, boost::units::si::newton_meter)
Newton meter unit of Torque.
PLAYRHO_CONSTEXPR const auto NewtonSecond = Newton * Second
Newton second unit of Momentum.
PLAYRHO_CONSTEXPR const auto NewtonMeterSecond = NewtonMeter * Second
Newton meter second unit of AngularMomentum.
PLAYRHO_CONSTEXPR const auto RevolutionsPerMinute = 2 * Pi * Radian / (Real{60} * Second)
Revolutions per minute units of AngularVelocity.
PLAYRHO_CONSTEXPR const auto EarthlyLinearAcceleration = Real{-9.8f} * MeterPerSquareSecond
Earthly gravity.
PLAYRHO_CONSTEXPR const auto BigG = Real{6.67408e-11f} * CubicMeter / (Kilogram * SquareSecond)
Big "G".
PLAYRHO_CONSTEXPR const auto EarthlyGravity2D = LinearAcceleration2{0_mps2, EarthlyLinearAcceleration}
Earthly gravity in 2-dimensions.
Detailed Description
Namespace for all PlayRho related names.
Typedef Documentation
AABB2D
using playrho::AABB2D = typedef AABB<2>
2-Dimensional Axis Aligned Bounding Box.
Note
This data structure is 16-bytes large (on at least one 64-bit platform).
BodyCounter
using playrho::BodyCounter = typedef std::remove_const<decltype(MaxBodies)>::type
Body count type.
Note
This type must always be able to contain the MaxBodies value.
ChildCounter
using playrho::ChildCounter = typedef std::remove_const<decltype(MaxChildCount)>::type
Child counter type.
Relating to "children" of shape where each child is a convex shape possibly comprising a concave shape.
Note
This type must always be able to contain the MaxChildCount value.
ClipList
using playrho::ClipList = typedef ArrayList<ClipVertex, MaxManifoldPoints>
Clip list for ClipSegmentToLine.
See also
ClipSegmentToLine.
Note
This data structure is at least 24-bytes large.
ContactCounter
using playrho::ContactCounter = typedef Wider<BodyCounter>::type
Contact count type.
Note
This type must be able to contain the squared value of BodyCounter.
Fixed32
using playrho::Fixed32 = typedef Fixed<std::int32_t,9>
32-bit fixed precision type.
Note
The available numeric fidelity of any 32-bit fixed point type is very limited. Using a 32-bit fixed point type for Real should only be considered for simulations where it's been found to work and where the dynamics won't be changing between runs.
Force2
using playrho::Force2 = typedef Vector2<Force>
2-element vector of Force quantities.
Note
Often used as a 2-dimensional force vector.
IndexPair
using playrho::IndexPair = typedef std::pair<VertexCounter, VertexCounter>
Index pair.
Note
This data structure is at least 2-bytes large.
IndexPair3
using playrho::IndexPair3 = typedef std::array<IndexPair, MaxSimplexEdges>
Index pairs.
Note
This data type is 6-bytes large (on at least one 64-bit platform).
JointCounter
using playrho::JointCounter = typedef std::remove_const<decltype(MaxJoints)>::type
Joint count type.
Note
This type must be able to contain the MaxJoints value.
Length2
using playrho::Length2 = typedef Vector2<Length>
2-element vector of Length quanties.
Note
Often used as a 2-dimensional distance or location vector.
LinearAcceleration2
using playrho::LinearAcceleration2 = typedef Vector2<LinearAcceleration>
2-element vector of LinearAcceleration quantities.
Note
Often used as a 2-dimensional linear acceleration vector.
LinearVelocity2
using playrho::LinearVelocity2 = typedef Vector2<LinearVelocity>
2-element vector of LinearVelocity quantities.
Note
Often used as a 2-dimensional speed vector.
Momentum2
using playrho::Momentum2 = typedef Vector2<Momentum>
2-element vector of Momentum quantities.
Note
Often used as a 2-dimensional momentum vector.
Optional
template<typename T > using playrho::Optional = typedef OptionalValue<T>
Optional type alias.
An alias setup to facilitate switching between implementations of the optional type idea.
Note
This is meant to be used directly for optional values.
RayCastOutput
using playrho::RayCastOutput = typedef Optional<RayCastHit>
Ray cast output.
This is a type alias for an optional RayCastHit instance.
See also
RayCast, Optional, RayCastHit
Real
using playrho::Real = typedef float
Real-number type.
This is the number type underlying numerical calculations conceptually involving real-numbers. Ideally the implementation of this type doesn't suffer from things like: catastrophic cancellation, catastrophic division, overflows, nor underflows.
Note
This can be implemented using any of the fundamental floating point types (float, double, or long double).
This can also be implemented using a "LiteralType" that has the necessary support: all common mathematical functions, support for infinity and NaN, and a specialization of the std::numeric_limits class template for it.
At present, the Fixed32 and Fixed64 aliases of the Fixed template type are provided as examples of qualifying literal types though the usability of Fixed32 is limited and its use is discouraged.
Regarding division:
While dividing 1 by a real, caching the result, and then doing multiplications with the result may well be faster (than repeatedly dividing), dividing 1 by the real can also result in an underflow situation that's then compounded every time it's multiplied with other values.
Meanwhile, dividing every time by a real isolates any underflows to the particular division where underflow occurs.
Warning
Using Fixed32 is not advised as its numerical limitations are more likely to result in problems like overflows or underflows.
The note regarding division applies even more so when using a fixed-point type (for Real).
See also
http://en.cppreference.com/w/cpp/language/types
http://en.cppreference.com/w/cpp/types/is_floating_point
http://en.cppreference.com/w/cpp/concept/LiteralType
SimplexEdges
using playrho::SimplexEdges = typedef ArrayList<SimplexEdge, MaxSimplexEdges, std::remove_const<decltype(MaxSimplexEdges)>::type>
Simplex edge collection.
Note
This data is 28 * 3 + 4 = 88-bytes large (on at least one 64-bit platform).
TimestepIters
using playrho::TimestepIters = typedef std::uint8_t
Time step iterations type.
A type for counting iterations per time-step.
TupleContainsType
template<typename T , typename Tuple > using playrho::TupleContainsType = typedef typename HasType<T, Tuple>::type
Tuple contains type alias.
Alias in case the trait itself should be std::true_type or std::false_type.
Note
This is from Piotr Skotnicki's answer on StackOverflow to the question of "How do I find out if a tuple contains a type?".
See also
https://stackoverflow.com/a/25958302/7410358
Vec2
using playrho::Vec2 = typedef Vector2<Real>
Vector with 2 Real elements.
Note
This data structure is two-times the size of the Real type (or 8 using Real of float).
Vec3
using playrho::Vec3 = typedef Vector3<Real>
A 3D column vector with 3 elements.
Note
This data structure is 3 times the size of Real - i.e. 12-bytes (with 4-byte Real).
Vector2
template<typename T > using playrho::Vector2 = typedef Vector<T, 2>
Vector with 2-elements.
Note
This is just a C++11 alias template for 2-element uses of the Vector template.
Vector3
template<typename T > using playrho::Vector3 = typedef Vector<T, 3>
Vector with 3-elements.
Note
This is just a C++11 alias template for 3-element uses of the Vector template.
VertexCounter
using playrho::VertexCounter = typedef std::remove_const<decltype(MaxShapeVertices)>::type
Vertex count type.
Note
This type must not support more than 255 vertices as that would conflict with the ContactFeature::Index type.
Enumeration Type Documentation
BodyType
enum playrho::BodyType strong
Body Type.
Note
static: zero mass, zero velocity, may be manually moved
kinematic: zero mass, non-zero velocity set by user, moved by solver
dynamic: positive mass, non-zero velocity determined by forces, moved by solver
Enumerator
Static
Static body type.
Static bodies have no mass, have no forces applied to them, and aren't moved by physical processeses. They are impenetrable.
Note
Physics applied: none.
Kinematic
Kinematic body type.
Kinematic bodies have no mass and have no forces applied to them, but can move at set velocities. They are impenetrable.
Note
Physics applied: velocity.
Dynamic
Dynamic body type.
Dynamic bodies are fully simulated bodies. Dynamic bodies always have a positive non-zero mass. They may be penetrable.
Note
Physics applied: velocity, acceleration.
PointState
enum playrho::PointState strong
Point state enumeration.
Note
This is used for determining the state of contact points.
Enumerator
NullState
point does not exist
AddState
point was added in the update
PersistState
point persisted across the update
RemoveState
point was removed in the update
Function Documentation
Alloc()
T * playrho::Alloc (std::size_t size)
Allocates memory.
Note
Implement this function to use your own memory allocator.
Referenced by playrho::BlockAllocator::Allocate(), playrho::StackAllocator::Allocate(), and playrho::StackAllocator::StackAllocator().
AlmostZero()
template<typename BT , unsigned int FB> PLAYRHO_CONSTEXPR bool playrho::AlmostZero (Fixed< BT, FB > value) inline
Gets whether a given value is almost zero.
An almost zero value is "subnormal". Dividing by these values can lead to odd results like a divide by zero trap occurring.
Returns
true if the given value is almost zero, false otherwise.
Referenced by AlmostEqual(), ClipSegmentToLine(), ComputeCentroid(), Distance(), GetMassData(), GetToiViaSat(), playrho::MouseJoint::InitVelocityConstraints(), Invert(), Normalize(), playrho::PulleyJoint::PulleyJoint(), RayCast(), and Solve().
ApplyAngularImpulse()
void ApplyAngularImpulse (Body & body, AngularMomentum impulse) inline noexcept
Applies an angular impulse.
Parameters
body Body to apply the angular impulse to.
impulse Angular impulse to be applied.
ApplyForce()
void ApplyForce (Body & body, Force2 force, Length2 point) inline noexcept
Apply a force at a world point.
Note
If the force is not applied at the center of mass, it will generate a torque and affect the angular velocity.
Non-zero forces wakes up the body.
Parameters
body Body to apply the force to.
force World force vector.
point World position of the point of application.
ApplyForceToCenter()
void ApplyForceToCenter (Body & body, Force2 force) inline noexcept
Apply a force to the center of mass.
Note
Non-zero forces wakes up the body.
Parameters
body Body to apply the force to.
force World force vector.
ApplyLinearAcceleration()
void ApplyLinearAcceleration (Body & body, LinearAcceleration2 amount) inline
Applies the given linear acceleration to the given body.
Referenced by playrho::World::SetGravity().
ApplyLinearImpulse()
void ApplyLinearImpulse (Body & body, Momentum2 impulse, Length2 point) inline noexcept
Applies an impulse at a point.
Note
This immediately modifies the velocity.
This also modifies the angular velocity if the point of application is not at the center of mass.
Non-zero impulses wakes up the body.
Parameters
body Body to apply the impulse to.
impulse the world impulse vector.
point the world position of the point of application.
ApplyTorque()
void ApplyTorque (Body & body, Torque torque) inline noexcept
Applies a torque.
Note
This affects the angular velocity without affecting the linear velocity of the center of mass.
Non-zero forces wakes up the body.
Parameters
body Body to apply the torque to.
torque about the z-axis (out of the screen).
Awaken() [1/2]
bool Awaken (Body & body) inline noexcept
Awakens the body if it's asleep.
Referenced by Awaken().
Awaken() [2/2]
BodyCounter Awaken (World & world) noexcept
Awakens all of the bodies in the given world.
Calls all of the world's bodies' SetAwake method.
Returns
Sum total of calls to bodies' SetAwake method that returned true.
See also
Body::SetAwake.
CalcGravitationalAcceleration()
Acceleration CalcGravitationalAcceleration (const Body & body) noexcept
Calculates the gravitationally associated acceleration for the given body within its world.
Returns
Zero acceleration if given body is has no mass, else the acceleration of the body due to the gravitational attraction to the other bodies.
CalcToi()
TOIOutput CalcToi (const Contact & contact, ToiConf conf)
Calculates the Time Of Impact for the given contact with the given configuration.
Referenced by playrho::World::UpdateContactTOIs().
ClearForces()
void ClearForces (World & world) inline noexcept
Clears forces.
Manually clear the force buffer on all bodies.
ClipSegmentToLine()
ClipList playrho::ClipSegmentToLine (const ClipList & vIn, const UnitVec2 & normal, Length offset, ContactFeature::Index indexA)
Clipping for contact manifolds.
This returns an array of points from the given line that are inside of the plane as defined by a given normal and offset.
Parameters
vIn Clip list of two points defining the line.
normal Normal of the plane with which to determine intersection.
offset Offset of the plane with which to determine intersection.
indexA Index of vertex A.
Returns
List of zero one or two clip points.
CollideShapes()
Manifold CollideShapes (const DistanceProxy & shapeA, const Transformation & xfA, const DistanceProxy & shapeB, const Transformation & xfB, Manifold::Conf conf = GetDefaultManifoldConf())
Calculates the relevant collision manifold.
Note
The returned touching state information typically agrees with that returned from the DistanceProxy-based TestOverlap function. This is not always the case however especially when the separation or overlap distance is closer to zero.
Referenced by playrho::Contact::Update().
ComputeAABB() [1/5]
AABB2D ComputeAABB (const DistanceProxy & proxy, const Transformation & xf) noexcept
Computes the AABB.
Computes the Axis Aligned Bounding Box (AABB) for the given child shape at a given a transform.
Warning
Behavior is undefined if the given transformation is invalid.
Parameters
proxy Distance proxy for the child shape.
xf World transform of the shape.
Returns
AABB for the proxy shape or the default AABB if the proxy has a zero vertex count.
Referenced by ComputeAABB(), ComputeIntersectingAABB(), playrho::World::CreateProxies(), and playrho::World::Synchronize().
ComputeAABB() [2/5]
AABB2D ComputeAABB (const DistanceProxy & proxy, const Transformation & xfm0, const Transformation & xfm1) noexcept
Computes the AABB.
Computes the Axis Aligned Bounding Box (AABB) for the given child shape at the given transforms.
Warning
Behavior is undefined if a given transformation is invalid.
Parameters
proxy Distance proxy for the child shape.
xfm0 World transform 0 of the shape.
xfm1 World transform 1 of the shape.
Returns
AABB for the proxy shape or the default AABB if the proxy has a zero vertex count.
ComputeAABB() [3/5]
AABB2D ComputeAABB (const Shape & shape, const Transformation & xf) noexcept
Computes the AABB for the given shape with the given transformation.
ComputeAABB() [4/5]
AABB2D ComputeAABB (const Fixture & fixture) noexcept
Computes the AABB for the given fixture.
This is the AABB of the entire shape of the given fixture at the body's location for the given fixture.
ComputeAABB() [5/5]
AABB2D ComputeAABB (const Body & body)
Computes the AABB for the given body.
ComputeIntersectingAABB()
AABB2D playrho::ComputeIntersectingAABB (const Fixture & fA, ChildCounter iA, const Fixture & fB, ChildCounter iB) noexcept
Computes the intersecting AABB for the given pair of fixtures and indexes.
The intersecting AABB for the given pair of fixtures is the intersection of the AABB for child A of the shape of fixture A with the AABB for child B of the shape of fixture B.
Referenced by ComputeIntersectingAABB().
ComputeMassData()
MassData ComputeMassData (const Body & body) noexcept
Computes the body's mass data.
This basically accumulates the mass data over all fixtures.
Note
The center is the mass weighted sum of all fixture centers. Divide it by the mass to get the averaged center.
Returns
accumalated mass data for all fixtures associated with the given body.
ComputePerimeterRatio()
Real playrho::ComputePerimeterRatio (const DynamicTree & tree) inline noexcept
Gets the ratio of the sum of the perimeters of nodes to the root perimeter.
Note
Zero is returned if no proxies exist at the time of the call.
Returns
Value of zero or more.
Contains()
template<std::size_t N> PLAYRHO_CONSTEXPR bool Contains (const AABB< N > & a, const AABB< N > & b) inline noexcept
Checks whether the first AABB fully contains the second AABB.
Whether the first AABB contains the entirety of the second AABB where containment is defined as being equal-to or within an AABB.
Note
The "unset" AABB is contained by all valid AABBs including the "unset" AABB itself.
Parameters
a AABB to test whether it constains the second AABB.
b AABB to test whether it's contained by the first AABB.
Referenced by playrho::World::Synchronize().
Count() [1/3]
std::size_t Count (const Island & island, const Body * entry)
Counts the number of occurrances of the given entry in the given island.
Referenced by playrho::World::ProcessContactsForTOI().
Count() [2/3]
std::size_t Count (const Island & island, const Contact * entry)
Counts the number of occurrances of the given entry in the given island.
Count() [3/3]
std::size_t Count (const Island & island, const Joint * entry)
Counts the number of occurrances of the given entry in the given island.
CreateRectangularEnclosingBody()
Body * CreateRectangularEnclosingBody (World & world, Length2 dimensions, const ShapeDef & baseConf)
Creates a rectanglular enclosure.
CreateSquareEnclosingBody()
Body * CreateSquareEnclosingBody (World & world, Length size, const ShapeDef & baseConf) inline
Creates a square enclosure.
Distance()
DistanceOutput playrho::Distance (const DistanceProxy & proxyA, const Transformation & transformA, const DistanceProxy & proxyB, const Transformation & transformB, DistanceConf conf = DistanceConf{})
Determines the closest points between two shapes.
Note
Supports any combination of shapes.
On the first call, the Simplex::Cache.count should be set to zero.
Parameters
proxyA Proxy A.
transformA Transoform of A.
proxyB Proxy B.
transformB Transoform of B.
conf Configuration to use including the simplex cache for assisting the determination.
Returns
Closest points between the two shapes and the count of iterations it took to determine them. The iteration count will always be greater than zero unless DefaultMaxDistanceIters is zero.
Referenced by GetToiViaSat(), and TestOverlap().
Dump()
void playrho::Dump (const World & world)
Dump the world into the log file.
Warning
this should be called outside of a time step.
Referenced by Dump().
Fatten()
template<std::size_t N> PLAYRHO_CONSTEXPR AABB< N > & Fatten (AABB< N > & var, const NonNegative< Length > amount) inline noexcept
Fattens an AABB by the given amount.
Referenced by GetFattenedAABB().
FindClosestBody()
Body * FindClosestBody (const World & world, Length2 location) noexcept
Finds body in given world that's closest to the given location.
Flip()
PLAYRHO_CONSTEXPR ContactFeature Flip (ContactFeature val) inline noexcept
Flips contact features information.
Free()
void playrho::Free (void * mem)
Frees memory.
Note
If you implement Alloc, you should also implement this function.
Referenced by playrho::BlockAllocator::Clear(), playrho::StackAllocator::Free(), playrho::BlockAllocator::Free(), playrho::DynamicTree::operator=(), playrho::GrowableStack< T, N >::push(), playrho::DynamicTree::RebuildBottomUp(), and playrho::DynamicTree::~DynamicTree().
Get()
template<size_t I, size_t N, typename T > PLAYRHO_CONSTEXPR auto & Get (Vector< T, N > & v) inline noexcept
Gets the I'th element of the given collection.
GetAABB() [1/2]
PLAYRHO_CONSTEXPR AABB2D GetAABB (const DynamicTree::TreeNode & node) inline noexcept
Gets the AABB of the given DynamicTree node.
Referenced by playrho::DynamicTree::FindLowestCostNode(), playrho::DynamicTree::SetChildren(), and playrho::DynamicTree::ValidateMetrics().
GetAABB() [2/2]
AABB2D GetAABB (const DynamicTree & tree) inline noexcept
Gets the AABB for the given DynamicTree.
Gets the AABB that encloses all other AABB instances that are within the given DynamicTree.
Returns
Enclosing AABB or the "unset" AABB.
GetAcceleration()
Acceleration GetAcceleration (const Body & body) inline noexcept
Gets the given body's acceleration.
Parameters
body Body whose acceleration should be returned.
GetAngle()
Angle GetAngle (const Body & body) inline noexcept
Gets the body's angle.
Returns
Body's angle relative to its World.
GetAngularVelocity() [1/3]
AngularVelocity GetAngularVelocity (const WheelJoint & joint) noexcept
Get the current joint translation speed.
GetAngularVelocity() [2/3]
AngularVelocity GetAngularVelocity (const RevoluteJoint & joint)
Gets the current joint angle speed.
GetAngularVelocity() [3/3]
AngularVelocity GetAngularVelocity (const Body & body) inline noexcept
Gets the angular velocity.
Parameters
body Body to get the angular velocity for.
Returns
the angular velocity.
Referenced by GetBodyDef(), and SetLinearVelocity().
GetAwakeCount()
BodyCounter GetAwakeCount (const World & world) noexcept
Gets the count of awake bodies in the given world.
GetBodyA()
Body * GetBodyA (const Contact & contact) noexcept
Gets the body A associated with the given contact.
Referenced by playrho::PrismaticJoint::EnableLimit(), playrho::PrismaticJoint::EnableMotor(), playrho::VelocityConstraint::GetPoint(), playrho::PrismaticJoint::SetLimits(), playrho::PrismaticJoint::SetMaxMotorForce(), playrho::PrismaticJoint::SetMotorSpeed(), and playrho::World::UpdateContacts().
GetBodyB()
Body * GetBodyB (const Contact & contact) noexcept
Gets the body B associated with the given contact.
Referenced by playrho::PrismaticJoint::EnableLimit(), playrho::PrismaticJoint::EnableMotor(), playrho::VelocityConstraint::GetPoint(), playrho::PrismaticJoint::SetLimits(), playrho::PrismaticJoint::SetMaxMotorForce(), playrho::PrismaticJoint::SetMotorSpeed(), playrho::MouseJoint::SetTarget(), and playrho::World::UpdateContacts().
GetBodyCount()
BodyCounter GetBodyCount (const World & world) inline noexcept
Gets the body count in the given world.
Returns
0 or higher.
GetBodyDef()
BodyDef GetBodyDef (const Body & body) noexcept
Gets the body definition for the given body.
Parameters
body Body to get the BodyDef for.
Referenced by playrho::World::CopyBodies().
GetCenter() [1/2]
template<std::size_t N> PLAYRHO_CONSTEXPR Vector< Length, N > GetCenter (const AABB< N > & aabb) inline noexcept
Gets the center of the AABB.
Referenced by RayCast().
GetCenter() [2/2]
template<typename T > PLAYRHO_CONSTEXPR T GetCenter (const Interval< T > & v) inline noexcept
Gets the center of the given interval.
Warning
Behavior is undefined if the difference between the given range's max and min values overflows the range of the Interval::value_type.
GetCentripetalForce()
Force2 GetCentripetalForce (const Body & body, Length2 axis)
Gets the centripetal force necessary to put the body into an orbit having the given radius.
GetChildCount() [1/2]
PLAYRHO_CONSTEXPR ChildCounter playrho::GetChildCount (const EdgeShapeConf &) inline noexcept
Gets the "child" count for the given shape configuration.
Returns
1.
GetChildCount() [2/2]
PLAYRHO_CONSTEXPR ChildCounter playrho::GetChildCount (const PolygonShapeConf &) inline noexcept
Gets the "child" count for the given shape configuration.
Returns
1.
GetContactCount()
ContactCounter GetContactCount (const World & world) inline noexcept
Gets the count of contacts in the given world.
Note
Not all contacts are for shapes that are actually touching. Some contacts are for shapes which merely have overlapping AABBs.
Returns
0 or higher.
GetCurrentLengthA()
Length GetCurrentLengthA (const PulleyJoint & joint)
Get the current length of the segment attached to bodyA.
GetCurrentLengthB()
Length GetCurrentLengthB (const PulleyJoint & joint)
Get the current length of the segment attached to bodyB.
GetDefaultBodyDef()
PLAYRHO_CONSTEXPR BodyDef GetDefaultBodyDef () inline noexcept
Gets the default body definition.
GetDefaultFixtureDef()
PLAYRHO_CONSTEXPR FixtureDef GetDefaultFixtureDef () inline noexcept
Gets the default fixture definition.
GetDefaultManifoldConf()
PLAYRHO_CONSTEXPR Manifold::Conf GetDefaultManifoldConf () inline noexcept
Gets the default manifold configuration.
GetDefaultToiConf()
PLAYRHO_CONSTEXPR auto GetDefaultToiConf () inline
Gets the default time of impact configuration.
GetDefaultWorldDef()
PLAYRHO_CONSTEXPR WorldDef GetDefaultWorldDef () inline noexcept
Gets the default definitions value.
Note
This method exists as a work-around for providing the World constructor a default value without otherwise getting a compiler error such as: "cannot use defaulted constructor of 'Def' within 'World' outside of member functions because 'gravity' has an initializer"
GetDensity()
NonNegative<AreaDensity> playrho::GetDensity (const Shape & shape) noexcept
Gets the density of the given shape.
Gets the density of this fixture.
Returns
Non-negative density (in mass per area).
Referenced by playrho::Fixture::GetDensity().
GetDimensions()
template<std::size_t N> PLAYRHO_CONSTEXPR Vector< Length, N > GetDimensions (const AABB< N > & aabb) inline noexcept
Gets dimensions of the given AABB.
Referenced by GetExtents().
GetDisplacedAABB()
template<std::size_t N> PLAYRHO_CONSTEXPR AABB< N > GetDisplacedAABB (AABB< N > aabb, const Vector< Length, N > displacement) inline
Gets the AABB that the result of displacing the given AABB by the given displacement amount.
Referenced by playrho::World::Synchronize().
GetDistanceJointDef()
DistanceJointDef GetDistanceJointDef (const DistanceJoint & joint) noexcept
Gets the definition data for the given joint.
Referenced by playrho::World::CopyJoints().
GetEdge()
Length2 GetEdge (const PolygonShapeConf & shape, VertexCounter index)
Gets the identified edge of the given polygon shape.
Note
This must not be called for shapes with less than 2 vertices.
Warning
Behavior is undefined if called for a shape with less than 2 vertices.
GetEnclosingAABB()
template<std::size_t N> PLAYRHO_CONSTEXPR AABB< N > GetEnclosingAABB (AABB< N > a, const AABB< N > & b) inline
Gets the AABB that minimally encloses the given AABBs.
Referenced by playrho::DynamicTree::FindLowestCostNode(), playrho::DynamicTree::InsertLeaf(), playrho::DynamicTree::Rebalance(), playrho::DynamicTree::RebuildBottomUp(), playrho::DynamicTree::SetChildren(), and playrho::DynamicTree::ValidateMetrics().
GetExtents()
template<std::size_t N> PLAYRHO_CONSTEXPR Vector< Length, N > GetExtents (const AABB< N > & aabb) inline noexcept
Gets the extents of the AABB (half-widths).
Referenced by RayCast().
GetFaceFaceContactFeature()
PLAYRHO_CONSTEXPR ContactFeature GetFaceFaceContactFeature (ContactFeature::Index a, ContactFeature::Index b) inline noexcept
Gets the face face contact feature for the given indices.
GetFaceVertexContactFeature()
PLAYRHO_CONSTEXPR ContactFeature GetFaceVertexContactFeature (ContactFeature::Index a, ContactFeature::Index b) inline noexcept
Gets the face vertex contact feature for the given indices.
GetFattenedAABB()
template<std::size_t N> PLAYRHO_CONSTEXPR AABB< N > GetFattenedAABB (AABB< N > aabb, const Length amount) inline
Gets the fattened AABB result.
Referenced by ComputeAABB(), playrho::World::CreateProxies(), and playrho::World::Synchronize().
GetFixtureA()
Fixture * GetFixtureA (const Contact & contact) inline noexcept
Gets the fixture A associated with the given contact.
GetFixtureB()
Fixture * GetFixtureB (const Contact & contact) inline noexcept
Gets the fixture B associated with the given contact.
GetFixtureCount() [1/2]
std::size_t GetFixtureCount (const Body & body) noexcept
Gets the fixture count of the given body.
Referenced by GetFixtureCount().
GetFixtureCount() [2/2]
std::size_t GetFixtureCount (const World & world) noexcept
Gets the count of fixtures in the given world.
GetFixtureDef()
FixtureDef GetFixtureDef (const Fixture & fixture) noexcept
Gets the fixture definition for the given fixture.
Parameters
fixture Fixture to get the definition for.
Referenced by playrho::World::CopyBodies().
GetForce()
Force2 GetForce (const Body & body) inline noexcept
Gets the net force that the given body is currently experiencing.
GetFriction()
Real playrho::GetFriction (const Shape & shape) noexcept
Gets the friction of the given shape.
Gets the coefficient of friction.
Returns
Value of 0 or higher.
Referenced by playrho::Fixture::GetFriction().
GetFrictionJointDef()
FrictionJointDef GetFrictionJointDef (const FrictionJoint & joint) noexcept
Gets the definition data for the given joint.
Referenced by playrho::World::CopyJoints().
GetFwdPerpendicular()
PLAYRHO_CONSTEXPR UnitVec2 playrho::GetFwdPerpendicular (const UnitVec2 vector) inline noexcept
Gets a vector clockwise (forward-clockwise) perpendicular to the given vector.
This takes a vector of form (x, y) and returns the vector (y, -x).
Parameters
vector Vector to return a clockwise perpendicular equivalent for.
Returns
A clockwise 90-degree rotation of the given vector.
See also
GetRevPerpendicular.
GetGearJointDef()
GearJointDef GetGearJointDef (const GearJoint & joint) noexcept
Gets the definition data for the given joint.
Referenced by playrho::World::CopyJoints().
GetHeight()
DynamicTree::Height GetHeight (const DynamicTree & tree) inline noexcept
Gets the height of the binary tree.
Returns
Height of the tree (as stored in the root node) or 0 if the root node is not valid.
Referenced by playrho::DynamicTree::ComputeHeight(), playrho::DynamicTree::FindLowestCostNode(), playrho::DynamicTree::FreeNode(), playrho::DynamicTree::GetAABB(), playrho::DynamicTree::GetBranchData(), playrho::DynamicTree::GetChild1(), playrho::DynamicTree::GetChild2(), playrho::DynamicTree::GetLeafData(), playrho::DynamicTree::GetParent(), playrho::DynamicTree::SetAABB(), playrho::DynamicTree::SetChild1(), playrho::DynamicTree::SetChild2(), playrho::DynamicTree::SetChildren(), playrho::DynamicTree::SetLeafData(), playrho::DynamicTree::SetParent(), playrho::DynamicTree::Validate(), playrho::DynamicTree::ValidateMetrics(), and playrho::DynamicTree::ValidateStructure().
GetIntersection()
template<typename T > PLAYRHO_CONSTEXPR Interval< T > GetIntersection (Interval< T > a, const Interval< T > & b) inline noexcept
Gets the intersecting interval of two given ranges.
Referenced by GetIntersectingAABB().
GetInvalid()
template<> PLAYRHO_CONSTEXPR AABB2D GetInvalid () inline noexcept
Gets an invalid AABB value.
GetJointAngle()
Angle GetJointAngle (const RevoluteJoint & joint)
Gets the current joint angle.
GetJointCount()
JointCounter GetJointCount (const World & world) inline noexcept
Gets the count of joints in the given world.
Returns
0 or higher.
GetJointTranslation() [1/2]
Length GetJointTranslation (const WheelJoint & joint) noexcept
Get the current joint translation.
GetJointTranslation() [2/2]
Length GetJointTranslation (const PrismaticJoint & joint) noexcept
Get the current joint translation.
GetLinearVelocity() [1/2]
LinearVelocity GetLinearVelocity (const PrismaticJoint & joint) noexcept
Get the current joint translation speed.
GetLinearVelocity() [2/2]
LinearVelocity2 GetLinearVelocity (const Body & body) inline noexcept
Gets the linear velocity of the center of mass.
Parameters
body Body to get the linear velocity for.
Returns
the linear velocity of the center of mass.
Referenced by GetBodyDef(), GetCentripetalForce(), and SetAngularVelocity().
GetLinearVelocityFromLocalPoint()
LinearVelocity2 GetLinearVelocityFromLocalPoint (const Body & body, const Length2 localPoint) inline noexcept
Gets the linear velocity from a local point.
Parameters
body Body to get the linear velocity for.
localPoint point in local coordinates.
Returns
the world velocity of a point.
GetLinearVelocityFromWorldPoint()
LinearVelocity2 GetLinearVelocityFromWorldPoint (const Body & body, const Length2 worldPoint) inline noexcept
Gets the linear velocity from a world point attached to this body.
Parameters
body Body to get the linear velocity for.
worldPoint point in world coordinates.
Returns
the world velocity of a point.
Referenced by GetLinearVelocityFromLocalPoint().
GetLocalPoint()
Length2 GetLocalPoint (const Body & body, const Length2 worldPoint) inline noexcept
Gets a local point relative to the body's origin given a world point.
Parameters
body Body that the returned point should be relative to.
worldPoint point in world coordinates.
Returns
the corresponding local point relative to the body's origin.
GetLocalRotInertia()
RotInertia GetLocalRotInertia (const Body & body) inline noexcept
Gets the rotational inertia of the body about the local origin.
Returns
the rotational inertia.
Referenced by GetMassData().
GetLocalVector()
UnitVec2 GetLocalVector (const Body & body, const UnitVec2 uv) inline noexcept
Gets a locally oriented unit vector given a world oriented unit vector.
Parameters
body Body that the returned vector should be relative to.
uv Unit vector in world orientation.
Returns
the corresponding local vector.
GetLocation()
Length2 GetLocation (const Body & body) inline noexcept
Gets the body's origin location.
This is the location of the body's origin relative to its world. The location of the body after stepping the world's physics simulations is dependent on a number of factors:
Location at the last time step.
Forces acting on the body (gravity, applied force, applied impulse).
The mass data of the body.
Damping of the body.
Restitution and friction values of the body's fixtures when they experience collisions.
Returns
World location of the body's origin.
See also
GetAngle.
Referenced by CalcGravitationalAcceleration(), and SetAngle().
GetLowerBound()
template<std::size_t N> PLAYRHO_CONSTEXPR Vector< Length, N > GetLowerBound (const AABB< N > & aabb) inline noexcept
Gets the lower bound.
Referenced by RayCast().
GetMass()
Mass GetMass (const Body & body) inline noexcept
Gets the total mass of the body.
Returns
Value of zero or more representing the body's mass (in kg).
See also
GetInvMass, SetMassData
Referenced by CalcGravitationalAcceleration(), GetCentripetalForce(), GetForce(), GetLocalRotInertia(), GetMassData(), and playrho::MouseJoint::InitVelocityConstraints().
GetMassData() [1/6]
MassData playrho::GetMassData (const MultiShapeConf & arg) noexcept
Computes the mass properties of this shape using its dimensions and density. The inertia tensor is computed about the local origin.
Gets the mass data for the given shape configuration.
Returns
Mass data for this shape.
GetMassData() [2/6]
MassData GetMassData (Length r, NonNegative< AreaDensity > density, Length2 location)
Computes the mass data for a circular shape.
Parameters
r Radius of the circlular shape.
density Areal density of mass.
location Location of the center of the shape.
Referenced by ComputeMassData(), playrho::World::CopyBodies(), playrho::ChainShapeConf::GetMassData(), and GetMassData().
GetMassData() [3/6]
MassData GetMassData (Length r, NonNegative< AreaDensity > density, Length2 v0, Length2 v1)
Computes the mass data for a linear shape.
Parameters
r Radius of the vertices of the linear shape.
density Areal density of mass.
v0 Location of vertex zero.
v1 Location of vertex one.
Use the fixture's areal mass density times the shape's second moment of area to derive I.
See also
https://en.wikipedia.org/wiki/Second_moment_of_area
GetMassData() [4/6]
MassData GetMassData (Length vertexRadius, NonNegative< AreaDensity > density, Span< const Length2 > vertices)
Gets the mass data for the given collection of vertices with the given properties.
GetMassData() [5/6]
MassData GetMassData (const Fixture & f)
Computes the mass data for the given fixture.
The mass data is based on the density and the shape of the fixture. The rotational inertia is about the shape's origin.
Note
This operation may be expensive.
Parameters
f Fixture to compute the mass data for.
GetMassData() [6/6]
MassData GetMassData (const Body & body) noexcept
Gets the mass data of the body.
Returns
a struct containing the mass, inertia and center of the body.
GetMaxRegLinearCorrection()
Length GetMaxRegLinearCorrection (const StepConf & conf) inline noexcept
Gets the maximum regular linear correction from the given value.
GetMaxSeparation() [1/3]
IndexPairDistance playrho::GetMaxSeparation (const DistanceProxy & proxy1, Transformation xf1, const DistanceProxy & proxy2, Transformation xf2)
Gets the max separation information.
Note
Prefer using this function - over the GetMaxSeparation function that takes a stopping length - when it's already known that the two convex shapes's AABBs overlap.
Returns
Index of the vertex and normal from proxy1, index of the vertex from proxy2 (that had the maximum separation distance from each other in the direction of that normal), and the maximal distance.
Referenced by CollideShapes().
GetMaxSeparation() [2/3]
IndexPairDistance playrho::GetMaxSeparation (const DistanceProxy & proxy1, Transformation xf1, const DistanceProxy & proxy2, Transformation xf2, Length stop)
Gets the max separation information.
Returns
Index of the vertex and normal from proxy1, index of the vertex from proxy2 (that had the maximum separation distance from each other in the direction of that normal), and the maximal distance.
GetMaxSeparation() [3/3]
IndexPairDistance playrho::GetMaxSeparation (const DistanceProxy & proxy1, const DistanceProxy & proxy2, Length stop = MaxFloat *Meter)
Gets the max separation information.
Returns
Index of the vertex and normal from proxy1, index of the vertex from proxy2 (that had the maximum separation distance from each other in the direction of that normal), and the maximal distance.
GetMaxSeparation4x4()
IndexPairDistance playrho::GetMaxSeparation4x4 (const DistanceProxy & proxy1, Transformation xf1, const DistanceProxy & proxy2, Transformation xf2)
Gets the max separation information for the first four vertices of the two given shapes.
This is a version of the get-max-separation functions that is optimzed for two quadrilateral (4-vertice) polygons.
Returns
Index of the vertex and normal from proxy1, index of the vertex from proxy2 (that had the maximum separation distance from each other in the direction of that normal), and the maximal distance.
Referenced by CollideShapes().
GetMotorForce()
Force GetMotorForce (const PrismaticJoint & joint, Frequency inv_dt) inline noexcept
Gets the current motor force for the given joint, given the inverse time step.
GetMotorJointDef()
MotorJointDef GetMotorJointDef (const MotorJoint & joint) noexcept
Gets the definition data for the given joint.
Referenced by playrho::World::CopyJoints().
GetMotorTorque()
Torque GetMotorTorque (const RevoluteJoint & joint, Frequency inv_dt) inline noexcept
Gets the current motor torque for the given joint given the inverse time step.
GetMouseJointDef()
MouseJointDef GetMouseJointDef (const MouseJoint & joint) noexcept
Gets the definition data for the given joint.
Referenced by playrho::World::CopyJoints().
GetMovedAABB()
template<std::size_t N> PLAYRHO_CONSTEXPR AABB< N > GetMovedAABB (AABB< N > aabb, const Vector< Length, N > value) inline noexcept
Gets the result of moving the given AABB by the given value.
Referenced by playrho::DynamicTree::ShiftOrigin().
GetMovementConf()
MovementConf GetMovementConf (const StepConf & conf) noexcept
Gets the movement configuration from the given value.
Referenced by playrho::World::SolveRegIslandViaGS(), and playrho::World::SolveToiViaGS().
GetNext()
PLAYRHO_CONSTEXPR DynamicTree::Size GetNext (const DynamicTree::TreeNode & node) inline noexcept
Gets the next index of the given node.
Warning
Behavior is undefined if the given node is not an "unused" node.
GetNormal()
UnitVec2 playrho::GetNormal (const VelocityConstraint & vc) inline noexcept
Gets the normal of the velocity constraint contact in world coordinates.
Note
This value is set via the velocity constraint's SetNormal method.
Returns
Contact normal (in world coordinates) if previously set, an invalid value otherwise.
Referenced by playrho::VelocityConstraint::GetPoint().
GetPerimeter()
PLAYRHO_CONSTEXPR Length GetPerimeter (const AABB2D & aabb) inline noexcept
Gets the perimeter length of the 2-dimensional AABB.
Warning
Behavior is undefined for an invalid AABB.
Returns
Twice the sum of the width and height.
See also
https://en.wikipedia.org/wiki/Perimeter
Referenced by ComputePerimeterRatio(), playrho::DynamicTree::ComputeTotalPerimeter(), playrho::DynamicTree::FindLowestCostNode(), and playrho::DynamicTree::RebuildBottomUp().
GetPointDelta()
PLAYRHO_CONSTEXPR Length2 playrho::GetPointDelta (const SimplexEdge & sv) inline noexcept
Gets "w".
Returns
2D vector value of wB minus wA.
Referenced by playrho::Simplex::CalcMetric(), playrho::Simplex::CalcSearchDirection(), playrho::Simplex::Get(), and GetScaledDelta().
GetPosition()
PLAYRHO_CONSTEXPR Position GetPosition (const Position pos0, const Position pos1, const Real beta) inline noexcept
Gets the position between two positions at a given unit interval.
Parameters
pos0 Position at unit interval value of 0.
pos1 Position at unit interval value of 1.
beta Unit interval (value between 0 and 1) of travel between pos0 and pos1.
Returns
pos0 if pos0 == pos1 or beta == 0, pos1 if beta == 1, or at the given unit interval value between pos0 and pos1.
Referenced by playrho::Sweep::Advance0(), and GetTransformation().
GetPosition1()
Position GetPosition1 (const Body & body) inline noexcept
Gets the "position 1" Position information for the given body.
Referenced by GetBodyConstraint(), and playrho::World::UpdateBody().
GetPrismaticJointDef()
PrismaticJointDef GetPrismaticJointDef (const PrismaticJoint & joint) noexcept
Gets the definition data for the given joint.
Referenced by playrho::World::CopyJoints().
GetPSM()
PositionSolverManifold playrho::GetPSM (const Manifold & manifold, Manifold::size_type index, const Transformation & xfA, const Transformation & xfB)
Gets the normal-point-separation data in world coordinates for the given inputs.
Note
The returned normal is in the direction of shape A to shape B.
The returned separation distance does not account for vertex radiuses. It's simply the separation between the points of the manifold. To account for the vertex radiuses, the total vertex radius must be subtracted from this separation distance.
GetPulleyJointDef()
PulleyJointDef GetPulleyJointDef (const PulleyJoint & joint) noexcept
Gets the definition data for the given joint.
Referenced by playrho::World::CopyJoints().
GetRestitution()
Real playrho::GetRestitution (const Shape & shape) noexcept
Gets the restitution value of the given shape.
Gets the coefficient of restitution.
Referenced by playrho::VelocityConstraint::GetPoint(), and playrho::Fixture::GetRestitution().
GetRevoluteJointDef()
RevoluteJointDef GetRevoluteJointDef (const RevoluteJoint & joint) noexcept
Gets the definition data for the given joint.
Referenced by playrho::World::CopyJoints().
GetRevPerpendicular()
PLAYRHO_CONSTEXPR UnitVec2 playrho::GetRevPerpendicular (const UnitVec2 vector) inline noexcept
Gets a vector counter-clockwise (reverse-clockwise) perpendicular to the given vector.
This takes a vector of form (x, y) and returns the vector (-y, x).
Parameters
vector Vector to return a counter-clockwise perpendicular equivalent for.
Returns
A counter-clockwise 90-degree rotation of the given vector.
See also
GetFwdPerpendicular.
GetRopeJointDef()
RopeJointDef GetRopeJointDef (const RopeJoint & joint) noexcept
Gets the definition data for the given joint.
Referenced by playrho::World::CopyJoints().
GetRotInertia()
RotInertia GetRotInertia (const Body & body) inline noexcept
Gets the rotational inertia of the body.
Parameters
body Body to get the rotational inertia for.
Returns
the rotational inertia.
Referenced by GetLocalRotInertia(), and GetTorque().
GetShapeCount()
std::size_t GetShapeCount (const World & world) noexcept
Gets the count of unique shapes in the given world.
GetSize()
template<typename T > PLAYRHO_CONSTEXPR T playrho::GetSize (const Interval< T > & v) inline noexcept
Gets the size of the given interval.
Gets the difference between the max and min values.
Warning
Behavior is undefined if the difference between the given range's max and min values overflows the range of the Interval::value_type.
Returns
Non-negative value unless the given interval is "unset" or invalid.
Referenced by GetDimensions(), and GetPerimeter().
GetSupportIndex()
template<class T > VertexCounter GetSupportIndex (const DistanceProxy & proxy, T d) inline noexcept
Gets the supporting vertex index in the given direction for the given distance proxy.
This finds the vertex that's most significantly in the direction of the given vector and returns its index.
Note
0 is returned for a given zero length direction vector.
Parameters
proxy Distance proxy object to find index in if a valid index exists for it.
d Direction vector to find index for.
Returns
InvalidVertex if d is invalid or the count of vertices is zero, otherwise a value from 0 to one less than count.
See also
GetVertexCount().
< Index of vertex that when dotted with d has the max value.
< Max dot value.
< Index of vertex that when dotted with d has the max value.
< Max dot value.
< Index of vertex that when dotted with d has the max value.
< Max dot value.
Referenced by Distance(), playrho::SeparationFinder::FindMinSeparationForFaceA(), playrho::SeparationFinder::FindMinSeparationForFaceB(), and playrho::SeparationFinder::FindMinSeparationForPoints().
GetToiViaSat()
TOIOutput GetToiViaSat (const DistanceProxy & proxyA, const Sweep & sweepA, const DistanceProxy & proxyB, const Sweep & sweepB, ToiConf conf = GetDefaultToiConf())
Gets the time of impact for two disjoint convex sets using the Separating Axis Theorem.
Computes the upper bound on time before two shapes penetrate too much. Time is represented as a fraction between [0,tMax]. This uses a swept separating axis and may miss some intermediate, non-tunneling collision. If you change the time interval, you should call this function again.
See also
https://en.wikipedia.org/wiki/Hyperplane_separation_theorem
Precondition
The given sweeps are both at the same alpha0.
Warning
Behavior is undefined if sweeps are not at the same alpha0.
Behavior is undefined if conf's tMax is not between 0 and 1 inclusive.
Note
Uses Distance to compute the contact point and normal at the time of impact.
This only works for two disjoint convex sets.
Parameters
proxyA Proxy A. The proxy's vertex count must be 1 or more.
sweepA Sweep A. Sweep of motion for shape represented by proxy A.
proxyB Proxy B. The proxy's vertex count must be 1 or more.
sweepB Sweep B. Sweep of motion for shape represented by proxy B.
conf Configuration details for on calculation. Like the targeted depth of penetration.
Returns
Time of impact output data.
XXX maybe should return TOIOutput{t1, stats, TOIOutput::e_belowMinTarget}?
Referenced by CalcToi().
GetTorque()
Torque GetTorque (const Body & body) inline noexcept
Gets the net torque that the given body is currently experiencing.
GetTouchingCount()
ContactCounter GetTouchingCount (const World & world) noexcept
Gets the touching count for the given world.
GetTransformation()
Transformation GetTransformation (const Fixture & f) noexcept
Gets the transformation associated with the given fixture.
Warning
Behavior is undefined if the fixture doesn't have an associated body - i.e. behavior is undefined if the fixture has nullptr as its associated body.
GetType()
JointType GetType (const Joint & joint) noexcept
Gets the type of the given joint.
Referenced by Dump(), and playrho::GearJoint::IsOkay().
GetTypeName()
template<typename T > const char* playrho::GetTypeName () inline noexcept
Gets the library defined name for the given type.
Provides an interface to a specializable function for getting C-style null-terminated array of characters that names the type.
Returns
Non-null pointer to C-style string name of specified type.
GetTypeName< Fixed32 >()
template<> const char* playrho::GetTypeName< Fixed32 > () inline noexcept
Gets the specialized name for the Fixed32 type.
Provides an interface to a specialized function for getting C-style null-terminated array of characters that names the Fixed32 type.
Returns
Non-null pointer to C-style string name of specified type.
GetTypeName< Fixed64 >()
template<> const char* playrho::GetTypeName< Fixed64 > () inline noexcept
Gets the specialized name for the Fixed64 type.
Provides an interface to a specialized function for getting C-style null-terminated array of characters that names the Fixed64 type.
Returns
Non-null pointer to C-style string name of specified type.
GetUpperBound()
template<std::size_t N> PLAYRHO_CONSTEXPR Vector< Length, N > GetUpperBound (const AABB< N > & aabb) inline noexcept
Gets the upper bound.
Referenced by RayCast().
GetVelocity()
Velocity GetVelocity (const Body & body, Time h, MovementConf conf) noexcept
Gets the velocity of the body after the given time accounting for the body's acceleration and capped by the given configuration.
Warning
Behavior is undefined if the given elapsed time is an invalid value (like NaN).
Parameters
body Body to get the velocity for.
h Time elapsed to get velocity for. Behavior is undefined if this value is invalid.
conf Movement configuration. This defines caps on linear and angular speeds.
GetVertexFaceContactFeature()
PLAYRHO_CONSTEXPR ContactFeature GetVertexFaceContactFeature (ContactFeature::Index a, ContactFeature::Index b) inline noexcept
Gets the vertex face contact feature for the given indices.
Referenced by ClipSegmentToLine().
GetVertexRadius()
NonNegative<Length> playrho::GetVertexRadius (const Shape & shape) noexcept
Gets the vertex radius of the given shape.
Gets the vertex radius.
This gets the radius from the vertex that the shape's "skin" should extend outward by. While any edges - line segments between multiple vertices - are straight, corners between them (the vertices) are rounded and treated as rounded. Shapes with larger vertex radiuses compared to edge lengths therefore will be more prone to rolling or having other shapes more prone to roll off of them. Here's an image of a shape configured via a PolygonShapeConf with it's skin drawn:
Note
This must be a non-negative value.
See also
UseVertexRadius
GetVertexVertexContactFeature()
PLAYRHO_CONSTEXPR ContactFeature GetVertexVertexContactFeature (ContactFeature::Index a, ContactFeature::Index b) inline noexcept
Gets the vertex vertex contact feature for the given indices.
Referenced by playrho::Manifold::GetForCircles().
GetWeldJointDef()
WeldJointDef GetWeldJointDef (const WeldJoint & joint) noexcept
Gets the definition data for the given joint.
Referenced by playrho::World::CopyJoints().
GetWheelJointDef()
WheelJointDef GetWheelJointDef (const WheelJoint & joint) noexcept
Gets the definition data for the given joint.
Referenced by playrho::World::CopyJoints().
GetWorldIndex() [1/2]
JointCounter GetWorldIndex (const Joint * joint)
Gets the world index of the given joint.
GetWorldIndex() [2/2]
BodyCounter GetWorldIndex (const Body * body) noexcept
Gets the world index for the given body.
Referenced by Dump().
GetWorldManifold() [1/2]
WorldManifold GetWorldManifold (const Manifold & manifold, Transformation xfA, Length radiusA, Transformation xfB, Length radiusB)
Gets the world manifold for the given data.
Precondition
The given manifold input has between 0 and 2 points.
Parameters
manifold Manifold to use. Uses the manifold's type, local point, local normal, point-count, and the indexed-points' local point data.
xfA Transformation A.
radiusA Radius of shape A.
xfB Transformation B.
radiusB Radius of shape B.
Returns
World manifold value for the given inputs which will have the same number of points as the given manifold has. The returned world manifold points will be the mid-points of the manifold intersection.
Referenced by GetWorldManifold().
GetWorldManifold() [2/2]
WorldManifold GetWorldManifold (const Contact & contact)
Gets the world manifold for the given data.
Note
This is a convenience function that in turn calls the GetWorldManifold(const Manifold&, const Transformation&, const Real, const Transformation& xfB, const Real) function.
Parameters
contact Contact to return a world manifold for.
Returns
World manifold value for the given inputs which will have the same number of points as the given manifold has. The returned world manifold points will be the mid-points of the contact's intersection.
GetWorldPoint()
Length2 GetWorldPoint (const Body & body, const Length2 localPoint) inline noexcept
Gets the world coordinates of a point given in coordinates relative to the body's origin.
Parameters
body Body that the given point is relative to.
localPoint a point measured relative the the body's origin.
Returns
the same point expressed in world coordinates.
Referenced by playrho::WeldJoint::GetAnchorA(), playrho::FrictionJoint::GetAnchorA(), playrho::DistanceJoint::GetAnchorA(), playrho::WheelJoint::GetAnchorA(), playrho::RopeJoint::GetAnchorA(), playrho::PrismaticJoint::GetAnchorA(), playrho::RevoluteJoint::GetAnchorA(), playrho::GearJoint::GetAnchorA(), playrho::PulleyJoint::GetAnchorA(), playrho::WeldJoint::GetAnchorB(), playrho::FrictionJoint::GetAnchorB(), playrho::WheelJoint::GetAnchorB(), playrho::PrismaticJoint::GetAnchorB(), playrho::RopeJoint::GetAnchorB(), playrho::DistanceJoint::GetAnchorB(), playrho::RevoluteJoint::GetAnchorB(), playrho::GearJoint::GetAnchorB(), playrho::MouseJoint::GetAnchorB(), playrho::PulleyJoint::GetAnchorB(), GetCurrentLengthA(), GetCurrentLengthB(), GetJointTranslation(), GetLinearVelocityFromLocalPoint(), and RotateAboutLocalPoint().
GetWorldVector() [1/2]
Length2 GetWorldVector (const Body & body, const Length2 localVector) inline noexcept
Gets the world coordinates of a vector given the local coordinates.
Parameters
body Body that the given vector is relative to.
localVector a vector fixed in the body.
Returns
the same vector expressed in world coordinates.
Referenced by GetJointTranslation().
GetWorldVector() [2/2]
UnitVec2 GetWorldVector (const Body & body, const UnitVec2 localVector) inline noexcept
Gets the world vector for the given local vector from the given body's transformation.
GetYAxis()
PLAYRHO_CONSTEXPR UnitVec2 playrho::GetYAxis (UnitVec2 rot) inline noexcept
Gets the "Y-axis".
Note
This is the reverse perpendicular vector of the given unit vector.
HasSensor()
bool HasSensor (const Contact & contact) noexcept
Whether the given contact has a sensor.
Referenced by playrho::World::SolveToi(), and playrho::World::UpdateContactTOIs().
Include() [1/2]
template<std::size_t N> PLAYRHO_CONSTEXPR AABB< N > & Include (AABB< N > & var, const Vector< Length, N > & value) inline noexcept
Includes the given location into the given AABB.
Referenced by ComputeAABB(), and GetEnclosingAABB().
Include() [2/2]
template<std::size_t N> PLAYRHO_CONSTEXPR AABB< N > & Include (AABB< N > & var, const AABB< N > & val) inline noexcept
Includes the second AABB into the first one.
Note
If an unset AABB is added to the first AABB, the result will be the first AABB.
If the first AABB is unset and another AABB is added to it, the result will be the other AABB.
IncMotorSpeed()
template<class T > void playrho::IncMotorSpeed (T & j, AngularVelocity delta) inline
Increment motor speed.
Template function for incrementally changing the motor speed of a joint that has the SetMotorSpeed and GetMotorSpeed methods.
IsActive()
bool IsActive (const Contact & contact) noexcept
Determines whether the given contact is "active".
Referenced by playrho::World::SolveToi(), and playrho::World::UpdateContactTOIs().
IsBranch()
PLAYRHO_CONSTEXPR bool IsBranch (const DynamicTree::TreeNode & node) inline noexcept
Is branch.
Determines whether the given DynamicTree node is a branch node. Branch nodes have 2 indices to child nodes.
Determines whether the given node is a "branch" node.
Referenced by playrho::DynamicTree::ComputeHeight(), playrho::DynamicTree::FindLowestCostNode(), playrho::DynamicTree::FindReference(), playrho::DynamicTree::GetBranchData(), playrho::DynamicTree::GetChild1(), playrho::DynamicTree::GetChild2(), playrho::DynamicTree::SetChild1(), playrho::DynamicTree::SetChild2(), SetParent(), and playrho::DynamicTree::ValidateMetrics().
IsEnabled()
bool IsEnabled (const Joint & j) noexcept
Short-cut function to determine if both bodies are enabled.
IsFor()
PLAYRHO_CONSTEXPR bool IsFor (const JointKey key, const Body * body) inline noexcept
Determines whether the given key is for the given body.
IsFullOfBodies()
bool IsFullOfBodies (const Island & island) inline
Determines whether the given island is full of bodies.
IsFullOfContacts()
bool IsFullOfContacts (const Island & island) inline
Determines whether the given island is full of contacts.
IsImpenetrable()
bool IsImpenetrable (const Contact & contact) noexcept
Whether the given contact is "impenetrable".
Referenced by playrho::World::SolveToi(), and playrho::World::UpdateContactTOIs().
IsIntersecting()
template<typename T > PLAYRHO_CONSTEXPR bool IsIntersecting (const Interval< T > & a, const Interval< T > & b) inline noexcept
Checks whether two value ranges have any intersection/overlap at all.
Referenced by TestOverlap().
IsLeaf()
PLAYRHO_CONSTEXPR bool IsLeaf (const DynamicTree::TreeNode & node) inline noexcept
Is leaf.
Whether or not this node is a leaf node.
Determines whether the given DynamicTree node is a leaf node. Leaf nodes have a pointer to user data.
Note
This has constant complexity.
Returns
true if this is a leaf node, false otherwise.
Referenced by playrho::DynamicTree::FindLowestCostNode(), playrho::DynamicTree::GetLeafData(), playrho::DynamicTree::SetLeafData(), and playrho::DynamicTree::ValidateStructure().
IsMaxTranslationWithinTolerance()
bool IsMaxTranslationWithinTolerance (const StepConf & conf) noexcept
Determines whether the maximum translation is within tolerance.
IsUnused()
PLAYRHO_CONSTEXPR bool IsUnused (const DynamicTree::TreeNode & node) inline noexcept
Is unused.
Whether this node is free (or allocated).
Determines whether the given DynamicTree node is an unused node.
Referenced by playrho::DynamicTree::FreeNode(), playrho::DynamicTree::GetAABB(), GetAABB(), GetNext(), playrho::DynamicTree::GetParent(), playrho::DynamicTree::SetAABB(), and playrho::DynamicTree::SetParent().
IsValid() [1/7]
template<> PLAYRHO_CONSTEXPR bool IsValid (const Acceleration & value) inline noexcept
Determines if the given value is valid.
IsValid() [2/7]
template<> PLAYRHO_CONSTEXPR bool IsValid (const Velocity & value) inline noexcept
Determines if the given value is valid.
IsValid() [3/7]
template<> PLAYRHO_CONSTEXPR bool IsValid (const Position & value) inline noexcept
Determines if the given value is valid.
IsValid() [4/7]
template<> PLAYRHO_CONSTEXPR bool IsValid (const Transformation & value) inline noexcept
Determines if the given value is valid.
IsValid() [5/7]
template<> PLAYRHO_CONSTEXPR bool playrho::IsValid (const Mat22 & value) inline noexcept
Determines if the given value is valid.
Determines whether the given vector contains finite coordinates.
IsValid() [6/7]
template<> PLAYRHO_CONSTEXPR bool IsValid (const Sweep & value) inline noexcept
Determines if the given value is valid.
IsValid() [7/7]
template<> PLAYRHO_CONSTEXPR bool IsValid (const Manifold & value) inline noexcept
Gets whether the given manifold is valid.
Referenced by playrho::Sweep::Advance0(), ComputeAABB(), playrho::DynamicTree::CreateLeaf(), Distance(), playrho::DynamicTree::FindLowestCostNode(), playrho::VelocityConstraint::GetPoint(), playrho::WorldManifold::GetPointCount(), GetPosition(), GetToiViaSat(), GetTransformation(), playrho::MouseJoint::InitVelocityConstraints(), playrho::MouseJoint::IsOkay(), IsValid(), playrho::Body::SetAcceleration(), playrho::MotorJoint::SetCorrectionFactor(), playrho::BodyConstraint::SetPosition(), playrho::GearJoint::SetRatio(), playrho::MouseJoint::SetTarget(), playrho::Body::SetTransform(), playrho::Body::SetTransformation(), playrho::BodyConstraint::SetVelocity(), playrho::MouseJoint::SolveVelocityConstraints(), playrho::World::Synchronize(), and playrho::World::UpdateBody().
MixFriction()
Real playrho::MixFriction (Real friction1, Real friction2) inline
Mixes friction.
Friction mixing formula. The idea is to allow either fixture to drive the resulting friction to zero. For example, anything slides on ice.
Warning
Behavior is undefined if either friction values is less than zero.
Parameters
friction1 A zero or greater value.
friction2 A zero or greater value.
Referenced by ResetFriction().
MixRestitution()
Real playrho::MixRestitution (Real restitution1, Real restitution2) inline noexcept
Mixes restitution.
Restitution mixing law. The idea is allow for anything to bounce off an inelastic surface. For example, a superball bounces on anything.
Referenced by ResetRestitution().
operator!=() [1/15]
PLAYRHO_CONSTEXPR bool operator!= (const FixtureProxy & lhs, const FixtureProxy & rhs) inline noexcept
Inequality operator.
operator!=() [2/15]
PLAYRHO_CONSTEXPR bool operator!= (const Acceleration & lhs, const Acceleration & rhs) inline
Inequality operator.
operator!=() [3/15]
PLAYRHO_CONSTEXPR bool operator!= (const Velocity & lhs, const Velocity & rhs) inline
Inequality operator.
operator!=() [4/15]
PLAYRHO_CONSTEXPR bool operator!= (const Position & lhs, const Position & rhs) inline
Inequality operator.
operator!=() [5/15]
PLAYRHO_CONSTEXPR bool operator!= (MassData lhs, MassData rhs) inline
MassData inequality operator.
operator!=() [6/15]
PLAYRHO_CONSTEXPR bool operator!= (Transformation lhs, Transformation rhs) inline noexcept
Inequality operator.
operator!=() [7/15]
PLAYRHO_CONSTEXPR bool operator!= (const Filter lhs, const Filter rhs) inline noexcept
Inequality operator.
operator!=() [8/15]
PLAYRHO_CONSTEXPR bool operator!= (ContactFeature lhs, ContactFeature rhs) inline noexcept
Determines if the given two contact features are not equal.
operator!=() [9/15]
template<std::size_t N> PLAYRHO_CONSTEXPR bool operator!= (const AABB< N > & lhs, const AABB< N > & rhs) inline noexcept
Gets whether the two AABB objects are not equal.
Returns
true if the two values are not equal, false otherwise.
operator!=() [10/15]
bool operator!= (const DistanceProxy & lhs, const DistanceProxy & rhs) inline noexcept
Determines with the two given distance proxies are not equal.
operator!=() [11/15]
template<typename T , std::size_t N> PLAYRHO_CONSTEXPR bool operator!= (const Vector< T, N > & lhs, const Vector< T, N > & rhs) inline noexcept
Inequality operator.
operator!=() [12/15]
template<typename T > PLAYRHO_CONSTEXPR bool operator!= (const Interval< T > & a, const Interval< T > & b) inline noexcept
Inequality operator.
Note
Satisfies the EqualityComparable concept for Interval objects.
See also
http://en.cppreference.com/w/cpp/concept/EqualityComparable
operator!=() [13/15]
PLAYRHO_CONSTEXPR bool operator!= (const DynamicTree::LeafData & lhs, const DynamicTree::LeafData & rhs) inline noexcept
Inequality operator.
operator!=() [14/15]
bool operator!= (const Manifold::Point & lhs, const Manifold::Point & rhs) noexcept
Determines whether the two given manifold points are not equal.
operator!=() [15/15]
bool operator!= (const Manifold & lhs, const Manifold & rhs) noexcept
Manifold inequality operator.
Determines whether the two given manifolds are not equal.
operator*() [1/8]
PLAYRHO_CONSTEXPR Position operator* (const Real scalar, const Position & pos) inline
Multiplication operator.
operator*() [2/8]
PLAYRHO_CONSTEXPR Acceleration operator* (const Acceleration & lhs, const Real rhs) inline
Multiplication operator.
operator*() [3/8]
PLAYRHO_CONSTEXPR Velocity operator* (const Velocity & lhs, const Real rhs) inline
Multiplication operator.
operator*() [4/8]
PLAYRHO_CONSTEXPR Acceleration operator* (const Real lhs, const Acceleration & rhs) inline
Multiplication operator.
operator*() [5/8]
PLAYRHO_CONSTEXPR Velocity operator* (const Real lhs, const Velocity & rhs) inline
Multiplication operator.
operator*() [6/8]
template<std::size_t N, typename T1 , typename T2 , typename OT = decltype(T1{} * T2{})> PLAYRHO_CONSTEXPR auto operator* (const T1 s, const Vector< T2, N > & a) inline noexcept
Multiplication operator.
operator*() [7/8]
template<std::size_t N, typename T1 , typename T2 , typename OT = decltype(T1{} * T2{})> PLAYRHO_CONSTEXPR auto operator* (const Vector< T1, N > & a, const T2 s) inline noexcept
Multiplication operator.
operator*() [8/8]
template<std::size_t N, typename T1 , typename T2 , typename OT = decltype(T1{} * T2{})> PLAYRHO_CONSTEXPR auto operator* (const Vector< T1, N > & lhs, const Vector< T2, N > & rhs) inline noexcept
Multiplication operator.
operator*=() [1/3]
PLAYRHO_CONSTEXPR Acceleration & operator*= (Acceleration & lhs, const Real rhs) inline
Multiplication assignment operator.
operator*=() [2/3]
PLAYRHO_CONSTEXPR Velocity & operator*= (Velocity & lhs, const Real rhs) inline
Multiplication assignment operator.
operator*=() [3/3]
template<typename T , std::size_t N> PLAYRHO_CONSTEXPR auto & operator*= (Vector< T, N > & lhs, const Real rhs) inline noexcept
Multiplication assignment operator.
operator+() [1/8]
PLAYRHO_CONSTEXPR Position operator+ (const Position & value) inline
Positive operator.
operator+() [2/8]
PLAYRHO_CONSTEXPR Position operator+ (const Position & lhs, const Position & rhs) inline
Addition operator.
operator+() [3/8]
PLAYRHO_CONSTEXPR Acceleration operator+ (const Acceleration & lhs, const Acceleration & rhs) inline
Addition operator.
operator+() [4/8]
PLAYRHO_CONSTEXPR Velocity operator+ (const Velocity & lhs, const Velocity & rhs) inline
Addition operator.
operator+() [5/8]
PLAYRHO_CONSTEXPR Acceleration operator+ (const Acceleration & value) inline
Positive operator.
operator+() [6/8]
PLAYRHO_CONSTEXPR Velocity operator+ (const Velocity & value) inline
Positive operator.
operator+() [7/8]
template<typename T , std::size_t N> PLAYRHO_CONSTEXPR auto operator+ (Vector< T, N > v) inline noexcept
Unary plus operator.
operator+() [8/8]
template<typename T , std::size_t N> PLAYRHO_CONSTEXPR auto operator+ (Vector< T, N > lhs, const Vector< T, N > rhs) inline noexcept
Adds two vectors component-wise.
operator+=() [1/4]
PLAYRHO_CONSTEXPR Position & operator+= (Position & lhs, const Position & rhs) inline
Addition assignment operator.
operator+=() [2/4]
PLAYRHO_CONSTEXPR Acceleration & operator+= (Acceleration & lhs, const Acceleration & rhs) inline
Addition assignment operator.
operator+=() [3/4]
PLAYRHO_CONSTEXPR Velocity & operator+= (Velocity & lhs, const Velocity & rhs) inline
Addition assignment operator.
operator+=() [4/4]
template<typename T , std::size_t N> PLAYRHO_CONSTEXPR auto & operator+= (Vector< T, N > & lhs, const Vector< T, N > rhs) inline noexcept
Increments the left hand side value by the right hand side value.
operator-() [1/8]
PLAYRHO_CONSTEXPR Position operator- (const Position & value) inline
Negation operator.
operator-() [2/8]
PLAYRHO_CONSTEXPR Position operator- (const Position & lhs, const Position & rhs) inline
Subtraction operator.
operator-() [3/8]
PLAYRHO_CONSTEXPR Acceleration operator- (const Acceleration & lhs, const Acceleration & rhs) inline
Subtraction operator.
operator-() [4/8]
PLAYRHO_CONSTEXPR Velocity operator- (const Velocity & lhs, const Velocity & rhs) inline
Subtraction operator.
operator-() [5/8]
PLAYRHO_CONSTEXPR Acceleration operator- (const Acceleration & value) inline
Negation operator.
operator-() [6/8]
PLAYRHO_CONSTEXPR Velocity operator- (const Velocity & value) inline
Negation operator.
operator-() [7/8]
template<typename T , std::size_t N> PLAYRHO_CONSTEXPR auto operator- (Vector< T, N > v) inline noexcept
Unary negation operator.
operator-() [8/8]
template<typename T , std::size_t N> PLAYRHO_CONSTEXPR auto operator- (Vector< T, N > lhs, const Vector< T, N > rhs) inline noexcept
Subtracts two vectors component-wise.
operator-=() [1/4]
PLAYRHO_CONSTEXPR Position & operator-= (Position & lhs, const Position & rhs) inline
Subtraction assignment operator.
operator-=() [2/4]
PLAYRHO_CONSTEXPR Acceleration & operator-= (Acceleration & lhs, const Acceleration & rhs) inline
Subtraction assignment operator.
operator-=() [3/4]
PLAYRHO_CONSTEXPR Velocity & operator-= (Velocity & lhs, const Velocity & rhs) inline
Subtraction assignment operator.
operator-=() [4/4]
template<typename T , std::size_t N> PLAYRHO_CONSTEXPR auto & operator-= (Vector< T, N > & lhs, const Vector< T, N > rhs) inline noexcept
Decrements the left hand side value by the right hand side value.
operator/() [1/4]
PLAYRHO_CONSTEXPR Acceleration operator/ (const Acceleration & lhs, const Real rhs) inline
Division operator.
operator/() [2/4]
PLAYRHO_CONSTEXPR Velocity operator/ (const Velocity & lhs, const Real rhs) inline
Division operator.
operator/() [3/4]
template<std::size_t N, typename T1 , typename T2 , typename OT = decltype(T1{} / T2{})> PLAYRHO_CONSTEXPR auto operator/ (const Vector< T1, N > & a, const T2 s) inline noexcept
Division operator.
operator/() [4/4]
template<std::size_t N, typename T1 , typename T2 , typename OT = decltype(T1{} / T2{})> PLAYRHO_CONSTEXPR auto operator/ (const Vector< T1, N > & lhs, const Vector< T2, N > & rhs) inline noexcept
Division operator.
operator/=() [1/3]
PLAYRHO_CONSTEXPR Acceleration & operator/= (Acceleration & lhs, const Real rhs) inline
Division assignment operator.
operator/=() [2/3]
PLAYRHO_CONSTEXPR Velocity & operator/= (Velocity & lhs, const Real rhs) inline
Division assignment operator.
operator/=() [3/3]
template<typename T , std::size_t N> PLAYRHO_CONSTEXPR auto & operator/= (Vector< T, N > & lhs, const Real rhs) inline noexcept
Division assignment operator.
operator<() [1/3]
template<std::size_t N> bool operator< (const AABB< N > & lhs, const AABB< N > & rhs) inline noexcept
Less-than operator.
operator<() [2/3]
template<typename T > PLAYRHO_CONSTEXPR bool operator< (const Interval< T > & lhs, const Interval< T > & rhs) inline noexcept
Less-than operator.
Note
Provides a "strict weak ordering" relation.
This is a lexicographical comparison.
Obeys the LessThanComparable concept: for all a, !(a < a); if (a < b) then !(b < a); if (a < b) and (b < c) then (a < c); with equiv = !(a < b) && !(b < a), if equiv(a, b) and equiv(b, c), then equiv(a, c).
See also
https://en.wikipedia.org/wiki/Weak_ordering#Strict_weak_orderings
http://en.cppreference.com/w/cpp/concept/LessThanComparable
operator<() [3/3]
template<typename T , std::size_t N> PLAYRHO_CONSTEXPR bool operator< (const Vector< T, N > & lhs, const Vector< T, N > & rhs) inline noexcept
Lexicographical less-than operator.
operator<<()
template<typename T , std::size_t N> ::std::ostream& playrho::operator<< (::std::ostream & os, const Vector< T, N > & value)
Output stream operator.
operator<=() [1/3]
template<std::size_t N> bool operator<= (const AABB< N > & lhs, const AABB< N > & rhs) inline noexcept
Less-than or equal-to operator.
operator<=() [2/3]
template<typename T > PLAYRHO_CONSTEXPR bool operator<= (const Interval< T > & lhs, const Interval< T > & rhs) inline noexcept
Less-than or equal-to operator.
Note
Provides a "strict weak ordering" relation.
This is a lexicographical comparison.
See also
https://en.wikipedia.org/wiki/Weak_ordering#Strict_weak_orderings
operator<=() [3/3]
template<typename T , std::size_t N> PLAYRHO_CONSTEXPR bool operator<= (const Vector< T, N > & lhs, const Vector< T, N > & rhs) inline noexcept
Lexicographical less-than or equal-to operator.
operator==() [1/15]
bool operator== (const DistanceProxy & lhs, const DistanceProxy & rhs) noexcept
Determines with the two given distance proxies are equal.
operator==() [2/15]
PLAYRHO_CONSTEXPR bool operator== (const FixtureProxy & lhs, const FixtureProxy & rhs) inline noexcept
Equality operator.
operator==() [3/15]
PLAYRHO_CONSTEXPR bool operator== (const Acceleration & lhs, const Acceleration & rhs) inline
Equality operator.
operator==() [4/15]
PLAYRHO_CONSTEXPR bool operator== (const Velocity & lhs, const Velocity & rhs) inline
Equality operator.
operator==() [5/15]
PLAYRHO_CONSTEXPR bool operator== (const Position & lhs, const Position & rhs) inline
Equality operator.
operator==() [6/15]
PLAYRHO_CONSTEXPR bool operator== (MassData lhs, MassData rhs) inline
MassData equality operator.
operator==() [7/15]
PLAYRHO_CONSTEXPR bool operator== (Transformation lhs, Transformation rhs) inline noexcept
Equality operator.
operator==() [8/15]
PLAYRHO_CONSTEXPR bool operator== (const Filter lhs, const Filter rhs) inline noexcept
Equality operator.
operator==() [9/15]
PLAYRHO_CONSTEXPR bool operator== (ContactFeature lhs, ContactFeature rhs) inline noexcept
Determines if the given two contact features are equal.
operator==() [10/15]
template<std::size_t N> PLAYRHO_CONSTEXPR bool operator== (const AABB< N > & lhs, const AABB< N > & rhs) inline noexcept
Gets whether the two AABB objects are equal.
Returns
true if the two values are equal, false otherwise.
operator==() [11/15]
template<typename T , std::size_t N> PLAYRHO_CONSTEXPR bool operator== (const Vector< T, N > & lhs, const Vector< T, N > & rhs) inline noexcept
Equality operator.
operator==() [12/15]
template<typename T > PLAYRHO_CONSTEXPR bool operator== (const Interval< T > & a, const Interval< T > & b) inline noexcept
Equality operator.
Note
Satisfies the EqualityComparable concept for Interval objects.
See also
http://en.cppreference.com/w/cpp/concept/EqualityComparable
operator==() [13/15]
PLAYRHO_CONSTEXPR bool operator== (const DynamicTree::LeafData & lhs, const DynamicTree::LeafData & rhs) inline noexcept
Equality operator.
operator==() [14/15]
bool operator== (const Manifold::Point & lhs, const Manifold::Point & rhs) noexcept
Determines whether the two given manifold points are equal.
operator==() [15/15]
bool operator== (const Manifold & lhs, const Manifold & rhs) noexcept
Manifold equality operator.
Note
In-so-far as manifold points are concerned, order doesn't matter; only whether the two manifolds have the same point set.
operator>() [1/3]
template<std::size_t N> bool operator> (const AABB< N > & lhs, const AABB< N > & rhs) inline noexcept
Greater-than operator.
operator>() [2/3]
template<typename T > PLAYRHO_CONSTEXPR bool operator> (const Interval< T > & lhs, const Interval< T > & rhs) inline noexcept
Greater-than operator.
Note
Provides a "strict weak ordering" relation.
This is a lexicographical comparison.
See also
https://en.wikipedia.org/wiki/Weak_ordering#Strict_weak_orderings
operator>() [3/3]
template<typename T , std::size_t N> PLAYRHO_CONSTEXPR bool operator> (const Vector< T, N > & lhs, const Vector< T, N > & rhs) inline noexcept
Lexicographical greater-than operator.
operator>=() [1/3]
template<std::size_t N> bool operator>= (const AABB< N > & lhs, const AABB< N > & rhs) inline noexcept
Greater-than or equal-to operator.
operator>=() [2/3]
template<typename T > PLAYRHO_CONSTEXPR bool operator>= (const Interval< T > & lhs, const Interval< T > & rhs) inline noexcept
Greater-than or equal-to operator.
Note
Provides a "strict weak ordering" relation.
This is a lexicographical comparison.
See also
https://en.wikipedia.org/wiki/Weak_ordering#Strict_weak_orderings
operator>=() [3/3]
template<typename T , std::size_t N> PLAYRHO_CONSTEXPR bool operator>= (const Vector< T, N > & lhs, const Vector< T, N > & rhs) inline noexcept
Lexicographical greater-than or equal-to operator.
Query()
void playrho::Query (const DynamicTree & tree, const AABB2D & aabb, const DynamicTreeSizeCB & callback)
Query the given dynamic tree and find nodes overlapping the given AABB.
Note
The callback instance is called for each leaf node that overlaps the supplied AABB.
Referenced by playrho::World::FindNewContacts(), and playrho::World::QueryAABB().
RayCast()
void playrho::RayCast (const DynamicTree & tree, const RayCastInput & input, const DynamicTree::RayCastCallback & callback)
Ray-cast against the leafs in the given tree.
Note
This relies on the callback to perform an exact ray-cast in the case where the leaf node contains a shape.
The callback also performs collision filtering.
Performance is roughly k * log(n), where k is the number of collisions and n is the number of leaf nodes in the tree.
Parameters
tree Dynamic tree to raycast.
input the ray-cast input data. The ray extends from p1 to p1 + maxFraction * (p2 - p1).
callback A callback instance function that's called for each leaf that is hit by the ray. The callback should return 0 to terminate raycasting, or greater than 0 to update the segment bounding box. Values less than zero are ignored.
Referenced by RayCast(), and playrho::World::RayCast().
Realloc()
void * playrho::Realloc (void * ptr, std::size_t new_size)
Reallocates memory.
Note
Implement this function to use your own memory allocator.
Referenced by Realloc().
ResetFriction()
void ResetFriction (Contact & contact)
Resets the friction mixture to the default value.
ResetRestitution()
void ResetRestitution (Contact & contact) noexcept
Reset the restitution to the default value.
Rotate()
PLAYRHO_CONSTEXPR UnitVec2 playrho::Rotate (const UnitVec2 vector, const UnitVec2 & angle) inline noexcept
Rotates a unit vector by the angle expressed by the second unit vector.
Returns
Unit vector for the angle that's the sum of the two angles expressed by the input unit vectors.
RotateAboutLocalPoint()
void RotateAboutLocalPoint (Body & body, Angle amount, Length2 localPoint)
Rotates a body a given amount around a point in body local coordinates.
This changes both the linear and angular positions of the body.
Note
Manipulating a body's position this way may cause non-physical behavior.
This is a convenience function that translates the local point into world coordinates and then calls the RotateAboutWorldPoint function.
Parameters
body Body to rotate.
amount Amount to rotate body by (in counter-clockwise direction).
localPoint Point in local coordinates.
RotateAboutWorldPoint()
void RotateAboutWorldPoint (Body & body, Angle amount, Length2 worldPoint)
Rotates a body a given amount around a point in world coordinates.
This changes both the linear and angular positions of the body.
Note
Manipulating a body's position this way may cause non-physical behavior.
Parameters
body Body to rotate.
amount Amount to rotate body by (in counter-clockwise direction).
worldPoint Point in world coordinates.
Referenced by RotateAboutLocalPoint().
round()
template<typename BT , unsigned int FB> Fixed<BT, FB> playrho::round (Fixed< BT, FB > value) inline noexcept
Rounds the given value.
See also
http://en.cppreference.com/w/cpp/numeric/math/round
Referenced by RoundOff().
Set()
void Set (JointDef & def, const Joint & joint) noexcept
Sets the joint definition data for the given joint.
Referenced by GetDistanceJointDef(), GetFrictionJointDef(), GetGearJointDef(), GetMotorJointDef(), GetMouseJointDef(), GetPrismaticJointDef(), GetPulleyJointDef(), GetRevoluteJointDef(), GetRopeJointDef(), GetWeldJointDef(), and GetWheelJointDef().
SetAcceleration()
void SetAcceleration (Body & body, Acceleration value) inline noexcept
Sets the accelerations on the given body.
Note
This has no effect on non-accelerable bodies.
A non-zero acceleration will also awaken the body.
Parameters
body Body whose acceleration should be set.
value Acceleration value to set.
Referenced by SetAccelerations().
SetAccelerations() [1/2]
void SetAccelerations (World & world, std::function< Acceleration(const Body &b)> fn) noexcept
Sets the accelerations of all the world's bodies.
SetAccelerations() [2/2]
void SetAccelerations (World & world, Acceleration acceleration) noexcept
Sets the accelerations of all the world's bodies to the given value.
SetAngle()
void SetAngle (Body & body, Angle value) inline noexcept
Sets the body's angular orientation.
This instantly adjusts the body to be at the new angular orientation.
Warning
Manipulating a body's angle this way can cause non-physical behavior!
Parameters
body Body to move.
value Valid world angle of the body's local origin. Behavior is undefined if value is invalid.
See also
Body::SetTransform
SetAngularAcceleration()
void SetAngularAcceleration (Body & body, AngularAcceleration value) inline noexcept
Sets the given angular acceleration of the given body.
SetAngularVelocity()
void SetAngularVelocity (Body & body, AngularVelocity omega) inline noexcept
Sets the angular velocity.
Parameters
body Body to set the angular velocity of.
omega the new angular velocity.
SetAwake() [1/3]
void SetAwake (const Fixture & f) noexcept
Sets the associated body's sleep status to awake.
Note
This is a convenience function that simply looks up the fixture's body and calls that body' SetAwake method.
Parameters
f Fixture whose body should be awoken.
SetAwake() [2/3]
void SetAwake (Joint & j) noexcept
Wakes up the joined bodies.
SetAwake() [3/3]
void SetAwake (const Contact & c) noexcept
Sets awake the fixtures of the given contact.
SetForce()
void SetForce (Body & body, Force2 force, Length2 point) inline noexcept
Sets the given amount of force at the given point to the given body.
SetLinearAcceleration()
void SetLinearAcceleration (Body & body, LinearAcceleration2 value) inline noexcept
Sets the given linear acceleration of the given body.
Referenced by ApplyLinearAcceleration().
SetLinearVelocity()
void SetLinearVelocity (Body & body, const LinearVelocity2 v) inline noexcept
Sets the linear velocity of the center of mass.
Parameters
body Body to set the linear velocity of.
v the new linear velocity of the center of mass.
SetLocation()
void SetLocation (Body & body, Length2 value) inline noexcept
Sets the body's location.
This instantly adjusts the body to be at the new location.
Warning
Manipulating a body's location this way can cause non-physical behavior!
Parameters
body Body to move.
value Valid world location of the body's local origin. Behavior is undefined if value is invalid.
See also
Body::SetTransform
SetParent()
DynamicTree::TreeNode & SetParent (DynamicTree::TreeNode & node, DynamicTree::Size other) inline noexcept
Sets the parent index of the given node.
Warning
Behavior is undefined if the given node is not a "branch" node.
SetTorque()
void SetTorque (Body & body, Torque torque) inline noexcept
Sets the given amount of torque to the given body.
ShouldCollide()
bool playrho::ShouldCollide (const Body & lhs, const Body & rhs) noexcept
Should collide.
Determines whether a body should possibly be able to collide with the other body.
Returns
true if either body is dynamic and no joint prevents collision, false otherwise.
Referenced by playrho::World::Add(), playrho::World::DestroyContacts(), and playrho::ContactFilter::ShouldCollide().
sqrt()
template<typename BT , unsigned int FB> auto playrho::sqrt (Fixed< BT, FB > arg) inline
Square root's the given value.
Note
This implementation isn't meant to be fast, only correct enough.
Referenced by playrho::Simplex::CalcMetric(), playrho::UnitVec2::Get(), playrho::VertexSet::GetDefaultMinSeparationSquared(), GetMagnitude(), GetVelocity(), MixFriction(), and RayCast().
Step()
StepStats Step (World & world, Time delta, TimestepIters velocityIterations = 8, TimestepIters positionIterations = 3)
Steps the world ahead by a given time amount.
Performs position and velocity updating, sleeping of non-moving bodies, updating of the contacts, and notifying the contact listener of begin-contact, end-contact, pre-solve, and post-solve events. If the given velocity and position iterations are more than zero, this method also respectively performs velocity and position resolution of the contacting bodies.
Note
While body velocities are updated accordingly (per the sum of forces acting on them), body positions (barring any collisions) are updated as if they had moved the entire time step at those resulting velocities. In other words, a body initially at p0 going v0 fast with a sum acceleration of a, after time t and barring any collisions, will have a new velocity (v1) of v0 + (a * t) and a new position (p1) of p0 + v1 * t.
Warning
Varying the time step may lead to non-physical behaviors.
Postcondition
Static bodies are unmoved.
Kinetic bodies are moved based on their previous velocities.
Dynamic bodies are moved based on their previous velocities, gravity, applied forces, applied impulses, masses, damping, and the restitution and friction values of their fixtures when they experience collisions.
Parameters
world World to step.
delta Time to simulate as a delta from the current state. This should not vary.
velocityIterations Number of iterations for the velocity constraint solver.
positionIterations Number of iterations for the position constraint solver. The position constraint solver resolves the positions of bodies that overlap.
TestOverlap() [1/3]
template<std::size_t N> PLAYRHO_CONSTEXPR bool TestOverlap (const AABB< N > & a, const AABB< N > & b) inline noexcept
Tests for overlap between two axis aligned bounding boxes.
Note
This function's complexity is constant.
Referenced by playrho::World::DestroyContacts(), Query(), RayCast(), TestOverlap(), and playrho::Contact::Update().
TestOverlap() [2/3]
Area playrho::TestOverlap (const DistanceProxy & proxyA, const Transformation & xfA, const DistanceProxy & proxyB, const Transformation & xfB, DistanceConf conf = DistanceConf{})
Determine if two generic shapes overlap.
Note
The returned touching state information typically agrees with that returned from the CollideShapes function. This is not always the case however especially when the separation or overlap distance is closer to zero.
TestOverlap() [3/3]
bool TestOverlap (const DynamicTree & tree, DynamicTree::Size leafIdA, DynamicTree::Size leafIdB) inline noexcept
Tests for overlap of the elements identified in the given dynamic tree.
ToString()
const char * playrho::ToString (JointType type) noexcept
Provides a C-style (null-terminated) string name for given joint type.
Returns
C-style English-language human-readable string uniquely identifying the joint type.
trunc()
template<typename BT , unsigned int FB> Fixed<BT, FB> playrho::trunc (Fixed< BT, FB > arg) inline
Truncates the given value.
See also
http://en.cppreference.com/w/c/numeric/math/trunc
Referenced by ModuloViaTrunc().
Unawaken()
bool Unawaken (Body & body) inline noexcept
Puts the body to sleep if it's awake.
Validate()
bool Validate (const PolygonShapeConf & shape)
Validate convexity of the given shape.
Note
This is a time consuming operation.
Returns
true if valid
Variable Documentation
DefaultAngularSleepTolerance
PLAYRHO_CONSTEXPR const auto playrho::DefaultAngularSleepTolerance = Real{(Pi * 2) / 180} * RadianPerSecond
Default angular sleep tolerance.
A body cannot sleep if its angular velocity is above this amount.
DefaultAngularSlop
PLAYRHO_CONSTEXPR const auto playrho::DefaultAngularSlop = (Pi * 2_rad) / Real{180}
Default angular slop.
A small angle used as a collision and constraint tolerance. Usually it is chosen to be numerically significant, but visually insignificant.
DefaultCirclesRatio
PLAYRHO_CONSTEXPR const auto playrho::DefaultCirclesRatio = Real{10}
Default circles ratio.
Ratio used for switching between rounded-corner collisions and closest-face biased normal collisions.
DefaultLinearSleepTolerance
PLAYRHO_CONSTEXPR const auto playrho::DefaultLinearSleepTolerance = 0.01_mps
Default linear sleep tolerance.
A body cannot sleep if the magnitude of its linear velocity is above this amount.
DefaultLinearSlop
PLAYRHO_CONSTEXPR const auto playrho::DefaultLinearSlop = details::Defaults<Real>::GetLinearSlop()
Default linear slop.
Length used as a collision and constraint tolerance. Usually chosen to be numerically significant, but visually insignificant. Lower or raise to decrease or increase respectively the minimum of space between bodies at rest.
Note
Smaller values relative to sizes of bodies increases the time it takes for bodies to come to rest.
Referenced by playrho::DiskShapeConf::GetDefaultRadius(), playrho::PolygonShapeConf::GetDefaultVertexRadius(), playrho::EdgeShapeConf::GetDefaultVertexRadius(), playrho::ChainShapeConf::GetDefaultVertexRadius(), playrho::MultiShapeConf::GetDefaultVertexRadius(), and playrho::PolygonShapeConf::Set().
DefaultMaxAngularCorrection
PLAYRHO_CONSTEXPR const auto playrho::DefaultMaxAngularCorrection = Real(8.0f / 180.0f) * Pi * 1_rad
Default maximum angular correction.
Note
This value should be greater than the angular slop value.
DefaultMaxLinearCorrection
PLAYRHO_CONSTEXPR const auto playrho::DefaultMaxLinearCorrection = 0.2_m
Default maximum linear correction.
The maximum linear position correction used when solving constraints. This helps to prevent overshoot.
Note
This value should be greater than the linear slop value.
DefaultMaxRotation
PLAYRHO_CONSTEXPR const auto playrho::DefaultMaxRotation = Angle{Pi * 1_rad / Real(2)}
Default maximum rotation per world step.
Warning
This value should be less than Pi * Radian.
Note
This limit is meant to prevent numerical problems. Adjusting this value isn't advised.
See also
StepConf::maxRotation.
DefaultMaxSubSteps
PLAYRHO_CONSTEXPR const auto playrho::DefaultMaxSubSteps = std::uint8_t{8}
Default maximum number of sub steps.
This is the default maximum number of sub-steps per contact in continuous physics simulation. In other words, this is the default maximum number of times in a world step that a contact will have continuous collision resolution done for it.
Note
Used in the TOI phase of step processing.
DefaultMinStillTimeToSleep
PLAYRHO_CONSTEXPR const auto playrho::DefaultMinStillTimeToSleep = Time{1_s / 2}
Default minimum still time to sleep.
The default minimum time bodies must be still for bodies to be put to sleep.
EarthlyGravity2D
PLAYRHO_CONSTEXPR const auto playrho::EarthlyGravity2D = LinearAcceleration2{0_mps2, EarthlyLinearAcceleration}
Earthly gravity in 2-dimensions.
Linear acceleration in 2-dimensions of an earthly object due to Earth's mass.
See also
EarthlyLinearAcceleration
InvalidIndexPair
PLAYRHO_CONSTEXPR const auto playrho::InvalidIndexPair
Initial value:
= IndexPair{
        InvalidVertex, InvalidVertex
    }
Invalid index pair value.
Referenced by playrho::SeparationFinder::FindMinSeparation(), playrho::Simplex::GetIndexPairs(), GetMaxSeparation(), GetMaxSeparation4x4(), and GetNumIndices().
MaxBodies
PLAYRHO_CONSTEXPR const auto playrho::MaxBodies
Initial value:
= static_cast<std::uint16_t>(std::numeric_limits<std::uint16_t>::max() -
                                                      std::uint16_t{1})
Maximum number of bodies in a world.
Note
This is 65534 based off std::uint16_t and eliminating one value for invalid.
Referenced by playrho::World::AddToIsland(), and playrho::World::CreateBody().
MaxContacts
PLAYRHO_CONSTEXPR const auto playrho::MaxContacts = ContactCounter{MaxBodies} * ContactCounter{MaxBodies - 1} / ContactCounter{2}
Maximum number of contacts in a world (2147319811).
Uses the formula for the maximum number of edges in an unidirectional graph of MaxBodies nodes. This occurs when every possible body is connected to every other body.
Referenced by playrho::World::Add().
MaxJoints
PLAYRHO_CONSTEXPR const auto playrho::MaxJoints
Initial value:
= static_cast<std::uint16_t>(std::numeric_limits<std::uint16_t>::max() -
                                                      std::uint16_t{1})
Maximum number of joints in a world.
Note
This is 65534 based off std::uint16_t and eliminating one value for invalid.
Referenced by playrho::World::CreateJoint().
MaxManifoldPoints
PLAYRHO_CONSTEXPR const auto playrho::MaxManifoldPoints = std::uint8_t{2}
Maximum manifold points. This is the maximum number of contact points between two convex shapes. Do not change this value.
Note
For memory efficiency, uses the smallest integral type that can hold the value.
Referenced by playrho::ContactImpulsesList::AddEntry(), playrho::VelocityConstraint::AddPoint(), playrho::Manifold::AddPoint(), playrho::WorldManifold::GetImpulses(), playrho::WorldManifold::GetPoint(), playrho::VelocityConstraint::GetPointAt(), playrho::WorldManifold::GetSeparation(), playrho::VelocityConstraint::PointAt(), and playrho::Manifold::SetPointImpulses().
MaxShapeVertices
PLAYRHO_CONSTEXPR const auto playrho::MaxShapeVertices = std::uint8_t{254}
Maximum number of vertices for any shape type.
Note
For memory efficiency, uses the smallest integral type that can hold the value minus one that's left out as a sentinal value.
Referenced by GetToiViaSat().
Pi
PLAYRHO_CONSTEXPR const auto playrho::Pi = Real(3.14159265358979323846264338327950288)
Pi.
An "irrational number" that's defined as the ratio of a circle's circumference to its diameter.
Note
While the include file definition of M_PI may be a POSIX compliance requirement and initially attractive to use, it's apparently not a C++ standards requirement and casually including it pollutes the namespace of all code that uses this library. Whatever the case, MSVS2017 doesn't make it part of the cmath include without enabling _USE_MATH_DEFINES. So rather than add yet more C-preprocessor macros to all sources that this library may be compiled with, it's simply hard-coded in here instead using a C++ mechanism that also keeps it with the enclosing namespace.
Any narrowing is intentional.
See also
https://en.wikipedia.org/wiki/Pi
Referenced by GetAreaOfCircle(), GetCircleVertices(), GetDelta(), GetMassData(), playrho::ChainShapeConf::GetMassData(), GetNormalized(), playrho::WeldJoint::InitVelocityConstraints(), playrho::DistanceJoint::InitVelocityConstraints(), playrho::MouseJoint::InitVelocityConstraints(), and playrho::WheelJoint::InitVelocityConstraints().
s_blockSizeLookup
PLAYRHO_CONSTEXPR const std::uint8_t playrho::s_blockSizeLookup[BlockAllocator::MaxBlockSize+1] static
Initial value:
=
{
    0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
    7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
    8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
    9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
    9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
}
Block size lookup array.
s_blockSizes
PLAYRHO_CONSTEXPR const std::size_t playrho::s_blockSizes[BlockAllocator::BlockSizes] static
Initial value:
=
{
    16,
    32,
    64,
    96,
    128,
    160,
    192,
    224,
    256,
    320,
    384,
    448,
    512,
    640,
}
Array of block sizes.
SquareRootTwo
PLAYRHO_CONSTEXPR const auto playrho::SquareRootTwo
Initial value:
=
    Real(1.414213562373095048801688724209698078569671875376948073176679737990732478462)
Square root of two.
See also
https://en.wikipedia.org/wiki/Square_root_of_2
Referenced by playrho::UnitVec2::GetBottomRight(), and playrho::UnitVec2::GetTopRight().