PlayRho: playrho::AABB Struct Reference
playrho::AABB Struct Reference
Axis Aligned Bounding Box.
#include <AABB.hpp>
Public Member Functions
constexpr AABB ()=default
Default constructor.
constexpr AABB (const LengthInterval &x, const LengthInterval &y) noexcept
Initializing copy constructor.
constexpr AABB (LengthInterval &&x, LengthInterval &&y) noexcept
Initializing move constructor.
constexpr AABB (const Length2D p) noexcept
Initializing constructor for a single point.
constexpr AABB (const Length2D a, const Length2D b) noexcept
Initializing constructor for two points.
Public Attributes
LengthInterval rangeX
Holds the value range of "X".
LengthInterval rangeY
Holds the value range of "Y".
Related Functions
(Note that these are not member functions.)
constexpr bool operator== (const AABB &lhs, const AABB &rhs)
Gets whether the two AABB objects are equal.
constexpr bool operator!= (const AABB &lhs, const AABB &rhs)
Gets whether the two AABB objects are not equal.
constexpr bool operator< (const AABB &lhs, const AABB &rhs) noexcept
Less-than operator.
constexpr bool operator<= (const AABB &lhs, const AABB &rhs) noexcept
Less-than or equal-to operator.
constexpr bool operator> (const AABB &lhs, const AABB &rhs) noexcept
Greater-than operator.
constexpr bool operator>= (const AABB &lhs, const AABB &rhs) noexcept
Greater-than or equal-to operator.
constexpr bool TestOverlap (const AABB &a, const AABB &b) noexcept
Tests for overlap between two axis aligned bounding boxes.
constexpr Length2D GetCenter (const AABB &aabb) noexcept
Gets the center of the AABB.
constexpr Length2D GetDimensions (const AABB &aabb) noexcept
Gets dimensions of the given AABB.
constexpr Length2D GetExtents (const AABB &aabb) noexcept
Gets the extents of the AABB (half-widths).
constexpr Length GetPerimeter (const AABB &aabb) noexcept
Gets the perimeter length of the AABB.
template<>
constexpr AABB GetInvalid () noexcept
Gets an invalid AABB value.
constexpr bool Contains (const AABB &a, const AABB &b) noexcept
Checks whether the first AABB fully contains the second AABB.
constexpr AABB & Include (AABB &var, const Length2D &value) noexcept
Includes the given location into the given AABB.
constexpr AABB & Include (AABB &var, const AABB &val) noexcept
Includes the second AABB into the first one.
constexpr AABB & Fatten (AABB &var, const NonNegative< Length > amount) noexcept
Fattens an AABB by the given amount.
constexpr AABB GetDisplacedAABB (AABB aabb, const Length2D displacement)
Gets the AABB that the result of displacing the given AABB by the given displacement amount.
constexpr AABB GetFattenedAABB (AABB aabb, const Length amount)
Gets the fattened AABB result.
constexpr AABB GetMovedAABB (AABB aabb, const Length2D value) noexcept
Gets the result of moving the given AABB by the given value.
constexpr AABB GetEnclosingAABB (AABB a, const AABB &b)
Gets the AABB that minimally encloses the given AABBs.
constexpr Length2D GetLowerBound (const AABB &aabb) noexcept
Gets the lower bound.
constexpr Length2D GetUpperBound (const AABB &aabb) noexcept
Gets the upper bound.
RayCastOutput RayCast (const AABB &aabb, const RayCastInput &input) noexcept
Cast a ray against the given AABB.
Detailed Description
Axis Aligned Bounding Box.
This is a concrete value class for an axis aligned bounding box (AABB) which is a type of bounding volume.
Note
This class satisfies at least the following concepts: all the basic concepts, EqualityComparable, and Swappable.
This class is composed of — as in contains and owns &mdash two LengthInterval variables.
Non-defaulted methods of this class are marked noexcept and expect that the Length type doesn't throw.
This data structure is 16-bytes large (on at least one 64-bit platform).
See also
https://en.wikipedia.org/wiki/Bounding_volume
http://en.cppreference.com/w/cpp/concept
Constructor & Destructor Documentation
constexpr playrho::AABB::AABB () default
Default constructor.
Constructs an "unset" AABB.
Note
If an unset AABB is added to another AABB, the result will be the other AABB.
constexpr playrho::AABB::AABB (const Length2D p) inline explicit noexcept
Initializing constructor for a single point.
Parameters
p Point location to initialize this AABB with.
Postcondition
rangeX will have its min and max values both set to the given point's X value.
rangeY will have its min and max values both set to the given point's Y value.
constexpr playrho::AABB::AABB (const Length2D a, const Length2D b) inline noexcept
Initializing constructor for two points.
Parameters
a Point location "A" to initialize this AABB with.
b Point location "B" to initialize this AABB with.
Friends And Related Function Documentation
constexpr bool Contains (const AABB & a, const AABB & b) related
Checks whether the first AABB fully contains the second AABB.
Whether the first AABB contains the entirety of the second AABB where containment is defined as being equal-to or within an AABB.
Note
The "unset" AABB is contained by all valid AABBs including the "unset" AABB itself.
Parameters
a AABB to test whether it constains the second AABB.
b AABB to test whether it's contained by the first AABB.
constexpr AABB & Fatten (AABB & var, const NonNegative< Length > amount) related
Fattens an AABB by the given amount.
Referenced by playrho::GetFattenedAABB().
constexpr Length2D GetCenter (const AABB & aabb) related
Gets the center of the AABB.
Referenced by playrho::GetCenter().
constexpr Length2D GetDimensions (const AABB & aabb) related
Gets dimensions of the given AABB.
Referenced by playrho::GetExtents().
constexpr AABB GetDisplacedAABB (AABB aabb, const Length2D displacement) related
Gets the AABB that the result of displacing the given AABB by the given displacement amount.
constexpr AABB GetEnclosingAABB (AABB a, const AABB & b) related
Gets the AABB that minimally encloses the given AABBs.
constexpr Length2D GetExtents (const AABB & aabb) related
Gets the extents of the AABB (half-widths).
constexpr AABB GetFattenedAABB (AABB aabb, const Length amount) related
Gets the fattened AABB result.
constexpr AABB GetInvalid () related
Gets an invalid AABB value.
constexpr Length2D GetLowerBound (const AABB & aabb) related
Gets the lower bound.
constexpr AABB GetMovedAABB (AABB aabb, const Length2D value) related
Gets the result of moving the given AABB by the given value.
constexpr Length GetPerimeter (const AABB & aabb) related
Gets the perimeter length of the AABB.
Warning
Behavior is undefined for an invalid AABB.
Returns
Twice the sum of the width and height.
constexpr Length2D GetUpperBound (const AABB & aabb) related
Gets the upper bound.
constexpr AABB & Include (AABB & var, const Length2D & value) related
Includes the given location into the given AABB.
Referenced by playrho::GetEnclosingAABB().
constexpr AABB & Include (AABB & var, const AABB & val) related
Includes the second AABB into the first one.
Note
If an unset AABB is added to the first AABB, the result will be the first AABB.
If the first AABB is unset and another AABB is added to it, the result will be the other AABB.
constexpr bool operator!= (const AABB & lhs, const AABB & rhs) related
Gets whether the two AABB objects are not equal.
Returns
true if the two values are not equal, false otherwise.
constexpr bool operator< (const AABB & lhs, const AABB & rhs) related
Less-than operator.
constexpr bool operator<= (const AABB & lhs, const AABB & rhs) related
Less-than or equal-to operator.
constexpr bool operator== (const AABB & lhs, const AABB & rhs) related
Gets whether the two AABB objects are equal.
Returns
true if the two values are equal, false otherwise.
constexpr bool operator> (const AABB & lhs, const AABB & rhs) related
Greater-than operator.
constexpr bool operator>= (const AABB & lhs, const AABB & rhs) related
Greater-than or equal-to operator.
constexpr bool TestOverlap (const AABB & a, const AABB & b) related
Tests for overlap between two axis aligned bounding boxes.
Note
This function's complexity is constant.
The documentation for this struct was generated from the following files:
AABB.hpp
RayCastOutput.hpp