name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Optionally generate compile_commands.json

    - uses: ZedThree/clang-tidy-review@v0.10.1
      id: review
      with:
        clang_tidy_version: '14'
        config_file: '.clang-tidy'
        cmake_command: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
