name: docs

on:
  push:
    branches: [ "master", "release-1.1" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master", "release-1.1" ]

env:
  TARGET_BRANCH_NAME: ${{github.base_ref || github.ref_name}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prerequisites
      run: |
        sudo apt update
        sudo apt install doxygen graphviz

    - name: Configure
      run: >
        cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=Release
        -DPLAYRHO_BUILD_DOC=ON
        -DPLAYRHO_BUILD_LIBRARY=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Install
      run: cmake --install ${{github.workspace}}/build --prefix ${{github.workspace}}/install

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: docs-${{env.TARGET_BRANCH_NAME}}
        path: ${{github.workspace}}/install/share/doc/PlayRho
