PlayRho: playrho::d2::World Class Reference
playrho::d2::World Class Reference
Definition of an independent and simulatable "world".
#include <playrho/d2/World.hpp>
Public Types
using AssociationListener = std::function< void(std::pair< BodyID, ShapeID >)>
Body-shape listener.
using Bodies = std::vector< BodyID >
Container type for Body identifiers.
using BodyContacts = std::vector< std::tuple< ContactKey, ContactID > >
Container type for Body associated contact information.
using BodyJoints = std::vector< std::pair< BodyID, JointID > >
Container type for Body associated Joint identifiers.
using ContactListener = std::function< void(ContactID)>
Listener type for some contact related events.
using Contacts = std::vector< KeyedContactID >
Container type for keyed contact identifiers.
using ImpulsesContactListener = std::function< void(ContactID, const ContactImpulsesList &, unsigned)>
Impulses contact listener.
using JointListener = std::function< void(JointID)>
Listener type for some joint related events.
using Joints = std::vector< JointID >
Container type for Joint identifiers.
using ManifoldContactListener = std::function< void(ContactID, const Manifold &)>
Listener type for some manifold contact events.
using ShapeListener = std::function< void(ShapeID)>
Shape listener.
using Shapes = std::vector< ShapeID >
Container type for Shape identifiers.
Public Member Functions
Special Member Functions
Special member functions that are explicitly defined.
World (const WorldConf &def=WorldConf{})
Constructs a world object.
World (const World &other)
Copy constructor.
World (World &&other) noexcept
Move constructor.
World & operator= (const World &other)
Copy assignment operator.
World & operator= (World &&other) noexcept
Move assignment operator.
~World () noexcept
Destructor.
Listener Member Functions
void SetShapeDestructionListener (ShapeListener listener) noexcept
Registers a destruction listener for shapes.
void SetDetachListener (AssociationListener listener) noexcept
Registers a detach listener for shapes detaching from bodies.
void SetJointDestructionListener (JointListener listener) noexcept
Registers a destruction listener for joints.
void SetBeginContactListener (ContactListener listener) noexcept
Registers a begin contact event listener.
void SetEndContactListener (ContactListener listener) noexcept
Registers an end contact event listener.
void SetPreSolveContactListener (ManifoldContactListener listener) noexcept
Registers a pre-solve contact event listener.
void SetPostSolveContactListener (ImpulsesContactListener listener) noexcept
Registers a post-solve contact event listener.
Miscellaneous Member Functions
void Clear () noexcept
Clears this world.
StepStats Step (const StepConf &conf=StepConf{})
Steps the world simulation according to the given configuration.
bool IsStepComplete () const noexcept
Whether or not "step" is complete.
bool GetSubStepping () const noexcept
Gets whether or not sub-stepping is enabled.
void SetSubStepping (bool flag) noexcept
Enables/disables single stepped continuous physics.
const DynamicTree & GetTree () const noexcept
Gets access to the broad-phase dynamic tree information.
bool IsLocked () const noexcept
Is the world locked (in the middle of a time step).
void ShiftOrigin (const Length2 &newOrigin)
Shifts the world origin.
Length GetMinVertexRadius () const noexcept
Gets the minimum vertex radius that shapes in this world can be.
Length GetMaxVertexRadius () const noexcept
Gets the maximum vertex radius that shapes in this world can be.
Frequency GetInvDeltaTime () const noexcept
Gets the inverse delta time.
Body Member Functions.
Member functions relating to bodies.
BodyCounter GetBodyRange () const noexcept
Gets the extent of the currently valid body range.
const Bodies & GetBodies () const noexcept
Gets the world body range for this constant world.
const Bodies & GetBodiesForProxies () const noexcept
Gets the bodies-for-proxies range for this world.
BodyID CreateBody (const Body &body)
Creates a rigid body that's a copy of the given one.
const Body & GetBody (BodyID id) const
Gets the state of the identified body.
void SetBody (BodyID id, const Body &value)
Sets the state of the identified body.
void Destroy (BodyID id)
Destroys the identified body.
const BodyJoints & GetJoints (BodyID id) const
Gets the range of joints attached to the identified body.
const BodyContacts & GetContacts (BodyID id) const
Gets the container of contacts attached to the identified body.
const Shapes & GetShapes (BodyID id) const
Gets the identities of the shapes associated with the identified body.
Joint Member Functions
Member functions relating to joints.
JointCounter GetJointRange () const noexcept
Gets the extent of the currently valid joint range.
const Joints & GetJoints () const noexcept
Gets the world joint range.
JointID CreateJoint (const Joint &def)
Creates a joint to constrain one or more bodies.
const Joint & GetJoint (JointID id) const
Gets the value of the identified joint.
void SetJoint (JointID id, const Joint &def)
Sets the identified joint to the given value.
void Destroy (JointID id)
Destroys the identified joint.
Shape Member Functions
Member functions relating to shapes.
ShapeCounter GetShapeRange () const noexcept
Gets the extent of the currently valid shape range.
ShapeID CreateShape (const Shape &def)
Creates an identifiable copy of the given shape within this world.
const Shape & GetShape (ShapeID id) const
void SetShape (ShapeID, const Shape &def)
Sets the identified shape to the new value.
void Destroy (ShapeID id)
Destroys the identified shape.
Contact Member Functions
Member functions relating to contacts.
ContactCounter GetContactRange () const noexcept
Gets the extent of the currently valid contact range.
Contacts GetContacts () const
Gets the world contact range.
const Contact & GetContact (ContactID id) const
Gets the identified contact.
void SetContact (ContactID id, const Contact &value)
Sets the identified contact's state.
const Manifold & GetManifold (ContactID id) const
Gets the collision manifold for the identified contact.
Related Functions
(Note that these are not member functions.)
void ApplyAngularImpulse (World &world, BodyID id, AngularMomentum impulse)
Applies an angular impulse.
void ApplyForce (World &world, BodyID id, const Force2 &force, const Length2 &point)
Apply a force at a world point.
void ApplyForceToCenter (World &world, BodyID id, const Force2 &force)
Applies a force to the center of mass of the given body.
void ApplyLinearImpulse (World &world, BodyID id, const Momentum2 &impulse, const Length2 &point)
Applies an impulse at a point.
void ApplyTorque (World &world, BodyID id, Torque torque)
Applies a torque.
void Attach (World &world, BodyID id, const Shape &shape, bool resetMassData=true)
Creates the shape within the world and then associates it with the validly identified body.
void Attach (World &world, BodyID id, ShapeID shapeID, bool resetMassData=true)
Associates a validly identified shape with the validly identified body.
BodyCounter Awaken (World &world)
Awakens all of the bodies in the given world.
bool Awaken (World &world, BodyID id)
Awakens the body if it's asleep.
Acceleration CalcGravitationalAcceleration (const World &world, BodyID id)
Calculates the gravitationally associated acceleration for the given body within its world.
void Clear (World &world) noexcept
Clears this world.
void ClearForces (World &world)
Clears forces.
AABB ComputeAABB (const World &world, BodyID bodyID, ShapeID shapeID)
Computes the AABB for the identified shape relative to the identified body within the given world.
AABB ComputeAABB (const World &world, BodyID id)
Computes the AABB for the identified body within the given world.
AABB ComputeIntersectingAABB (const World &world, BodyID bA, ShapeID sA, ChildCounter iA, BodyID bB, ShapeID sB, ChildCounter iB)
Computes the intersecting AABB for the given pair of body-shape-index values.
AABB ComputeIntersectingAABB (const World &world, const Contact &contact)
Computes the intersecting AABB for the given contact.
MassData ComputeMassData (const World &world, BodyID id)
Computes the identified body's mass data.
MassData ComputeMassData (const World &world, const Span< const ShapeID > &ids)
Computes the mass data total of the identified shapes.
BodyID CreateBody (World &world, const Body &body=Body{}, bool resetMassData=true)
Creates a rigid body within the world that's a copy of the given one.
BodyID CreateBody (World &world, const BodyConf &def, bool resetMassData=true)
Creates a rigid body with the given configuration.
JointID CreateJoint (World &world, const Joint &def)
Creates a new joint within the given world.
template<typename T >
JointID CreateJoint (World &world, const T &value)
Creates a new joint from a configuration.
ShapeID CreateShape (World &world, const Shape &def)
Creates a shape within the specified world.
template<typename T >
auto CreateShape (World &world, const T &shapeConf) -> decltype(CreateShape(world, Shape{shapeConf}))
Creates a shape within the specified world using a configuration of the shape.
void Destroy (World &world, BodyID id)
Destroys the identified body.
void Destroy (World &world, JointID id)
Destroys the identified joint.
void Destroy (World &world, ShapeID id)
Destroys the identified shape.
bool Detach (World &world, BodyID id, bool resetMassData=true)
Disassociates all of the associated shape from the validly identified body.
bool Detach (World &world, BodyID id, ShapeID shapeID, bool resetMassData=true)
Disassociates a validly identified shape from the validly identified body.
void EnableLimit (World &world, JointID id, bool value)
Sets whether the identified joint's limit is enabled or not.
void EnableMotor (World &world, JointID id, bool value)
BodyID FindClosestBody (const World &world, const Length2 &location)
Finds body in given world that's closest to the given location.
Acceleration GetAcceleration (const World &world, BodyID id)
Gets the acceleration of the identified body.
Length2 GetAnchorA (const World &world, JointID id)
Length2 GetAnchorB (const World &world, JointID id)
Angle GetAngle (const World &world, BodyID id)
Gets the angle of the identified body.
Angle GetAngle (const World &world, const RevoluteJointConf &conf)
Gets the current angle of the given configuration in the given world.
Angle GetAngle (const World &world, JointID id)
Gets the angle property of the identified joint if it has it.
AngularAcceleration GetAngularAcceleration (const World &world, BodyID id)
Gets this body's angular acceleration.
Frequency GetAngularDamping (const World &world, BodyID id)
Gets the angular damping of the body.
Angle GetAngularLowerLimit (const World &world, JointID id)
RotInertia GetAngularMass (const World &world, JointID id)
Gets the computed angular rotational inertia used by the joint.
AngularMomentum GetAngularMotorImpulse (const World &world, JointID id)
Gets the angular motor impulse of the identified joint if it has this property.
Angle GetAngularOffset (const World &world, JointID id)
Gets the target angular offset.
AngularMomentum GetAngularReaction (const World &world, JointID id)
Get the angular reaction on body-B for the identified joint.
Angle GetAngularUpperLimit (const World &world, JointID id)
AngularVelocity GetAngularVelocity (const World &world, BodyID id)
Gets the angular velocity.
AngularVelocity GetAngularVelocity (const World &world, const RevoluteJointConf &conf)
Gets the current angular velocity of the given configuration.
AngularVelocity GetAngularVelocity (const World &world, const WheelJointConf &conf)
Gets the angular velocity for the given configuration within the specified world.
AngularVelocity GetAngularVelocity (const World &world, JointID id)
Gets the angular velocity of the identified joint if it has this property.
ShapeCounter GetAssociationCount (const World &world)
Gets the count of body-shape associations in the given world.
BodyCounter GetAwakeCount (const World &world)
Gets the count of awake bodies in the given world.
const std::vector< BodyID > & GetBodies (const World &world) noexcept
Gets the bodies of the specified world.
const std::vector< BodyID > & GetBodiesForProxies (const World &world) noexcept
Gets the bodies-for-proxies range for the given world.
const Body & GetBody (const World &world, BodyID id)
Gets the body configuration for the identified body.
BodyID GetBodyA (const World &world, ContactID id)
Gets the body-A of the identified contact if it has one.
BodyID GetBodyA (const World &world, JointID id)
Gets the identifier of body-A of the identified joint.
BodyID GetBodyB (const World &world, ContactID id)
Gets the body-B of the identified contact if it has one.
BodyID GetBodyB (const World &world, JointID id)
Gets the identifier of body-B of the identified joint.
BodyCounter GetBodyCount (const World &world) noexcept
Gets the body count in the given world.
BodyCounter GetBodyRange (const World &world) noexcept
Gets the extent of the currently valid body range.
Force2 GetCentripetalForce (const World &world, BodyID id, const Length2 &axis)
Gets the centripetal force necessary to put the body into an orbit having the given radius.
ChildCounter GetChildIndexA (const World &world, ContactID id)
Gets the child primitive index A for the identified contact.
ChildCounter GetChildIndexB (const World &world, ContactID id)
Gets the child primitive index B for the identified contact.
bool GetCollideConnected (const World &world, JointID id)
Gets collide connected for the specified joint.
const Contact & GetContact (const World &world, ContactID id)
Gets the identified contact.
ContactCounter GetContactCount (const World &world) noexcept
Gets the count of contacts in the given world.
ContactCounter GetContactRange (const World &world) noexcept
Gets the extent of the currently valid contact range.
std::vector< KeyedContactID > GetContacts (const World &world)
Gets the contacts recognized within the given world.
const std::vector< std::tuple< ContactKey, ContactID > > & GetContacts (const World &world, BodyID id)
Gets the container of all contacts attached to the identified body.
Length GetCurrentLengthA (const World &world, JointID id)
Get the current length of the segment attached to body-A.
Length GetCurrentLengthB (const World &world, JointID id)
Get the current length of the segment attached to body-B.
Real GetDampingRatio (const World &world, JointID id)
Gets the damping ratio associated with the identified joint if it has one.
Real GetDefaultFriction (const World &world, ContactID id)
Gets the default friction amount for the identified contact.
Real GetDefaultRestitution (const World &world, ContactID id)
Gets the default restitution amount for the identified contact.
NonNegative< AreaDensity > GetDensity (const World &world, ShapeID id)
Gets the density of this shape.
DistanceJointConf GetDistanceJointConf (const World &world, BodyID bodyA, BodyID bodyB, const Length2 &anchorA=Length2{}, const Length2 &anchorB=Length2{})
Gets the configuration for the given parameters.
Filter GetFilterData (const World &world, ShapeID id)
Gets the filter data for the identified shape.
Frequency GetFrequency (const World &world, JointID id)
Gets the frequency of the identified joint if it has this property.
NonNegativeFF< Real > GetFriction (const World &world, ContactID id)
Gets the friction used with the identified contact.
NonNegativeFF< Real > GetFriction (const World &world, ShapeID id)
Gets the coefficient of friction of the specified shape.
FrictionJointConf GetFrictionJointConf (const World &world, BodyID bodyA, BodyID bodyB, const Length2 &anchor)
Gets the confguration for the given parameters.
GearJointConf GetGearJointConf (const World &world, JointID id1, JointID id2, Real ratio=Real{1})
Gets the configuration for the given parameters.
Length2 GetGroundAnchorA (const World &world, JointID id)
Length2 GetGroundAnchorB (const World &world, JointID id)
InvMass GetInvMass (const World &world, BodyID id)
Gets the inverse total mass of the body.
InvRotInertia GetInvRotInertia (const World &world, BodyID id)
Gets the inverse rotational inertia of the body.
const Joint & GetJoint (const World &world, JointID id)
Gets the value of the identified joint.
JointCounter GetJointCount (const World &world) noexcept
JointCounter GetJointRange (const World &world) noexcept
Gets the extent of the currently valid joint range.
const std::vector< JointID > & GetJoints (const World &world) noexcept
Gets the joints of the specified world.
const std::vector< std::pair< BodyID, JointID > > & GetJoints (const World &world, BodyID id)
Gets the range of all joints attached to the identified body.
Length GetJointTranslation (const World &world, JointID id)
Gets the current joint translation.
Length GetLength (const World &world, JointID id)
Gets the length associated with the identified joint if it has one.
LimitState GetLimitState (const World &world, JointID id)
Gets the joint's limit state if it has one.
LinearAcceleration2 GetLinearAcceleration (const World &world, BodyID id)
Gets this body's linear acceleration.
Frequency GetLinearDamping (const World &world, BodyID id)
Gets the linear damping of the body.
Momentum GetLinearMotorImpulse (const World &world, JointID id)
Gets the linear motor impulse of the identified joint if it supports that.
Length2 GetLinearOffset (const World &world, JointID id)
Gets the target linear offset, in frame A.
Momentum2 GetLinearReaction (const World &world, JointID id)
Gets the linear reaction on body-B at the joint anchor.
LinearVelocity2 GetLinearVelocity (const World &world, BodyID id)
Gets the linear velocity of the center of mass of the identified body.
LinearVelocity GetLinearVelocity (const World &world, const PrismaticJointConf &joint) noexcept
Gets the current linear velocity of the given configuration.
Length2 GetLocalAnchorA (const World &world, JointID id)
Length2 GetLocalAnchorB (const World &world, JointID id)
Length2 GetLocalCenter (const World &world, BodyID id)
Gets the local position of the center of mass of the specified body.
Length2 GetLocalPoint (const World &world, BodyID id, const Length2 &worldPoint)
Gets a local point relative to the body's origin given a world point.
RotInertia GetLocalRotInertia (const World &world, BodyID id)
Gets the rotational inertia of the body about the local origin.
UnitVec GetLocalVector (const World &world, BodyID body, const UnitVec &uv)
Convenience function for getting the local vector of the identified body.
UnitVec GetLocalXAxisA (const World &world, JointID id)
Gets the local-X-axis-A property of the identified joint if it has it.
UnitVec GetLocalYAxisA (const World &world, JointID id)
Gets the local-Y-axis-A property of the identified joint if it has it.
Length2 GetLocation (const World &world, BodyID id)
Convenience function for getting just the location of the identified body.
const Manifold & GetManifold (const World &world, ContactID id)
Gets the manifold for the identified contact.
Mass GetMass (const World &world, BodyID id)
Gets the mass of the body.
MassData GetMassData (const World &world, BodyID id)
Gets the mass data of the body.
MassData GetMassData (const World &world, ShapeID id)
Gets the mass data for the identified shape in the given world.
Torque GetMaxMotorTorque (const World &world, JointID id)
Gets the max motor torque.
Length GetMaxVertexRadius (const World &world) noexcept
Gets the max vertex radius that shapes for the given world are allowed to be.
Length GetMinVertexRadius (const World &world) noexcept
Gets the min vertex radius that shapes for the given world are allowed to be.
Force GetMotorForce (const World &world, JointID id, Frequency inv_dt)
Gets the current motor force for the given joint, given the inverse time step.
MotorJointConf GetMotorJointConf (const World &world, BodyID bA, BodyID bB)
Gets the confguration for the given parameters.
AngularVelocity GetMotorSpeed (const World &world, JointID id)
Gets the motor-speed property of the identied joint if it supports it.
Torque GetMotorTorque (const World &world, JointID id, Frequency inv_dt)
Gets the current motor torque for the given joint given the inverse time step.
PrismaticJointConf GetPrismaticJointConf (const World &world, BodyID bA, BodyID bB, const Length2 &anchor, const UnitVec &axis)
Gets the configuration for the given parameters.
PulleyJointConf GetPulleyJointConf (const World &world, BodyID bA, BodyID bB, const Length2 &groundA, const Length2 &groundB, const Length2 &anchorA, const Length2 &anchorB)
Gets the configuration for the given parameters.
Real GetRatio (const World &world, JointID id)
Gets the ratio property of the identified joint if it has it.
Angle GetReferenceAngle (const World &world, JointID id)
Gets the reference-angle property of the identified joint if it has it.
Real GetRestitution (const World &world, ContactID id)
Gets the restitution used with the identified contact.
Real GetRestitution (const World &world, ShapeID id)
Gets the coefficient of restitution of the specified shape.
RevoluteJointConf GetRevoluteJointConf (const World &world, BodyID bodyA, BodyID bodyB, const Length2 &anchor)
Gets the configuration for the given parameters.
RotInertia GetRotInertia (const World &world, BodyID id)
Gets the rotational inertia of the body.
const Shape & GetShape (const World &world, ShapeID id)
Gets the shape associated with the identifier.
ShapeID GetShapeA (const World &world, ContactID id)
Gets shape A of the identified contact.
ShapeID GetShapeB (const World &world, ContactID id)
Gets shape B of the identified contact.
ShapeCounter GetShapeCount (const World &world, BodyID id)
Gets the count of shapes associated with the identified body.
ShapeCounter GetShapeRange (const World &world) noexcept
Gets the extent of the currently valid shape range.
const std::vector< ShapeID > & GetShapes (const World &world, BodyID id)
Gets the identities of the shapes associated with the identified body.
bool GetSubStepping (const World &world) noexcept
Gets whether or not sub-stepping is enabled.
LinearVelocity GetTangentSpeed (const World &world, ContactID id)
Gets the tangent speed of the identified contact.
Length2 GetTarget (const World &world, JointID id)
Gets the target point.
std::optional< UnitInterval< Real > > GetToi (const World &world, ContactID id)
Gets the time of impact (TOI) as a fraction or empty value.
TimestepIters GetToiCount (const World &world, ContactID id)
Gets the Time Of Impact (TOI) count.
ContactCounter GetTouchingCount (const World &world)
Gets the touching count for the given world.
Transformation GetTransformation (const World &world, BodyID id)
Gets the body's transformation.
const DynamicTree & GetTree (const World &world) noexcept
Gets the dynamic tree of the given world.
BodyType GetType (const World &world, BodyID id)
Gets the type of the identified body.
TypeID GetType (const World &world, JointID id)
Gets the type of the joint.
TypeID GetType (const World &world, ShapeID id)
Gets the type of the shape.
ShapeCounter GetUsedShapesCount (const World &world) noexcept
Gets the count of uniquely identified shapes that are in use - i.e. that are attached to bodies.
Velocity GetVelocity (const World &world, BodyID id)
Gets the velocity of the identified body.
WeldJointConf GetWeldJointConf (const World &world, BodyID bodyA, BodyID bodyB, const Length2 &anchor=Length2{})
Gets the configuration for the given parameters.
WheelJointConf GetWheelJointConf (const World &world, BodyID bodyA, BodyID bodyB, const Length2 &anchor, const UnitVec &axis=UnitVec::GetRight())
Gets the definition data for the given parameters.
Length2 GetWorldCenter (const World &world, BodyID id)
Get the world position of the center of mass of the specified body.
BodyCounter GetWorldIndex (const World &, BodyID id) noexcept
Gets the world index for the given body.
JointCounter GetWorldIndex (const World &, JointID id) noexcept
Gets the world index of the given joint.
WorldManifold GetWorldManifold (const World &world, ContactID id)
Gets the world manifold for the identified contact.
Length2 GetWorldPoint (const World &world, BodyID id, const Length2 &localPoint)
Gets the world coordinates of a point given in coordinates relative to the body's origin.
UnitVec GetWorldVector (const World &world, BodyID id, const UnitVec &localVector)
Convenience function for getting a world vector of the identified body.
bool HasValidToi (const World &world, ContactID id)
Whether or not the contact has a valid TOI.
bool IsAccelerable (const World &world, BodyID id)
Is identified body "accelerable"?
bool IsAwake (const World &world, BodyID id)
Gets the awake/asleep state of this body.
bool IsAwake (const World &world, ContactID id)
Gets the awake status of the specified contact.
bool IsEnabled (const World &world, BodyID id)
Gets the enabled/disabled state of the body.
bool IsEnabled (const World &world, ContactID id)
Gets the enabled status of the identified contact.
bool IsEnabled (const World &world, JointID id)
Gets the enabled/disabled state of the joint.
bool IsFixedRotation (const World &world, BodyID id)
Gets whether the body has fixed rotation.
bool IsImpenetrable (const World &world, BodyID id)
Is the body treated like a bullet for continuous collision detection?
bool IsLimitEnabled (const World &world, JointID id)
Gets whether the identified joint's limit is enabled.
bool IsMassDataDirty (const World &world, BodyID id)
Gets whether the body's mass-data is dirty.
bool IsMotorEnabled (const World &world, JointID id)
bool IsSensor (const World &world, ShapeID id)
Is the specified shape a sensor (non-solid)?
bool IsSleepingAllowed (const World &world, BodyID id)
Gets whether the identified body is allowed to sleep.
bool IsSpeedable (const World &world, BodyID id)
Is identified body "speedable".
bool IsTouching (const World &world, ContactID id)
Is this contact touching?
bool NeedsFiltering (const World &world, ContactID id)
Whether or not the contact needs filtering.
bool NeedsUpdating (const World &world, ContactID id)
Whether or not the contact needs updating.
bool RayCast (const World &world, const RayCastInput &input, const ShapeRayCastCB &callback)
Ray-cast the world for all fixtures in the path of the ray.
void ResetFriction (World &world, ContactID id)
void ResetMassData (World &world, BodyID id)
Resets the mass data properties.
void ResetRestitution (World &world, ContactID id)
void Rotate (World &world, ShapeID id, const UnitVec &value)
Rotates all of the given shape's vertices by the given amount.
void RotateAboutLocalPoint (World &world, BodyID id, Angle amount, const Length2 &localPoint)
Rotates a body a given amount around a point in body local coordinates.
void RotateAboutWorldPoint (World &world, BodyID id, Angle amount, const Length2 &worldPoint)
Rotates a body a given amount around a point in world coordinates.
void Scale (World &world, ShapeID id, const Vec2 &value)
Scales all of the given shape's vertices by the given amount.
void SetAcceleration (World &world, BodyID id, AngularAcceleration value)
Sets the rotational accelerations on the body.
void SetAcceleration (World &world, BodyID id, const Acceleration &value)
Sets the accelerations on the given body.
void SetAcceleration (World &world, BodyID id, const LinearAcceleration2 &linear, AngularAcceleration angular)
Sets the linear and rotational accelerations on the body.
void SetAcceleration (World &world, BodyID id, const LinearAcceleration2 &value)
Sets the linear accelerations on the body.
void SetAccelerations (World &world, const Acceleration &acceleration)
Sets the accelerations of all the world's bodies to the given value.
void SetAccelerations (World &world, const LinearAcceleration2 &acceleration)
Sets the accelerations of all the world's bodies to the given value.
template<class F >
void SetAccelerations (World &world, F fn)
Sets the accelerations of all the world's bodies.
void SetAngle (World &world, BodyID id, Angle value)
Sets the body's angular orientation.
void SetAngularDamping (World &world, BodyID id, NonNegative< Frequency > angularDamping)
Sets the angular damping of the body.
void SetAngularLimits (World &world, JointID id, Angle lower, Angle upper)
void SetAngularOffset (World &world, JointID id, Angle value)
Sets the target angular offset.
void SetAwake (World &world, BodyID id)
Wakes up the identified body.
void SetAwake (World &world, ContactID id)
Sets awake the bodies of the given contact.
void SetAwake (World &world, JointID id)
Wakes up the joined bodies.
void SetBeginContactListener (World &world, std::function< void(ContactID)> listener) noexcept
Sets the begin-contact lister.
void SetBody (World &world, BodyID id, const Body &body)
Sets the body state for the identified body.
void SetContact (World &world, ContactID id, const Contact &value)
Sets the identified contact's state.
void SetDensity (World &world, ShapeID id, NonNegative< AreaDensity > value)
Sets the density of this shape.
void SetDetachListener (World &world, std::function< void(std::pair< BodyID, ShapeID >)> listener) noexcept
Sets the detach lister.
void SetEnabled (World &world, BodyID id, bool value)
Sets the enabled state of the body.
void SetEnabled (World &world, ContactID id)
Sets the enabled status of the identified contact.
void SetEnabled (World &world, ContactID id, bool value)
Convenience function for setting/unsetting the enabled status of the identified contact based on the value parameter.
void SetEndContactListener (World &world, std::function< void(ContactID)> listener) noexcept
Sets the end-contact lister.
void SetFilterData (World &world, ShapeID id, const Filter &filter)
Convenience function for setting the contact filtering data.
void SetFixedRotation (World &world, BodyID id, bool value)
Sets this body to have fixed rotation.
void SetForce (World &world, BodyID id, const Force2 &force, const Length2 &point)
Sets the given amount of force at the given point to the given body.
void SetFrequency (World &world, JointID id, Frequency value)
Sets the frequency of the identified joint if it has this property.
void SetFriction (World &world, ContactID id, NonNegative< Real > friction)
Sets the friction value for the identified contact.
void SetFriction (World &world, ShapeID id, NonNegative< Real > value)
Convenience function for setting the coefficient of friction of the specified shape.
void SetImpenetrable (World &world, BodyID id)
Sets the impenetrable status of the identified body.
void SetImpenetrable (World &world, BodyID id, bool value)
Convenience function that sets/unsets the impenetrable status of the identified body.
void SetJoint (World &world, JointID id, const Joint &def)
Sets the value of the identified joint.
template<typename T >
void SetJoint (World &world, JointID id, const T &value)
Sets a joint's value from a configuration.
void SetJointDestructionListener (World &world, std::function< void(JointID)> listener) noexcept
Sets the joint destruction lister.
void SetLinearDamping (World &world, BodyID id, NonNegative< Frequency > linearDamping)
Sets the linear damping of the body.
void SetLinearOffset (World &world, JointID id, const Length2 &value)
Sets the target linear offset, in frame A.
void SetLocation (World &world, BodyID id, const Length2 &value)
Sets the body's location.
void SetMassData (World &world, BodyID id, const MassData &massData)
Sets the mass properties to override the mass properties of the fixtures.
void SetMaxMotorTorque (World &world, JointID id, Torque value)
void SetMotorSpeed (World &world, JointID id, AngularVelocity value)
Sets the motor-speed property of the identied joint if it supports it.
void SetPostSolveContactListener (World &world, std::function< void(ContactID, const ContactImpulsesList &, unsigned)> listener) noexcept
Sets the post-solve-contact lister.
void SetPreSolveContactListener (World &world, std::function< void(ContactID, const Manifold &)> listener) noexcept
Sets the pre-solve-contact lister.
void SetRestitution (World &world, ContactID id, Real restitution)
Sets the restitution value for the specified contact.
void SetRestitution (World &world, ShapeID id, Real value)
Sets the coefficient of restitution of the specified shape.
void SetSensor (World &world, ShapeID id, bool value)
Convenience function for setting whether the shape is a sensor or not.
void SetShape (World &world, ShapeID, const Shape &def)
Sets the identified shape to the new value.
void SetShapeDestructionListener (World &world, std::function< void(ShapeID)> listener) noexcept
Sets the shape destruction lister.
void SetSleepingAllowed (World &world, BodyID, bool value)
Sets whether the identified body is allowed to sleep.
void SetSubStepping (World &world, bool flag) noexcept
Enables/disables single stepped continuous physics.
void SetTangentSpeed (World &world, ContactID id, LinearVelocity value)
Sets the desired tangent speed for a conveyor belt behavior.
void SetTarget (World &world, JointID id, const Length2 &value)
Sets the target point.
void SetTorque (World &world, BodyID id, Torque torque)
Sets the given amount of torque to the given body.
void SetTransform (World &world, BodyID id, const Length2 &location, Angle angle)
Sets the position of the body's origin and rotation.
void SetTransformation (World &world, BodyID id, const Transformation &value)
Sets the transformation of the body.
void SetType (World &world, BodyID id, BodyType value, bool resetMassData=true)
Sets the type of the given body.
void SetVelocity (World &world, BodyID id, AngularVelocity value)
Sets the velocity of the identified body.
void SetVelocity (World &world, BodyID id, const LinearVelocity2 &value)
Sets the velocity of the identified body.
void SetVelocity (World &world, BodyID id, const Velocity &value)
Sets the body's velocity (linear and angular velocity).
void ShiftOrigin (World &world, const Length2 &newOrigin)
Shifts the world origin.
bool ShiftOrigin (World &world, JointID id, const Length2 &value)
Shifts the origin of the identified joint.
StepStats Step (World &world, const StepConf &conf=StepConf{})
Steps the given world the specified amount.
StepStats Step (World &world, Time delta, TimestepIters velocityIterations=StepConf::DefaultRegVelocityIters, TimestepIters positionIterations=StepConf::DefaultRegPositionIters)
Steps the world ahead by a given time amount.
bool TestPoint (const World &world, BodyID bodyId, ShapeID shapeId, const Length2 &p)
Tests a point for containment in a shape associated with a body.
void Translate (World &world, ShapeID id, const Length2 &value)
Translates all of the given shape's vertices by the given amount.
void UnsetAwake (World &world, BodyID id)
Sleeps the identified body.
void UnsetEnabled (World &world, ContactID id)
Unsets the enabled status of the identified contact.
void UnsetImpenetrable (World &world, BodyID id)
Unsets the impenetrable status of the identified body.
Detailed Description
Definition of an independent and simulatable "world".
The world class manages physics entities, dynamic simulation, and queries. In a physical sense, perhaps this is more like a universe in that entities in a world have no interaction with entities in other worlds. In any case, there's precedence, from a physics-engine standpoint, for this being called a world.
Note
World instances do not themselves have any force or acceleration properties. They simply utilize the acceleration property of the bodies they manage. This is different than some other engines (like Box2D which provides a world gravity property).
World instances are composed of — i.e. contain and own — body, contact, shape, and joint entities. These are identified by BodyID, ContactID, ShapeID, and JointID values respectively.
This class uses the pointer to implementation (PIMPL) technique and non-vitural interface (NVI) pattern to provide a complete layer of abstraction from the actual implementations used. This forms a "compilation firewall" — or application binary interface (ABI) — to help provide binary stability while facilitating experimentation and optimization.
Attention
For example, the following could be used to create a dynamic body having a one meter radius disk shape:
auto world = World{};
const auto shape = world.CreateShape(Shape{DiskShapeConf{1_m}});
const auto body = world.CreateBody(BodyConf{}.Use(BodyType::Dynamic).Use(shape));
See also
BodyID, ContactID, ShapeID, JointID, Physical Entities.
https://en.wikipedia.org/wiki/Non-virtual_interface_pattern
https://en.wikipedia.org/wiki/Application_binary_interface
https://en.cppreference.com/w/cpp/language/pimpl
Constructor & Destructor Documentation
World() [1/3]
playrho::d2::World::World (const WorldConf & def = WorldConf{}) explicit
Constructs a world object.
Parameters
def A customized world configuration or its default value.
Note
A lot more configurability can be had via the StepConf data that's given to the world's Step method.
Exceptions
InvalidArgument if the given max vertex radius is less than the min.
See also
Step.
World() [2/3]
playrho::d2::World::World (const World & other)
Copy constructor.
Copy constructs this world with a deep copy of the given world.
World() [3/3]
playrho::d2::World::World (World && other) default noexcept
Move constructor.
Move constructs this world.
Postcondition
this is what other used to be.
other is in a "valid but unspecified state". The only thing it can be used for, is as the destination of an assignment.
~World()
playrho::d2::World::~World () noexcept
Destructor.
All physics entities are destroyed and all memory is released.
Note
This will call the Clear() function.
See also
Clear.
Member Function Documentation
Clear()
void playrho::d2::World::Clear () noexcept
Clears this world.
Note
This calls the joint and shape destruction listeners (if they're set), for all defined joints and shapes, before clearing anything. Any exceptions thrown from these listeners are ignored.
Postcondition
The contents of this world have all been destroyed and this world's internal state is reset as though it had just been constructed.
See also
SetJointDestructionListener, SetShapeDestructionListener.
Referenced by Clear().
CreateBody()
BodyID playrho::d2::World::CreateBody (const Body & body)
Creates a rigid body that's a copy of the given one.
Warning
This function should not be used while the world is locked — as it is during callbacks. If it is, it will throw an exception or abort your program.
Note
No references to the configuration are retained. Its value is copied.
Postcondition
The created body will be present in the range returned from the GetBodies() method.
Parameters
body A customized body or its default value.
Returns
Identifier of the newly created body which can later be destroyed by calling the Destroy(BodyID) method.
Exceptions
WrongState if this method is called while the world is locked.
LengthError if this operation would create more than MaxBodies.
std::out_of_range if the given body references any invalid shape identifiers.
See also
Destroy(BodyID), GetBodies.
Physical Entities.
Referenced by CreateBody().
CreateJoint()
JointID playrho::d2::World::CreateJoint (const Joint & def)
Creates a joint to constrain one or more bodies.
Warning
This function is locked during callbacks.
Postcondition
The created joint will be present in the range returned from the GetJoints() method.
Returns
Identifier of newly created joint which can later be destroyed by calling the Destroy(JointID) method.
Exceptions
WrongState if this method is called while the world is locked.
LengthError if this operation would create more than MaxJoints.
See also
Physical Entities.
Destroy(JointID), GetJoints.
Referenced by CreateJoint().
CreateShape()
ShapeID playrho::d2::World::CreateShape (const Shape & def)
Creates an identifiable copy of the given shape within this world.
Exceptions
InvalidArgument if called for a shape with a vertex radius that's either: less than the minimum vertex radius, or greater than the maximum vertex radius.
WrongState if this method is called while the world is locked.
LengthError if this operation would create more than MaxShapes.
See also
Destroy(ShapeID), GetShape, SetShape.
Referenced by CreateShape().
Destroy() [1/3]
void playrho::d2::World::Destroy (BodyID id)
Destroys the identified body.
Destroys the identified body that had previously been created by a call to this world's CreateBody(const BodyConf&) method.
Warning
This automatically deletes all associated shapes and joints.
This function is locked during callbacks.
Behavior is not specified if identified body wasn't created by this world.
Note
This function is locked during callbacks.
Postcondition
The destroyed body will no longer be present in the range returned from the GetBodies() method.
Parameters
id Identifier of body to destroy that had been created by this world.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid body identifier.
See also
CreateBody(const BodyConf&), GetBodies, GetBodyRange.
Physical Entities.
Referenced by Destroy().
Destroy() [2/3]
void playrho::d2::World::Destroy (JointID id)
Destroys the identified joint.
Destroys the identified joint that had previously been created by a call to this world's CreateJoint(const Joint&) method.
Warning
This function is locked during callbacks.
Note
This may cause the connected bodies to begin colliding.
Postcondition
The destroyed joint will no longer be present in the range returned from the GetJoints() method.
Parameters
id Identifier of joint to destroy that had been created by this world.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid joint identifier.
See also
CreateJoint(const Joint&), GetJoints, GetJointRange.
Physical Entities.
Destroy() [3/3]
void playrho::d2::World::Destroy (ShapeID id)
Destroys the identified shape.
Exceptions
std::out_of_range If given an invalid shape identifier.
See also
CreateShape.
GetBodies()
const World::Bodies & playrho::d2::World::GetBodies () const noexcept
Gets the world body range for this constant world.
Gets a range enumerating the bodies currently existing within this world. These are the bodies that had been created from previous calls to the CreateBody(const BodyConf&) method that haven't yet been destroyed.
Returns
An iterable of body identifiers.
See also
CreateBody(const BodyConf&).
Referenced by Awaken(), CalcGravitationalAcceleration(), FindClosestBody(), GetAssociationCount(), GetAwakeCount(), and SetAccelerations().
GetBodiesForProxies()
const World::Bodies & playrho::d2::World::GetBodiesForProxies () const noexcept
Gets the bodies-for-proxies range for this world.
Provides insight on what bodies have been queued for proxy processing during the next call to the world step method.
See also
Step.
Todo:
Remove this function from this class - access from implementation instead.
GetBody()
const Body & playrho::d2::World::GetBody (BodyID id) const
Gets the state of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetBody, GetBodyRange.
Referenced by GetAnchorA(), GetAnchorB(), GetAngle(), GetAngularVelocity(), GetBody(), GetJointTranslation(), IsEnabled(), and SetAwake().
GetBodyRange()
BodyCounter playrho::d2::World::GetBodyRange () const noexcept
Gets the extent of the currently valid body range.
Note
This is one higher than the maxium BodyID that is in range for body related functions.
GetContact()
const Contact & playrho::d2::World::GetContact (ContactID id) const
Gets the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
SetContact, GetContactRange.
Referenced by GetContact(), GetDefaultFriction(), and GetDefaultRestitution().
GetContactRange()
ContactCounter playrho::d2::World::GetContactRange () const noexcept
Gets the extent of the currently valid contact range.
Note
This is one higher than the maxium ContactID that is in range for contact related functions.
GetContacts() [1/2]
World::Contacts playrho::d2::World::GetContacts () const
Gets the world contact range.
Warning
contacts are created and destroyed in the middle of a time step. Use ContactListener to avoid missing contacts.
Returns
World contacts sized-range.
GetContacts() [2/2]
const World::BodyContacts & playrho::d2::World::GetContacts (BodyID id) const
Gets the container of contacts attached to the identified body.
Warning
This collection changes during the time step and you may miss some collisions if you don't use ContactListener.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
GetBodyRange.
Referenced by GetContacts(), and GetTouchingCount().
GetInvDeltaTime()
Frequency playrho::d2::World::GetInvDeltaTime () const noexcept
Gets the inverse delta time.
Gets the inverse delta time that was set on construction or assignment, and updated on every call to the Step() method having a non-zero delta-time.
See also
Step.
Referenced by Step().
GetJoint()
const Joint & playrho::d2::World::GetJoint (JointID id) const
Gets the value of the identified joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
See also
SetJoint, GetJointRange.
Referenced by GetAnchorA(), GetAnchorB(), GetAngle(), GetAngularReaction(), GetBodyA(), GetBodyB(), GetCollideConnected(), GetJoint(), GetJointTranslation(), GetLinearReaction(), GetLocalAnchorA(), GetLocalAnchorB(), GetReferenceAngle(), GetType(), and SetAwake().
GetJointRange()
JointCounter playrho::d2::World::GetJointRange () const noexcept
Gets the extent of the currently valid joint range.
Note
This is one higher than the maxium JointID that is in range for joint related functions.
GetJoints() [1/2]
const World::Joints & playrho::d2::World::GetJoints () const noexcept
Gets the world joint range.
Gets a range enumerating the joints currently existing within this world. These are the joints that had been created from previous calls to the CreateJoint method that haven't yet been destroyed.
Returns
World joints sized-range.
See also
CreateJoint.
GetJoints() [2/2]
const World::BodyJoints & playrho::d2::World::GetJoints (BodyID id) const
Gets the range of joints attached to the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
CreateJoint, GetBodyRange.
Referenced by GetJoints().
GetManifold()
const Manifold & playrho::d2::World::GetManifold (ContactID id) const
Gets the collision manifold for the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
GetContact, GetContactRange.
Referenced by GetManifold().
GetMaxVertexRadius()
Length playrho::d2::World::GetMaxVertexRadius () const noexcept
Gets the maximum vertex radius that shapes in this world can be.
See also
GetMinVertexRadius.
Referenced by GetMaxVertexRadius().
GetMinVertexRadius()
Length playrho::d2::World::GetMinVertexRadius () const noexcept
Gets the minimum vertex radius that shapes in this world can be.
See also
GetMaxVertexRadius.
Referenced by GetMinVertexRadius().
GetShape()
const Shape & playrho::d2::World::GetShape (ShapeID id) const
Exceptions
std::out_of_range If given an invalid shape identifier.
See also
CreateShape.
Referenced by GetDefaultFriction(), GetDefaultRestitution(), and GetShape().
GetShapeRange()
ShapeCounter playrho::d2::World::GetShapeRange () const noexcept
Gets the extent of the currently valid shape range.
Note
This is one higher than the maxium ShapeID that is in range for shape related functions.
GetShapes()
const World::Shapes & playrho::d2::World::GetShapes (BodyID id) const
Gets the identities of the shapes associated with the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
GetBodyRange, CreateBody, SetBody.
Referenced by GetAssociationCount(), and GetShapes().
GetSubStepping()
bool playrho::d2::World::GetSubStepping () const noexcept
Gets whether or not sub-stepping is enabled.
See also
SetSubStepping, IsStepComplete.
Referenced by GetSubStepping().
GetTree()
const DynamicTree & playrho::d2::World::GetTree () const noexcept
Gets access to the broad-phase dynamic tree information.
Todo:
Consider removing this function. This function exposes the implementation detail of the broad-phase contact detection system.
Referenced by GetTree().
IsStepComplete()
bool playrho::d2::World::IsStepComplete () const noexcept
Whether or not "step" is complete.
The "step" is completed when there are no more TOI events for the current time step.
Returns
true unless sub-stepping is enabled and the step method returned without finishing all of its sub-steps.
See also
GetSubStepping, SetSubStepping.
operator=() [1/2]
World & playrho::d2::World::operator= (const World & other)
Copy assignment operator.
Copy assigns this world with a deep copy of the given world.
operator=() [2/2]
World & playrho::d2::World::operator= (World && other) default noexcept
Move assignment operator.
Move assigns this world.
Postcondition
this is what other used to be.
other is in a "valid but unspecified state". The only thing it can be used for, is as the destination of an assignment.
SetBody()
void playrho::d2::World::SetBody (BodyID id, const Body & value)
Sets the state of the identified body.
Exceptions
std::out_of_range if given an invalid id of if the given body references any invalid shape identifiers.
InvalidArgument if the specified ID was destroyed.
See also
GetBody, GetBodyRange.
Referenced by SetAngularDamping(), SetAwake(), SetBody(), SetEnabled(), SetFixedRotation(), SetImpenetrable(), SetLinearDamping(), SetMassData(), SetSleepingAllowed(), SetType(), SetVelocity(), UnsetAwake(), and UnsetImpenetrable().
SetContact()
void playrho::d2::World::SetContact (ContactID id, const Contact & value)
Sets the identified contact's state.
Note
This may throw an exception or update associated entities to preserve invariants.
Invariant
A contact may only be impenetrable if one or both bodies are.
A contact may only be active if one or both bodies are awake.
A contact may only be a sensor or one or both shapes are.
Exceptions
std::out_of_range If given an invalid contact identifier.
InvalidArgument if a change would violate an invariant or if the specified ID was destroyed.
See also
GetContact, GetContactRange.
Referenced by SetContact().
SetJoint()
void playrho::d2::World::SetJoint (JointID id, const Joint & def)
Sets the identified joint to the given value.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid joint identifier.
InvalidArgument if the specified ID was destroyed.
See also
GetJoint, GetJointRange.
Referenced by SetJoint().
SetJointDestructionListener()
void playrho::d2::World::SetJointDestructionListener (JointListener listener) noexcept
Registers a destruction listener for joints.
Note
This listener is called on Clear() for every joint. It's also called on Destroy(BodyID) for every joint associated with the identified body.
See also
Clear, Destroy(BodyID).
Referenced by SetJointDestructionListener().
SetShape()
void playrho::d2::World::SetShape (ShapeID id, const Shape & def)
Sets the identified shape to the new value.
Exceptions
std::out_of_range If given an invalid shape identifier.
InvalidArgument if the specified ID was destroyed.
See also
CreateShape.
Referenced by SetShape().
SetShapeDestructionListener()
void playrho::d2::World::SetShapeDestructionListener (ShapeListener listener) noexcept
Registers a destruction listener for shapes.
Note
This listener is called on Clear() for every shape.
See also
Clear.
Referenced by SetShapeDestructionListener().
SetSubStepping()
void playrho::d2::World::SetSubStepping (bool flag) noexcept
Enables/disables single stepped continuous physics.
Note
This is not normally used. Enabling sub-stepping is meant for testing.
Postcondition
The GetSubStepping() method will return the value this method was called with.
See also
IsStepComplete, GetSubStepping.
Referenced by SetSubStepping().
ShiftOrigin()
void playrho::d2::World::ShiftOrigin (const Length2 & newOrigin)
Shifts the world origin.
Note
Useful for large worlds.
The body shift formula is: position -= newOrigin.
Postcondition
The "origin" of this world's bodies, joints, and the board-phase dynamic tree have been translated per the shift amount and direction.
Parameters
newOrigin the new origin with respect to the old origin
Exceptions
WrongState if this method is called while the world is locked.
Referenced by ShiftOrigin().
Step()
StepStats playrho::d2::World::Step (const StepConf & conf = StepConf{})
Steps the world simulation according to the given configuration.
Performs position and velocity updating, sleeping of non-moving bodies, updating of the contacts, and notifying the contact listener of begin-contact, end-contact, pre-solve, and post-solve events.
Warning
Behavior is not specified if given a negative step time delta.
Varying the step time delta may lead to non-physical behaviors.
Note
Calling this with a zero step time delta results only in fixtures and bodies registered for special handling being processed. No physics is performed.
If the given velocity and position iterations are zero, this method doesn't do velocity or position resolutions respectively of the contacting bodies.
While body velocities are updated accordingly (per the sum of forces acting on them), body positions (barring any collisions) are updated as if they had moved the entire time step at those resulting velocities. In other words, a body initially at position 0 (p0) going velocity 0 (v0) fast with a sum acceleration of a, after time t and barring any collisions, will have a new velocity (v1) of v0 + (a * t) and a new position (p1) of p0 + v1 * t.
Postcondition
Static bodies are unmoved.
Kinetic bodies are moved based on their previous velocities.
Dynamic bodies are moved based on their previous velocities, gravity, applied forces, applied impulses, masses, damping, and the restitution and friction values of their fixtures when they experience collisions.
Parameters
conf Configuration for the simulation step.
Returns
Statistics for the step.
Exceptions
WrongState if this method is called while the world is locked.
Referenced by Step().
Friends And Related Function Documentation
ApplyAngularImpulse()
void ApplyAngularImpulse (World & world, BodyID id, AngularMomentum impulse) related
Applies an angular impulse.
Parameters
world The world in which the identified body exists.
id Identifier of body to apply the angular impulse to.
impulse Angular impulse to be applied.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
ApplyForce()
void ApplyForce (World & world, BodyID id, const Force2 & force, const Length2 & point) related
Apply a force at a world point.
Note
If the force is not applied at the center of mass, it will generate a torque and affect the angular velocity.
Non-zero forces wakes up the body.
Parameters
world World in which body exists.
id Identity of body to apply the force to.
force World force vector.
point World position of the point of application.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
ApplyForceToCenter()
void ApplyForceToCenter (World & world, BodyID id, const Force2 & force) related
Applies a force to the center of mass of the given body.
Note
Non-zero forces wakes up the body.
Parameters
world The world in which the identified body exists.
id Identifier of body to apply the force to.
force World force vector.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
ApplyLinearImpulse()
void ApplyLinearImpulse (World & world, BodyID id, const Momentum2 & impulse, const Length2 & point) related
Applies an impulse at a point.
Note
This immediately modifies the velocity.
This also modifies the angular velocity if the point of application is not at the center of mass.
Non-zero impulses wakes up the body.
Parameters
world The world in which the identified body exists.
id Identifier of body to apply the impulse to.
impulse the world impulse vector.
point the world position of the point of application.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
ApplyTorque()
void ApplyTorque (World & world, BodyID id, Torque torque) related
Applies a torque.
Note
This affects the angular velocity without affecting the linear velocity of the center of mass.
Non-zero forces wakes up the body.
Parameters
world The world in which the identified body exists.
id Identifier of body to apply the torque to.
torque about the z-axis (out of the screen).
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
Attach() [1/2]
void Attach (World & world, BodyID id, const Shape & shape, bool resetMassData = true) related
Creates the shape within the world and then associates it with the validly identified body.
Exceptions
std::out_of_range If given an invalid body.
WrongState if this method is called while the world is locked.
See also
GetShapes, ResetMassData.
Attach() [2/2]
void Attach (World & world, BodyID id, ShapeID shapeID, bool resetMassData = true) related
Associates a validly identified shape with the validly identified body.
Note
This function should not be called if the world is locked.
Exceptions
std::out_of_range If given an invalid body or shape identifier.
WrongState if this method is called while the world is locked.
See also
GetShapes, ResetMassData.
Examples
World.cpp.
Awaken() [1/2]
BodyCounter Awaken (World & world) related
Awakens all of the bodies in the given world.
Calls all of the world's bodies' SetAwake method.
Returns
Sum total of calls to bodies' SetAwake method that returned true.
Awaken() [2/2]
bool Awaken (World & world, BodyID id) related
Awakens the body if it's asleep.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
CalcGravitationalAcceleration()
Acceleration CalcGravitationalAcceleration (const World & world, BodyID id) related
Calculates the gravitationally associated acceleration for the given body within its world.
Returns
Zero acceleration if given body is has no mass, else the acceleration of the body due to the gravitational attraction to the other bodies.
Exceptions
std::out_of_range If given an invalid body identifier.
Clear()
void Clear (World & world) related
Clears this world.
Note
This calls the joint and fixture destruction listeners (if they're set) before clearing anything.
Postcondition
The contents of this world have all been destroyed and this world's internal state is reset as though it had just been constructed.
ClearForces()
void ClearForces (World & world) related
Clears forces.
Manually clear the force buffer on all bodies.
Exceptions
WrongState if this function is called while the world is locked.
ComputeIntersectingAABB()
AABB ComputeIntersectingAABB (const World & world, BodyID bA, ShapeID sA, ChildCounter iA, BodyID bB, ShapeID sB, ChildCounter iB) related
Computes the intersecting AABB for the given pair of body-shape-index values.
The intersecting AABB for the given pair of body-shape-index values is the intersection of the AABB for child A of shape A of body A with the AABB for child B of shape B of body B.
ComputeMassData() [1/2]
MassData ComputeMassData (const World & world, BodyID id) related
Computes the identified body's mass data.
This basically accumulates the mass data over all fixtures.
Note
The center is the mass weighted sum of all fixture centers. Divide it by the mass to get the averaged center.
Returns
accumulated mass data for all fixtures associated with the given body.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
ComputeMassData() [2/2]
MassData ComputeMassData (const World & world, const Span< const ShapeID > & ids) related
Computes the mass data total of the identified shapes.
This basically accumulates the mass data over all shapes.
Note
The center is the mass weighted sum of all shape centers. Divide it by the mass to get the averaged center.
Returns
accumulated mass data for all shapes identified.
Exceptions
std::out_of_range If given an invalid shape identifier.
CreateBody() [1/2]
BodyID CreateBody (World & world, const Body & body = Body{}, bool resetMassData = true) related
Creates a rigid body within the world that's a copy of the given one.
Warning
This function should not be used while the world is locked — as it is during callbacks. If it is, it will throw an exception or abort your program.
Note
No references to the configuration are retained. Its value is copied.
Postcondition
The created body will be present in the range returned from the GetBodies(const World&) method.
Parameters
world The world within which to create the body.
body A customized body or its default value that is to be copied into the world.
resetMassData Whether or not the mass data of the body should be reset.
Returns
Identifier of the newly created body which can later be destroyed by calling the Destroy(World&, BodyID) method.
Exceptions
WrongState if this method is called while the world is locked.
LengthError if this operation would create more than MaxBodies.
See also
Destroy(World& world, BodyID), GetBodies(const World&), ResetMassData.
Physical Entities.
Examples
World.cpp.
CreateBody() [2/2]
BodyID CreateBody (World & world, const BodyConf & def, bool resetMassData = true) related
Creates a rigid body with the given configuration.
Warning
This function should not be used while the world is locked — as it is during callbacks. If it is, it will throw an exception or abort your program.
Note
No references to the configuration are retained. Its value is copied.
Postcondition
The created body will be present in the range returned from the GetBodies(const World&) method.
Parameters
world The world within which to create the body.
def A customized body configuration or its default value.
resetMassData Whether or not the mass data of the body should be reset.
Returns
Identifier of the newly created body which can later be destroyed by calling the Destroy(World&, BodyID) method.
Exceptions
WrongState if this method is called while the world is locked.
LengthError if this operation would create more than MaxBodies.
See also
Destroy(World& world, BodyID), GetBodies(const World&), ResetMassData.
Physical Entities.
CreateJoint() [1/2]
JointID CreateJoint (World & world, const Joint & def) related
Creates a new joint within the given world.
Exceptions
WrongState if this method is called while the world is locked.
CreateJoint() [2/2]
template<typename T > JointID CreateJoint (World & world, const T & value) related
Creates a new joint from a configuration.
This is a convenience function for allowing limited implicit conversions to joints.
Exceptions
WrongState if this method is called while the world is locked.
CreateShape() [1/2]
ShapeID CreateShape (World & world, const Shape & def) related
Creates a shape within the specified world.
Exceptions
WrongState if called while the world is "locked".
CreateShape() [2/2]
template<typename T > auto CreateShape (World & world, const T & shapeConf) -> decltype(CreateShape(world, Shape{shapeConf})) related
Creates a shape within the specified world using a configuration of the shape.
This is a convenience function for allowing limited implicit conversions to shapes.
Exceptions
WrongState if called while the world is "locked".
See also
CreateShape(World& world, const Shape& def).
Destroy() [1/3]
void Destroy (World & world, BodyID id) related
Destroys the identified body.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid body identifier.
See also
CreateBody(World&, const BodyConf&).
Examples
World.cpp.
Destroy() [2/3]
void Destroy (World & world, JointID id) related
Destroys the identified joint.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid joint identifier.
Destroy() [3/3]
void Destroy (World & world, ShapeID id) related
Destroys the identified shape.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid identifier.
Detach() [1/2]
bool Detach (World & world, BodyID id, bool resetMassData = true) related
Disassociates all of the associated shape from the validly identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
WrongState if this method is called while the world is locked.
See also
Attach, ResetMassData.
Detach() [2/2]
bool Detach (World & world, BodyID id, ShapeID shapeID, bool resetMassData = true) related
Disassociates a validly identified shape from the validly identified body.
Exceptions
std::out_of_range If given an invalid body or shape identifier.
WrongState if this method is called while the world is locked.
See also
ResetMassData.
Examples
World.cpp.
EnableLimit()
void EnableLimit (World & world, JointID id, bool value) related
Sets whether the identified joint's limit is enabled or not.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid joint identifier.
EnableMotor()
void EnableMotor (World & world, JointID id, bool value) related
Enable/disable the joint motor.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid joint identifier.
GetAcceleration()
Acceleration GetAcceleration (const World & world, BodyID id) related
Gets the acceleration of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetAcceleration(World&, BodyID, LinearAcceleration2, AngularAcceleration).
GetAnchorA()
Length2 GetAnchorA (const World & world, JointID id) related
Get the anchor point on body-A in world coordinates.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAnchorB()
Length2 GetAnchorB (const World & world, JointID id) related
Get the anchor point on body-B in world coordinates.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngle() [1/2]
Angle GetAngle (const World & world, BodyID id) related
Gets the angle of the identified body.
Returns
the current world rotation angle.
Exceptions
std::out_of_range If given an invalid body identifier.
GetAngle() [2/2]
Angle GetAngle (const World & world, JointID id) related
Gets the angle property of the identified joint if it has it.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularAcceleration()
AngularAcceleration GetAngularAcceleration (const World & world, BodyID id) related
Gets this body's angular acceleration.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
GetAcceleration(const World& world, BodyID id).
GetAngularDamping()
Frequency GetAngularDamping (const World & world, BodyID id) related
Gets the angular damping of the body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetAngularLowerLimit()
Angle GetAngularLowerLimit (const World & world, JointID id) related
Get the lower joint limit.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularMass()
RotInertia GetAngularMass (const World & world, JointID id) related
Gets the computed angular rotational inertia used by the joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularMotorImpulse()
AngularMomentum GetAngularMotorImpulse (const World & world, JointID id) related
Gets the angular motor impulse of the identified joint if it has this property.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularOffset()
Angle GetAngularOffset (const World & world, JointID id) related
Gets the target angular offset.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularReaction()
AngularMomentum GetAngularReaction (const World & world, JointID id) related
Get the angular reaction on body-B for the identified joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularUpperLimit()
Angle GetAngularUpperLimit (const World & world, JointID id) related
Get the upper joint limit.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetAngularVelocity() [1/2]
AngularVelocity GetAngularVelocity (const World & world, BodyID id) related
Gets the angular velocity.
Parameters
world World in which body is identified for.
id Identifier of body to get the angular velocity for.
Returns
the angular velocity.
Exceptions
std::out_of_range If given an invalid body identifier.
GetAngularVelocity() [2/2]
AngularVelocity GetAngularVelocity (const World & world, JointID id) related
Gets the angular velocity of the identified joint if it has this property.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetBody()
const Body & GetBody (const World & world, BodyID id) related
Gets the body configuration for the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
CreateBody(World& world, const BodyConf&), SetBody(World& world, BodyID id, const Body& body).
GetBodyA() [1/2]
BodyID GetBodyA (const World & world, ContactID id) related
Gets the body-A of the identified contact if it has one.
Returns
Identification of the body-A or InvalidBodyID.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetBodyA() [2/2]
BodyID GetBodyA (const World & world, JointID id) related
Gets the identifier of body-A of the identified joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetBodyB() [1/2]
BodyID GetBodyB (const World & world, ContactID id) related
Gets the body-B of the identified contact if it has one.
Returns
Identification of the body-B or InvalidBodyID.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetBodyB() [2/2]
BodyID GetBodyB (const World & world, JointID id) related
Gets the identifier of body-B of the identified joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetBodyCount()
BodyCounter GetBodyCount (const World & world) related
Gets the body count in the given world.
Returns
0 or higher.
Examples
World.cpp.
GetBodyRange()
BodyCounter GetBodyRange (const World & world) related
Gets the extent of the currently valid body range.
Note
This is one higher than the maxium BodyID that is in range for body related functions.
GetCentripetalForce()
Force2 GetCentripetalForce (const World & world, BodyID id, const Length2 & axis) related
Gets the centripetal force necessary to put the body into an orbit having the given radius.
Exceptions
std::out_of_range If given an invalid body identifier.
GetChildIndexA()
ChildCounter GetChildIndexA (const World & world, ContactID id) related
Gets the child primitive index A for the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetChildIndexB()
ChildCounter GetChildIndexB (const World & world, ContactID id) related
Gets the child primitive index B for the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetCollideConnected()
bool GetCollideConnected (const World & world, JointID id) related
Gets collide connected for the specified joint.
Note
Modifying the collide connect flag won't work correctly because the flag is only checked when fixture AABBs begin to overlap.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetContact()
const Contact & GetContact (const World & world, ContactID id) related
Gets the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetContactCount()
ContactCounter GetContactCount (const World & world) related
Gets the count of contacts in the given world.
Note
Not all contacts are for shapes that are actually touching. Some contacts are for shapes which merely have overlapping AABBs.
Returns
0 or higher.
GetContactRange()
ContactCounter GetContactRange (const World & world) related
Gets the extent of the currently valid contact range.
Note
This is one higher than the maxium ContactID that is in range for contact related functions.
GetContacts()
const std::vector< std::tuple< ContactKey, ContactID > > & GetContacts (const World & world, BodyID id) related
Gets the container of all contacts attached to the identified body.
Warning
This collection changes during the time step and you may miss some collisions if you don't use ContactListener.
Exceptions
std::out_of_range If given an invalid body identifier.
Examples
World.cpp.
GetCurrentLengthA()
Length GetCurrentLengthA (const World & world, JointID id) related
Get the current length of the segment attached to body-A.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetCurrentLengthB()
Length GetCurrentLengthB (const World & world, JointID id) related
Get the current length of the segment attached to body-B.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetDampingRatio()
Real GetDampingRatio (const World & world, JointID id) related
Gets the damping ratio associated with the identified joint if it has one.
Exceptions
std::out_of_range If given an invalid joint identifier.
std::invalid_argument If the identified joint's type doesn't support this.
GetDefaultFriction()
Real GetDefaultFriction (const World & world, ContactID id) related
Gets the default friction amount for the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
SetFriction.
GetDefaultRestitution()
Real GetDefaultRestitution (const World & world, ContactID id) related
Gets the default restitution amount for the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
SetRestitution.
GetDensity()
NonNegative< AreaDensity > GetDensity (const World & world, ShapeID id) related
Gets the density of this shape.
Returns
Non-negative density (in mass per area).
Exceptions
std::out_of_range If given an invalid identifier.
GetFilterData()
Filter GetFilterData (const World & world, ShapeID id) related
Gets the filter data for the identified shape.
Exceptions
std::out_of_range If given an invalid identifier.
See also
SetFilterData.
Examples
World.cpp.
GetFrequency()
Frequency GetFrequency (const World & world, JointID id) related
Gets the frequency of the identified joint if it has this property.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetFriction() [1/2]
NonNegativeFF< Real > GetFriction (const World & world, ContactID id) related
Gets the friction used with the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
SetFriction.
GetFriction() [2/2]
NonNegativeFF< Real > GetFriction (const World & world, ShapeID id) related
Gets the coefficient of friction of the specified shape.
Returns
Value of 0 or higher.
Exceptions
std::out_of_range If given an invalid identifier.
GetGroundAnchorA()
Length2 GetGroundAnchorA (const World & world, JointID id) related
Get the first ground anchor.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetGroundAnchorB()
Length2 GetGroundAnchorB (const World & world, JointID id) related
Get the second ground anchor.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetInvMass()
InvMass GetInvMass (const World & world, BodyID id) related
Gets the inverse total mass of the body.
Returns
Value of zero or more representing the body's inverse mass (in 1/kg).
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetMassData.
GetInvRotInertia()
InvRotInertia GetInvRotInertia (const World & world, BodyID id) related
Gets the inverse rotational inertia of the body.
Returns
Inverse rotational inertia (in 1/kg-m^2).
Exceptions
std::out_of_range If given an invalid body identifier.
GetJoint()
const Joint & GetJoint (const World & world, JointID id) related
Gets the value of the identified joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetJointCount()
JointCounter GetJointCount (const World & world) related
Gets the count of joints in the given world.
Returns
0 or higher.
GetJointRange()
JointCounter GetJointRange (const World & world) related
Gets the extent of the currently valid joint range.
Note
This is one higher than the maxium JointID that is in range for joint related functions.
GetJoints()
const std::vector< std::pair< BodyID, JointID > > & GetJoints (const World & world, BodyID id) related
Gets the range of all joints attached to the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetJointTranslation()
Length GetJointTranslation (const World & world, JointID id) related
Gets the current joint translation.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLength()
Length GetLength (const World & world, JointID id) related
Gets the length associated with the identified joint if it has one.
Exceptions
std::out_of_range If given an invalid joint identifier.
std::invalid_argument If the identified joint's type doesn't support this.
GetLimitState()
LimitState GetLimitState (const World & world, JointID id) related
Gets the joint's limit state if it has one.
Exceptions
std::out_of_range If given an invalid joint identifier.
std::invalid_argument If the identified joint's type doesn't support this.
GetLinearAcceleration()
LinearAcceleration2 GetLinearAcceleration (const World & world, BodyID id) related
Gets this body's linear acceleration.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
GetAcceleration(const World& world, BodyID id).
GetLinearDamping()
Frequency GetLinearDamping (const World & world, BodyID id) related
Gets the linear damping of the body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetLinearMotorImpulse()
Momentum GetLinearMotorImpulse (const World & world, JointID id) related
Gets the linear motor impulse of the identified joint if it supports that.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLinearOffset()
Length2 GetLinearOffset (const World & world, JointID id) related
Gets the target linear offset, in frame A.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLinearReaction()
Momentum2 GetLinearReaction (const World & world, JointID id) related
Gets the linear reaction on body-B at the joint anchor.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLinearVelocity()
LinearVelocity2 GetLinearVelocity (const World & world, BodyID id) related
Gets the linear velocity of the center of mass of the identified body.
Parameters
world World in which body is identified for.
id Identifier of body to get the linear velocity for.
Returns
the linear velocity of the center of mass.
Exceptions
std::out_of_range If given an invalid body identifier.
GetLocalAnchorA()
Length2 GetLocalAnchorA (const World & world, JointID id) related
Get the anchor point on body-A in local coordinates.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLocalAnchorB()
Length2 GetLocalAnchorB (const World & world, JointID id) related
Get the anchor point on body-B in local coordinates.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLocalCenter()
Length2 GetLocalCenter (const World & world, BodyID id) related
Gets the local position of the center of mass of the specified body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetLocalPoint()
Length2 GetLocalPoint (const World & world, BodyID id, const Length2 & worldPoint) related
Gets a local point relative to the body's origin given a world point.
Parameters
world The world in which the identified body exists.
id Identifier of body that the returned point should be relative to.
worldPoint point in world coordinates.
Returns
the corresponding local point relative to the body's origin.
Exceptions
std::out_of_range If given an invalid body identifier.
GetLocalRotInertia()
RotInertia GetLocalRotInertia (const World & world, BodyID id) related
Gets the rotational inertia of the body about the local origin.
Returns
the rotational inertia.
Exceptions
std::out_of_range If given an invalid body identifier.
GetLocalVector()
UnitVec GetLocalVector (const World & world, BodyID body, const UnitVec & uv) related
Convenience function for getting the local vector of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetLocalXAxisA()
UnitVec GetLocalXAxisA (const World & world, JointID id) related
Gets the local-X-axis-A property of the identified joint if it has it.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLocalYAxisA()
UnitVec GetLocalYAxisA (const World & world, JointID id) related
Gets the local-Y-axis-A property of the identified joint if it has it.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetLocation()
Length2 GetLocation (const World & world, BodyID id) related
Convenience function for getting just the location of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
GetTransformation(const World& world, BodyID id).
GetManifold()
const Manifold & GetManifold (const World & world, ContactID id) related
Gets the manifold for the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
Examples
World.cpp.
GetMass()
Mass GetMass (const World & world, BodyID id) related
Gets the mass of the body.
Note
This may be the total calculated mass or it may be the set mass of the body.
Returns
Value of zero or more representing the body's mass.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
GetInvMass, SetMassData
GetMassData() [1/2]
MassData GetMassData (const World & world, BodyID id) related
Gets the mass data of the body.
Returns
Data structure containing the mass, inertia, and center of the body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetMassData() [2/2]
MassData GetMassData (const World & world, ShapeID id) related
Gets the mass data for the identified shape in the given world.
Exceptions
std::out_of_range If given an invalid identifier.
GetMaxMotorTorque()
Torque GetMaxMotorTorque (const World & world, JointID id) related
Gets the max motor torque.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetMotorForce()
Force GetMotorForce (const World & world, JointID id, Frequency inv_dt) related
Gets the current motor force for the given joint, given the inverse time step.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetMotorSpeed()
AngularVelocity GetMotorSpeed (const World & world, JointID id) related
Gets the motor-speed property of the identied joint if it supports it.
Exceptions
std::out_of_range If given an invalid joint identifier.
See also
SetMotorSpeed(World& world, JointID id, AngularVelocity value)
GetMotorTorque()
Torque GetMotorTorque (const World & world, JointID id, Frequency inv_dt) related
Gets the current motor torque for the given joint given the inverse time step.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetRatio()
Real GetRatio (const World & world, JointID id) related
Gets the ratio property of the identified joint if it has it.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetReferenceAngle()
Angle GetReferenceAngle (const World & world, JointID id) related
Gets the reference-angle property of the identified joint if it has it.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetRestitution() [1/2]
Real GetRestitution (const World & world, ContactID id) related
Gets the restitution used with the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
SetRestitution(World& world, ContactID id, Real restitution)
GetRestitution() [2/2]
Real GetRestitution (const World & world, ShapeID id) related
Gets the coefficient of restitution of the specified shape.
Exceptions
std::out_of_range If given an invalid identifier.
GetRotInertia()
RotInertia GetRotInertia (const World & world, BodyID id) related
Gets the rotational inertia of the body.
Parameters
world The world in which the identified body exists.
id Identifier of body to get the rotational inertia for.
Returns
the rotational inertia.
Exceptions
std::out_of_range If given an invalid body identifier.
GetShape()
const Shape & GetShape (const World & world, ShapeID id) related
Gets the shape associated with the identifier.
Exceptions
std::out_of_range If given an invalid identifier.
GetShapeA()
ShapeID GetShapeA (const World & world, ContactID id) related
Gets shape A of the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetShapeB()
ShapeID GetShapeB (const World & world, ContactID id) related
Gets shape B of the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetShapeCount()
ShapeCounter GetShapeCount (const World & world, BodyID id) related
Gets the count of shapes associated with the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
GetShapes(const World& world, BodyID id).
GetShapeRange()
ShapeCounter GetShapeRange (const World & world) related
Gets the extent of the currently valid shape range.
Note
This is one higher than the maxium ShapeID that is in range for shape related functions.
GetShapes()
const std::vector< ShapeID > & GetShapes (const World & world, BodyID id) related
Gets the identities of the shapes associated with the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
Attach, Detach.
GetSubStepping()
bool GetSubStepping (const World & world) related
Gets whether or not sub-stepping is enabled.
See also
SetSubStepping, IsStepComplete.
GetTangentSpeed()
LinearVelocity GetTangentSpeed (const World & world, ContactID id) related
Gets the tangent speed of the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetTarget()
Length2 GetTarget (const World & world, JointID id) related
Gets the target point.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetToi()
std::optional< UnitInterval< Real > > GetToi (const World & world, ContactID id) related
Gets the time of impact (TOI) as a fraction or empty value.
Returns
Time of impact fraction in the range of 0 to 1 if set (where 1 means no actual impact in current time slot), otherwise empty.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
HasValidToi.
GetToiCount()
TimestepIters GetToiCount (const World & world, ContactID id) related
Gets the Time Of Impact (TOI) count.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetTransformation()
Transformation GetTransformation (const World & world, BodyID id) related
Gets the body's transformation.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetTransformation(World& world, BodyID id, Transformation xfm).
GetType() [1/3]
BodyType GetType (const World & world, BodyID id) related
Gets the type of the identified body.
See also
SetType(World& world, BodyID id, BodyType value)
GetType() [2/3]
TypeID GetType (const World & world, JointID id) related
Gets the type of the joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetType() [3/3]
TypeID GetType (const World & world, ShapeID id) related
Gets the type of the shape.
Exceptions
std::out_of_range If given an invalid identifier.
GetVelocity()
Velocity GetVelocity (const World & world, BodyID id) related
Gets the velocity of the identified body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetVelocity(World& world, BodyID id, const Velocity& value).
GetWorldCenter()
Length2 GetWorldCenter (const World & world, BodyID id) related
Get the world position of the center of mass of the specified body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetWorldIndex() [1/2]
BodyCounter GetWorldIndex (const World & , BodyID id) related
Gets the world index for the given body.
Exceptions
std::out_of_range If given an invalid body identifier.
GetWorldIndex() [2/2]
JointCounter GetWorldIndex (const World & , JointID id) related
Gets the world index of the given joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
GetWorldManifold()
WorldManifold GetWorldManifold (const World & world, ContactID id) related
Gets the world manifold for the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
GetWorldPoint()
Length2 GetWorldPoint (const World & world, BodyID id, const Length2 & localPoint) related
Gets the world coordinates of a point given in coordinates relative to the body's origin.
Parameters
world World context.
id Identifier of body that the given point is relative to.
localPoint a point measured relative the the body's origin.
Returns
the same point expressed in world coordinates.
Exceptions
std::out_of_range If given an invalid body identifier.
HasValidToi()
bool HasValidToi (const World & world, ContactID id) related
Whether or not the contact has a valid TOI.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
GetToi.
IsAccelerable()
bool IsAccelerable (const World & world, BodyID id) related
Is identified body "accelerable"?
Indicates whether the body is accelerable, i.e. whether it is effected by forces. Only Dynamic bodies are accelerable.
Returns
true if the body is accelerable, false otherwise.
Exceptions
std::out_of_range If given an invalid body identifier.
IsAwake() [1/2]
bool IsAwake (const World & world, BodyID id) related
Gets the awake/asleep state of this body.
Warning
Being awake may or may not imply being speedable.
Returns
true if the body is awake.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetAwake(World& world, BodyID id), UnsetAwake(BodyID id).
IsAwake() [2/2]
bool IsAwake (const World & world, ContactID id) related
Gets the awake status of the specified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
SetAwake.
IsEnabled() [1/3]
bool IsEnabled (const World & world, BodyID id) related
Gets the enabled/disabled state of the body.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetEnabled.
IsEnabled() [2/3]
bool IsEnabled (const World & world, ContactID id) related
Gets the enabled status of the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
IsEnabled() [3/3]
bool IsEnabled (const World & world, JointID id) related
Gets the enabled/disabled state of the joint.
Exceptions
std::out_of_range If given an invalid joint identifier.
IsFixedRotation()
bool IsFixedRotation (const World & world, BodyID id) related
Gets whether the body has fixed rotation.
Exceptions
std::out_of_range If given an invalid body identifier.
See also
SetFixedRotation.
IsImpenetrable()
bool IsImpenetrable (const World & world, BodyID id) related
Is the body treated like a bullet for continuous collision detection?
Exceptions
std::out_of_range If given an invalid body identifier.
IsLimitEnabled()
bool IsLimitEnabled (const World & world, JointID id) related
Gets whether the identified joint's limit is enabled.
Exceptions
std::out_of_range If given an invalid joint identifier.
IsMassDataDirty()
bool IsMassDataDirty (const World & world, BodyID id) related
Gets whether the body's mass-data is dirty.
Exceptions
std::out_of_range If given an invalid body identifier.
IsMotorEnabled()
bool IsMotorEnabled (const World & world, JointID id) related
Is the joint motor enabled?
Exceptions
std::out_of_range If given an invalid joint identifier.
See also
EnableMotor(World& world, JointID joint, bool value)
IsSensor()
bool IsSensor (const World & world, ShapeID id) related
Is the specified shape a sensor (non-solid)?
Returns
the true if the shape is a sensor.
Exceptions
std::out_of_range If given an invalid identifier.
See also
SetSensor.
IsSleepingAllowed()
bool IsSleepingAllowed (const World & world, BodyID id) related
Gets whether the identified body is allowed to sleep.
Exceptions
std::out_of_range If given an invalid body identifier.
IsSpeedable()
bool IsSpeedable (const World & world, BodyID id) related
Is identified body "speedable".
Is the body able to have a non-zero speed associated with it. Kinematic and Dynamic bodies are speedable. Static bodies are not.
Exceptions
std::out_of_range If given an invalid body identifier.
IsTouching()
bool IsTouching (const World & world, ContactID id) related
Is this contact touching?
Touching is defined as either:
This contact's manifold has more than 0 contact points, or
This contact has sensors and the two shapes of this contact are found to be overlapping.
Returns
true if this contact is said to be touching, false otherwise.
Exceptions
std::out_of_range If given an invalid contact identifier.
NeedsFiltering()
bool NeedsFiltering (const World & world, ContactID id) related
Whether or not the contact needs filtering.
Exceptions
std::out_of_range If given an invalid contact identifier.
NeedsUpdating()
bool NeedsUpdating (const World & world, ContactID id) related
Whether or not the contact needs updating.
Exceptions
std::out_of_range If given an invalid contact identifier.
ResetFriction()
void ResetFriction (World & world, ContactID id) related
Resets the friction mixture to the default value.
Exceptions
std::out_of_range If given an invalid contact identifier.
ResetMassData()
void ResetMassData (World & world, BodyID id) related
Resets the mass data properties.
This resets the mass data to the sum of the mass properties of the fixtures.
Note
This method must be called after associating new shapes to the body to update the body mass data properties unless SetMassData is used.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
See also
SetMassData, Attach, Detach.
ResetRestitution()
void ResetRestitution (World & world, ContactID id) related
Resets the restitution to the default value.
Exceptions
std::out_of_range If given an invalid contact identifier.
Rotate()
void Rotate (World & world, ShapeID id, const UnitVec & value) related
Rotates all of the given shape's vertices by the given amount.
Note
This may throw std::bad_alloc or any exception that's thrown by the constructor for the model's underlying data type.
Exceptions
std::bad_alloc if there's a failure allocating storage.
std::out_of_range If given an invalid identifier.
RotateAboutLocalPoint()
void RotateAboutLocalPoint (World & world, BodyID id, Angle amount, const Length2 & localPoint) related
Rotates a body a given amount around a point in body local coordinates.
This changes both the linear and angular positions of the body.
Note
Manipulating a body's position this way may cause non-physical behavior.
This is a convenience function that translates the local point into world coordinates and then calls the RotateAboutWorldPoint function.
Parameters
world The world in which the identified body exists.
id Identifier of body to rotate.
amount Amount to rotate body by (in counter-clockwise direction).
localPoint Point in local coordinates.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
RotateAboutWorldPoint()
void RotateAboutWorldPoint (World & world, BodyID id, Angle amount, const Length2 & worldPoint) related
Rotates a body a given amount around a point in world coordinates.
This changes both the linear and angular positions of the body.
Note
Manipulating a body's position this way may cause non-physical behavior.
Parameters
world The world in which the identified body exists.
id Identifier of body to rotate.
amount Amount to rotate body by (in counter-clockwise direction).
worldPoint Point in world coordinates.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
Scale()
void Scale (World & world, ShapeID id, const Vec2 & value) related
Scales all of the given shape's vertices by the given amount.
Note
This may throw std::bad_alloc or any exception that's thrown by the constructor for the model's underlying data type.
Exceptions
std::bad_alloc if there's a failure allocating storage.
std::out_of_range If given an invalid identifier.
SetAcceleration() [1/4]
void SetAcceleration (World & world, BodyID id, AngularAcceleration value) related
Sets the rotational accelerations on the body.
Note
This has no effect on non-accelerable bodies.
A non-zero acceleration will also awaken the body.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
See also
GetAcceleration(const World& world, BodyID id).
SetAcceleration() [2/4]
void SetAcceleration (World & world, BodyID id, const Acceleration & value) related
Sets the accelerations on the given body.
Note
This has no effect on non-accelerable bodies.
A non-zero acceleration will also awaken the body.
Parameters
world The world in which the identified body's acceleration should be set.
id Identifier of body whose acceleration should be set.
value Acceleration value to set.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
See also
GetAcceleration(const World& world, BodyID id).
SetAcceleration() [3/4]
void SetAcceleration (World & world, BodyID id, const LinearAcceleration2 & linear, AngularAcceleration angular) related
Sets the linear and rotational accelerations on the body.
Note
This has no effect on non-accelerable bodies.
A non-zero acceleration will also awaken the body.
Parameters
world World in which it all happens.
id Identifier of body whose acceleration should be set.
linear Linear acceleration.
angular Angular acceleration.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
See also
GetAcceleration(const World& world, BodyID id).
SetAcceleration() [4/4]
void SetAcceleration (World & world, BodyID id, const LinearAcceleration2 & value) related
Sets the linear accelerations on the body.
Note
This has no effect on non-accelerable bodies.
A non-zero acceleration will also awaken the body.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
See also
GetAcceleration(const World& world, BodyID id).
SetAccelerations() [1/3]
void SetAccelerations (World & world, const Acceleration & acceleration) related
Sets the accelerations of all the world's bodies to the given value.
Exceptions
WrongState if this function is called while the world is locked.
SetAccelerations() [2/3]
void SetAccelerations (World & world, const LinearAcceleration2 & acceleration) related
Sets the accelerations of all the world's bodies to the given value.
Note
This will leave the angular acceleration alone.
Exceptions
WrongState if this function is called while the world is locked.
SetAccelerations() [3/3]
template<class F > void SetAccelerations (World & world, F fn) related
Sets the accelerations of all the world's bodies.
Parameters
world World instance to set the acceleration of all contained bodies for.
fn Function or functor with a signature like: Acceleration (*fn)(World&,BodyID).
Exceptions
WrongState if this function is called while the world is locked.
SetAngle()
void SetAngle (World & world, BodyID id, Angle value) related
Sets the body's angular orientation.
This instantly adjusts the body to be at the new angular orientation.
Warning
Manipulating a body's angle this way can cause non-physical behavior!
Parameters
world The world in which the identified body's angle should be set.
id Identifier of body to move.
value Valid world angle of the body's local origin.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
See also
GetAngle(const World& world, BodyID id).
SetAngularDamping()
void SetAngularDamping (World & world, BodyID id, NonNegative< Frequency > angularDamping) related
Sets the angular damping of the body.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
SetAngularLimits()
void SetAngularLimits (World & world, JointID id, Angle lower, Angle upper) related
Set the joint limits.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid joint identifier.
SetAngularOffset()
void SetAngularOffset (World & world, JointID id, Angle value) related
Sets the target angular offset.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid joint identifier.
SetAwake() [1/3]
void SetAwake (World & world, BodyID id) related
Wakes up the identified body.
Note
This wakes up any associated contacts that had been asleep.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
See also
IsAwake(const World& world, BodyID id), UnsetAwake(World& world, BodyID id).
SetAwake() [2/3]
void SetAwake (World & world, ContactID id) related
Sets awake the bodies of the given contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
SetAwake() [3/3]
void SetAwake (World & world, JointID id) related
Wakes up the joined bodies.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid joint identifier.
SetBody()
void SetBody (World & world, BodyID id, const Body & body) related
Sets the body state for the identified body.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid body identifier.
See also
GetBody(const World& world, BodyID id).
SetContact()
void SetContact (World & world, ContactID id, const Contact & value) related
Sets the identified contact's state.
Note
This may throw an exception or update associated entities to preserve invariants.
Invariant
A contact may only be impenetrable if one or both bodies are.
A contact may only be active if one or both bodies are awake.
A contact may only be a sensor or one or both shapes are.
Exceptions
std::out_of_range If given an invalid contact identifier.
SetDensity()
void SetDensity (World & world, ShapeID id, NonNegative< AreaDensity > value) related
Sets the density of this shape.
Exceptions
std::out_of_range If given an invalid identifier.
SetEnabled() [1/3]
void SetEnabled (World & world, BodyID id, bool value) related
Sets the enabled state of the body.
A disabled body is not simulated and cannot be collided with or woken up. If you pass a flag of true, all fixtures will be added to the broad-phase. If you pass a flag of false, all fixtures will be removed from the broad-phase and all contacts will be destroyed. Fixtures and joints are otherwise unaffected.
Note
A disabled body is still owned by a World object and remains in the world's body container.
You may continue to create/destroy fixtures and joints on disabled bodies.
Fixtures on a disabled body are implicitly disabled and will not participate in collisions, ray-casts, or queries.
Joints connected to a disabled body are implicitly disabled.
Exceptions
WrongState If call would change body's state when world is locked.
std::out_of_range If given an invalid body identifier.
Postcondition
IsEnabled() returns the state given to this function.
See also
IsEnabled.
SetEnabled() [2/3]
void SetEnabled (World & world, ContactID id) related
Sets the enabled status of the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
SetEnabled() [3/3]
void SetEnabled (World & world, ContactID id, bool value) related
Convenience function for setting/unsetting the enabled status of the identified contact based on the value parameter.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
IsEnabled(const World&, ContactID).
SetFilterData()
void SetFilterData (World & world, ShapeID id, const Filter & filter) related
Convenience function for setting the contact filtering data.
Note
This won't update contacts until the next time step when either parent body is speedable and awake.
This automatically refilters contacts.
Exceptions
std::out_of_range If given an invalid identifier.
See also
GetFilterData.
Examples
World.cpp.
SetFixedRotation()
void SetFixedRotation (World & world, BodyID id, bool value) related
Sets this body to have fixed rotation.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
Note
This also causess the mass data to be reset.
See also
IsFixedRotation.
SetForce()
void SetForce (World & world, BodyID id, const Force2 & force, const Length2 & point) related
Sets the given amount of force at the given point to the given body.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
SetFrequency()
void SetFrequency (World & world, JointID id, Frequency value) related
Sets the frequency of the identified joint if it has this property.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid joint identifier.
SetFriction() [1/2]
void SetFriction (World & world, ContactID id, NonNegative< Real > friction) related
Sets the friction value for the identified contact.
Note
Overrides the default friction mixture. You can call this in "pre-solve" listeners. This value persists until set or reset.
Parameters
world The world in which the contact is identified in.
id Identifier of the contact whose friction value should be set.
friction Co-efficient of friction value of zero or greater.
Precondition
friction must be greater-than or equal-to zero.
Postcondition
GetFriction(world, id) returns the value set.
Exceptions
std::out_of_range If given an invalid contact identifier.
See also
GetFriction(const World&, ContactID).
SetFriction() [2/2]
void SetFriction (World & world, ShapeID id, NonNegative< Real > value) related
Convenience function for setting the coefficient of friction of the specified shape.
Exceptions
std::out_of_range If given an invalid identifier.
See also
GetFriction.
SetImpenetrable() [1/2]
void SetImpenetrable (World & world, BodyID id) related
Sets the impenetrable status of the identified body.
Sets that the body should be treated like a bullet for continuous collision detection.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
SetImpenetrable() [2/2]
void SetImpenetrable (World & world, BodyID id, bool value) related
Convenience function that sets/unsets the impenetrable status of the identified body.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
SetJoint() [1/2]
void SetJoint (World & world, JointID id, const Joint & def) related
Sets the value of the identified joint.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid joint identifier.
SetJoint() [2/2]
template<typename T > void SetJoint (World & world, JointID id, const T & value) related
Sets a joint's value from a configuration.
This is a convenience function for allowing limited implicit conversions to joints.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid joint identifier.
SetLinearDamping()
void SetLinearDamping (World & world, BodyID id, NonNegative< Frequency > linearDamping) related
Sets the linear damping of the body.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
SetLinearOffset()
void SetLinearOffset (World & world, JointID id, const Length2 & value) related
Sets the target linear offset, in frame A.
Exceptions
std::out_of_range If given an invalid joint identifier.
SetLocation()
void SetLocation (World & world, BodyID id, const Length2 & value) related
Sets the body's location.
This instantly adjusts the body to be at the new location.
Warning
Manipulating a body's location this way can cause non-physical behavior!
Parameters
world The world in which the identified body's location should be set.
id Identifier of body to move.
value Valid world location of the body's local origin.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
See also
GetLocation(const World& world, BodyID id).
SetMassData()
void SetMassData (World & world, BodyID id, const MassData & massData) related
Sets the mass properties to override the mass properties of the fixtures.
Note
This changes the center of mass position.
Creating or destroying fixtures can also alter the mass.
This function has no effect if the body isn't dynamic.
Parameters
world The world in which the identified body exists.
id Identifier of the body.
massData the mass properties.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
SetMaxMotorTorque()
void SetMaxMotorTorque (World & world, JointID id, Torque value) related
Sets the maximum motor torque.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid joint identifier.
SetMotorSpeed()
void SetMotorSpeed (World & world, JointID id, AngularVelocity value) related
Sets the motor-speed property of the identied joint if it supports it.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid joint identifier.
See also
GetMotorSpeed(const World& world, JointID id)
SetRestitution() [1/2]
void SetRestitution (World & world, ContactID id, Real restitution) related
Sets the restitution value for the specified contact.
This override the default restitution mixture.
Note
You can call this in "pre-solve" listeners.
The value persists until you set or reset.
SetRestitution() [2/2]
void SetRestitution (World & world, ShapeID id, Real value) related
Sets the coefficient of restitution of the specified shape.
Exceptions
std::out_of_range If given an invalid identifier.
SetSensor()
void SetSensor (World & world, ShapeID id, bool value) related
Convenience function for setting whether the shape is a sensor or not.
Exceptions
std::out_of_range If given an invalid identifier.
See also
IsSensor.
SetShape()
void SetShape (World & world, ShapeID , const Shape & def) related
Sets the identified shape to the new value.
Exceptions
std::out_of_range If given an invalid shape identifier.
See also
CreateShape.
SetSleepingAllowed()
void SetSleepingAllowed (World & world, BodyID , bool value) related
Sets whether the identified body is allowed to sleep.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
SetSubStepping()
void SetSubStepping (World & world, bool flag) related
Enables/disables single stepped continuous physics.
Note
This is not normally used. Enabling sub-stepping is meant for testing.
Postcondition
The GetSubStepping() method will return the value this method was called with.
See also
IsStepComplete, GetSubStepping.
SetTangentSpeed()
void SetTangentSpeed (World & world, ContactID id, LinearVelocity value) related
Sets the desired tangent speed for a conveyor belt behavior.
Exceptions
std::out_of_range If given an invalid contact identifier.
SetTarget()
void SetTarget (World & world, JointID id, const Length2 & value) related
Sets the target point.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid joint identifier.
SetTorque()
void SetTorque (World & world, BodyID id, Torque torque) related
Sets the given amount of torque to the given body.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
SetTransform()
void SetTransform (World & world, BodyID id, const Length2 & location, Angle angle) related
Sets the position of the body's origin and rotation.
This instantly adjusts the body to be at the new position and new orientation.
Warning
Manipulating a body's transform can cause non-physical behavior!
Note
Contacts are updated on the next call to World::Step.
Parameters
world The world in which the identified body's transform should be set.
id Identifier of body whose transform is to be set.
location Valid world location of the body's local origin.
angle Valid world rotation.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
SetTransformation()
void SetTransformation (World & world, BodyID id, const Transformation & value) related
Sets the transformation of the body.
This instantly adjusts the body to be at the new transformation.
Warning
Manipulating a body's transformation can cause non-physical behavior!
Note
Contacts are updated on the next call to World::Step.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
See also
GetTransformation(const World& world, BodyID id).
SetType()
void SetType (World & world, BodyID id, BodyType value, bool resetMassData = true) related
Sets the type of the given body.
Note
This may alter the body's mass and velocity.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid body identifier.
See also
GetType(const World& world, BodyID id), ResetMassData.
SetVelocity() [1/3]
void SetVelocity (World & world, BodyID id, AngularVelocity value) related
Sets the velocity of the identified body.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
SetVelocity() [2/3]
void SetVelocity (World & world, BodyID id, const LinearVelocity2 & value) related
Sets the velocity of the identified body.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
SetVelocity() [3/3]
void SetVelocity (World & world, BodyID id, const Velocity & value) related
Sets the body's velocity (linear and angular velocity).
Note
This method does nothing if this body is not speedable.
A non-zero velocity will awaken this body.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
See also
GetVelocity(BodyID), SetAwake, SetUnderActiveTime.
ShiftOrigin() [1/2]
void ShiftOrigin (World & world, const Length2 & newOrigin) related
Shifts the world origin.
Note
Useful for large worlds.
The body shift formula is: position -= newOrigin.
Postcondition
The "origin" of this world's bodies, joints, and the board-phase dynamic tree have been translated per the shift amount and direction.
Parameters
world The world whose origin should be shifted.
newOrigin the new origin with respect to the old origin
Exceptions
WrongState if this method is called while the world is locked.
ShiftOrigin() [2/2]
bool ShiftOrigin (World & world, JointID id, const Length2 & value) related
Shifts the origin of the identified joint.
Note
This only effects joints having points in world coordinates.
Exceptions
WrongState if this method is called while the world is locked.
std::out_of_range If given an invalid joint identifier.
Step()
StepStats Step (World & world, Time delta, TimestepIters velocityIterations = StepConf::DefaultRegVelocityIters, TimestepIters positionIterations = StepConf::DefaultRegPositionIters) related
Steps the world ahead by a given time amount.
Performs position and velocity updating, sleeping of non-moving bodies, updating of the contacts, and notifying the contact listener of begin-contact, end-contact, pre-solve, and post-solve events. If the given velocity and position iterations are more than zero, this method also respectively performs velocity and position resolution of the contacting bodies.
Note
While body velocities are updated accordingly (per the sum of forces acting on them), body positions (barring any collisions) are updated as if they had moved the entire time step at those resulting velocities. In other words, a body initially at p0 going v0 fast with a sum acceleration of a, after time t and barring any collisions, will have a new velocity (v1) of v0 + (a * t) and a new position (p1) of p0 + v1 * t.
Warning
Varying the time step may lead to non-physical behaviors.
Postcondition
Static bodies are unmoved.
Kinetic bodies are moved based on their previous velocities.
Dynamic bodies are moved based on their previous velocities, gravity, applied forces, applied impulses, masses, damping, and the restitution and friction values of their fixtures when they experience collisions.
Parameters
world World to step.
delta Time to simulate as a delta from the current state. This should not vary.
velocityIterations Number of iterations for the velocity constraint solver.
positionIterations Number of iterations for the position constraint solver. The position constraint solver resolves the positions of bodies that overlap.
Translate()
void Translate (World & world, ShapeID id, const Length2 & value) related
Translates all of the given shape's vertices by the given amount.
Note
This may throw std::bad_alloc or any exception that's thrown by the constructor for the model's underlying data type.
Exceptions
std::bad_alloc if there's a failure allocating storage.
std::out_of_range If given an invalid identifier.
UnsetAwake()
void UnsetAwake (World & world, BodyID id) related
Sleeps the identified body.
Note
This sleeps any associated contacts whose other body is also asleep.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
See also
IsAwake(const World& world, BodyID id), SetAwake(World& world, BodyID id).
UnsetEnabled()
void UnsetEnabled (World & world, ContactID id) related
Unsets the enabled status of the identified contact.
Exceptions
std::out_of_range If given an invalid contact identifier.
UnsetImpenetrable()
void UnsetImpenetrable (World & world, BodyID id) related
Unsets the impenetrable status of the identified body.
Exceptions
WrongState if this function is called while the world is locked.
std::out_of_range If given an invalid body identifier.
The documentation for this class was generated from the following files:
Library/include/playrho/d2/World.hpp
Library/include/playrho/d2/AABB.hpp
Library/include/playrho/d2/DistanceJointConf.hpp
Library/include/playrho/d2/FrictionJointConf.hpp
Library/include/playrho/d2/GearJointConf.hpp
Library/include/playrho/d2/MotorJointConf.hpp
Library/include/playrho/d2/PrismaticJointConf.hpp
Library/include/playrho/d2/PulleyJointConf.hpp
Library/include/playrho/d2/RayCastOutput.hpp
Library/include/playrho/d2/RevoluteJointConf.hpp
Library/include/playrho/d2/WeldJointConf.hpp
Library/include/playrho/d2/WheelJointConf.hpp
Library/include/playrho/d2/WorldBody.hpp
Library/include/playrho/d2/WorldContact.hpp
Library/include/playrho/d2/WorldJoint.hpp
Library/include/playrho/d2/WorldMisc.hpp
Library/include/playrho/d2/WorldShape.hpp
Library/source/playrho/d2/World.cpp
Library/source/playrho/d2/WorldSpecial.cpp