PlayRho: Units For Physical Quantities
Units For Physical Quantities
Units for expressing physical quantities like time and length.
Variables
constexpr auto playrho::CubicMeter = Meter * Meter * Meter
Cubic meter unit of volume.
constexpr auto playrho::Degree = Angle{Radian * Pi / Real{180}}
Degree unit of angle quantity.
constexpr auto playrho::DegreePerSecond = AngularVelocity{RadianPerSecond * Degree / Radian}
Degree per second unit of angular velocity.
constexpr auto playrho::DegreePerSquareSecond = Degree / (Second * Second)
Degree per square second unit of angular acceleration.
constexpr auto playrho::Hertz = Frequency(detail::hertz)
Hertz unit of Frequency.
constexpr auto playrho::Kilogram = Mass(detail::kilogram)
Kilogram unit of mass.
constexpr auto playrho::KilogramPerSquareMeter = AreaDensity(detail::kilogram_per_square_meter)
Kilogram per square meter unit of area density.
constexpr auto playrho::Meter = Length(detail::meter)
Meter unit of Length.
constexpr auto playrho::MeterPerSecond = LinearVelocity(detail::meter_per_second)
Meter per second unit of linear velocity.
constexpr auto playrho::MeterPerSquareSecond = LinearAcceleration(detail::meter_per_second_squared)
Meter per square second unit of linear acceleration.
constexpr auto playrho::Newton = Force(detail::newton)
Newton unit of force.
constexpr auto playrho::NewtonMeter = Torque(detail::newton_meter)
Newton meter unit of torque.
constexpr auto playrho::NewtonMeterSecond = NewtonMeter * Second
Newton meter second unit of angular momentum.
constexpr auto playrho::NewtonSecond = Newton * Second
Newton second unit of momentum.
constexpr auto playrho::Radian = Angle(detail::radian)
Radian unit of angle.
constexpr auto playrho::RadianPerSecond = AngularVelocity(detail::radian_per_second)
Radian per second unit of angular velocity.
constexpr auto playrho::RadianPerSquareSecond = Radian / (Second * Second)
Radian per square second unit of angular acceleration.
constexpr auto playrho::RevolutionsPerMinute = 2 * Pi * Radian / (Real{detail::SecondsPerMinute} * Second)
Revolutions per minute units of angular velocity.
constexpr auto playrho::Second = Time(detail::second)
Second unit of time.
constexpr auto playrho::SquareMeter = Area(detail::square_meter)
Square meter unit of area.
constexpr auto playrho::SquareRadian = Radian * Radian
Square radian unit type.
constexpr auto playrho::SquareSecond = Second * Second
Square second unit.
Detailed Description
Units for expressing physical quantities like time and length.
These are the unit definitions for expressing physical quantities like time and length. Conceptually a given unit is only usable with the quantities that are made up of the dimensions which the unit is associated with.
See also
Physical Quantity Types.
Variable Documentation
Degree
constexpr auto playrho::Degree = Angle{Radian * Pi / Real{180}} constexpr
Degree unit of angle quantity.
See also
Angle.
Radian.
Examples
WorldBody.cpp.
Referenced by playrho::literals::operator""_deg().
DegreePerSecond
constexpr auto playrho::DegreePerSecond = AngularVelocity{RadianPerSecond * Degree / Radian} constexpr
Degree per second unit of angular velocity.
See also
AngularVelocity.
Degree, Second.
DegreePerSquareSecond
constexpr auto playrho::DegreePerSquareSecond = Degree / (Second * Second) constexpr
Degree per square second unit of angular acceleration.
See also
AngularAcceleration.
Degree, Second.
Examples
WorldBody.cpp.
Hertz
constexpr auto playrho::Hertz = Frequency(detail::hertz) constexpr
Hertz unit of Frequency.
Represents the hertz unit of frequency (Hz).
See also
Frequency.
https://en.wikipedia.org/wiki/Hertz
Referenced by playrho::literals::operator""_Hz().
Kilogram
constexpr auto playrho::Kilogram = Mass(detail::kilogram) constexpr
Kilogram unit of mass.
Note
This is the SI base unit of mass.
See also
Mass.
https://en.wikipedia.org/wiki/Kilogram
Examples
WorldBody.cpp.
Referenced by playrho::d2::World::ComputeMassData(), playrho::d2::PrismaticJointConf::GetAngularReaction(), playrho::d2::RevoluteJointConf::GetAngularReaction(), playrho::d2::WeldJointConf::GetAngularReaction(), playrho::d2::ChainShapeConf::GetMassData(), playrho::d2::GetMassData(), playrho::d2::PrismaticJointConf::InitVelocity(), playrho::d2::RevoluteJointConf::InitVelocity(), playrho::d2::TargetJointConf::InitVelocity(), playrho::d2::WeldJointConf::InitVelocity(), playrho::literals::operator""_g(), playrho::literals::operator""_kg(), playrho::literals::operator""_Pg(), playrho::literals::operator""_Yg(), playrho::d2::GearJointConf::SolvePosition(), playrho::d2::PrismaticJointConf::SolvePosition(), playrho::d2::RevoluteJointConf::SolvePosition(), playrho::d2::WeldJointConf::SolvePosition(), playrho::d2::WheelJointConf::SolvePosition(), playrho::d2::GearJointConf::SolveVelocity(), playrho::d2::RevoluteJointConf::SolveVelocity(), and playrho::d2::WeldJointConf::SolveVelocity().
KilogramPerSquareMeter
constexpr auto playrho::KilogramPerSquareMeter = AreaDensity(detail::kilogram_per_square_meter) constexpr
Kilogram per square meter unit of area density.
See also
AreaDensity.
Referenced by playrho::literals::operator""_kgpm2().
Meter
constexpr auto playrho::Meter = Length(detail::meter) constexpr
Meter unit of Length.
A unit of the length quantity.
Note
This is the SI base unit of length.
See also
Length.
https://en.wikipedia.org/wiki/Metre
Examples
DistanceJoint.cpp, GearJoint.cpp, MotorJoint.cpp, PrismaticJoint.cpp, PulleyJoint.cpp, RevoluteJoint.cpp, WeldJoint.cpp, WheelJoint.cpp, World.cpp, and WorldBody.cpp.
Referenced by playrho::d2::GetManifold(), playrho::d2::GearJointConf::InitVelocity(), playrho::d2::PrismaticJointConf::InitVelocity(), playrho::literals::operator""_cm(), playrho::literals::operator""_dm(), playrho::literals::operator""_Gm(), playrho::literals::operator""_km(), playrho::literals::operator""_m(), playrho::literals::operator""_Mm(), playrho::d2::GearJointConf::SolvePosition(), playrho::d2::PrismaticJointConf::SolvePosition(), playrho::d2::WeldJointConf::SolvePosition(), playrho::d2::WheelJointConf::SolvePosition(), playrho::d2::PrismaticJointConf::SolveVelocity(), and playrho::d2::DistanceProxy::TestPoint().
MeterPerSecond
constexpr auto playrho::MeterPerSecond = LinearVelocity(detail::meter_per_second) constexpr
Meter per second unit of linear velocity.
See also
LinearVelocity.
Referenced by playrho::d2::GetContactRelVelocity(), playrho::literals::operator""_kps(), playrho::literals::operator""_mps(), playrho::d2::RevoluteJointConf::SolveVelocity(), and playrho::d2::WeldJointConf::SolveVelocity().
MeterPerSquareSecond
constexpr auto playrho::MeterPerSquareSecond = LinearAcceleration(detail::meter_per_second_squared) constexpr
Meter per square second unit of linear acceleration.
See also
LinearAcceleration.
Examples
DistanceJoint.cpp, RevoluteJoint.cpp, World.cpp, and WorldBody.cpp.
Referenced by playrho::literals::operator""_mps2().
Newton
constexpr auto playrho::Newton = Force(detail::newton) constexpr
Newton unit of force.
See also
Force.
Examples
PrismaticJoint.cpp, and WorldBody.cpp.
Referenced by playrho::literals::operator""_N().
NewtonMeter
constexpr auto playrho::NewtonMeter = Torque(detail::newton_meter) constexpr
Newton meter unit of torque.
See also
Torque.
Newton, Meter.
Examples
RevoluteJoint.cpp, and WheelJoint.cpp.
Referenced by playrho::literals::operator""_Nm().
NewtonMeterSecond
constexpr auto playrho::NewtonMeterSecond = NewtonMeter * Second constexpr
Newton meter second unit of angular momentum.
See also
AngularMomentum.
Newton, Meter, Second.
Examples
RevoluteJoint.cpp, and WorldBody.cpp.
NewtonSecond
constexpr auto playrho::NewtonSecond = Newton * Second constexpr
Newton second unit of momentum.
See also
Momentum.
Newton, Second.
Referenced by playrho::d2::PrismaticJointConf::GetLinearReaction(), playrho::d2::RevoluteJointConf::GetLinearReaction(), playrho::d2::WeldJointConf::GetLinearReaction(), playrho::d2::PrismaticJointConf::InitVelocity(), playrho::d2::RevoluteJointConf::InitVelocity(), playrho::d2::WeldJointConf::InitVelocity(), playrho::literals::operator""_Ns(), playrho::d2::PrismaticJointConf::SolveVelocity(), playrho::d2::RevoluteJointConf::SolveVelocity(), and playrho::d2::WeldJointConf::SolveVelocity().
Radian
constexpr auto playrho::Radian = Angle(detail::radian) constexpr
Radian unit of angle.
See also
Angle.
Degree.
Examples
WorldBody.cpp.
Referenced by playrho::d2::World::ApplyForce(), playrho::d2::Body::ApplyLinearImpulse(), playrho::Atan2(), playrho::d2::GearJointConf::GetAngularReaction(), playrho::d2::PrismaticJointConf::GetAngularReaction(), playrho::d2::RevoluteJointConf::GetAngularReaction(), playrho::d2::WeldJointConf::GetAngularReaction(), playrho::GetCircleVertices(), playrho::d2::GetContactRelVelocity(), playrho::d2::GetEffectiveInvMass(), playrho::d2::World::GetLinearVelocity(), playrho::d2::Body::GetLinearVelocityFromWorldPoint(), playrho::GetNormalized(), playrho::GetShortestDelta(), playrho::d2::DistanceJointConf::InitVelocity(), playrho::d2::FrictionJointConf::InitVelocity(), playrho::d2::GearJointConf::InitVelocity(), playrho::d2::MotorJointConf::InitVelocity(), playrho::d2::PrismaticJointConf::InitVelocity(), playrho::d2::PulleyJointConf::InitVelocity(), playrho::d2::RevoluteJointConf::InitVelocity(), playrho::d2::RopeJointConf::InitVelocity(), playrho::d2::TargetJointConf::InitVelocity(), playrho::d2::WeldJointConf::InitVelocity(), playrho::d2::WheelJointConf::InitVelocity(), playrho::literals::operator""_rad(), playrho::d2::World::SetForce(), playrho::d2::World::SetMassData(), playrho::d2::DistanceJointConf::SolvePosition(), playrho::d2::GearJointConf::SolvePosition(), playrho::d2::PrismaticJointConf::SolvePosition(), playrho::d2::PulleyJointConf::SolvePosition(), playrho::d2::RevoluteJointConf::SolvePosition(), playrho::d2::RopeJointConf::SolvePosition(), playrho::d2::WeldJointConf::SolvePosition(), playrho::d2::WheelJointConf::SolvePosition(), playrho::GaussSeidel::SolvePositionConstraint(), playrho::d2::DistanceJointConf::SolveVelocity(), playrho::d2::FrictionJointConf::SolveVelocity(), playrho::d2::GearJointConf::SolveVelocity(), playrho::d2::MotorJointConf::SolveVelocity(), playrho::d2::PrismaticJointConf::SolveVelocity(), playrho::d2::PulleyJointConf::SolveVelocity(), playrho::d2::RevoluteJointConf::SolveVelocity(), playrho::d2::RopeJointConf::SolveVelocity(), playrho::d2::TargetJointConf::SolveVelocity(), playrho::d2::WeldJointConf::SolveVelocity(), and playrho::d2::WheelJointConf::SolveVelocity().
RadianPerSecond
constexpr auto playrho::RadianPerSecond = AngularVelocity(detail::radian_per_second) constexpr
Radian per second unit of angular velocity.
See also
AngularVelocity.
Radian, Second.
Examples
PrismaticJoint.cpp, RevoluteJoint.cpp, WheelJoint.cpp, and WorldBody.cpp.
Referenced by playrho::d2::RevoluteJointConf::SolveVelocity(), and playrho::d2::WeldJointConf::SolveVelocity().
RadianPerSquareSecond
constexpr auto playrho::RadianPerSquareSecond = Radian / (Second * Second) constexpr
Radian per square second unit of angular acceleration.
See also
AngularAcceleration.
Radian, Second.
Examples
Body.cpp, DistanceJoint.cpp, RevoluteJoint.cpp, World.cpp, and WorldBody.cpp.
Referenced by playrho::d2::World::CalcGravitationalAcceleration().
RevolutionsPerMinute
constexpr auto playrho::RevolutionsPerMinute = 2 * Pi * Radian / (Real{detail::SecondsPerMinute} * Second) constexpr
Revolutions per minute units of angular velocity.
See also
AngularVelocity, Time
Minute.
Referenced by playrho::literals::operator""_rpm().
Second
constexpr auto playrho::Second = Time(detail::second) constexpr
Second unit of time.
Note
This is the SI base unit of time.
See also
Time.
https://en.wikipedia.org/wiki/Second
Examples
World.cpp.
Referenced by playrho::d2::PrismaticJointConf::GetAngularReaction(), playrho::d2::RevoluteJointConf::GetAngularReaction(), playrho::d2::WeldJointConf::GetAngularReaction(), playrho::d2::PrismaticJointConf::InitVelocity(), playrho::d2::RevoluteJointConf::InitVelocity(), playrho::d2::TargetJointConf::InitVelocity(), playrho::d2::WeldJointConf::InitVelocity(), playrho::literals::operator""_d(), playrho::literals::operator""_h(), playrho::literals::operator""_min(), playrho::literals::operator""_s(), playrho::d2::RevoluteJointConf::SolveVelocity(), and playrho::d2::WeldJointConf::SolveVelocity().
SquareMeter
constexpr auto playrho::SquareMeter = Area(detail::square_meter) constexpr
Square meter unit of area.
See also
Area.
Examples
WorldBody.cpp.
Referenced by playrho::ComputeCentroid(), playrho::d2::Simplex::Get(), playrho::d2::PrismaticJointConf::GetAngularReaction(), playrho::d2::RevoluteJointConf::GetAngularReaction(), playrho::d2::WeldJointConf::GetAngularReaction(), playrho::d2::VertexSet::GetDefaultMinSeparationSquared(), playrho::GetPolarMoment(), playrho::d2::PrismaticJointConf::InitVelocity(), playrho::d2::RevoluteJointConf::InitVelocity(), playrho::d2::WeldJointConf::InitVelocity(), playrho::literals::operator""_m2(), playrho::d2::DistanceProxy::RayCast(), playrho::d2::RayCast(), playrho::d2::PrismaticJointConf::SolvePosition(), playrho::d2::RevoluteJointConf::SolvePosition(), playrho::d2::WeldJointConf::SolvePosition(), playrho::d2::RevoluteJointConf::SolveVelocity(), and playrho::d2::WeldJointConf::SolveVelocity().
SquareRadian
constexpr auto playrho::SquareRadian = Radian * Radian constexpr
Square radian unit type.
See also
Angle.
Radian.
Examples
Body.cpp, FrictionJoint.cpp, MotorJoint.cpp, RevoluteJoint.cpp, WeldJoint.cpp, and WorldBody.cpp.
Referenced by playrho::d2::TargetJointConf::GetEffectiveMassMatrix(), playrho::d2::Body::GetLocalRotInertia(), playrho::d2::World::GetLocalRotInertia(), playrho::d2::GetMassData(), playrho::d2::FrictionJointConf::InitVelocity(), playrho::d2::GearJointConf::InitVelocity(), playrho::d2::MotorJointConf::InitVelocity(), playrho::d2::PrismaticJointConf::InitVelocity(), playrho::d2::PulleyJointConf::InitVelocity(), playrho::d2::WheelJointConf::InitVelocity(), playrho::d2::World::SetMassData(), playrho::d2::PrismaticJointConf::SolvePosition(), playrho::d2::PulleyJointConf::SolvePosition(), playrho::d2::RevoluteJointConf::SolvePosition(), and playrho::d2::WheelJointConf::SolvePosition().
SquareSecond
constexpr auto playrho::SquareSecond = Second * Second constexpr
Square second unit.
See also
Second
Examples
WorldBody.cpp.