PlayRho: Math Functions For Checked Types
Math Functions For Checked Types
Common Mathematical Functions For Checked Types.
Functions
template<class ValueType , class Checker , bool NoExcept>
auto playrho::detail::abs (const Checked< ValueType, Checker, NoExcept > &arg) -> decltype(Checked< ValueType, Checker, false >(abs(arg.get())))
Computes the absolute value.
template<class ValueType , class Checker , bool NoExcept>
auto playrho::detail::nextafter (const Checked< ValueType, Checker, NoExcept > &from, const Checked< ValueType, Checker, NoExcept > &to) -> decltype(Checked< ValueType, Checker, false >(nextafter(from.get(), to.get())))
Next after function.
Detailed Description
Common Mathematical Functions For Checked Types.
See also
Checked
https://en.cppreference.com/w/cpp/numeric/math
Function Documentation
abs()
template<class ValueType , class Checker , bool NoExcept> auto playrho::detail::abs (const Checked< ValueType, Checker, NoExcept > & arg) -> decltype(Checked<ValueType, Checker, false>(abs(arg.get())))
Computes the absolute value.
See also
https://en.cppreference.com/w/cpp/numeric/math/fabs
nextafter()
template<class ValueType , class Checker , bool NoExcept> auto playrho::detail::nextafter (const Checked< ValueType, Checker, NoExcept > & from, const Checked< ValueType, Checker, NoExcept > & to) -> decltype(Checked<ValueType, Checker, false>(nextafter(from.get(), to.get())))
Next after function.
See also
https://en.cppreference.com/w/cpp/numeric/math/nextafter
Examples
World.cpp.
Referenced by playrho::AlmostEqual(), playrho::d2::UnitVec::Get(), playrho::ToiOutput::GetToiViaSat(), playrho::StepConf::IsMaxTranslationWithinTolerance(), playrho::detail::UnitMagnitudeChecker< T >::operator()(), and playrho::d2::DistanceProxy::RayCast().