PlayRho: playrho::d2::part Namespace Reference
playrho::d2::part Namespace Reference
Classes
class Compositor
A class template for compositing shaped part types eligible for use with classes like the playrho::d2::Shape class.
struct DefaultPolicies
Default policy class implementations for the Compositor host class template.
struct DefaultPolicyArgs
Default policy arguments for the Compositor template class.
struct DensityIs
Sets the implementing class of the Compositor density policy.
struct Discriminator
"Discriminator" for named template arguments.
struct DynamicAreaDensity
Dynamic area density policy class.
struct DynamicFilter
Dynamic filter policy class.
struct DynamicFriction
Dynamic friction.
class DynamicRectangle
Dynamic rectangle.
struct DynamicRestitution
Dynamic restitution policy class.
struct DynamicSensor
Dynamic sensor policy class.
struct FilterIs
Sets the implementing class of the Compositor filter policy.
struct FrictionIs
Sets the implementing class of the Compositor friction policy.
struct GeometryIs
Sets the implementing class of the Compositor geometry policy.
struct PolicySelector
Policy selector for named template arguments for the Compositor host class template.
struct RestitutionIs
Sets the implementing class of the Compositor restitution policy.
struct SensorIs
Sets the implementing class of the Compositor sensor policy.
struct StaticAreaDensity
Static area density policy class.
struct StaticFilter
Static filter policy class.
struct StaticFriction
Static friction.
class StaticRectangle
Static rectangle.
struct StaticRestitution
Static restitution policy class.
struct StaticSensor
Static sensor policy class.
struct StaticTenthsFriction
Static tenths friction.
Functions
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto GetChild (const Compositor< P1, P2, P3, P4, P5, P6 > &arg, ChildCounter index) noexcept(noexcept(arg.GetChild(index))) -> decltype(arg.GetChild(index))
Gets the "child" shape for the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
constexpr auto GetChildCount (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept -> decltype(arg.GetChildCount())
Gets the "child" count for the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
constexpr auto GetDensity (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept -> decltype(arg.density)
Gets the density of the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
constexpr auto GetDimensions (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept -> decltype(arg.GetDimensions())
Gets the rectangle's width and height dimensions.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
constexpr auto GetFilter (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept -> decltype(arg.filter)
Gets the filter of the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
constexpr auto GetFriction (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept -> decltype(arg.friction)
Gets the friction of the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto GetMassData (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept -> decltype(arg.GetMassData(GetDensity(arg)))
Gets the mass data for the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
constexpr auto GetOffset (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept -> decltype(arg.GetOffset())
Gets the rectangle's x and y offset.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
constexpr auto GetRestitution (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept -> decltype(arg.restitution)
Gets the restitution of the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
constexpr auto GetVertexRadius (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept(noexcept(arg.GetVertexRadius())) -> decltype(arg.GetVertexRadius())
Gets the vertex radius of the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto GetVertexRadius (const Compositor< P1, P2, P3, P4, P5, P6 > &arg, ChildCounter index) noexcept(noexcept(GetChild(arg, index))) -> decltype(GetVertexRadius(GetChild(arg, index)))
Gets the vertex radius of the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
constexpr auto IsSensor (const Compositor< P1, P2, P3, P4, P5, P6 > &arg) noexcept -> decltype(arg.sensor)
Gets the is-sensor state of the given shape configuration.
template<class P11 , class P12 , class P13 , class P14 , class P15 , class P16 , class P21 , class P22 , class P23 , class P24 , class P25 , class P26 >
bool operator!= (const Compositor< P11, P12, P13, P14, P15, P16 > &lhs, const Compositor< P21, P22, P23, P24, P25, P26 > &rhs) noexcept
Inequality operator.
template<class P11 , class P12 , class P13 , class P14 , class P15 , class P16 , class P21 , class P22 , class P23 , class P24 , class P25 , class P26 >
bool operator== (const Compositor< P11, P12, P13, P14, P15, P16 > &lhs, const Compositor< P21, P22, P23, P24, P25, P26 > &rhs) noexcept
Equality operator.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto Rotate (Compositor< P1, P2, P3, P4, P5, P6 > &arg, ::playrho::d2::UnitVec value) -> decltype(arg.Rotate(value))
Rotates the given compositor's vertices by the given value.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , std::size_t N>
auto Scale (Compositor< P1, P2, P3, P4, P5, P6 > &arg, const Vector< Real, N > &value) -> decltype(arg.Scale(value))
Scales the given compositor's vertices by the given value.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto SetDensity (Compositor< P1, P2, P3, P4, P5, P6 > &arg, NonNegative< AreaDensity > value) -> std::enable_if_t<!std::is_const_v< decltype(arg.density)>, void >
Density setter.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto SetDimensions (Compositor< P1, P2, P3, P4, P5, P6 > &arg, decltype(arg.GetDimensions()) value) -> decltype(arg.SetDimensions(value))
Sets the rectangle's width and height dimensions.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto SetFilter (Compositor< P1, P2, P3, P4, P5, P6 > &arg, Filter value) -> std::enable_if_t<!std::is_const_v< decltype(arg.filter)>, void >
Filter setter.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto SetFriction (Compositor< P1, P2, P3, P4, P5, P6 > &arg, NonNegative< Real > value) -> std::enable_if_t<!std::is_const_v< decltype(arg.friction)>, void >
Sets friction.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto SetOffset (Compositor< P1, P2, P3, P4, P5, P6 > &arg, decltype(arg.GetOffset()) value) -> decltype(arg.SetOffset(value))
Sets the rectangle's x and y offset.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto SetRestitution (Compositor< P1, P2, P3, P4, P5, P6 > &arg, Real value) -> std::enable_if_t<!std::is_const_v< decltype(arg.restitution)>, void >
Sets restitution.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto SetSensor (Compositor< P1, P2, P3, P4, P5, P6 > &arg, bool value) -> std::enable_if_t<!std::is_const_v< decltype(arg.sensor)>, void >
Sensor setter.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
auto SetVertexRadius (Compositor< P1, P2, P3, P4, P5, P6 > &arg, ChildCounter index, decltype(arg.GetVertexRadius()) value) -> decltype(arg.SetVertexRadius(index, value))
Gets the vertex radius of the given shape configuration.
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , std::size_t N>
auto Translate (Compositor< P1, P2, P3, P4, P5, P6 > &arg, const Vector< Length, N > &value) -> decltype(arg.Translate(value))
Translates the given compositor's vertices by the given value.
Detailed Description
Name space for parts attached to bodies and support for those parts.
Function Documentation
GetChild()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto GetChild (const Compositor< P1, P2, P3, P4, P5, P6 > & arg, ChildCounter index) -> decltype(arg.GetChild(index)) noexcept
Gets the "child" shape for the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name.
Examples
Compositor.cpp.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::GetVertexRadius(), and playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::operator==().
GetChildCount()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > constexpr auto GetChildCount (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.GetChildCount()) constexpr noexcept
Gets the "child" count for the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name.
Examples
Compositor.cpp.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::operator==().
GetDensity()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > constexpr auto GetDensity (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.density) constexpr noexcept
Gets the density of the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name.
Examples
Compositor.cpp.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::GetMassData(), and playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::operator==().
GetDimensions()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > constexpr auto GetDimensions (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.GetDimensions()) constexpr noexcept
Gets the rectangle's width and height dimensions.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name.
Examples
Compositor.cpp.
GetFilter()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > constexpr auto GetFilter (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.filter) constexpr noexcept
Gets the filter of the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::operator==().
GetFriction()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > constexpr auto GetFriction (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.friction) constexpr noexcept
Gets the friction of the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name.
Examples
Compositor.cpp.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::operator==().
GetMassData()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto GetMassData (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.GetMassData(GetDensity(arg))) noexcept
Gets the mass data for the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name.
Examples
Compositor.cpp.
GetOffset()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > constexpr auto GetOffset (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.GetOffset()) constexpr noexcept
Gets the rectangle's x and y offset.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name.
Examples
Compositor.cpp.
GetRestitution()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > constexpr auto GetRestitution (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.restitution) constexpr noexcept
Gets the restitution of the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name.
Examples
Compositor.cpp.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::operator==().
GetVertexRadius() [1/2]
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > constexpr auto GetVertexRadius (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.GetVertexRadius()) constexpr noexcept
Gets the vertex radius of the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name.
Examples
Compositor.cpp.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::GetVertexRadius().
GetVertexRadius() [2/2]
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto GetVertexRadius (const Compositor< P1, P2, P3, P4, P5, P6 > & arg, ChildCounter index) -> decltype(GetVertexRadius(GetChild(arg, index))) noexcept
Gets the vertex radius of the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name.
IsSensor()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > constexpr auto IsSensor (const Compositor< P1, P2, P3, P4, P5, P6 > & arg) -> decltype(arg.sensor) constexpr noexcept
Gets the is-sensor state of the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name.
Referenced by playrho::d2::part::Compositor< P1, P2, P3, P4, P5, P6 >::operator==().
Rotate()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto Rotate (Compositor< P1, P2, P3, P4, P5, P6 > & arg, ::playrho::d2::UnitVec value) -> decltype(arg.Rotate(value))
Rotates the given compositor's vertices by the given value.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name and accepting the given value.
Examples
Compositor.cpp.
Scale()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , std::size_t N> auto Scale (Compositor< P1, P2, P3, P4, P5, P6 > & arg, const Vector< Real, N > & value) -> decltype(arg.Scale(value))
Scales the given compositor's vertices by the given value.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name and accepting the given value.
Examples
Compositor.cpp.
SetDensity()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto SetDensity (Compositor< P1, P2, P3, P4, P5, P6 > & arg, NonNegative< AreaDensity > value) -> std::enable_if_t<!std::is_const_v<decltype(arg.density)>, void>
Density setter.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name and accepting the given value.
Examples
Compositor.cpp.
SetDimensions()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto SetDimensions (Compositor< P1, P2, P3, P4, P5, P6 > & arg, decltype(arg.GetDimensions()) value) -> decltype(arg.SetDimensions(value))
Sets the rectangle's width and height dimensions.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name and accepting the given value.
Examples
Compositor.cpp.
SetFilter()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto SetFilter (Compositor< P1, P2, P3, P4, P5, P6 > & arg, Filter value) -> std::enable_if_t<!std::is_const_v<decltype(arg.filter)>, void>
Filter setter.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name and accepting the given value.
Examples
Compositor.cpp.
SetFriction()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto SetFriction (Compositor< P1, P2, P3, P4, P5, P6 > & arg, NonNegative< Real > value) -> std::enable_if_t<!std::is_const_v<decltype(arg.friction)>, void>
Sets friction.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name and accepting the given value.
Examples
Compositor.cpp.
SetOffset()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto SetOffset (Compositor< P1, P2, P3, P4, P5, P6 > & arg, decltype(arg.GetOffset()) value) -> decltype(arg.SetOffset(value))
Sets the rectangle's x and y offset.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name and accepting the given value.
Examples
Compositor.cpp.
SetRestitution()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto SetRestitution (Compositor< P1, P2, P3, P4, P5, P6 > & arg, Real value) -> std::enable_if_t<!std::is_const_v<decltype(arg.restitution)>, void>
Sets restitution.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name and accepting the given value.
Examples
Compositor.cpp.
SetSensor()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto SetSensor (Compositor< P1, P2, P3, P4, P5, P6 > & arg, bool value) -> std::enable_if_t<!std::is_const_v<decltype(arg.sensor)>, void>
Sensor setter.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member variable of this same name and accepting the given value.
Examples
Compositor.cpp.
SetVertexRadius()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > auto SetVertexRadius (Compositor< P1, P2, P3, P4, P5, P6 > & arg, ChildCounter index, decltype(arg.GetVertexRadius()) value) -> decltype(arg.SetVertexRadius(index, value))
Gets the vertex radius of the given shape configuration.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name and accepting the given index and value.
Examples
Compositor.cpp.
Translate()
template<class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , std::size_t N> auto Translate (Compositor< P1, P2, P3, P4, P5, P6 > & arg, const Vector< Length, N > & value) -> decltype(arg.Translate(value))
Translates the given compositor's vertices by the given value.
Note
By way of SFINAE, this function is only available from overload resolution for objects having a member function of this same name and accepting the given value.
Examples
Compositor.cpp.